### PR TITLE
fix heap allocators when shrinking an object but growing its alignment

### PR DESCRIPTION
**Pull request by squeek502**
This is the same fix as https://github.com/andrewrk/zig-general-purpose-allocator/pull/3 but for the std heap allocators.

Before the changes in this PR, the added test case would fail for each of the allocators with a stack trace like:

```
Test 3/6 ArenaAllocator...reached unreachable code
/home/ryan/Programming/zig/zig/build/lib/zig/std/debug.zig:169:14: 0x20402c in ??? (test)
    if (!ok) unreachable; // assertion failure
             ^
/home/ryan/Programming/zig/zig/build/lib/zig/std/mem.zig:231:11: 0x20bb05 in ??? (test)
    assert(dest.len >= source.len);
          ^
/home/ryan/Programming/zig/zig/build/lib/zig/std/heap.zig:258:25: 0x2099d3 in ??? (test)
                mem.copy(u8, result, old_mem);
                        ^
```

### CODE REVIEW

**Comment by squeek502** [comment]
Looks like there's a few more things to fix for this PR:
- Windows is tripping [this assertion](https://github.com/ziglang/zig/blob/053bdfc7e348d0e5547ab1d4f53bf21f2b1b09fa/std/heap.zig#L167) in the new test
- Linux/Mac are failing the FixedBufferAllocator test with OutOfMemory:
  + Mac: `Test 42/779 heap.std-macosx-x86_64-Debug-c-multi FixedBufferAllocator...error: OutOfMemory`
  + Linux: `Test 42/781 heap.std-linux-x86_64-Debug-c-single FixedBufferAllocator...error: OutOfMemory`
  + Possibly due to [this loop](https://github.com/ziglang/zig/pull/2312/files#diff-1af05a4c80f24b620ba7851630de5ea8R734) which was copied from [this GPDA test](https://github.com/andrewrk/zig-general-purpose-allocator/blob/master/gpda.zig#L994-L1007) to ensure that the slice we are `realloc`ing is not already aligned to the new alignment (because that would circumvent the code the test cares about triggering)

**Comment by andrewrk** [comment]
Nice! I'll find some time tomorrow to go over this.

**Comment by squeek502** [comment]
Fixed the issues in https://github.com/ziglang/zig/pull/2312#issuecomment-485061982. This is ready for review.

**Comment by andrewrk** [comment]
Looks good! I'd probably use `std.math.min` rather than an `if` but it's more of a style thing, not important. Thanks for the fix.

**Comment by squeek502** [comment]
> Looks good! I'd probably use `std.math.min` rather than an `if` but it's more of a style thing, not important. Thanks for the fix.

The only reason I didn't do that is that it was using `mem.copy` so I thought it made sense to keep using that where possible. Wasn't sure if switching everything over to `@memcpy` made sense or not.

**Pull request merged**
