### PR TITLE
std.math: port `int_log10` from Rust

### PR DESCRIPTION
**Pull request by adriandelgado**
A straight forward port of `int_log10` from the [Rust standard library](https://github.com/rust-lang/rust/blob/f63ccaf25f74151a5d8ce057904cd944074b01d2/library/core/src/num/int_log10.rs), including tests.

In theory, this makes it possible to  _accurately_ compute `log10` of any integer, from `u1` to `u65535`. However, due to a [compiler bug](https://github.com/ziglang/zig/issues/14816), currently it only gives accurate results up to `u136`.

Even with limitations, the proposed implementation it's an improvement because currently the compiler segfaults when trying to use integers bigger than `u128` and gives wrong results even when it works.

I've been learning Zig for 2 weeks, sorry for any mistakes or non idiomatic code.

### CODE REVIEW

**Comment by jedisct1** [comment]
Incidentally, that bug appears to be fixed :) https://github.com/jacobly0/zig/commit/c1d16a2b80e258a126ed496dab09a8a7c26f8468

**Comment by adriandelgado** [comment]
Those are some interesting resources for further optimizations, I wasn't aware of them.

Also, I wanted to improve `@log10` to accept integers too because of #13642, but that is a more difficult task for a noob (too much compiler internals).

Seeing how this PR fails a lot of tests, postponing `@log10` was the right call.

**Comment by adriandelgado** [comment]
Due to #14816 being fixed I rebased and cleaned the history to try again. I also increased the test cases up to `u512` which should be possible now.

**Comment by adriandelgado** [comment]
It seems like only the LLVM backend can divide big ints for now...

**Comment by adriandelgado** [comment]
I skipped some tests similar to #14482

**Pull request merged**
