### PR TITLE
Synchronize what gets compiled into `libc_nonshared.a` with glibc

### PR DESCRIPTION
**Pull request by lifthrasiir**
In lieu of #16152, I tried to compile every glibc version from 2.32 to 2.38 (the most recent) to see any differences. It turns out that recent changes to `glibc.zig` didn't take account of Makefile changes, and #16152 was only a symptom of this broader issue. This PR updates `glibc.zig` to take account for the following:

* 2.33 moved all statically linked `stat` functions from `libc_nonshared.a` to `libc.so`, using the usual ELF symbol versioning. In fact, AFAIK the ELF symbol versioning *was* a response to the experience from `libc_nonshared.a` (which can technically violate ODR), and these were the last functions to adapt it. (bminor/glibc@8ed005daf0ab03e142500324a34087ce179ae78e, bminor/glibc@589260cef8c2090d67d3deaa0a9ffa61c96de951, bminor/glibc@4d97cc8cf3da925fd06fc37d4daebafce3247719, bminor/glibc@99468ed45f5a58f584bab60364af937eb6f8afda)
    * Therefore 19ca2415f26b07b399a60fd17a4cf85f290da0fd should be reverted, because 2.32 was the last version that those functions were present in `libc_nonshared.a`. 3dcd3612dca6f649a1e05f558c5d6ed462d2e4a4 can be also safely reverted (they were a simple portable redirection before 2.33).
    * In addition, those added files depended on [`glibc/include/errno.h`](https://github.com/bminor/glibc/blob/glibc-2.34/include/errno.h) among others to access `__libc_errno`. But it is defined from `libc.so`, so [`glibc/csu/errno.c`](https://github.com/bminor/glibc/blob/glibc-2.34/csu/errno.c) should not be added.
* `-DSHARED` option only applies to `*.os` files, i.e. objects compiled into `libc.so`. `*.oS` (note the capital `S`) files for `libc_nonshared.a` never needed them and I've verified that glibc 2.32 only passes `-DLIBC_NONSHARED=1` for all `*.oS` files.
    * It seems that 6a12dce207114842e2e49a3aeb18af01ab207f0b was a mistake due to the missed 2.33 change, so it should be reverted.
* I believe 2.34 is the latest glibc version with non-code changes to `libc_nonshared.a`. I've checked remaining 4 objects; they all agree with the shipped version except for header inlining.

Now, given this PR deals with multiple glibc versions, I couldn't fully test it. I did however test:

* That `zig cc -target x86_64-linux-gnu.2.31` still compiles `libc_nonshared.a` with all stat functions but no `errno.o` and correctly produces a working shared object for the original example.
* That `zig cc -target x86_64-linux-gnu.2.34` compiles `libc_nonshared.a` with only 4 object files remaining since 2.34. I don't have any Linux environment with glibc 2.32 or later so I couldn't directly test it, but at least it correctly compiles with a `stat@plt` trampoline (as opposed to `__xstat@plt`) to the `stat@GLIBC_2.33` symbol.
* That `ci/x86_64-linux-release.sh` successfully passes. This covers any unintentional changes for non-glibc targets. I intended to produce a full distribution suitable for zig-pypi, so I took some more time.

Any additional verification for other glibc versions and `test-std` against them would be appreciated.

### CODE REVIEW

**Comment by squeek502** [comment]
This may also fix https://github.com/ziglang/zig/issues/17034. Similar attempt at the same thing: https://github.com/ziglang/zig/pull/17521

glibc headers got updated in https://github.com/ziglang/zig/pull/17489

**Comment by andrewrk** [comment]
This is great work! Thanks for doing this. I'm sorry that I did not look at this pull request until now. Are you willing to do the work of rebasing it? If so, let me know. Otherwise, I'll get to it over the next week or so.

**Comment by lifthrasiir** [comment]
> I'm sorry that I did not look at this pull request until now.

Oh, it took me a few days to notice this reply as well, don't mind :-)

I'll try to rebase the PR this weekend. If I were not able to do that, you may ignore me and pick this up.

**Review by rootbeer — COMMENTED** [review]
Looks great to me.  Nice cleanup in glibc.zig.

**Comment by rootbeer** [comment]
I reproduced the test failures locally on this PR.  Its failing to compile the new files when they're used (so the zig build itself works, but building a gnu-libc test case fails):

```
$ ./build/stage4/bin/zig run ../playground/confused-tls.zig -lc -target native-native-gnu
error(compilation): clang failed with stderr: lib/libc/glibc/io/mknod-2.32.c:55:35: error: expected function body after function declarator

error(compilation): clang failed with stderr: lib/libc/glibc/io/lstat-2.32.c:55:35: error: expected function body after function declarator

error(compilation): clang failed with stderr: lib/libc/glibc/io/stat-2.32.c:54:33: error: expected function body after function declarator

error(compilation): clang failed with stderr: lib/libc/glibc/io/fstat-2.32.c:55:35: error: expected function body after function declarator

error: sub-compilation of glibc libc_nonshared.a failed
    lib/libc/glibc/io/mknod-2.32.c:1:1: note: unable to build C object: clang exited with code 1
    lib/libc/glibc/io/lstat-2.32.c:1:1: note: unable to build C object: clang exited with code 1
    lib/libc/glibc/io/stat-2.32.c:1:1: note: unable to build C object: clang exited with code 1
    lib/libc/glibc/io/fstat-2.32.c:1:1: note: unable to build C object: clang exited with code 1
error: unable to build glibc CRT file: SubCompilationFailed
```

The line its complaining about is:
```
weak_hidden_alias (__mknod, mknod)
```

From what I can tell (manually running the compile command with `-E`), this line isn't gettting expanded by a macro....   Probably there is some (missing) change between the official v2.32 glibc headers and the ... "custom" headers Zig has ...

Yeah, "weak_hidden_alias" (and a bunch of other macros) were removed from glibc's include/libc-symbols.h in 2022: in https://sourceware.org/git/?p=glibc.git;a=blobdiff;f=include/libc-symbols.h;h=f4437ff6ad770ce79b4beefe08cb9adfa0b6e6da;hp=4fde8394718454d9e11a6485155fa4e7c83922fb;hb=62595e89447c09fe4e34cd9fc1d4cf1b7f3ecb33;hpb=8ee2c043cfb35c48b45c7c5aed4022a8a7352bdc

I'll poke around and see if changing "weak_hidden_alias()" to something else, or putting the header definitions back in makes sense.   I may be off base on this, though.

**Comment by lifthrasiir** [comment]
> Yeah, "weak_hidden_alias" (and a bunch of other macros) were removed from glibc's include/libc-symbols.h in 2022: in https://sourceware.org/git/?p=glibc.git;a=blobdiff;f=include/libc-symbols.h;h=f4437ff6ad770ce79b4beefe08cb9adfa0b6e6da;hp=4fde8394718454d9e11a6485155fa4e7c83922fb;hb=62595e89447c09fe4e34cd9fc1d4cf1b7f3ecb33;hpb=8ee2c043cfb35c48b45c7c5aed4022a8a7352bdc

Oops, yeah, I wasn't paying attention (my local LLVM compilation is currently out of date, so I only checked histories of conflicting files). I agree that simply reviving `weak_hidden_alias` and `_weak_hidden_alias` seems the plausible solution. They essentially define three or four attributes:

* [`__attribute__((weak))`](https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#index-weak-function-attribute) and [`__attribute__((alias("...")))`](https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#index-alias-function-attribute) should work in any glibc targets (or have common workarounds that don't need additional changes) as it is also a part of the `weak_alias` macro.
* [`__attribute__((visibility("hidden")))`](https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#index-visibility-function-attribute) seems to be similar. It's used by the `attribute_hidden` macro, which is enabled when `SHARED` is turned on. So we should be safe unless there is some weird target where only a statically linked glibc is available, in which case we don't need `libc_nonshared.a` at all.
* [`__attribute__((copy(...)))`](https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#index-copy-function-attribute) is indirectly enabled via the `__attribute_copy__` macro in `cdefs.h` for GCC 9+. Assuming `__attribute__((alias))` works, this should be safe.

**Comment by rootbeer** [comment]
Pasting the old definitions of `weak_hidden_alias` back into the libc-symbols.h header seems to fix the problem.  Thanks for the pointers. 

The patch is available at https://github.com/ziglang/zig/commit/c76fbfa2ed2aee93c08497b4f1ae8567b70fdc60  But its just this diff for libc-symbols.h:
```
/* Zig patch.  weak_hidden_alias was removed from glibc v2.36 (v2.37?), Zig
   needs it for the v2.32 and earlier {f,l,}stat wrappers, so only include
   in this header for 2.32 and earlier. */
#if (__GLIBC__ == 2 && __GLIBC_MINOR__ <= 32) || __GLIBC__ < 2
# define weak_hidden_alias(name, aliasname) \
  _weak_hidden_alias (name, aliasname)
# define _weak_hidden_alias(name, aliasname) \
  extern __typeof (name) aliasname \
    __attribute__ ((weak, alias (#name), __visibility__ ("hidden"))) \
    __attribute_copy__ (name);
#endif
```

I wasn't sure if I should push something, or wait for one of you to cherry-pick into this tree.  Just redoing the patch is fine with me too.

**Comment by rootbeer** [comment]
I also noticed a test is disabled because of the bug this PR is fixing, so that is probably worth enabling in this stack.  There is at least: https://github.com/jacobly0/zig/commit/01f9cdd21a8f18941636c061a5985a040e4a4bcd (a quick search found no others).

**Comment by andrewrk** [comment]
Work is continuing at #17702

**Pull request closed without merging**
