### PR TITLE
Add lower and upper functions

### PR DESCRIPTION
**Pull request by isaachier**

### CODE REVIEW

**Comment by BarabasGitHub** [comment]
This only works for ASCII.

**Comment by thejoshwolfe** [comment]
This has been discussed before (#891 #893). The tldr is that unicode manipulation functions like this are too hard to do correctly, and users should look to using ICU directly instead of the zig standard library.

Once zig is more mature and serious apps have been written in zig that handle unicode properly, we may revisit this decision. But in the meantime, i know enough about unicode to know not to attempt to support this outside of ICU.

**Comment by isaachier** [comment]
Understood. Honestly, this started as simple ASCII upper/lower functions but I guess the answer is to use C's ctype or ICU for unicode?

**Comment by isaachier** [comment]
I don't mean ICU specifically, just wondering if there is a need for `toLower`/`toUpper`/`isLower`/`isUpper`/`eqlIgnoreCase` for ASCII in Zig. I tried using `@cInclude("ctype.h");` but (in hindsight obvious) got a linking error. Zig itself has no equivalent functions at the moment

**Pull request closed without merging**
