### PR TITLE
autodoc: use commonmark.js for Markdown rendering

### PR DESCRIPTION
**Pull request by ianprime0509**
This allows doc comments to use a wider range of Markdown syntax, such as list items spanning multiple lines. Since commonmark.js is already being used to render guide content, this also does not need to introduce a new dependency.

### CODE REVIEW

**Comment by andrewrk** [comment]
I don't think autodocs should depend on a third party markdown implementation. It should be zig autodocs-flavored markdown so that it can properly link to stuff without awkward glue code between autodocs and the markdown implementation.

Also there are markdown features that may be better to not support, or features that are not officially supported by markdown.

**Comment by ianprime0509** [comment]
That's fair, bloat is certainly a concern considering commonmark.js is more than twice the size (in lines) than the Autodoc `main.js`, which is disproportionate given their roles in the project. Having attempted (and failed) to write a Commonmark parser myself several years ago, I agree that there's a lot of complexity that could be avoided by a simpler standard without losing a lot of expressive power.

Should I close this PR, or did you leave it open for further feedback?

I could instead make an attempt at updating the existing parser to handle the case that originally motivated this change, which was
```md
- List item 1
- List item 2 spanning multiple lines, but the subsequent lines
  are treated as a separate paragraph.
```

**Comment by matklad** [comment]
>I agree that there's a lot of complexity that could be avoided by a simpler standard without losing a lot of expressive power.

FWIW, [djot](https://djot.net) (by John MacFarlane of https://spec.commonmark.org/0.30/ and https://github.com/jgm/pandoc) is a strong contender for such a standard. It's not yet 1.0, so I won't recommend it just now, but there's a chance that it matures enough by Zig's own 1.0.

**Comment by kristoff-it** [comment]
After discussing this with Andrew we agreed to move forward with the CommonMark parser for now and to replace it with something better (ie custom written) eventually.

**Pull request merged**
