### PR TITLE
cmake: add `ZIG_BUILD_ARGS_OVERRIDE` string option

### PR DESCRIPTION
**Pull request by BratishkaErik**
Useful when someone wants to pass argument that is not yet exposed to CMake via "ZIG_WHATEVER" option, for example "--search-prefix" from here: https://github.com/ziglang/zig/issues/18434 .

Also change order of arguments in cmake/install.cmake to be the same as in CMakeLists.txt, so that "--prefix" can be overriden in both steps.

Also bump minimum CMake version to "3.9".

### CODE REVIEW

**Comment by BratishkaErik** [comment]
Forgot to bump CMake version in README, fixed now.

**Comment by andrewrk** [comment]
why do you need to override arbitrary arguments? it does not specify intent clearly enough.

**Comment by BratishkaErik** [comment]
> why do you need to override arbitrary arguments? it does not specify intent clearly enough.

For example, to pass "-Ddebug_extensions" to zig2 when building stage3. This way, we don't need to spend extra time building stage4, since all args are used together in one step (stage3).

Or if someone can't even build stage3, like in mentioned issue.

**Comment by erikarvstedt** [comment]
You can build just stage 2 with `make zig2` (when using the makefile generator).

Maybe [this simpler approach](https://github.com/erikarvstedt/zig/commit/7faafa8adcc4ee008a5a0c9cd55b241c3c0d87a8), which adds var `ZIG_EXTRA_BUILD_ARGS` to amend the existing var setup, is a better fit for just adding some args to the stage3 build.

**Comment by BratishkaErik** [comment]
> You can build just stage 2 with `make zig2` (when using the makefile generator).
> 
> Maybe [this simpler approach](https://github.com/erikarvstedt/zig/commit/7faafa8adcc4ee008a5a0c9cd55b241c3c0d87a8), which adds var `ZIG_EXTRA_BUILD_ARGS` to amend the existing var setup, is a better fit for just adding some args to the stage3 build.

Thank you for info, this may sound silly, but I completely forgot about this. I changed this PR complwtely, now this is a general cleanup of CMakeLists.txt and revival of https://github.com/ziglang/zig/pull/12747 .

**Comment by BratishkaErik** [comment]
> > You can build just stage 2 with `make zig2` (when using the makefile generator).
> > Maybe [this simpler approach](https://github.com/erikarvstedt/zig/commit/7faafa8adcc4ee008a5a0c9cd55b241c3c0d87a8), which adds var `ZIG_EXTRA_BUILD_ARGS` to amend the existing var setup, is a better fit for just adding some args to the stage3 build.
> 
> Thank you for info, this may sound silly, but I completely forgot about this. I changed this PR complwtely, now this is a general cleanup of CMakeLists.txt and revival of #12747 .

Oops, I closed it by removing branch and can't reopen it, new PR here https://github.com/ziglang/zig/pull/19969 .

**Pull request closed without merging**
