### PR TITLE
Redesign How Autodoc Works

### LINKED ISSUE #3403: generated docs: source listings with links back to docs
Extracted from #21 

The idea here is you can easily get to the source for a given function, decl, or type, and while looking at the source, get back to the docs. Functions would list callsites so that you could look at an example or at least a test of how something is used.

### LINKED ISSUE #13512: Compiler panic when .emit_docs in build.zig is combined with a bad @import
### Zig Version

0.11.0-dev.137+e40c38d25

### Steps to Reproduce and Observed Behavior

Make a zig project with these files:

`build.zig`
```zig
const std = @import("std");

pub fn build(b: *std.build.Builder) void {
    const target = b.standardTargetOptions(.{});
    const mode = b.standardReleaseOptions();

    const exe = b.addExecutable("main", "src/main.zig");
    exe.emit_docs = .emit; // boom
    exe.setTarget(target);
    exe.setMainPkgPath("./src");

    exe.setBuildMode(mode);
    exe.install();
}
```

`src/main.zig`
```zig
const Nothing = @import("none"); // this doesn't exist

pub fn main() !void {}
```

And run `zig build`:
```
⇒  zig build
thread 26970 panic: attempt to unwrap error: PackageNotFound
Unable to dump stack trace: debug info stripped
error: main...
error: The following command terminated unexpectedly:
/opt/zig/zig-linux-x86_64-0.11.0-dev.137+e40c38d25/zig build-exe /tmp/rep/src/main.zig -femit-docs --cache-dir /tmp/rep/zig-cache --global-cache-dir /home/josh/.cache/zig --name main --main-pkg-path /tmp/rep/src --enable-cache 
error: the following build command failed with exit code 6:
/tmp/rep/zig-cache/o/f6b591257cb6359f87ccd16bf93f70bb/build /opt/zig/zig-linux-x86_64-0.11.0-dev.137+e40c38d25/zig /tmp/rep /tmp/rep/zig-cache /home/josh/.cache/zig
```

This does not happen when the `.emit_docs` line in `build.zig` is removed.

### Expected Behavior

The compiler should not crash.

### LINKED ISSUE #15865: Autodoc: guide markdown files are dependencies
Related to #15864, today we define which guides should be included in a build of Autodoc by mentioning them in the root file container-level doc comment, like so:

```
//!zig-autodoc-guide: intro.md
//!zig-autodoc-guide: quickstart.md
//!zig-autodoc-guide: advanced-docs/advanced-stuff.md

//!zig-autodoc-section: CLI Usage

//!zig-autodoc-guide: cli-basics.md
//!zig-autodoc-guide: cli-advanced.md
```

As things stand currently, those files are not recognized as input files by the caching system, meaning that changing them will not trigger a rebuild in the case of a cache hit for everything else. Today this is in practice mostly fine since Autodoc doesn't really integrate with the cache system at all, but once #15864 is fixed, this will become a more prominent issue.

### LINKED ISSUE #16490: move autodocs logic from the compiler into the browser and avoid unnecessary javascript files
With Disable Cache checked, Firefox downloads 13 MiB over the network for the [std lib docs](https://ziglang.org/documentation/master/std/). Meanwhile, a tarball of the standard library source files (`GZIP=-9 tar cfz std.tar.gz std/`) is only 2.1 MiB. This comparison isn't even counting all the .zig files that get converted into .zig.html. The preprocessing steps that the compiler does bloats the data for dubious benefits, when autodoc could be operating on a more compact data set instead.

Furthermore, #3403 is not implemented yet, and it is a hard requirement that I am imposing. Having all the source code available instead of prerendered in separate html files is the simplest and least wasteful way to implement that feature.

I also would like to see these files deleted from zig:

 * [commonmark.js](https://github.com/ziglang/zig/blob/32a175740c8750a7db550011795a4c22c0d0bc93/lib/docs/commonmark.js)
 * [ziglexer.js](https://github.com/ziglang/zig/blob/32a175740c8750a7db550011795a4c22c0d0bc93/lib/docs/ziglexer.js)

*Especially* the lexer. There is absolutely no reason to have this in javascript instead of sharing code with the actual lexer that we have written in zig. I don't want to hear any excuses about passing strings over the wasm/js boundary. There are various strategies to do it cleanly, you just need to use your imagination.

In other software projects, "use the right tool for the job" is a fair mantra. In this particular repository, however, we need to demonstrate that Zig is truly a general-purpose programming language. Please don't invest in any more javascript logic that should be zig logic instead. I'm going to lose my shit if somebody suggests adding a package.json to the docs/ folder.

### LINKED ISSUE #16728: autodoc: LazyPath links go to FileSource, other deprecations affected
### Zig Version

0.12.0-dev.1+a327d8b99

### Steps to Reproduce and Observed Behavior

- Navigate to [std.Build documentation](https://ziglang.org/documentation/master/std/#A;std:Build)
- Click on any link to "LazyPath"
- It takes you to https://ziglang.org/documentation/master/std/#A;std:Build.FileSource, the page title is `std.Build.FileSource`, but all the comments on the page refer to it as LazyPath.

The same exists for:

- Step.Compile: goes to [std.Build.LibExeObjStep](https://ziglang.org/documentation/master/std/#A;std:Build.LibExeObjStep).
- Build: goes to [std.Build.Builder](https://ziglang.org/documentation/master/std/#A;std:Build.Builder)

### Expected Behavior

LazyPath links should go to https://ziglang.org/documentation/master/std/#A;std:Build.LazyPath 
and Step.Compile to https://ziglang.org/documentation/master/std/#A;std:Build.Step.Compile.
Build links should go back to [std.Build](https://ziglang.org/documentation/master/std/#A;std:Build).

---

This is likely caused by declaration positions:

- FileSource is defined earlier in Build.zig than LazyPath:

    https://github.com/ziglang/zig/blob/ac95cfe4496a5504b42bf37b02f34eff390fe956/lib/std/Build.zig#L61

    https://github.com/ziglang/zig/blob/ac95cfe4496a5504b42bf37b02f34eff390fe956/lib/std/Build.zig#L1672

- LibExeObjStep is defined earlier than Step:

    https://github.com/ziglang/zig/blob/ac95cfe4496a5504b42bf37b02f34eff390fe956/lib/std/Build.zig#L25

    https://github.com/ziglang/zig/blob/ac95cfe4496a5504b42bf37b02f34eff390fe956/lib/std/Build.zig#L31

Note that other deprecations where the new entity is defined before the deprecated do not suffer from this. For example, other types nested inside Step defined after it do not have this problem:

https://github.com/ziglang/zig/blob/ac95cfe4496a5504b42bf37b02f34eff390fe956/lib/std/Build.zig#L32-L35

Step.CheckFile links go to [the right link](https://ziglang.org/documentation/master/std/#A;std:Build.Step.CheckFile).

### LINKED ISSUE #16741: Autodoc: std.heap.page_allocator source link points to std.heap.memory_pool
how to reproduce:
- visit https://ziglang.org/documentation/master/std/#A;std:heap.page_allocator
- click `[src]` in the bottom right corner

expected:
https://ziglang.org/documentation/master/std/src/std/heap/PageAllocator.zig.html
found:
https://ziglang.org/documentation/master/std/src/std/heap/memory_pool.zig.html#L10

### LINKED ISSUE #16763: Autodoc: splitSequence link points to split
When looking at https://ziglang.org/documentation/master/std/#A;std:mem.split

there is link

`Deprecated: use splitSequence`

But it points to https://ziglang.org/documentation/master/std/#A;std:mem.split.

I can open page for splitSequence manually https://ziglang.org/documentation/master/std/#A;std:mem.splitSequence

### LINKED ISSUE #16898: Autodoc: Dead hyperlinks in the `std.time` reference
There are dead hyperlinks in the `std.time` reference: [master/std.time](https://ziglang.org/documentation/master/std/#A;std:time). Clicking [`std.os.clock_gettime`](https://ziglang.org/documentation/master/std/#A;std:time.std.os.clock_gettime) under the timestamp methods leads to a [404](https://ziglang.org/documentation/master/std/#A;std:time.std.os.clock_gettime).
image

Regression-ish since the previous version didn't contain hyperlinks: [0.10.0/std.time](https://ziglang.org/documentation/0.10.0/std/#root;time).

### LINKED ISSUE #17061: Autodoc: display resolution path when displaying decls
Autodoc sometimes resolves indirection for us, but it would be very useful to keep track of all the resolution that has happened.

As one example, currently `std.json.ObjectMap` is defined as follows:

```zig
pub const ObjectMap = @import("another_file.zig").ObjectMap;

// in another_file:
pub const ObjectMap = std.StringHashMap(Value);
```

I think it would be worthwile for Autodoc to show us the entire indirection path that got us to StringHashMap, but this requires annotating whenever we 'resolveValue' and find a nice way of displaying the information.

See https://github.com/ziglang/zig/commit/e5c72a32a766df00e56b18e5da1a335277c79321

### PR DESCRIPTION
**Pull request by andrewrk**
This branch deletes the Autodoc implementation and replaces it with a new one.

## High Level Strategy

The old implementation looked like this:

```
  5987 src/Autodoc.zig
   435 src/autodoc/render_source.zig
 10270 lib/docs/commonmark.js
  1245 lib/docs/index.html
  5242 lib/docs/main.js
  2146 lib/docs/ziglexer.js
 25325 total
```

After compilation (sizes are for standard library documentation):

```
272K commonmark.js
3.8M data-astNodes.js
360K data-calls.js
767K data-comptimeExprs.js
2.2M data-decls.js
896K data-exprs.js
 13K data-files.js
  45 data-guideSections.js
 129 data-modules.js
  15 data-rootMod.js
 294 data-typeKinds.js
3.2M data-types.js
 38K index.html
158K main.js
 36M src/ (470 .zig.html files)
 78K ziglexer.js
```

Total output size: 47M (5.7M gzipped)

`src/Autodoc.zig` processed ZIR code, outputting JSON data for a web application to consume. This resulted in a lot of code ineffectively trying to reconstruct the AST from no-longer-available data.

`lib/docs/commonmark.js` was a third-party markdown implementation that supported *too many features*; for example I don't want it to be possible to have HTML tags in doc comments, because that would make source code uglier. Only markdown that looks good both as source and rendered should be allowed.

`lib/docs/ziglexer.js` was an implementation of Zig language tokenization in JavaScript, despite Zig already exposing its own tokenizer in the standard library. When I saw this [added to the zig project](https://github.com/ziglang/zig/pull/16306), [a little part of me died inside](https://github.com/ziglang/zig/issues/16490).

`src/autodoc/render_source.zig` was a tool that converted .zig files to a syntax-highlighted but non-interactive .zig.html files.

The new implementation looks like this:

```
   942 lib/docs/main.js
   403 lib/docs/index.html
   933 lib/docs/wasm/markdown.zig
   226 lib/docs/wasm/Decl.zig
  1500 lib/docs/wasm/markdown/Parser.zig
   254 lib/docs/wasm/markdown/renderer.zig
   192 lib/docs/wasm/markdown/Document.zig
   941 lib/docs/wasm/main.zig
  1038 lib/docs/wasm/Walk.zig
  6630 total
```

After compilation (sizes are for standard library documentation):

```
 12K index.html
 32K main.js
192K main.wasm
 12M sources.tar
```

Total output size: 12M (2.3M gzipped)

As you can see, it is both dramatically simpler in terms of implementation as well as build artifacts. Now there are exactly 4 files instead of approximately one gajillion, with a 4x reduction in total file size of the generated web app. 

However, not only is it simpler, it's actually more powerful than the old system, because instead of processing ZIR, this system processes the source files directly, meaning it has 100% of the information and never needs to piece anything together backwards.

This strategy uses a WebAssembly module written in Zig. This allows it to reuse components from the compiler, such as the tokenizer, parser, and other utilities for operating on Zig code.

The sources.tar file, after being decompressed by the HTTP layer, is fed directly into the wasm module's memory. The tar file is parsed using std.tar and source files are parsed in place, with some additional computations added to hash tables on the side.

There is room for introducing worker threads to speed up the parsing, although single-threaded it's already so fast that it doesn't really seem necessary.

## Zig Installation

Before this branch, a Zig installation comes with a `docs/std/` directory that contains those 47M of output artifacts mentioned above.

This branch removes those artifacts from Zig installations, instead offering the `zig std` command, which hosts std lib autodocs and spawns a browser window to view them. When this command is activated, `lib/compiler/std-docs.zig` is compiled from source to perform this operation (#19063).

The HTTP server creates the requested files on the fly, including rebuilding main.wasm if any of its source files changed, and constructing sources.tar, meaning that any source changes to the documented files, *or to the autodoc system itself* are immediately reflected when viewing docs. Prefixing the URL with `/debug` results in a debug build of the WebAssembly module.

This means contributors can test changes to Zig standard library documentation, as well as autodocs functionality, by pressing refresh in their browser window.

In total, the Zig installation size is reduced from 317M to 268M (-15%).

## Time to Build the Compiler

Since many lines were deleted from the compiler, we might hope for it to compile faster.

```
Benchmark 1 (3 runs): before/zig build-exe ...
  measurement          mean ± σ            min … max           outliers         delta
  wall_time          86.8s  ± 3.28s     84.1s  … 90.5s           0 ( 0%)        0%
  peak_rss           4.58GB ±  492KB    4.58GB … 4.58GB          0 ( 0%)        0%
  cpu_cycles          350G  ± 1.99G      348G  …  352G           0 ( 0%)        0%
  instructions        505G  ±  205M      505G  …  506G           0 ( 0%)        0%
  cache_references   21.4G  ±  128M     21.3G  … 21.5G           0 ( 0%)        0%
  cache_misses       1.76G  ± 15.3M     1.75G  … 1.78G           0 ( 0%)        0%
  branch_misses      2.43G  ± 2.19M     2.43G  … 2.43G           0 ( 0%)        0%
Benchmark 2 (3 runs): after/zig build-exe ...
  measurement          mean ± σ            min … max           outliers         delta
  wall_time          85.9s  ± 3.63s     82.8s  … 89.9s           0 ( 0%)          -  1.1% ±  9.0%
  peak_rss           4.51GB ±  259KB    4.51GB … 4.51GB          0 ( 0%)        ⚡-  1.5% ±  0.0%
  cpu_cycles          346G  ± 2.29G      343G  …  347G           0 ( 0%)          -  1.2% ±  1.4%
  instructions        499G  ±  185M      498G  …  499G           0 ( 0%)        ⚡-  1.3% ±  0.1%
  cache_references   21.0G  ±  209M     20.8G  … 21.2G           0 ( 0%)          -  1.9% ±  1.8%
  cache_misses       1.73G  ± 16.9M     1.71G  … 1.75G           0 ( 0%)          -  1.9% ±  2.1%
  branch_misses      2.41G  ± 2.16M     2.41G  … 2.41G           0 ( 0%)          -  0.7% ±  0.2%
```

Not much difference here.

A ReleaseSmall build of the compiler shrinks from 10M to 9.8M (-1%).

## Time to Build Autodocs

Autodocs generation is now done properly as part of the pipeline of the compiler rather than tacked on at the end. It also no longer has any dependencies on other parts of the pipeline.

This is how long it now takes to generate standard library documentation:

```
Benchmark 1 (3 runs): old/zig test /home/andy/dev/zig/lib/std/std.zig -fno-emit-bin -femit-docs=docs
  measurement          mean ± σ            min … max           outliers         delta
  wall_time          13.3s  ±  405ms    12.8s  … 13.6s           0 ( 0%)        0%
  peak_rss           1.08GB ±  463KB    1.08GB … 1.08GB          0 ( 0%)        0%
  cpu_cycles         54.8G  ±  878M     54.3G  … 55.8G           0 ( 0%)        0%
  instructions        106G  ±  313K      106G  …  106G           0 ( 0%)        0%
  cache_references   2.11G  ± 35.4M     2.07G  … 2.14G           0 ( 0%)        0%
  cache_misses       41.3M  ±  455K     40.8M  … 41.7M           0 ( 0%)        0%
  branch_misses       116M  ± 67.8K      116M  …  116M           0 ( 0%)        0%
Benchmark 2 (197 runs): new/zig build-obj -fno-emit-bin -femit-docs=docs ../lib/std/std.zig
  measurement          mean ± σ            min … max           outliers         delta
  wall_time          24.6ms ± 1.03ms    22.8ms … 28.3ms          4 ( 2%)        ⚡- 99.8% ±  0.3%
  peak_rss           87.3MB ± 60.6KB    87.2MB … 87.4MB          0 ( 0%)        ⚡- 91.9% ±  0.0%
  cpu_cycles         38.4M  ±  903K     37.4M  … 46.1M          13 ( 7%)        ⚡- 99.9% ±  0.2%
  instructions       39.7M  ± 12.4K     39.7M  … 39.8M           0 ( 0%)        ⚡-100.0% ±  0.0%
  cache_references   2.65M  ± 89.1K     2.54M  … 3.43M           3 ( 2%)        ⚡- 99.9% ±  0.2%
  cache_misses        197K  ± 5.71K      186K  …  209K           0 ( 0%)        ⚡- 99.5% ±  0.1%
  branch_misses       184K  ± 1.97K      178K  …  190K           6 ( 3%)        ⚡- 99.8% ±  0.0%
```

## Regressed Features

* Guides
  - I don't want to port the langref to a guide. I think that should remain a separate document.
  - I think there is room for guides to be added back to this system - likely they will actually work better since there is now support for parsing and linkifying arbitrary code.

### Reliable Linkification

This stems from the fact that with full source files we have all the information, and can write more robust code to look up identifiers from the context they occur in.

### Interactive Source Listings

Press `u` to go to source code for any declaration:

image

The links take you to the API page for that specific link by changing the location hash.

### Embedded Source Listings

image

### Search Includes Doc Comments

Pretty straightforward. The current autodoc seems to not support this for some reason.

image

Planning to also add struct field names, struct field docs, parameter names, and parameter docs to this.

### Error Set View

Merged error sets are detected:

image

Errors that come from other declarations are linked:

image

Errors are also shown on function view:

image

### Correct Type Detection

image

Previous implementation guesses wrong on the type of `options` as well as `DynLib`.

### Correct Implementation of Scroll History

See https://github.com/andrewrk/autodoc/commit/6d96a63430b39c8a08158410b25dd0ecafea28db

## Follow-Up Work

I do not consider these to be merge blockers.

* make the panic handler reflect the failure in the user interface
* when navigating back to search results, up+down arrow should keep working
* redundant search results (search "format")
* in query_exec_fallible, sorting should also check the local namespace inside the file
* walk assign_destructure not implemented yet
* escape URLs when rendering html (look for `missing_feature_url_escape`)
* implement renderHome for multiple modules
* struct fields: render each component separate rather than via source rendering
* infer comptime_int constants (example: members of `#std.time`)
* when global const has a type of `type`, categorize it as a type despite its value
* show abbreviated doc comments in types and namespaces listings
* show type function names as e.g. `ArrayList(T)`
* enum fields should not be linkified (example: `std.log.Level`)
* shrink Ast to fit the slices
* linkification of methods (example: `std.array_hash_map.ArrayHashMap.count`)
* navigating to source from a decl should scroll to the decl
* in source view, make `@imports` into links, but keep same syntax highlighting
* include struct field names and doc comments in search query matching
* include function parameter names and doc comments in search query matching
* instead of logging "can't index foo because it has syntax errors" put it in the UI
* in Walk.expr() it is missing support for asm_input/asm_output nodes
* in renderNamespace, handle an aliasing loop
* add a history item when clicking a search result (it already works when keyboard triggered)
* instead of "declaration not found", show the decl that can't be penetrated (example: `#std.os.system.fd_t`)
* when rendering source code, better handle indentation (example: `#std.array_hash_map.ArrayHashMapUnmanaged.count`)

-----

closes #3403
closes #13512
closes #15865
closes #16490
closes #16728
closes #16741
closes #16763
closes #16898
closes #17061

### CODE REVIEW

**Comment by Jarred-Sumner** [comment]
> reliable linkification

Does that mean it no longer uses relies on `location.hash` (`"#/std/fs/File/`) and instead uses pathnames for generated documentation pages? This would let Google display relevant search results for Zig's standard library documentation for searches like "read file zig" or "close file zig" or "zig http client"

If it is still using `#`, there're ways to fix that without losing offline access, without always needing a server to host the files, and without depending on another tool or framework.

You can use a [Service Worker](https://web.dev/learn/pwa/service-workers) to override the [`"fetch"` event](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/fetch_event) and then when a request is made to a page like `/std/fs/File` you can use the [Cache API](https://developer.mozilla.org/en-US/docs/Web/API/Cache) to retrieve generated HTML for the page and store it. Then, Zig developers will be able to go to https://ziglang.org/documentation/master/std/fs/File/write in their browser

For indexing, separately, you can have a cron job run ~daily that generates the static versions of all the HTML pages and saves the output. Can probably reuse the code from the service worker to do this, as it's a similar operation

**Comment by andrewrk** [comment]
> Does that mean it no longer uses relies on `location.hash` (`"#/std/fs/File/`) and instead uses pathnames for generated documentation pages?

No, it's still a location.hash based system.

> You can [do a bunch of stuff]

What's the problem statement?

**Comment by zraineri** [comment]
Having the generated urls be pathnames instead of the hash structure allows for better Google etc. search

Generating

`https://ziglang.org/documentation/master/std/fs/File/write`

instead of

`https://ziglang.org/documentation/master/std/#A;std:fs.File.write`

would be ideal

**Comment by RossComputerGuy** [comment]
> Generating
> 
> `https://ziglang.org/documentation/master/std/fs/File/write`
> 
> instead of
> 
> `https://ziglang.org/documentation/master/std/#A;std:fs.File.write`

Another note about this is it also makes search bar suggestions based on history a little better. Ime, FF tends to not push results if hash based routing is used but it does push more results when path based routing is used.

**Comment by andrewrk** [comment]
Here is a link to play with the new implementation: https://andrewkelley.me/temp/autodoc-preview-1397342/index.html

**Comment by andrewrk** [comment]
that corresponds to this follow-up issue:

> instead of "declaration not found", show the decl that can't be penetrated (example: #std.os.system.fd_t)

**Comment by motiejus** [comment]
Just curious, why did you choose to compile stdlib in the browser using wasm, as opposed to in the server itself, and serve the resulting `.html` files?

Not saying it would be better or worse, just couldn't locate the deciding factor in this PR.

**Comment by nektro** [comment]
iiuc it was so that once u visit https://ziglang.org/documentation/master/std/ or any other hosted version you'd have all the info after page load and would be able to view everything even if u lost internet after that point

**Pull request merged**
