### PR TITLE
print_zir: fix crash in writeRestoreErrRetIndex

### LINKED ISSUE #17793: print_zir crash in writeRestoreErrRetIndex
### Zig Version

0.12.0-dev.1359+1880c799a

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

pub fn panic(msg: []const u8, st: ?*std.builtin.StackTrace, start: ?usize) noreturn {
    _ = .{ msg, st, start };
    @trap();
}
```

```
$ stage4/bin/zig ast-check -t test.zig 
# Source bytes:       569B
# Tokens:             53 (289B)
# AST Nodes:          24 (440B)
# Total ZIR bytes:    774B
# Instructions:       33 (297B)
# String Table Bytes: 45B
# Extra Data Items:   92 (368B)
thread 348763 panic: reached unreachable code
/home/andy/dev/zig/lib/std/debug.zig:342:14: 0x633ccfc in assert (zig)
    if (!ok) unreachable; // assertion failure
             ^
/home/andy/dev/zig/src/Zir.zig:2233:19: 0x670ec60 in toIndex (zig)
            assert(inst != .none);
                  ^
/home/andy/dev/zig/src/print_zir.zig:2612:24: 0x6863769 in writeInstRef__anon_77381 (zig)
        if (ref.toIndex()) |i| {
                       ^
/home/andy/dev/zig/src/print_zir.zig:2467:30: 0x6863ba7 in writeRestoreErrRetIndex__anon_77385 (zig)
        try self.writeInstRef(stream, inst_data.operand);
                             ^
/home/andy/dev/zig/src/print_zir.zig:307:71: 0x65e5c02 in writeInstToStream__anon_59269 (zig)
            .restore_err_ret_index => try self.writeRestoreErrRetIndex(stream, inst),
                                                                      ^
/home/andy/dev/zig/src/print_zir.zig:2742:39: 0x6865b12 in writeBody__anon_77397 (zig)
            try self.writeInstToStream(stream, inst);
                                      ^
/home/andy/dev/zig/src/print_zir.zig:2704:31: 0x6865e31 in writeBracedBodyConditional__anon_77396 (zig)
            try self.writeBody(stream, body);
                              ^
/home/andy/dev/zig/src/print_zir.zig:2695:44: 0x68666b2 in writeBracedBody__anon_77395 (zig)
        try self.writeBracedBodyConditional(stream, body, self.recurse_blocks);
                                           ^
/home/andy/dev/zig/src/print_zir.zig:1356:33: 0x686681d in writePlNodeBlockWithoutSrc__anon_77394 (zig)
        try self.writeBracedBody(stream, body);
                                ^
/home/andy/dev/zig/src/print_zir.zig:1348:44: 0x6866a0b in writeBlock__anon_77393 (zig)
        try self.writePlNodeBlockWithoutSrc(stream, inst);
                                           ^
```

### Expected Behavior

Full ZIR printed for the example source file.

### PR DESCRIPTION
**Pull request by alichraghi**
Closes #17793

### CODE REVIEW

**Comment by andrewrk** [comment]
Can you show the ZIR? Does it look good?

`zig ast-check -t foo.zig`

**Comment by alichraghi** [comment]
yep
```sh
$ cat test.zig
test {}
```
```llvm
$ zig ast-check -t test.zig

%Zir.Inst.Index.main_struct_inst = extended(struct_decl(parent, Auto, {
  test line(76) hash(ac62b50184fcf99dd8c56be82ce7c820): %Zir.Inst.Index(1) = block_inline({
    %Zir.Inst.Index(7) = func_fancy(test, ret_ty=@InternPool.Index.anyerror_void_error_union_type, body={
      %Zir.Inst.Index(2) = block({
        %Zir.Inst.Index(3) = restore_err_ret_index(%Zir.Inst.Index(2))
        %Zir.Inst.Index(4) = break(%Zir.Inst.Index(2), @InternPool.Index.void_value)
      }) node_offset:77:6 to :77:6
      %Zir.Inst.Index(5) = restore_err_ret_index()
      %Zir.Inst.Index(6) = ret_implicit(@InternPool.Index.void_value) token_offset:77:7 to :77:7
    }) (lbrace=1:6,rbrace=1:7) node_offset:77:1 to :77:1
    %Zir.Inst.Index(8) = break_inline(%Zir.Inst.Index(1), %Zir.Inst.Index(7))
  }) node_offset:77:1 to :77:1
}, {}, {})
```

**Comment by andrewrk** [comment]
Can you fix these while you are at it?

`%Zir.Inst.Index(7)`

this is supposed to be instead

`%7`

**Comment by alichraghi** [comment]
`%Zir.Inst.Index(7)` => `%7`
`@InternPool.Index.anyerror_void_error_union_type` => `@anyerror_void_error_union_type`

```
$ zig ast-check -t test.zig

%0 = extended(struct_decl(parent, Auto, {
  test line(76) hash(ac62b50184fcf99dd8c56be82ce7c820): %1 = block_inline({
    %7 = func_fancy(test, ret_ty=@anyerror_void_error_union_type, body={
      %2 = block({
        %3 = restore_err_ret_index(%2)
        %4 = break(%2, @void_value)
      }) node_offset:77:6 to :77:6
      %5 = restore_err_ret_index()
      %6 = ret_implicit(@void_value) token_offset:77:7 to :77:7
    }) (lbrace=1:6,rbrace=1:7) node_offset:77:1 to :77:1
    %8 = break_inline(%1, %7)
  }) node_offset:77:1 to :77:1
}, {}, {})
```

**Comment by andrewrk** [comment]
Looks good, thank you!

**Pull request merged**
