### PR TITLE
sub-architecture annihilation

### LINKED ISSUE #4261: remove the concept of "sub-architecture" in favor of CPU features
the "sub-architecture" part of the target overlaps with specifying target CPU features:

```zig
    pub const Arch = union(enum) {
        arm: Arm32,
        armeb: Arm32,
        aarch64: Arm64,
        aarch64_be: Arm64,
        aarch64_32: Arm64,
// ....
        pub const Arm64 = enum {
            v8_5a,
            v8_4a,
            v8_3a,
            v8_2a,
            v8_1a,
            v8,
            v8r,
            v8m_baseline,
            v8m_mainline,
        };

```

arm target features:

```zig
const std = @import("../std.zig");
const Cpu = std.Target.Cpu;

pub const Feature = enum {
    @"32bit",
    @"8msecext",
    a12,
    a15,
    a17,
    a32,
    a35,
    a5,
    a53,
    a55,
    a57,
    a7,
    a72,
    a73,
    a75,
    a76,
    a8,
    a9,
    aclass,
    acquire_release,
    aes,
    armv2,
    armv2a,
    armv3,
    armv3m,
    armv4,
    armv4t,
    armv5t,
    armv5te,
    armv5tej,
    armv6,
    armv6_m,
    armv6j,
    armv6k,
    armv6kz,
    armv6s_m,
    armv6t2,
    armv7_a,
    armv7_m,
    armv7_r,
    armv7e_m,
    armv7k,
    armv7s,
    armv7ve,
    armv8_a,
    armv8_m_base,
    armv8_m_main,
    armv8_r,
    armv8_1_a,
    armv8_1_m_main,
    armv8_2_a,
    armv8_3_a,
    armv8_4_a,
    armv8_5_a,
```

I propose to entirely remove "sub-architecture" concept from the language & CLI, and rely instead on the more-powerful ability to specify CPU features. Each "sub-architecture" is represented as a CPU feature that depends on the previous one.

### PR DESCRIPTION
**Pull request by andrewrk**
remove the concept of "sub-architecture" in favor of CPU features. Also rearrange the `std.Target`
data structure.

See https://github.com/ziglang/zig/issues/4261#issuecomment-588490502 for what this means for zig programmers.

note: `@import("builtin")` was already deprecated in favor of    `@import("std").builtin`.

  * `std.builtin.arch` is now deprecated in favor of
    `std.builtin.cpu.arch`.
  * `std.Target.CpuFeatures.Cpu` is now `std.Target.Cpu.Model`.
  * `std.Target.CpuFeatures` is now `std.Target.Cpu`.
  * `std.Target` no longer has an `arch` field. Instead it has a
    `cpu` field, which has `arch`, `model`, and `features`.
  * `std.Target` no longer has a `cpu_features` field.
  * `std.Target.Arch` is moved to `std.Target.Cpu.Arch` and
    it is an enum instead of a tagged union.
  * `std.Target.parseOs` is moved to `std.Target.Os.parse`.
  * `std.Target.parseAbi` is moved to `std.Target.Abi.parse`.
  * `std.Target.parseArchSub` is only for arch now and moved
    to `std.Target.Cpu.Arch.parse`.
  * `std.Target.parse` is improved to accept CPU name and features.
  * `std.Target.Arch.getBaselineCpuFeatures` is moved to
    `std.Target.Cpu.baseline`.
  * `std.Target.allCpus` is renamed to `std.Target.allCpuModels`.
  * `std.Target.defaultAbi` is moved to `std.Target.Abi.default`.
  * Significant cleanup of aarch64 and arm CPU features, resulting in
    the needed bit count for cpu feature set going from 174 to 138.
  * Add `std.Target.Cpu.Feature.Set.addFeatureSet` for merging
    feature sets together.

`-target-feature` and `-target-cpu` are removed in favor of
`-mcpu`, to conform to established conventions, and it gains
additional power to support cpu features. The syntax is:
-mcpu=name+on1+on2-off1-off2

closes #4261

## checklist

 * [x] remove as much of sub-arch stuff from stage1 as possible. maybe llvm requires some extra info that we can derive from cpu features.
 * [x] `std.Target.parse` is failing the unit tests that I wrote for it
 * [x] update `zig build` for new CLI
 * [x] update std lib and compiler_rt and stuff where it depends on the sub-arch. Convert it to use cpu features instead.
 * [x] need to do a partial revert of 96f45c27b65307fe4abd5d1fb1cf314b1f493d8e
 * [x] improve error diagnostics for failed parsing of `-mcpu`. it should list the available cpu models and available cpu features, for example
 * [x] rebase on master

### CODE REVIEW

**Comment by daurnimator** [comment]
Could you give examples of picking a cpu with no features (both in build.zig and on command line?)

Could you show how the baseline CPU can be selected based on the target OS?

**Comment by andrewrk** [comment]
> Could you give examples of picking a cpu with no features (both in build.zig and on command line?)

```zig
foo.setTheTarget(.{
    .cpu = std.Target.aarch64.cortex_a35.toCpu(.aarch64_be),
    .os = .linux,
    .abi = .gnu,
});
```

```
zig build-exe hello.zig -mcpu=pentium
```

> Could you show how the baseline CPU can be selected based on the target OS?

The baseline cpu currently depends only on the architecture. You can see examples of calling `Target.Cpu.baseline` all throughout this PR.

**Comment by daurnimator** [comment]
> The baseline cpu currently depends only on the architecture. You can see examples of calling `Target.Cpu.baseline` all throughout this PR.

If we're breaking these APIs now, then shouldn't we add this feature?

> 10:13:50 | <daurnimator> | I'm not sure if we do it: but the target OS should inform the target baseline cpu feature-set
> 10:15:54 | <andrewrk> | daurnimator, that's a good call and we do not do it yet

**Comment by andrewrk** [comment]
No, that's a separate issue. The first step to tackling that is for someone to compile a table of what the baseline cpu features actually are for each OS.

**Comment by Rocknest** [comment]
Great PR :+1: 

But since that `-target {}` and `-mcpu={}` are not the same as in clang/LLVM, one might be confused by this. I think `-mcpu={}` should be something else like `--cpu {}`, not sure about `-target` though.

**Pull request merged**
