### PR TITLE
Adds ability to iterate overs lines in a reader:

### PR DESCRIPTION
**Pull request by amirrezaask**
This PR will add LinesIterator struct and a method on `reader` called `readLinesAlloc` that will get an Allocator and returns an iterator that for each `.next()` call will alocate enough memory, check with `max_size` and read the line into alocated space and return that line to the user.
```zig
for (reader.readLinesAlloc()) |line| {
     // do smth with the line
}
```

### CODE REVIEW

**Comment by matu3ba** [comment]
What use case do you have for this change?

On file operations one has typically 3 operations: 1. read whole file at once from the meta-information of the file system, 2. predetermine maximum length in file + error out, 3. predetermined length with more of an exceptional code path using new/bigger allocations for the content.

**Comment by jayschwa** [comment]
Related: #3822

**Comment by amirrezaask** [comment]
> What use case do you have for this change?
> 
> On file operations one has typically 3 operations: 1. read whole file at once from the meta-information of the file system, 2. predetermine maximum length in file + error out, 3. predetermined length with more of an exceptional code path using new/bigger allocations for the content.

It's more of a high level kind of api as we see in high level programming languages to read any kind of reader imagine a file by lines and loop over lines easily

**Comment by ominitay** [comment]
What does this achieve which isn't already done by `readUntilDelimiterAlloc`?

**Comment by amirrezaask** [comment]
> What does this achieve which isn't already done by `readUntilDelimiterAlloc`?

This is a simpler interface when you want whole file lines and iterate over them, all other languages have some way of doing so, it's simpler and more readable than doing while(true) and read until for example EOF.

**Comment by ominitay** [comment]
So, you're saying that this:
```zig
var iter = reader.readLinesAlloc(a, std.math.maxInt(usize));
while (iter.next()) |line| {
    ...
}
```
Is simpler than this?
```zig
while (reader.readUntilDelimiterAlloc(a, '\n', std.math.maxInt(usize))) |line| {
    ...
}
```
I don't really see the improvement.

**Comment by ominitay** [comment]
Wait I've just blindly followed your code and trusted it, but this code is incorrect as it stands...

**Comment by ominitay** [comment]
You don't ever return null -- you return an empty slice when you reach the end. So anyone trying to use this in a while loop will just have an infinite loop

**Comment by amirrezaask** [comment]
Sorry, I had a problem on my setup I thought of the sample you provided but for some reason i was getting compile error, i am new to zig so I thought it wasn't possible, i will close this pr sry for the inconvenience.

**Comment by ominitay** [comment]
No problem :) If you need any help, consider joining a Zig community, such as the Zig Discord, where you can get help!

**Comment by amirrezaask** [comment]
> No problem :) If you need any help, consider joining a Zig community, such as the Zig Discord!

Already did but sometimes things seems so easy that you are embarrassed to ask questions

**Comment by jayschwa** [comment]
> What does this achieve which isn't already done by `readUntilDelimiterAlloc`?

While the impl in this PR didn't handle it, one advantage for a distinct line-reading function is that the user doesn't have to think about CRLF vs LF. I'm not sure the state of CRLF in Windows these days, but it's still common in Internet protocols. [Go](https://pkg.go.dev/bufio#Reader.ReadLine) and [Rust](https://doc.rust-lang.org/std/io/trait.BufRead.html#method.lines) handle both in their buffered readers, for example.

**Pull request closed without merging**
