### PR TITLE
Handle singular param count word in error messages

### PR DESCRIPTION
**Pull request by codekidX**
Hello,

This is my first PR for this project, please note that I do not know either C++ or Zig. I just wrote my first Zig program today and found this small unhandled output when passing more arguments than required or less. Do let me know if any changes is needed or can be improved.

### CODE REVIEW

**Comment by Rocknest** [comment]
It can simply be 'argument(s)'

**Comment by codekidX** [comment]
@Rocknest that would be a lot better, I thought of that but it was not consistent with other errors. 

Which approach would be better, anyone?

**Comment by pixelherodev** [comment]
I second `argument(s)` for this; let's keep it simple.

**Comment by andrewrk** [comment]
Thanks!

**Pull request merged**
