### PR TITLE
Implement Add/Mul reductions

### PR DESCRIPTION
**Pull request by LemonBoy**
Not as straightforward as I had expected due to some bugs in testing/stage1.

There's some documentation for `@reduce`, feel free to take over it as I'm not a great writer :\

cc @data-man, give this a spin!

### CODE REVIEW

**Comment by data-man** [comment]
Thank you so much!

More tests:
```diff
diff --git a/test/stage1/behavior/vector.zig b/test/stage1/behavior/vector.zig
index 1c0f1b04c..43f9b4954 100644
--- a/test/stage1/behavior/vector.zig
+++ b/test/stage1/behavior/vector.zig
@@ -521,14 +521,33 @@ test "vector reduce operation" {
             doTheTestReduce(.Min, [4]i32{ 1234567, -386, 0, 3 }, @as(i32, -386));
             doTheTestReduce(.Max, [4]i32{ 1234567, -386, 0, 3 }, @as(i32, 1234567));
 
+            doTheTestReduce(.Min, [4]i64{ 1234567, -386, 0, 3 }, @as(i64, -386));
+            doTheTestReduce(.Max, [4]i64{ 1234567, -386, 0, 3 }, @as(i64, 1234567));
+
+            doTheTestReduce(.Min, [4]i128{ 1234567, -386, 0, 3 }, @as(i128, -386));
+            doTheTestReduce(.Max, [4]i128{ 1234567, -386, 0, 3 }, @as(i128, 1234567));
+
             doTheTestReduce(.Add, [4]i32{ -9, -99, -999, -9999 }, @as(i32, -11106));
+            doTheTestReduce(.Add, [4]u32{ 9, 99, 999, 9999 }, @as(u32, 11106));
+
             doTheTestReduce(.Add, [4]i64{ 9, 99, 999, 9999 }, @as(i64, 11106));
+            doTheTestReduce(.Add, [4]u64{ 9, 99, 999, 9999 }, @as(u64, 11106));
+
+            doTheTestReduce(.Add, [4]i128{ -9, -99, -999, -9999 }, @as(i128, -11106));
+            doTheTestReduce(.Add, [4]u128{ 9, 99, 999, 9999 }, @as(u128, 11106));
+
+            doTheTestReduce(.Add, [4]f32{ -1.9, 5.1, -60.3, 100.0 }, @as(f32, 42.9));
+            doTheTestReduce(.Add, [4]f64{ -1.9, 5.1, -60.3, 100.0 }, @as(f64, 42.9));
+            doTheTestReduce(.Add, [4]f128{ -1.9, 5.1, -60.3, 100.0 }, @as(f128, 42.9));
 
             doTheTestReduce(.Min, [4]u32{ 99, 9999, 9, 99999 }, @as(u32, 9));
             doTheTestReduce(.Max, [4]u32{ 99, 9999, 9, 99999 }, @as(u32, 99999));
 
-            doTheTestReduce(.Mul, [4]i32{ -9, -99, -999, 999 }, @as(i32, -889218891));
-            doTheTestReduce(.Mul, [4]i64{ 9, 99, 999, 9999 }, @as(i64, 8900199891));
+            doTheTestReduce(.Min, [4]u64{ 99, 9999, 9, 99999 }, @as(u64, 9));
+            doTheTestReduce(.Max, [4]u64{ 99, 9999, 9, 99999 }, @as(u64, 99999));
+
+            doTheTestReduce(.Min, [4]u128{ 99, 9999, 9, 99999 }, @as(u128, 9));
+            doTheTestReduce(.Max, [4]u128{ 99, 9999, 9, 99999 }, @as(u128, 99999));
 
             doTheTestReduce(.Min, [4]f32{ -10.3, 10.0e9, 13.0, -100.0 }, @as(f32, -100.0));
             doTheTestReduce(.Max, [4]f32{ -10.3, 10.0e9, 13.0, -100.0 }, @as(f32, 10.0e9));
@@ -536,16 +555,22 @@ test "vector reduce operation" {
             doTheTestReduce(.Min, [4]f64{ -10.3, 10.0e9, 13.0, -100.0 }, @as(f64, -100.0));
             doTheTestReduce(.Max, [4]f64{ -10.3, 10.0e9, 13.0, -100.0 }, @as(f64, 10.0e9));
 
-            doTheTestReduce(.Add, [4]f32{ -1.9, 5.1, -60.3, 100.0 }, @as(f32, 42.9));
-            doTheTestReduce(.Add, [4]f64{ -1.9, 5.1, -60.3, 100.0 }, @as(f64, 42.9));
+            doTheTestReduce(.Min, [4]f128{ -10.3, 10.0e9, 13.0, -100.0 }, @as(f128, -100.0));
+            doTheTestReduce(.Max, [4]f128{ -10.3, 10.0e9, 13.0, -100.0 }, @as(f128, 10.0e9));
+
+            doTheTestReduce(.Mul, [4]i32{ -9, -99, -999, 999 }, @as(i32, -889218891));
+            doTheTestReduce(.Mul, [4]i64{ 9, 99, 999, 9999 }, @as(i64, 8900199891));
+            doTheTestReduce(.Mul, [4]i128{ 9, 99, 999, 9999 }, @as(i128, 8900199891));
 
             doTheTestReduce(.Mul, [4]f32{ -1.9, 5.1, -60.3, 100.0 }, @as(f32, 58430.7));
             doTheTestReduce(.Mul, [4]f64{ -1.9, 5.1, -60.3, 100.0 }, @as(f64, 58430.7));
+            doTheTestReduce(.Mul, [4]f128{ -1.9, 5.1, -60.3, 100.0 }, @as(f128, 58430.7));
 
             // Test the reduction on vectors containing NaNs.
             const f16_nan = math.nan(f16);
             const f32_nan = math.nan(f32);
             const f64_nan = math.nan(f64);
+            const f128_nan = math.nan(f128);
 
             doTheTestReduce(.Add, [4]f16{ -1.9, 5.1, f16_nan, 100.0 }, f16_nan);
             doTheTestReduce(.Add, [4]f16{ -1.9, 5.1, f16_nan, 100.0 }, f16_nan);
@@ -556,6 +581,9 @@ test "vector reduce operation" {
             doTheTestReduce(.Add, [4]f64{ -1.9, 5.1, f64_nan, 100.0 }, f64_nan);
             doTheTestReduce(.Add, [4]f64{ -1.9, 5.1, f64_nan, 100.0 }, f64_nan);
 
+            doTheTestReduce(.Add, [4]f128{ -1.9, 5.1, f128_nan, 100.0 }, f128_nan);
+            doTheTestReduce(.Add, [4]f128{ -1.9, 5.1, f128_nan, 100.0 }, f128_nan);
+
             doTheTestReduce(.Mul, [4]f16{ -1.9, 5.1, f16_nan, 100.0 }, f16_nan);
             doTheTestReduce(.Mul, [4]f16{ -1.9, 5.1, f16_nan, 100.0 }, f16_nan);
 
@@ -564,6 +592,9 @@ test "vector reduce operation" {
 
             doTheTestReduce(.Mul, [4]f64{ -1.9, 5.1, f64_nan, 100.0 }, f64_nan);
             doTheTestReduce(.Mul, [4]f64{ -1.9, 5.1, f64_nan, 100.0 }, f64_nan);
+
+            doTheTestReduce(.Mul, [4]f128{ -1.9, 5.1, f128_nan, 100.0 }, f128_nan);
+            doTheTestReduce(.Mul, [4]f128{ -1.9, 5.1, f128_nan, 100.0 }, f128_nan);
         }
     };
 
```

**Comment by data-man** [comment]
>some documentation

:thinking: 
<table>
<tr>
	<td>op
	<td>booleans
	<td>integers
	<td>floats
<tr>
	<td>.Add
	<td>:x: 
	<td>:heavy_check_mark:
	<td>:heavy_check_mark:
<tr>
	<td>.And
	<td>:heavy_check_mark:
	<td>:heavy_check_mark:
	<td>:x: 
<tr>
	<td>.Max
	<td>:x: 
	<td>:heavy_check_mark:
	<td>:heavy_check_mark:
<tr>
	<td>.Min
	<td>:x: 
	<td>:heavy_check_mark:
	<td>:heavy_check_mark:
<tr>
	<td>.Mul
	<td>:x: 
	<td>:heavy_check_mark:
	<td>:heavy_check_mark:
<tr>
	<td>.Or
	<td>:heavy_check_mark:
	<td>:heavy_check_mark:
	<td>:x: 
<tr>
	<td>.Xor
	<td>:heavy_check_mark:
	<td>:heavy_check_mark:
	<td>:x: 
</table>

If that's acceptable, I'll send a patch.

**Comment by andrewrk** [comment]
Code looks good; `tidy` found an html issue in the doc changes:

```
+ tidy -qe ../zig-cache/langref.html
line 9702 column 7 - Warning: inserting implicit <p>
line 9702 column 7 - Warning: trimming empty <p>
```

I spot the problem, happy to take care of this in a fixup right now while merging.

**Comment by andrewrk** [comment]
Landed in 2e1cef75086a0b606fd8f1f7a0cda4ab2f0b7a49

**Comment by LemonBoy** [comment]
> More tests:

Thank you, please send a follow-up PR so that the CI can check if anything blows up. `fp128` vectors are quite useless IMO, no ISA supports them natively.

> Landed in 2e1cef7

Danke!

**Pull request closed without merging**
