### PR TITLE
add runtime safety for noreturn function returning

### LINKED ISSUE #15221: Proposal: Automatically insert `unreachable` statement after calling a extern function marked as noreturn
Let's say I have a bunch external functions, one of them should be marked as `noreturn`.
```Zig
extern fn foo() void;
extern fn bar() noreturn;
extern fn baz() void;
extern fn qux() void;
```
If I accidently mark them as:
```zig
extern fn foo() void;
extern fn bar() void;
extern fn baz() noreturn;
extern fn qux() void;
```
Then if I call `baz` in a function like:
```zig
fn shouldReturn() i32 {
    // some code
    baz();
    return res;
}
```
The `baz` would return normally without trigger a `reach unreachable code` panic even in `Debug` mode. And we could build it without getting any warnning message. And because `baz` is marked as `noreturn`, the `return` statement is eliminated, then we would get a crazy control flow and some confusing panic.

One of zig's goal is `No hidden control flow`. So maybe we should automatically insert `unreachable` statement after calling a extern function marked as noreturn.

### PR DESCRIPTION
**Pull request by Vexu**
Closes #15221

### CODE REVIEW

**Comment by Vexu** [comment]
@jacobly0 can you help me figure out what's going on with the liveness in this branch?

Reduced code for the failure is:
```zig
pub export fn entry() void {
    while (true) {
        foo() catch |err| switch (err) {
            error.foo => {
                while (true) {}
            },
        };
        foo() catch {};
    }
}
fn foo() error{foo}!void {}
```
producing this AIR:
```
# Begin Function AIR: a.entry:
# Total AIR+Liveness bytes: 2.0341796875KiB
# AIR Instructions:         139 (1.2216796875KiB)
# AIR Extra Data:           78 (312B)
# AIR Values Bytes:         30 (240B)
# Liveness tomb_bits:       72B
# Liveness Extra Data:      12 (48B)
# Liveness special table:   6 (48B)
  %0 = const_ty(*const type)
  %1 = constant(*const type, builtin)
  %2 = constant(type, builtin)
  %3 = const_ty(*const type)
  %4 = constant(*const type, builtin.StackTrace)
  %5 = constant(type, builtin.StackTrace)
  %6 = const_ty(builtin.StackTrace)
  %21 = const_ty(*const fn() error{foo}!void)
  %22 = constant(*const fn() error{foo}!void, (function 'foo'))
  %23 = const_ty(fn() error{foo}!void)
  %24 = constant(fn() error{foo}!void, (function 'foo'))
  %26 = const_ty(error{foo}!void)
  %31 = const_ty(error{foo})
  %33 = const_ty(*const type)
  %34 = constant(*const type, builtin)
  %35 = constant(type, builtin)
  %36 = const_ty(builtin.StackTrace)
  %38 = const_ty(error{foo})
  %41 = const_ty(error{foo})
  %42 = const_ty(error{foo})
  %43 = constant(error{foo}, error.foo)
  %63 = const_ty(*const type)
  %64 = constant(*const type, builtin)
  %65 = constant(type, builtin)
  %66 = const_ty(*const type)
  %67 = constant(*const type, builtin.panic_messages)
  %68 = constant(type, builtin.panic_messages)
  %69 = const_ty(*const *const [23:0]u8)
  %70 = constant(*const *const [23:0]u8, "switch on corrupt value")
  %71 = const_ty(*const [23:0]u8)
  %72 = constant(*const [23:0]u8, "switch on corrupt value")
  %73 = const_ty(*const type)
  %74 = constant(*const type, builtin)
  %75 = constant(type, builtin)
  %76 = const_ty(*const fn([]const u8, ?*builtin.StackTrace, ?usize) noreturn)
  %77 = constant(*const fn([]const u8, ?*builtin.StackTrace, ?usize) noreturn, (function 'default_panic'))
  %78 = const_ty(fn([]const u8, ?*builtin.StackTrace, ?usize) noreturn)
  %79 = constant(fn([]const u8, ?*builtin.StackTrace, ?usize) noreturn, (function 'default_panic'))
  %80 = const_ty(*const type)
  %81 = constant(*const type, builtin)
  %82 = constant(type, builtin)
  %83 = const_ty(?*builtin.StackTrace)
  %84 = constant(?*builtin.StackTrace, null)
  %85 = constant([]const u8, "switch on corrupt value")
  %86 = const_ty(?usize)
  %87 = constant(?usize, null)
  %95 = const_ty(error{foo}!void)
  %100 = const_ty(error{foo})
  %102 = const_ty(*const type)
  %103 = constant(*const type, builtin)
  %104 = constant(type, builtin)
  %105 = const_ty(builtin.StackTrace)
  %109 = const_ty(*const type)
  %110 = constant(*const type, builtin)
  %111 = constant(type, builtin)
  %113 = const_ty(*usize)
  %125 = const_ty(*const type)
  %126 = constant(*const type, builtin)
  %127 = constant(type, builtin)
  %129 = const_ty(*[]usize)
  %131 = const_ty([]usize)
  %133 = const_ty([]usize)
  %135 = const_ty(*usize)

  %124 = alloc(*[32]usize)
  %128 = alloc(*builtin.StackTrace)
  %130 = struct_field_ptr_index_1(*[]usize, %128)
  %132 = array_to_slice([]usize, %124!)
  %134!= store(%130!, %132!)
  %136 = struct_field_ptr_index_0(*usize, %128)
  %137!= store(%136!, @Zir.Inst.Ref.zero_usize)
  %138!= set_err_return_trace(%128!)
  %7 = save_err_return_trace_index()
  %9!= dbg_block_begin()
  %123!= dbg_block_end()
  %11!= loop(noreturn, {
    %13!= dbg_stmt(2:12)
    %14!= dbg_block_begin()
    %16!= dbg_stmt(2:18)
    %18!= dbg_block_begin()
    %19!= dbg_stmt(3:9)
    %20!= block(void, {
      %25!= dbg_stmt(3:12)
      %27 = call(%24, [])
      %28 = is_non_err(%27)
      %91!= cond_br(%28!, {
        %29 = unwrap_errunion_payload(void, %27!)
        %30!= br(%20, %29!)
      }, {
        %7!
        %32!= unwrap_errunion_err(error{foo}, %27)
        %37!= save_err_return_trace_index()
        %39 = unwrap_errunion_err(error{foo}, %27!)
        %40!= dbg_stmt(3:35)
        %90!= switch_br(%39!, [%43] => {
            %45!= dbg_block_begin()
            %47!= dbg_block_begin()
            %60!= dbg_block_end()
            %61!= dbg_block_end()
            %49!= loop(noreturn, {
              %51!= dbg_stmt(5:24)
              %52!= dbg_block_begin()
              %54!= dbg_stmt(5:30)
              %58!= dbg_block_end()
            })
          }, else => {
            %7!
            %62!= dbg_stmt(3:35)
            %88!= call(%79, [%85, %84, %87])
            %89!= unreach()
          }
        )
      })
    })
    %92!= dbg_stmt(8:9)
    %93!= block(void, {
      %94!= dbg_stmt(8:12)
      %96 = call(%24, [])
      %97 = is_non_err(%96)
      %117!= cond_br(%97!, {
        %98 = unwrap_errunion_payload(void, %96!)
        %99!= br(%93, %98!)
      }, {
        %96!
        %101!= unwrap_errunion_err(error{foo}, %96)
        %106!= save_err_return_trace_index()
        %112 = err_return_trace(*builtin.StackTrace)
        %114 = struct_field_ptr_index_0(*usize, %112!)
        %115!= store(%114!, %7)
        %116!= br(%93, @Zir.Inst.Ref.void_value)
      })
    })
    %118!= dbg_block_end()
    %121!= dbg_block_end()
  })
# End Function AIR: a.entry

error(liveness_verify): %90: dead operand %7 reused and killed again
```

**Comment by andrewrk** [comment]
> liveness

cc @mlugg

**Comment by mlugg** [comment]
god dammit i was so sure i'd caught all the liveness bugs

**Comment by jacobly0** [comment]
@mlugg would be the one to verify this, but I hit no obvious failures with the following diff applied, although the liveness of actual infinite loops seems suboptimal.
```diff
diff --git a/src/Liveness.zig b/src/Liveness.zig
index a1bfb73e2..afd0dfb03 100644
--- a/src/Liveness.zig
+++ b/src/Liveness.zig
@@ -1601,9 +1601,6 @@ fn analyzeInstLoop(
             const num_loop_live = data.old_extra.items[extra_idx + num_breaks + 1];
             const loop_live = data.old_extra.items[extra_idx + num_breaks + 2 ..][0..num_loop_live];

-            // This is necessarily not in the same control flow branch, because loops are noreturn
-            data.live_set.clearRetainingCapacity();
-
             try data.live_set.ensureUnusedCapacity(gpa, @intCast(u32, loop_live.len));
             for (loop_live) |alive| {
                 data.live_set.putAssumeCapacity(alive, {});
```

**Comment by mlugg** [comment]
If that works I think it's purely coincidental, the original logic there seems sound - I suspect the actual root cause is some faulty logic in switch_br handling. I'll take a closer look tomorrow

**Comment by jacobly0** [comment]
It's not specific to `switch_br` because replacing it with a `cond_br` has the exact same behavior.  Here's a promising diff that produces the infinite loop liveness I expect:

```diff
diff --git a/src/Liveness.zig b/src/Liveness.zig
index a1bfb73e2..565576088 100644
--- a/src/Liveness.zig
+++ b/src/Liveness.zig
@@ -1601,6 +1601,16 @@ fn analyzeInstLoop(
             const num_loop_live = data.old_extra.items[extra_idx + num_breaks + 1];
             const loop_live = data.old_extra.items[extra_idx + num_breaks + 2 ..][0..num_loop_live];

+            if (num_breaks == 0) {
+                // This loop never breaks, so the old live set becomes branch deaths.
+                try data.branch_deaths.ensureUnusedCapacity(gpa, data.live_set.count());
+                var it = data.live_set.keyIterator();
+                while (it.next()) |key| {
+                    const death = key.*;
+                    data.branch_deaths.putAssumeCapacity(death, {});
+                }
+            }
+
             // This is necessarily not in the same control flow branch, because loops are noreturn
             data.live_set.clearRetainingCapacity();
```

**Comment by mlugg** [comment]
That still looks suspicious - why would zero branches be a special case? What if we branched to a scope outside %7?

I'm currently a bit suspicious of parts of my strategy - I can't actually see a reason that branch_deaths should even exist, but maybe I'm forgetting bits of how it works. Hold tight, I'll be taking a look later today!

**Comment by mlugg** [comment]
Okay yes, having re-familiarised myself with the code - I think `branch_deaths` can be eliminated from Liveness, simplifying it and fixing this bug. I'll try to get that PR up later today - sorry for the issues here @Vexu!

**Comment by Vexu** [comment]
Somehow these changes broke the load-elision logic in LLVM so I had to manually workaround it in `crypto/aes/soft.zig` until I finish #15688. I assume that's OK since the compiler was previously able to avoid those redundant memcpy's.

**Pull request merged**
