### PR TITLE
i386-linux support

### PR DESCRIPTION
**Pull request by SamTebbs33**
This patch adds i386-linux support (#1929). It is not finished and this PR will be added to as time goes on. The current issues are:

* wasi.zig asserts that the alignment of i64 and u64 ~isn't~ is 8.
* Zig runs out of registers during register allocation when compiling the syscall6 function, since the linux syscall abi uses ebp.

Feedback on how to address the above is very welcome.

### CODE REVIEW

**Comment by andrewrk** [comment]
> wasi.zig asserts that the alignment of i64 and u64 isn't 8.

I'd like to change this `is_the_target` thing in master branch. Each of these imports sort of assumes that they only get imported when their corresponding target is active, which you can see with these assertions. This is resulting in pulling in a lot more code than necessary, and, as you can see, running comptime blocks that is unnecessary and even problematic.

> Zig runs out of registers during register allocation when compiling the syscall6 function, since the linux syscall abi uses ebp.

The first thing I would check is if this is due to zig adding `no-omit-frame-pointer` in safe modes. You can test if syscall6 works with release-fast where the frame pointer is omitted. If it does, then a good solution would be adding detection that if an inline assembly block clobbers `rbp` then don't add no-omit-frame-pointer to that function.

**Comment by LemonBoy** [comment]
> Zig runs out of registers during register allocation when compiling the syscall6 function, since the linux syscall abi uses ebp.

x86 has so few GPRs that you have to get a bit creative, follow the path used by musl:

```C
	__asm__ __volatile__ ("pushl %7 ; push %%ebp ; mov 4(%%esp),%%ebp ; " SYSCALL_INSNS " ; pop %%ebp ; add $4,%%esp"
		: "=a"(__ret) : "a"(n), "b"(a1), "c"(a2), "d"(a3), "S"(a4), "D"(a5), "g"(a6) : "memory");
```

This way you don't break the frame chain and we're still able to backtrace out of this call without the need for DWARF infos.

> If it does, then a good solution would be adding detection that if an inline assembly block clobbers rbp then don't add no-omit-frame-pointer to that function.

Yikes, a compiler that does that deserves a honorable mention in the hall of shame. 

Some more notes since I've already walked this road:

* Since this is x86 you also need another syscall stub in order to do any operation on a socket.

* Please fill the whole `/bits` file using the definitions taken from musl libc, don't copy & paste anything out of the other .zig files or you'll inevitably copy over a wrong definition.

* Double check your `stat` struct, you really want its 64-bit variant and you really want to use `SYS_fstat64` instead of the olde 32-bit variant.

* If a platform has `SYS_rt_sigreturn` and `SYS_sigreturn` you have to use them in `restore_rt` and `restore`. Again, don't copy definitions without double-checking them.

* Check out the i386-specific quirk in `clone`, you have to pass a `UserDesc` there too.

* Speaking of `UserDesc`, if you want threading to work you have to save the `entry_num` value once you get a "slot" upon startup (save it in `TLSImage`) and then re-use it as needed.

* Run tests, if you find some fucked-up syscall that's not caught by some test then write one.

**Comment by andrewrk** [comment]
> follow the path used by musl:

Ah that's much better than my proposed solution. Thanks! 

I agree with the rest of the review as well.

**Comment by SamTebbs33** [comment]
> > Zig runs out of registers during register allocation when compiling the syscall6 function, since the linux syscall abi uses ebp.
> 
> x86 has so few GPRs that you have to get a bit creative, follow the path used by musl:
> 
> ```c
> 	__asm__ __volatile__ ("pushl %7 ; push %%ebp ; mov 4(%%esp),%%ebp ; " SYSCALL_INSNS " ; pop %%ebp ; add $4,%%esp"
> 		: "=a"(__ret) : "a"(n), "b"(a1), "c"(a2), "d"(a3), "S"(a4), "D"(a5), "g"(a6) : "memory");
> ```
> 
> This way you don't break the frame chain and we're still able to backtrace out of this call without the need for DWARF infos.

Thanks, I'll look into this.
 
> * Since this is x86 you also need another syscall stub in order to do any operation on a socket.

Could you elaborate?

> * If a platform has `SYS_rt_sigreturn` and `SYS_sigreturn` you have to use them in `restore_rt` and `restore`. Again, don't copy definitions without double-checking them.

I see the distinction now, thanks for clearing that up. It's hard to see that for yourself when the existing bits and linux files aren't commented.

> * Check out the i386-specific quirk in `clone`, you have to pass a `UserDesc` there too.
Is that the clone in `std/special/c.zig` or in `linux/i386.zig`?

Regarding the copy-paste remarks, I only copied the `restore = restore_rt` part and got the rest from the following sources, they may be useful for others:
* tls: https://github.com/darlinghq/darling/blob/master/src/kernel/emulation/linux/machdep/tls.c
* O_LARGEFILE: https://github.com/golang/go/blob/50bd1c4d4eb4fac8ddeb5f063c099daccfb71b26/src/syscall/zerrors_linux_386.go
* syscalls: https://w3challs.com/syscalls/?arch=x86
* stat.h: https://github.com/torvalds/linux/blob/master/arch/x86/include/uapi/asm/stat.h

**Comment by andrewrk** [comment]
> got the rest from the following sources, they may be useful for others:

This list is a bit suspect, I think we would be better off with `zig translate-c` and using musl headers as reference.

**Comment by LemonBoy** [comment]
> Could you elaborate?

[socketcall](https://linux.die.net/man/2/socketcall) is the gateway for all the socket-related operations, it's an historical artifact that's been sort-of obsoleted in newer kernels (> 4.x IIRC) by providing "proper" syscall numbers for those ops.

> got the rest from the following sources

Yeah, no. As Andrew suggests use musl (and the kernel source if needed) as a reference.

> Is that the clone in std/special/c.zig or in linux/i386.zig?

The `clone` syscall itself, that's used in order to implement threading.
Here's the interesting excerpt from the `clone` manpage:

```
       CLONE_SETTLS (since Linux 2.5.32)
              The TLS (Thread Local Storage) descriptor is set to newtls.

              The interpretation of newtls and the resulting effect is  archi‐
              tecture  dependent.   On  x86, newtls is interpreted as a struct
              user_desc * (see set_thread_area(2)).  On x86-64 it is  the  new
              value  to  be set for the %fs base register (see the ARCH_SET_FS
              argument to arch_prctl(2)).  On architectures with  a  dedicated
              TLS register, it is the new value of that register.
```

**Comment by SamTebbs33** [comment]
I tried using the suggested syscall6 implementation but still ran into a "ran out of registers during register allocation error". I even tried doing the same for arg5 as I did for arg6 (pushing onto stack and moving into the correct register) but ran into "inline assembly requires more registers than available". I thought of taking them straight from the function's arguments according and putting them in the correct registers, something like

```
mov 4(esp), eax
mov 8(esp), ebx
mov 12(esp), ecx
// etc.
int $0x80
```
This would require different assembly depending on the abi chosen.

**Comment by LemonBoy** [comment]
> I tried using the suggested syscall6 implementation but still ran into a "ran out of registers during register allocation error". I even tried doing the same for arg5 as I did for arg6 (pushing onto stack and moving into the correct register) but ran into "inline assembly requires more registers than available". 

Let's start from the very beginning. The `g` constraint means the compiler is free to pick either a register or a memory location, this is extremely good in our case since that means we either get a stack slot (if the frame pointer is used) or a spare register if possible. But life always finds a way to smack you in the face so here's the bad news: the `g` constraint isn't supported by LLVM.
So far so good, we can always use an alternative constraint right? `rm` instructs the compiler to pick a register or a memory location, that's exactly what we need right? Yes and no, while this will make your code compile and work just fine I have a bad news for you, LLVM *always* gives up and picks the `m` out of the two alternatives.

Enough blabbering:

```zig
pub fn syscall6(
    number: usize,
    arg1: usize,
    arg2: usize,
    arg3: usize,
    arg4: usize,
    arg5: usize,
    arg6: usize,
) usize {
    return asm volatile (
        \\  push %%ebp
        \\  mov %[arg6], %%ebp
        \\  int $0x80
        \\  pop %%ebp
        : [ret] "={eax}" (-> usize)
        : [number] "{eax}" (number),
          [arg1] "{ebx}" (arg1),
          [arg2] "{ecx}" (arg2),
          [arg3] "{edx}" (arg3),
          [arg4] "{esi}" (arg4),
          [arg5] "{edi}" (arg5),
          [arg6] "rm" (arg6)
        : "memory"
    );
}
```

**Comment by SamTebbs33** [comment]
Thanks @LemonBoy. I also saw that the "g" constraint wasn't supported but "rm" works well.

**Comment by SamTebbs33** [comment]
I haven't been able to commit much time to this PR but plan to within the next few days, I'm currently running into a fault when using `setThreadPointer` which I guess is to do with @LemonBoy 's comment about how it needs to use an `entry_num` allocated during startup.

**Comment by andrewrk** [comment]
This has been WIP for over a month, and is probably too big to get merged. I suggest to break this into smaller, more easily mergable, independent improvements.

**Comment by annacrombie** [comment]
@SamTebbs33 Dont give up!  I'm really excited about i386 linux support for zig

**Comment by andrewrk** [comment]
Note that if you use `-lc --strip --single-threaded` then Zig already does support i386-linux-musl and i386-linux-gnu to some degree:

```
$ ./zig build-exe ../test/standalone/hello_world/hello.zig -target i386-linux-musl --strip -lc --single-threaded
$ ./hello
Hello, world!
```

But certainly having support that does not depend on libc, supports threads, and debug info would be nice :)

**Pull request closed without merging**
