### PR TITLE
Make align expr on fns a compile error in Wasm

### PR DESCRIPTION
**Pull request by kubkon**
In Wasm, specifying alignment of function pointers makes little sense since function pointers are in fact indices to a Wasm table, therefore any alignment check on those is invalid. This can cause unexpected behaviour when checking expected alignment with `@ptrToInt(fn_ptr)` or similar. This commit proposes to make `align` expressions a compile error when compiled to Wasm architecture.

Some references:
[1] [Mozilla: WebAssembly Tables](https://developer.mozilla.org/en-US/docs/WebAssembly/Understanding_the_text_format#WebAssembly_tables)
[2] [Sunfishcode's Wasm Ref Manual](https://github.com/sunfishcode/wasm-reference-manual/blob/master/WebAssembly.md#indirect-call)

---

If we decide to go this route, I think it'd be worthwhile adding a compile error test for this. I tried adding a Wasm-only test case to `tests/compile_error.zig` but it seems these are not cross-compiled to Wasm. Any pointers here would be much appreciated.

Another alternative for this is to detect if we're dealing with a function pointer in Wasm in built-ins such `@alignCast` and `@ptrToInt` and emulate alignment, but I think that might be less desirable and lead to situations where the programmer would expect one thing, and get something different (in terms of compiler behaviour). Any thoughts on this would be great!

I'm not sure who'd be best to look at this so I'm gonna go ahead and cc @andrewrk, but if anyone has got some points they'd like to raise, by all means please do!

### CODE REVIEW

**Comment by andrewrk** [comment]
>  I think it'd be worthwhile adding a compile error test for this. I tried adding a Wasm-only test case to `tests/compile_error.zig` but it seems these are not cross-compiled to Wasm. Any pointers here would be much appreciated.

This example should help:

https://github.com/ziglang/zig/blob/d10e407977f1ba165ca3d0a04d7b270096185559/test/compile_errors.zig#L816-L832

**Comment by kubkon** [comment]
> > I think it'd be worthwhile adding a compile error test for this. I tried adding a Wasm-only test case to `tests/compile_error.zig` but it seems these are not cross-compiled to Wasm. Any pointers here would be much appreciated.
> 
> This example should help:
> 
> https://github.com/ziglang/zig/blob/d10e407977f1ba165ca3d0a04d7b270096185559/test/compile_errors.zig#L816-L832

Perfect, thanks! This is now done in 08b0cae.

**Comment by kubkon** [comment]
Oh and BTW, I didn't really touch any of the self-hosted code, but I can investigate and add a `@compileError` in the right place to achieve the same effect as with stage0 and stage1 (perhaps as a subsequent PR though). What do you think @andrewrk?

**Comment by andrewrk** [comment]
Thanks for thinking of self-hosted! What you're describing should be possible to do within a few days  but we don't actually have compile error tests setup for self-hosted yet (see #5422).

But don't worry, it won't be forgotten; the fact that you added a compile error test case for stage1 will ensure that it happens in self-hosted. Because all the stage1 compile error test cases will be sorted into categories:

 * Passes in stage1 but not self-hosted
 * Passes in self-hosted but not stage1
 * Passes in both

**Comment by kubkon** [comment]
> Thanks for thinking of self-hosted! What you're describing should be possible to do within a few days but we don't actually have compile error tests setup for self-hosted yet (see #5422).
> 
> But don't worry, it won't be forgotten; the fact that you added a compile error test case for stage1 will ensure that it happens in self-hosted. Because all the stage1 compile error test cases will be sorted into categories:
> 
>     * Passes in stage1 but not self-hosted
> 
>     * Passes in self-hosted but not stage1
> 
>     * Passes in both

Sounds good! I'll watch the space for relevant PRs, and after they land, I'll make sure we get coverage for this as well.

**Pull request merged**
