### PR TITLE
@TypeOf with multiple args

### LINKED ISSUE #439: @typeOf() should take multiple parameters and do peer type resolution
the type of:

```zig
const foo = switch (bar()) {
    A => a(),
    B => b(),
    C => c(),
}
```

is some type that each of `a()`, `b()`, and `c()` either are or can implicitly convert to. Determining this type is called peer type resolution. That's already a solved problem.

The `@typeOf()` builtin function should take multiple parameters and do peer type resolution on them to expose this concept directly to users.

This is useful in this context:

```zig
fn max(a: var, b: var) -> @typeOf(a, b) {
    if (a > b) a else b
}
```

### PR DESCRIPTION
**Pull request by LemonBoy**
Closes #439 (oh that's quite old)

Missing pieces (for another PR/day):
* Use it in more places
* Documentation

### CODE REVIEW

**Comment by syscall0** [comment]
Shouldn't this take tuple as argument instead of varargs?

**Comment by LemonBoy** [comment]
It feels a bit awkward with tuples, `@TypeOf(.{bar})` looks like you're asking for the tuple type.

**Comment by SpexGuy** [comment]
Maybe we need a separate macro for this case? Something like `@PeerType(.{ @TypeOf(a), @TypeOf(b) })`. Pretty fugly but it's more consistent with the lack of overloads elsewhere and separates PTR from var -> type resolution which would let you use it in situations where only the types are known.

**Comment by LemonBoy** [comment]
`TypeOf` is not overloaded this way, the single-argument case is nothing but the multi-argument one with N=1.

**Comment by SpexGuy** [comment]
That's true, but it doesn't change that I can't do resolution if I only know the types.  Are there any other precedents for varargs builtins?

**Comment by alexnask** [comment]
@SpexGuy  
`@compileLog`, `@asyncCall` , `@newStackCall` (although the last two have to be switched to use and argument pack tuple)

**Comment by SpexGuy** [comment]
Ok then this is probably fine. I'm just worried that proponents of varargs will point to this as a reason to add them back into the language. ("you couldn't even write the builtins without them" or some argument along those lines.)

**Comment by SpexGuy** [comment]
But that concern can be separate from this PR. This is hardly the place for this discussion. Sorry @LemonBoy, carry on.

**Comment by andrewrk** [comment]
landed in 378bf1c3b71fdcc823fb9a5382400ec0a659fc00

**Pull request closed without merging**
