### PR TITLE
add error for discarding if/while pointer capture

### LINKED ISSUE #21356: pointer modifier allowed on discarded `if`/`while` capture
### Zig Version

0.14.0-dev.1472+3929cac15

### Steps to Reproduce and Observed Behavior

```zig
test {
    if (null) |*_| {}
    while (null) |*_| {}
}
```
test passes

### Expected Behavior

an error as it is in `for` loops
```zig
test {
    for (.{}) |*_| {}
}
```
`pointer modifier invalid on discard`

### PR DESCRIPTION
**Pull request by xdBronch**
closes #21356
is it normal to make helper functions for repeated errors like this? its small but it feels wrong having the same thing pasted so many times

### CODE REVIEW

**Comment by Vexu** [comment]
Repeating the error is fine but could you add a test for it? Seems like the existing ones aren't tested either.

**Comment by xdBronch** [comment]
sure, that would go in test/cases/compile_errors/ right?

**Review by Vexu — APPROVED** [review]
A bit nit-picky so feel free to ignore but all those tests are testing the same thing so it'd be nice to have them all together in the same file.

**Comment by xdBronch** [comment]
ah i considered that but thought it would stop the analysis when it hit the first one, didnt realize it would keep going if they werent in the same function. yeah i could do that

**Pull request merged**
