### PR TITLE
Implement system package mode

### LINKED ISSUE #14281: a zig build mode intended to be used when packaging an application or library for a system distribution
This proposal is accepted; please see these comments for the criteria for closing the issue:
 * https://github.com/ziglang/zig/issues/14281#issuecomment-1624220653
 * https://github.com/ziglang/zig/issues/14281#issuecomment-1644900436

-----

Extracted from #14265.

The use case is as follows:

Someone wants to take an upstream application, and package it for a Linux distribution, or another kind of distribution such as Homebrew or Nix.

The application knows exactly what versions of each dependency it wants to build against, but distributions only provide a limited set of versions. Furthermore, the system distribution wants to be in charge of providing all dependencies, building the application from source without access to any files outside of those provided by the system itself, via its own dependency management system.

For this use case, instead of fetching dependencies from the URLs provided by zig build.zig.zon files, instead there should be some kind of override that makes the dependencies fetched from the system package manager.

Related: [Stay Together For The Kids: Why System Package Managers and Language Package Managers Struggle to Cooperate](https://www.youtube.com/watch?v=stChOsejLEQ)

### LINKED ISSUE #14597: ability to fetch only needed dependencies
This is a competing proposal to #14591.

Inside of a build.zig file, there may be conditional logic that decides whether a dependency is needed. For example:

```zig
const std = @import("std");

pub fn build(b: *std.build.Builder) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const enable_libmp3lame = b.option(bool, "enable-libmp3lame",
        "support MP3 decoding via libmp3lame") orelse true;

    const lib = b.addStaticLibrary(.{
        .name = "ffmpeg",
        .target = target,
        .optimize = optimize,
    });
    lib.linkLibrary(libz_dep.artifact("z"));
    if (enable_libmp3lame) {
        const libmp3lame_dep = b.dependency("libmp3lame", .{
            .target = target,
            .optimize = optimize,
        });
        lib.linkLibrary(libmp3lame_dep.artifact("mp3lame"));
    }
    lib.linkLibC();
    lib.addIncludePath(".");
}
```

Key point here being that `b.dependency("mp3lame")` is only called if the `enable_libmp3lame` option is set to true. This means that when that option is not set, libmp3lame is in fact not a dependency.

This proposal is to embrace arbitrary logic deciding what is or isn't a dependency. Instead of marking categories of dependencies in the `build.zig.zon` file, Zig would have the heuristic choice to pre-fetch some, all, or none of the dependencies. When running build.zig, if any packages referenced with dependency() were not fetched already, the build runner would exit in a special manner and communicate the set of dependency packages that were missing. Zig would fetch them and then re-execute the build runner.

Along with this proposal would come a new flag to `zig build`: `--fetch`. Note that this is still part of the `zig build` subcommand - indeed it would support all of the same flags and build options as a standard `zig build` operation. However, in this case, after running the build.zig script, it would not actually perform the make(). Instead it would only fetch missing packages for the given set of flags. In most typical cases, no additional flags would be used, but one could imagine passing something like this: `zig build --fetch --Denable-libmp3lame=false` to avoid fetching libmp3lame in the above example.

Related: #14283

### PR DESCRIPTION
**Pull request by andrewrk**
## Synopsis

Makes the zig build system significantly more friendly to system package maintainers by introducing System Integration Options.

Closes #14281
Closes #14597

## Demo

Using [groovebasin](https://github.com/andrewrk/groovebasin/tree/old-client) as an example project:

### New API for declaring optional system library integration

```diff
--- a/build.zig
+++ b/build.zig
@@ -5,18 +5,8 @@ pub fn build(b: *std.Build) void {
     const optimize = b.standardOptimizeOption(.{
         .preferred_optimize_mode = .ReleaseSafe,
     });
-    const libgroove_optimize_mode = b.option(
-        std.builtin.OptimizeMode,
-        "libgroove-optimize",
-        "override optimization mode of libgroove and its dependencies",
-    );
     const use_llvm = b.option(bool, "use-llvm", "LLVM backend");
 
-    const groove_dep = b.dependency("groove", .{
-        .optimize = libgroove_optimize_mode orelse .ReleaseFast,
-        .target = target,
-    });
-
     b.installDirectory(.{
         .source_dir = .{ .path = "public" },
         .install_dir = .lib,
@@ -31,7 +21,22 @@ pub fn build(b: *std.Build) void {
         .use_llvm = use_llvm,
         .use_lld = use_llvm,
     });
-    server.linkLibrary(groove_dep.artifact("groove"));
+
+    if (b.systemIntegrationOption("groove", .{})) {
+        server.linkSystemLibrary("groove");
+    } else {
+        const libgroove_optimize_mode = b.option(
+            std.builtin.OptimizeMode,
+            "libgroove-optimize",
+            "override optimization mode of libgroove and its dependencies",
+        );
+        const groove_dep = b.dependency("groove", .{
+            .optimize = libgroove_optimize_mode orelse .ReleaseFast,
+            .target = target,
+        });
+        server.linkLibrary(groove_dep.artifact("groove"));
+    }
+
     b.installArtifact(server);
 
     const run_cmd = b.addRunArtifact(server);
```

This diff plus some similar diffs in the project's dependency tree.

### New help section

There is a new `--help` section:

```
System Integration Options:
  --system [dir]               System Package Mode. Disable fetching; prefer system libs
  -fsys=[name]                 Enable a system integration
  -fno-sys=[name]              Disable a system integration
  --host-target [triple]       Use the provided target as the host
  --host-cpu [cpu]             Use the provided CPU as the host
  --host-dynamic-linker [path] Use the provided dynamic linker as the host

  Available System Integrations:                Enabled:
    groove                                      no
    z                                           no
    mp3lame                                     no
    vorbis                                      no
    ogg                                         no
```

### Using the system integration options

```
[nix-shell:~/dev/groovebasin]$ zig build --host-target x86_64-linux-gnu --host-dynamic-linker /nix/store/whypqfa83z4bsn43n4byvmw80n4mg3r8-glibc-2.37-45/lib64/ld-linux-x86-64.so.2 -fsys=z

[nix-shell:~/dev/groovebasin]$ ldd zig-out/bin/groovebasin 
    linux-vdso.so.1 (0x00007fff054c7000)
    libz.so.1 => /nix/store/8mw6ssjspf8k1ija88cfldmxlbarl1bb-zlib-1.2.13/lib/libz.so.1 (0x00007fe164675000)
    libm.so.6 => /nix/store/whypqfa83z4bsn43n4byvmw80n4mg3r8-glibc-2.37-45/lib/libm.so.6 (0x00007fe164595000)
    libc.so.6 => /nix/store/whypqfa83z4bsn43n4byvmw80n4mg3r8-glibc-2.37-45/lib/libc.so.6 (0x00007fe1643ae000)
    /nix/store/whypqfa83z4bsn43n4byvmw80n4mg3r8-glibc-2.37-45/lib64/ld-linux-x86-64.so.2 (0x00007fe164696000)
```

The result is using baseline CPU due to the `--host-target` flag. Note that `--host-target` is always a valid option even if the build script does not expose any standard target option.

Now, re-run the command but removing `-fsys=z`:

```
[nix-shell:~/dev/groovebasin]$ ~/Downloads/zig/build-release/stage4/bin/zig build --host-target x86_64-linux-gnu --host-dynamic-linker /nix/store/whypqfa83z4bsn43n4byvmw80n4mg3r8-glibc-2.37-45/lib64/ld-linux-x86-64.so.2 

[nix-shell:~/dev/groovebasin]$ ldd zig-out/bin/groovebasin 
    linux-vdso.so.1 (0x00007ffcc23f6000)
    libm.so.6 => /nix/store/whypqfa83z4bsn43n4byvmw80n4mg3r8-glibc-2.37-45/lib/libm.so.6 (0x00007f525feea000)
    libc.so.6 => /nix/store/whypqfa83z4bsn43n4byvmw80n4mg3r8-glibc-2.37-45/lib/libc.so.6 (0x00007f525fd03000)
    /nix/store/whypqfa83z4bsn43n4byvmw80n4mg3r8-glibc-2.37-45/lib64/ld-linux-x86-64.so.2 (0x00007f525ffcc000)
```

### new release option

```
  --release[=mode]             Request release mode, optionally specifying a
                               preferred optimization mode: fast, safe, small
```

```
andy@ark ~/d/a/zlib (main)> zig build --release
the project does not declare a preferred optimization mode. choose: --release=fast, --release=safe, or --release=small
error: the following build command failed with exit code 1:
/home/andy/dev/ayb/zlib/zig-cache/o/6f46a03cb0f5f70d2c891f31086fecc9/build /home/andy/Downloads/zig/build-release/stage3/bin/zig /home/andy/dev/ayb/zlib /home/andy/dev/ayb/zlib/zig-cache /home/andy/.cache/zig --seed 0x3e999c60 --release
andy@ark ~/d/a/zlib (main) [1]> zig build --release=safe
andy@ark ~/d/a/zlib (main)> vim build.zig
andy@ark ~/d/a/zlib (main)> git diff
diff --git a/build.zig b/build.zig
index 76bbb01..1bc13e6 100644
--- a/build.zig
+++ b/build.zig
@@ -5,7 +5,9 @@ pub fn build(b: *std.Build) void {
     const lib = b.addStaticLibrary(.{
         .name = "z",
         .target = b.standardTargetOptions(.{}),
-        .optimize = b.standardOptimizeOption(.{}),
+        .optimize = b.standardOptimizeOption(.{
+            .preferred_optimize_mode = .ReleaseFast,
+        }),
     });
     lib.linkLibC();
     lib.addCSourceFiles(.{
andy@ark ~/d/a/zlib (main)> zig build --release
andy@ark ~/d/a/zlib (main)> zig build --release=small
andy@ark ~/d/a/zlib (main)> 
```

### Lazy Dependencies

```diff
--- a/build.zig
+++ b/build.zig
-    const groove_dep = b.dependency("groove", .{
-        .optimize = libgroove_optimize_mode orelse .ReleaseFast,
-        .target = target,
-    });
+    if (b.lazyDependency("groove", .{
+        .optimize = libgroove_optimize_mode orelse .ReleaseFast,
+        .target = target,
+    })) |groove_dep| {
+        server.linkLibrary(groove_dep.artifact("groove"));
+    }
```

```diff
--- a/build.zig.zon
+++ b/build.zig.zon
@@ -5,6 +5,7 @@
         .groove = .{
             .url = "https://github.com/andrewrk/libgroove/archive/66745eae734e986cd478e7220664f2de902d10a1.tar.gz",
             .hash = "1220285f0f6b2be336519a0e612a11617c655f78b0efe1cac12fc73fc1e50c7b3e14",
+            .lazy = true,
         },
     },
     .paths = .{
```

This makes the dependency only get fetched if it is actually used. The build runner will be rebuilt if any missing lazy dependencies are encountered.

### Error for using dependency() instead of lazyDependency()

```
$ zig build -h
thread 2904684 panic: dependency 'groove' is marked as lazy in build.zig.zon which means it must use the lazyDependency function instead
/home/andy/Downloads/zig/lib/std/debug.zig:434:22: 0x11901a9 in panicExtra__anon_18741 (build)
    std.builtin.panic(msg, trace, ret_addr);
                     ^
/home/andy/Downloads/zig/lib/std/debug.zig:409:15: 0x1167399 in panic__anon_18199 (build)
    panicExtra(null, null, format, args);
              ^
/home/andy/Downloads/zig/lib/std/Build.zig:1861:32: 0x1136dca in dependency__anon_16705 (build)
                std.debug.panic("dependency '{s}{s}' is marked as lazy in build.zig.zon which means it must use the lazyDependency function instead", .{ b.dep_prefix, name });
                               ^
/home/andy/dev/groovebasin/build.zig:33:40: 0x10e8865 in build (build)
        const groove_dep = b.dependency("groove", .{
                                       ^
/home/andy/Downloads/zig/lib/std/Build.zig:1982:33: 0x10ca783 in runBuild__anon_8952 (build)
        .Void => build_zig.build(b),
                                ^
/home/andy/Downloads/zig/lib/build_runner.zig:310:29: 0x10c6708 in main (build)
        try builder.runBuild(root);
                            ^
/home/andy/Downloads/zig/lib/std/start.zig:585:37: 0x10af845 in posixCallMainAndExit (build)
            const result = root.main() catch |err| {
                                    ^
/home/andy/Downloads/zig/lib/std/start.zig:253:5: 0x10af331 in _start (build)
    asm volatile (switch (native_arch) {
    ^
???:?:?: 0x8 in ??? (???)
Unwind information for `???:0x8` was not available, trace may be incomplete

error: the following build command crashed:
/home/andy/dev/groovebasin/zig-cache/o/20af710f8e0e96a0ccc68c47688b2d0d/build /home/andy/Downloads/zig/build-release/stage3/bin/zig /home/andy/dev/groovebasin /home/andy/dev/groovebasin/zig-cache /home/andy/.cache/zig --seed 0x513e8ce9 -Z4472a09906216280 -h
```

It's allowed to do the reverse - lazyDependency() when the manifest file does not mark it as lazy.

It's probably best practice to always use lazyDependency() in build.zig.

### avoid fetching in system mode

```
[nix-shell:~/dev/2Pew]$ zig build --system ~/tmp/p -fno-sys=SDL2
error: lazy dependency package not found: /home/andy/tmp/p/1220c5360c9c71c215baa41b46ec18d0711059b48416a2b1cf96c7c2d87b2e8e4cf6
info: remote package fetching disabled due to --system mode
info: dependencies might be avoidable depending on build configuration

[nix-shell:~/dev/2Pew]$ zig build --system ~/tmp/p 

[nix-shell:~/dev/2Pew]$ mv ~/.cache/zig/p/1220c5360c9c71c215baa41b46ec18d0711059b48416a2b1cf96c7c2d87b2e8e4cf6 ~/tmp/p

[nix-shell:~/dev/2Pew]$ zig build --system ~/tmp/p -fno-sys=SDL2
steps [5/8] zig build-lib SDL2 ReleaseFast native... Compile C Objects [75/128] e_atan2... ^C

[nix-shell:~/dev/2Pew]$ 
```

## Full List of Breaking Changes

Predicted breakage due to these changes: little to none

* `b.zig_exe` => `b.graph.zig_exe`
* `b.env_map` => `b.graph.env_map`
* `b.search_prefixes`: it's now an ArrayListUnmanaged. `addSearchPrefix` is unchanged
* `b.global_cache_root` => `b.graph.global_cache_root`
* `b.cache` => `b.graph.cache`

## Merge Checklist

* [x] implement `--release`
* [x] make the CLI rebuild the build runner with lazy deps added
* [x] implement `--system [dir]` command

### CODE REVIEW

**Comment by thejoshwolfe** [comment]
> It's probably best practice to always use lazyDependency() in build.zig.

Does this mean the default should be switched? Maybe call the other way "side effect dependency" or something? (is that why you would want a dependency you don't use?)

**Comment by andrewrk** [comment]
Dependencies do not have side effects. The use case is conditional dependencies - the configuration values chosen decides the set of actual dependencies used.

**Comment by slimsag** [comment]
Can you comment on this: if a build.zig file imports a dependency via `@import("foo").bar()` for additional build-time logic, can `foo` still be an optional dependency?

My assumption would be no, and that if you have a dependency which needs any additional build-time logic to be imported like that, it becomes a viral dependency (if you use it, your dependency also cannot be optional)?

I'm not necessarily opposed to that, but want to understand the limitations here if any.

The reason I am asking is because in Mach currently, we use this to abstract some of the platform-specific nuances of desktop/mobile/web, where the former has a `main` entrypoint that looks very different from the latter (which are dynamic libraries rather than an executable), so we e.g. `@import("mach").createApp(my_mod)` basically which let's mach create the main platform-specific entrypoint, and just import/call `my_mod` as if it were the entrypoint without the platform-specific bits. I am considering moving away from this approach, and if lazy dependencies don't support it that may be another factor in encouraging me to do so.

others (@MasterQ32 ?) may have other reasons to need `@import("foo").bar()` logic I'm unaware of though

**Comment by rohlem** [comment]
The set of modules imported for build-time logic could vary depending on f.e. the configured target (including details such as CPU features and OS version).
This should be supportable if the `build.zig` compilation process catches `@import`-not-found errors and compares the missing module name to the set of lazy dependencies.
If it finds a match, it can download this dependency (the same as if had it encountered a `lazyDependency` call in executed `build.zig` code) and then retry compilation and execution of `build.zig`.

**Comment by andrewrk** [comment]
@slimsag as it stands in this branch, direct `@import` only works on non lazy dependencies.

Regardless of what changes here I would encourage you to explore module based abstractions instead of inversion of control flow based abstractions. Happy to work with you on any limitations you encounter.

But I'll tinker a bit and see if we can have the ability to import lazy dependencies build logic. I don't want to do what @rohlem is suggesting though so it would be a breaking change either way.

**Comment by andrewrk** [comment]
Alright, I spent some more time investigating these follow-up issues, but ultimately I decided to move forward with this branch as-is, and address them later.  This is certainly a step forward. Let's try this out for a while and then here are some follow-up issues to tackle:

### deprecating dependency() and making lazyDependency() the preferred API

I think this might be a good idea to do in the future, since using `lazyDependency()` lets you toggle the laziness only by editing build.zig.zon. This would be a prerequisite for making all dependencies always lazy.

However as it stands, this branch is actually not very invasive; the breaking changes are minimal. I think it would be a good idea to solve the other problems mentioned below before inflicting unnecessary breaking changes on build.zig users.

### direct `@import` in build scripts

I looked into making this work for lazy dependencies. It's possible, but it has some downsides:
* it requires generating a zig source file per dependency instead of one dependencies.zig file for the whole tree. I don't know how much of a problem this is in reality, perhaps it's more distasteful in theory than in practice.
* It requires some clunky API in the build.zig script - an explicit check for the existence of a dependency followed by the `@import`, or something like that.

Maybe I could find a more satisfactory solution if I keep poking at it.

That said, this feature was always meant for actual build script dependencies, it was not intended for inversion of control and having the dependency take over the build script logic for the parent package. I think users should try to get away from doing that, and I'm happy to work together on coming up with a satisfactory API that is based on dependencies *exposing things* rather than *doing build logic*.

### making all dependencies always lazy

This would simplify things by removing an unnecessary choice from the programmer, and result in fewer packages fetched unnecessarily. Why get the programmer involved if the build system can always just do the right thing without asking? The problem with this right now is twofold:
* Lazy dependencies don't work with direct `@import` in build scripts. When the programmer puts `lazy = true` currently, they are losing the ability to use `@import` for that dependency.
* It would cause the build script to get recompiled more often - approximately a number of times equal to the dependency tree depth. In the future, such rebuilds will be near instantaneous thanks to compiler performance enhancements and a separation of user logic from the build runner, but as it stands each rebuild is about 4-5 seconds long.

**Comment by andrewrk** [comment]
> My assumption would be no, and that if you have a dependency which needs any additional build-time logic to be imported like that, it becomes a viral dependency (if you use it, your dependency also cannot be optional)?

Sorry I missed this question earlier. I have not tested this to be absolutely sure, but based on the way it is implemented it is not viral. When a lazy dependency is fetched, its own non-lazy dependencies will all be fetched and therefore `@import` will work. `@import` will only fail on lazy dependencies, it will succeed on non-lazy dependencies.

**Comment by castholm** [comment]
@andrewrk Regarding `@import` in build scripts

> That said, this feature was always meant for actual build script dependencies, it was not intended for inversion of control and having the dependency take over the build script logic for the parent package. I think users should try to get away from doing that, and I'm happy to work together on coming up with a satisfactory API that is based on dependencies _exposing things_ rather than _doing build logic_.

Could you clarify what you mean by "having the dependency take over the build script logic for the parent package"? Because as both a library author and user, being able to expose helper functions that compose and orchestrate build steps seems like one of the main benefits of being able to `@import` a dependency's build script.

For non-trivial packages I would even say `const libfoo = @import("foo").fooArtifact(.{})` is strictly superior to `const libfoo = b.dependency("foo", .{}).artifact("foo")` in terms of UX because you get away from the duck-typed `args` struct and the limitations of the types of options that can be defined through `b.option()` in favor of a fully typed, user-discoverable set of options that tools like ZLS can provide completions for.

**Comment by nektro** [comment]
> That said, this feature was always meant for actual build script dependencies, it was not intended for inversion of control and having the dependency take over the build script logic for the parent package.

I think the proliferation of zig modules in the wild will the blur this line to the point of not really mattering.

> For non-trivial packages I would even say `const libfoo = @import("foo").fooArtifact(.{})` is strictly superior to `const libfoo = b.dependency("foo", .{}).artifact("foo")` in terms of UX because you get away from the duck-typed `args` struct and the limitations of the types of options that can be defined through `b.option()` in favor of a fully typed, user-discoverable set of options that tools like ZLS can provide completions for.

I don't agree with this line at all and to me what it's calling for is a perfect example of designing around a local maximum.

**Comment by andrewrk** [comment]
Partially reverted in #19684.

**Pull request merged**
