### PR TITLE
`std.Target`: Rewrite `Abi.default()` to have better defaults across the board.

### LINKED ISSUE #9089: Improve *BSD native ABI detection
At the moment zig detects the native ABI as `.gnu`, that may cause some problems as many *BSD libcs are not fully gnu-compliant (eg. NetBSD has no `sincos`, a GNU extension, but since we're passing LLVM the wrong triple we end up with [some missing symbols](https://github.com/ziglang/zig-bootstrap/pull/60)).

cc @mikdusan as I guess you'd love some BSD action

### PR DESCRIPTION
**Pull request by alexrp**

### CODE REVIEW

**Comment by alexrp** [comment]
@mikdusan would you be able to test this on the BSDs?

**Comment by mikdusan** [comment]
> @mikdusan would you be able to test this on the BSDs?

With patch I can system-bootstrap on freebsd, netbsd, openbsd . I'm not sure that `default()` ever gets really used on the BSDs because we do not have any kind of cross-targeting support. For example, on master `zig build-exe hello.zig -target x86_64-freebsd` will always fail so it's just generally the detected target used, which btw still ends up as `-gnu` as shown by `zig env`.

**Comment by alexrp** [comment]
> which btw still ends up as `-gnu` as shown by `zig env`.

That's the part I was mainly interested in. I'm surprised that's still the case with these changes. :slightly_frowning_face: I'll see if I can figure out why that is.

**Comment by alexrp** [comment]
Ok, at this point I actually have no idea where the `-gnu` could be coming from if it's still showing up in `zig env` with a freshly built compiler with this commit. A grep for `\.gnu` turns up nothing obvious. :thinking:

**Comment by Vexu** [comment]
> Ok, at this point I actually have no idea where the `-gnu` could be coming from if it's still showing up in `zig env` with a freshly built compiler with this commit. A grep for `\.gnu` turns up nothing obvious. 🤔


My guess would be that https://github.com/ziglang/zig/blob/148b5b4c7806a694084f1e6f9514b0333cb75c6a/lib/std/zig/system.zig#L535 overrides the default ABI with gnu which is the first element in the array constructed here https://github.com/ziglang/zig/blob/148b5b4c7806a694084f1e6f9514b0333cb75c6a/lib/std/zig/system.zig#L987

**Comment by alexrp** [comment]
That seems like a very plausible guess, yeah. I don't think we should be excluding `Abi.none` in that list since `DynamicLinker.standard()` does the right thing:

https://github.com/ziglang/zig/blob/148b5b4c7806a694084f1e6f9514b0333cb75c6a/lib/std/Target.zig#L2030-L2031
https://github.com/ziglang/zig/blob/148b5b4c7806a694084f1e6f9514b0333cb75c6a/lib/std/Target.zig#L1746
https://github.com/ziglang/zig/blob/148b5b4c7806a694084f1e6f9514b0333cb75c6a/lib/std/Target.zig#L1762-L1764

**Review by andrewrk — APPROVED** [review]

**Comment by alexrp** [comment]
I'll merge this as-is and follow up with a fix for `detectAbiAndDynamicLinker()`.

**Pull request merged**
