### PR TITLE
translate-c: Better support for division in macros

### LINKED ISSUE #13162: stage2: translate-c macro with division results in compile error
### Zig Version

0.10.0-dev.4324+c23b3e6fd

### Steps to Reproduce

`translate-c` the following and use the resulting function

```c
#define GLAD_VERSION_MAJOR(version) (version / 10000)
```

```zig
c.GLAD_VERSION_MAJOR(@as(c_int, 20000));
```

### Expected Behavior

Works.

### Actual Behavior

Error:

```
cimport.zig:1362:68: error: division with 'c_int' and 'c_int': signed integers must use @divTrunc, @divFloor, or @divExact
pub inline fn GLAD_VERSION_MAJOR(version: anytype) @TypeOf(version / @as(c_int, 10000)) {
```

Full translation:

```zig
pub inline fn GLAD_VERSION_MAJOR(version: anytype) @TypeOf(version / @as(c_int, 10000)) {
    return version / @as(c_int, 10000);
}
```

### PR DESCRIPTION
**Pull request by ehaas**
Perform C-style arithmetic conversions on operands to division operator in macros

Closes #13162

### CODE REVIEW

**Comment by ehaas** [comment]
We should probably do arithmetic conversion in macros for all the C operators that do it. If this approach looks good I can add the other ones.

**Review by Vexu — APPROVED** [review]
This will make macros much more verbose but I don't see any way around that.

**Comment by topolarity** [comment]
Is this specific to macros, or does this apply to arithmetic expressions in all contexts?

**Comment by ehaas** [comment]
Clang does the conversions for us for actual C code; the problem is that we just see macros as a stream of tokens and have to recreate C's semantics.

**Comment by mitchellh** [comment]
Thank you! I think a similar fix needs to be applied to mod math: 13346

**Comment by topolarity** [comment]
The added tests don't pass on stage1:
```zig
$ ./build/stage3/bin/zig test test/behavior.zig -I test -I . -fstage1 
./zig-cache/o/e46197c6bc613fe11d6210fe71091391/cimport.zig:654:110: error: unable to evaluate constant expression
pub inline fn DIVIDE_CONSTANT(version: anytype) @TypeOf(@import("std").zig.c_translation.MacroArithmetic.div(version, @as(c_int, 1000))) {
                                                                                                             ^
./zig-cache/o/e46197c6bc613fe11d6210fe71091391/cimport.zig:654:49: note: called from here
pub inline fn DIVIDE_CONSTANT(version: anytype) @TypeOf(@import("std").zig.c_translation.MacroArithmetic.div(version, @as(c_int, 1000))) {
                                                ^
./test/behavior/translate_c_macros.zig:144:56: note: called from here
test "Macro that uses division operator. Issue #13162" {
                                                       ^
```

Is this a regression?

**Pull request merged**
