### PR TITLE
Initial implementation of @extern builtin

### PR DESCRIPTION
**Pull request by LemonBoy**
I heard from the grapevine somebody needs weak extern symbols.

MVP based on our previous discussion & failed attempts.

### CODE REVIEW

**Comment by andrewrk** [comment]
I'm actually a little bit further along than this in a local branch - my strategy is to append to a list and then iterate over it in do_code_gen. It works for things in a comptime scope too

**Comment by andrewrk** [comment]
ok my code is not at a point where it's working though so I'm tempted to merge this as is since we have to re-implement it in stage2 anyway

**Comment by LemonBoy** [comment]
> I'm actually a little bit further along than this in a local branch 

The only missing thing is documentation and (hopefully) a few changes to let the parser allow `@extern`, right now it rejects that with a syntax error because `extern` is a keyword (?).

> would this unblock #4503 as-is?

AFAIR I needed this to check for `_DYNAMIC` being defined or not. Yes, this should be enough.

**Comment by suirad** [comment]
How does this compare with `@export(fnname, "out name", .Weak)`?

When I was using the above I was hoping it would work like the extern.

**Comment by LemonBoy** [comment]
> How does this compare with @export(fnname, "out name", .Weak)?

That exports a weak symbol, `extern` lets you import weak (or strong) symbols.

**Pull request merged**
