### PR TITLE
Improve compiler frontend handling of missing option parameter

### PR DESCRIPTION
**Pull request by perillo**
## First commit
Currently the compiler frontend prints unfriendly error messages when an option requires a parameter but it is not supplied by the command line arguments.

Example:
```console
$ zig build-exe -x -fno-llvm main.zig
error: language not recognized: '-fno-llvm'
```

Update the `ArgsIterator.nextOrFatal` method to report an error when the argument is an option.

For compatibility, add a new `nextMultiOrFatal` method, that behaves in the same way as the old `nextOrFatal`.  Currently it is only used for the deprecated `--mod` option.

Example after this change:
```console
$ zig build-exe -x -fno-llvm main.zig
error: expected parameter after -x
```

Additionally, improve the coding style used in ArgsIterator, removing
unnecessary use of @This and adding an empty line between methods.

This is a little improvement, but better then nothing.

## Second commit
Currently in the the compiler frontend source code, options like `-l c` and `-lc` are not handled near each other, thus making reading the code more complex.

Move variant short options right after the associated normal short option.

I tested the change using `git diff --color-moves=plain`.

## Notes

All the short variant options get the parameter value using `arg[2..]`, with the exception of the `-l` option, where instead use `arg["-l"..len]`.

I think that this should be normalized.

### CODE REVIEW

**Comment by Vexu** [comment]
Doesn't this theoretically make it impossible to give values starting with `-` to many arguments that don't have variants? Not sure how big of a problem that'll be in practice.



> For compatibility, add a new `nextMultiOrFatal` method, that behaves in the same way as the old `nextOrFatal`. Currently it is only used for the deprecated `--mod` option.

This and the deprecated `--mod` option can now be removed since `zig1.wasm` has since been updated.

**Comment by perillo** [comment]
> Doesn't this theoretically make it impossible to give values starting with `-` to many arguments that don't have variants? Not sure how big of a problem that'll be in practice.
> 

This change will make adding values starting with `-` inconvenient but not impossible; the user will need to quote the value.

As a counter example:
`zig test --test-filter -lc test.zig`

So the choice is to have a possibly confusing/missing error message or adding quotes when necessary.

Thanks for the review.

**Comment by Vexu** [comment]
> This change will make adding values starting with `-` inconvenient but not impossible; the user will need to quote the value.

What do you mean? `--test-filter "-foo"` is the same as `--test-filter -foo` and `"--test-filter -foo"` is one single argument.

**Comment by perillo** [comment]
> > This change will make adding values starting with `-` inconvenient but not impossible; the user will need to quote the value.
> 
> What do you mean? `--test-filter "-foo"` is the same as `--test-filter -foo` and `"--test-filter -foo"` is one single argument.

You are right, I was hasty.

However Python `argparse` seems to implement the same idea:
```console
> python -m unittest -k c

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```

```console
> python -m unittest -k -c
usage: python -m unittest [-h] [-v] [-q] [--locals] [-f] [-c] [-b] [-k TESTNAMEPATTERNS] [tests ...]
python -m unittest: error: argument -k: expected one argument
```

Another option is to not use the traditional UNIX(?) short/long options, and instead use the GNU variant.

**Review by Vexu — APPROVED** [review]

**Comment by andrewrk** [comment]
no thanks. these are not compelling changes, and you might have made mistakes.

**Pull request closed without merging**
