### PR TITLE
tls certificates: support more BSDs

### LINKED ISSUE #16279: FreeBSD: TlsInitializationFailed
### Zig Version

0.11.0-dev.3892+0a6cd257b

### Steps to Reproduce and Observed Behavior

```sh
# Any project that needs TLS to build eg zigtools/zls too
$ git clone https://github.com/zigzap/zap
$ cd zap
$ zig build
/home/kitty/src/zig/zig/lib/std/crypto/tls/Client.zig:562:49: 0x38a7496 in init__anon_154662 (zig)
                                .certificate => return error.TlsCertificateNotVerified,
                                                ^
/home/kitty/src/zig/zig/lib/std/http/Client.zig:913:103: 0x33b7ee4 in connectUnproxied (zig)
            conn.data.tls_client.* = std.crypto.tls.Client.init(stream, client.ca_bundle, host) catch return error.TlsInitializationFailed;
                                                                                                      ^
/home/kitty/src/zig/zig/lib/std/http/Client.zig:948:9: 0x3149a08 in connect (zig)
        return client.connectUnproxied(host, port, protocol);
        ^
/home/kitty/src/zig/zig/lib/std/http/Client.zig:1013:44: 0x2f37c6f in request (zig)
    const conn = options.connection orelse try client.connect(host, port, protocol);
                                           ^
/usr/home/kitty/src/zig/zig/src/Package.zig:497:19: 0x2f35406 in fetchAndUnpack (zig)
        var req = try http_client.request(.GET, uri, h, .{});
                  ^
/usr/home/kitty/src/zig/zig/src/Package.zig:282:21: 0x2f3dd3e in fetchAndAddDependencies (zig)
        const sub = try fetchAndUnpack(
                    ^
/usr/home/kitty/src/zig/zig/src/main.zig:4461:13: 0x2db0b04 in cmdBuild (zig)
            try fetch_result;
            ^
/usr/home/kitty/src/zig/zig/src/main.zig:285:9: 0x2d5889d in mainArgs (zig)
        return cmdBuild(gpa, arena, cmd_args);
        ^
/usr/home/kitty/src/zig/zig/src/main.zig:213:5: 0x2d559fe in main (zig)
    return mainArgs(gpa, arena, args);
```

### Expected Behavior

Build should be successful, or at least fetch the packages successfully first

### PR DESCRIPTION
**Pull request by mikdusan**
- add support for freebsd, netbsd, dragonfly
- refactor rescanOpenBSD -> rescanBSD
- make os-specific rescan*() non-public

closes #16279

---

- tested on freebsd 13.2, openbsd 7.3, netbsd 9.3, dragonfly 6.4

### CODE REVIEW

**Review by andrewrk — CHANGES_REQUESTED** [review]
Why do macOS and Windows have public rescan functions but Linux and OpenBSD do not?

Please implement this without using variable mutation on the directory path lists, and don't use the unnecessary Linux logic on BSDs that only have 1 path to look at. I think the previous code was better than this refactoring. I think all you need is a common BSD helper function to support more BSDs without introducing code duplication.

**Comment by andrewrk** [comment]
Looks great, thank you!

**Comment by mikdusan** [comment]
[aaaah you already commented and I did another force push]

> Why do macOS and Windows have public rescan functions but Linux and OpenBSD do not?

PR updated to maintain pub for the OS specialization fn's. Doing this is also the reason there are 2 switches to get through for BSD (although they are comptime so not terrible). I could reduce it to 1 switch but that would make rescanBSD inconsistent with the other rescan*() fn args by requiring a `cert_file_path` arg.

My thoughts re going non-public before your review: currently 1 external call-site for `rescan()` and no external call-sites for the OS specialized fn's. Unless we have a need, my preference was to make things non-public unless required for import reasons (eg. rescanMac). But yes, along this reasoning, `rescanWindows()` should not be public.

> Please implement this without using variable mutation on the directory path lists, and don't use the unnecessary Linux logic on BSDs that only have 1 path to look at. I think the previous code was better than this refactoring. I think all you need is a common BSD helper function to support more BSDs without introducing code duplication.

PR updated to remove the variable mutation anti-pattern.

**Review by andrewrk — CHANGES_REQUESTED** [review]
I think it's simpler to have the logic for switching on builtin.os.tag in only one place. I think that's how you had it before. What was the motivation for changing it to this?

**Comment by mikdusan** [comment]
> I think it's simpler to have the logic for switching on builtin.os.tag in only one place. I think that's how you had it before. What was the motivation for changing it to this?

I'll revert it to what you saw.

The motivation was the public API:

- rescanLinux(cb, gpa)
- rescanWindows(cb, gpa)
- rescanMac(cb, gpa)
- rescanBSD(cb, gpa, cert_file_path)

as you mentioned in irc, making non-public, it completely removes my apprehension, I'll do that now too!

**Pull request merged**
