### PR TITLE
Build information dumping with `--dump-build-info`

### PR DESCRIPTION
**Pull request by SuperAuguste**
Another one 😎

- [x] Dependency (`.dependency`) information
- [x] Build-level module information
- [ ] Step information
  - [ ] Name and structure
  - [ ] Modules
  - [ ] Options?

### CODE REVIEW

**Comment by marler8997** [comment]
Here was my previous feeble attempt in case it's helpful for reference: https://github.com/ziglang/zig/pull/9973

**Comment by rohlem** [comment]
Naming nit: While `wet` is indeed an antonym to `dry`, I don't think I've ever seen it in a CLI interface.
`dry` seems to stem primarily from [`dry run`](https://en.wiktionary.org/wiki/dry_run) (i.e. practice/rehearsal), while the collocation `wet run` (for actual execution/competition/performance) isn't as actively used (or at all).

I'd suggest instead calling it `on`, as the antonym for the option `off`, as really, `dry` is its own separate category - the other two options don't influence build execution at all.
And calling them `wet-on`/`wet-off` or `do-on`/`do-off` is overkill as well; they're `non-dry` simply because if they were `dry` it'd be in their name.

**Comment by matklad** [comment]
Might be a stepping stone for https://github.com/ziglang/zig/issues/14286, "build graph for IDEs" ideally is the same thing as "build graph driving the execution of the build".

**Comment by andrewrk** [comment]
Also just a word of caution... I can feel myself having a lot of opinions about the way this works. So if you have anything else to work on, you might want to prioritize that. I don't want you to do a bunch of work and then have the PR rot because I want to participate it in personally, but busy with other things.

**Pull request closed without merging**
