### PR TITLE
Add testcase for switch statement with multiline string

### PR DESCRIPTION
**Pull request by LewisGaul**
Fixes https://github.com/ziglang/zig/issues/7855

The linked issue seems to already be fixed, but this PR adds a testcase to prevent regression.

Also fixed zig fmt adding trailing space after before the target expression when it's rendered on a newline (e.g. in this testcase).

### CODE REVIEW

**Comment by LewisGaul** [comment]
@ifreund would you be able to review? :)

**Review by ifreund — COMMENTED** [review]
I don't think checking if the first target token is on the next line is sufficent. Does the following test case pass?
```zig
try testTransform(
    \\test {
    \\    switch (x) {
    \\        foo =>
    \\            foo(),
    \\    }
    \\}
    \\
,
    \\test {
    \\    switch (x) {
    \\        foo => foo(),
    \\    }
    \\}
    \\
);
```
From reading your code I'd expect this to fail as the switch arm rendered without the space:
```zig
foo =>foo(),
```

**Comment by LewisGaul** [comment]
@ifreund
You're exactly right (added testcase for this). I actually expected the newline to be respected although now I realise I literally wrote a comment that explains why that's not the case!

Do you think the newline should be respected or removed in the example you gave?

**Comment by ifreund** [comment]
> Do you think the newline should be respected or removed in the example you gave?

I think the newline should be removed as per the status quo.

Only multi line string literals should need special handling here, if you want to make a change from the current behavior I think it would be nice if they were indented.

**Comment by LewisGaul** [comment]
Yep cool I'm guessing I should just be able to change the check from `tree.tokensOnSameLine()` to checking whether the target expr token is a multiline string (trying that now). Will leave the status quo behaviour.

**Review by ifreund — APPROVED** [review]
LGTM, Thanks!

**Pull request merged**
