### PR TITLE
AstGen: add error for redundant comptime var in comptime scope

### PR DESCRIPTION
**Pull request by wrongnull**
Inspired from https://github.com/ziglang/zig/pull/18227

### CODE REVIEW

**Review by nektro — APPROVED** [review]

**Comment by rohlem** [comment]
I thought I remembered a proposal-like discussion somewhere to require `comptime var` when the type of the variable is comptime-only, but now I can't find it anymore.
Maybe someone else remembers/finds what I mean, I don't remember the full context / motivations behind it anymore either.

<details><summary>My own two cents of why I'm not too fond of this change:</summary>
<p>

At `comptime`, variables have the attribute that you can safely return a `*const` to them from the current scope (see #7396).
This can be used as a sort of compile-time memory allocation.
By marking variables I use this way as `comptime var`, I am safe from forgetting about / overlooking this should I ever want to convert/enable the code to run at run-time.

Workaround I thought of while writing this comment:
I guess I can explicitly write `if (!@inComptime()) @compileError("x is a comptime allocation");` into the code after every such variable `x`.
It's a bit more to think about and remember, and imo a little less readable, but no deal breaker I guess

</p>
</details>

**Comment by mlugg** [comment]
This is only for cases where `comptime` is known from syntax alone, such as `comptime var` in a `comptime` block. This should be fairly obvious to change; in general, you can't just expect code to work when you delete `comptime` keywords.

With regard to the specific use case you mentioned: doing this with `comptime var` is supposed to be illegal, and will become a compile error in future. You *must* use comptime-known `const`s to get a runtime-valid constant pointer. Use `const x = comptime ...` if you really want to be sure the thing is comptime-known, but usually it's obvious.

**Comment by rohlem** [comment]
> in general, you can't just expect code to work when you delete comptime keywords.

Zig's explicit goal with `comptime` semantics is to make allow using the same code at compile-time as at run-time
(and to that end, for the code to behave the same in both scenarios).
I realize that we're not 100% there yet, but I personally regard any difference in behavior between run-time and `comptime` as a usability bug.
We might not get rid of all of them before 1.0, but in my eyes it's worth pointing them out and trying to reduce them.

> With regard to the specific use case you mentioned: doing this with comptime var is supposed to be illegal [...] .
> You _must_ use comptime-known `const`s to get a runtime-valid constant pointer.

That conflicts with my current understanding - I cannot find any basis for it in #7396, and don't remember it from any other issues.
Not to sound like I don't believe you (I know and appreciate your work as part of the core team!), I just hadn't read of that distinction before.

Your suggestion of explicitly writing `const result = comptime var_buffer;` and then returning `&result` indeed seems like a readability improvement,
and I would be in favor of doing that. However even that `comptime` keyword is disallowed by compile error when already in a `comptime` scope,
so I don't think that works as a reminder for me either.

**Comment by matu3ba** [comment]
> I realize that we're not 100% there yet, but I personally regard any difference in behavior between run-time and comptime as a usability bug.

1. This is unfeasible to solve in general due to 1.1 Zig not enforcing input of accuracy constraints and the 1.2 input number being also approximated for runtime-known code vs comptime known (for practicability). As example, the set of decimal numbers in integer range with precision 0.1 can not be accurately represented in binary floats with different semantics for comptime and runtime code.
2. My gut feeling tells me that the only way without forcing the programmer to type more would be to extend the type system to `d32, d64, d128` and for arbitrary precision floats as well as `arbprec` for comptime-only types and default to `d32`, but this would again break use cases outside of decimal floats and penalize binary float intended applications.
3. I have not seen yet a good proposal starting with an outline of the problem and the possible solution space. https://github.com/ziglang/zig/issues/1974 and https://github.com/ziglang/zig/issues/4221 have barely details, tradeoffs etc. If you're interested in a discussions etc, then please write me on discord.

**Comment by rohlem** [comment]
@matu3ba While number precision wasn't mentioned in this thread yet, it's certainly also an interesting topic.
That said, I don't see a fundamental reason why `comptime` couldn't "emulate the target architecture" in this regard (that's exactly the text currently stated on `ziglang.org`, lol).
But as many architectures' specifications allow different floating point precisions between cpu models, of course there won't be a single correct answer on what to do.

Anyway, I don't see a connection between floating point imprecision, and lifetime/memory semantics in relation to language syntax.
In my eyes reducing footguns, such as by making `comptime` behavior closer to run-time behavior, in any area is an improvement.
I don't see a reason for giving up on efforts for such language improvement.

**Comment by wrongnull** [comment]
In addition to this, I think that ```@call``` with ```.compile_time``` modifier should cause the same compilation error if called in comptime scope (this could probably be probably be handled in ```Sema.analyzeCall```). So far I'm not sure if I'm right.

**Comment by matu3ba** [comment]
> Anyway, I don't see a connection between floating point imprecision, and lifetime/memory semantics in relation to language syntax.

During compilation time, you want portable behavior which also includes at least the option to have portability across floating point operations. Portability across floating point operations mandates arbitrary precision numbers, which require allocations at compilation time to handle etc.

During runtime mostly runtime performance is much more important.

How and if to make both work with the same code paths at scope/fn level remains unclear/not well motivated yet. The [comptime block in the langref](https://ziglang.org/documentation/master/#comptime) does not clarify semantics at all.

**Comment by andrewrk** [comment]
Nice, thank you.

**Pull request merged**
