### PR TITLE
Sema: resolve union layout on field access

### PR DESCRIPTION
**Pull request by schmee**
Closes https://github.com/ziglang/zig/issues/18518.

### CODE REVIEW

**Comment by mlugg** [comment]
This isn't the appropriate fix. The layout should be resolved only when we emit whatever AIR instruction is using the type layout. It should not be resolved early unnecessarily.

It looks like in this case, the issue is related to lowering debug types. I'm not quite sure of the appropriate solution in this case, but it isn't this one.

**Comment by schmee** [comment]
@mlugg thanks for the review and for clarifying the constraints, I'll take another look with this in mind 👍

**Comment by Vexu** [comment]
`queueFullTypeResolution` should work for this.

**Comment by schmee** [comment]
Superseded by https://github.com/ziglang/zig/pull/19182 👍

**Pull request closed without merging**
