### PR TITLE
Install LLVM fatal error handler

### PR DESCRIPTION
**Pull request by LemonBoy**

### CODE REVIEW

**Comment by andrewrk** [comment]
Why?

**Comment by LemonBoy** [comment]
Backtraces and exits with `abort` in case of error.

**Comment by andrewrk** [comment]
Will this conflict with https://github.com/ziglang/zig/blob/eb7d36ae0d240b8ef5421703e613d164cf691d8d/src/main.cpp#L306?

**Comment by LemonBoy** [comment]
> Will this conflict with 

I don't think so, `abort` shouldn't trigger the segfault handler under any circumstance.

**Comment by daurnimator** [comment]
Should this be solved on a more case-by-case basis? e.g. with https://github.com/ziglang/zig/compare/master...daurnimator:always-verify-llvm-modules ?

**Comment by andrewrk** [comment]
I merged @daurnimator's commit above. I don't really want LLVM to be that in control of zig's process. I want zig to own its own error handling.

**Pull request closed without merging**
