### PR TITLE
Elide evaluation of tautological integral comparisons

### LINKED ISSUE #2146: allow tautological < and > against integers.
```
var d: u4 = undefined;
if (d < 16) 
...
```
```
/home/shawn/git/zig/build/lib/zig/std/ascii.zig:218:24: error: integer value 16 cannot be implicitly casted to type 'u4'
    } else if (index < 16) {
                       ^
```

### PR DESCRIPTION
**Pull request by hryx**
This change introduced a bug (see below), so this is a WIP.

Fixes #2146 

## Language changes

A [tautological](https://en.wikipedia.org/wiki/Tautology_(logic)) comparison between integers -- that is, a comparison whose outcome is known without even knowing both values -- will result in the correct boolean value at compile time. This can result in preventing the semantic analysis of one branch of a conditional statement, for example. See [use cases](https://github.com/ziglang/zig/issues/2146).

An integral comparison is considered a tautology if all of the following are true:

- one of the operands has a value known at compile time
- the comptime-known value would take too many bits to fit into the other operand's type

The compiler already handles some kinds of tautologies, like `false == true` and `-13 >= some_unsigned_var`. This change just extends that feature to cover cases based on type size.

## Notes

I added a few cases involving numbers on the "edge" of a type (e.g. the maximum value which can be represented in a u8 or i4), but it might be a good idea to automatically generate these comparisons to try to catch all such potential edge cases. (I was always inspired by the test which [checks all possible places an allocation could/should fail in the parser](https://github.com/ziglang/zig/blob/5951b79af40212754071157596b8aebbe2414ffb/lib/std/zig/parser_test.zig#L2790-L2817).)

## Bugs

After this change, the test [`compile-error switch with overlapping case ranges`](https://github.com/ziglang/zig/blob/a3f6a58c7785e7958f9d0b96d54356944bf34e32/test/compile_errors.zig#L311-L321) fails -- the compiler starts accepting overlapping ranges in a switch. I don't know why yet.

### CODE REVIEW

**Comment by LemonBoy** [comment]
> After this change, the test compile-error switch with overlapping case ranges fails -- the compiler starts accepting overlapping ranges in a switch. I don't know why yet.

You've found a bug! When ranges are involved the `CheckSwitchProngs` is generated in a block that may or may not be elided away during the constant-folding phase, as it happens in that test with your patchset.

**Comment by hryx** [comment]
@LemonBoy Thanks for the tip! I'll look into it as soon as I have a chance.

It looks like the switch prong check is only elided when one of the ranges covers all possible values.

```zig
export fn blep(x: i8) u8 {
    return switch (x) {
        0...2 => 0,
        // 0...255 => 1, // incorrectly passes
        1...255 => 1, // correctly errors
    };
}
```

**Comment by andrewrk** [comment]
@hryx not sure if you noticed, but @LemonBoy fixed the range bug in #4172, so that blocker at least should be out of your way.

**Comment by hryx** [comment]
Awesome! I'll rebase tonight and see if everything passes.

**Comment by LemonBoy** [comment]
Not really, that PR fixed an unrelated bug with ranges.

**Comment by hryx** [comment]
Indeed, no dice. Below is an abbreviated difference between IR output of master (d3e67d99216d3d) (-red) and this branch (+green), using the failing test case as source.

It looks like the first difference is that `BinOp | #6 <= 255` resolves to `Const | true` instead of staying a BinOp. My IR knowledge is limited but I assume that this means:

1. Some switch ranges are reduced to a BinOp, in this case `#6 <= 255` where `#6` is a u8.
2. With my change, `any_u8 <= 255` immediately resolves to comptime true, so the comparison is elided.
3. Presto buggo

If my assumption is true, maybe I can find a way to invoke the `CheckSwitchProngs` before this elision.  🤔 

```diff
 append new bb SwitchRangeYes_19
 ...
 ...
 -> #32 | Const                 | bool        | 0 | true
 ~ /home/hryx/projects/software/zig/bugs/2146/rangebug.zig:4:11
 ~ #34 | BinOp                 | (unknown)   | 1 | #6 <= 255 // no safety
--> #34 | BinOp                 | bool        | 0 | #6 <= 255
+-> #33 | Const                 | bool        | 0 | true
 ~ /home/hryx/projects/software/zig/bugs/2146/rangebug.zig:4:11
 ~ #35 | BinOp                 | (unknown)   | 1 | #33 BoolAnd #34 // no safety
--> #35 | BinOp                 | bool        | 0 | true BoolAnd #34 // no safety
+-> #34 | Const                 | bool        | 0 | true
 ~ /home/hryx/projects/software/zig/bugs/2146/rangebug.zig:4:11
 ~ #38 | CondBr                | noreturn    | - | if (#35) $SwitchRangeYes_36 else $SwitchRangeNo_37 // comptime = #9
 append new bb SwitchRangeNo_20
 -> (noreturn)
 ~ /home/hryx/projects/software/zig/bugs/2146/rangebug.zig:4:21
 ~ #39 | Const                 | comptime_int| 2 | 1
--> #39 | Const                 | comptime_int| 0 | 1
+-> #37 | Const                 | comptime_int| 0 | 1
 ~ /home/hryx/projects/software/zig/bugs/2146/rangebug.zig:4:21
 ~ #40 | EndExpr               | (unknown)   | - | EndExpr(result=peer(next=$SwitchElse_7),value=1)
--> #40 | Const                 | void        | 0 | {}
+-> #38 | Const                 | void        | 0 | {}
 ~ /home/hryx/projects/software/zig/bugs/2146/rangebug.zig:2:12
 ~ #41 | Br                    | noreturn    | - | goto $SwitchEnd_8 // comptime = #9
-append new bb SwitchRangeYes_36
+append new bb SwitchRangeYes_35
 -> (noreturn)
 ~ /home/hryx/projects/software/zig/bugs/2146/rangebug.zig:2:12
-~ #42 | CheckSwitchProngs     | (unknown)   | - | @checkSwitchProngs(#6,0...2,0...255)else:no
--> (invalid)./2146/rangebug.zig:4:9: error: duplicate switch value
-        0...255 => 1,
-        ^
-./2146/rangebug.zig:3:9: note: previous value is here
-        0...2 => 0,
-        ^
-./2146/rangebug.zig:2:12: note: referenced here
-    return switch (x) {
-           ^
+~ #45 | Phi                   | (unknown)   | 4 | $SwitchRangeYes_21:0 $SwitchRangeYes_36:1
+-> #42 | Phi                   | u8          | 0 | $SwitchRangeYes_19:0 $SwitchRangeYes_35:1
+~ /home/hryx/projects/software/zig/bugs/2146/rangebug.zig:2:12
+~ #46 | EndExpr               | (unknown)   | - | EndExpr(result=return,value=#45)
+-> #43 | Const                 | void        | 0 | {}
 ...
 ...
```

**Comment by hryx** [comment]
Ok, I found where this is happening and I think I know how to fix it. I'll find time to do so in the next night or two! Thank you for your patience 🦆

**Comment by LemonBoy** [comment]
My off-the-bat idea is to move the check into the `IrInstructionSwitchBr` semantic analysis phase (and make `IrInstructionCheckSwitchProngsRange` a proper `IrInstruction` so that's correctly analyzed)

**Comment by hryx** [comment]
It's a little sticky, but here's what I did to address it, and the new problem that came up that I'm now debugging.

We want to validate the prongs and their ranges before we convert the ranges into comparisons, because comparisons can turn into tautologies and get elided. My attempted solution was to append the `CheckSwitchProngs` instruction _before_ looping over all the prongs -- incomplete because we haven't even built the list of ranges to validate yet -- and then finish filling it out _after_ looking at all the prongs.

The new problem is that it segfaults when building libuserland. In `ir_analyze_instruction_check_switch_prongs`, one of the IrInstruction's `child` instruction has become null. Maybe this is the result of an elision that happened in one of the ranges? Super not sure but will keep digging/learning.

**Comment by mikdusan** [comment]
#### reduction: `hello.zig`
```zig
export fn entry(a: u8) void {
    switch (a) { 
        1...10 => {},
        0...255 => {},
    }
}   

pub fn panic(msg: []const u8, error_return_trace: ?*@import("builtin").StackTrace) noreturn {
    while (true) {}
}
```

#### command: `zig0 build-obj hello.zig`

**Comment by hryx** [comment]
Confirmed that my last comment was a buggy attempt regardless of new elision stuff, so ignore that comment/change.

Got a lot of help from @mikdusan tonight and will try a new approach where these tautological elisions are deferred to the analysis phase. @LemonBoy this is probably what you were getting at with your last suggestion above. That seems like the proper place for it to happen, conceptually.

**Comment by mikdusan** [comment]
Just brainstorming a possible solution:

- add new IR0 instruction `CheckSwitchProngsUnconditional`
- build it inside `ir_gen_switch_expr()` just before `return ir_lval_wrap()` and can this be forced comptime?
- add `ir_analyze_instruction_check_switch_prongs_unconditional()`
- move duplicate checking from `ir_analyze_instruction_check_switch_prongs()` → `ir_analyze_instruction_check_switch_prongs_unconditional()`

**Comment by mikdusan** [comment]
> The new problem is that it segfaults when building libuserland. In `ir_analyze_instruction_check_switch_prongs`, one of the IrInstruction's `child` instruction has become null. Maybe this is the result of an elision that happened in one of the ranges?

segfault:
<details>
image
</details>

because impl of `ir_analyze_instruction_check_switch_prongs()` expects an IR analysis pass to have completed for each range's start/end instructions. I haven't pin-pointed where it's covered by IR analysis code. The hint came from `alltypes.h`:
<details>
```diff
  struct IrInstruction {
      Scope *scope;
      AstNode *source_node;
      LLVMValueRef llvm_value;
      ZigValue *value;
      uint32_t debug_id;
      // if ref_count is zero and the instruction has no side effects,
      // the instruction can be omitted in codegen
      uint32_t ref_count;
!     // When analyzing IR, instructions that point to this instruction in the "old ir"
!     // can find the instruction that corresponds to this value in the "new ir"
!     // with this child field.
!     IrInstruction *child;
      IrBasicBlock *owner_bb;
      // Nearly any instruction can have to be stored as a local variable before suspending
      // and then loaded after resuming, in case there is an expression with a suspend point
      // in it, such as: x + await y
      IrInstruction *spill;
      IrInstructionId id;
      // true if this instruction was generated by zig and not from user code
      bool is_gen;

      // for debugging purposes, these are useful to call to inspect the instruction
      void dump();
      void src();
  };
```
</details>

**Comment by LemonBoy** [comment]
>  I haven't pin-pointed where it's covered by IR analysis code

The semantic analysis doesn't touch the ranges (if you look closely they're not even proper IrInstruction subclasses!) and everything works just fine for "proper" ranges because the literal ends up in the BinOp instruction, that's where it gets analyzed.

**Comment by mikdusan** [comment]
@LemonBoy, thanks for the explanation!

@hryx, I managed to insert unconditional (and mostly redundant) CheckSwitchProngs with this patch: https://github.com/mikdusan/zig/commit/87e49dd83da58ff434eb11b72c58c1b28f1a9d05

**Comment by hryx** [comment]
Thanks both of you for the input.

@LemonBoy I did notice that `IrInstructionCheckSwitchProngsRange` is not an actual instruction, but I took that fact for granted -- I'm still missing some fundamental understanding of the IR system. I've been trying to learn the implications of appending an IR instruction vs. just calling `ir_resolve_const` willy-nilly, but it seems the rabbit hole goes deep. I don't yet understand what affect the order of instructions has, what `ir_build_ref` does, etc.

Should there be a new IR instruction so that resolving ranges happens in analysis instead of in `ir_gen_switch`?

Tangential question: Why does it ir_gen_switch_expr` need to iterate over non-range (case-only) prongs separately? It's not clear to me why this needs to be split into two loops.

**Comment by mikdusan** [comment]
> Tangential question: Why does it ir_gen_switch_expr need to iterate over non-range (case-only) prongs separately? It's not clear to me why this needs to be split into two loops

because the general approach is to setup like this:

1. canonicalize the else/ranged to if/branches
2. canonicalize the true value-branch-prongs (value to branch associates) to formal switch. These need to  be together and no longer intertwined with else/ranged prongs.

Mapping to LLVM's switch instruction is now straight forward.

**Comment by andrewrk** [comment]
Still a draft; no changes for 1 month. I'm putting the ball back in your court @hryx  :basketball: 

please re-open whenever you want!

**Pull request closed without merging**
