### PR TITLE
Allow for all integer types up to 128 bits.

### PR DESCRIPTION
**Pull request by BarabasGitHub**
I also tried to find the code for integer types or anything in the self hosted compiler but I couldn't find it.

Will it automatically link this to the issue now that I put the # in the branch name? I guess not. Does this work? #745

### CODE REVIEW

**Comment by BarabasGitHub** [comment]
Oops, I didn't run all the tests.

**Comment by BarabasGitHub** [comment]
I'll try to take a look at the IntType.

**Comment by BarabasGitHub** [comment]
Meh, as far as I can see that means I've to parse the variable name in Ir.cpp unless I it can be intercepted somewhere before.

**Comment by andrewrk** [comment]
I agree with @tiehuis. To solve #745 we do need to have a table of lazily generated int types, and we do need to parse the variable name just before looking it up in the primitive type table. Although we probably will pre-generate the common ones and keep references to them for convenience. 

I'd be happy to prioritize this issue; I could knock it out pretty quickly since I have all the quirks memorized. Feel free to leave this PR up as motivation .

The self hosted compiler does not support integers yet :-)

**Pull request closed without merging**
