### PR TITLE
elf: add basic aarch64 and riscv64 support

### PR DESCRIPTION
**Pull request by kubkon**
cc @Rexicon226

### CODE REVIEW

**Review by Rexicon226 — APPROVED** [review]
LGTM!

Love the tests.

**Comment by Rexicon226** [comment]
Hmm, found an interesting issue.

When relocating something like this:
```
10: b7 04 00 00   lui     s1, 0
          0000000000000010:  R_RISCV_HI20 empty.value
14: 83 a4 04 00   lw      s1, 0(s1)
          0000000000000014:  R_RISCV_LO12_I       empty.value
```
with this PR, i get output that seems that not split up the difference correctly.
```
8000010: b7 04 00 10   lui     s1, 65536
8000014: 83 a4 04 00   lw      s1, 0(s1)
```

Whereas when I use the same isel (`build-obj`) -> use lld to link, I get:
```
111d8: b7 34 01 00   lui     s1, 19
111dc: 83 a4 04 28   lw      s1, 640(s1)
```

Might be nothing, might be my fault. Don't know yet. Just want to document it.

**Comment by Rexicon226** [comment]
Another data point:
Using `zld` instead of `lld` provides sane results:
image

Issue is with the upstream then?

**Comment by kubkon** [comment]
The CI failures are due to a bug in QEMU version we are using which was already reported by me upstream and fixed: https://gitlab.com/qemu-project/qemu/-/issues/1952 It looks like we are using QEMU 6.1 while the fix landed in 8.2. How about we update the QEMU version we are using in the CI to 8.2 then? cc @andrewrk @mikdusan

**Comment by mikdusan** [comment]
> How about we update the QEMU version we are using in the CI

- bumped https://github.com/ziglang/qemu-static to qemu 8.2.1
- I have artifact `qemu-linux-x86_64-8.2.1.tar.xz` available or just follow the readme to build

**Comment by andrewrk** [comment]
Thanks @mikdusan.

@kubkon - both x86_64-linux CI machines, and hence all the x86_64-linux runners, now have that qemu version available in `~/deps/`, so you can go ahead and update the files in ci/* in this PR.

**Comment by Rexicon226** [comment]
thanks @andrewrk :D

**Pull request merged**
