### PR TITLE
build: populate output arguments of run step with side effects

### PR DESCRIPTION
**Pull request by Techatrix**
A run step that has been declared to have side effects does not set output arguments so they are left empty.

The following `build.zig` can reproduce the issue by attempting to copy itself into the zig-cache using `cp`.
```zig
const std = @import("std");

pub fn build(b: *std.Build) void {
    const run_cp = b.addSystemCommand(&.{"cp"});
    run_cp.has_side_effects = true;
    run_cp.addFileArg(.{ .path = "build.zig" });
    _ = run_cp.addOutputFileArg("output.zig");

    b.getInstallStep().dependOn(&run_cp.step);
}
```

```
cp: cannot create regular file '': No such file or directory
install
└─ run cp (output.zig) failure
error: the following command exited with error code 1:
cp /home/techatrix/repos/zig/build.zig  
Build Summary: 0/2 steps succeeded; 1 failed (disable with --summary none)
install transitive failure
└─ run cp (output.zig) failure
error: the following build command failed with exit code 1:
zig-cache/o/71256c9453f9a834cb566e8cda508c21/build /home/techatrix/repos/zig/build/stage3/bin/zig /home/techatrix/repos/zig zig-cache /home/techatrix/.cache/zig --seed 0x3ff1fdef -Zf8b6314e1b1d03fd
```

### CODE REVIEW

**Comment by castholm** [comment]
Relevant issue: #18281

I was looking into this a while back and I also had the initial idea of moving this chunk of code up to before the early return, but I was worried that this may inadventently end up creating a lot of garbage in `zig-cache/tmp/` that isn't automatically cleaned up. A responsible build script might use `Step.RemoveDir` (which would probably need to be updated to work with `LazyPath`s) to clean up intermediary run step output, but I'm wondering if the `zig build` process itself should clean up these temporary files before exiting.

**Comment by mkpoli** [comment]
I also run into this problem where I wanted to generate a file with current time as a side effect, so it should always be rebuilt.

The temporary solution worked for me is to simply add the time as an argument (without even using it), so it effectively equivalent to `has_side_effects` that always rebuild rather than being cached.
```zig
const tool = b.addExecutable(.{ .name = "generate_time", .root_source_file = .{ .path = "tools/generate_time.zig" }, .target = b.host });
const tool_step = b.addRunArtifact(tool);
const output = tool_step.addOutputFileArg("version.zig");

tool_step.addArg(try std.fmt.allocPrint(std.heap.page_allocator, "{d}", .{std.time.timestamp()}));
```

**Review by andrewrk — CHANGES_REQUESTED** [review]
Thank you and I'm sorry for the delayed review, but this needs a new test case before being merged.

**Comment by Techatrix** [comment]
Superseded by #20488

**Pull request closed without merging**
