### PR TITLE
std: add std.ArrayList.remove

### LINKED ISSUE #2247: Add std.ArrayList.remove
There should be a function `std.ArrayList.remove` that moves fields down to fill the empty space.

It may be useful to add a backwards iterator at the same time.

### PR DESCRIPTION
**Pull request by daurnimator**
Closes #2247 

Required for a sensible http headers object.

### CODE REVIEW

**Comment by andrewrk** [comment]
I'm on board with adding this function, but since it has an important caveat of O(N) performance, I'd like to request the following changes:
 * a name that makes it sound like not one of the "main" operations of `ArrayList`. For example `removeElementByShifting`. I'm open to other names as well.
 * add documentation comments for the function mentioning O(N) and explaining how the function is implemented.

**Comment by daurnimator** [comment]
I was thinking that it would be good if zig container types all had the same API (for operations they support), with big-O behaviour documented in e.g. a table. [Similar to C++](http://www.cplusplus.com/reference/stl/)

`.remove` is already supported by
  - hash_map
  - priority_queue
  - rb
  - linked_list
  - atomic/queue

**Comment by andrewrk** [comment]
> I was thinking that it would be good if zig container types all had the same API (for operations they support)

Please take this question earnestly - I'm not trying to be condescending - can you explain this reasoning? Other than a vague sense of tidiness that one gets from cleaning their room.

**Comment by vgmind** [comment]
I guess being explicit here is important as there is more than one valid way to remove an element from an ArrayList. There's the shift method being implement here that has certain run time characteristics that people with large arrays may not like but keeps the original order. Then there is the swap with the last element and just decrease the size, not great if you need to keep your Array list ordered but has constant performance characteristics.

**Comment by Tetralux** [comment]
See https://github.com/ziglang/zig/issues/2247#issuecomment-488771675.

**Comment by andrewrk** [comment]
@daurnimator you good with `orderedRemove`?

**Comment by daurnimator** [comment]
> @daurnimator you good with `orderedRemove`?

I'm okay with it; I'd still like to call it `.remove`, I've been meaning to do a write up on why; though we can make a new issue for that if we can merge this now?

**Pull request merged**
