### PR TITLE
added -- to pass args to zig build commands

### PR DESCRIPTION
**Pull request by emekoi**
fixed version of #3527. there may be some issues on osx or linux due to #1814.

### CODE REVIEW

**Comment by andrewrk** [comment]
Instead of mixing the arg iterator and the argsAlloc(), how about doing argsAlloc() unconditionally, and using that for everything?

**Comment by emekoi** [comment]
what about using `argsAlloc` to populate an `ArrayList` via `fromOwnedSlice`?

**Comment by andrewrk** [comment]
What problem does introducing an ArrayList solve?

**Comment by emekoi** [comment]
should i remove `ArgIterator.index` then?

**Comment by andrewrk** [comment]
Yes I'm suggesting to avoid ArgIterator entirely and rely only on process.argsAlloc(). I think this will be overall simpler now that we want a slice of the remaining args.

**Comment by faerryn** [comment]
Should `if (b.args) |args| run_cmd.addArgs(args);` be included in `lib/std/special/init-exe/build.zig` after `const run_cmd` is declared?
This would use this pull request's feature by default, which may be good.

**Pull request merged**
