### PR TITLE
os: implement `os.getenv` for windows

### PR DESCRIPTION
**Pull request by kcbanner**
Closes https://github.com/ziglang/zig/issues/8456

### CODE REVIEW

**Comment by kcbanner** [comment]
@squeek502 question for you: Is it correct to use `eqlIgnoreCaseUtf8` here? The docs for `_environ` state it's a list of MBCS strings: <https://learn.microsoft.com/en-us/cpp/c-runtime-library/environ-wenviron?view=msvc-170>, and I'm not sure if it's valid to compare them like this.

**Comment by squeek502** [comment]
Unsure, will have to check. This part of the docs also seems like a potential problem:

> in a program that uses wmain, _environ is initially NULL because the environment is composed of wide-character strings. On the first call to _getenv or _putenv, a corresponding multibyte-character string environment is created and is pointed to by _environ.

**Comment by squeek502** [comment]
I don't think this is implementable on Windows.

With this test code:

```
const std = @import("std");

pub fn main() void {
    const path = std.os.getenv("славься");
    std.debug.print("getenv(славься): {?s}\n", .{path});
}
```

```
> set СЛАВЬСЯ=1
> zig run 16464.zig -lc
getenv(славься): null
```

and when adding some debug printing to print out all the keys in `_environ`, the `СЛАВЬСЯ` is `???????`.

On Windows, MBCS doesn't necessarily mean UTF-8, as there are other multi-byte character sets like [code page 932](https://en.wikipedia.org/wiki/Code_page_932_(Microsoft_Windows)). My guess is that the encoding used to populate `_environ` might be based on the system's default code page/language setting, but I'm not totally sure.

Either way, by default, `_environ` is definitely not using UTF-8 encoding, so the only way to get proper Unicode environment keys would be via `_wenviron` (if that's even possible), which then means that the value would have to be converted from UTF-16 to UTF-8, which means it would need an allocator, which means that we're back to needing `getEnvVarOwned`.

---

So, I think the right fix here is to move the
```
    if (builtin.os.tag == .windows) {
        @compileError("std.os.getenv is unavailable for Windows because environment string is in WTF-16 format. See std.process.getEnvVarOwned for cross-platform API or std.os.getenvW for Windows-specific API.");
    }
```
branch up to the top of `std.os.getenv`, as linking `libc` doesn't change the viability of the `getenv` API on Windows.

**Comment by andrewrk** [comment]
closing abandoned draft

**Pull request closed without merging**
