### PR TITLE
CI: increase stage3 test coverage

### PR DESCRIPTION
**Pull request by andrewrk**
* Use a debug build of stage3 instead of a debug build of stage2 for
   our self-hosted compiler test coverage.
 * Move coverage from stage1 to stage3 for:
   - building self-hosted without LLVM
   - building self-hosted for 32-bit arm
   - test-compiler-rt
   - test-behavior
   - test-std
     - caveat: release mode is skipped because I observed a problem
       locally.
   - test-compare-output
   - test-asm-link
   - test-fmt

### CODE REVIEW

**Comment by kubkon** [comment]
Hmm, I wonder where this error on linux comes from:

```
...
error(link): undefined reference to symbol 'dyld_stub_binder'
error: UndefinedSymbolReference
...
```

The linker will automatically link against the `libSystem.X.tbd` provided by Zig as seen [here](https://github.com/ziglang/zig/blob/47c58cba595a8e1eddf6c87086d52691d180a103/src/link/MachO.zig#L879). Is that a misconfiguration somewhere or a miscomp perhaps?

**Comment by andrewrk** [comment]
I am able to reproduce the problem locally, by following these steps:

1. Use an x86_64 linux machine
2. Use zig-bootstrap with `x86_64-linux-musl baseline` to produce LLVM libraries for that target.
3. In the Zig source tree, `stage1/bin/zig build -p stage2 -Dskip-install-lib-files -Denable-llvm`
4. `stage2/bin/zig build -p stage3 -Dskip-install-lib-files -Dtarget=native-native-musl -Dstatic-llvm --search-prefix ~/Downloads/zig_bootstrap/out/x86_64-linux-musl-baseline`
5. `stage3/bin/zig test ../lib/compiler_rt.zig -target x86_64-macos-none`

Note that using `stage2/bin/zig test ../lib/compiler_rt.zig -target x86_64-macos-none` does not trigger the problem.

**Comment by topolarity** [comment]
No special magic, I'm afraid

I saw that the segfault was a dereference of an undefined bit pattern and followed the code back to yaml.zig where the field was supposed to be set. I got lucky when the problem [was already nearly reduced](https://github.com/ziglang/zig/blob/0efc6a35bead74b5faffbc87b446b5087f1bb99b/src/link/tapi/yaml.zig#L359-L382)

**Comment by topolarity** [comment]
BTW, that bug reproduces for me even on stage3-debug even without zig-bootstrap - the last one did too

**Comment by andrewrk** [comment]
Ah! Same here.

**Comment by andrewrk** [comment]
I tracked it down to this `error.Overflow`:

https://github.com/ziglang/zig/blob/0efc6a35bead74b5faffbc87b446b5087f1bb99b/src/link/MachO/Atom.zig#L983-L986

**Comment by topolarity** [comment]
Nice. Meanwhile, I found that the error trace is bad because `heap.rawCAlloc` really does end up calling `builtin.returnError`:

Before opt:
```llvm
; Function Attrs: nounwind uwtable
define internal fastcc void @heap.rawCAlloc({ { i8*, i64 }, i16, [6 x i8] }* noalias nonnull sret({ { i8*, i64 }, i16, [6 x i8] }) %0, %builtin.StackTrace* nonnull %1, i8* nonnull align 1 %2, i64 %3, i29 %4, i29 %5, i64 %6) unnamed_addr #0 {
Entry:
  ...
  %10 = call i8* @malloc(i64 %3)
  %11 = icmp ne i8* %10, null
  br i1 %11, label %Then, label %Else
  ...
Else:                                             ; preds = %Entry
  call fastcc void @builtin.returnError(%builtin.StackTrace* %1) #8
  ...
```
After `opt -O1`:
```llvm
; Function Attrs: nounwind uwtable
define internal fastcc void @heap.rawCAlloc({ { i8*, i64 }, i16, [6 x i8] }* noalias nocapture nonnull writeonly sret({ { i8*, i64 }, i16, [6 x i8] }) %0, %builtin.StackTrace* nonnull %1, i8* nocapture nonnull readnone align 1 %2, i64 %3, i29 %4, i29 %5, i64 %6) unnamed_addr #3 {
Entry:
  %7 = icmp ult i29 %4, 17        ; check alignment < 16
  br i1 %7, label %debug.assert.exit, label %Then.i
  ...
debug.assert.exit:                                ; preds = %Entry
  %8 = call i8* @malloc(i64 %3)
  %.not = icmp eq i8* %8, null
  call fastcc void @builtin.returnError(%builtin.StackTrace* nonnull %1) #22
  br i1 %.not, label %Else, label %Block3
  ...
```

Really scratching my head on this one.

**Pull request merged**
