### PR TITLE
[ZigBuildSystem] Allow install()ing tests

### PR DESCRIPTION
**Pull request by pixelherodev**

### CODE REVIEW

**Comment by travisstaloch** [comment]
Closes #5530

**Comment by ifreund** [comment]
This sounds super useful, though it seems like most projects will want to gate `install()`ing their tests behind a build option so that the test binaries are not installed to e.g. `/usr/bin` alongside the main binary with
```
zig build --prefix /usr install
```

**Comment by FireFox317** [comment]
I looked into the failing Windows CI, turns out this has nothing to do with this PR. I build Zig of master branch, no idea why this is passing on the master CI tho. The following error is happening: 
```
D:\Dev\Zig\zig-source\build>bin\zig.exe test ..\lib\std\process.zig --override-lib-dir ..\lib
Test [2/5] test "os.getEnvMap"...error - detected leaked allocations without matching free: 3

D:\Dev\Zig\zig-source\lib\std\special\test_runner.zig:52:46: 0x7ff71f37127a in std.special.main (test.obj)
                error.Leak => std.debug.panic("", .{}),
                                             ^
D:\Dev\Zig\zig-source\lib\std\start.zig:134:65: 0x7ff71f36373e in std.start.WinMainCRTStartup (test.obj)
    std.os.windows.kernel32.ExitProcess(initEventLoopAndCallMain());
                                                                ^
Unable to dump stack trace: FileNotFound

Tests failed. Use the following command to reproduce the failure:
D:\Dev\Zig\zig-source\build\zig-cache\o\nJZfRBazPBrNoMbgz5kswbh-SjLcVVcLz0rnH_UQnVSx6HuqhNwB-IEWBXoFChC5\test.exe

D:\Dev\Zig\zig-source\build>
```

**Comment by pixelherodev** [comment]
Triggered CI to run again via `git commit --amend && git push --force`, and hopefully the weird CI failure is gone now.

**Comment by pixelherodev** [comment]
Heck, rebased against master and re-pushed. Maybe that'll help.

**Comment by FireFox317** [comment]
@pixelherodev When I ran the std tests on my windows box I ran in the same problem. However for some reason the current CI does not detect the problem, and with your change it suddenly does. This has nothing to do with your PR

**Comment by pixelherodev** [comment]
@FireFox317 I'm 99% sure that the CI failures weren't actually related to the PR, but I'm not willing to risk it anyways. CI is working fine on other PRs, and on master, so if it's not working on this _now_ (after rebasing to master), it's worth considering we might be missing something that CI is catching (but I don't remember the failure right now, so... /shrug).

We'll find out within ~2 hours, depending on how long Azure takes.

**Comment by FireFox317** [comment]
Failed again unfortunately.

**Comment by pixelherodev** [comment]
I genuinely don't see how it can be related to the changes I made, but I also don't see how it can be anything else.

**Comment by FireFox317** [comment]
Even without this PR, current master tests fail on my machine with the same exact error. Thus we know it is not because of this PR. But for some reason it is not failing on the CI on the master branch, but only with this PR added it does (which is good, because now we have better coverage :D)

**Comment by andrewrk** [comment]
The process for encountering a flaky test is to open an issue for it then disable it (comment it out) with a link to the issue URL

**Comment by andrewrk** [comment]
I'm not convinced installing tests is the way to go here. Consider what "installing" means - the end-user's system gets the binary. Tests are explicitly to be run by the developer.

Now there is a valid use case here, which is for developers to have better access to the test binaries for testing purposes. But let's try to solve that use case without compromising the end-user's use case of not having these test binaries.

Everyone who wants this feature, can you try using `setOutputDir` (which has semi-recently been improved to cooperate with the cache system) on your test artifacts?

I'm pretty confident this is going to be the best answer here, so I'm going to close this. But will re-open if anyone pushes back.

**Comment by pixelherodev** [comment]
That makes plenty of sense to me. I think it might be worth documenting
somewhere though.

-- Email domain proudly hosted at https://migadu.com

**Comment by travisstaloch** [comment]
I would also like to see some documentation.  using `setOutputDir` doesn't seem to do anything with the latest download (0.6.0+6123201f0).  
```zig
var main_tests = b.addTest("file.zig");
main_tests.setOutputDir("test_bin");
```
```sh
zig build test 
# resulting binary ends up in 
# zig-cache/o/BB97Vg55jrVxquogqyzObhC9rLMOaUmruUi4DxXOPPKCQu6Z6rO4ZbkLExuK6UBp/test
```
Have the `setOutputDir` changes not been merged into master yet?

**Comment by squeek502** [comment]
> using `setOutputDir` doesn't seem to do anything

As far as I can tell, `setOutputDir` is ignored by tests due to this conditional:

https://github.com/ziglang/zig/blob/b25e58b0acb3153814c96161f5d6bc1fa3316800/lib/std/build.zig#L2665-L2673

That is, `output_dir` is only used when `kind != .@"test"`

**Comment by pixelherodev** [comment]
Should be an easy fix.

**Pull request closed without merging**
