### PR TITLE
fmt padding correction

### LINKED ISSUE #5401: `comptime std.fmt.bufPrint` doesn't compile
Minimal reproduction: https://godbolt.org/z/XpHG-B
```zig
const std = @import("std");

pub fn main() void {
    comptime var buf = [_]u8{0} ** 64;
    var s = comptime std.fmt.bufPrint(&buf, "{} {}", .{ "test", "123"});
    std.debug.warn("{}", .{s});
}
```

```
/opt/compiler-explorer/zig-master/lib/zig/std/fmt.zig:593:5: error: else prong required when switching on type '(enum literal)'
    switch (alignment) {
    ^
/opt/compiler-explorer/zig-master/lib/zig/std/fmt.zig:565:25: note: called from here
        return formatBuf(bytes, options, out_stream);
                        ^
/opt/compiler-explorer/zig-master/lib/zig/std/fmt.zig:414:42: note: called from here
                        return formatText(value, fmt, options, out_stream);
                                         ^
/opt/compiler-explorer/zig-master/lib/zig/std/fmt.zig:182:35: note: called from here
                    try formatType(
                                  ^
/opt/compiler-explorer/zig-master/lib/zig/std/fmt.zig:1090:15: note: called from here
    try format(fbs.outStream(), fmt, args);
              ^
<source>:5:38: note: called from here
    var s = comptime std.fmt.bufPrint(&buf, "{} {}", .{ "test", "123"});
                                     ^
<source>:3:20: note: called from here
pub fn main() void {
                   ^
```

### PR DESCRIPTION
**Pull request by data-man**

### CODE REVIEW

**Comment by Vexu** [comment]
The correct workaround would be to add `: Alignment` to line 590. However this is a common pattern and if something is not done in the compiler to try to properly cast the enum literal, similar issues will keep showing up.

**Comment by alexnask** [comment]
@Vexu Right, I was expecting the `orelse` to introduce a result location of type Alignment in this case, even at comptime.

**Comment by data-man** [comment]
Fixed differently. :)

**Comment by data-man** [comment]
I don't know what happens in the tests.

**Pull request merged**
