### PR TITLE
Remove redundant test name prefixes now that test names are fully qualified

### PR DESCRIPTION
**Pull request by squeek502**
Follow up to #19079, which made test names fully qualified.

This fixes tests that had now-redundant information in their test names. For example here's a fully qualified test name before the changes in this commit:

`priority_queue.test.std.PriorityQueue: shrinkAndFree`

and the same test's name after the changes in this commit:

`priority_queue.test.shrinkAndFree`

### CODE REVIEW

**Comment by Vexu** [comment]
A lot of these should be doctests.

**Comment by andrewrk** [comment]
I agree with @Vexu - please make the tests that are named after specific functions to be doctests. In other words, do this:
```diff
-test "atan2" { ... }
+test atan2 { ... }
```
Other than that, this is ready to be merged.

**Comment by squeek502** [comment]
How far would you like me to go with changing things to doctests? For example, is this sort of thing desired (moving top level `test "clone"` in `buf_set.zig` into the `BufSet` struct so that its a doctest of the `clone` method)?

```diff
--- a/lib/std/buf_set.zig
+++ b/lib/std/buf_set.zig
@@ -90,6 +90,23 @@ pub const BufSet = struct {
         return self.cloneWithAllocator(self.allocator());
     }
 
+    test clone {
+        var original = BufSet.init(testing.allocator);
+        defer original.deinit();
+        try original.insert("x");
+
+        var cloned = try original.clone();
+        defer cloned.deinit();
+        cloned.remove("x");
+        try testing.expect(original.count() == 1);
+        try testing.expect(cloned.count() == 0);
+
+        try testing.expectError(
+            error.OutOfMemory,
+            original.cloneWithAllocator(testing.failing_allocator),
+        );
+    }
+
     fn free(self: *const BufSet, value: []const u8) void {
         self.hash_map.allocator.free(value);
     }
@@ -115,23 +132,6 @@ test BufSet {
     try bufset.insert("z");
 }
 
-test "clone" {
-    var original = BufSet.init(testing.allocator);
-    defer original.deinit();
-    try original.insert("x");
-
-    var cloned = try original.clone();
-    defer cloned.deinit();
-    cloned.remove("x");
-    try testing.expect(original.count() == 1);
-    try testing.expect(cloned.count() == 0);
-
-    try testing.expectError(
-        error.OutOfMemory,
-        original.cloneWithAllocator(testing.failing_allocator),
-    );
-}
-
 test "clone with arena" {
     const allocator = std.testing.allocator;
     var arena = std.heap.ArenaAllocator.init(allocator);
```

**Comment by andrewrk** [comment]
It's up to your discretion how much you want to do - I'm happy to merge this either way.

But to address your question more directly, that is a change that I would like to see, either now or later.

**Comment by andrewrk** [comment]
Thanks @squeek502! This should hopefully help future contributors see the more idiomatic way to name unit tests in zig.

**Pull request merged**
