### PR TITLE
Properly reset error return trace index

### LINKED ISSUE #1923: when handling a returned error, if the expression/block does not try/return error, reset error return trace index to 0
When trying to run the first example code from #1813 with an executable that can't be found, the error trace is weird. It looks like the return address array is filled with addresses from `windowsCreateProcess`.
I believe this is due to the loop in `spawnWindows` that tries every directory from `PATH` and returns a lot of errors because the file doesn't exist.

As for why it is sometimes `PATH_NOT_FOUND` and others `FILE_NOT_FOUND`, I assume my `PATH` contains some old directories that don't exist anymore.

Example output:
```
$ zig run childprocess.zig
error: Unexpected
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:693:45: 0x7ff663ac4a97 in windowsCreateProcess (run.obj)
            windows.ERROR.PATH_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:693:45: 0x7ff663ac4a97 in windowsCreateProcess (run.obj)
            windows.ERROR.PATH_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:693:45: 0x7ff663ac4a97 in windowsCreateProcess (run.obj)
            windows.ERROR.PATH_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:693:45: 0x7ff663ac4a97 in windowsCreateProcess (run.obj)
            windows.ERROR.PATH_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:693:45: 0x7ff663ac4a97 in windowsCreateProcess (run.obj)
            windows.ERROR.PATH_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:693:45: 0x7ff663ac4a97 in windowsCreateProcess (run.obj)
            windows.ERROR.PATH_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:693:45: 0x7ff663ac4a97 in windowsCreateProcess (run.obj)
            windows.ERROR.PATH_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:693:45: 0x7ff663ac4a97 in windowsCreateProcess (run.obj)
            windows.ERROR.PATH_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:693:45: 0x7ff663ac4a97 in windowsCreateProcess (run.obj)
            windows.ERROR.PATH_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:693:45: 0x7ff663ac4a97 in windowsCreateProcess (run.obj)
            windows.ERROR.PATH_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\index.zig:2253:5: 0x7ff663aa3442 in unexpectedErrorWindows (run.obj)
    return error.Unexpected;
    ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:696:21: 0x7ff663ac4a5d in windowsCreateProcess (run.obj)
            else => return os.unexpectedErrorWindows(err),
                    ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:611:21: 0x7ff663ac34d6 in ChildProcess::ChildProcess_spawnWindows (run.obj)
                    return err;
                    ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:127:13: 0x7ff663ac09ce in ChildProcess::ChildProcess_spawn (run.obj)
            return self.spawnWindows();
            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:209:9: 0x7ff663ac01bb in ChildProcess::ChildProcess_exec (run.obj)
        try child.spawn();
        ^
D:\DEV\Zig\error-traces\childprocess.zig:5:18: 0x7ff663abff2a in main (run.obj)
  const result = try std.os.ChildProcess.exec(
                 ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
```

### PR DESCRIPTION
**Pull request by Vexu**
Currently depends on #12807 to free up two Zir instruction slots, only the last commit is relevant to this PR.

Example:
```zig
const std = @import("std");
test {
    return error.SkipZigTest;
}
fn foo() !void {
    return error.DontShow;
}
test {
    foo() catch {
        std.debug.dumpStackTrace(@errorReturnTrace().?.*);
        // return error.Second;
    };
    return error.Wtf;
}

```
With the comment:
```
Test [1/2] test_0... SKIP
Test [2/2] test_1... ./a.zig:6:5: 0x20f128 in foo (test)
    return error.DontShow;
    ^
Test [2/2] test_1... FAIL (Wtf)
./a.zig:13:5: 0x20f185 in test_1 (test)
    return error.Wtf;
    ^
0 passed; 1 skipped; 1 failed.
```
Uncommented:
```
Test [1/2] test_0... SKIP
Test [2/2] test_1... ./a.zig:6:5: 0x20f138 in foo (test)
    return error.DontShow;
    ^
Test [2/2] test_1... FAIL (Second)
./a.zig:6:5: 0x20f138 in foo (test)
    return error.DontShow;
    ^
./a.zig:11:9: 0x20f18e in test_1 (test)
        return error.Second;
        ^
0 passed; 1 skipped; 1 failed.
```

Closes #1923

### CODE REVIEW

**Comment by Vexu** [comment]
Hmm, this still doesn't handle this case properly:
```zig
const std = @import("std");
test {
    return error.SkipZigTest;
}
fn foo() !void {
    return error.DontShow;
}
test {
    foo() catch {
        foo() catch {};
        std.debug.dumpStackTrace(@errorReturnTrace().?.*);
    };
}
```

Maybe it'd be better to start off with a simplified version which always resets to zero since it handles all the common cases properly.

**Comment by topolarity** [comment]
> Hmm, this still doesn't handle this case properly:

Not sure if this is good news or bad, but I'm just finishing up an overlapping change that should handle that case correctly. It intends to implement the rest of https://github.com/ziglang/zig/issues/1923#issuecomment-1218495574 (esp. supporting `break`)

Let me know how we can best coordinate the follow-up change so that I don't step on your toes here 🙂

**Comment by Vexu** [comment]
If you have a more complete fix then let's go with that, I just want this annoyance fixed to get the full benefit of #12807

**Comment by Vexu** [comment]
Closing in favor of the more complete solution.

**Pull request closed without merging**
