### PR TITLE
`File.stat`: Support detection of `Kind.sym_link` on Windows

### PR DESCRIPTION
**Pull request by squeek502**
Requires an extra NtQueryInformationFile call when FILE_ATTRIBUTE_REPARSE_POINT is set to determine if it's actually a symlink or some other kind of reparse point (https://learn.microsoft.com/en-us/windows/win32/fileio/reparse-point-tags). This is something that `File.Metadata.kind` was already doing, so the same technique is used in `stat`.

Also, replace the std.os.windows.DeviceIoControl call in `metadata` with NtQueryInformationFile (NtQueryInformationFile is what gets called during kernel32.GetFileInformationByHandleEx with FileAttributeTagInfo, verified using NtTrace).

Addresses the last bit of https://github.com/ziglang/zig/issues/18290 that #18323 doesn't.

### CODE REVIEW

**Review by daurnimator — COMMENTED** [review]
Isn't this sort of like `AT_SYMLINK_NOFOLLOW` on unices? Should we introduce that flag as an argument across all OSes?

**Comment by squeek502** [comment]
> Isn't this sort of like AT_SYMLINK_NOFOLLOW on unices? Should we introduce that flag as an argument across all OSes?

This is in `File.stat`, meaning you already have an open file descriptor.

**Comment by squeek502** [comment]
Looks like the added test uncovered a `OpenDirOptions.no_follow` bug on MacOS.

**Comment by perillo** [comment]
@squeek502 Thanks for the PR.

Just a few question:

  1. From the Windows documentation, there are additionally parse points can be used to *emulate* POSIX .
      As an example https://en.wikipedia.org/wiki/NTFS_reparse_point#Unix_domain_socket_(socket).  Does it make sense to implement it?

  2. In `FileMetadata`, as you wrote in #18323, the implementation is *correct*.  However, what is the reason why there is no change time?

**Comment by squeek502** [comment]
>     1. From the Windows documentation, there are additionally parse points can be used to _emulate_ POSIX .
>        As an example https://en.wikipedia.org/wiki/NTFS_reparse_point#Unix_domain_socket_(socket).  Does it make sense to implement it?

If there's an example of how to go about getting a `HANDLE` to such a reparse point, that'd be helpful. Or if there's an example from another standard library that handles this case (Rust doesn't, for example; it only knows about file/directory/symlink).

>     2. In `FileMetadata`, as you wrote in [Fix `Stat.ctime` docs, and correct its value on Windows #18323](https://github.com/ziglang/zig/pull/18323), the implementation is _correct_.  However, what is the reason why there is no change time?

Likely just an oversight, the context for the `Metadata` implementation is here: https://github.com/ziglang/zig/pull/10486

**Pull request merged**
