### PR TITLE
std.fs: Absorb `IterableDir` into `Dir`

### PR DESCRIPTION
**Pull request by andrewrk**
This reverts #12060.

I was against this change originally, but approved it to keep an open mind. After a year of trying it in practice, I firmly believe that the previous way of doing it was better.

Furthermore, I took this opportunity to extract `Dir` and `AtomicFile` out from fs.zig into Dir.zig and AtomicFile.zig respectively, and also to flatten `std.fs.file.File` into `std.fs.File`.

### CODE REVIEW

**Comment by squeek502** [comment]
I think extracting `Dir` is a good change, but I think it will also increase confusion about the `Absolute` suffixed functions since they will seem like they have precedence being in the `std.fs` namespace proper (https://github.com/ziglang/zig/issues/16736).

Would like to get your thoughts [on my comment here](https://github.com/ziglang/zig/pull/16743#discussion_r1328059752) while you're thinking about `std.fs`

**Comment by nektro** [comment]
> I was against this change originally, but approved it to keep an open mind. After a year of trying it in practice, I firmly believe that the previous way of doing it was better.

**Comment by nektro** [comment]
> I was against this change originally, but approved it to keep an open mind. After a year of trying it in practice, I firmly believe that the previous way of doing it was better.

what led you to this? type safety from comptime-knowable state is a good thing

**Comment by andrewrk** [comment]
My comments on #12060 are still relevant, so check those out if you haven't already. To expand:

1. It's often, but not always, comptime-knowable whether the directory needs iterating.
2. The other directory opening flags have the same property: some subset of directory functionality is available based on their values, and they are also often but not always comptime-knowable. You can imagine that we don't want all of the following types:
    * Dir
    * IterableDir
    * AccessSubPathsDir
    * IterableAccessSubPathsDir
    * NoFollowDir
    * NoFollowIterableDir
    * NoFollowAccessSubPathsDir
    * NoFollowIterableAccessSubPathsDir
3. #16738

**Pull request merged**
