### PR TITLE
Typo: insure => ensure

### PR DESCRIPTION
**Pull request by bertie-wheen**
Noticed several instances of the same typo. In most other places it's correctly 'ensure', just not here.

### CODE REVIEW

**Comment by xdBronch** [comment]
see https://github.com/ziglang/zig/pull/19181#issuecomment-1998000935

**Comment by bertie-wheen** [comment]
Oops, accidentally fully reverted, rather than the partial revert I meant to do. Will fix!

**Comment by bertie-wheen** [comment]
Oops, reverted the wrong half of the commit. Will fix!

**Comment by bertie-wheen** [comment]
Have squashed. The commit now only fixes typos in non-vendored code.

**Comment by Daggerfall-is-the-best-TES-game** [comment]
Just some food for thought; this isn't necessarily a typo. 
the third definition of
image
and the first definition of
image
shows they are synonyms.

**Comment by bertie-wheen** [comment]
Am aware of that, but it is essentially a typo, as they're not _really_ synonyms. Insure is nearly always used for the financial/insurance meaning, whereas ensure is more correct in these cases. Even if you want to make the argument that you _can_ use "insure" for the "to make sure" meaning, it's very non-standard, and moreover is inconsistent with our choices everywhere else. Even excluding `lib/libc*`, there are ~1.5k instances of "ensure" across 200+ files, and these are the only exceptions. Particularly, there are several functions/methods that include it (e.g. `ensureTotalCapacity`, `ensureUnusedCapacity`, ...), and basically I think that - as with code style - it's better to be consistent.

**Comment by Vexu** [comment]
`lib/include` is also vendored.

**Comment by bertie-wheen** [comment]
@Vexu I've committed a revert of the `lib/include` files, but there's still the main typo, which is in `lib/init/build.zig.zon`. Can you reopen?

**Pull request closed without merging**
