### PR TITLE
zig run/cc: recognize "-x language"

### LINKED ISSUE #10915: Zig c++ does not respect -x flag
### Zig Version

0.10.0-dev.760+1a84c23d6

### Steps to Reproduce

Save the following to a file with an extension which is not generally used for C++, such as `test.foo` or `test.hpp`:

```cxx
// test

int main(void){
  return 1;
}
```

Compile with 
```bash
$ zig c++ -x c++ test.foo
```

### Expected Behavior

If the file is named `test.cpp`, it compiles just fine. I would expect that `-x c++` to emulate this behavior.

### Actual Behavior

The `zig c++` command fails:

```
ld.lld: error: test.foo:1: unknown directive: //
>>> // test
>>> ^
```

### PR DESCRIPTION
**Pull request by motiejus**
This commit adds support for "-x language" for a couple of hand-picked supported languages. There is no reason the list of supported languages to not grow (e.g. add "c-header"), but I'd like to keep it small at the start.

Alternative 1
-------------

I first tried to add a new type "Language", and then add that to the `CSourceFile`. But oh boy what a change it turns out to be. So I am keeping myself tied to FileExt and see what you folks think.

Alternative 2
-------------

I tried adding `Language: ?[]const u8` to `CSourceFile`. However, the language/ext, whatever we want to call it, still needs to be interpreted in the main loop: one kind of handling for source files, other kind of handling for everything else.

Test case
---------

*standalone.c*

    #include <iostream>

    int main() {
        std::cout << "elho\n";
    }

Compile and run:

    $ ./zig run -x c++ -lc++ standalone.c
    elho
    $ ./zig c++ -x c++ standalone.c -o standalone && ./standalone
    elho
    $ .zig/x-lang/bin/zig cc -lc++ -x c++ standalone.c -o standalone  && ./standalone 
    elho

Fixes #10915

### CODE REVIEW

**Comment by sagehane** [comment]
Does this PR work with `build.zig` too?

Something like:
```zig
    const exe = b.addExecutable("whatever", null);
    exe.addCSourceFiles(&.{
        "file1.c",
        "file2.c",
    }, &.{
        "-x c++",
    });
```
I know a bizarre project that only compiles when compiling Lua with a C++ compiler, and this would greatly help.

**Comment by N00byEdge** [comment]
wouldn't it be `"-x", "c++"`? For zig build it doesn't matter anyways, you can add cpp files aready afaik.

**Comment by motiejus** [comment]
cc @bfredl this is one of the prerequisites to compile neovim with `zig cc`.

**Comment by motiejus** [comment]
> Does this PR work with `build.zig` too?
> 
> Something like:
> 
> ```zig
>     const exe = b.addExecutable("whatever", null);
>     exe.addCSourceFiles(&.{
>         "file1.c",
>         "file2.c",
>     }, &.{
>         "-x c++",
>     });
> ```
> 
> I know a bizarre project that only compiles when compiling Lua with a C++ compiler, and this would greatly help.

Not in this PR. That could be added, but I am not sure if the approach will be accepted in the first place. So I will not extend the scope yet.

**Comment by motiejus** [comment]
@sandhose's comment from https://github.com/ziglang/zig/issues/10915#issuecomment-1355162858:

> > Can you try with #13544? I just added it to understand `assembler-with-cpp`.
> 
> @motiejus I built your PR and tried ; it fails with the following error:
> 
> ```
> $ /tmp/zig/build/stage3/bin/zig cc -target aarch64-linux-gnu -g -O0 -ffunction-sections -fdata-sections -fPIC -gdwarf-4 -fno-omit-frame
> -pointer -Wall -Wextra -xassembler-with-cpp -DCFG_TARGET_OS_linux -DCFG_TARGET_ARCH_aarch64 -DCFG_TARGET_ENV_gnu -o /tmp/aarch_aapcs64.o -c src/arch/aar
> ch_aapcs64.s
> error: language 'assembly' is unsupported in this context
> ```
> 
> To reproduce:
> 
> ```
> git clone https://github.com/rust-lang/stacker
> cd stacker/psm
> zig cc -target aarch64-linux-gnu -g -O0 -ffunction-sections -fdata-sections -fPIC -gdwarf-4 -fno-omit-frame-pointer -Wall -Wextra -xassembler-with-cpp -DCFG_TARGET_OS_linux -DCFG_TARGET_ARCH_aarch64 -DCFG_TARGET_ENV_gnu -o /tmp/aarch_aapcs64.o -c src/arch/aarch_aapcs64.s
> ```

Thanks for providing the reproducible case. I've updated the PR and it no longer throws this error. Please test the current version.

**Comment by morenol** [comment]
> @sandhose's comment from [#10915 (comment)](https://github.com/ziglang/zig/issues/10915#issuecomment-1355162858):
> 
> > > Can you try with #13544? I just added it to understand `assembler-with-cpp`.
> > 
> > 
> > @motiejus I built your PR and tried ; it fails with the following error:
> > ```
> > $ /tmp/zig/build/stage3/bin/zig cc -target aarch64-linux-gnu -g -O0 -ffunction-sections -fdata-sections -fPIC -gdwarf-4 -fno-omit-frame
> > -pointer -Wall -Wextra -xassembler-with-cpp -DCFG_TARGET_OS_linux -DCFG_TARGET_ARCH_aarch64 -DCFG_TARGET_ENV_gnu -o /tmp/aarch_aapcs64.o -c src/arch/aar
> > ch_aapcs64.s
> > error: language 'assembly' is unsupported in this context
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > To reproduce:
> > ```
> > git clone https://github.com/rust-lang/stacker
> > cd stacker/psm
> > zig cc -target aarch64-linux-gnu -g -O0 -ffunction-sections -fdata-sections -fPIC -gdwarf-4 -fno-omit-frame-pointer -Wall -Wextra -xassembler-with-cpp -DCFG_TARGET_OS_linux -DCFG_TARGET_ARCH_aarch64 -DCFG_TARGET_ENV_gnu -o /tmp/aarch_aapcs64.o -c src/arch/aarch_aapcs64.s
> > ```
> 
> Thanks for providing the reproducible case. I've updated the PR and it no longer throws this error. Please test the current version.

I tried this branch and it worked for me

**Comment by kassane** [comment]
Is it intended to add support to `-x c++-modules` too?

**Comment by motiejus** [comment]
> Is it intended to add support to `-x c++-module` too?

Once this is merged, you are welcome to do so, should be relatively easy if you have a use case.

From my experience with working on this, it's difficult to add an extension without good understanding and example on how it will be used.

**Review by andrewrk — CHANGES_REQUESTED** [review]
Excellent work. I see only one more thing to be done before merging, which is to add the new field `ext` to the cache hash in the `addNonIncrementalStuffToCacheManifest` (search for `extra_flags`).

**Pull request merged**
