### PR TITLE
Add `std.debug.print` for formatted printing to StdOut

### PR DESCRIPTION
**Pull request by ForLoveOfCats**
A friend was resorting to using C's `printf` in order to print formatted output to StdOut so I figured this sort of thing might as well be in the std. Should it be in a different namespace or have a different name?

Sidenote: I think that the doc comments for `warn` and this are in the wrong location?

### CODE REVIEW

**Comment by daurnimator** [comment]
This can be nicer since 0237e7a701892a0bf3c57e6868f54421782ff91d.

Note, I've got a PR coming soon that will let you do: `try io.getStdOut().print(.....)`; will that be sufficient?

**Comment by ForLoveOfCats** [comment]
I figured that this would require a rework, I'd head about those changes on the grapevine. I guess I'll rebase, rewrite, and force push. I doubt that this will be merged though. It's such a minor change that can be done outside std, it hasn't even been triaged.

**Comment by ForLoveOfCats** [comment]
Okay this has been updated and I "fixed" the position of the doc comments on warn and this new print.

**Comment by ForLoveOfCats** [comment]
Fudge, no. Ignore me. It's still getting stderr 🤦‍♂

**Comment by andrewrk** [comment]
Here's where the direction that `std.debug.warn` API is headed in: #2586

There won't be a global stdout printing API in the standard library. It will be up to applications to coordinate with libraries on how they want to do this.

**Pull request closed without merging**
