### PR TITLE
Merge pull request #1 from ziglang/master

### PR DESCRIPTION
**Pull request by ityonemo**
makes this one member function public; making it public affords access to the structured data of the stacktrace for other systems besides std, without having to serialize and deserialize out of string formats.

### CODE REVIEW

**Comment by LemonBoy** [comment]
This PR is empty?

**Comment by andrewrk** [comment]
This looks like a mistake - looking forward to the real PR

**Comment by ityonemo** [comment]
oops. I must have done 'git stash' without realizing it.

**Comment by ityonemo** [comment]
superceded by https://github.com/ziglang/zig/pull/7294

**Pull request closed without merging**
