### PR TITLE
std.fmt.comptimePrint: Return null terminated string

### PR DESCRIPTION
**Pull request by tadeokondrak**
Same reason as string literals are null terminated.
I don't need to explicitly set the 0 even if the array is undefined, right?

### CODE REVIEW

**Comment by daurnimator** [comment]
> Same reason as string literals are null terminated.

What is this reason? I don't think its actually recorded anywhere?

>  I don't need to explicitly set the 0 even if the array is undefined, right?

I think you do.

**Comment by ifreund** [comment]
Is this really needed? `++ "\x00"` isn't hard to add when null termination is required.

**Comment by tadeokondrak** [comment]
> What is this reason? I don't think its actually recorded anywhere?

Well, the reason over having a separate `comptimePrint0` is that if we don't really mind having a null terminator after every string literal in the language, why split the API into two when we can just have one that always null terminates?

> I think you do.

Is `buf[buf.len] = 0` allowed? I still don't really understand sentinel-terminated arrays.

> Is this really needed? ++ "\x00" isn't hard to add when null termination is required.

Well, casting it to a null terminated string also requires `s[0..s.len - 1:0]`.

**Comment by ifreund** [comment]
> Is buf[buf.len] = 0 allowed? I still don't really understand sentinel-terminated arrays.

Yes that's the way to do it. See e.g. `Allocator.dupeZ()`.

> Well, casting it to a null terminated string also requires s[0..s.len - 1:0].

Fair enough.

**Comment by katesuyu** [comment]
> > Same reason as string literals are null terminated.
> What is this reason? I don't think its actually recorded anywhere?
Interop with C is common enough that it's important for there to be null terminated string literal syntax, as there was in previous versions of Zig (`c"abc"` iirc). However, given it's useful to be able to use a string in both C and Zig, what you actually want from such a string literal is a sentinel-terminated slice, which is usable both as a normal slice and an argument to a C function that expects a null-terminated string. At which point why not just have this be the default string literal, since it works in all contexts? I believe that's why our string literals are all null terminated.

Of course, I would expect the null byte to be elided during compilation if it is never actually needed.

**Pull request merged**
