### PR TITLE
std/crypto: API cleanup

### LINKED ISSUE #5851: use arrays instead of slices when the length is compile time known in std.crypto APIs
Currently, most of the crypto algorithms in the standard library use slices for input/output parameters, even in cases where the input/output has a fixed size. Is there any reason for using a slice, or would a pointer to a fixed-size array be more appropriate?

For example, `AES.encrypt` has a signature `pub fn encrypt(ctx: Self, dst: []u8, src: []const u8) void`, but `dst` and `src` both refer to a single 16-byte block, so using `pub fn encrypt(ctx: Self, dst: *[16]u8, src: *[16]const u8) void` makes more sense.

### PR DESCRIPTION
**Pull request by zigazeljko**
Closes #5851

### CODE REVIEW

**Comment by jedisct1** [comment]
Thank you! These are great changes!

I'm not sure that we should change the MAC API though.

`KMAC`, for example, supports arbitrary long output, that may not be known until finalization.

So maybe keeping the current interface for MACs would be better.

**Comment by zigazeljko** [comment]
> I'm not sure that we should change the MAC API though.

All the other MAC functions (GHASH, Poly1305, SipHash) already use this API.

**Comment by jedisct1** [comment]
Yes, but HMAC is not a MAC with a fixed output length, it's a generic construction. I'm not sure that we should constraint its output to a fixed length.

**Comment by andrewrk** [comment]
I support #5851 and happy to merge this when you two come to an agreement on the PR.

**Comment by zigazeljko** [comment]
> Yes, but HMAC is not a MAC with a fixed output length, it's a generic construction.

Yes, but each concrete type of HMAC (such as `HmacSha256`) **is** a MAC with a fixed output length. And my PR correctly chooses the output parameter type based on the `Hash` parameter (e.g. in `HmacSha1`, the signature will be `pub fn final(ctx: *Self, out: *[20]u8) void`, and in `HmacSha256`, the signature will be `pub fn final(ctx: *Self, out: *[32]u8) void`).

Is that what you had in mind or am I missing something?

**Comment by jedisct1** [comment]
Alright let's merge it, then :)

**Pull request merged**
