### PR TITLE
Increase io.BufferedInStream readByte speed by ~75%

### PR DESCRIPTION
**Pull request by frmdstryr**
Improves readByte speed from ~125MB/s to ~220MB/s. See #3840

### CODE REVIEW

**Comment by daurnimator** [comment]
Could you compare to my FIFO pr?

**Comment by andrewrk** [comment]
Semi-related: https://godbolt.org/z/XpA-g-

LLVM does not seem to have a problem with `@fieldParentPtr` or our interface pattern.

**Comment by frmdstryr** [comment]
@daurnimator , I cloned the branch from #3763 built it and ran the `readBufferedInStream` fn from #3840 with -Drelease-fast=true and got:

```
578323968 bytes (578 MB, 552 MiB) copied, 7.66603 s, 75.4 MB/s
```

**Comment by frmdstryr** [comment]
It would be good to have some sort of  benchmark test suite to check performance over time

**Comment by andrewrk** [comment]
Yep, definitely. I'll set that up eventually, but also if any community member(s) wanted to run their own set of benchmarks that would be most welcome

**Pull request merged**
