### PR TITLE
Make it more convenient to define new tests

### PR DESCRIPTION
**Pull request by pixelherodev**

### CODE REVIEW

**Comment by andrewrk** [comment]
This turns a declarative set of cases into something that requires being aware of state. Can you make a case for why this is an improvement?

**Comment by pixelherodev** [comment]
It makes it more convenient to define a number of tests for the same platform in a row, which is a very common pattern. e.g. if we're adding 100 linux-x64 tests, we only need to to tell the harness the platform once instead of for each one. It means that if we e.g. sort tests by platform into different files, each *file* needs to declare the platform, instead of each individual case.

I see your objections to this though, and I admit I fully agree. I think I may have taken the convenience too far here. Should I look for a better way, or just close this?

**Comment by andrewrk** [comment]
It's not a common pattern though. Look at how often it is done for stage1 tests - out of thousands of tests, only 3-4 are target specific

**Comment by pixelherodev** [comment]
I might come at this again soonish with a cleaner approach, but this definitely isn't the way to go.

**Pull request closed without merging**
