### PR TITLE
Fully static stage1 compiler on windows

### LINKED ISSUE #3391: the windows zig binaries from the download page dynamically link vcredist140.dll instead of static linking
Just downloaded and tried to build the hello.zig example, but when I did in the terminal (Powershell/cmd), got no output at all. At a whim I doubleclicked zig.exe and got an errormessage for missing the vcredist140 dll - so downloaded the latest VC runtime, and now it works. Would be nice if there was a heads-up in the documentation. :)

### PR DESCRIPTION
**Pull request by Sahnvour**
Fixes #3391.

This doesn't enable linking debug zig with release llvm yet but I still plan to do it soon.

### CODE REVIEW

**Comment by andrewrk** [comment]
Next steps:
 * Update https://github.com/ziglang/zig/wiki/How-to-build-LLVM,-libclang,-and-liblld-from-source#windows correspondingly
 * Update https://ziglang.org/deps/llvm+clang-9.0.0-win64-msvc-release.tar.xz
 * Rebuild this branch in the CI and make sure it works

**Comment by Sahnvour** [comment]
@andrewrk wiki updated, I can provide a static build of llvm+clang if you wish.

**Comment by andrewrk** [comment]
Thanks @Sahnvour. I started a build based on the new instructions. It will probably be ~12 hours before the new tarball is in place.

>  I can provide a static build of llvm+clang if you wish.

I'll be happy to set up you ~the bomb~ with S3 permissions at some point so that you can do this. The UI for that is annoying though and I don't have enough patience today for it, so for now I'll take care of uploading this tarball.

**Comment by andrewrk** [comment]
Continued in a branch in this repository here: #3467

**Pull request closed without merging**
