### PR TITLE
Musl mistranslation fix in math.complex (partial subset from #20346)

### PR DESCRIPTION
**Pull request by expikr**
@tiehuis 

Also copied over the straight changes to ldexp, exp, and sinh so as to not conflict due to change in the inner impl signatures.

### CODE REVIEW

**Review by andrewrk — CHANGES_REQUESTED** [review]
PR lacks testing methodology, motivation, and a useful title.

To merge this PR would involve more work than doing all of these things myself.

**Comment by tiehuis** [comment]
Sorry for my late response here. I have reviewed the specific musl corrections against upstream and these are valid and what I would like to merge. This change however is a little larger than I expected though due to trying to retain the signatures as well in the other PR.

I don't mind making these changes directly in a smaller isolated PR and then reviewing the full set of api changes on its own. I'm happy to do this as well, you will just need to rebase your PR if so.

Otherwise I will set aside some time this weekend to look at #20346 fully.

**Comment by tiehuis** [comment]
You could compare against musl and take the inputs. I was thinking follow through the implementations (e.g. sqrt/tanh) and construct some additional test inputs for branches which are currently untested.

e.g. https://github.com/ziglang/zig/blob/b705146aecd17dd8caf63766deef38a2b762594e/lib/std/math/complex/cosh.zig#L125

**Comment by andrewrk** [comment]
Author has not complied with my request to limit to 1 open PR at a time, is now in timeout for 1 year.

**Pull request closed without merging**
