### PR TITLE
unembed ConstExprValue from IrInstruction and intern 1-possible-value types

### PR DESCRIPTION
**Pull request by mikdusan**
- this PR has 3 commits
- memory report with maximum resident size for (uncached) test is as follows:

host: macOS 10.15.1
command: `gtime -v zig -fmem-report --cache off --output-dir zig-cache -fmem-report test lib/std/std.zig`

#### commit: rename ConstExprValue → ZigValue
```
Const: 7073345 items, 144 bytes each, total 971.38 MiB
ConstGlobalRefs: 18701697 items, 24 bytes each, total 428.05 MiB
ResetResult: 1750877 items, 152 bytes each, total 253.80 MiB
ZigValue: 3150835 items, 80 bytes each, total 240.39 MiB
Unknown_8: 29310030 items, 8 bytes each, total 223.62 MiB
EndExpr: 1383963 items, 160 bytes each, total 211.18 MiB
VarPtr: 1147147 items, 160 bytes each, total 175.04 MiB
Unknown_64: 2211102 items, 64 bytes each, total 134.95 MiB
IrBasicBlock: 811038 items, 120 bytes each, total 92.82 MiB
LoadPtr: 572389 items, 152 bytes each, total 82.97 MiB
...
Maximum resident set size (kbytes): 4815564
Elapsed (wall clock) time (h:mm:ss or m:ss): 0:24.82
```

#### commit: unembed ZigValue from IrInstruction
```
ZigValue: 18714968 items, 80 bytes each, total 1.39 GiB
Const: 7073345 items, 72 bytes each, total 485.69 MiB
ConstGlobalRefs: 18701697 items, 24 bytes each, total 428.05 MiB
Unknown_8: 29310030 items, 8 bytes each, total 223.62 MiB
Unknown_64: 2211102 items, 64 bytes each, total 134.95 MiB
ResetResult: 1750877 items, 80 bytes each, total 133.58 MiB
EndExpr: 1383963 items, 88 bytes each, total 116.15 MiB
VarPtr: 1147147 items, 88 bytes each, total 96.27 MiB
IrBasicBlock: 811038 items, 120 bytes each, total 92.82 MiB
Unknown_40: 1905533 items, 40 bytes each, total 72.69 MiB
...
Maximum resident set size (kbytes): 4985284
Elapsed (wall clock) time (h:mm:ss or m:ss): 0:26.69
```

#### commit: const interning for 1-possible-value types
```
ZigValue: 14729595 items, 80 bytes each, total 1.097 GiB
Const: 7073345 items, 72 bytes each, total 485.688 MiB
ConstGlobalRefs: 14716324 items, 24 bytes each, total 336.830 MiB
Unknown_8: 29310030 items, 8 bytes each, total 223.618 MiB
Unknown_64: 2211102 items, 64 bytes each, total 134.955 MiB
ResetResult: 1750877 items, 80 bytes each, total 133.581 MiB
EndExpr: 1383963 items, 88 bytes each, total 116.147 MiB
VarPtr: 1147147 items, 88 bytes each, total 96.272 MiB
IrBasicBlock: 811038 items, 120 bytes each, total 92.816 MiB
Unknown_40: 1905533 items, 40 bytes each, total 72.690 MiB
...
undefined: interned 3124 times
void: interned 3973372 times
null: interned 3533 times
unreachable: interned 5344 times
...
Maximum resident set size (kbytes): 4535756
Elapsed (wall clock) time (h:mm:ss or m:ss): 0:26.12
```

net maximum RSS savings for PR: `273 MiB`

### CODE REVIEW

**Comment by andrewrk** [comment]
Related: #471. 

Note that the "Total bytes used" in our memory report does not include external things such as LLVM or the implementation of malloc(). The target goal of 3.5 GiB is peak resident memory as measured by the parent process, e.g. `time -v`.

So we have a realistic goal here: reduce usage by 0.8 GiB.

**Comment by mikdusan** [comment]
progress update (uncommitted work)

#### the good
- `ir_build_const_void()` accounts for 154,165 intern hits
- `ir_const_void()` accounts for over 3,000,000 intern hits
- this alone bought and paid for the unembedding penalty

#### the bad
- had to disable `ZigValue` interning for anything with more than 1 possible value
- still investigating why; I think the value may be getting mutated and may have to write a custom mmap allocator to make memory read-only to identify offending code

#### base reference (rename commit)
- Maximum resident set size (kbytes): 4359304

#### unembed commit
Maximum resident set size (kbytes): 4524828

#### 1-possible-value intern
Maximum resident set size (kbytes): 4090136
void: interned 3867723 times
undefined: interned 3160 times
null: interned 3428 times
bool: interned 0 times
int: interned 0 times
comptime_int: interned 0 times
enum_literal: interned 0 times
fn: interned 0 times
type: interned 0 times
unreachable: interned 5312 times

**Comment by mikdusan** [comment]
- rebased from master all the commits
- added a WIP commit that may help in the future if we solve for non-1-possible-values
- cleaned up interning commit

**Comment by mikdusan** [comment]
ugh. I forgot to add memory stats to the final commit
- pending review I'd like to add the following to commit message BEFORE any merge to master

```
ZigValue: 14794797 items, 80 bytes each, total 1.102 GiB
Const: 7106784 items, 72 bytes each, total 487.984 MiB
ConstGlobalRefs: 14781526 items, 24 bytes each, total 338.322 MiB
Unknown_8: 29466664 items, 8 bytes each, total 224.813 MiB
ResetResult: 1762005 items, 80 bytes each, total 134.430 MiB
EndExpr: 1394227 items, 88 bytes each, total 117.008 MiB
VarPtr: 1153951 items, 88 bytes each, total 96.843 MiB
IrBasicBlock: 813103 items, 120 bytes each, total 93.052 MiB
Unknown_64: 1328728 items, 64 bytes each, total 81.099 MiB
Unknown_40: 1929697 items, 40 bytes each, total 73.612 MiB
...
undefined: interned 3109 times
void: interned 3996082 times
null: interned 3527 times
unreachable: interned 5422 times
...
Maximum resident set size (kbytes): 4531324
Elapsed (wall clock) time (h:mm:ss or m:ss): 0:24.96
```

**Comment by mikdusan** [comment]
amended last commit with memory report; here's the state of memory usage concerning this PR:

commit | descr | Maximum resident set size (kbytes)
---|---|---
ad0871ea4bf2dfbed07282ffe14738b5347d5d32 | master (baseline) | 4788812
8517baa6e0676e6fa39a04d46dd09e29181bfc05 | unembed ZigValue from IrInstruction | 4951384
3a721e94fc9e2a5c1275658da3431e6f59e2b3fa | const interning for 1-possible-value types | 4531324

summary: **256MB RSS reduction**

**Comment by mikdusan** [comment]
- rebased against master
- removed memory report from commit messages (PR is the right place)

**Pull request merged**
