### PR TITLE
Fix silent zig fmt errors

### PR DESCRIPTION
**Pull request by danielchasehooper**
`zig fmt` would silently fail for paths that didn't exist. This caused me significant confusion when I was trying to format a file but I had a typo in the name - the command looked like it succeeded in the terminal, but the file wasn't changing.

The problem was due to using the warn log level for the error - in `.ReleaseSafe` and `.ReleaseFast` build modes `.warn` messages aren't printed. I think it's fair to use the error level since `FileNotFound` errors like this cause `zig fmt` to produce a nonzero exit code.

### CODE REVIEW

**Comment by danielchasehooper** [comment]
The test failures seem to be unrelated to this change

**Comment by mlugg** [comment]
Why do you believe the failures unrelated to this change? That's a quite weird argument to make when *all 10 runs* failed in the exact same manner as one another, with each one reporting a formatting error *in precisely the file you changed*. As it is, the code you have written does not obey `zig fmt`.

**Comment by danielchasehooper** [comment]
>  That's a quite weird argument to make 
Sorry wasn't trying to argue, was an honest misreading of the test output. Just trying to help. 

I've run `zig fmt`.

**Comment by mlugg** [comment]
Sorry, by "argument" I just meant "point"/"reason" here, I didn't mean for it to be interpreted as an accusation. Thanks!

**Comment by andrewrk** [comment]
Thanks!

**Pull request merged**
