### PR TITLE
(WIP) Progress Bar for 3rd Party Packages

### PR DESCRIPTION
**Pull request by VeroAsghar**
Currently, the total number of dependencies is displayed along with the current iteration. When "content-length" is accessable, that is displayed (in bytes?) along with the dependency name. When encountering a subdependency, another counter is displayed with the name "{parent}.{child}" along with the subdependency count. However, the parent iteration is not incremented. Currently trying to find a fix for that.

### CODE REVIEW

**Comment by VeroAsghar** [comment]
#16463

**Comment by VeroAsghar** [comment]
Current Impl Example:
```
downloading packages... [1/5] libz...
downloading packages... [2/5] libmp3lame...
downloading packages... [3/5] libvorbis...
downloading packages... [3/5] libvorbis [1/1] libvorbis.libogg...
downloading packages... [5/5] nasm...
```

**Comment by andrewrk** [comment]
> Current Impl Example:

to be honest, it looks kind of clunky. Can it be more pretty?

P.S. you can use https://asciinema.org/ to share a terminal recording.

**Comment by mlugg** [comment]
I don't think transitive dependencies should use nested progress indicators like this for two reasons:
- Package hierarchies may have shared transitive dependencies, which we only have to download once.
- Package hierarchies may be arbitrarily deep, cluttering the on-screen output.

Instead, when we fetch a package and discover its dependencies, the root progress node should have its total updated - all package fetches should be done under the main progress node. (`std.Progress.Node.setEstimatedTotalItems` is the API you'd want there.)

> to be honest, it looks kind of clunky. Can it be more pretty?

For the record, I believe (and expressed to the creator of this PR) that having a kinda-ugly progress bar in for 0.11 (which we can improve upon later) will be much better than waiting until 0.12 for a nicer one, simply to avoid confusion over the coming months

**Comment by VeroAsghar** [comment]
Thank you for the feedback!

Oh I forgot! One thing I should have made clear: the current implementation will overwrite itself on the terminal line as is common with the `std.Progress` API. I just wanted to show how each stage of the output looks currently. I’ll make sure in the future to accurately label what it being displayed.

I’ll now work towards removing the nested nodes for transitive dependencies. I’m going to try and see if I can find a project where a nested dependency isn’t listed in the `build.zig.zon` to see how the current implementation handles that. (Theoretically, it should just auto update as `fetchAndAddDependencies` recurses.)

One area I’m currently blocked on is reliably getting the file size of the package (when `content-length` is missing), but also displaying how much is currently downloaded. From what I can understand that information is from the `request.response`, after `request.wait` is called. However, I believe that same function is also a blocking call, so I’m currently not sure how I can “watch” the progress of the download.

Thanks again for your time!
I’ll keep working at it!

P.S. If this is all too much information, I’m sorry I’ll tone it down in the future, I’ve got a bit of a bad habit of needing to share updates and plans from my internships and thesis work.
 
P.S.S. If you have the time:
I would like some tips on would be “reducing API impact” (I’m not sure if a real term for this exists). A bit of context: in my own past hobby projects I would be able to change any code as needed to get the information I needed, however in a collaborative project like this, I’m working under the assumption that instead changes should be relatively minimized or at least seemingly local, which is a bit of a new skill I need to practice.

**Comment by VeroAsghar** [comment]
Implementation question: How should the progress bar look when a dependency is shared by the main dependency and a nested dependency? 
Currently, I would just update the dependency count, but I believe it is only being downloaded once. Which would mean the my implementation is wrong. However, to differentiate these dependencies from other nested dependencies I would need to carry around a list of already downloaded package names/hashes, which seems a little excessive?

**Comment by VeroAsghar** [comment]
I spoke with @mlugg and realized I’m currently not able to finish this PR in time for 0.11’s release. He very nicely said he would be taking over further development! 
In the future, I will try and find an issue that I can take a crack at with a longer timeframe.

**Pull request closed without merging**
