### PR TITLE
Add missing assembly instructions to the x86 backend

### LINKED ISSUE #19773: Missing x86 mnemonics and registers (self-hosted backend encoder)
There are some assembly instruction mnemonics missing on the x86 backend, specially some CPL0 instructions like `cli`, `sti`, `wrmsr`, `rdmsr`, `hlt`, `ltr`, `lidt`, `iretq`, `hlt`... There are some registers missing too, namely the control registers (`cr0`, `cr2`, and so on).

### PR DESCRIPTION
**Pull request by Arnau478**
The x86 backend was missing some important instructions. They're not generated by the compiler, but having them ensures they can be used in inline assembly. Added tests for all of them. Control registers were also added. A list of added instructions:
- `rdmsr`
- `wrmsr`
- `sysret`
- `cmc`
- `clc`
- `stc`
- `cli`
- `sti`
- `cld`
- `std`
- `int1`
- `int`
- `iret`
- `hlt`

Fixes #19773

### CODE REVIEW

**Comment by sfiedler0** [comment]
It would be a good idea to add the `int` instruction (which throws an interrupt and is really good for testing interrupt handling in the kernel).

**Comment by Arnau478** [comment]
> It would be a good idea to add the `int` instruction (which throws an interrupt and is really good for testing interrupt handling in the kernel).

True, `int` and `iret` were missing too! Added them in b5d7804

**Comment by sfiedler0** [comment]
Probably also some instructions related to `inb` and `outb` (and `inw` and so on)?  
Port I/O is really important for kernels (UART logging, PIC communicating, PS/2 and whatever)

**Comment by Arnau478** [comment]
> Probably also some instructions related to `inb` and `outb` (and `inw` and so on)? Port I/O is really important for kernels (UART logging, PIC communicating, PS/2 and whatever)

The thing is, `in`/`out` instructions are kind of weird. Like `rdmsr` and `wrmsr`, they have implicit register operands. However, they are usually written with the operands being explicit (even though only `al`/`ax`/`eax` and `dx` are allowed, respectively). This wouldn't fit the current assembler implementation. Also, there are many ways to do it (size postfix, explicit register, or both), regarding language design. I think it should be made a separate issue and debated there. Either way, it requires a design decision that I hope someone with an important role in the organization can make.

**Review by jacobly0 — CHANGES_REQUESTED** [review]
Unfortunately, the CI does not run any tests in `src`, and the tests added in this PR do not pass as many of the added encodings are wrong.  If you prefer, you can make these changes [upstream](https://github.com/kubkon/zig-dis-x86_64) first where the CI does run the tests.  Also note that without Mir encodings most of these instructions will not be usable in inline asm, which should have been obvious if any amount of testing had been done before creating this PR.  I'm afraid making these kind of changes requires a lot of attention to detail to get right.

**Comment by Arnau478** [comment]
@jacobly0 I'm sorry, I missed the Mir. I will set the PR as a draft for now, in case someone wants to address the linked issue while I work on it. Thanks for mentioning the upstream.

**Comment by jacobly0** [comment]
> The thing is, `in`/`out` instructions are kind of weird. Like `rdmsr` and `wrmsr`, they have implicit register operands. However, they are usually written with the operands being explicit (even though only `al`/`ax`/`eax` and `dx` are allowed, respectively).

See `stos`/`stosb` etc for an example of how to implement this.

**Comment by andrewrk** [comment]
closing old draft

**Pull request closed without merging**
