### PR TITLE
Bring back ZIG_SKIP_INSTALL_LIB_FILES

### PR DESCRIPTION
**Pull request by daurnimator**
I think this was accidentally removed for non-MSVC by @mikdusan in https://github.com/ziglang/zig/pull/4215#issuecomment-753330074 ?

(It was also touched by 7eb0a3edcef2ab752ff1e45e6f1316b633b29606 but that just brought the help description up to date with its accidental removal)

### CODE REVIEW

**Comment by mikdusan** [comment]
Why? I was under the impression `ZIG_SKIP_INSTALL_LIB_FILES` mechanism caused friction to maintainers and the two-step `make` + `make install` is desired.

**Comment by daurnimator** [comment]
> I was under the impression `ZIG_SKIP_INSTALL_LIB_FILES` mechanism caused friction to maintainers and the two-step `make` + `make install` is desired.

I cause no friction to maintainers: they don't use it.

---

I use it for local development: I found that without this PR, working on parts of the standard library, I had to re-run `make` to use them. That took my development feedback cycle up to the scale of minutes whereas with this patch it is milliseconds.

**Comment by andrewrk** [comment]
ZIG_SKIP_INSTALL_LIB_FILES is already present, but it is windows only. On non-windows, it already works as desired; simply omit the `make install` step and the installation of lib files will be skipped.

>  I had to re-run `make` to use them

This is not the case if you avoid `make install`.

**Comment by andrewrk** [comment]
I reconsidered, and I think your way is nice that it's consistent between platforms even though there is still a trick to make it work on non-Windows platforms. Sorry for the noise.

**Pull request merged**
