### PR TITLE
[ignore] more drone CI tests

### PR DESCRIPTION
**Pull request by mikdusan**
#### [sorry for PR noise]

this works with manual docker/alpine, Release+STATIC, llvm10

but let's log `lscpu` because there are different CPU available at drone

### CODE REVIEW

**Comment by mikdusan** [comment]
...just got success on a branch based on 39589cffe0bfcfda8d4802cc14fc335f532a7a90 where yesterday it was failing, and the same commit succeeded on merge to master several days ago. I'll define success as being able to `make install` without `std::bad_alloc`.

`lscpu` (needs `apk add util-linux`) recorded:

#### drone CI: most recent success
```
Architecture:        aarch64
CPU op-mode(s):      64-bit
Byte Order:          Little Endian
CPU(s):              44
On-line CPU(s) list: 0-43
Thread(s) per core:  1
Core(s) per socket:  44
Socket(s):           1
NUMA node(s):        1
Vendor ID:           Qualcomm
Model:               3
Model name:          Falkor
Stepping:            0x0
CPU max MHz:         2600.0000
CPU min MHz:         600.0000
BogoMIPS:            40.00
L1d cache:           1.4 MiB
L1i cache:           2.8 MiB
L2 cache:            11 MiB
L3 cache:            55 MiB
NUMA node0 CPU(s):   0-43
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid asimdrdm
```

#### drone ssh session: also succeeded with same commit
```
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          32
On-line CPU(s) list:             0-31
Thread(s) per core:              1
Core(s) per socket:              32
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       APM
Model:                           2
Model name:                      X-Gene
Stepping:                        0x3
CPU max MHz:                     3300.0000
CPU min MHz:                     363.9700
BogoMIPS:                        90.00
L1d cache:                       1 MiB
L1i cache:                       1 MiB
L2 cache:                        4 MiB
NUMA node0 CPU(s):               0-31
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Vulnerable
Flags:                           fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
```

#### drone CI: other sampling but script did not get far enough to `make install`
```
Architecture:        aarch64
CPU op-mode(s):      64-bit
Byte Order:          Little Endian
CPU(s):              96
On-line CPU(s) list: 0-95
Thread(s) per core:  1
Core(s) per socket:  48
Socket(s):           2
NUMA node(s):        2
Vendor ID:           Cavium
Model:               1
Model name:          ThunderX 88XX
Stepping:            0x1
BogoMIPS:            200.00
NUMA node0 CPU(s):   0-47
NUMA node1 CPU(s):   48-95
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
```

**Comment by mikdusan** [comment]
would like to add that the most recent success is a little perplexing... I could swear already tried `39589cffe0bfcfda8d4802cc14fc335f532a7a90` and it failed but unfortunately did not have an `lscpu` output to record.

**Comment by mikdusan** [comment]
another tidbit: with __divtf3 bits drone-CI succeeds, and drone-ssh fails:

#### drone CI: `lscpu` for d12269426939661177313f13df64e52bcd1da2a4
```
Architecture:        aarch64
CPU op-mode(s):      64-bit
Byte Order:          Little Endian
CPU(s):              44  
On-line CPU(s) list: 0-43
Thread(s) per core:  1
Core(s) per socket:  44  
Socket(s):           1   
NUMA node(s):        1   
Vendor ID:           Qualcomm
Model:               3   
Model name:          Falkor
Stepping:            0x0 
CPU max MHz:         2600.0000
CPU min MHz:         600.0000
BogoMIPS:            40.00
L1d cache:           1.4 MiB 
L1i cache:           2.8 MiB 
L2 cache:            11 MiB 
L3 cache:            55 MiB 
NUMA node0 CPU(s):   0-43
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid asimdrdm
```

#### drone ssh: `lscpu` for d12269426939661177313f13df64e52bcd1da2a4
```
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          32
On-line CPU(s) list:             0-31
Thread(s) per core:              1
Core(s) per socket:              32
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       APM
Model:                           2
Model name:                      X-Gene
Stepping:                        0x3
CPU max MHz:                     3300.0000
CPU min MHz:                     363.9700
BogoMIPS:                        90.00
L1d cache:                       1 MiB
L1i cache:                       1 MiB
L2 cache:                        4 MiB
NUMA node0 CPU(s):               0-31
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Vulnerable
Flags:                           fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
```

**Comment by andrewrk** [comment]
You don't actually need a pull request open - you can just push to a branch and the CI tests will run for the branch

**Pull request closed without merging**
