### PR TITLE
Maths tests resurrected (exp and log functions) with bugfixes

### PR DESCRIPTION
**Pull request by LewisGaul**
Reviving https://github.com/ziglang/zig/pull/12355 (previously https://github.com/ziglang/zig/pull/10415).

- Add test framework (at `lib/std/math/test.zig`) for maths functions that take in a float and output a float of the same type, e.g. `exp()`
- Create tests for all exp/log functions under `lib/std/math/test/`
  - Sanity tests, taken from [libc-test](https://wiki.musl-libc.org/libc-test.html) (e.g. [exp.h](http://nsz.repo.hu/git/?p=libc-test;a=blob;f=src/math/sanity/exp.h;h=7cbdfcae8770955be175e824e92e535fabae4430;hb=HEAD))
  - Special cases (inf, nan, 0, ...)
  - Boundary cases (last value before inf, first subnormal, ...)
- Remove special case tests from function implementation modules to avoid duplication (leave the basic tests intact)
- Bugfixes uncovered by improved testing:
  - `exp2_32()` flushing to zero too soon
  - `expm1_32()` giving incorrect results for a certain range of small negative inputs
  - `ln64()` giving incorrect results for positive subnormal inputs
  - Some functions returning canonical NaN instead of passing through input NaNs unchanged (as per Musl and GCC)
  - `log10_64()` returning 32-bit inf and NaN, which would be fine as it's cast up, except casting NaN results in failure to pass through the input unchanged

Example output with 'log_level = .info' for debugging (failing test added for illustration):
```
$./zig test --zig-lib-dir lib lib/std/std.zig --test-filter 'exp32() boundary'
Test [1/1] test.exp.test "math.exp32() boundary"... [default] (info):
[default] (info):  IN:  0x42B97217  0x1.72e42ep6      9.27228317e+01
[default] (info): OUT:  0x7F800000  inf               inf
[default] (info): EXP:  0x7F7FFF84  0x1.ffff08p127    3.40279851e+38
FAILURE: expected exp(0x1.72e42ep6)->0x1.ffff08p127, got inf (32-bit)
[default] (info):
[default] (info):  IN:  0x42B17218  0x1.62e43p6       8.87228393e+01
[default] (info): OUT:  0x7F800000  inf               inf
[default] (info):
[default] (info):  IN:  0x7F7FFFFF  0x1.fffffep127    3.40282346e+38
[default] (info): OUT:  0x7F800000  inf               inf
[default] (info):
[default] (info):  IN:  0x00000001  0x0.000002p-126   1.40129846e-45
[default] (info): OUT:  0x3F800000  0x1p0             1.0e+00
[default] (info):
[default] (info):  IN:  0x80000001  -0x0.000002p-126  -1.40129846e-45
[default] (info): OUT:  0x3F800000  0x1p0             1.0e+00
[default] (info):
[default] (info):  IN:  0x00800000  0x1p-126          1.17549435e-38
[default] (info): OUT:  0x3F800000  0x1p0             1.0e+00
[default] (info):
[default] (info):  IN:  0x80800000  -0x1p-126         -1.17549435e-38
[default] (info): OUT:  0x3F800000  0x1p0             1.0e+00
[default] (info):
[default] (info):  IN:  0xC2CFF1B4  -0x1.9fe368p6     -1.03972076e+02
[default] (info): OUT:  0x00000001  0x0.000002p-126   1.40129846e-45
[default] (info):
[default] (info):  IN:  0xC2CFF1B5  -0x1.9fe36ap6     -1.03972084e+02
[default] (info): OUT:  0x00000000  0x0.0p0           0.0e+00
[default] (info):
[default] (info):  IN:  0xC2AEAC4F  -0x1.5d589ep6     -8.73365402e+01
[default] (info): OUT:  0x00800026  0x1.00004cp-126   1.17549967e-38
[default] (info):
[default] (info):  IN:  0xC2AEAC50  -0x1.5d58ap6      -8.73365478e+01
[default] (info): OUT:  0x007FFFE6  0x0.ffffccp-126   1.17549070e-38
[default] (info):
[default] (info): Subtest summary: 10 passed; 1 failed
Test [1/1] test.exp.test "math.exp32() boundary"... FAIL (Failure)
/mnt/c/Users/legaul/repos/zig/lib/std/math/test.zig:96:17: 0x21906a in Testcase(std.math.exp,"exp",f32).run (test)
                return error.TestExpectedEqual;
                ^
/mnt/c/Users/legaul/repos/zig/lib/std/math/test.zig:120:23: 0x217ecd in runTests (test)
    if (failures > 0) return error.Failure;
                      ^
/mnt/c/Users/legaul/repos/zig/lib/std/math/test/exp.zig:78:5: 0x217398 in test.exp.test "math.exp32() boundary" (test)
    try runTests(cases);
    ^
0 passed; 0 skipped; 1 failed.
error: the following test command failed with exit code 1:
lib/std/math/zig-cache/o/7af2224de94b200df723802d7c69b7dc/test /mnt/c/Users/legaul/repos/zig/build/zig
```

---

Previous suggestions from @matu3ba that I'm considering out of scope of this PR:

- Adding tests for all extreme values (e.g. +/- inf) rather than targeted boundary cases (see https://github.com/ziglang/zig/pull/10415#discussion_r775308449)

- Taking on all Musl tests
> 2 ideas for discussion
> 
> 1. port [libc-test](https://wiki.musl-libc.org/libc-test.html) to zig
> 
> * 1.1. Port the test running functions from [libc-test](https://wiki.musl-libc.org/libc-test.html), which is the test library of musl.
> * 1.2. Use scripts to generate the test code from the musl test macros.
> * more code to write, but less dependency on C/clang
> * caveat, but actually a feature: Include the comments in the generated test code.
> 
> 2. vendor [libc-test](https://wiki.musl-libc.org/libc-test.html)
> 
> * 2.1 use zig stubs for the build scripts and test calls
> * less code to write, but more dependency on C/clang

### CODE REVIEW

**Comment by LewisGaul** [comment]
The CI failures are making me sad :( I ran the tests on WSL1 Ubuntu20.04 and they passed. I think they might all related to the bit representation of NaN. I'm just not sure how to reproduce to debug the issue... Might have to try running natively on Windows.

**Comment by matu3ba** [comment]
> bit representation of NaN. I'm just not sure how to reproduce to debug the issue... Might have to try running natively on Windows.

Also sent on discord some ideas, but I'm not too familiar yet with NaN, infinity or expected bit differences of accuracy ranges, only with value range computations stolen from https://blog.demofox.org/2017/11/21/floating-point-precision/:
```
Hey Lewis, some questions or ideas to get you on speed and your PR merged:
- 1. Do you have access to Windows laptop to test?
- 2. Did you try comparing/printing the underlying bit representation?
A simple example would be
```rust
const std = @import("std");
const math = std.math;
const print = std.debug.print;

pub fn main() !void {
    // expected exp(0x1.288bbcp3)->0x1.4abc8p13, got 0x1.4abc82p13 (32-bit)
    const exp: f32 = 0x1.4abc8p13;
    const got: f32 = 0x1.4abc82p13;
    print("exp: {e}\ngot: {e}\n", .{ exp, got });
    print("exp: {b}\ngot: {b}\n", .{ @as(u32, @intFromFloat(exp)), @as(u32, @intFromFloat(got)) });
}
```
- 3. Make mask functions for simpler comparisons of NaNs and infinity like shown here: https://en.wikipedia.org/wiki/NaN
I think those could also go into std.math, because they provide convenience + knowledge on float encoding, but that decision etc is nonessential.
- 4. You could check with assembly, if any signaling bit has been set.
- 5. Clutter your code with assertions related to the "Encoding" in https://en.wikipedia.org/wiki/NaN
- 6. Install a handler for SIGFPE on Posix to get the stack trace.
- 7. On error: Print the number representations before the operations.
```

**Comment by matu3ba** [comment]
On stage4 (without bootstrapping) on Arch-derivate  Linux, I get 
```
user@pc ~/d/g/z/z/upstr_math_tests (upstr_math_tests)> ./deb/bin/zig test --zig-lib-dir lib lib/std/std.zig --test-filter 'exp32() boundary'
Test [30/59] test.math.exp32() boundary... [default] (info):
[default] (info):  IN:  0x42B17217  0x1.62e42ep6      8.87228317e+01
[default] (info): OUT:  0x7F7FFF84  0x1.ffff08p127    3.40279851e+38
[default] (info):
[default] (info):  IN:  0x42B17218  0x1.62e43p6       8.87228393e+01
[default] (info): OUT:  0x7F800000  inf               inf
[default] (info):
[default] (info):  IN:  0x7F7FFFFF  0x1.fffffep127    3.40282346e+38
[default] (info): OUT:  0x7F800000  inf               inf
[default] (info):
[default] (info):  IN:  0x00000001  0x0.000002p-126   1.40129846e-45
[default] (info): OUT:  0x3F800000  0x1p0             1.0e+00
[default] (info):
[default] (info):  IN:  0x80000001  -0x0.000002p-126  -1.40129846e-45
[default] (info): OUT:  0x3F800000  0x1p0             1.0e+00
[default] (info):
[default] (info):  IN:  0x00800000  0x1p-126          1.17549435e-38
[default] (info): OUT:  0x3F800000  0x1p0             1.0e+00
[default] (info):
[default] (info):  IN:  0x80800000  -0x1p-126         -1.17549435e-38
[default] (info): OUT:  0x3F800000  0x1p0             1.0e+00
[default] (info):
[default] (info):  IN:  0xC2CFF1B4  -0x1.9fe368p6     -1.03972076e+02
[default] (info): OUT:  0x00000001  0x0.000002p-126   1.40129846e-45
[default] (info):
[default] (info):  IN:  0xC2CFF1B5  -0x1.9fe36ap6     -1.03972084e+02
[default] (info): OUT:  0x00000000  0x0.0p0           0.0e+00
[default] (info):
[default] (info):  IN:  0xC2AEAC4F  -0x1.5d589ep6     -8.73365402e+01
[default] (info): OUT:  0x00800026  0x1.00004cp-126   1.17549967e-38
[default] (info):
[default] (info):  IN:  0xC2AEAC50  -0x1.5d58ap6      -8.73365478e+01
[default] (info): OUT:  0x007FFFE6  0x0.ffffccp-126   1.17549070e-38
[default] (info):
[default] (info): Subtest summary: 11 passed; 0 failed
All 59 tests passed.
user@pc ~/d/g/z/z/upstr_math_tests (upstr_math_tests)> ./rel/bin/zig test --zig-lib-dir lib lib/std/std.zig --test-filter 'exp32() boundary'
Test [30/59] test.math.exp32() boundary... [default] (info):
[default] (info):  IN:  0x42B17217  0x1.62e42ep6      8.87228317e+01
[default] (info): OUT:  0x7F7FFF84  0x1.ffff08p127    3.40279851e+38
[default] (info):
[default] (info):  IN:  0x42B17218  0x1.62e43p6       8.87228393e+01
[default] (info): OUT:  0x7F800000  inf               inf
[default] (info):
[default] (info):  IN:  0x7F7FFFFF  0x1.fffffep127    3.40282346e+38
[default] (info): OUT:  0x7F800000  inf               inf
[default] (info):
[default] (info):  IN:  0x00000001  0x0.000002p-126   1.40129846e-45
[default] (info): OUT:  0x3F800000  0x1p0             1.0e+00
[default] (info):
[default] (info):  IN:  0x80000001  -0x0.000002p-126  -1.40129846e-45
[default] (info): OUT:  0x3F800000  0x1p0             1.0e+00
[default] (info):
[default] (info):  IN:  0x00800000  0x1p-126          1.17549435e-38
[default] (info): OUT:  0x3F800000  0x1p0             1.0e+00
[default] (info):
[default] (info):  IN:  0x80800000  -0x1p-126         -1.17549435e-38
[default] (info): OUT:  0x3F800000  0x1p0             1.0e+00
[default] (info):
[default] (info):  IN:  0xC2CFF1B4  -0x1.9fe368p6     -1.03972076e+02
[default] (info): OUT:  0x00000001  0x0.000002p-126   1.40129846e-45
[default] (info):
[default] (info):  IN:  0xC2CFF1B5  -0x1.9fe36ap6     -1.03972084e+02
[default] (info): OUT:  0x00000000  0x0.0p0           0.0e+00
[default] (info):
[default] (info):  IN:  0xC2AEAC4F  -0x1.5d589ep6     -8.73365402e+01
[default] (info): OUT:  0x00800026  0x1.00004cp-126   1.17549967e-38
[default] (info):
[default] (info):  IN:  0xC2AEAC50  -0x1.5d58ap6      -8.73365478e+01
[default] (info): OUT:  0x007FFFE6  0x0.ffffccp-126   1.17549070e-38
[default] (info):
[default] (info): Subtest summary: 11 passed; 0 failed
All 59 tests passed.
user@pc ~/d/g/z/z/upstr_math_tests (upstr_math_tests)> ./deb/bin/zig test --zig-lib-dir lib lib/std/std.zig --test-filter 'exp32() boundary' -lc
Test [30/59] test.math.exp32() boundary... [default] (info):
[default] (info):  IN:  0x42B17217  0x1.62e42ep6      8.87228317e+01
[default] (info): OUT:  0x7F7FFF84  0x1.ffff08p127    3.40279851e+38
[default] (info):
[default] (info):  IN:  0x42B17218  0x1.62e43p6       8.87228393e+01
[default] (info): OUT:  0x7F800000  inf               inf
[default] (info):
[default] (info):  IN:  0x7F7FFFFF  0x1.fffffep127    3.40282346e+38
[default] (info): OUT:  0x7F800000  inf               inf
[default] (info):
[default] (info):  IN:  0x00000001  0x0.000002p-126   1.40129846e-45
[default] (info): OUT:  0x3F800000  0x1p0             1.0e+00
[default] (info):
[default] (info):  IN:  0x80000001  -0x0.000002p-126  -1.40129846e-45
[default] (info): OUT:  0x3F800000  0x1p0             1.0e+00
[default] (info):
[default] (info):  IN:  0x00800000  0x1p-126          1.17549435e-38
[default] (info): OUT:  0x3F800000  0x1p0             1.0e+00
[default] (info):
[default] (info):  IN:  0x80800000  -0x1p-126         -1.17549435e-38
[default] (info): OUT:  0x3F800000  0x1p0             1.0e+00
[default] (info):
[default] (info):  IN:  0xC2CFF1B4  -0x1.9fe368p6     -1.03972076e+02
[default] (info): OUT:  0x00000001  0x0.000002p-126   1.40129846e-45
[default] (info):
[default] (info):  IN:  0xC2CFF1B5  -0x1.9fe36ap6     -1.03972084e+02
[default] (info): OUT:  0x00000000  0x0.0p0           0.0e+00
[default] (info):
[default] (info):  IN:  0xC2AEAC4F  -0x1.5d589ep6     -8.73365402e+01
[default] (info): OUT:  0x00800026  0x1.00004cp-126   1.17549967e-38
[default] (info):
[default] (info):  IN:  0xC2AEAC50  -0x1.5d58ap6      -8.73365478e+01
[default] (info): OUT:  0x007FFFE6  0x0.ffffccp-126   1.17549070e-38
[default] (info):
[default] (info): Subtest summary: 11 passed; 0 failed
All 59 tests passed.
```

I'll take a look at Windows next.

**Comment by LewisGaul** [comment]
All the failures (at least for x86 linux debug in the CI, that I grepped the logs for) are in `exp`, `exp2`, `ln` (aka `log` in `compiler_rt`), `log10` and `log2`, with no failures in `expm1` and `log1p`. This makes sense, because the former are wrapped in `@`-prefixed builtin calls from `std.math`, which must result in some arch/hardware-specific code flow.

So, my suspicion is that the problem can be explained as follows:
- My tests cover the exp and log functions exposed by `std.math`, calling the functions that take `anytype`, passing different float types (`f32` and `f64`)
- Many of the implementations actually now call out to builtins, e.g. `std.math.exp()` is a trivial wrapper around `@exp()` following https://github.com/ziglang/zig/pull/11532 (and the follow-up https://github.com/ziglang/zig/pull/11666)
- My understanding (which could be wrong), is that the implementations in `compiler_rt` are used by the `@`-prefixed Zig builtins if and only if they are not provided at a hardware level (or something like that)
- This would mean that my tests are only actually testing the Zig implementations when there are no hardware implementations available (and there may be subtle differences in behaviour in the two cases)

If this is the case, then my tests should instead directly be calling the underlying Zig implementations, e.g. `compiler_rt.log2.log2f()`.

**Comment by matu3ba** [comment]
> My understanding (which could be wrong), is that the implementations in compiler_rt are used by the @-prefixed Zig builtins if and only if they are not provided at a hardware level (or something like that)

This is in general correct, but there are further compiler_rt functions used by LLVM.

> This would mean that my tests are only actually testing the Zig implementations when there are no hardware implementations available (and there may be subtle differences in behaviour in the two cases)

Yes. I was digging abit and I found (potentially) more horrible behavior. This is a summary of the text send to you on discord:
- I hope we are not running into LLVM generating outright broken float code on several targets: https://discourse.llvm.org/t/semantics-of-floating-point-instructions-are-unclear/68733/4. For example, x87 is broken as in not IEE754 compliant and I'm sure others are as well (hardware implementations).
- I dont think signaling and non-signaling NaN are respected by LLVM, see https://reviews.llvm.org/D143074:
"Maybe we want a guarantee that if no input is signaling than the output is not signaling either? I am not sure if that is a guarantee LLVM provides currently. Generally the vibe seems to be that LLVM will just produce some NaN, arbitrarily chosen from the set of all qNaN and sNaN, and completely independent of which kind of NaN (if any) was in the input.". This is from Ralf Jung, so I thinks this is very likely correct.

Suggestions for next/future steps to validate LLVM floating point semantics:
- 1. Make a list of all non-IEE754 compliant hardware implementations (and add it to targets)
- 2. Get the compiler_rt instrumentation working, see https://reviews.llvm.org/D58997 for compiler_rt order instrumentation and document usage / build flags etc.
- 3. make abi checks for each arch for how it encodes signaling and non-signaling nans and all the other floating operations (for future self-hosted backends to correctly implement NaN etc behavior)
- 4. Double check the LLVM IR
- 5. Document a strategy how to eliminate LLVM float miscompilations and/or the support status of LLVM.

**Comment by LewisGaul** [comment]
So, here's a summary of the current status of the PR:
- When I originally wrote these tests all the code under test was in `lib/std/math/`, so it made sense for the test infra to live there too (it was suggested to me to use `lib/std/math/test.zig` and `lib/std/math/test/`).
- Some of the code under test now lives in `lib/compiler_rt/`, with the functions in `lib/std/math/` only falling back to the `compiler_rt` code *sometimes* (depending on the target, I'm not clear exactly when).
- We still want the tests to live alongside the code under test, i.e. some tests in `lib/std/math/` and others in `lib/compiler_rt/`.
- The test infra in `lib/std/math/test.zig` is still relevant across all of these tests.

The problem is I don't know how to share this test infra between `lib/compiler_rt/` and `lib/std/math/`...
  - I don't think tests in `lib/compiler_rt/` can import the test infra from `lib/std/math/test.zig`?
  - It doesn't make much sense for it to live in `lib/compiler_rt/`.
  - Should it go in `lib/test/`? How would the tests in `lib/compiler_rt/` and `lib/std/math/` import from there?

**Comment by matu3ba** [comment]
if you want to have a look how much of a mess IEEE754 NaN creates for optimization compilers (plus hardware doing different things), take a look at this [llvm discussion started by someone trying to verify floats in alive2]( https://discourse.llvm.org/t/semantics-of-nan/66729/26).
This also makes me wonder, if the [wasm spec is not too optimistic around the float NaN guarantees](https://webassembly.github.io/spec/core/exec/numerics.html#nan-propagation).

**Comment by LewisGaul** [comment]
Sorry, messed up the merge, I'll open a new PR

**Pull request closed without merging**
