### PR TITLE
fixed FileNotFound due to incorrect handling of trailing path separator in cache paths

### LINKED ISSUE #12685: path arguments to `zig build` are inconsistent in whether they are relative to build root, such as --zig-lib-dir
Here we collect zig lib dir from the user:

https://github.com/ziglang/zig/blob/75d5a4b9a255895246762f27399e14821bc0e768/src/main.zig#L3769-L3770

It is then used relative to the cwd in order to build the build runner. Next, it is passed to the build runner and then the build runner interprets the file path as being relative to build.zig.

It can't be both ways; it needs to be consistently one way.

This results in nonsense experiences such as this:

```
$ stage3/bin/zig build  --zig-lib-dir ../lib
error: unable to open zig lib directory from 'zig-lib-dir' argument or env, '/home/andy/dev/lib': FileNotFound
$ stage3/bin/zig build  --zig-lib-dir lib
error: unable to open zig lib directory from 'zig-lib-dir' argument: 'lib': FileNotFound
```

As a workaround until this issue is fixed an absolute path can be used:

```
$ stage3/bin/zig build  --zig-lib-dir $(pwd)/../lib
(ok)
```

### PR DESCRIPTION
**Pull request by MasterQ32**
The problem was that paths in the cache are assumed to endwithout the path separator, but are added verbatim from the command line in several places. The solution here is to make sure that all prefixes are without path separator by cutting it off when it is passed to Cache.addPrefix. This way, the assumption is met.

Resolves #12685

### CODE REVIEW

**Comment by andrewrk** [comment]
I don't think this fixes #12685 - I believe the problem is that src/main.zig does it one way and build_runner.zig does it the other way. I'm not sure why patching Cache.zig here would address this problem. Does this patch perhaps address a different issue instead?

**Comment by MasterQ32** [comment]
Hm, maybe i actually took the wrong issue /o\

The issue that is fixed has this effect:
```
[felix@denkplatte-v2 apigen]$ zig build --zig-lib-dir ~/software/zig-current/lib
[felix@denkplatte-v2 apigen]$ zig build --zig-lib-dir ~/software/zig-current/lib/
warning: FileNotFound: /home/felix/software/zig-current/lib/uild_runner.zig
error: FileNotFound
exit code: 1
[felix@denkplatte-v2 apigen]$
```

Which happens because a lot of code paths assume the path is not ending with `/` and will remove the wrong part of the path if it actually has a `/` suffix. The patch here normalizes this to not having a trailing `/`

**Review by andrewrk — CHANGES_REQUESTED** [review]
Thank you for making this fix. I'm sorry but can we please instead solve this with an `assert` here that there is no trailing path separator, and then go fix the callsites to `addPrefix` whenever that assert is tripped?

**Comment by squeek502** [comment]
I believe the problem this is trying to solve has already been fixed by https://github.com/ziglang/zig/pull/16886

**Comment by andrewrk** [comment]
Aha, thank you! In that case, closing.

**Pull request closed without merging**
