### PR TITLE
Fixed bug on Windows when creating process with empty environment.

### PR DESCRIPTION
**Pull request by BenoitJGirard**
Apparently CreateProcessW() expects the input environment block to have two null 2-byte characters, even if there are no strings in the block. Not obvious from documentation. 

Let me know if more is needed in terms of submitted tests, etc.

### CODE REVIEW

**Comment by andrewrk** [comment]
Thanks for the contribution! I'll look at this today and add a test for it. How did you find this out?

**Comment by BenoitJGirard** [comment]
Found out by adding a CommandStep to a Builder with an empty environment, in an attempt to start a "sanitized" Zig process with all inputs explicit.

Where should I have added a test?

**Comment by andrewrk** [comment]
Ahh, that makes sense. If you want to try your hand at making a test, here's my recommendation:

 * create a standalone test in test/standalone/your_new_directory
 * add your new standalone test to `test/build_examples.zig` (sorry for the misleading name)
 * look at the other standalone tests for an example
 * to run it, do this: `bin/zig build --build-file ../build.zig test-build-examples`, or you can `cd` to your standalone directory and run `../../../build/bin/zig build test`

**Comment by andrewrk** [comment]
I ended up coding it a different way, and added a test in e1fbb24d64caa956846405bd42aed59e5b9513f2. So this is now fixed. Thanks again!

**Pull request closed without merging**
