### PR TITLE
fix compiler error in 'std.fmt.Parser.until'

### PR DESCRIPTION
**Pull request by allocgator**
Fixes `_ = &std.fmt.Parser.until;` in #20505

### CODE REVIEW

**Review by Vexu — CHANGES_REQUESTED** [review]
`until` should not be using `++`, a better solution would be to call `nextCodepoint` like the other functions next to it and return a slice like it did before #18533

**Comment by allocgator** [comment]
> until should not be using ++, a better solution would be to call nextCodepoint like the other functions next to it and return a slice like it did before https://github.com/ziglang/zig/pull/18533

Would it involve converting `u21` to `u8` ?

**Comment by Vexu** [comment]
No, it would look something like:
```zig
pub fn until(self: *@This(), ch: u21) []const u8 {
    const start = self.iter.i;
    while (self.peek(0)) |code_point| {
        if (code_point == ch)
            break;
        _ = self.iter.nextCodepoint();
    }
    return self.iter.bytes[start..self.iter.i];
}
```

**Review by andrewrk — CHANGES_REQUESTED** [review]
This kind of easily tested change should come with unit test coverage.

**Comment by Vexu** [comment]
Fair enough, none of the previous fixes in #20505 added any specific tests so I figured the existing usage as part of format strings would be sufficient.

**Comment by allocgator** [comment]
I've merged this PR with #22275

**Pull request closed without merging**
