### PR TITLE
Change builtins to return a string literal

### PR DESCRIPTION
**Pull request by jmc-88**
Fixes issue #3779 (I think?).

### CODE REVIEW

**Review by Vexu — CHANGES_REQUESTED** [review]
`@tagName` and `@errorName` should both return a null terminated slice instead since they can be used with runtime known arguments and returning different types based on whether they are being executed at `comptime` or not is bad for generic code.

**Comment by marler8997** [comment]
Looks like @andrewrk was the one to suggest that we use pointers to arrays when the length is comptime known (see https://github.com/ziglang/zig/issues/3779#issuecomment-558886346).  I can see how this could cause some issues with generic code, but I think sometimes this information is necessary, so I don't see much choice other than to expose it.

**Comment by Vexu** [comment]
I assumed he was referring to `@embedFile` and `@typeName` since they are always `comptime` but I could be wrong.

**Comment by jmc-88** [comment]
> Looks like @andrewrk was the one to suggest that we use pointers to arrays when the length is comptime known (see [#3779 (comment)](https://github.com/ziglang/zig/issues/3779#issuecomment-558886346)).

Yes, I took that comment as reference, and probably misunderstood it, and here we are. :smile: 

> `@tagName` and `@errorName` should both return a null terminated slice instead since they can be used with runtime known arguments and returning different types based on whether they are being executed at `comptime` or not is bad for generic code.

Just for extra n00b-friendly clarity, the desire is to ensure these builtins all return `[:0]const u8`?

**Comment by Vexu** [comment]
This change should also apply to all the strings in `std.builtin.TypeInfo`, and yes `[:0]const u8` is the correct type.

**Comment by Vexu** [comment]
Are you still interested in finishing this pr? I'd be happy to do it for you if not.

**Comment by jmc-88** [comment]
Sorry, yeah, I'd like to work on this. I got busy with real life and now I have a scary rebase in front of me :smile: 

I'll update this PR as soon as possible and ping the thread.

**Comment by jmc-88** [comment]
I have updated the PR and it seems to pass `test-behavior` locally, PTAL.

**Review by Vexu — COMMENTED** [review]
Looks good so far, do you also want to make the change to `@typeInfo` and `@src`?

**Comment by jmc-88** [comment]
> Looks good so far, do you also want to make the change to `@typeInfo` and `@src`?

I have local changes ready to update string fields contained by structures returned by these two to `[:0]const u8`.

But while applying changes to `@typeInfo()` I realized its `std.builtin.TypeInfo` output is also an input to `@Type()` and that could break existing code. For instance, this assignment fails since it uses a `[]const u8` as returned by `std.mem.tokenize()` and that can't implicitly cast to `[:0]const u8`: https://github.com/ziglang/zig/blob/e006281d79a31e10bdbc07b3e33427d719ec01df/test/behavior/bugs/6456.zig#L20

Would you say this is WAI?

**Comment by Vexu** [comment]
Hmm, I didn't think of that. I see three ways to solve this:

1. Have separate types for `@typeInfo` and `@Type`, which would break even more code.
2. Leave things as they are, which kind of defeats the purpose of this change.
3. Add casts from `[]T -> [:t]T` and `*[N]T -> *[N:t]T` when the value is comptime known, which would make this change purely cosmetic.

I'll make an issue for this since this pr is already useful as is.

**Pull request merged**
