### PR TITLE
std.mem: expose readPackedIntLittle and readPackedIntBig

### LINKED ISSUE #16048: std.mem.readPackedIntLittle and std.mem.readPackedIntBig are not marked as pub
### Zig Version

0.11.0-dev.1635+d09e39aef

### Steps to Reproduce and Observed Behavior

Try to compile a program that uses those functions.

### Expected Behavior

I don't see a reason for them to be private and i needed to use them for a project i'm working on.
I modified the file on my system to make them public, i'm too lazy to do all the stuff needed to make a pull request so i just did it this way.

### PR DESCRIPTION
**Pull request by yujiri8**
closes #16048

### CODE REVIEW

**Comment by nektro** [comment]
it would unify more to instead make `writePackedIntLittle` and `writePackedIntBig` private rather than increase the api surface area more

**Comment by nektro** [comment]
`readPackedInt` and `writePackedInt` both accept an `endian` parameter

**Comment by yujiri8** [comment]
Sounds good. I'll try doing that instead

**Comment by yujiri8** [comment]
Whoa! I was about to ask if we should do the same for f32_max and such, but it was recently done! Cool

**Pull request merged**
