### PR TITLE
std.builtin: renamings

### PR DESCRIPTION
**Pull request by r00ster91**

### CODE REVIEW

**Comment by r00ster91** [comment]
Seems to be passing now. Can this get a review before `stage1/zig1.wasm` is outdated again?

This PR makes breaking changes to public APIs only in https://github.com/ziglang/zig/pull/13930/files#diff-7194f8244f143a85a7a746c039e71c572a156dda1130e629c7655e9dcdb0ff4a.
All other changes update the rest of the codebase to use the new names.

**Review by Vexu — APPROVED** [review]
If you want you could also remove `layout` from `Enum` at the same time to reduce the amount of times the wasm binary is updated.

**Comment by r00ster91** [comment]
Oh sure, if that's easy to do I could do that here as well.

Can we remove the `layout`s of `Union` and `Struct` too? Maybe only `Union`?
https://github.com/ziglang/zig/blob/f7d8367a279b4335a2fea2a34b6101699cd37ada/lib/std/builtin.zig#L352

https://github.com/ziglang/zig/blob/f7d8367a279b4335a2fea2a34b6101699cd37ada/lib/std/builtin.zig#L292

**Comment by r00ster91** [comment]
Right, nevermind. It makes sense that enums can't really have a different layout but unions and structs can.

https://github.com/ziglang/zig/blob/f7d8367a279b4335a2fea2a34b6101699cd37ada/lib/std/meta.zig#L390

Should this return `Type.ContainerLayout.Auto` or should the case be removed altogether?

**Comment by Vexu** [comment]
I think it should be removed if it doesn't break too much existing code.

**Comment by r00ster91** [comment]
Because this PR already has a lot of changes I would prefer using the CI of another PR for these other changes. Turns out this requires a lot of changes and locally I can't really test this layout removal either (it segfaults) so let's leave this PR as-is so that we don't confuse incoming CI failures with something else.

**Comment by r00ster91** [comment]
Well, we can note that at this point it passed so later I can still revert.

**Comment by r00ster91** [comment]
Oh and I'm also not really able to build the new stage1/zig1.wasm now (`Trace/breakpoint trap (core dumped)`).

**Comment by Vexu** [comment]
It looks like you didn't update `zirTypeInfo`

**Comment by r00ster91** [comment]
After these changes I just pushed I'm still hitting `Trace/breakpoint trap (core dumped)` with `zig build update-zig1 --zig-lib-dir lib`. I tried to see what it says with a debug build of the compiler and it said that some `integer cast truncated bits`:
```
/zig/src/arch/x86_64/Emit.zig:2039:71: 0x148848a in new (zig)
            return @intToEnum(PtrSize, math.log2_int(u4, @intCast(u4, @divExact(bit_size, 8))));
```
Can you think of any other places where an update is missing?

**Comment by Vexu** [comment]
> After these changes I just pushed I'm still hitting `Trace/breakpoint trap (core dumped)` with `zig build update-zig1 --zig-lib-dir lib`

I don't think you're supposed to add `--zig-lib-dir` unless your `zig` already contains all these changes.

**Comment by r00ster91** [comment]
Oh, thanks! Looks like that worked for you.
Well I did that to feed back the std changes. Otherwise I get:
```
$ zig build update-zig1
src/type.zig:6219:56: error: no field named 'type' in struct 'builtin.Type.StructField'
            return std.meta.fieldInfo(t.Type(), .data).type;
                                                       ^~~~
```

**Comment by Vexu** [comment]
> Oh, thanks! Looks like that worked for you. Well I did that to feed back the std changes. Otherwise I get:
> 
> ```
> $ zig build update-zig1
> src/type.zig:6219:56: error: no field named 'type' in struct 'builtin.Type.StructField'
>             return std.meta.fieldInfo(t.Type(), .data).type;
>                                                        ^~~~
> ```

That could be avoided by making the compiler changes before standard library changes but I just patched the compiler to use the old names.

**Comment by r00ster91** [comment]
```
All 1 tests passed.
info: PASS build test/standalone/options/build.zig (Debug)
info: PASS build test/standalone/cat/main.zig (Debug)
info: PASS build test/standalone/cat/main.zig (ReleaseSafe)
info: PASS build test/standalone/cat/main.zig (ReleaseFast)
info: PASS build test/standalone/cat/main.zig (ReleaseSmall)
info: PASS build test/standalone/issue_12471/main.zig (Debug)
info: PASS build test/standalone/issue_12471/main.zig (ReleaseSafe)
info: PASS build test/standalone/issue_12471/main.zig (ReleaseFast)
info: PASS build test/standalone/issue_12471/main.zig (ReleaseSmall)
info: PASS build test/standalone/guess_number/main.zig (Debug)
info: PASS build test/standalone/guess_number/main.zig (ReleaseSafe)
info: PASS build test/standalone/guess_number/main.zig (ReleaseFast)
info: PASS build test/standalone/guess_number/main.zig (ReleaseSmall)
info: PASS build test/standalone/main_return_error/error_u8.zig (Debug)
info: PASS build test/standalone/main_return_error/error_u8.zig (ReleaseSafe)
info: PASS build test/standalone/main_return_error/error_u8.zig (ReleaseFast)
info: PASS build test/standalone/main_return_error/error_u8.zig (ReleaseSmall)
info: PASS build test/standalone/main_return_error/error_u8_non_zero.zig (Debug)
info: PASS build test/standalone/main_return_error/error_u8_non_zero.zig (ReleaseSafe)
info: PASS build test/standalone/main_return_error/error_u8_non_zero.zig (ReleaseFast)
info: PASS build test/standalone/main_return_error/error_u8_non_zero.zig (ReleaseSmall)
info: PASS build test/standalone/noreturn_call/inline.zig (Debug)
info: PASS build test/standalone/noreturn_call/inline.zig (ReleaseSafe)
info: PASS build test/standalone/noreturn_call/inline.zig (ReleaseFast)
info: PASS build test/standalone/noreturn_call/inline.zig (ReleaseSmall)
info: PASS build test/standalone/noreturn_call/as_arg.zig (Debug)
info: PASS build test/standalone/noreturn_call/as_arg.zig (ReleaseSafe)
info: PASS build test/standalone/noreturn_call/as_arg.zig (ReleaseFast)
info: PASS build test/standalone/noreturn_call/as_arg.zig (ReleaseSmall)
1 passed; 1 skipped; 1 failed.
```
`1 failed.` It says that something failed but it doesn't tell me what?
As I'm not able to test locally I'm not sure where to go from here to be honest.

**Comment by Vexu** [comment]
> `1 failed.` It says that something failed but it doesn't tell me what?
> As I'm not able to test locally the way the CI does I'm not sure where to go from here to be honest.

It's the `test_runner_path` test after your snippet and the "fail" is intentional:
```
1 passed; 1 skipped; 1 failed.
info: PASS build test/standalone/test_runner_path/build.zig (Debug)
```
https://github.com/ziglang/zig/pull/13411/files#diff-ceaf054dcfc64f4f51e244e5e4a8b1950670ea9673435623b7949387e0e3b2f9

Probably shouldn't be printed to stderr to avoid confusion.

**Comment by Vexu** [comment]
CI failure caused by different behavior of `std.math.log2` for `comptime_int` vs runtime int types:

```zig
test {
    _ = std.math.log2(0); // OK, 0
    _ = std.math.log2(@as(u16, 0)); // assertion failure
}
```

**Comment by r00ster91** [comment]
Alright, I would say before I force-push another 100 times, let's do that in a different PR. @Vexu I removed the faulty commit. Can you kindly rebuild `stage1/zig1.wasm` so we can finally get this merged?

**Pull request merged**
