### PR TITLE
elf: implement archiving input object files

### PR DESCRIPTION
**Pull request by kubkon**

### CODE REVIEW

**Comment by kubkon** [comment]
@andrewrk could you comment on 281daba? Previous assumption of `makeExecutable`/`makeWritable` dance is no longer sufficient since ELF can emit both relocatable object files and static libraries and we hold open file handles which need to be closed and re-opened on Windows when renaming tmp cache directory to avoid `AccessDenied` error.

**Comment by andrewrk** [comment]
hmm, I don't think we should be calling `makeExecutable` for static archives, right?

**Comment by kubkon** [comment]
> hmm, I don't think we should be calling `makeExecutable` for static archives, right?

Exactly, that's why I have changed that to unconditionally closing file handles.

**Comment by andrewrk** [comment]
Oh, I see. Yes I think this is a good solution :+1:

**Review by andrewrk — APPROVED** [review]
Nice work! Great to see the additions to CheckObject. That investment in testing infrastructure will pay off big time.

**Comment by kubkon** [comment]
> Nice work! Great to see the additions to CheckObject. That investment in testing infrastructure will pay off big time.

I really do hope so!

**Pull request merged**
