### PR TITLE
std.math: Add O(log N) implementation of `log2(x)` for `comptime_int`

### PR DESCRIPTION
**Pull request by topolarity**
Since `@clz` is undefined for `comptime_int` and Zig does not provide `@fls` (find-last-set), `log2` for comptime integers needs to be computed algorithmically.

This change replaces the existing implementation with a basic binary search

The benefit is that the added tests no longer hit the default backward branch quota of 1000 :+1:

### CODE REVIEW

**Review by andrewrk — APPROVED** [review]
Nice!

**Comment by jibal** [comment]
> The benefit is that the added tests no longer hit the default backward branch quota of 1000 👍

Is something going to be done about that misfeature? I gave up on a comptime-heavy implementation of ranges in part because of it (and other comptime issues that I'm hoping will be improved with Stage2). I can't even set a large global limit because some stdlib functions arbitrarily set it back to low values.

**Comment by andrewrk** [comment]
> set it back to low values.

https://ziglang.org/documentation/master/#setEvalBranchQuota

> If the new_quota is smaller than the default quota (1000) or a previously explicitly set quota, it is ignored.

**Comment by jibal** [comment]
Is that new? Because it wasn't my experience. In any case, I think a global value is a bad idea ... unless making it ridiculously large, it can make programs suddenly stop compiling due to small changes.

**Comment by andrewrk** [comment]
It's not global

**Comment by jibal** [comment]
I must be seriously misunderstanding something. If it's not global, then what is its scope? I've seen proposals to make it scoped or add a variant that is scoped, but the documentation you just pointed me to doesn't say anything about scope.

**Pull request merged**
