### PR TITLE
Solve the return type ambiguity

### LINKED ISSUE #760: syntax flaw: return type
Fundamentally we have this ambiguity:

```zig
fn foo() A { }
```

Is this a function that returns A with an empty body? Or is this a function that returns the struct literal `A{}` and we're about to parse the body?

Another example

```zig
fn foo() error {}
```

Function that returns an error, or empty error set, and we're about to find the function body?

```zig
fn foo() error{}!void {
}
```

The above is not allowed because zig thinks the return value is `error` and the function has an empty body, and then is surprised by the `!`. So we have to do this:

```zig
fn foo() (error{}!void) {
}
```

Unfortunate. And the compile errors for forgetting to put a return type on a function point at the wrong place.

Let's come up with a better syntax for return types. All of these issues are potentially on the table:
 * could reintroduce `->` or `=>` if it helps.
 * could change the struct literal syntax / error set declaration syntax
 * multiple return values are potentially in zig's future. but also maybe not.
 * could potentially go back to allowing leaving off the return type for `void` return types.
 * error set inference - which currently looks like this:  `fn foo() !T {}`  - is special syntax that belongs to a function definition that marks the function as having an inferred error set. It doesn't necessarily have to be specified as it currently is by leaving off the error set of the `!` binary operator.

The syntax change should be satisfying, let's make this the last time everybody has to update all their return type code.

### PR DESCRIPTION
**Pull request by Hejsil**
Fixes #760 

I chose [using `.` before `{`](https://github.com/ziglang/zig/issues/760#issuecomment-370286078) as the way to solve this.

I've only made the changes nessesary for stage1 to compile this code:
```
const A = error.{B};
const S = struct.{a: u8};
const E = enum.{A};
const U1 = union.{A:u8};
const U2 = union(enum).{A:u8};
const U3 = union(E).{A:u8};

export fn a() void {
    var q: A = A.B;
    var s: S = S.{.a = 0};
    var e: E = E.A;
    var uu1: U1 = U1.{.A=0};
    var uu2: U2 = U2.{.A=0};
    var uu3: U3 = U3.{.A=0};
}


pub fn panic(msg: []const u8, error_return_trace: ?*@import("builtin").StackTrace) noreturn {
    unreachable;
}
```

Next step is to have a `zig fmt` branch that can translate old code into the new syntax, and then use that to finish this PR.

### CODE REVIEW

**Comment by Hejsil** [comment]
I have all tests passing locally. The `solve-return-type-problem-fmt` branch can be used to upgrade old code to the new syntax.

**Comment by winksaville** [comment]
In [using . before {](https://github.com/ziglang/zig/issues/760#issuecomment-370286078) it mentions "Remove the requirement of () for if, while, for, switch, etc.". I pulled in the branch and gave it a try on an `if` statement and it seems they are still required:
```
$ cat if.zig
const std = @import("std");
const warn = std.debug.warn;

test "if" {
    var i: usize = 1;
    var j: usize = 2;
    var k: usize = undefined;

    //if (i < j) {
    if i < j {
        k = @intCast(usize, 3);
    } else {
        k = @intCast(usize, 4);
    }
    warn("i={} j={} k={}\n", i, j, k);
}

$ ./build/bin/zig test if.zig 
/home/wink/prgs/ziglang/zig/if.zig:10:8: error: expected token '(', found 'Symbol'
    if i < j {
       ^
```

Is it the long term plan to remove the requirment for the parens?

**Comment by Hejsil** [comment]
@winksaville I did not remove this requirement, as the purpose of this PR is to solve the return type ambiguity. Someone else could then remove the requirement in their own PR :)

**Comment by andrewrk** [comment]
@Hejsil when you get back from your trip, I have an idea how we can avoid too much conflicts, when merging this:

 1. make a new branch from master
 2. run the zig fmt fixer upper in the new branch
 3. merge the new branch into this PR branch

hopefully that reduces the number of conflicts.

**Comment by Hejsil** [comment]
Jobs done!

**Comment by allochi** [comment]
I'm really sorry, this is not in anyway trying to be picky or undermind the great work that you guys are doing, but I don't like this change to the language, I may get used to it, but I have a point.

`.` has been engraved in programmers mind as a member access operators, just like `*` for pointers, having it used this way is harmful for readability in my opinion, I checked the new standard library for example, and it doesn't look good, too many confusing dots to define a struct or initialize an instance.

```c
const point = Point.{ .x = 10, .y = 20 };
```

I respect your decision and I regret not contributing to the original discussion, but I would like to ask to reconsider using `.` for that purpose. 

I wouldn't mind using keywords like `define` and `new` which declare their purpose than overloading `.` 

```c
const Point = struct.define {
    x: i32,
    y: i32,
};

const point = Point.new {
    .x = 10,
    .y = 20,
};
```

**and to be quite honest I much prefer the original way without a dot or a keyword.**

**Comment by Hejsil** [comment]
@allochi It's probably better to post this on the [issue](https://github.com/ziglang/zig/issues/760) instead of here, so we can keep the discussion in one place.

**Comment by allochi** [comment]
@Hejsil Thanks, I will do so.

**Pull request merged**
