### PR TITLE
Sema: Special case undef Value in intFromFloatScalar

### LINKED ISSUE #16389: `@intFromFloat` cast from `undefined` crashes
### Zig Version

0.11

### Steps to Reproduce and Observed Behavior

```zig
test {
    var a: i32 = @intFromFloat(@as(f32, undefined));
    _ = a;
}
```

https://github.com/ziglang/zig/blob/d78517f4f0f540f0d0254a78e47a7b4a30e98c74/src/value.zig#L1109

### Expected Behavior

a compile error probably, because Value is known as undefined

### PR DESCRIPTION
**Pull request by der-teufel-programming**
Closes #16389 giving it the behaviour of `@floatFromInt` for `undefined`

### CODE REVIEW

**Comment by andrewrk** [comment]
This is incorrect.

https://ziglang.org/documentation/master/#intFromFloat

> If the integer part of the floating point number cannot fit in the destination type, it invokes safety-checked [Undefined Behavior](https://ziglang.org/documentation/master/#Undefined-Behavior).

Since an `undefined` float might have an integer part that does not fit in the destination integer type, this must be treated as a compile error. @alichraghi correctly notes the expected behavior in that issue.

**Review by andrewrk — CHANGES_REQUESTED** [review]
Meant to request changes, not close it.

**Comment by andrewrk** [comment]
Looks good - please have a look in test/cases/compile_errors/ for inspiration on how to add a compile error test for this new error.

**Comment by Vexu** [comment]
Fixed in e2ff486de5f3aceb21730e1feabbaf9b03432660

**Pull request closed without merging**
