### PR TITLE
std.child_process: add tests to test/standalone

### PR DESCRIPTION
**Pull request by matu3ba**
fixup of 67d5bfefba48d28c02e2841f1a47a213d28d4693

### CODE REVIEW

**Comment by matu3ba** [comment]
missing explicit deinit of allocator.

**Review by ityonemo — COMMENTED** [review]
these cases really hepled me understand ChildProcess

**Comment by ityonemo** [comment]
it looks like ChildProcess struct no longer requires an allocator on init, (which is why the deinit is now gone).  Does this warrant changing the name of the function?  Probably, also the allocator field should also go away.

**Comment by matu3ba** [comment]
Looks like Windows has a cache issue or spurious failure, I will force-push to confirm.

<details>

```
2022-09-18T20:27:05.1849563Z error: FileNotFound
2022-09-18T20:27:05.1905805Z D:\a\1\s\stage3-release\lib\zig\std\os\windows.zig:1598:32: 0x7ff6253c0da6 in CreateProcessW (parent.exe.obj)
2022-09-18T20:27:05.1912422Z             .PATH_NOT_FOUND => return error.FileNotFound,
2022-09-18T20:27:05.1913411Z                                ^
2022-09-18T20:27:05.1915922Z D:\a\1\s\stage3-release\lib\zig\std\child_process.zig:1072:5: 0x7ff6253c0c91 in windowsCreateProcess (parent.exe.obj)
2022-09-18T20:27:05.1921167Z     return windows.CreateProcessW(
2022-09-18T20:27:05.1922151Z     ^
2022-09-18T20:27:05.1925426Z D:\a\1\s\stage3-release\lib\zig\std\os\windows.zig:1598:32: 0x7ff6253c0da6 in CreateProcessW (parent.exe.obj)
2022-09-18T20:27:05.1935345Z             .PATH_NOT_FOUND => return error.FileNotFound,
2022-09-18T20:27:05.1936879Z                                ^
2022-09-18T20:27:05.1938911Z D:\a\1\s\stage3-release\lib\zig\std\child_process.zig:1072:5: 0x7ff6253c0c91 in windowsCreateProcess (parent.exe.obj)
2022-09-18T20:27:05.1943317Z     return windows.CreateProcessW(
2022-09-18T20:27:05.1944521Z     ^
2022-09-18T20:27:05.1946601Z D:\a\1\s\stage3-release\lib\zig\std\os\windows.zig:1598:32: 0x7ff6253c0da6 in CreateProcessW (parent.exe.obj)
2022-09-18T20:27:05.1952111Z             .PATH_NOT_FOUND => return error.FileNotFound,
2022-09-18T20:27:05.1953265Z                                ^
2022-09-18T20:27:05.1955382Z D:\a\1\s\stage3-release\lib\zig\std\child_process.zig:1072:5: 0x7ff6253c0c91 in windowsCreateProcess (parent.exe.obj)
2022-09-18T20:27:05.1958861Z     return windows.CreateProcessW(
2022-09-18T20:27:05.1959697Z     ^
2022-09-18T20:27:05.1962316Z D:\a\1\s\stage3-release\lib\zig\std\os\windows.zig:1598:32: 0x7ff6253c0da6 in CreateProcessW (parent.exe.obj)
2022-09-18T20:27:05.1968818Z             .PATH_NOT_FOUND => return error.FileNotFound,
2022-09-18T20:27:05.1969857Z                                ^
2022-09-18T20:27:05.1972141Z D:\a\1\s\stage3-release\lib\zig\std\child_process.zig:1072:5: 0x7ff6253c0c91 in windowsCreateProcess (parent.exe.obj)
2022-09-18T20:27:05.1979459Z     return windows.CreateProcessW(
2022-09-18T20:27:05.1980460Z     ^
2022-09-18T20:27:05.1982653Z D:\a\1\s\stage3-release\lib\zig\std\os\windows.zig:1598:32: 0x7ff6253c0da6 in CreateProcessW (parent.exe.obj)
2022-09-18T20:27:05.1988671Z             .PATH_NOT_FOUND => return error.FileNotFound,
2022-09-18T20:27:05.1989953Z                                ^
2022-09-18T20:27:05.1992107Z D:\a\1\s\stage3-release\lib\zig\std\child_process.zig:1072:5: 0x7ff6253c0c91 in windowsCreateProcess (parent.exe.obj)
2022-09-18T20:27:05.1996125Z     return windows.CreateProcessW(
2022-09-18T20:27:05.1997639Z     ^
2022-09-18T20:27:05.1999035Z D:\a\1\s\stage3-release\lib\zig\std\child_process.zig:1009:17: 0x7ff6253a4429 in spawnWindows (parent.exe.obj)
2022-09-18T20:27:05.2003543Z                 return no_path_err; // return the original error
2022-09-18T20:27:05.2004806Z                 ^
2022-09-18T20:27:05.2006026Z D:\a\1\s\stage3-release\lib\zig\std\child_process.zig:141:13: 0x7ff625373678 in spawn (parent.exe.obj)
2022-09-18T20:27:05.2007410Z             return self.spawnWindows();
2022-09-18T20:27:05.2008263Z             ^
2022-09-18T20:27:05.2009517Z D:\a\1\s\stage3-release\lib\zig\std\child_process.zig:148:9: 0x7ff625371f4e in spawnAndWait (parent.exe.obj)
2022-09-18T20:27:05.2010922Z         try self.spawn();
2022-09-18T20:27:05.2011816Z         ^
2022-09-18T20:27:05.2013178Z D:\a\1\s\test\standalone\childprocess_minimal\parent.zig:9:21: 0x7ff625371cee in main (parent.exe.obj)
2022-09-18T20:27:05.2014513Z     const ret_val = try child_proc.spawnAndWait();
2022-09-18T20:27:05.2015448Z                     ^
2022-09-18T20:27:05.2016769Z D:\a\1\s\stage3-release\lib\zig\std\os\windows.zig:1598:32: 0x7ff6253c0da6 in CreateProcessW (parent.exe.obj)
2022-09-18T20:27:05.2021151Z             .PATH_NOT_FOUND => return error.FileNotFound,
2022-09-18T20:27:05.2022354Z                                ^
2022-09-18T20:27:05.2024636Z D:\a\1\s\stage3-release\lib\zig\std\child_process.zig:1072:5: 0x7ff6253c0c91 in windowsCreateProcess (parent.exe.obj)
2022-09-18T20:27:05.2028676Z     return windows.CreateProcessW(
2022-09-18T20:27:05.2029575Z     ^
2022-09-18T20:27:05.2031937Z D:\a\1\s\stage3-release\lib\zig\std\os\windows.zig:1598:32: 0x7ff6253c0da6 in CreateProcessW (parent.exe.obj)
2022-09-18T20:27:05.2037308Z             .PATH_NOT_FOUND => return error.FileNotFound,
2022-09-18T20:27:05.2038403Z                                ^
2022-09-18T20:27:05.2040200Z D:\a\1\s\stage3-release\lib\zig\std\child_process.zig:1072:5: 0x7ff6253c0c91 in windowsCreateProcess (parent.exe.obj)
2022-09-18T20:27:05.2044304Z     return windows.CreateProcessW(
2022-09-18T20:27:05.2045220Z     ^
2022-09-18T20:27:05.2047199Z D:\a\1\s\stage3-release\lib\zig\std\os\windows.zig:1598:32: 0x7ff6253c0da6 in CreateProcessW (parent.exe.obj)
2022-09-18T20:27:05.2053001Z             .PATH_NOT_FOUND => return error.FileNotFound,
2022-09-18T20:27:05.2054378Z                                ^
2022-09-18T20:27:05.2056170Z D:\a\1\s\stage3-release\lib\zig\std\child_process.zig:1072:5: 0x7ff6253c0c91 in windowsCreateProcess (parent.exe.obj)
2022-09-18T20:27:05.2059641Z     return windows.CreateProcessW(
2022-09-18T20:27:05.2060613Z     ^
2022-09-18T20:27:05.2062946Z D:\a\1\s\stage3-release\lib\zig\std\os\windows.zig:1598:32: 0x7ff6253c0da6 in CreateProcessW (parent.exe.obj)
2022-09-18T20:27:05.2068708Z             .PATH_NOT_FOUND => return error.FileNotFound,
2022-09-18T20:27:05.2069752Z                                ^
2022-09-18T20:27:05.2072075Z D:\a\1\s\stage3-release\lib\zig\std\child_process.zig:1072:5: 0x7ff6253c0c91 in windowsCreateProcess (parent.exe.obj)
2022-09-18T20:27:05.2076148Z     return windows.CreateProcessW(
2022-09-18T20:27:05.2076998Z     ^
2022-09-18T20:27:05.2078924Z D:\a\1\s\stage3-release\lib\zig\std\os\windows.zig:1598:32: 0x7ff6253c0da6 in CreateProcessW (parent.exe.obj)
2022-09-18T20:27:05.2085018Z             .PATH_NOT_FOUND => return error.FileNotFound,
2022-09-18T20:27:05.2086462Z                                ^
2022-09-18T20:27:05.2088185Z D:\a\1\s\stage3-release\lib\zig\std\child_process.zig:1072:5: 0x7ff6253c0c91 in windowsCreateProcess (parent.exe.obj)
2022-09-18T20:27:05.2091805Z     return windows.CreateProcessW(
2022-09-18T20:27:05.2092802Z     ^
2022-09-18T20:27:05.2095277Z D:\a\1\s\stage3-release\lib\zig\std\os\windows.zig:1598:32: 0x7ff6253c0da6 in CreateProcessW (parent.exe.obj)
2022-09-18T20:27:05.2100406Z             .PATH_NOT_FOUND => return error.FileNotFound,
2022-09-18T20:27:05.2101692Z                                ^
2022-09-18T20:27:05.2103803Z D:\a\1\s\stage3-release\lib\zig\std\child_process.zig:1072:5: 0x7ff6253c0c91 in windowsCreateProcess (parent.exe.obj)
2022-09-18T20:27:05.2107480Z     return windows.CreateProcessW(
2022-09-18T20:27:05.2108533Z     ^
2022-09-18T20:27:05.2110855Z D:\a\1\s\stage3-release\lib\zig\std\os\windows.zig:1598:32: 0x7ff6253c0da6 in CreateProcessW (parent.exe.obj)
2022-09-18T20:27:05.2116503Z             .PATH_NOT_FOUND => return error.FileNotFound,
2022-09-18T20:27:05.2117587Z                                ^
2022-09-18T20:27:05.2119377Z D:\a\1\s\stage3-release\lib\zig\std\child_process.zig:1072:5: 0x7ff6253c0c91 in windowsCreateProcess (parent.exe.obj)
2022-09-18T20:27:05.2127324Z     return windows.CreateProcessW(
2022-09-18T20:27:05.2128206Z     ^
2022-09-18T20:27:05.2129913Z D:\a\1\s\stage3-release\lib\zig\std\os\windows.zig:1598:32: 0x7ff6253c0da6 in CreateProcessW (parent.exe.obj)
2022-09-18T20:27:05.2137455Z             .PATH_NOT_FOUND => return error.FileNotFound,
2022-09-18T20:27:05.2138571Z                                ^
2022-09-18T20:27:05.2144302Z D:\a\1\s\stage3-release\lib\zig\std\child_process.zig:1072:5: 0x7ff6253c0c91 in windowsCreateProcess (parent.exe.obj)
2022-09-18T20:27:05.2148247Z     return windows.CreateProcessW(
2022-09-18T20:27:05.2149198Z     ^
2022-09-18T20:27:05.2151745Z D:\a\1\s\stage3-release\lib\zig\std\os\windows.zig:1598:32: 0x7ff6253c0da6 in CreateProcessW (parent.exe.obj)
2022-09-18T20:27:05.2157476Z             .PATH_NOT_FOUND => return error.FileNotFound,
2022-09-18T20:27:05.2158565Z                                ^
2022-09-18T20:27:05.2160567Z D:\a\1\s\stage3-release\lib\zig\std\child_process.zig:1072:5: 0x7ff6253c0c91 in windowsCreateProcess (parent.exe.obj)
2022-09-18T20:27:05.2165093Z     return windows.CreateProcessW(
2022-09-18T20:27:05.2166558Z     ^
2022-09-18T20:27:05.2183850Z The following command exited with error code 1 (expected 0):
2022-09-18T20:27:05.2185405Z cd D:\a\1\s\test\standalone\childprocess_minimal && D:\a\1\s\test\standalone\childprocess_minimal\zig-out\bin\parent.exe 
2022-09-18T20:27:05.2186538Z error: UnexpectedExitCode
2022-09-18T20:27:05.2271437Z D:\a\1\s\stage3-release\lib\zig\std\build\RunStep.zig:277:17: 0x7ff6ab39b93f in runCommand (build.exe.obj)
2022-09-18T20:27:05.2273102Z                 return error.UnexpectedExitCode;
2022-09-18T20:27:05.2274091Z                 ^
2022-09-18T20:27:05.2277588Z D:\a\1\s\stage3-release\lib\zig\std\build\RunStep.zig:183:5: 0x7ff6ab391dca in make (build.exe.obj)
2022-09-18T20:27:05.2279032Z     try runCommand(
2022-09-18T20:27:05.2279986Z     ^
2022-09-18T20:27:05.2281086Z D:\a\1\s\stage3-release\lib\zig\std\build.zig:3638:9: 0x7ff6ab33cfd9 in make (build.exe.obj)
2022-09-18T20:27:05.2295484Z         try self.makeFn(self);
2022-09-18T20:27:05.2296470Z         ^
2022-09-18T20:27:05.2298298Z D:\a\1\s\stage3-release\lib\zig\std\build.zig:509:9: 0x7ff6ab32c305 in makeOneStep (build.exe.obj)
2022-09-18T20:27:05.2299294Z         try s.make();
2022-09-18T20:27:05.2300151Z         ^
2022-09-18T20:27:05.2301277Z D:\a\1\s\stage3-release\lib\zig\std\build.zig:503:17: 0x7ff6ab32c285 in makeOneStep (build.exe.obj)
2022-09-18T20:27:05.2302400Z                 return err;
2022-09-18T20:27:05.2303383Z                 ^
2022-09-18T20:27:05.2304840Z D:\a\1\s\stage3-release\lib\zig\std\build.zig:464:13: 0x7ff6ab32bfe1 in make (build.exe.obj)
2022-09-18T20:27:05.2306954Z             try self.makeOneStep(s);
2022-09-18T20:27:05.2307891Z             ^
2022-09-18T20:27:05.2309217Z D:\a\1\s\stage3-release\lib\zig\build_runner.zig:223:21: 0x7ff6ab32f05d in main (build.exe.obj)
2022-09-18T20:27:05.2310497Z             else => return err,
2022-09-18T20:27:05.2311347Z                     ^
2022-09-18T20:27:05.2312647Z D:\a\1\s\stage3-release\lib\zig\std\os\windows.zig:127:35: 0x7ff6ab36d875 in OpenFile (build.exe.obj)
2022-09-18T20:27:05.2314194Z         .OBJECT_PATH_NOT_FOUND => return error.FileNotFound,
2022-09-18T20:27:05.2315494Z                                   ^
2022-09-18T20:27:05.2317070Z D:\a\1\s\stage3-release\lib\zig\std\os.zig:2779:21: 0x7ff6ab33cc31 in mkdiratW (build.exe.obj)
2022-09-18T20:27:05.2325439Z         else => |e| return e,
2022-09-18T20:27:05.2326627Z                     ^
2022-09-18T20:27:05.2328232Z D:\a\1\s\stage3-release\lib\zig\std\os.zig:2702:9: 0x7ff6ab32b700 in mkdirat (build.exe.obj)
2022-09-18T20:27:05.2336057Z         return mkdiratW(dir_fd, sub_dir_path_w.span(), mode);
2022-09-18T20:27:05.2337270Z         ^
2022-09-18T20:27:05.2338594Z D:\a\1\s\stage3-release\lib\zig\std\fs.zig:1361:9: 0x7ff6ab32b600 in makeDir (build.exe.obj)
2022-09-18T20:27:05.2343548Z         try os.mkdirat(self.fd, sub_path, default_new_dir_mode);
2022-09-18T20:27:05.2344673Z         ^
2022-09-18T20:27:05.2346802Z D:\a\1\s\stage3-release\lib\zig\std\os\windows.zig:126:35: 0x7ff6ab36d846 in OpenFile (build.exe.obj)
2022-09-18T20:27:05.2348587Z         .OBJECT_NAME_NOT_FOUND => return error.FileNotFound,
2022-09-18T20:27:05.2349509Z                                   ^
2022-09-18T20:27:05.2351518Z D:\a\1\s\stage3-release\lib\zig\std\fs.zig:1159:23: 0x7ff6ab370d73 in openFileW (build.exe.obj)
2022-09-18T20:27:05.2356231Z             .handle = try w.OpenFile(sub_path_w, .{
2022-09-18T20:27:05.2357148Z                       ^
2022-09-18T20:27:05.2358698Z D:\a\1\s\stage3-release\lib\zig\std\fs.zig:1031:13: 0x7ff6ab35166e in openFile (build.exe.obj)
2022-09-18T20:27:05.2362842Z             return self.openFileW(path_w.span(), flags);
2022-09-18T20:27:05.2363694Z             ^
2022-09-18T20:27:05.2366005Z D:\a\1\s\stage3-release\lib\zig\std\os\windows.zig:134:35: 0x7ff6ab36d98c in OpenFile (build.exe.obj)
2022-09-18T20:27:05.2369056Z         .OBJECT_NAME_COLLISION => return error.PathAlreadyExists,
2022-09-18T20:27:05.2369999Z                                   ^
2022-09-18T20:27:05.2371636Z D:\a\1\s\stage3-release\lib\zig\std\os.zig:2779:21: 0x7ff6ab33cc31 in mkdiratW (build.exe.obj)
2022-09-18T20:27:05.2379194Z         else => |e| return e,
2022-09-18T20:27:05.2380193Z                     ^
2022-09-18T20:27:05.2381344Z D:\a\1\s\stage3-release\lib\zig\std\os.zig:2702:9: 0x7ff6ab32b700 in mkdirat (build.exe.obj)
2022-09-18T20:27:05.2389244Z         return mkdiratW(dir_fd, sub_dir_path_w.span(), mode);
2022-09-18T20:27:05.2390227Z         ^
2022-09-18T20:27:05.2391460Z D:\a\1\s\stage3-release\lib\zig\std\fs.zig:1361:9: 0x7ff6ab32b600 in makeDir (build.exe.obj)
2022-09-18T20:27:05.2396461Z         try os.mkdirat(self.fd, sub_path, default_new_dir_mode);
2022-09-18T20:27:05.2397427Z         ^
2022-09-18T20:27:05.2399909Z D:\a\1\s\stage3-release\lib\zig\std\os\windows.zig:126:35: 0x7ff6ab36d846 in OpenFile (build.exe.obj)
2022-09-18T20:27:05.2401814Z         .OBJECT_NAME_NOT_FOUND => return error.FileNotFound,
2022-09-18T20:27:05.2402634Z                                   ^
2022-09-18T20:27:05.2405133Z D:\a\1\s\stage3-release\lib\zig\std\fs.zig:1159:23: 0x7ff6ab370d73 in openFileW (build.exe.obj)
2022-09-18T20:27:05.2410063Z             .handle = try w.OpenFile(sub_path_w, .{
2022-09-18T20:27:05.2411108Z                       ^
2022-09-18T20:27:05.2412749Z D:\a\1\s\stage3-release\lib\zig\std\fs.zig:1031:13: 0x7ff6ab35166e in openFile (build.exe.obj)
2022-09-18T20:27:05.2417358Z             return self.openFileW(path_w.span(), flags);
2022-09-18T20:27:05.2418486Z             ^
2022-09-18T20:27:05.2420812Z D:\a\1\s\stage3-release\lib\zig\std\os\windows.zig:134:35: 0x7ff6ab36d98c in OpenFile (build.exe.obj)
2022-09-18T20:27:05.2422313Z         .OBJECT_NAME_COLLISION => return error.PathAlreadyExists,
2022-09-18T20:27:05.2423138Z                                   ^
2022-09-18T20:27:05.2425219Z D:\a\1\s\stage3-release\lib\zig\std\os.zig:2779:21: 0x7ff6ab33cc31 in mkdiratW (build.exe.obj)
2022-09-18T20:27:05.2433907Z         else => |e| return e,
2022-09-18T20:27:05.2434906Z                     ^
2022-09-18T20:27:05.2435936Z D:\a\1\s\stage3-release\lib\zig\std\os.zig:2702:9: 0x7ff6ab32b700 in mkdirat (build.exe.obj)
2022-09-18T20:27:05.2443678Z         return mkdiratW(dir_fd, sub_dir_path_w.span(), mode);
2022-09-18T20:27:05.2445061Z         ^
2022-09-18T20:27:05.2446102Z D:\a\1\s\stage3-release\lib\zig\std\fs.zig:1361:9: 0x7ff6ab32b600 in makeDir (build.exe.obj)
2022-09-18T20:27:05.2452243Z         try os.mkdirat(self.fd, sub_path, default_new_dir_mode);
2022-09-18T20:27:05.2453304Z         ^
2022-09-18T20:27:05.2455678Z D:\a\1\s\stage3-release\lib\zig\std\os\windows.zig:126:35: 0x7ff6ab36d846 in OpenFile (build.exe.obj)
2022-09-18T20:27:05.2458022Z         .OBJECT_NAME_NOT_FOUND => return error.FileNotFound,
2022-09-18T20:27:05.2458896Z                                   ^
2022-09-18T20:27:05.2461828Z D:\a\1\s\stage3-release\lib\zig\std\fs.zig:1159:23: 0x7ff6ab370d73 in openFileW (build.exe.obj)
2022-09-18T20:27:05.2466523Z             .handle = try w.OpenFile(sub_path_w, .{
2022-09-18T20:27:05.2467583Z                       ^
2022-09-18T20:27:05.2469279Z D:\a\1\s\stage3-release\lib\zig\std\fs.zig:1031:13: 0x7ff6ab35166e in openFile (build.exe.obj)
2022-09-18T20:27:05.2473911Z             return self.openFileW(path_w.span(), flags);
2022-09-18T20:27:05.2474789Z             ^
2022-09-18T20:27:05.2477116Z D:\a\1\s\stage3-release\lib\zig\std\os\windows.zig:134:35: 0x7ff6ab36d98c in OpenFile (build.exe.obj)
2022-09-18T20:27:05.2478985Z         .OBJECT_NAME_COLLISION => return error.PathAlreadyExists,
2022-09-18T20:27:05.2480040Z                                   ^
2022-09-18T20:27:05.2481171Z D:\a\1\s\stage3-release\lib\zig\std\os.zig:2779:21: 0x7ff6ab33cc31 in mkdiratW (build.exe.obj)
2022-09-18T20:27:05.2489623Z         else => |e| return e,
2022-09-18T20:27:05.2490679Z                     ^
2022-09-18T20:27:05.2491631Z D:\a\1\s\stage3-release\lib\zig\std\os.zig:2702:9: 0x7ff6ab32b700 in mkdirat (build.exe.obj)
2022-09-18T20:27:05.2501237Z         return mkdiratW(dir_fd, sub_dir_path_w.span(), mode);
2022-09-18T20:27:05.2502138Z         ^
2022-09-18T20:27:05.2503137Z D:\a\1\s\stage3-release\lib\zig\std\fs.zig:1361:9: 0x7ff6ab32b600 in makeDir (build.exe.obj)
2022-09-18T20:27:05.2508584Z         try os.mkdirat(self.fd, sub_path, default_new_dir_mode);
2022-09-18T20:27:05.2509657Z         ^
2022-09-18T20:27:05.2532301Z error: the following build command failed with exit code 1:
2022-09-18T20:27:05.2533940Z D:\a\1\s\test\standalone\childprocess_minimal\zig-cache\o\d62f712e16155a6539cfc38e83eae8d8\build.exe D:\a\1\s\stage3-release\bin\zig.exe D:\a\1\s\test\standalone\childprocess_minimal D:\a\1\s\test\standalone\childprocess_minimal\zig-cache C:\Users\VssAdministrator\AppData\Local\zig test
2022-09-18T20:27:05.2677132Z The following command exited with error code 1 (expected 0):
2022-09-18T20:27:05.2678691Z cd D:\a\1\s && stage3-release\bin\zig.exe build --build-file D:\a\1\s\test\standalone\childprocess_minimal\build.zig test 
2022-09-18T20:27:05.2752720Z error: UnexpectedExitCode
2022-09-18T20:27:05.2843581Z D:\a\1\s\stage3-release\lib\zig\std\build.zig:2110:13: 0x7ff66731574c in runPkgConfig (build.exe.obj)
2022-09-18T20:27:05.2850558Z             return error.PackageNotFound;
2022-09-18T20:27:05.2851563Z             ^
2022-09-18T20:27:05.2856267Z D:\a\1\s\stage3-release\lib\zig\std\build.zig:2110:13: 0x7ff66731574c in runPkgConfig (build.exe.obj)
2022-09-18T20:27:05.2863120Z             return error.PackageNotFound;
2022-09-18T20:27:05.2863960Z             ^
2022-09-18T20:27:05.2869839Z D:\a\1\s\stage3-release\lib\zig\std\build.zig:2110:13: 0x7ff66731574c in runPkgConfig (build.exe.obj)
2022-09-18T20:27:05.2876869Z             return error.PackageNotFound;
2022-09-18T20:27:05.2877946Z             ^
2022-09-18T20:27:05.2883148Z D:\a\1\s\stage3-release\lib\zig\std\build.zig:2110:13: 0x7ff66731574c in runPkgConfig (build.exe.obj)
2022-09-18T20:27:05.2889927Z             return error.PackageNotFound;
2022-09-18T20:27:05.2890949Z             ^
2022-09-18T20:27:05.2896075Z D:\a\1\s\stage3-release\lib\zig\std\build.zig:2110:13: 0x7ff66731574c in runPkgConfig (build.exe.obj)
2022-09-18T20:27:05.2902790Z             return error.PackageNotFound;
2022-09-18T20:27:05.2904751Z             ^
2022-09-18T20:27:05.2908894Z D:\a\1\s\stage3-release\lib\zig\std\build.zig:2110:13: 0x7ff66731574c in runPkgConfig (build.exe.obj)
2022-09-18T20:27:05.2915519Z             return error.PackageNotFound;
2022-09-18T20:27:05.2916470Z             ^
2022-09-18T20:27:05.2922200Z D:\a\1\s\stage3-release\lib\zig\std\build.zig:2110:13: 0x7ff66731574c in runPkgConfig (build.exe.obj)
2022-09-18T20:27:05.2931289Z             return error.PackageNotFound;
2022-09-18T20:27:05.2932421Z             ^
2022-09-18T20:27:05.2936286Z D:\a\1\s\stage3-release\lib\zig\std\build.zig:2110:13: 0x7ff66731574c in runPkgConfig (build.exe.obj)
2022-09-18T20:27:05.2942983Z             return error.PackageNotFound;
2022-09-18T20:27:05.2943812Z             ^
2022-09-18T20:27:05.2949330Z D:\a\1\s\stage3-release\lib\zig\std\build.zig:2110:13: 0x7ff66731574c in runPkgConfig (build.exe.obj)
2022-09-18T20:27:05.2955656Z             return error.PackageNotFound;
2022-09-18T20:27:05.2956493Z             ^
2022-09-18T20:27:05.2961632Z D:\a\1\s\stage3-release\lib\zig\std\build.zig:2110:13: 0x7ff66731574c in runPkgConfig (build.exe.obj)
2022-09-18T20:27:05.2968516Z             return error.PackageNotFound;
2022-09-18T20:27:05.2969388Z             ^
2022-09-18T20:27:05.2972221Z D:\a\1\s\stage3-release\lib\zig\std\os\windows.zig:134:35: 0x7ff6672afc5c in OpenFile (build.exe.obj)
2022-09-18T20:27:05.2974022Z         .OBJECT_NAME_COLLISION => return error.PathAlreadyExists,
2022-09-18T20:27:05.2974980Z                                   ^
2022-09-18T20:27:05.2976097Z D:\a\1\s\stage3-release\lib\zig\std\os.zig:2779:21: 0x7ff66726cf31 in mkdiratW (build.exe.obj)
2022-09-18T20:27:05.2987931Z         else => |e| return e,
2022-09-18T20:27:05.2988953Z                     ^
2022-09-18T20:27:05.2990451Z D:\a\1\s\stage3-release\lib\zig\std\os.zig:2702:9: 0x7ff66724b700 in mkdirat (build.exe.obj)
2022-09-18T20:27:05.2999535Z         return mkdiratW(dir_fd, sub_dir_path_w.span(), mode);
2022-09-18T20:27:05.3000639Z         ^
2022-09-18T20:27:05.3001884Z D:\a\1\s\stage3-release\lib\zig\std\fs.zig:1361:9: 0x7ff66724b600 in makeDir (build.exe.obj)
2022-09-18T20:27:05.3009239Z         try os.mkdirat(self.fd, sub_path, default_new_dir_mode);
2022-09-18T20:27:05.3010441Z         ^
2022-09-18T20:27:05.3014498Z D:\a\1\s\stage3-release\lib\zig\std\build\RunStep.zig:277:17: 0x7ff6672eb61f in runCommand (build.exe.obj)
2022-09-18T20:27:05.3016361Z                 return error.UnexpectedExitCode;
2022-09-18T20:27:05.3017730Z                 ^
2022-09-18T20:27:05.3021368Z D:\a\1\s\stage3-release\lib\zig\std\build\RunStep.zig:183:5: 0x7ff6672c6e2a in make (build.exe.obj)
2022-09-18T20:27:05.3022490Z     try runCommand(
2022-09-18T20:27:05.3023315Z     ^
2022-09-18T20:27:05.3024723Z D:\a\1\s\stage3-release\lib\zig\std\build.zig:3638:9: 0x7ff66726d2d9 in make (build.exe.obj)
2022-09-18T20:27:05.3036238Z         try self.makeFn(self);
2022-09-18T20:27:05.3037440Z         ^
2022-09-18T20:27:05.3038617Z D:\a\1\s\stage3-release\lib\zig\std\build.zig:509:9: 0x7ff66724c305 in makeOneStep (build.exe.obj)
2022-09-18T20:27:05.3040424Z         try s.make();
2022-09-18T20:27:05.3041183Z         ^
2022-09-18T20:27:05.3042309Z D:\a\1\s\stage3-release\lib\zig\std\build.zig:503:17: 0x7ff66724c285 in makeOneStep (build.exe.obj)
2022-09-18T20:27:05.3044055Z                 return err;
2022-09-18T20:27:05.3044854Z                 ^
2022-09-18T20:27:05.3045979Z D:\a\1\s\stage3-release\lib\zig\std\build.zig:503:17: 0x7ff66724c285 in makeOneStep (build.exe.obj)
2022-09-18T20:27:05.3047374Z                 return err;
2022-09-18T20:27:05.3048505Z                 ^
2022-09-18T20:27:05.3049842Z D:\a\1\s\stage3-release\lib\zig\std\build.zig:503:17: 0x7ff66724c285 in makeOneStep (build.exe.obj)
2022-09-18T20:27:05.3051128Z                 return err;
2022-09-18T20:27:05.3052169Z                 ^
2022-09-18T20:27:05.3053160Z D:\a\1\s\stage3-release\lib\zig\std\build.zig:464:13: 0x7ff66724bfe1 in make (build.exe.obj)
2022-09-18T20:27:05.3054575Z             try self.makeOneStep(s);
2022-09-18T20:27:05.3055631Z             ^
2022-09-18T20:27:05.3056792Z D:\a\1\s\stage3-release\lib\zig\build_runner.zig:223:21: 0x7ff66724f05d in main (build.exe.obj)
2022-09-18T20:27:05.3058198Z             else => return err,
2022-09-18T20:27:05.3059117Z                     ^
2022-09-18T20:27:05.3063415Z D:\a\1\s\stage3-release\lib\zig\std\build.zig:2110:13: 0x7ff66731574c in runPkgConfig (build.exe.obj)
2022-09-18T20:27:05.3070274Z             return error.PackageNotFound;
2022-09-18T20:27:05.3071093Z             ^
2022-09-18T20:27:05.3075937Z D:\a\1\s\stage3-release\lib\zig\std\build.zig:2110:13: 0x7ff66731574c in runPkgConfig (build.exe.obj)
2022-09-18T20:27:05.3082853Z             return error.PackageNotFound;
2022-09-18T20:27:05.3083686Z             ^
2022-09-18T20:27:05.3093508Z D:\a\1\s\stage3-release\lib\zig\std\build.zig:2110:13: 0x7ff66731574c in runPkgConfig (build.exe.obj)
2022-09-18T20:27:05.3100044Z             return error.PackageNotFound;
2022-09-18T20:27:05.3100928Z             ^
2022-09-18T20:27:05.3105693Z D:\a\1\s\stage3-release\lib\zig\std\build.zig:2110:13: 0x7ff66731574c in runPkgConfig (build.exe.obj)
2022-09-18T20:27:05.3113036Z             return error.PackageNotFound;
2022-09-18T20:27:05.3113970Z             ^
2022-09-18T20:27:05.3119764Z D:\a\1\s\stage3-release\lib\zig\std\build.zig:2110:13: 0x7ff66731574c in runPkgConfig (build.exe.obj)
2022-09-18T20:27:05.3126390Z             return error.PackageNotFound;
2022-09-18T20:27:05.3127792Z             ^
2022-09-18T20:27:05.3133708Z D:\a\1\s\stage3-release\lib\zig\std\build.zig:2110:13: 0x7ff66731574c in runPkgConfig (build.exe.obj)
2022-09-18T20:27:05.3140649Z             return error.PackageNotFound;
2022-09-18T20:27:05.3141589Z             ^
2022-09-18T20:27:05.3147254Z D:\a\1\s\stage3-release\lib\zig\std\build.zig:2110:13: 0x7ff66731574c in runPkgConfig (build.exe.obj)
2022-09-18T20:27:05.3153586Z             return error.PackageNotFound;
2022-09-18T20:27:05.3154498Z             ^
2022-09-18T20:27:05.3159604Z D:\a\1\s\stage3-release\lib\zig\std\build.zig:2110:13: 0x7ff66731574c in runPkgConfig (build.exe.obj)
2022-09-18T20:27:05.3165754Z             return error.PackageNotFound;
2022-09-18T20:27:05.3167106Z             ^
2022-09-18T20:27:05.3172561Z D:\a\1\s\stage3-release\lib\zig\std\build.zig:2110:13: 0x7ff66731574c in runPkgConfig (build.exe.obj)
2022-09-18T20:27:05.3180702Z             return error.PackageNotFound;
2022-09-18T20:27:05.3182037Z             ^
2022-09-18T20:27:05.3203190Z error: the following build command failed with exit code 1:
2022-09-18T20:27:05.3204859Z D:\a\1\s\zig-cache\o\61766c497271fea95492f018252e39b9\build.exe D:\a\1\s\stage3-release\bin\zig.exe D:\a\1\s D:\a\1\s\zig-cache C:\Users\VssAdministrator\AppData\Local\zig test docs --search-prefix D:\a\1\s\zig+llvm+lld+clang-x86_64-windows-gnu-0.10.0-dev.61+9be8396b7 -Dstatic-llvm -Dskip-non-native
2022-09-18T20:27:05.6194440Z ##[error]PowerShell exited with code '1'.
2022-09-18T20:27:05.6710839Z ##[section]Finishing: Test
```

</details>

**Comment by andrewrk** [comment]
This was never passing the CI and is now stale. Feel free to open a new PR if you want to continue these efforts. I suggest to get tests passing locally before opening the PR.

**Pull request closed without merging**
