### PR TITLE
add docs step to default `build.zig` templates

### PR DESCRIPTION
**Pull request by sudw1n**
The default build files created from `zig init-exe` or `zig init-lib` don't provide a way to generate documentation of the package/library. In my experience, it isn't obvious how to use the `getEmittedDocs()` function. Wanting to generate documentation was a usual thing coming from something like `cargo doc` (Rust) so I was surprised the Zig build system didn't have something similar in place. This pull request proposes we add this feature as a (optional) step for the build system.

### CODE REVIEW

**Comment by IntegratedQuantum** [comment]
I understand that this is a common use case for libraries.
But why add it to executables as well?

**Comment by der-teufel-programming** [comment]
That's a valid concern. Also I think it's unnecessary to do
```zig
install_docs.step.dependOn(&lib.step);
```
It isn't necessary to build the final binary to generate documentation and for big projects emitting the binary might take a long time which would slow down docs generation without need

**Comment by sudw1n** [comment]
> But why add it to executables as well?
Yeah, I was initially just going to add that to the `init-lib` template, but figured having it in both would appear more consistent.
I only intended for this to be a proposal for adding a `docs` step to the default templates. I am not even sure what I've shown is the correct way to do it.

**Comment by sudw1n** [comment]
> It isn't necessary to build the final binary to generate documentation

Thanks, I didn't know that. I've made the necessary changes in the latest commit.

**Comment by IntegratedQuantum** [comment]
> Yeah, I was initially just going to add that to the init-lib template, but figured having it in both would appear more consistent.

Is consistency really a good reason here? They're clearly meant for different things. Like init-lib also doesn't have a run step either.

**Comment by sudw1n** [comment]
That's a fair point. I suppose I should just leave `init-exe` alone.

**Pull request closed without merging**
