### PR TITLE
std: `os.renameatW` properly fail with `PathAlreadyExists`

### PR DESCRIPTION
**Pull request by jagt**
Before this fix `os.renameatW` never fail with `PathAlreadyExists`. When dest path exists it fails with `AccessDenied`.
To me this causes most of my `zig build` stuck trouble described in here: <https://github.com/ziglang/zig/issues/8362>

A simple fixture that demonstrate current behavior:

```zig
const std = @import("std");
const testing = std.testing;

test "rename on windows" {
    const cwd = std.fs.cwd();

    cwd.makeDir("foo") catch {};
    cwd.makeDir("bar") catch {};

    try testing.expectError(error.AccessDenied, std.fs.rename(cwd, "foo", cwd, "bar"));
}
```

After this commit the test should be like this:

```zig
    try testing.expectError(error.PathAlreadyExists, std.fs.rename(cwd, "foo", cwd, "bar"));
```

I believe this should mitigate the `zig build` AccessDenied problem quite a lot on windows.

The concerning part is that this change added a new system call on the `AccessDenied` error code path. 

Another way to address the zig build issue is to change the behavior of `renameTmpIntoCache` so that it checks dest dir befor rename on windows.

Thanks in advance!

### CODE REVIEW

**Comment by squeek502** [comment]
Note that rename for directories is broken more generally on Windows (#6364), so this could be a misdiagnosis of the problem you're encountering.

Also, this is different than how non-Windows platforms handle this particular rename, as on Linux renaming a dir onto an empty dir succeeds, and PathAlreadyExists only occurs if the destination is a non-empty directory:

```zig
const std = @import("std");
const testing = std.testing;

test "rename onto empty dir" {
    var tmp_dir = testing.tmpDir(.{});
    defer tmp_dir.cleanup();

    try tmp_dir.dir.makeDir("test_dir");
    try tmp_dir.dir.makeDir("target_dir");
    try tmp_dir.dir.rename("test_dir", "target_dir");

    // Ensure the directory was renamed
    try testing.expectError(error.FileNotFound, tmp_dir.dir.openDir("test_dir", .{}));
    var dir = try tmp_dir.dir.openDir("target_dir", .{});
    dir.close();
}

test "rename onto non-empty dir" {
    var tmp_dir = testing.tmpDir(.{});
    defer tmp_dir.cleanup();

    try tmp_dir.dir.makeDir("test_dir");

    var target_dir = try tmp_dir.dir.makeOpenPath("target_dir", .{});
    var file = try target_dir.createFile("test_file", .{ .read = true });
    file.close();
    target_dir.close();

    // Rename will fail with PathAlreadyExists if target_dir is non-empty
    try testing.expectError(error.PathAlreadyExists, tmp_dir.dir.rename("test_dir", "target_dir"));

    // Ensure the directory was not renamed
    var dir = try tmp_dir.dir.openDir("test_dir", .{});
    dir.close();
}
```
On Linux gives:

```
$ zig test rename.zig
All 2 tests passed.
```

There's also some test code in the Zig std library that tests some of this stuff (but is currently skipped on Windows):

https://github.com/ziglang/zig/blob/d2681d2537b630359657e117ed77cf12a15bb7df/lib/std/fs/test.zig#L436-L477

This also ties into https://github.com/ziglang/zig/issues/6600, since it's still slightly unclear how these types of platform differences should be handled by `std.os`.

**Comment by jagt** [comment]
Thanks for the info! For the `rename onto empty dir` case it's pretty surprising.
I did noticed that there's a previous cl <https://github.com/ziglang/zig/commit/d3f87f8ac01039722197a13a12342fc747a90567> that explicitly allow `fs.rename` work on dir on windows.

I do agree that make fs things work is tricky. I'll fire for a separated PR to hack around `renameTmpIntoCache` for now since that's the thing I'm trying to fix.

**Comment by jagt** [comment]
I've opened <https://github.com/ziglang/zig/pull/11419> in which addresses the same issue.

**Comment by andrewrk** [comment]
Instead of solving this problem by adding more syscalls on Windows to try to match the POSIX interface, I would like to instead solve this by making `std.os.renameat` be a compile error on Windows. Any code paths that call `std.os.renameat` will have to be updated to have conditional compilation for Windows and handle it differently. This way Windows users will still get the ideal experience which does not make unnecessary syscalls.

I think this is a perfect example of what #6600 is intended to address.
See also: #5019

**Comment by squeek502** [comment]
> Instead of solving this problem by adding more syscalls on Windows to try to match the POSIX interface, I would like to instead solve this by making std.os.renameat be a compile error on Windows. Any code paths that call std.os.renameat will have to be updated to have conditional compilation for Windows and handle it differently. This way Windows users will still get the ideal experience which does not make unnecessary syscalls.

Does this mean that something like`std.fs.Dir.rename` would have different behavior per-platform? Or would the idea be to make `std.fs.Dir.rename` not necessarily conform to POSIX `rename` either, but instead find some common-ground functionality that works efficiently-enough for all platforms? Or would this rule out `rename` from being able to be part of `std.fs` at all, and instead users would need to call the os-specific functions and handle the differences themselves?

**Comment by andrewrk** [comment]
Different behavior per platform is one possible resolution to the problem. I would describe the design space like this:
* If there is a behavior definition that we can choose that lowers to a single syscall on all platforms and the differences are minor enough, then this is a nice approach. We can see this for a few functions in std.fs which document that they are atomic on some platforms and not on others.
* Otherwise, the next strategy is to make the functions more specific in their semantics. Then they will lower to one syscall on some platforms and multiple on others. The user will call the one with the matching semantics they need and get the ideal lowering for each platform.

For the case of rename, the second approach seems like it might be the way to go to me.

**Pull request closed without merging**
