### PR TITLE
Trailing comma is respected for builtin calls

### PR DESCRIPTION
**Pull request by LemonBoy**

### CODE REVIEW

**Comment by andrewrk** [comment]
Reverted in f83411b0b1b857c7f8679e3b90d2093ba60621d4 due to test breakage. Apologies for the premature merge.

**Comment by LemonBoy** [comment]
@Vexu Can you have a look at this? I think `translate-c` is emitting a trailing comma somewhere down the long chain of generated casts :thinking:

**Comment by Vexu** [comment]
I think the problem is in `transCCast` where `expr` is rendered before any of the casts which means the comma between the type and the expression is also a trailing comma.

**Comment by LemonBoy** [comment]
> I think the problem is in transCCast where expr is rendered before any of the casts which means the comma between the type and the expression is also a trailing comma.

Yup, the problem also seems to show up when translating `#define FOO ((unsigned char)'\377')`.
I've worked around the problem in #4058 but I don't really know if the token order is an invariant we must respect here.

**Pull request merged**
