### PR TITLE
translate-c: Correctly translate enum init values, addressing #1360

### LINKED ISSUE #1360: translate-c incorrectly translates enum init values
```c
typedef enum VkResult {
    VK_SUCCESS = 0,
    VK_NOT_READY = 1,
    VK_TIMEOUT = 2,
    VK_EVENT_SET = 3,
    VK_EVENT_RESET = 4,
    VK_INCOMPLETE = 5,
    VK_ERROR_OUT_OF_HOST_MEMORY = -1,
    VK_ERROR_OUT_OF_DEVICE_MEMORY = -2,
    VK_ERROR_INITIALIZATION_FAILED = -3,
    VK_ERROR_DEVICE_LOST = -4,
    VK_ERROR_MEMORY_MAP_FAILED = -5,
    VK_ERROR_LAYER_NOT_PRESENT = -6,
    VK_ERROR_EXTENSION_NOT_PRESENT = -7,
    VK_ERROR_FEATURE_NOT_PRESENT = -8,
    VK_ERROR_INCOMPATIBLE_DRIVER = -9,
    VK_ERROR_TOO_MANY_OBJECTS = -10,
    VK_ERROR_FORMAT_NOT_SUPPORTED = -11,
    VK_ERROR_FRAGMENTED_POOL = -12,
    VK_ERROR_OUT_OF_POOL_MEMORY = -1000069000,
    VK_ERROR_INVALID_EXTERNAL_HANDLE = -1000072003,
    VK_ERROR_SURFACE_LOST_KHR = -1000000000,
    VK_ERROR_NATIVE_WINDOW_IN_USE_KHR = -1000000001,
    VK_SUBOPTIMAL_KHR = 1000001003,
    VK_ERROR_OUT_OF_DATE_KHR = -1000001004,
    VK_ERROR_INCOMPATIBLE_DISPLAY_KHR = -1000003001,
    VK_ERROR_VALIDATION_FAILED_EXT = -1000011001,
    VK_ERROR_INVALID_SHADER_NV = -1000012000,
    VK_ERROR_FRAGMENTATION_EXT = -1000161000,
    VK_ERROR_NOT_PERMITTED_EXT = -1000174001,
    VK_ERROR_OUT_OF_POOL_MEMORY_KHR = VK_ERROR_OUT_OF_POOL_MEMORY,
    VK_ERROR_INVALID_EXTERNAL_HANDLE_KHR = VK_ERROR_INVALID_EXTERNAL_HANDLE,
    VK_RESULT_BEGIN_RANGE = VK_ERROR_FRAGMENTED_POOL,
    VK_RESULT_END_RANGE = VK_INCOMPLETE,
    VK_RESULT_RANGE_SIZE = (VK_INCOMPLETE - VK_ERROR_FRAGMENTED_POOL + 1),
    VK_RESULT_MAX_ENUM = 0x7FFFFFFF
} VkResult;
```

```zig
pub const enum_VkResult = extern enum {
    VK_SUCCESS = 0,
    VK_NOT_READY = 1,
    VK_TIMEOUT = 2,
    VK_EVENT_SET = 3,
    VK_EVENT_RESET = 4,
    VK_INCOMPLETE = 5,
    VK_ERROR_OUT_OF_HOST_MEMORY = -4294967295,
    VK_ERROR_OUT_OF_DEVICE_MEMORY = -4294967294,
    VK_ERROR_INITIALIZATION_FAILED = -4294967293,
    VK_ERROR_DEVICE_LOST = -4294967292,
    VK_ERROR_MEMORY_MAP_FAILED = -4294967291,
    VK_ERROR_LAYER_NOT_PRESENT = -4294967290,
    VK_ERROR_EXTENSION_NOT_PRESENT = -4294967289,
    VK_ERROR_FEATURE_NOT_PRESENT = -4294967288,
    VK_ERROR_INCOMPATIBLE_DRIVER = -4294967287,
    VK_ERROR_TOO_MANY_OBJECTS = -4294967286,
    VK_ERROR_FORMAT_NOT_SUPPORTED = -4294967285,
    VK_ERROR_FRAGMENTED_POOL = -4294967284,
    VK_ERROR_OUT_OF_POOL_MEMORY = -3294898296,
    VK_ERROR_INVALID_EXTERNAL_HANDLE = -3294895293,
    VK_ERROR_SURFACE_LOST_KHR = -3294967296,
    VK_ERROR_NATIVE_WINDOW_IN_USE_KHR = -3294967295,
    VK_SUBOPTIMAL_KHR = 1000001003,
    VK_ERROR_OUT_OF_DATE_KHR = -3294966292,
    VK_ERROR_INCOMPATIBLE_DISPLAY_KHR = -3294964295,
    VK_ERROR_VALIDATION_FAILED_EXT = -3294956295,
    VK_ERROR_INVALID_SHADER_NV = -3294955296,
    VK_ERROR_FRAGMENTATION_EXT = -3294806296,
    VK_ERROR_NOT_PERMITTED_EXT = -3294793295,
    VK_ERROR_OUT_OF_POOL_MEMORY_KHR = -3294898296,
    VK_ERROR_INVALID_EXTERNAL_HANDLE_KHR = -3294895293,
    VK_RESULT_BEGIN_RANGE = -4294967284,
    VK_RESULT_END_RANGE = 5,
    VK_RESULT_RANGE_SIZE = 18,
    VK_RESULT_MAX_ENUM = 2147483647,
};
```

### PR DESCRIPTION
**Pull request by mtn**
Fixes #1360 

This was literally my first time looking closely at clang or llvm, so there could be a better way of doing things. I think it may also be possible to use a bit mask after grabbing the raw data to deal with the fact that it gets cast (which I think was the whole issue).

Also, I found the compiler pretty easy to understand, which was awesome!

### CODE REVIEW

**Comment by kristate** [comment]
Thanks! Please add some test cases, since we will have to fix this in stage2 as well.

**Comment by mtn** [comment]
@kristate Done :) It's a more minimal example than what was in the original issue, but tests for the same error.

**Comment by mtn** [comment]
Oh right, I didn't look at `bigint_init_data`, but that completely makes sense. In hindsight I probably shouldn't been more confused by my incorrect mental model. I'll take another look now.

**Comment by mtn** [comment]
I might be wrong, but I think my last commit fixes the issue, and doesn't break on values greater than 64 bits, since it uses APSInt builtins to flip negatives to positives.

I can clean up the code before merging, assuming it's correct.

**Comment by kristate** [comment]
@mtn I pushed some changes to your repo -- please merge them: mtn/zig#1

Thanks!

**Comment by andrewrk** [comment]
Thanks!

**Pull request merged**
