### PR TITLE
Sema: combine signed->unsigned and shrinkage runtime checks in intCast

### PR DESCRIPTION
**Pull request by wsengir**
Shout-out to @mitchellh who laid out the groundwork for these intCast runtime safety checks. This is just a bit of algebra to combine the two compares.

### CODE REVIEW

**Review by mitchellh — COMMENTED** [review]
Beautiful. Thanks so much for cleaning this up!

**Comment by wsengir** [comment]
This is currently blocked by `subwrap` support in non-LLVM backends, but there's no rush. I'm not fully satisfied by the code being generated (by LLVM), so I'll be taking another pass at this.

**Comment by wsengir** [comment]
Rebased! I had to disable an `int128` test for the C backend since `airWrapOp` does not support large integers yet.

**Comment by matu3ba** [comment]
I tested this with
```zig
    //buff = -3; // fails as expected
    //buff = -2;
    //buff = 1;
    //buff = 2; // fails as expected
    //_ = @intCast(i2, buff);

    //buff = -1; // fails as expected
    //buff = 0;
    buff = 4; // fails as expected
    _ = @intCast(u2, buff);
```

and it works as expected.

**Pull request merged**
