### PR TITLE
fetch: Keep .lazy = true

### PR DESCRIPTION
**Pull request by der-teufel-programming**
Solves #19725

### CODE REVIEW

**Comment by rupakhetibinit** [comment]
This seems like a wrong way to do it. If we currently have guarantees that `zig fetch --save <url>` only needs to change the url and the hash, I think a better implementation is to change the url and the hash and to not touch any other fields.

The way this PR is done, it only works in current context, what if in the future another field is introduced for another use-case. It just doesn't seem practical to keep changing it on every new field that is added increasing maintenance burden.

But that's just my 2 cents. Maybe some core team member can chime in and give feedback.

**Review by andrewrk — CHANGES_REQUESTED** [review]
I agree with @rupakhetibinit

**Comment by der-teufel-programming** [comment]
I've changed the implementation to now only touch the hash and location fields when updating dependencies

**Comment by andrewrk** [comment]
Thanks!

**Pull request merged**
