### PR TITLE
Add const variants to iterators in `std.enum`

### PR DESCRIPTION
**Pull request by fuzzypixelz**
Suppose I have a global `const` value `map` of type `EnumArray` and I wish to iterate over it without modifying `map`. Then the lack of a read-only iterator will force me to make `map` into a variable even though it doesn't need to be.

The `SegmentedList` structure uses the same naming conventions used here, i.e. `ConstIterator` and `constIterator`.

### CODE REVIEW

**Comment by Vexu** [comment]
Same goal as #12995, @SpexGuy which approach do you prefer?

**Comment by fuzzypixelz** [comment]
@Vexu @SpexGuy I don't think just slapping `const` on the argument pointer is a good idea.

What if I wish to `initUndefined` my enum array and iterate over key/value pairs to fill it in? I cannot do that if my enum array had to be `const`.

Looking at languages like Rust, there is a convention to use `iter` for read-only iterators and `iter_mut` for iterators of mutable references. Zig is not Rust. But I still believe that an `iterator` vs `constIterator` distinction is worth upholding as a convention, because the two serve very different use cases. So that a programmer can simply reach in for either by name.

I would go a bit further and say that any iterator which doesn't allow for mutating the collections through the values it returns should take `*const Self` and be dubbed `constIterator`. A good example of this is `bit_set.zig`, where all the `*BitSet` variants have the signature:

```zig
pub fn iterator(self: *const Self, comptime options: IteratorOptions) Iterator(options)
```

I would rename this to `constIterator`.

But we don't have to go bike-shedding just yet :^)

If the implementation is a bit too verbose for everyone here, I can rewrite it to emulate `SegmentedList`; i.e. share the common bits between `Iterator` and `ConstIterator`:

```zig
pub const Iterator = BaseIterator(*Self, *T);

pub const ConstIterator = BaseIterator(*const Self, *const T);

fn BaseIterator(comptime SelfType: type, comptime ElementPtr: type) type {
    // magic!
}
```

Cheers.

**Comment by tensorush** [comment]
@Vexu I don't think the approach in #12995 is applicable here, because indexed set iterator doesn't store any internal pointers as opposed to indexed array and indexed map.

**Comment by fuzzypixelz** [comment]
Not at all. I'll be taking a look back at it soon.

**Comment by andrewrk** [comment]
Closing abandoned draft.

**Pull request closed without merging**
