### PR TITLE
Proposal: Export stdin, stdout, stderr as streams directly from std.io

### PR DESCRIPTION
**Pull request by nmichaels**
I think it changes the hello world example for the better.

### CODE REVIEW

**Comment by deltaphc** [comment]
Chiming in with a little support.

While this PR doesn't enable anything new, it _does_ make the simple and obvious use case of using standard streams a lot more straightforward. Every other mainstream language has an easily accessible and obvious "print statement" of some kind, and I think it's quite reasonable to make it more accessible in Zig.

**Comment by FireFox317** [comment]
Maybe we should do `std.log.in/out/err()`, because with the current proposal (`std.in/out/err()`) these can mean any stream that is part of std, like a filesystem or network stream.

**Comment by ifreund** [comment]
Personally, I would for vote for `std.io.in`/`std.io.out`/`std.io.err`. This would make the namespacing a little more consistent while still being short and sweet.  `std.log` does not make sense as the namespace imo as it merely an interface and does not hold general io primitives. The only io it does is in the optional default implementation which can be overridden.

**Comment by nmichaels** [comment]
I did like std.in mostly because it's cute, but you're right; Other than being able to call it "stdandard in" it doesn't make a lot of sense to put it in the top level namespace.

**Comment by andrewrk** [comment]
Here's why this wasn't already done:

When using standard input and output, there are a few design decisions to keep in mind:
 * Use buffered input / output?
 * Protect with a mutex so that multiple threads can access the streams?

In C, these questions are both answered for you: yes, and yes.

In Zig it's more low level. The APIs are all there for you to use if you want them, but you have to build your own answers to these questions by chaining (or not) the respective APIs together. There are valid use cases for any combination of answers to these questions.

The problem here is that it starts making a more opinionated API that is simultaneously not necessarily the best default for people to naively follow (imagine some users' surprise when they find out `std.io.out()` is not safe to use from multiple threads, nor is it buffered) yet looks "official" and may lead the person into believing it does more than it does. Compared to a lower level interface, where it is clear you are getting a file, and converting that into a stream using the standard API, no special casing.

Further, if we were to provide a global API that did mutexes and buffering, it becomes a problem if you mix the global ones with locally created ones. And what if the user wanted to configure the buffer size? Forcing the user to make all the choices and take on the responsibility of brokering access to standard I/O means we keep the std lib both simple and powerful.

This is an area where I'd like to push back. I think the verbosity of Hello World, while problematic for "marketing", does teach beginners about the File and Writer APIs separately and teach them the important lesson that there is no magic, they will have to find or build the abstraction layers that they want and explicitly utilize them.

**Pull request closed without merging**
