### PR TITLE
Make clearer inline code blocks in language reference paragraphs

### LINKED ISSUE #9316: Language Reference: Improve legibility of inline code in paragraphs
### Issue
The language reference has inline code blocks in its paragraphs that are difficult to discern from normal text.

### Expectation
Increase legibility of code blocks within the language reference's paragraphs so that code can be discerned from description.

### PR DESCRIPTION
**Pull request by paulespinosa**
_**Please read later comments. There have been updates since this comment was made. This message is left to preserve the differences made during code review.**_

This commit makes the inline code blocks within paragraphs standout against the
descriptive text. The code blocks within tables are left un-styled.

The line-height of the paragraphs has been set to 1.7 based on recommendations
from MDN Web Docs and W3C. The value is unitless based on the recommendation.

The changes apply both normal and dark modes.

### Screenshots

pic-selected-210706-1629-09
pic-selected-210706-1629-40
pic-selected-210706-1630-08
pic-selected-210706-1630-22

Closes #9316, #6313

### CODE REVIEW

**Comment by dbandstra** [comment]
I appreciate your initiative to improve docs readability. Some personal thoughts:

- line-height 1.7 seems excessive, wouldn't 1.5 be enough?
- `ul` and `ol` should get the same line-height as `p`. Maybe exempt the sidebar (`#toc`) from this though.
- The inline code styles should also apply to `ul code` and `ol code`
- The inline code background color seems too dark in the light theme

 I feel that inline code and block code should use the same font-size (the default, not 12pt) and possibly even the same background and border. Here's a screenshot using #f8f8f8 (what block code currently uses) for inline code as well, and adding `border: 1px dotted silver` to both of them.

Here is a screenshot with my suggestions:

Screen Shot 2021-07-06 at 10 45 37 AM

These are just my own thoughts, keep in mind i'm just a random guy, not a member of Zig core team or anything.

**Comment by paulespinosa** [comment]
I have updated this pull request using the suggestions from @dbandstra with the addition of adding the same styling to the code blocks within tables.

Regarding the line-height, I set it to 1.5 which is the recommended minimum. I looked at other language references and have found values from 1.45 to 1.75. I just set to the minimum as suggested for now.
Line height examples:
* C# uses 1.6
* Rust uses 1.45
* MDN uses 1.75
* This GitHub comments section uses 1.5

### Screenshots
These screenshots are taken from the latest commit.
pic-selected-210707-1146-11
pic-selected-210707-1146-30
pic-selected-210707-1146-56
pic-selected-210707-1147-13
pic-selected-210707-1147-51
pic-selected-210707-1148-09

**Comment by dbandstra** [comment]
Thanks :)

Two comments:

* Dark mode still has light borders in the `pre` blocks. I think the borders should be darker (fainter), like they are for inline code.
* I don't think `p, ul, ol, :not(#toc)` is correct. Since `:not` is by itself, it's actually matching every element in the document other than the `toc` container div itself. I think what might make more sense is:

```css
body {
    line-height: 1.5;
}
#toc, pre > code {
    line-height: normal;
}
```

**Comment by paulespinosa** [comment]
@dbandstra would setting line-height in `#content` and reset it in `pre > code` have any negative side effects?

``` css
#contents {
  /* ... */
  line-height: 1.5;
}
pre > code {
 /* ... */
 line-height: normal;
```

**Comment by paulespinosa** [comment]
I went ahead and set the line height in `#contents` selector.

Regarding the dark mode preformatted code blocks border color, good catch @dbandstra. 

### Screenshots
Here are more screenshots from the latest commit where the line height is set for all of contents and the dark mode preformatted code block background color is updated.
pic-selected-210707-1422-02
pic-selected-210707-1423-52
pic-selected-210707-1424-15

**Comment by dbandstra** [comment]
> would setting line-height in #content and reset it in pre > code have any unwanted side effects?

Nope, that works too.

Thanks, that's all from me.

**Review by Vexu — APPROVED** [review]

**Pull request merged**
