### PR TITLE
Add `zig cc` support for LLVM flag `--no-undefined-version` follow up from #17326

### PR DESCRIPTION
**Pull request by behos**
Following up from this PR https://github.com/ziglang/zig/pull/17326 to unblock it by applying the formatting fix.

Happy to close this PR if the original one is updated of course :)

All credit goes to https://github.com/DhashS

### CODE REVIEW

**Comment by castholm** [comment]
@behos Sorry to tag you in multiple places but just so you don't miss it, I opened a PR with some fixes and additions to your fork.

https://github.com/DataDog/zig/pull/1

> - `main.zig` did not handle the option correctly, which meant that `zig build-lib --undefined-version ...` didn't actually work and instead printed an "unrecognized parameter" error message. The first commit fixes this.
> - The second commit exposes the option to the build system. (I'm working on a port of SDL3 to the zig build system which needs to pass this option in order to build successfully.)
>
> I've tested the changes locally (both the standard and `--no-` variants) and can confirm they work correctly now.

**Comment by behos** [comment]
The latest changes in the File struct broke this so I'll need to have another look on how to pass the new option again.

**Comment by behos** [comment]
@castholm Could you do another check for your changes? I had to do a merge and restructure the integration points a bit.

**Comment by castholm** [comment]
@behos I might be able to try in a bit, first I need to get my SDL project working again with the newest build system changes. Will report back.

**Pull request closed without merging**
