### PR TITLE
Docgen improve code readability

### PR DESCRIPTION
**Pull request by perillo**
Attempt to improve the readability and consistency of `docgen`.

### CODE REVIEW

**Comment by nektro** [comment]
do u have a before/after screenshot?

**Comment by perillo** [comment]
> do u have a before/after screenshot?

You can just read each commit diff.

Just in case there is misunderstanding, this PR does not improve the readability of the *Zig Language Reference*, but the readability of the `docgen` tool.

**Comment by andrewrk** [comment]
No thanks. The only actual thing this does is slightly increase the number of bytes users download from the langref.

**Comment by perillo** [comment]
@andrewrk, I added multiple commits so that do you can discard the ones you don't like.

If the problem is the increase size of langref, you can just remove 2e2c4cf (and probably also you can also a340d27).

However I think additional 8 bytes are a good price for consistency.

Thanks.

**Pull request closed without merging**
