### PR TITLE
STAGE1_SOURCES: In 0.7.x, leb128.zig is in std/debug

### PR DESCRIPTION
**Pull request by jedisct1**
Should fix the 0.7.x CI issue.

### CODE REVIEW

**Comment by kubkon** [comment]
Wait, has `leb128.zig` been moved? If so there's quite a few places that'll need updating.

**Comment by jedisct1** [comment]
It was moved in 48d60834fd61404ea009f7f970775f9c59de1240

**Comment by kubkon** [comment]
Huh, totally missed that one, thanks!

**Comment by jedisct1** [comment]
Looks like other files have been moved as well. Maintaining `ZIG_STAGE2_SOURCES` is going to be painful.

**Comment by jedisct1** [comment]
CI's green again!

**Comment by andrewrk** [comment]
Thanks @jedisct1!

**Pull request merged**
