### PR TITLE
stage1: add field access on opaque error

### LINKED ISSUE #7813: Assertion failed at ir.cpp:22760 in ir_analyze_container_member_access_inner
While trying to factor some comptime arguments into a struct for [cZPeg](https://github.com/spadix0/cZPeg), I ran into this:

```console
$ zig build test                               
All 25 tests passed.
Semantic Analysis [85/655] Assertion failed at /Users/runner/work/1/s/src/stage1/ir.cpp:22760 in ir_analyze_container_member_access_inner. This is a bug in the Zig compiler.The following command terminated unexpectedly:
/Users/spadix/zig-macos-x86_64-0.8.0-dev.1001+811833658/zig test /Users/spadix/proj/czpeg/src/czpeg/re.zig --cache-dir /Users/spadix/proj/czpeg/zig-cache --global-cache-dir /Users/spadix/.cache/zig --name test 
error: the following build command failed with exit code 1:
/Users/spadix/proj/czpeg/zig-cache/o/fcb79c9b92ca39c2295f175ae6ea2441/build /Users/spadix/zig-macos-x86_64-0.8.0-dev.1001+811833658/zig /Users/spadix/proj/czpeg /Users/spadix/proj/czpeg/zig-cache /Users/spadix/.cache/zig test
```

The code to reproduce is here:  https://github.com/spadix0/cZPeg/tree/zig_assert_ir_analyze_container
that may not compile even without the assertion, but all tests pass before the branch, so something in that (small) diff probably triggered the problem(?)

<details>
<summary>stack trace</summary>

```
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
  * frame #0: 0x00007fff736a133a libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fff7375de60 libsystem_pthread.dylib`pthread_kill + 430
    frame #2: 0x00007fff73628808 libsystem_c.dylib`abort + 120
    frame #3: 0x0000000100003866 zig`std.os.abort + 6
    frame #4: 0x00000001000048fe zig`std.debug.panicExtra + 910
    frame #5: 0x00000001000010d9 zig`std.builtin.default_panic + 25
    frame #6: 0x000000010000a32a zig`stage2_panic + 26
    frame #7: 0x00000001003684fc zig`zig_panic(char const*, ...) + 172
    frame #8: 0x00000001003f9c9c zig`ir_analyze_container_member_access_inner(IrAnalyze*, ZigType*, Buf*, IrInst*, IrInstGen*, IrInst*, ZigType*) + 828
    frame #9: 0x00000001003b5be3 zig`ir_analyze_instruction_base(IrAnalyze*, IrInstSrc*) + 66451
    frame #10: 0x00000001003a4a5b zig`ir_analyze(CodeGen*, IrExecutableSrc*, IrExecutableGen*, ZigType*, AstNode*, ZigValue*) + 1227
    frame #11: 0x00000001003a3201 zig`ir_eval_const_value(CodeGen*, Scope*, AstNode*, ZigValue*, unsigned long*, unsigned long*, ZigFn*, Buf*, AstNode*, Buf*, IrExecutableGen*, AstNode*, UndefAllowed) + 593
    frame #12: 0x00000001004007b5 zig`ir_analyze_fn_call(IrAnalyze*, IrInst*, ZigFn*, ZigType*, IrInstGen*, IrInstGen*, IrInst*, CallModifier, IrInstGen*, IrInst*, bool, IrInstGen**, unsigned long, IrInstGen*, ResultLoc*) + 5173
    frame #13: 0x00000001003ff341 zig`ir_analyze_fn_call_src(IrAnalyze*, IrInstSrcCall*, ZigFn*, ZigType*, IrInstGen*, IrInstGen*, IrInst*, CallModifier) + 401
    frame #14: 0x00000001003b1819 zig`ir_analyze_instruction_base(IrAnalyze*, IrInstSrc*) + 49097
    frame #15: 0x00000001003a4a5b zig`ir_analyze(CodeGen*, IrExecutableSrc*, IrExecutableGen*, ZigType*, AstNode*, ZigValue*) + 1227
    frame #16: 0x00000001003a3201 zig`ir_eval_const_value(CodeGen*, Scope*, AstNode*, ZigValue*, unsigned long*, unsigned long*, ZigFn*, Buf*, AstNode*, Buf*, IrExecutableGen*, AstNode*, UndefAllowed) + 593
    frame #17: 0x00000001004007b5 zig`ir_analyze_fn_call(IrAnalyze*, IrInst*, ZigFn*, ZigType*, IrInstGen*, IrInstGen*, IrInst*, CallModifier, IrInstGen*, IrInst*, bool, IrInstGen**, unsigned long, IrInstGen*, ResultLoc*) + 5173
    frame #18: 0x00000001003ff341 zig`ir_analyze_fn_call_src(IrAnalyze*, IrInstSrcCall*, ZigFn*, ZigType*, IrInstGen*, IrInstGen*, IrInst*, CallModifier) + 401
    frame #19: 0x00000001003b1819 zig`ir_analyze_instruction_base(IrAnalyze*, IrInstSrc*) + 49097
    frame #20: 0x00000001003a4a5b zig`ir_analyze(CodeGen*, IrExecutableSrc*, IrExecutableGen*, ZigType*, AstNode*, ZigValue*) + 1227
    frame #21: 0x00000001003a3201 zig`ir_eval_const_value(CodeGen*, Scope*, AstNode*, ZigValue*, unsigned long*, unsigned long*, ZigFn*, Buf*, AstNode*, Buf*, IrExecutableGen*, AstNode*, UndefAllowed) + 593
    frame #22: 0x00000001004007b5 zig`ir_analyze_fn_call(IrAnalyze*, IrInst*, ZigFn*, ZigType*, IrInstGen*, IrInstGen*, IrInst*, CallModifier, IrInstGen*, IrInst*, bool, IrInstGen**, unsigned long, IrInstGen*, ResultLoc*) + 5173
    frame #23: 0x00000001003ff341 zig`ir_analyze_fn_call_src(IrAnalyze*, IrInstSrcCall*, ZigFn*, ZigType*, IrInstGen*, IrInstGen*, IrInst*, CallModifier) + 401
    frame #24: 0x00000001003b1819 zig`ir_analyze_instruction_base(IrAnalyze*, IrInstSrc*) + 49097
    frame #25: 0x00000001003a4a5b zig`ir_analyze(CodeGen*, IrExecutableSrc*, IrExecutableGen*, ZigType*, AstNode*, ZigValue*) + 1227
    frame #26: 0x00000001003a3201 zig`ir_eval_const_value(CodeGen*, Scope*, AstNode*, ZigValue*, unsigned long*, unsigned long*, ZigFn*, Buf*, AstNode*, Buf*, IrExecutableGen*, AstNode*, UndefAllowed) + 593
    frame #27: 0x00000001004007b5 zig`ir_analyze_fn_call(IrAnalyze*, IrInst*, ZigFn*, ZigType*, IrInstGen*, IrInstGen*, IrInst*, CallModifier, IrInstGen*, IrInst*, bool, IrInstGen**, unsigned long, IrInstGen*, ResultLoc*) + 5173
    frame #28: 0x00000001003ff341 zig`ir_analyze_fn_call_src(IrAnalyze*, IrInstSrcCall*, ZigFn*, ZigType*, IrInstGen*, IrInstGen*, IrInst*, CallModifier) + 401
    frame #29: 0x00000001003b1819 zig`ir_analyze_instruction_base(IrAnalyze*, IrInstSrc*) + 49097
    frame #30: 0x00000001003a4a5b zig`ir_analyze(CodeGen*, IrExecutableSrc*, IrExecutableGen*, ZigType*, AstNode*, ZigValue*) + 1227
    frame #31: 0x00000001003a3201 zig`ir_eval_const_value(CodeGen*, Scope*, AstNode*, ZigValue*, unsigned long*, unsigned long*, ZigFn*, Buf*, AstNode*, Buf*, IrExecutableGen*, AstNode*, UndefAllowed) + 593
    frame #32: 0x00000001004007b5 zig`ir_analyze_fn_call(IrAnalyze*, IrInst*, ZigFn*, ZigType*, IrInstGen*, IrInstGen*, IrInst*, CallModifier, IrInstGen*, IrInst*, bool, IrInstGen**, unsigned long, IrInstGen*, ResultLoc*) + 5173
    frame #33: 0x00000001003ff341 zig`ir_analyze_fn_call_src(IrAnalyze*, IrInstSrcCall*, ZigFn*, ZigType*, IrInstGen*, IrInstGen*, IrInst*, CallModifier) + 401
    frame #34: 0x00000001003aed75 zig`ir_analyze_instruction_base(IrAnalyze*, IrInstSrc*) + 38181
    frame #35: 0x00000001003a4a5b zig`ir_analyze(CodeGen*, IrExecutableSrc*, IrExecutableGen*, ZigType*, AstNode*, ZigValue*) + 1227
    frame #36: 0x00000001003a3201 zig`ir_eval_const_value(CodeGen*, Scope*, AstNode*, ZigValue*, unsigned long*, unsigned long*, ZigFn*, Buf*, AstNode*, Buf*, IrExecutableGen*, AstNode*, UndefAllowed) + 593
    frame #37: 0x00000001004007b5 zig`ir_analyze_fn_call(IrAnalyze*, IrInst*, ZigFn*, ZigType*, IrInstGen*, IrInstGen*, IrInst*, CallModifier, IrInstGen*, IrInst*, bool, IrInstGen**, unsigned long, IrInstGen*, ResultLoc*) + 5173
    frame #38: 0x00000001003ff341 zig`ir_analyze_fn_call_src(IrAnalyze*, IrInstSrcCall*, ZigFn*, ZigType*, IrInstGen*, IrInstGen*, IrInst*, CallModifier) + 401
    frame #39: 0x00000001003b1819 zig`ir_analyze_instruction_base(IrAnalyze*, IrInstSrc*) + 49097
    frame #40: 0x00000001003a4a5b zig`ir_analyze(CodeGen*, IrExecutableSrc*, IrExecutableGen*, ZigType*, AstNode*, ZigValue*) + 1227
    frame #41: 0x00000001003a3201 zig`ir_eval_const_value(CodeGen*, Scope*, AstNode*, ZigValue*, unsigned long*, unsigned long*, ZigFn*, Buf*, AstNode*, Buf*, IrExecutableGen*, AstNode*, UndefAllowed) + 593
    frame #42: 0x00000001004007b5 zig`ir_analyze_fn_call(IrAnalyze*, IrInst*, ZigFn*, ZigType*, IrInstGen*, IrInstGen*, IrInst*, CallModifier, IrInstGen*, IrInst*, bool, IrInstGen**, unsigned long, IrInstGen*, ResultLoc*) + 5173
    frame #43: 0x00000001004005cc zig`ir_analyze_fn_call(IrAnalyze*, IrInst*, ZigFn*, ZigType*, IrInstGen*, IrInstGen*, IrInst*, CallModifier, IrInstGen*, IrInst*, bool, IrInstGen**, unsigned long, IrInstGen*, ResultLoc*) + 4684
    frame #44: 0x00000001003ff341 zig`ir_analyze_fn_call_src(IrAnalyze*, IrInstSrcCall*, ZigFn*, ZigType*, IrInstGen*, IrInstGen*, IrInst*, CallModifier) + 401
    frame #45: 0x00000001003b1819 zig`ir_analyze_instruction_base(IrAnalyze*, IrInstSrc*) + 49097
    frame #46: 0x00000001003a4a5b zig`ir_analyze(CodeGen*, IrExecutableSrc*, IrExecutableGen*, ZigType*, AstNode*, ZigValue*) + 1227
    frame #47: 0x000000010037d905 zig`analyze_fn_body(CodeGen*, ZigFn*) + 1269
    frame #48: 0x000000010037ef07 zig`semantic_analyze(CodeGen*) + 231
    frame #49: 0x000000010033c62f zig`codegen_build_object(CodeGen*) + 1439
    frame #50: 0x000000010033515e zig`zig_stage1_build_object + 2222
    frame #51: 0x00000001000dc8b0 zig`Compilation.performAllTheWork + 82544
    frame #52: 0x00000001000c1410 zig`Compilation.update + 1776
    frame #53: 0x0000000100089f4c zig`main.updateModule + 28
    frame #54: 0x000000010002cb2f zig`main.buildOutputType + 90319
    frame #55: 0x0000000100004a87 zig`main + 391
    frame #56: 0x00007fff73559cc9 libdyld.dylib`start + 1
```
</details>

### PR DESCRIPTION
**Pull request by mikdusan**
- prevents stage1 panic
- error "no field named '...' in '(anytype)' (opaque has no fields)"
- add test case

closes #7813

### CODE REVIEW

**Comment by LemonBoy** [comment]
I think the problem is a bit deeper than a missing error message.
I expect `@typeof` on a `anytype` field to return the type of its assigned value instead of `anytype`.

**Comment by mikdusan** [comment]
```zig
    pub const Folder = struct {
        /// initial value for accumulator.  one of:
        ///   * comptime initial value of type T
        ///   * fn(Parser)T called to produce initial value (may error)
        init: anytype = {},
```

what type should that be?

**Comment by LemonBoy** [comment]
> what do you expect @typeof() field init assigned {} ? I'm assuming you want void to come thru?

The same value returned by `@TypeOf({})`, `void` in this case.

**Comment by mikdusan** [comment]
@LemonBoy I put in a check and reachthru for the type behind anytype and it seems to be a little progress...
but it breaks down with things like this:

```zig
    comptime var box = Box{ .payload = Person{ .age = 42 }};
```

but this works:
```zig
    comptime var box = Box{ .payload = {}};
    comptime box.payload = true;
    comptime var tmp = Person{ .age = 42 };
    comptime box.payload = tmp;
```

any ideas? I'm not sure it's worth the effort to _really_ fix this in stage1?

**Comment by LemonBoy** [comment]
What's `Box`? And `Person`? What's the error? Do you have a self-contained test case?

**Comment by mikdusan** [comment]
#### `redux.zig`
```zig
// (desired) error: type 'void' does not support field access
test "case1" {
    comptime var data = Data{};
    _ = data.uber.just_a_field_name;
}

const Data = struct {
    uber: anytype = {},
};


// segfault - it gets past my patch because the context is not simple,
// - from init/rls context
// - if already init, same underlying type? that'll probably work
// - if already init, diff underlying type? replace?
test "case2" {
    comptime var box = Box{ .payload = Person{ .age = 42 }};
    comptime expect(box.payload.age == 42);
    comptime expect(@TypeOf(box.payload.age) == u64);
}

// passes
test "case3" {
    comptime var box = Box{ .payload = {}};
    comptime box.payload = true;
    comptime var tmp = Person{ .age = 42 };
    comptime box.payload = tmp;
}

// error: type '(anytype)' does not support struct initialization syntax
test "case4" {
    comptime var box = Box{ .payload = {}};
    comptime box.payload = true;
    comptime var tmp = Person{ .age = 42 };
    comptime box.payload = tmp;
    comptime box.payload = Person{ .age = 0 };
}

const Box = struct {
    payload: anytype,
};
const Person = struct {
    age: u64,
};
```

#### case1 error (good)
```
./redux.zig:17:18: error: type 'void' does not support field access
    _ = data.uber.just_a_field_name;
                 ^
```

#### case2 segfault
```
Assertion failed at ../src/stage1/ir.cpp:22760 in ir_analyze_container_member_access_inner. This is a bug in the Zig compiler.thread 2170131 panic:
/Users/mike/project/zig/work/anytype_field_ptr/src/main.zig:167:21: 0x10891c5a5 in main.mainArgs (zig1)
    const cmd = args[1];
                    ^
???:?:?: 0x10d8a783f in ??? (???)
???:?:?: 0x1093b454d in __ZL10zig_assertbPKciS0_ (???)
???:?:?: 0x1094212f7 in __ZL40ir_analyze_container_member_access_innerP9IrAnalyzeP7ZigTypeP3BufP6IrInstP9IrInstGenS6_S2_ (???)
???:?:?: 0x109420ab2 in __ZL30ir_analyze_container_field_ptrP9IrAnalyzeP3BufP6IrInstP9IrInstGenS4_P7ZigTypeb (???)
???:?:?: 0x1093ee8d9 in __ZL32ir_analyze_instruction_field_ptrP9IrAnalyzeP17IrInstSrcFieldPtr (???)
???:?:?: 0x1093b70fb in __ZL27ir_analyze_instruction_baseP9IrAnalyzeP9IrInstSrc (???)
???:?:?: 0x1093b60ff in __Z10ir_analyzeP7CodeGenP15IrExecutableSrcP15IrExecutableGenP7ZigTypeP7AstNodeP8ZigValue (???)
???:?:?: 0x109336e7e in __ZL13analyze_fn_irP7CodeGenP5ZigFnP7AstNode (???)
???:?:?: 0x109324a08 in __ZL15analyze_fn_bodyP7CodeGenP5ZigFn (???)
???:?:?: 0x109325a86 in __Z16semantic_analyzeP7CodeGen (???)
???:?:?: 0x1093646e2 in __ZL15gen_root_sourceP7CodeGen (???)
???:?:?: 0x10936317f in __Z20codegen_build_objectP7CodeGen (???)
???:?:?: 0x109470aa4 in _zig_stage1_build_object (???)
```

#### case4 error
```
./redux.zig:49:34: error: type '(anytype)' does not support struct initialization syntax
    comptime box.payload = Person{ .age = 0 };
                                 ^
```

**Comment by mikdusan** [comment]
It occurs to me that case4 error is existing behaviour and not effected by this PR. But if what that error says is true:
```
error: type '(anytype)' does not support struct initialization syntax
```

we can probably guard against that and emit the same error? Much simpler.

**Comment by mikdusan** [comment]
After working with `anytype` some more in an unrelated project I'm leaning towards the belief that it is like a container and can hold any type of value. When subjected to `@TypeOf` or `@typeInfo` then the underlying type is returned. This sounds reasonable and zig already does this.

But I do not think we should allow any behaviour-creep of the underlying type to come through unless `@as` or casting or _something_ is done with it. On the face of it, it should **not** act like its underlying type. It shouldn't coerce. It shouldn't allow field access if underlying is a struct, shouldn't allow union access, etc. Extra work should be required to get at underlying type.

The motivation for this PR was code that caused zig to segfault if attempting field-access on a field that was initialized `any: anytype = {},` . I fixed that with a simple error message in an early commit on this PR (ugh rebased and force-pushed and gone). But that's the way to go, imo.

**Comment by LemonBoy** [comment]
Something got lost in translation, what I said is that in the linked issue `folder.init` has a `TypeOf` of `type` while `ir_analyze_container_member_access_inner ` treats it as if it were an `anytype` value.

Is that expected or not, that was my relatively simple question.

**Comment by mikdusan** [comment]
I don't see any evidence that `@TypeOf(folder.init) == type` is incorrect. A simple trace shows a multitude of values that yield correct `@TypeOf(folder.init)` results varying from:

| MARKER0, void
| MARKER0, (null)
| MARKER0, (null)
| MARKER0, (null)
| MARKER0, void
| MARKER0, (null)
| MARKER0, void
| MARKER0, void
| MARKER0, (null)
| MARKER0, void
| MARKER0, void
| MARKER0, comptime_int
| MARKER0, void

It's only (well this is my assumption but given the above trace is compelling) when userland code assigns `folder.init = type` does `@TypeOf(folder.init)` (and typeinfo) report it as `type`. Which is correct. Given the recursive parsing nature of user code doing this, I'll leave finding that as an exercise for author.

and on that premise, there is no `@TypeOf()` issue on an opaque. My reduction doesn't show it and user case doesn't show it given the above.

**Comment by LemonBoy** [comment]
The `TypeOf` part is indeed correct, I took some time to debug that beast of a test case.
When you take `x.y` where `y` is an `anytype` field you get back a `*anytype` pointer, the effective field type comes into play iff you read/write from that.

```zig
const X = struct {
    x: anytype
};

comptime {
    @compileLog(@TypeOf((X{ .x = 3 }).x));  // comptime_int
    @compileLog(@TypeOf(&(X{ .x = 3 }).x)); // *const (anytype)
}
```

The patch makes sense if this is the expected behaviour wrt pointers to anytype fields.
Honestly I'd have expected the pointer to be `*const comptime_int`, generic code must now make some extra effort to recover the real field type.

**Comment by mikdusan** [comment]
I'm going to close this to unclutter the PR queue. Been side-tracked on other things and didn't anticipate this isn't quite as straight forward as initially thought. Maybe I'll get back to it later.

**Pull request closed without merging**
