### PR TITLE
Move std.testing.zig_exe_path into build options

### PR DESCRIPTION
**Pull request by SpexGuy**
This PR supercedes #10526

### CODE REVIEW

**Comment by andrewrk** [comment]
Is it required to use `--pkg-begin test_options test_options.zig --pkg-end` now in order to run the standard library tests?

**Comment by SpexGuy** [comment]
Unfortunately yes, there are a small number of tests that use it. (I think it's one in std.ChildProcess where it launches the compiler).  We could change these tests, or advise people to run std lib tests through `zig build` instead.

**Review by andrewrk — CHANGES_REQUESTED** [review]
* I don't want it to be necessary to use `--pkg-begin` / `--pkg-end` args to execute the standard library test suite.
 * Please have a look at 67d5bfefba48d28c02e2841f1a47a213d28d4693 and see if that changes anything

**Comment by SpexGuy** [comment]
Thanks, looks like 67d5bfe removed all those dependencies.  I've removed the test_options package from build.zig and the linux CI script, it is no longer needed.

**Pull request merged**
