### PR TITLE
ci: azure: split build-and-test step

### PR DESCRIPTION
**Pull request by hdorio**
Follow up of https://github.com/ziglang/zig/pull/10812
Trying to fix issues brought up in https://github.com/ziglang/zig/pull/10812#issuecomment-1034387507.

This PR do the following:

 - add `aws --acl public-read` to allow public access to `builds/` on S3.
 - use `git fetch --unshallow` like in the original script because the pipeline may sometimes use a shallow clone.
 - the first json file is now `windows-{branch}.json` instead of `windows-.json`.

> wrong file path, it should be something like x86_64-windows-0.10.0-dev.630+7c1061784.zip. In the cmake output I see -- Configuring zig version 0.10.0 which is wrong

This should be fixed now, my [pipeline](https://dev.azure.com/hdorio/ziglang/_build/results?buildId=128&view=logs&j=3e8797c7-5b0a-5f2c-07a4-1bc5e60a122e&t=1fd55f13-a0e6-5b4d-f45a-00c805480cb1&l=35) shows `-- Configuring zig version 0.10.0-dev.5531+90c36e1fd`

> didn't get set with the public option:
> $ curl -I http://ziglang.org.s3.amazonaws.com/builds/zig-windows-x86_64-0.10.0.zip
> HTTP/1.1 403 Forbidden

This is what my pipeline uploaded on my S3 bucket (ziglang-test.org)

s3-bucket-zilang-test org

```
$ curl -I http://ziglang-test.org.s3.amazonaws.com/builds/zig-windows-x86_64-0.10.0-dev.5531%2B90c36e1fd.zip
HTTP/1.1 200 OK
x-amz-id-2: M2Nb6+QvIs5nznn3Ifkl9VBbfemK+kKwx9AIqBR6qNa1WlWa+MM7m4rjEXuHxSS3XMzKnwWQhLM=
x-amz-request-id: HMCTMBKR2TBRJ7JV
Date: Tue, 15 Feb 2022 21:37:59 GMT
Last-Modified: Tue, 15 Feb 2022 17:47:31 GMT
ETag: "417f942b214986894df3e75a07177ae8-8"
Cache-Control: public, max-age=31536000, immutable
Accept-Ranges: bytes
Content-Type: application/x-zip-compressed
Server: AmazonS3
Content-Length: 64029426
```

```
$ curl -I http://ziglang-test.org.s3.amazonaws.com/builds/x86_64-windows-0.10.0-dev.5531%2B90c36e1fd.json
HTTP/1.1 200 OK
x-amz-id-2: Yfe8c+Vrlq1ITAX4gvfpewsmsLHXgcoxk0W2PPgP/19Q9gVBrTApeFKv8eXtzox+p/Hgu+Tm40k=
x-amz-request-id: 47V904M6B3N0NC1P
Date: Tue, 15 Feb 2022 21:45:14 GMT
Last-Modified: Tue, 15 Feb 2022 17:47:43 GMT
ETag: "3ab6f878c55ef5233f7256cfc8d7bb0f"
Accept-Ranges: bytes
Content-Type: application/json
Server: AmazonS3
Content-Length: 165
```
Note that the header `x-amz-meta-s3cmd-attrs` is not set.

```
$ curl -I http://ziglang-test.org.s3.amazonaws.com/builds/windows-master.json
HTTP/1.1 200 OK
x-amz-id-2: n8YrIcdO7O6cKKOA+xAPVWzpYChvVGmA0iwqxw+G3eyCpxxkcg2Ol2+U2Aqe95dPLdDvN9beIj4=
x-amz-request-id: WXQVQPZC90ND7887
Date: Tue, 15 Feb 2022 21:42:26 GMT
Last-Modified: Tue, 15 Feb 2022 17:47:41 GMT
ETag: "3ab6f878c55ef5233f7256cfc8d7bb0f"
Cache-Control: max-age=0, must-revalidate
Accept-Ranges: bytes
Content-Type: application/json
Server: AmazonS3
Content-Length: 165
```
Note that `windows-.json` is now named `windows-master.json` and that the header `x-amz-meta-s3cmd-attrs` is not set.

> appears to be missing the very important cache-control headers

Forbidden requests don't have cache control headers. Adding the `--acl public-read` should fix the issue, `curl` displays `Cache-Control: public, max-age=31536000, immutable` on my S3 bucket ziglang-test.org for "zig-windows-x86_64-0.10.0-dev.5531+90c36e1fd.zip".

---

I can't fully test the "OnMasterSuccess" pipeline step, I let you tell me if everything looks okay:

```
$cat req.json
{
  "manifest": "image: alpine/latest\npackages:\n  - py3-pip\n  - curl\n  - jq\n  - xz\nsecrets:\n  - 51bfddf5-86a6-4e01-8576-358c72a4a0a4\n  - 44e2bd57-1d07-42bf-925e-22a36119041d\nsources:\n  - [https://github.com/ziglang/zig\ntasks:\n](https://github.com/ziglang/zig/ntasks:/n)  - build: cd zig && ./ci/srht/update_download_page 0.10.0-dev.5531+90c36e1fd\n"
}
```
```
curl -v -H Authorization:token fake-random-oauth-token-hKH_xKrMxXu91pE10xfQiokGprRKApTM3HRhTff7U -H Content-Type:application/json -X POST -d @- https://builds.hut.lavatech.top/api/jobs
```
My test pipeline run is public [here](https://dev.azure.com/hdorio/ziglang/_build/results?buildId=128&view=logs&j=66c508b3-22d8-5694-7d22-f3942fcb43f0&t=8bc79083-8da2-58cd-f841-96932ddfe0fe&l=1)

### CODE REVIEW

**Comment by hdorio** [comment]
@andrewrk can you give this another shot and tell me if you see any issue for the upload portion of the CI pipeline?

**Comment by andrewrk** [comment]
Yep I'll try to get to this at some point this week. Thanks!

**Comment by hdorio** [comment]
@andrewrk I saw the work you have done on your branch `ci-windows-zig-cc` and used that in my [pipepline](https://dev.azure.com/hdorio/ziglang/_build/results?buildId=139&view=results) with [7670e0de](https://github.com/hdorio/zig/commit/7670e0da4387d8678b9b71b4444a58fe4ae3b36) on my fork. Do you want me to update this pull request to use `zig` instead of `cmake`?

Note that my tests changed the content of `windows-master.json` and `macos-.json` on my S3 bucket.

**Comment by andrewrk** [comment]
I was just about to drop by here and request this. Would you mind rebasing this on top of `ci-windows-zig-cc`? I have finally got it passing.

The important change is using `zig build` instead of `cmake` and `msvc`. Together with your changes here, this means we will not rely on MSVC, cmake, or MSYS!

I plan to clean up the branch quite a bit and then merge to master today. You might benefit from waiting until then and rebasing against master directly.

**Comment by hdorio** [comment]
> Can you clarify what you mean by this? I don't quite understand what you are saying.

The content used to be about version `5531+90c36e1fd` but after the run of my pipeline with `zig` instead of `msvc`  the content is about version `5533+7670e0da4`

**Comment by andrewrk** [comment]
That seems normal right? That just means there are 2 more commits in the branch.

**Comment by hdorio** [comment]
> That seems normal right? That just means there are 2 more commits in the branch.

Yes, it's normal.

> Would you mind rebasing this on top of ci-windows-zig-cc?

I don't mind but maybe I should wait for ci-windows-zig-cc to be merged into master.
I don't understand why BuildMacOS, BuildMacOS_arm64, OnMasterSuccess are no longer needed.

**Comment by hdorio** [comment]
> That is one of the cleanups I mentioned that I will be doing today.

Sorry, I didn't get that "cleanups" could mean re-adding those steps.
I'll wait for the merge on master and I'll rebase against master directly, like you said.

**Comment by andrewrk** [comment]
Here's the cleaned up PR: #10907

**Comment by andrewrk** [comment]
Thank you for the follow-up!

**Comment by andrewrk** [comment]
Looks like this was never working correctly:  #12380

**Pull request merged**
