### PR TITLE
[WIP] Better error diagnostics from json parsing

### LINKED ISSUE #16936: Better error logging for std.json panics at runtime
### Zig Version

0.11.0

### Steps to Reproduce and Observed Output

Usually when std.json fails to parse some json data, it panics and produces an error log something like this:
```sh
error: UnknownField
/usr/local/lib/zig/std/json/static.zig:371:25: 0x1061e741c in innerParse__anon_11603 (dev)
                        return error.UnknownField;
                        ^
/usr/local/lib/zig/std/json/static.zig:467:64: 0x1061d3744 in innerParse__anon_11227 (dev)
                                arraylist.appendAssumeCapacity(try innerParse(ptrInfo.child, allocator, source, options));
                                                               ^
/usr/local/lib/zig/std/json/static.zig:140:19: 0x1061b5a35 in parseFromTokenSourceLeaky__anon_10125 (dev)
    const value = try innerParse(T, allocator, scanner_or_reader, resolved_options);
                  ^
/usr/local/lib/zig/std/json/static.zig:107:20: 0x10618e04d in parseFromTokenSource__anon_7661 (dev)
    parsed.value = try parseFromTokenSourceLeaky(T, parsed.arena.allocator(), scanner_or_reader, options);
                   ^
/usr/local/lib/zig/std/json/static.zig:73:5: 0x106187a2d in parseFromSlice__anon_6948 (dev)
    return parseFromTokenSource(T, allocator, &scanner, options);
    ^
/Users/Robert/zig/dev/src/tiles.zig:35:18: 0x106186e3e in loadTiles (dev)
    const data = try json.parseFromSlice([]TileRecord, a, string, .{});
                 ^
/Users/Robert/zig/dev/src/state.zig:21:22: 0x10618815e in init (dev)
            .tiles = try tile.loadTiles(a, textures),
                     ^
```
or
```
error: UnexpectedToken
etc...
```
This is not helpful at all in debugging which part of the json failed to parse and why.

### Expected Output

It would be great if std.json would log the line of json it failed to parse, and why it couldn't be parsed into the given struct

For example
```sh
ERROR: failed to parse json string
   {"amount": 1.10, "name": "foo"}
into 
  struct {amount: u32, name: []u8,};
  
Expected identifier "amount" to hold u32, found f32.

#etc...
```

### PR DESCRIPTION
**Pull request by thejoshwolfe**
Closes #16936.

The idea here is that you can print the diagnostics to a stream, such as stderr. Something like this:

```
<json>:6:13: Overflow
   "a": 1123
        ^^^^
  in u8
  in test.MyStruct.a
  in test.MyStruct
```

I would also like to make it easier to provide diagnostics in the `options` parameters to many of the higher level APIs instead of needing to construct your own source object.

The memory management with this gets pretty tricky. The arena allocator for deserializing json into a struct is inappropriate to use, because it gets destroyed before the diagnostics get read sometimes. My current strategy is to use no allocator, but that's pretty limiting.

* [x] source snippet
* [x] messages for `parseFromTokenSource` errors
* [ ] messages for `parseFromValue` errors
* [x] context lines
* [ ] re-evaluate decision to not use an allocator. Currently requiring all error messages be comptime strings means we're pretty limited in what we can complain about.
* [ ] fix off-by-1 error in line snippet printing
* [ ] point the line snippet cursor back one token when it's not a syntax error.
* [ ] what do we do when the line snippet spans input slices in a really awkward way?
* [ ] change all `json/static.zig` errors to just `error.JsonDeserializationTypeError` instead of the current `error.{UnexpectedToken, InvalidNumber, Overflow, InvalidEnumTag, DuplicateField, UnknownField, MissingField, LengthMismatch}`. The detailed string message will tell you what the specific problem is instead of the integer error code.
* [ ] tests

I'm open to suggestions on how to go about this PR if anyone has opinions. i'm particularly dissatisfied with the allocator situation.

### CODE REVIEW

**Comment by thejoshwolfe** [comment]
there's no label to disable the CI checks, is there? this PR is not ready, and it's a waste of compute resources to run the CI checks already.

**Comment by nektro** [comment]
there is not sadly, even when draft :(

**Comment by andrewrk** [comment]
if it's not ready for review, why bother opening it? I would disable github's draft button if I could. I have no interest in WIP PRs.

**Comment by thejoshwolfe** [comment]
> if it's not ready for review, why bother opening it? I would disable github's draft button if I could. I have no interest in WIP PRs.

Ah, ok. I originally misread your comment on #16936 "here is the issue to track" as "is there an issue to track", so i thought someone was interested in looking at this. i'll just close this until it's in a better spot.

**Pull request closed without merging**
