### PR TITLE
Improved IO API around seeking

### PR DESCRIPTION
**Pull request by igor84**
This is a rebase of #11936 pull request to the latest master.

The pull request is a bit bigger cause I had to do everything in order to make sure that everything can be done as I imagined.

This pull requests removes `SeekableStream` as a separate entity and instead adds a `SeekableReader` and a `SeekableWriter` next to regular `Reader` and `Writer`. That allowed me to also solve the following issues:

1. There was no correct way to use `BufferedReader` with seeking. Now `BufferedReader` adds its own seek methods if the reader it is wrapping is a `SeekableReader`.
2. There was no way to make `StreamSource` wrap a `File` with a `BufferedReader` and still provide seeking. Instead of storing `File` it now stores either `File.SeekableReader` or `File.SeekableWriter`. That way it provides buffering and seeking but can not be used for both writing to a file and reading from it at the same time.

### CODE REVIEW

**Comment by andrewrk** [comment]
How would `WriterMethods` interact with this code?

https://github.com/ziglang/zig/blob/dc1f50e505105cabe1ed53951ca612778d6019ee/lib/std/crypto/tls/Client.zig#L785-L1140

**Comment by igor84** [comment]
Let me make sure I understand the question first. Currently `Client` does not provide `reader()` method that returns `std.io.Reader` at all and just provides some "raw" read methods itself. The question is how could we use `ReaderMethods` to add a `reader()` method to the Client that would return `std.io.Reader`?

If that is the question the easiest thing we can do is define something like this:

```rs
pub const ClientStreamContext = struct {
    client: *Client,
    stream: anytype
};

pub const Reader = std.io.Reader(ClientStreamContext, ReadError, read);

pub fn reader(c: *Client, stream: anytype): Reader {
    return .{ .context = .{ .c = c, .stream = stream } };
}
```

Additionally `read` method signature should be changed to `read(c: ClientStreamContext, buffer: []u8) !usize`.

The only problem I see here is that `ReadError` above needs to actually be `stream.ReadError` which we don't have at the `Client` struct level. I don't understand why is `Client` designed that way. Based on my quick overview of the that struct I don't see why it wouldn't be considered a wrapper around `stream` and thus save it in a private field in its `init` method.

If that were so `Client` could actually be a func that receives `comptime StreamType: type` and return a Client struct that now has access to StreamType.ReadError similar how `BufferedReader` receives underlying `ReaderType` that it wraps.

Either way I don't see a need to add `ReaderMethods` directly to the Client, but only through a `Reader`.

Please let me know if I misunderstood something?

Please let me know if I misunderstood the question or

**Comment by andrewrk** [comment]
I recognize this is the second time that you have made these changes, only to have them sit unreviewed for a very long time.

The reason I have bawked at this changeset both times is that I do not like the mixin strategy with `usingnamespace`. In fact I intend to fully eliminate all uses of `usingnamespace` in the standard library.

Is `usingnamespace` and `@hasDecl` a required component of this improvement?

**Comment by igor84** [comment]
Yes, this solution is based on using those constructs.

**Comment by andrewrk** [comment]
Again I apologize for how much effort you have put into this @igor84, only to have it sit for a long time unanswered. However, I am rejecting this on the basis of `usingnamespace` usage. That keyword is essentially forbidden in the standard library. And yes, I do plan to eradicate the remaining uses, of which there are currently 27.

I also recognize that there is an ongoing problem with interfaces in Zig, especially with regards to seekability, writer, and reader. I'm not completely sure what the road ahead looks like, but with this, we at least eliminate one possibility.

**Pull request closed without merging**
