### PR TITLE
edwards25519 - skip useless operations and duplicate lookup table

### PR DESCRIPTION
**Pull request by jedisct1**
Just some trivial changes; no functional changes.

Skip useless null additions and multiplications and comptime the basepoint multiples only once.

(maybe worth getting in 0.7.1?)

### CODE REVIEW

**Comment by andrewrk** [comment]
mind doing the rebase since #7016 was merged?

**Comment by jedisct1** [comment]
That one was based on 0.7.x (or `master` before the other change). It is not required any more on `master`.

**Comment by andrewrk** [comment]
Ah! You can actually open a PR against the 0.7.x branch if you want - it's supported by GitHub's UI. Up to you.

**Comment by jedisct1** [comment]
Done!

**Pull request merged**
