### PR TITLE
Fix major grammar issue in Array List

### PR DESCRIPTION
**Pull request by windows-fryer**
This could end the world.

#IContributed

### CODE REVIEW

**Comment by kaorlol** [comment]
Thank you for your keen vision Liga.

**Comment by Lightningrod6** [comment]
What in the world is a zig?

**Comment by SeanTheGleaming** [comment]
I'm glad we caught this before the world collapsed around us

**Comment by andrewrk** [comment]
No grammar fixes for first-time contributors please. Also you missed the other `addOne` function from the same file. This is a waste of human and CI resources. Typos, grammar, etc will be solved in big batches by someone more thorough.

**Pull request closed without merging**
