### PR TITLE
std.Build: Add methods for creating modules from a TranslateC object.

### PR DESCRIPTION
**Pull request by gauzey**
I wasn't sure whether to expose the dependencies as a parameter, or create an `AddModuleOptions` struct parameter. I went with the former since if I made such a struct it would only contain the dependencies as a member anyway, and I'm not sure what the likelihood is that the struct would ever contain more than that.

Lines 85-88 in `createModule` essentially inlines `moduleDependenciesToArrayHashMap`, which is used in the `createModule` implementation in Build.zig, but is private so I could not reuse it. So a bit of code duplication there. But, I wasn't sure if there was a common place to move that to, and it is a fairly simple function so didn't feel too wrong.

### CODE REVIEW

**Comment by andrewrk** [comment]
Thanks!

Hmm, I don't think it's actually possible for translated C code to import any module, so there is no need for a dependencies parameter. Other than that, if this solves your use case then I think this is good to go.

**Comment by gauzey** [comment]
Hah, had not even considered that. I'll update it with the dependencies parm removed.

**Review by andrewrk — APPROVED** [review]
I noticed another issue, but it actually affects all the methods in this file, so it can be solved separately. The issue is that using `self.step.owner` will add it to the same package as the one that created the TranslateC step. However, in the case that the TranslateC step exists as a dependency, that may be the wrong Build instance.

It's easier to understand this with a Run step. Consider a use case where a dependency provides an tool via a Compile step, and then your application depends on this package, and wants to run the tool. Well, you want that Run step to run in the context of the application, not the dependency!

Anyway, thanks for this patch, I will now mark it as auto-merge when the tests pass, and this other issue can be solved later.

**Comment by gauzey** [comment]
I think I see what you mean. Yeah, that didn't happen to hit me in my use case, since I'm creating the TranslateC in the same package the module is used in. Glad the issue was brought to light.

Thanks for the merge!

**Pull request merged**
