### PR TITLE
Add `@inComptime` builtin

### PR DESCRIPTION
**Pull request by mlugg**
Resolves: #868

I'm aware this proposal isn't yet accepted, but in a discussion on Discord, Andrew seemed very open to it (in fact thought it had already been accepted). I figured I'd put this PR together in the hopes that it's accepted.

I picked `@inComptime` for the builtin's name because `@areWeInComptime` felt needlessly wordy but `@isComptime` sounds (at least to me) like it's trying to check whether a value is comptime-known or something to that effect. `@inComptime` felt like the best way of expressing what the builtin actually does. It can be changed if others disagree.

### CODE REVIEW

**Comment by mlugg** [comment]
I managed to break aarch64 by emitting better code :) #15355 will disable the self-hosted aarch64 backend for now anyway, so I'm just going to wait for that.

**Comment by andrewrk** [comment]
Hmm I'm a bit confused why the zig.wasm update is needed. Did the CI fail before that?

**Comment by mlugg** [comment]
The compiler uses `Sha256` from `std`, which (now) uses `@inComptime` (previously used a `inline fn isComptime`)

**Comment by mlugg** [comment]
Okay, it remains necessary, because AstGen is resposible for validating builtin names so we get a compile error for the `Sha256` usage even if it's unreferenced. (I know there are security concerns with external contributors doing zig1 updates, so feel free to recreate that commit yourself if needed)

**Comment by andrewrk** [comment]
Thanks for the explanation! It makes sense :+1:

**Pull request merged**
