### PR TITLE
Fixes fmt padding for some types

### LINKED ISSUE #5333: std.fmt.format parameters do not work with strings
The following example does not work as expected:

```zig
std.debug.warn("{:18} width\n", .{"Minimum"});
std.debug.warn("{:=>24}\n", .{"Filled"});
std.debug.warn("{:^24}\n", .{"Centered"});
```

**Expected**:

```
Minimum            width
==================Filled
        Centered
```

**Actual**:

```
Minimum width
Filled
Centered
```

(The expected output is generated from the identical format strings in Python 3.)

Integers seem to work just fine however:

```zig
std.debug.warn("{:0>8}\n", .{42});
```

results in

```
00000042
```

I am using zig 0.6.0 installed via Homebrew on macOS.

### PR DESCRIPTION
**Pull request by data-man**
Closes #5333.

However, for many types, more work is required.

### CODE REVIEW

**Comment by LemonBoy** [comment]
Since there's no guarantee the string literals (the format specifier and the input strings) are encoded as utf8 the whole padding thing becomes a bit complex. However treating everything as ASCII encoded as you're doing is not a good solution.

**Comment by data-man** [comment]
I'm trying to improve current behavior and fix a specific issue.

> However treating everything as ASCII encoded as you're doing is not a good solution.

Which language calculates codepoints' widths in fmt?

**Comment by LemonBoy** [comment]
> Which language calculates codepoints' widths in fmt?

I never mentioned rune (or codepoint) cell widths should be taken into account as that mostly concerns terminals. What I'm saying is, what's the measurement unit of the maximum field width? Bytes? Runes?

A practical implementation such as the one used by Python 3 uses the latter:

```python
s = 'Résumé'
len(s) # 6 runes
len(s.encode('utf-8')) # 8 bytes
'{0:>10}'.format(s) # Correctly inserts 4 spaces
```

> I'm trying to improve current behavior and fix a specific issue.

The devil is in the detail.

**Comment by andrewrk** [comment]
I think this patch is an improvement since it fixes broken behavior.

The question of right-aligning strings is a separate issue, which I do think is important to consider, but this PR does not need to be the one to do it

**Pull request merged**
