### PR TITLE
std/mem: enhance len to accept sentinel-terminated array or slice

### PR DESCRIPTION
**Pull request by Pyrolistical**
There are 3 types that can be sentinel-terminated:
1. pointers
2. arrays
3. slices

`std.mem.len` only supported pointers. This PR adds support for arrays and slices.

Before this PR one had cast or use sliceTo:
```zig
const array: [10:0]u8 = ...;
const slice: [:0]u8 = ...;

// BEFORE
std.mem.len(@as([*:0]const u16, &array)
std.mem.sliceTo(&array, 0).len

std.mem.len(slice.ptr)
std.mem.sliceTo(slice, 0).len

// AFTER
std.mem.len(array)
std.mem.len(slice)
```

This does make `len` misleading and perhaps a better name would be `lenSentinel`

### CODE REVIEW

**Comment by rohlem** [comment]
The semantics provided here don't exactly align with the meaning of the types in the language:

- For `[*:s]T`, there is no additional length information, so the first occurrence of the sentinel determines its length, which is what the `std.mem.len` function seems to be intended for.
- `[n:s]T` on the other hand has a fixed length; the sentinel provides the information that after the `n` elements, an additional sentinel element of value `s` is provided (or rather should be, I don't think the compiler adds checks for this even in debug mode for now).
   However, the sentinel can also appear within the `n` elements. For example, `"a\0b"` is a valid literal of type `*const [3:0]u8` where `"a\0b"[1] == 0`.
- Similarly `[:s]T` has `.len` elements followed by a sentinel element, but the same sentinel may also appear within the elements.

To me it looks like currently users are supposed to only use `span` and `len` with `[*:s]T`, and for `[n:s]T` and `[:s]T` instead use `sliceTo` (which uses the length information as additional max-length fallback for safety).
I'm not sure whether extending the semantics of `std.mem.len` to allow less-safe usage is an improvement (just my 2c though, ultimately up to maintainers to decide).

**Comment by Pyrolistical** [comment]
Good point @rohlem. I added sliceTo examples to the description.

**Comment by copygirl** [comment]
Doesn't `std.mem.indexOf` fill this role?

**Comment by Pyrolistical** [comment]
@ifreund the bad functionality was removed. This PR only accepts sentinel terminated arrays and slices. I would also be happy to see `len` deleted all together. It's just in an awkward middle ground right now

**Comment by ifreund** [comment]
> @ifreund the bad functionality was removed. This PR only accepts sentinel terminated arrays and slices. I would also be happy to see `len` deleted all together. It's just in an awkward middle ground right now

Both sentinel terminated arrays and slices may have a sentinel somewhere in the middle of the array in addition to the sentinel at the end. That is, it's not guaranteed that `foo.len == mem.sliceTo(foo, sentinel)`.

I personally would be fine with removing `std.mem.len()`, I only see a single usage in the entire `ziglang/zig` repo which could trivially be rewritten to `mem.sliceTo()`.

**Pull request closed without merging**
