### PR TITLE
math: implement absInt for integer vectors

### PR DESCRIPTION
**Pull request by jordanlewis**
This commit adds support to absInt for integer vectors.

### CODE REVIEW

**Comment by travisstaloch** [comment]
would it be preferrable to implement this as?
```zig
return x * sign(x);
```

not sure about performance but seems like a maintainability win since `sign()` supports vector types.

**Comment by jordanlewis** [comment]
I think this version would be at least a little more performant as it has to do fewer vector ops. And I'm not sure how much of a maintainability win your suggestion really is - is this function liable to change?

**Comment by travisstaloch** [comment]
good call on fewer vector ops. i had to look for myself: https://godbolt.org/z/qPjMz34of

not sure how much `math.sign()` could change. believe its less than a year old (i added it) and the only change its had that i know of was adding float vector support recently.

**Comment by InKryption** [comment]
Might be worth making a similar change to `absCast`. Changes would probably be something like adding
```zig
    .Vector => |vec_info| @Vector(vec_info.len, std.meta.Int(.unsigned, @bitSizeOf(vec_info.child))),
```
to the return type switch, and
```zig
        .Vector => |vec_info| {
            const int_info = @typeInfo(vec_info.child).Int;
            if (int_info.signedness == .unsigned) return x;

            const Uint = std.meta.Int(.unsigned, int_info.bits);
            const Uvec = @Vector(vec_info.len, Uint);
            const a = @bitCast(Uvec, x);
            const b = ~@bitCast(Uvec, x -% @splat(vec_info.len, @as(vec_info.child, 1)));

            const pred = x > @splat(vec_info.len, @as(vec_info.child, 0));
            return @select(Uint, pred, a, b);
        },
```
to the function body switch.

**Comment by jordanlewis** [comment]
I agree, it would be nice to make this change - I can do it it a separate PR.

**Pull request merged**
