### PR TITLE
stage2: handle name-qualified imports in sema, add a zerofill sections workaround to incremental macho

### LINKED ISSUE #10765: Linking errors when running behavior tests on stage2 macOS x86_64
### Zig Version

0.10.0-dev.520+5cf918143

### Steps to Reproduce

1. Clone Zig repo
2. Build the stage1 compiler:
```
cd zig
mkdir build 
cd build
cmake .. -DCMAKE_PREFIX_PATH=$(brew --prefix llvm) -DZIG_STATIC_LLVM=on
make install -j8
```
3. Build the stage2 compiler:
```
./build/zig build --prefix $(pwd)/stage2 -Denable-llvm -Dconfig_h=build/config.h
```
4. Run behavior tests:
```
./stage2/bin/zig test test/behavior/math.zig -fLLVM --verbose-link --verbose-cimport --debug-compile-errors
```

### System information

macOS version: Catalina 10.15.7 (19H1713)

```
$ xcrun --sdk macosx --show-sdk-path
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk

$ xcrun --sdk macosx --show-sdk-version
11.1

$ xcode-select -p
/Applications/Xcode.app/Contents/Developer

$ /usr/local/opt/llvm/bin/llvm-config --system-paths
<EMPTY>

$ xcodebuild -version
Xcode 12.4
Build version 12D4e

$ pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
package-id: com.apple.pkg.CLTools_Executables
version: 12.4.0.0.1.1610135815
volume: /
location: /
install-time: 1643724396
groups: com.apple.FindSystemFiles.pkg-group
```

### Expected Behavior

Behavior tests running successfully.

### Actual Behavior

Output:

```
warning(link): library not found for '-lc'
warning(link): Library search paths:
zig ld -dynamic test/behavior/zig-cache/o/783d5453cbac6c1d886fd23c0253781d/test.o /Users/<USER>/.cache/zig/o/6038e68b06b36a4a81a14614da4b49f6/libcompiler_rt.a -o test/behavior/zig-cache/o/783d5453cbac6c1d886fd23c0253781d/test -lSystem -lc -lc
error: LibraryNotFound
/Users/<USER>/tmp/zig/src/link/tapi/yaml.zig:59:28: 0x1071e5a83 in link.tapi.yaml.Value.asList (zig)
        if (self != .list) return error.TypeMismatch;
                           ^
/Users/<USER>/tmp/zig/src/link/tapi/yaml.zig:59:28: 0x1071e5a83 in link.tapi.yaml.Value.asList (zig)
        if (self != .list) return error.TypeMismatch;

[ ... See "Details" below for full output ... ]
```

For some reason, `-lc` is passed twice on the command line, and it is still not found.

<details>

```
warning(link): library not found for '-lc'
warning(link): Library search paths:
zig ld -dynamic test/behavior/zig-cache/o/783d5453cbac6c1d886fd23c0253781d/test.o /Users/<USER>/.cache/zig/o/6038e68b06b36a4a81a14614da4b49f6/libcompiler_rt.a -o test/behavior/zig-cache/o/783d5453cbac6c1d886fd23c0253781d/test -lSystem -lc -lc
error: LibraryNotFound
/Users/<USER>/tmp/zig/src/link/tapi/yaml.zig:59:28: 0x1071e5a83 in link.tapi.yaml.Value.asList (zig)
        if (self != .list) return error.TypeMismatch;
                           ^
/Users/<USER>/tmp/zig/src/link/tapi/yaml.zig:59:28: 0x1071e5a83 in link.tapi.yaml.Value.asList (zig)
        if (self != .list) return error.TypeMismatch;
                           ^
/Users/<USER>/tmp/zig/src/link/tapi/yaml.zig:59:28: 0x1071e5a83 in link.tapi.yaml.Value.asList (zig)
        if (self != .list) return error.TypeMismatch;
                           ^
/Users/<USER>/tmp/zig/src/link/tapi/yaml.zig:59:28: 0x1071e5a83 in link.tapi.yaml.Value.asList (zig)
        if (self != .list) return error.TypeMismatch;
                           ^
/Users/<USER>/tmp/zig/src/link/tapi/yaml.zig:59:28: 0x1071e5a83 in link.tapi.yaml.Value.asList (zig)
        if (self != .list) return error.TypeMismatch;
                           ^
/Users/<USER>/tmp/zig/src/link/tapi/yaml.zig:59:28: 0x1071e5a83 in link.tapi.yaml.Value.asList (zig)
        if (self != .list) return error.TypeMismatch;
                           ^
/Users/<USER>/tmp/zig/src/link/tapi/yaml.zig:59:28: 0x1071e5a83 in link.tapi.yaml.Value.asList (zig)
        if (self != .list) return error.TypeMismatch;
                           ^
/Users/<USER>/tmp/zig/src/link/tapi/yaml.zig:59:28: 0x1071e5a83 in link.tapi.yaml.Value.asList (zig)
        if (self != .list) return error.TypeMismatch;
                           ^
/Users/<USER>/tmp/zig/src/link/tapi/yaml.zig:59:28: 0x1071e5a83 in link.tapi.yaml.Value.asList (zig)
        if (self != .list) return error.TypeMismatch;
                           ^
/Users/<USER>/tmp/zig/src/link/tapi/yaml.zig:59:28: 0x1071e5a83 in link.tapi.yaml.Value.asList (zig)
        if (self != .list) return error.TypeMismatch;
                           ^
/Users/<USER>/tmp/zig/src/link/tapi/yaml.zig:59:28: 0x1071e5a83 in link.tapi.yaml.Value.asList (zig)
        if (self != .list) return error.TypeMismatch;
                           ^
/Users/<USER>/tmp/zig/src/link/tapi/yaml.zig:59:28: 0x1071e5a83 in link.tapi.yaml.Value.asList (zig)
        if (self != .list) return error.TypeMismatch;
                           ^
/Users/<USER>/tmp/zig/src/link/tapi/yaml.zig:59:28: 0x1071e5a83 in link.tapi.yaml.Value.asList (zig)
        if (self != .list) return error.TypeMismatch;
                           ^
/Users/<USER>/tmp/zig/src/link/tapi/yaml.zig:59:28: 0x1071e5a83 in link.tapi.yaml.Value.asList (zig)
        if (self != .list) return error.TypeMismatch;
                           ^
/Users/<USER>/tmp/zig/src/link/tapi/yaml.zig:59:28: 0x1071e5a83 in link.tapi.yaml.Value.asList (zig)
        if (self != .list) return error.TypeMismatch;
                           ^
/Users/<USER>/tmp/zig/src/link/tapi/yaml.zig:59:28: 0x1071e5a83 in link.tapi.yaml.Value.asList (zig)
        if (self != .list) return error.TypeMismatch;
                           ^
/Users/<USER>/tmp/zig/src/link/MachO.zig:977:13: 0x106d94501 in link.MachO.flushModule (zig)
            return error.LibraryNotFound;
            ^
/Users/<USER>/tmp/zig/src/link/MachO.zig:429:5: 0x106d7673d in link.MachO.flush (zig)
    try self.flushModule(comp);
    ^
/Users/<USER>/tmp/zig/src/link.zig:582:23: 0x106d73aae in link.File.flush (zig)
            .macho => return @fieldParentPtr(MachO, "base", base).flush(comp),
                      ^
/Users/<USER>/tmp/zig/src/Compilation.zig:2186:5: 0x106d3280f in Compilation.flush (zig)
    try comp.bin_file.flush(comp); // This is needed before reading the error flags.
    ^
/Users/<USER>/tmp/zig/src/Compilation.zig:2168:9: 0x106d28afa in Compilation.update (zig)
        try comp.flush();
        ^
/Users/<USER>/tmp/zig/src/main.zig:2952:5: 0x106c9136e in updateModule (zig)
    try comp.update();
    ^
/Users/<USER>/tmp/zig/src/main.zig:2644:21: 0x106c193e4 in buildOutputType (zig)
        else => |e| return e,
                    ^
/Users/<USER>/tmp/zig/src/main.zig:216:9: 0x106bfeb89 in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .zig_test);
        ^
/Users/<USER>/tmp/zig/src/main.zig:165:5: 0x106bfdb16 in main (zig)
    return mainArgs(gpa, arena, args);
    ^
/Users/<USER>/tmp/zig/src/link/tapi/yaml.zig:59:28: 0x1071e5a83 in link.tapi.yaml.Value.asList (zig)
        if (self != .list) return error.TypeMismatch;
                           ^
/Users/<USER>/tmp/zig/src/link/tapi/yaml.zig:59:28: 0x1071e5a83 in link.tapi.yaml.Value.asList (zig)
        if (self != .list) return error.TypeMismatch;
                           ^
/Users/<USER>/tmp/zig/src/link/tapi/yaml.zig:59:28: 0x1071e5a83 in link.tapi.yaml.Value.asList (zig)
        if (self != .list) return error.TypeMismatch;
                           ^
/Users/<USER>/tmp/zig/src/link/tapi/yaml.zig:59:28: 0x1071e5a83 in link.tapi.yaml.Value.asList (zig)
        if (self != .list) return error.TypeMismatch;
                           ^
/Users/<USER>/tmp/zig/src/link/tapi/yaml.zig:59:28: 0x1071e5a83 in link.tapi.yaml.Value.asList (zig)
        if (self != .list) return error.TypeMismatch;
                           ^
/Users/<USER>/tmp/zig/src/link/tapi/yaml.zig:59:28: 0x1071e5a83 in link.tapi.yaml.Value.asList (zig)
        if (self != .list) return error.TypeMismatch;
                           ^
/Users/<USER>/tmp/zig/src/link/tapi/yaml.zig:59:28: 0x1071e5a83 in link.tapi.yaml.Value.asList (zig)
        if (self != .list) return error.TypeMismatch;
```

</details>

Explicitly passing the system library path with `-L /usr/lib` cause a different error, see "Details" below. This looks like an artifact of trying to link libc multiple times.

<details>

```
./stage2/bin/zig test test/behavior/math.zig -fLLVM --verbose-link --verbose-cimport --debug-compile-errors -L/usr/lib
zig ld -dynamic test/behavior/zig-cache/o/783d5453cbac6c1d886fd23c0253781d/test.o /Users/<USER>/.cache/zig/o/6038e68b06b36a4a81a14614da4b49f6/libcompiler_rt.a -o test/behavior/zig-cache/o/783d5453cbac6c1d886fd23c0253781d/test -lSystem -lc -lc -L/usr/lib
thread 251135 panic: reached unreachable code
/Users/<USER>/tmp/zig/build/lib/zig/std/debug.zig:234:14: 0x101dae018 in std.debug.assert (zig)
    if (!ok) unreachable; // assertion failure
             ^
/Users/<USER>/tmp/zig/build/lib/zig/std/hash_map.zig:994:19: 0x1021f6d39 in std.hash_map.HashMapUnmanaged([]const u8,u16,std.hash_map.StringContext,80).putNoClobberContext (zig)
            assert(!self.containsContext(key, ctx));
                  ^
/Users/<USER>/tmp/zig/build/lib/zig/std/hash_map.zig:991:44: 0x101fc00f5 in std.hash_map.HashMapUnmanaged([]const u8,u16,std.hash_map.StringContext,80).putNoClobber (zig)
            return self.putNoClobberContext(allocator, key, value, undefined);
                                           ^
/Users/<USER>/tmp/zig/src/link/MachO.zig:1306:37: 0x101f95b24 in link.MachO.parseDylib (zig)
    try self.dylibs_map.putNoClobber(self.base.allocator, dylib.id.?.name, dylib_id);
                                    ^
/Users/<USER>/tmp/zig/src/link/MachO.zig:1355:32: 0x101f68c6f in link.MachO.parseLibs (zig)
        if (try self.parseDylib(lib, .{
                               ^
/Users/<USER>/tmp/zig/src/link/MachO.zig:918:31: 0x101f49aad in link.MachO.flushModule (zig)
            try self.parseLibs(libs.items, self.base.options.sysroot, &dependent_libs);
                              ^
/Users/<USER>/tmp/zig/src/link/MachO.zig:429:25: 0x101f2c71e in link.MachO.flush (zig)
    try self.flushModule(comp);
                        ^
/Users/<USER>/tmp/zig/src/link.zig:582:72: 0x101f29a95 in link.File.flush (zig)
            .macho => return @fieldParentPtr(MachO, "base", base).flush(comp),
                                                                       ^
/Users/<USER>/tmp/zig/src/Compilation.zig:2186:28: 0x101ee87f0 in Compilation.flush (zig)
    try comp.bin_file.flush(comp); // This is needed before reading the error flags.
                           ^
/Users/<USER>/tmp/zig/src/Compilation.zig:2168:23: 0x101edea89 in Compilation.update (zig)
        try comp.flush();
                      ^
/Users/<USER>/tmp/zig/src/main.zig:2952:20: 0x101e47340 in updateModule (zig)
    try comp.update();
                   ^
/Users/<USER>/tmp/zig/src/main.zig:2642:17: 0x101dcf17f in buildOutputType (zig)
    updateModule(gpa, comp, hook) catch |err| switch (err) {
                ^
/Users/<USER>/tmp/zig/src/main.zig:216:31: 0x101db4b5d in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .zig_test);
                              ^
/Users/<USER>/tmp/zig/src/main.zig:165:20: 0x101db3ae2 in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/Users/<USER>/tmp/zig/build/lib/zig/std/start.zig:561:37: 0x10229ec78 in std.start.callMain (zig)
            const result = root.main() catch |err| {
                                    ^
/Users/<USER>/tmp/zig/build/lib/zig/std/start.zig:495:12: 0x101db6397 in std.start.callMainWithArgs (zig)
    return @call(.{ .modifier = .always_inline }, callMain, .{});
           ^
/Users/<USER>/tmp/zig/build/lib/zig/std/start.zig:460:12: 0x101db62d5 in std.start.main (zig)
    return @call(.{ .modifier = .always_inline }, callMainWithArgs, .{ @intCast(usize, c_argc), c_argv, envp });
           ^
???:?:?: 0x7fff6d95bcc8 in ??? (???)
???:?:?: 0x7 in ??? (???)
zsh: abort      ./stage2/bin/zig test test/behavior/math.zig -fLLVM --verbose-link
```

</details>

cc @kubkon, as mentioned in Discord.

### PR DESCRIPTION
**Pull request by kubkon**
Fixes #10765

Changes:

* sema: do not pass libc or libc++ to the linker as system libs on the linker line `-lc` and `-lc++` - they are handled separately via link options flags
* macho: handle bss like normal section in stage2 - this is just a temporary workaround until I work out how to manage non-physical sections between incremental updates
* update stage2 tests to use name-qualified import lib names for externs:

From:

```zig
extern fn write(...);
```

to

```zig
extern "c" fn write(...);
```

cc @schmee

### CODE REVIEW

**Review by schmee — APPROVED** [review]
Fixes the issues I'm seeing in https://github.com/ziglang/zig/issues/10765, thanks for investigating @kubkon!

**Comment by schmee** [comment]
On a closer look, I've found another issue. This may or may not be related to this PR but I'll post it here for completeness. With this PR, the following commands run successfully:

1. Building and running this program with `./stage2/bin/zig build-exe -lc -fLLVM program.zig`
```
pub extern "c" fn printf(format: [*:0]const u8, ...) c_int;

pub fn main() void {
    _ = printf("hello world!");
}
```
2. Running all behavior tests _except_ `translate_c_macros`:
```
$ ./stage2/bin/zig test test/behavior.zig -fLLVM
658 passed; 188 skipped; 0 failed.
```

Running the `translate_c_macros` tests results in the following output:


<details>

```
~/t/zig link-lib-fixes !1 ?11 ↯ 0.10.0-dev.415+178cd60a5 ./stage2/bin/zig test test/behavior/translate_c_macros.zig -fLLVM --verbose-cimport --debug-compile-errors
info(compilation): C import source: test/behavior/zig-cache/o/8710f9a6987c3382be290e2fc8e4697a/cimport.h
compile error during Sema: C import failed, src: translate_c_macros.zig:LazySrcLoc{ .node_offset = -1 }
thread 651957 panic: unexpected compile error occurred
Analyzing test/behavior/translate_c_macros.zig: translate_c_macros.zig:h
    > %18 = c_import({
        %19 = str("behavior/translate_c_macros.h")
        %20 = as_node(@Ref.const_slice_u8_type, %19)
        %21 = extended(c_include(%20))
        %22 = break_inline(%18, @Ref.void_value)
      })
      %23 = break_inline(%17, %18)
    For full context, use the command
      zig ast-check -t test/behavior/translate_c_macros.zig

  in test/behavior/translate_c_macros.zig: translate_c_macros.zig:test.casting to void with a macro
    > %26 = decl_ref("h")

/Users/<USER>/tmp/zig/src/Sema.zig:1398:35: 0x107e18b1e in Sema.failWithOwnedErrorMsg (zig)
        crash_report.compilerPanic("unexpected compile error occurred", null);
                                  ^
/Users/<USER>/tmp/zig/src/Sema.zig:3426:42: 0x107f46944 in Sema.zirCImport (zig)
        return sema.failWithOwnedErrorMsg(msg);
                                         ^
/Users/<USER>/tmp/zig/src/Sema.zig:606:65: 0x107d9ba72 in Sema.analyzeBodyInner (zig)
            .c_import                     => try sema.zirCImport(block, inst),
                                                                ^
/Users/<USER>/tmp/zig/src/Sema.zig:522:33: 0x107c00ffa in Sema.analyzeBody (zig)
    return sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                                ^
/Users/<USER>/tmp/zig/src/Module.zig:3628:45: 0x107c0dd28 in Module.semaDecl (zig)
    const break_index = try sema.analyzeBody(&block_scope, body);
                                            ^
/Users/<USER>/tmp/zig/src/Module.zig:3359:38: 0x107be02ec in Module.ensureDeclAnalyzed (zig)
    const type_changed = mod.semaDecl(decl) catch |err| switch (err) {
                                     ^
/Users/<USER>/tmp/zig/src/Sema.zig:15405:32: 0x1080c7313 in Sema.ensureDeclAnalyzed (zig)
    sema.mod.ensureDeclAnalyzed(decl) catch |err| {
                               ^
/Users/<USER>/tmp/zig/src/Sema.zig:15417:32: 0x10809568a in Sema.analyzeDeclRef (zig)
    try sema.ensureDeclAnalyzed(decl);
                               ^
/Users/<USER>/tmp/zig/src/Sema.zig:3866:31: 0x107f4aa71 in Sema.zirDeclRef (zig)
    return sema.analyzeDeclRef(decl);
                              ^
/Users/<USER>/tmp/zig/src/Sema.zig:616:65: 0x107d9c267 in Sema.analyzeBodyInner (zig)
            .decl_ref                     => try sema.zirDeclRef(block, inst),
                                                                ^
/Users/<USER>/tmp/zig/src/Sema.zig:522:33: 0x107c00ffa in Sema.analyzeBody (zig)
    return sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                                ^
/Users/<USER>/tmp/zig/src/Module.zig:4563:25: 0x107bdd59e in Module.analyzeFnBody (zig)
    _ = sema.analyzeBody(&inner_block, fn_info.body) catch |err| switch (err) {
                        ^
/Users/<USER>/tmp/zig/src/Compilation.zig:2756:47: 0x1079b6bed in Compilation.processOneJob (zig)
                var air = module.analyzeFnBody(decl, func, sema_arena) catch |err| switch (err) {
                                              ^
/Users/<USER>/tmp/zig/src/Compilation.zig:2675:30: 0x1079a0b84 in Compilation.performAllTheWork (zig)
            try processOneJob(self, work_item, main_progress_node);
                             ^
/Users/<USER>/tmp/zig/src/Compilation.zig:2081:31: 0x107999d2a in Compilation.update (zig)
    try comp.performAllTheWork();
                              ^
/Users/<USER>/tmp/zig/src/main.zig:2952:20: 0x1079032a0 in updateModule (zig)
    try comp.update();
                   ^
/Users/<USER>/tmp/zig/src/main.zig:2642:17: 0x10788b0df in buildOutputType (zig)
    updateModule(gpa, comp, hook) catch |err| switch (err) {
                ^
/Users/<USER>/tmp/zig/src/main.zig:216:31: 0x107870abd in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .zig_test);
                              ^
/Users/<USER>/tmp/zig/src/main.zig:165:20: 0x10786fa42 in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/Users/<USER>/tmp/zig/build/lib/zig/std/start.zig:561:37: 0x107d5abc8 in std.start.callMain (zig)
            const result = root.main() catch |err| {
                                    ^
/Users/<USER>/tmp/zig/build/lib/zig/std/start.zig:495:12: 0x1078722f7 in std.start.callMainWithArgs (zig)
    return @call(.{ .modifier = .always_inline }, callMain, .{});
           ^
/Users/<USER>/tmp/zig/build/lib/zig/std/start.zig:460:12: 0x107872235 in std.start.main (zig)
    return @call(.{ .modifier = .always_inline }, callMainWithArgs, .{ @intCast(usize, c_argc), c_argv, envp });
           ^
???:?:?: 0x7fff6d95bcc8 in ??? (???)
???:?:?: 0x5 in ??? (???)
zsh: abort      ./stage2/bin/zig test test/behavior/translate_c_macros.zig -fLLVM
```

</details>

Looking in the file system, `cimport.h` is indeed there:

```
$ cat test/behavior/zig-cache/o/8710f9a6987c3382be290e2fc8e4697a/cimport.h
#include <behavior/translate_c_macros.h>
```

Again, might be related to this or might be another problem entirely, I'll take a look at it and see if I can figure anything out 👍

**Comment by kubkon** [comment]
> On a closer look, I've found another issue. This may or may not be related to this PR but I'll post it here for completeness. With this PR, the following commands run successfully:
> 
>     1. Building and running this program with `./stage2/bin/zig build-exe -lc -fLLVM program.zig`
> 
> 
> ```
> pub extern "c" fn printf(format: [*:0]const u8, ...) c_int;
> 
> pub fn main() void {
>     _ = printf("hello world!");
> }
> ```
> 
>     2. Running all behavior tests _except_ `translate_c_macros`:
> 
> 
> ```
> $ ./stage2/bin/zig test test/behavior.zig -fLLVM
> 658 passed; 188 skipped; 0 failed.
> ```
> 
> Running the `translate_c_macros` tests results in the following output:
> 
> Looking in the file system, `cimport.h` is indeed there:
> 
> ```
> $ cat test/behavior/zig-cache/o/8710f9a6987c3382be290e2fc8e4697a/cimport.h
> #include <behavior/translate_c_macros.h>
> ```
> 
> Again, might be related to this or might be another problem entirely, I'll take a look at it and see if I can figure anything out +1

This looks like an unrelated issue as, if you look closely in the stack trace, it doesn't enter into the linker at all. I guess it wouldn't as it's meant to spit out a zig source file?

**Comment by schmee** [comment]
Makes sense, I'll do some more digging and maybe open a separate issue 👍

**Pull request merged**
