### PR TITLE
Package.Fetch: normalize path separators in symlinks

### LINKED ISSUE #17549: package fetching: path separators in symlinks are not normalized
Here you can see that symlink data is passed directly to the hasher:

https://github.com/ziglang/zig/blob/ca690ffa22ab4463e53b547d109a2b2081771e05/src/Package/Fetch.zig#L1430-L1433

This leads to incorrect package hashes on Windows when the unpacked directory of files has any symlinks with path separators in them.

Instead, on Windows only, back slashes need to be normalized into forward slashes.

Example - this is the expected results, and what happens on Linux:

```
$ zig fetch https://github.com/mitchellh/zig-build-macos-sdk/archive/166ff65bb7688c0a08c4ea98166ec8300aa34128.tar.gz
1220bfe1b32491a3448dff55c1dc0c12aa573f1e5bdb0a962bfbadaaa59e4833798b
```

However, on Windows, it gives an incorrect result:

```
PS C:\> zig.exe fetch https://github.com/mitchellh/zig-build-macos-sdk/archive/166ff65bb7688c0a08c4ea98166ec8300aa34128.tar.gz
1220505223f0f4e7208583416b19e3c913992218062b2ba8e41018364e7a5a8e93ae
```

### PR DESCRIPTION
**Pull request by andrewrk**
closes #17549

### CODE REVIEW

**Comment by andrewrk** [comment]
Using the new `--debug-hash` argument, I obtained this diff, showing where the problem is:

```diff
--- tmp/1	2023-10-16 18:16:37.782791727 -0700
+++ tmp/2	2023-10-16 18:23:55.375984408 -0700
@@ -305,13 +305,13 @@
 file: ea5f7a63bb1118ea4e6574a7a58e50fca59cab9a87a8c054e597940136eac828: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Headers/SFNTTypes.h
 file: 6c77e5b0502cb279eb37d3a1cefa9c9531913670251f9e1330e2a1087852c5c3: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/ATSHI.tbd
 file: 2eaa9a0dffe077794ca3b67d1317065b4380cf5e77d12e027813178f7ec1e550: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libATSServer.tbd
-link: 90ba3b9a62d13eeec7be8a39152fdeffe5cc49e0c8811d06c3ce941149fac125: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontParser.tbd
+link: 92f5c31621d8ab55cbf8d2872d5019c32c93d640081bbe3994978d19206e70a0: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontParser.tbd
 file: fb1b8e63d06ed4d222716fe0862f6a51e338660bfc2ad2520958e82e76206219: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontRegistry.tbd
 file: 12912efe0ff69cc1e213df97a6b9c3fe4367b83944293dba37fc2049d6db2e51: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontRegistryUI.tbd
 file: dd57270c3b0660e8a503059d85fc638a7457717f8e58da3f62b89099af6bf882: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontValidation.tbd
 file: bd55d0f4bbecf6df264f0bcfa533d4b810f0696d0aaddd3ad210ea3d9860db52: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontWorkerAccess.tbd
-link: bc8eb5fb699f82463e47a5ebafe60206ffc013c7fda285f53a14993674917fc1: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libType1Scaler.tbd
-link: 3034fca5e6ff0639a1ae529453908d471d1cf137379368b7e1711837b717aa7f: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libhvf.tbd
+link: 6e6cae05b9dc20967f81ab2979e6c0d0154af93497a72a72b2476cb8139c405f: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libType1Scaler.tbd
+link: dc85d00a52077567dcbc6c76c78999e295ec874235c27c838253bb3bc432fe4e: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libhvf.tbd
 link: 34e64d90337c8f0be60fcb7f599802b6034f5fff19336eb5434b51776848a9e7: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/Current
 link: 74fb7e9b35ac269f618d18c87b03a2e3cc53c04313c417eb56b8ebd424a937c5: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATSUI.framework/ATSUI.tbd
 link: 164caf700abd352ea07685f791a513c8a88bdceafbd8ea17cd450781b3c9d41d: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATSUI.framework/Headers
@@ -326,13 +326,13 @@
 file: 9f84679b092c94401e8208688d9b87a77a573ac7a90385c27076c48070efa622: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATSUI.framework/Versions/A/Headers/ATSUnicodeObjects.h
 file: 7bf58507450bc2a930db6b0c02c1850c3f7e05f6ac9bcb7ac10033bda6f78573: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATSUI.framework/Versions/A/Headers/ATSUnicodeTypes.h
 link: ea228b4302046e2cbb96d1dac0fd3fa37d9fe8feb4f2bb205695d9d23dcfc652: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATSUI.framework/Versions/Current
-link: d8e59509ad9610b0feedc5c52098def157ee71dfec6cd5ac56fbe8dd71d10259: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ColorSync.framework
+link: d14a96db1a8c36f4ccbc96d38f2aabc7c7f95325c91393a2b97f206aed842dd7: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ColorSync.framework
 link: c4909a7fe4fbee0a1ec62a8d258abb7fe07d9481bfae649a623893f7932f09fd: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ColorSyncLegacy.framework/ColorSyncLegacy.tbd
 file: e0273b9fb20a957df1193177fa5d9467a1ce8509d650c9f34e3aed23936dc155: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ColorSyncLegacy.framework/Versions/A/ColorSyncLegacy.tbd
 file: f25244b4af25872a7b4f604024a92c83d0f0f0e8e6921b70d5b1820718e0cfda: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ColorSyncLegacy.framework/Versions/A/Resources/ColorSyncDeprecated.tbd
 link: e6039ed6c644434325ac92104a9408c4b98c43f608f74b6d176e1a18925270e8: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ColorSyncLegacy.framework/Versions/Current
-link: 601e29ce90e30b4544ec7c59037d3c41210ef980708273f8c956ecca6e4b911a: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/CoreGraphics.framework
-link: 649bd3510394763799fe9eeffd787816854d7e5996b77c1ec9119983c55732ea: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/CoreText.framework
+link: 2ebf330f8f0554217f0055ca90cc538efed8f3935e1fd7bbc3895647f0163d96: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/CoreGraphics.framework
+link: 74c2013c0cd7c3a599a33ef47ed7878ab33d1d2c0f78823bc7237b2403347cf2: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/CoreText.framework
 link: 6c4eae9edb4d5b3e703b0fe5cefdc856b3821e0723b498420db225e92617a9ca: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/HIServices.framework/HIServices.tbd
 link: f8fff846afcd992b1ae9e8ffbb4fa033c3c9f6a2febff9b5f9e0b4d48b95803a: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/HIServices.framework/Headers
 file: 6b7a197546d73ac5b8cba4fd67721b639a67d8df5d36348d7354a41f02cd11d4: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/HIServices.framework/Versions/A/HIServices.tbd
@@ -356,7 +356,7 @@
 file: 5625c24c7f98038a161d0c61aa71a998cdc322d09e50d4459794e85cffef8393: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/HIServices.framework/Versions/A/Headers/TranslationServices.h
 file: d67d9c6c368d62c9d92748d07f8fb51a6c616b044907a248df111d9a1c2770d6: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/HIServices.framework/Versions/A/Headers/UniversalAccess.h
 link: b92835184368f0498b923c8f6c1310ea043c0ea1daf8542a745ebdb342671114: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/HIServices.framework/Versions/Current
-link: d0c9dfa6364e34226fe5a40e2be0a7a718afedc3eb97ad5168500e1022e82bd2: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ImageIO.framework
+link: f8f706352955753d7ee96bbe5a8a920d7c15897d15d36eb2b01231ccb72ae812: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ImageIO.framework
 link: 3708f64d399fda3103c8aeba81a21a6fd7f91bdde45d0de603a8bf4f26170e1f: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/PrintCore.framework/Headers
 link: 7d9698664416013c5c7979b3e2b036825961cd1f0c23d9745a17e714cb10c3a9: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/PrintCore.framework/PrintCore.tbd
 file: 36a4a59027b489ba0d50c1e1d0f055fd70f7913c07c4d28739c2db75805a6fcd: Frameworks/ApplicationServices.framework/Versions/A/Frameworks/PrintCore.framework/Versions/A/Headers/PDEPluginInterface.h
@@ -1389,11 +1389,11 @@
 file: 6bf1473938eb8580ed910ac0a02cf7298a48ea05763cbcbd4bc3b90fcd9322f0: Frameworks/ImageIO.framework/Versions/A/Resources/libTIFF.tbd
 link: 2ba9399484080ac4b5d762461526eade3bead1bc92d27299a539547fc31390a9: Frameworks/ImageIO.framework/Versions/Current
 link: 9bb6806890f7f6259520a1514faa49f8b73b5dd8669bf4e805214c5918bc567b: Frameworks/Kernel.framework/Headers
-link: b8c7a06b6a270f8c42a0e9f8dfbb20280f648bb9953a28dc8b7579deabc3d57b: Frameworks/Kernel.framework/Versions/A/Headers/AssertMacros.h
-link: 4b259c24a02500c6f9172b19b47469f07e4b40782f5f54fbe7ee995da86a3d6f: Frameworks/Kernel.framework/Versions/A/Headers/Availability.h
-link: fb5f20ffe2caeda53a9f9eb95f1015de5979d7a210fe07122614dd878fff1274: Frameworks/Kernel.framework/Versions/A/Headers/AvailabilityInternal.h
-link: de097694e3859fffc110bde698d7c9226e684c16b80ed823c9bc55e9d9386e30: Frameworks/Kernel.framework/Versions/A/Headers/AvailabilityMacros.h
-link: 7515b3afdb56a6cc6266740a3f7af14b712860814e37913560b9d16946f81003: Frameworks/Kernel.framework/Versions/A/Headers/AvailabilityVersions.h
+link: cf61d69edc51fa192dd82bc532defe7d4e0faff7477680442b04bd530bb3309a: Frameworks/Kernel.framework/Versions/A/Headers/AssertMacros.h
+link: e6485347e1957e8b4568b373359c576f7b53f7979fd2d075cbd29feec81902b8: Frameworks/Kernel.framework/Versions/A/Headers/Availability.h
+link: d0f94e630b2c1e643ba3567859414f92f345c27a3076754e3bb21a946f5a4288: Frameworks/Kernel.framework/Versions/A/Headers/AvailabilityInternal.h
+link: 8d8f00716938fc19225100967b695573cc032889bcc1500cc0aa11940b7d6433: Frameworks/Kernel.framework/Versions/A/Headers/AvailabilityMacros.h
+link: bfa7f61f5729cf5c019d9cd8c6d197a4d831db23b1b9063aaaa8849ba62b941b: Frameworks/Kernel.framework/Versions/A/Headers/AvailabilityVersions.h
 file: 16559cd563ae384b69c861369847ff8e6c8676c59dcad040511909461682d4d3: Frameworks/Kernel.framework/Versions/A/Headers/IOKit/hidsystem/IOHIDDescriptorParser.h
 file: a87872e7d52d1d7e4b17bb9b19b378909758f79fb17c248f6a9c10336ca180cd: Frameworks/Kernel.framework/Versions/A/Headers/IOKit/hidsystem/IOHIDParameter.h
 file: cb61a2945d7ad8e25a04254751318a1d336e33cd5f98b0b16d05e1acc00afcb9: Frameworks/Kernel.framework/Versions/A/Headers/IOKit/hidsystem/IOHIDShared.h
@@ -1407,8 +1407,8 @@
 file: bc2886e87855a0f80e37000427374392a33b7606e955330507beff21c452dad3: Frameworks/Kernel.framework/Versions/A/Headers/IOKit/hidsystem/IOHIPointing.h
 file: 2f6ce7b920544e605f50fb323547e4af0aca2b2a3e4ed960045c1ddfe42f6bee: Frameworks/Kernel.framework/Versions/A/Headers/IOKit/hidsystem/IOLLEvent.h
 file: 3114b74504ab91673bfa6ead5897877a43909dfce9b5fc2485ff20332387cfe6: Frameworks/Kernel.framework/Versions/A/Headers/IOKit/hidsystem/ev_keymap.h
-link: c3a2a795414629acac706441fbc1359f11a1b1dae9263aa93693f1600a31a978: Frameworks/Kernel.framework/Versions/A/Headers/TargetConditionals.h
-link: 874b41ae413bb5c7f2dcb6aa50f65222b6a47bac4ac2bfb6b1753e4cd24c07d3: Frameworks/Kernel.framework/Versions/A/Headers/os/availability.h
+link: a090b70fd59a825d1371b2741cfa90b30698bf6d5d658f8833884d25448e292b: Frameworks/Kernel.framework/Versions/A/Headers/TargetConditionals.h
+link: 98851cd154d47234c2fcdc11f38d873791072c6a421c465df5ef8c335b2663b2: Frameworks/Kernel.framework/Versions/A/Headers/os/availability.h
 link: 1b35dcc985e755200f7787bf4fbe921ce0849e257e9c8fd1a03abc19356efa73: Frameworks/Kernel.framework/Versions/Current
 link: 1f1d5d2363aa8167865f1fb27de938b9fad398a3a4e43c71b07ac106eb27a199: Frameworks/Metal.framework/Headers
 link: cf8e061c1a739d21c9fc19fe4c1b30416aa3cf8b196e78f92ea1a8a46257320b: Frameworks/Metal.framework/Metal.tbd
@@ -1848,7 +1848,7 @@
 file: 05545f326e0f6b574515050431b68b66eb197490fc4bb21596316a0a03f3f689: include/arm64/hv/hv_kern_types.h
 file: d97e5686821cc3619c16839232b4a0278bf4526e6f92a3f1203f0d5db65bbfbc: include/arpa/ftp.h
 file: 7d19e85c250782907a488d5ada0c45acd6a29cc67db63d03ca983647830ac43c: include/arpa/inet.h
-link: 5039a503d821fc6449499abc0787187466fc6b3356b9c97996860519e412223d: include/arpa/nameser.h
+link: b11d1b5578138850030e3a3b29d51eb186e53c1db86844c5f3f76365e5821566: include/arpa/nameser.h
 file: ff2857df750fec77583f542fb726bba9474c0992c334da4eb97bdc4961c283bb: include/arpa/nameser_compat.h
 file: 448c157696c26a5eba4c40f131d8c4035949fff86fb1d37c280f4a7517b4718f: include/arpa/telnet.h
 file: 0001f04477ba987633826624a406310af52f4860eb70a530fcb065b667929ea4: include/arpa/tftp.h
@@ -2873,7 +2873,7 @@
 file: 927dc268d3e1164da7662371fc8172d2efc4099389fc943b8fdc7e4dd07ab947: include/libxml/xpath.h
 file: 2ebcc93e1713c7fd4d734bfe3636b3a76574dce3c8c1eec42d24d7ca74439620: include/libxml/xpathInternals.h
 file: e76094248d69c121e0cb16d54efaa89ca6fff552093cd41fdaccdb6f58b4bbaf: include/libxml/xpointer.h
-link: 00433dd442074ea9a4abf3f77870ab4cbe8344c6db733f79d500d72f2d813976: include/libxml2/libxml
+link: 9bee0ad999ffeb3f0bfe800e391db15079bae4411106d350d56f124046642ca3: include/libxml2/libxml
 file: 018d0d26a823c6d526958abe50290efc42a3f6b9e4eae3e7c9a008c9fa5fc46a: include/libxslt/attributes.h
 file: 0a77aa9f8a791a4a6088a7a5398f7c357a1bdd5a405f73bb62721c4e30794424: include/libxslt/documents.h
 file: 0105314c798c5d3cd35da1b0694049de47f8f545f5004de4826fcb2c559d92b4: include/libxslt/extensions.h
@@ -3461,8 +3461,8 @@
 link: 5be35606398bfc71fb55469d83e7bcf5b878ed0f786b772bbd71c1857ef55187: include/pthread_spis.h
 file: 480b5ed8732e7e8ae4a1f03b479449ed71a598c086c20d64e4486d13cadd7ea2: include/pwd.h
 file: 5487d5534a4704706ae25946bb6b46c1074ecec1a555bdc406adc61d06ed2be0: include/ranlib.h
-link: 76c2c8978c8952b28ebf8be65908c57ff9550603c66bf5f330a71eb22fca89eb: include/readline/history.h
-link: ad811e865cae8aac38de82a8c05a7a037b999b888c6965009bd42f2db2db9821: include/readline/readline.h
+link: 37a77f8c6935b40f7f7ecf68034514c43dddf997f3e0c4bb357625a52e0de97c: include/readline/history.h
+link: 5cd7bed14aad9e07855b7b951ca3e456717626739c54b793951d0a8adc12a398: include/readline/readline.h
 file: aefe02d1503485dc3038a6241cfa69006e641f53c52a89da232399acdcec7563: include/readpassphrase.h
 file: bf3a1bcdf96c12cc0a5ba6a57b6acb1b1879e440359a7d1b2830756bf9a41cbe: include/regex.h
 file: 2c7558ce0a08e218a8aa465a80aa91e6ad39b4ca4d0f24eb8eee205c30972bd1: include/removefile.h
@@ -3537,8 +3537,8 @@
 file: 4ac71199b554afab25c4e0c50f684adca1a174e69da8f930dcb092aa14dd0dea: include/security/pam_modules.h
 file: b7688883f5a3cc326cd9ed5b75a06655a2bc0de92b02403052659456b0ee8d0b: include/security/pam_types.h
 file: 845f0eea6e7ed9bcca7aa52d7f3b47252773ae10a3315dcec74961be73faf54b: include/semaphore.h
-link: 95e479dcc0b379c9a2477fcc107aadc412fa848b2c76a60b43621417dfa64d2a: include/servers/bootstrap.h
-link: 0814f8e79ec45d0d1421c31aec23b2dec9087308e520adcfec2287f4bf0009f0: include/servers/bootstrap_defs.h
+link: 9d318de1b7580411e887d71a45bb53d13bfea530fce4f054538e1bbca0951c81: include/servers/bootstrap.h
+link: 18fd0c8dd4731107cec1f5df703894176b6faf50311933c4cafade342ff68e81: include/servers/bootstrap_defs.h
 file: e7ab3a00f6a61e3c06e05b88f7464d7456c8bc21835e56fab3b8bea01bc9a5c5: include/servers/key_defs.h
 file: 62c77e31181db81a3be68683850137fa491d2421f87c72bd8c968505822d1f58: include/servers/ls_defs.h
 file: 4421c9e0c1126b66a6afc4a0281066e92bbf2c4dd5e8037f1122f8526aa39c92: include/servers/netname.h
@@ -3805,11 +3805,11 @@
 file: 3b983db975b62a40cbc3609d8572b1e57747f8942f237d04657fc78aef31762c: include/sysexits.h
 file: b54db5fb892af0978ac83631a60e460866dc1418a960b6845f4f1b7e407d9d65: include/syslog.h
 file: 74a0a73c1123c2508e99f63d2d561242c4f2524b0cbbb4b0fd0a0b9ee660481a: include/tar.h
-link: afe6285bae36ff3fd9d015aaedfb5f3d0e30d9f2bd153a09268ceb65e10bdb4a: include/tcl.h
-link: e687920977568757f51d98ce0f3ece0a20ec9ab468775ddb76dbb5e4859ba875: include/tclDecls.h
-link: ca85c4d9b2c466ab435e106f7b929f9b16e585b45eb855be4bcddf8963d016ed: include/tclPlatDecls.h
-link: c9342a8e8ca6453ba5308429e2e65ab9227f46958ff9a671ce77a0ffd334a8e0: include/tclTomMath.h
-link: b2d846885adf5d826d6c08c5333f26446411b4c55328f6639cd481b94938c8a4: include/tclTomMathDecls.h
+link: 80ae4ef9c0a6fc06e74f477a045cc6b4f38d09854accc49559512c341a8ad507: include/tcl.h
+link: 69ee1bd75af687cad1755932800ad4acfefdcbba8911dfa3a7607b287d823690: include/tclDecls.h
+link: 7160b26f7869b4729461072808e228db160b4029b7ef223cf254d7a2c1769c5c: include/tclPlatDecls.h
+link: e81abff0ea33297e5e33d448f25fbb89c34a1ed47abcfdee38926c09769ea4bd: include/tclTomMath.h
+link: f0766f5c7b3454725d68b6710fa62a0926c0623f2438728849131d1756088a44: include/tclTomMathDecls.h
 file: 57d865c2166619e41829bd71d43f4ea35a494962a8e2dc8f27fee4c3b8dff0b8: include/term.h
 file: 7b1d1ba9db87506105ab317bff472a569b9a6e664c56c9990172adb5e8e99c00: include/term_entry.h
 file: 844cc332a5487b55f2be5cf0f7f574812d40add3108f35a299ec426b2628a0b5: include/termcap.h
@@ -3822,11 +3822,11 @@
 file: 1518be27f161a8d64ecd0a4ae3fbeedad46de6073845084f1837ffebc1453053: include/tidy/tidyenum.h
 file: 9e694ee40e1d755f49896e0e29807abb7c7c8811ef0c47f8e7fb9c2ef59969d6: include/time.h
 file: 578bcc41ac0d94a694a6754b05d83e5d5ffefb21df640fd9972562c12d5430ec: include/timeconv.h
-link: 95cb1b7f59ac0549b6f432f33d060e0be1ba9d245fba469ac5d363eb0b6f7716: include/tk.h
-link: 9c202101a4fe2161b9afa5020b87759e1012bb16cacd8846303571ed1e06f398: include/tkDecls.h
-link: 063958bb302a3fe970a7eb4eff01996299964cb7607d616fd9a43251499c4f04: include/tkIntXlibDecls.h
-link: 3e397a124b6df528ccab1d46708871840b521c35562e20a9e6f45747f8608f65: include/tkMacOSX.h
-link: 9d48237cdcee5d8894390d883340e5b49676ce14e0ecc6b4b799da8c8d749ddc: include/tkPlatDecls.h
+link: db5fbada67b50ce51dc4e45c4f32162365267f50b957ea715dd6e78d399475e5: include/tk.h
+link: 38c474d06678300157bf63be951db51e8bf6a9a15854bb9589fbdbd3a51282a6: include/tkDecls.h
+link: 44e14f87924b24f25bb6a2c405c3dfb989badd0982d04ab958b45ef821bacecc: include/tkIntXlibDecls.h
+link: 7b536d7ee0defc50b15b7654e23f5ec1a3a61f27bd4b61557495f5960f5ec406: include/tkMacOSX.h
+link: 7e856e0fe9649ae9a368643ae5e46bec544f958530faee8b16f725ff042796b8: include/tkPlatDecls.h
 file: e8e5fe640ce57363f2f7c373bb2c01a143f187004188b89ea5b2bc4ecda32633: include/ttyent.h
 file: b84b51f5c29158c568fbd95d273980c6debbb0f78c31a5406d64047df87ceaa9: include/tzfile.h
 file: 8cf18c8c093483e19e00e8f89cc9d439428946ded191c239a5d0f1dbfbb44154: include/ucontext.h
@@ -3903,4 +3903,4 @@
 file: 3e7f44bd317b48098f1a88f210cd2ffbbc95ba83a81b5f98fea31053ccb10cf4: stub.c
 file: 191a1fcbd1ed2d843c5ec4ab0979e321c309bcb0404f15d820f47180528d6170: update.sh
 file: bb46f74b43f51a0dc2a4be41e6980335e18f18df0cd9cf84e9ee0cbac618f1d6: verify.sh
-1220bfe1b32491a3448dff55c1dc0c12aa573f1e5bdb0a962bfbadaaa59e4833798b
+1220a541473adcd98ee7f528f13faf728d7c63eec3a6ae07001104e6bc76eb8721e8
```

It seems that path separator normalization is not the only thing that is non-equal for symlinks. Finding out what is different...

**Comment by andrewrk** [comment]
If we take one of those examples, `include/tkDecls.h`, we see on posix the symlink data is:
```
../../System/Library/Frameworks/Tk.framework/Versions/8.5/Headers/tkDecls.h
```
however on Windows it is an absolute path:
```
C:/Users/andy/AppData/Local/zig/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers/tkDecls.h
```

So this is actually #17461. That would actually make this fetch *fail* with the error "symlink points to outside of the package".

**Comment by andrewrk** [comment]
I extracted yet another issue from this into #17564.

**Comment by slimsag** [comment]
Just ran into this, nice to see there's a fix already in the works :D

**Pull request merged**
