### PR TITLE
make @log2 work on integers

### LINKED ISSUE #13642: `@log2` should work on integers in addition to floats
```zig
const std = @import("std");

const page_size = 4096;

test {
    try std.testing.expect(@log2(page_size) == 12);
}
```

```
test.zig:6:34: error: expected vector of floats or float type, found 'comptime_int'
    try std.testing.expect(@log2(page_size) == 12);
                                 ^~~~~~~~~
```

This code should work, in addition to runtime-known integers. It should return a value whose type has log2 number of bits.

Related:  #3321

### PR DESCRIPTION
**Pull request by wooster0**
Fixes #13642

This adds support for integers to `@log2`.
This does not add support for vectors of integers because that is not mentioned in #13642.
If that is also desired, I can try implementing that too, or at least a little bit.

This is a draft pull request because even though the tests I added in `test/behavior/floatop.zig` already pass, there are still some things to do and **I have some questions**:
* [X] ~~Should a~~ runtime safety check with a panic id like this https://github.com/ziglang/zig/blob/8ae92fd17ee9a3d46e4f441864a8544b440c0b2d/src/Module.zig#L195C1-L195C4 ~~be~~ added for when a runtime-known integer 0 is passed to `@log2`~~? There is a TODO for this in the code.~~
* [x] Implement log2 for `std.math.big.int.Const` ~~or emit a compile error rather than panicking~~.
* [ ] Figure out if vectors of integers are desired (are they?)

### CODE REVIEW

**Comment by r00ster91** [comment]
This provides some infrastructure for #16026 as well, by the way, so I would greatly appreciate answers to the questions in the PR description so I can move forward with this (this PR is *not* abandoned).

**Comment by farteryhr** [comment]
apologize for repeating my comment in #13642, although it received no reply yet. but i believe we should make it consistent with `div` with different rounding/exact variants, instead of being ambiguous.

**Comment by farteryhr** [comment]
i think there's still some difference, exactly like how `@div` ones works.
like when encountering '0' or negative input, floating point `@log2` might follow the floating point flags or follow the forgiving convention that returns NaN, while `uintn` (for example) `@ulog2` might just raise an error, also (if everything goes like what i prefer) `@ulog2_exact` to error once the input has bit count other than 1, `@ulog2_ceil` to accept all input, etc.

**Comment by andrewrk** [comment]
Closing abandoned draft

**Comment by wooster0** [comment]
It wasn't abandoned. This is in the description:

> Figure out if vectors of integers are desired (are they?)

I was simply waiting to get a yes or no on this so I can continue. It's not specified in the original issue.

Though the bit rot is probably so bad at this point that it makes sense to close anyway

**Comment by andrewrk** [comment]
You're asking if `@log2` is intended to support vectors? Yes, all the mathematical builtins are intended to support vectors.

**Pull request closed without merging**
