### PR TITLE
Sema: do not immediately destroy failed generic instantiation

### PR DESCRIPTION
**Pull request by Vexu**
I'm not sure how correct this is (especially note the added TODO) so a thorough review is needed.

### CODE REVIEW

**Comment by ifreund** [comment]
I hit the bug this fixes while upgrading tigerbeetle to zig's master branch. I successfully used this PR branch to get the compile errors that were causing the failed generic instantiations.

Since fixing the errors tigerbeetle can build using master branch, though I wonder if I'll have to come back to this branch to get compile error messages in some cases in the future.

**Comment by ifreund** [comment]
Trying to compile a different component of tigerbeetle still triggers a crash on this branch: https://github.com/tigerbeetledb/tigerbeetle/tree/ifreund-zig-crash-repro

Using this PR at commit 4fbb9514d66cc20d518749703ce7d33731a84f69 and running `zig bulild simulator` yields the following stack trace:
```
~/projects/zig/stage3-debug-gif/bin/zig build simulator
Semantic Analysis [1569] thread 3846 panic: attempt to use null value
Analyzing /home/ifreund/projects/tigerbeetle/src/test/accounting/workload.zig: test/accounting/workload.zig:WorkloadType.Action
    > %590 = closure_get(%589) 
      %591 = field_val(%590, "create_accounts") 
      %592 = enum_to_int(%591) 
      %593 = as_node(@Zir.Inst.Ref.u8_type, %592) 
      %594 = closure_get(%589) 
      %595 = field_val(%594, "create_transfers") 
      %596 = enum_to_int(%595) 
      %597 = as_node(@Zir.Inst.Ref.u8_type, %596) 
      %598 = closure_get(%589) 
      %599 = field_val(%598, "lookup_accounts") 
      %600 = enum_to_int(%599) 
      %601 = as_node(@Zir.Inst.Ref.u8_type, %600) 
      %602 = closure_get(%589) 
      %603 = field_val(%602, "lookup_transfers") 
      %604 = enum_to_int(%603) 
      %605 = as_node(@Zir.Inst.Ref.u8_type, %604) 
      %606 = break_inline(%588, @Zir.Inst.Ref.void_value)
    For full context, use the command
      zig ast-check -t /home/ifreund/projects/tigerbeetle/src/test/accounting/workload.zig

  in /home/ifreund/projects/tigerbeetle/src/test/accounting/workload.zig: test/accounting/workload.zig:WorkloadType
    > %588 = extended(enum_decl(dbg_var, {}, @Zir.Inst.Ref.u8_type, {%590..%606}, {
        create_accounts = %593,
        create_transfers = %597,
        lookup_accounts = %601,
        lookup_transfers = %605,
      }) 
  in /home/ifreund/projects/tigerbeetle/src/simulator.zig: simulator.zig:Workload
    > %69 = call(.compile_time, %67, [
        {%70, %71},
      ]) 
  in /home/ifreund/projects/tigerbeetle/src/simulator.zig: simulator.zig:main
    > %667 = decl_val("Workload") 
  in /home/ifreund/projects/zig/stage3-debug-gif/lib/zig/std/start.zig: start.zig:callMain
    > %2530 = is_non_err(%2529) 
  in /home/ifreund/projects/zig/stage3-debug-gif/lib/zig/std/start.zig: start.zig:callMain
    > %2532 = block({%2526..%2531}) 
  in /home/ifreund/projects/zig/stage3-debug-gif/lib/zig/std/start.zig: start.zig:callMain
    > %2449 = switch_block(%2447,
        else => {%2642..%2645},
        %2451 => {%2452..%2461},
        %2463 => {%2464..%2478},
        %2481 => {%2479..%2520},
        %2522 => {%2523..%2641}) 
  in /home/ifreund/projects/zig/stage3-debug-gif/lib/zig/std/start.zig: start.zig:initEventLoopAndCallMain
    > %2207 = builtin_call(%2205, %2206, @Zir.Inst.Ref.empty_struct) 
  in /home/ifreund/projects/zig/stage3-debug-gif/lib/zig/std/start.zig: start.zig:callMainWithArgs
    > %1911 = call(.auto, %1909, []) 
  in /home/ifreund/projects/zig/stage3-debug-gif/lib/zig/std/start.zig: start.zig:posixCallMainAndExit
    > %1783 = builtin_call(%1780, %1781, %1782) 
  in /home/ifreund/projects/zig/stage3-debug-gif/lib/zig/std/start.zig: start.zig:posixCallMainAndExit
    > %1775 = call(nodiscard .auto, %1773, [
        {%1776..%1784},
      ]) 

n/home/ifreund/projects/zig/src/Sema.zig:14064:9: 0x3d23040 in zirClosureGet (zig)
                if (offset_int == 0) return ptr;
        ^
/home/ifreund/projects/zig/src/Sema.zig:728:68: 0x3b4e28e in analyzeBodyInner (zig)
    var orig_captures: usize = parent_capture_scope.captures.count();
                                                                   ^
/home/ifreund/projects/zig/src/Sema.zig:611:30: 0x3b4c728 in analyzeBody (zig)
    sema.* = undefined;
                             ^
/home/ifreund/projects/zig/src/Sema.zig:2633:33: 0x3da5132 in zirEnumDecl (zig)
        .fields = .{},
                                ^
/home/ifreund/projects/zig/src/Sema.zig:926:67: 0x3b57bc0 in analyzeBodyInner (zig)
            .add       => try sema.zirArithmetic(block, inst, .add),
                                                                  ^
/home/ifreund/projects/zig/src/Sema.zig:611:30: 0x3b4c728 in analyzeBody (zig)
    sema.* = undefined;
                             ^
/home/ifreund/projects/zig/src/Sema.zig:6173:33: 0x3ff041d in analyzeCall (zig)
            func,
                                ^
/home/ifreund/projects/zig/src/Sema.zig:5711:28: 0x3d22cf6 in zirCall (zig)
    });
                           ^
/home/ifreund/projects/zig/src/Sema.zig:727:62: 0x3b4e1b0 in analyzeBodyInner (zig)

                                                             ^
/home/ifreund/projects/zig/src/Sema.zig:628:45: 0x39af0e8 in analyzeBodyBreak (zig)
    // that we need to break from an outer block. In such case we
                                            ^
/home/ifreund/projects/zig/src/Module.zig:4580:50: 0x39ab64c in semaDecl (zig)
    var sema: Sema = .{
                                                 ^
/home/ifreund/projects/zig/src/Module.zig:4205:38: 0x378ae58 in ensureDeclAnalyzed (zig)
    defer tracy.end();
                                     ^
/home/ifreund/projects/zig/src/Sema.zig:26439:32: 0x4029d27 in ensureDeclAnalyzed (zig)
                const limbs = try sema.arena.alloc(std.math.big.Limb, 2);
                               ^
/home/ifreund/projects/zig/src/Sema.zig:26481:32: 0x3de1044 in analyzeDeclRef (zig)
    inst_src: LazySrcLoc,
                               ^
/home/ifreund/projects/zig/src/Sema.zig:26409:45: 0x3ff7f34 in analyzeDeclVal (zig)
    try sema.requireRuntimeBlock(block, inst_src, null);
                                            ^
/home/ifreund/projects/zig/src/Sema.zig:5452:31: 0x3d26631 in zirDeclVal (zig)
    const inst_data = sema.code.instructions.items(.data)[inst].dbg_stmt;
                              ^
/home/ifreund/projects/zig/src/Sema.zig:737:65: 0x3b4ead9 in analyzeBodyInner (zig)
    // the loop. The only way to break out of the loop is with a `noreturn`
                                                                ^
/home/ifreund/projects/zig/src/Sema.zig:611:30: 0x3b4c728 in analyzeBody (zig)
    sema.* = undefined;
                             ^
/home/ifreund/projects/zig/src/Module.zig:5592:21: 0x3997270 in analyzeFnBody (zig)
                const str_tok = sema.code.instructions.items(.data)[inst].str_tok;
                    ^
/home/ifreund/projects/zig/src/Module.zig:4291:40: 0x3789cc8 in ensureFuncBodyAnalyzed (zig)
                    .outdated => continue, // already queued for update
                                       ^
/home/ifreund/projects/zig/src/Sema.zig:26450:36: 0x4107fff in ensureFuncBodyAnalyzed (zig)
            .signed => {
                                   ^
/home/ifreund/projects/zig/src/Sema.zig:28575:40: 0x3eaabd7 in resolveInferredErrorSet (zig)
                            const cand_elem_ty = cand_info.pointee_type.childType();
                                       ^
/home/ifreund/projects/zig/src/Sema.zig:26729:49: 0x3ddbee7 in analyzeIsNonErrComptimeOnly (zig)
    const field_count = inst_ty.structFieldCount();
                                                ^
/home/ifreund/projects/zig/src/Sema.zig:26756:56: 0x40037d4 in analyzeIsNonErr (zig)
    const init = try sema.structFieldVal(block, inst_src, inst, field_name, inst_src, inst_ty);
                                                       ^
/home/ifreund/projects/zig/src/Sema.zig:15341:53: 0x3d31fdc in zirIsNonErr (zig)
            const union_field_ty = t: {
                                                    ^
/home/ifreund/projects/zig/src/Sema.zig:770:66: 0x3b50789 in analyzeBodyInner (zig)
            .bool_not                     => try sema.zirBoolNot(block, inst),
                                                                 ^
/home/ifreund/projects/zig/src/Sema.zig:4972:34: 0x40243f2 in resolveBlockBody (zig)
    ) catch |err| switch (err) {
                                 ^
/home/ifreund/projects/zig/src/Sema.zig:4955:33: 0x3dd74d5 in zirBlock (zig)

                                ^
/home/ifreund/projects/zig/src/Sema.zig:1250:69: 0x3b5d2f8 in analyzeBodyInner (zig)
                if (block.is_comptime) {
                                                                    ^
/home/ifreund/projects/zig/src/Sema.zig:4972:34: 0x40243f2 in resolveBlockBody (zig)
    ) catch |err| switch (err) {
                                 ^
/home/ifreund/projects/zig/src/Sema.zig:9922:49: 0x3d41d55 in zirSwitchBlock (zig)
                        block,
                                                ^
/home/ifreund/projects/zig/src/Sema.zig:792:69: 0x3b51ab3 in analyzeBodyInner (zig)
            .enum_literal                 => try sema.zirEnumLiteral(block, inst),
                                                                    ^
/home/ifreund/projects/zig/src/Sema.zig:611:30: 0x3b4c728 in analyzeBody (zig)
    sema.* = undefined;
                             ^
/home/ifreund/projects/zig/src/Sema.zig:6173:33: 0x3ff041d in analyzeCall (zig)
            func,
                                ^
/home/ifreund/projects/zig/src/Sema.zig:19838:28: 0x3d7b048 in zirBuiltinCall (zig)
    } else ptr_src;
                           ^
/home/ifreund/projects/zig/src/Sema.zig:848:69: 0x3b54ba6 in analyzeBodyInner (zig)
            .size_of                      => try sema.zirSizeOf(block, inst),
                                                                    ^
/home/ifreund/projects/zig/src/Sema.zig:611:30: 0x3b4c728 in analyzeBody (zig)
    sema.* = undefined;
                             ^
/home/ifreund/projects/zig/src/Sema.zig:6173:33: 0x3ff041d in analyzeCall (zig)
            func,
                                ^
/home/ifreund/projects/zig/src/Sema.zig:5711:28: 0x3d22cf6 in zirCall (zig)
    });
                           ^
/home/ifreund/projects/zig/src/Sema.zig:727:62: 0x3b4e1b0 in analyzeBodyInner (zig)

                                                             ^
/home/ifreund/projects/zig/src/Sema.zig:611:30: 0x3b4c728 in analyzeBody (zig)
    sema.* = undefined;
                             ^
/home/ifreund/projects/zig/src/Sema.zig:6173:33: 0x3ff041d in analyzeCall (zig)
            func,
                                ^
/home/ifreund/projects/zig/src/Sema.zig:19838:28: 0x3d7b048 in zirBuiltinCall (zig)
    } else ptr_src;
                           ^
/home/ifreund/projects/zig/src/Sema.zig:848:69: 0x3b54ba6 in analyzeBodyInner (zig)
            .size_of                      => try sema.zirSizeOf(block, inst),
                                                                    ^
/home/ifreund/projects/zig/src/Sema.zig:628:45: 0x39af0e8 in analyzeBodyBreak (zig)
    // that we need to break from an outer block. In such case we
                                            ^
/home/ifreund/projects/zig/src/Sema.zig:593:50: 0x3fe7f25 in resolveBody (zig)

                                                 ^
/home/ifreund/projects/zig/src/Sema.zig:5704:46: 0x3d229c7 in zirCall (zig)

                                             ^
/home/ifreund/projects/zig/src/Sema.zig:727:62: 0x3b4e1b0 in analyzeBodyInner (zig)

                                                             ^
/home/ifreund/projects/zig/src/Sema.zig:611:30: 0x3b4c728 in analyzeBody (zig)
    sema.* = undefined;
                             ^
/home/ifreund/projects/zig/src/Module.zig:5592:21: 0x3997270 in analyzeFnBody (zig)
                const str_tok = sema.code.instructions.items(.data)[inst].str_tok;
                    ^
/home/ifreund/projects/zig/src/Module.zig:4291:40: 0x3789cc8 in ensureFuncBodyAnalyzed (zig)
                    .outdated => continue, // already queued for update
                                       ^
/home/ifreund/projects/zig/src/Compilation.zig:3047:42: 0x3788183 in processOneJob (zig)

                                         ^
/home/ifreund/projects/zig/src/Compilation.zig:2985:30: 0x367643e in performAllTheWork (zig)
        mod.sema_prog_node = main_progress_node.start("Semantic Analysis", 0);
                             ^
/home/ifreund/projects/zig/src/Compilation.zig:2325:31: 0x3672cdd in update (zig)

                              ^
/home/ifreund/projects/zig/src/main.zig:3376:20: 0x369ddc6 in updateModule (zig)
                _ = try cache_dir.updateFile(src_pdb_path, cwd, dst_pdb_path, .{});
                   ^
/home/ifreund/projects/zig/src/main.zig:3061:17: 0x341e23f in buildOutputType (zig)
        try comp.makeBinFileExecutable();
                ^
/home/ifreund/projects/zig/src/main.zig:230:31: 0x33f7916 in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .{ .build = .Exe });
                              ^
/home/ifreund/projects/zig/src/main.zig:174:20: 0x33f7020 in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/home/ifreund/projects/zig/build-gif/stage3/lib/zig/std/start.zig:578:37: 0x33f9551 in main (zig)
            const result = root.main() catch |err| {
                                    ^
error: simulator...
error: The following command terminated unexpectedly:
/home/ifreund/projects/zig/stage3-debug-gif/bin/zig build-exe /home/ifreund/projects/tigerbeetle/src/simulator.zig -OReleaseSafe --cache-dir /home/ifreund/projects/tigerbeetle/zig-cache --global-cache-dir /home/ifreund/.cache/zig --name simulator -fno-omit-frame-pointer --enable-cache 
error: the following build command failed with exit code 6:
/home/ifreund/projects/tigerbeetle/zig-cache/o/b575c815d4dc5afd80865427de55db58/build /home/ifreund/projects/zig/stage3-debug-gif/bin/zig /home/ifreund/projects/tigerbeetle /home/ifreund/projects/tigerbeetle/zig-cache /home/ifreund/.cache/zig simulator
```

**Comment by Vexu** [comment]
This patch fixes #12927 and #12765 individually but causes UAF when they're put together:
```diff
diff --git a/src/Sema.zig b/src/Sema.zig
index a1c7fa7b9..f834be15d 100644
--- a/src/Sema.zig
+++ b/src/Sema.zig
@@ -6927,6 +6927,14 @@ fn instantiateGenericCall(
         const src_decl = mod.declPtr(src_decl_index);
         const new_decl_index = try mod.allocateNewDecl(namespace, fn_owner_decl.src_node, src_decl.src_scope);
         errdefer mod.destroyDecl(new_decl_index);
+        errdefer if (mod.failed_decls.fetchSwapRemove(new_decl_index)) |kv| {
+            const err_gop = mod.failed_decls.getOrPutAssumeCapacity(sema.owner_decl_index);
+            if (!err_gop.found_existing) {
+                err_gop.value_ptr.* = kv.value;
+            } else {
+                kv.value.destroy(mod.gpa);
+            }
+        };
         const new_decl = mod.declPtr(new_decl_index);
         // TODO better names for generic function instantiations
         const decl_name = try std.fmt.allocPrintZ(gpa, "{s}__anon_{d}", .{
```

It might still be worth it since the mitigation doesn't catch #12765

**Comment by Vexu** [comment]
Looks like either the new CI doesn't check for memory leaks or they somehow disappeared by themselves.

**Review by andrewrk — APPROVED** [review]
I think this is the right move at the very least for now, and adding CI coverage memory leaks can come later.

**Pull request merged**
