### PR TITLE
fix #3237: resolve undefined symbol _DllMainCRTStartup

### LINKED ISSUE #3237: Using Zig as C compiler for a shared library leads to undefined symbol: _DllMainCRTStartup
The command: `zig build-lib --c-source test.c --library c -dynamic -target x86_64-windows-gnu` leads to `lld: error: <root>: undefined symbol: _DllMainCRTStartup` error. Compilation of static library seems to work fine.

### PR DESCRIPTION
**Pull request by zhaozg**

### CODE REVIEW

**Comment by LemonBoy** [comment]
The change is technically correct (the renaming is done by lld's [mingw driver](https://github.com/llvm/llvm-project/blob/606a734755d1fb6c35a17680d0c251f834b79334/lld/MinGW/Driver.cpp#L209) that we're not using) but the correction should only be performed for `i386` targets, like it's done a few line above the code you changed.

**Comment by LemonBoy** [comment]
Ok, looking at clang's [driver](https://github.com/llvm/llvm-project/blob/master/clang/lib/Driver/ToolChains/CrossWindows.cpp#L116-L137) suggests that the renaming is something we want, but the logic must take into account the x86 name mangling exception.

A small excerpt from [this LLVM ticket](https://reviews.llvm.org/D37710) explains why the rename is needed:
> To add to the confusion, the DLL entry point in MSVC is by default named _DllMainCRTStartup (which after i386 mangling ends up as __DllMainCRTStartup@12. In MinGW (and as in the defaults in the clang MinGW frontend), the DLL entry point is named DllMainCRTStartup which on i386 ends up as _DllMainCRTStartup@12.

**Comment by zhaozg** [comment]
I tried `try argv.append("-ALTERNATENAME:__DllMainCRTStartup@12=DllMainCRTStartup");`, but build for i386-windows-gnu not works. the error message is  `lld: error: <root>: undefined symbol: __DllMainCRTStartup@12`

**Comment by LemonBoy** [comment]
First things first, the correct invocation is `-ALTERNATENAME:__DllMainCRTStartup@12=_DllMainCRTStartup@12` because `ALTERNATENAME` works with raw symbol names and you still have to take into account the x86 decoration.

Please read the links I've posted, you can find there all the infos needed to finalize this patch.

The problem here is: MinGW defines its DLL entry point as `DllMainCRTStartup` while MSVC defines it as `_DllMainCRTStartup`.
We get the following symbols:

| Symbol      | i386 | other (x64, ARM, ...) |
| - | - | - |
| DllMainCRTStartup (MinGW)      | _DllMainCRTStartup@12  | DllMainCRTStartup |
| _DllMainCRTStartup (MSVC) | __DllMainCRTStartup@12 | _DllMainCRTStartup |

What this patch should do is trying to sort out this mess and have the linker pick the correct symbol when targeting either the MSVC abi or the GNU one.

Keep in mind that lld uses the following logic when `-DLL` is passed in:
```C
      StringRef s = (config->machine == I386) ? "__DllMainCRTStartup@12"
                                              : "_DllMainCRTStartup";
```
The impedance mismatch can be traced back to LLD preference for MSVC names while `i386-windows-gnu` (or `x86_64-windows-gnu`) build an link a crt0 that doesn't follow the same naming convention.

**Comment by zhaozg** [comment]
Thanks your guidelines.

**Comment by andrewrk** [comment]
Thanks @zhaozg & @LemonBoy

**Pull request merged**
