### PR TITLE
std.debug: detect general protection faults on x86_64-linux

### PR DESCRIPTION
**Pull request by wooster0**
```zig
const std = @import("std");

pub fn main() !void {
	var addr: *u8 = @ptrFromInt(0xaaaaaaaaaaaaaaaa);
	addr.* = 1;
}
```

On x86_64-linux:

Before:
```
$ zig run x.zig
Segmentation fault at address 0x0
/home/wooster/Desktop/zig/x.zig:5:5: 0x21d887 in main (x)
    addr.* = 1;
    ^
/home/wooster/Desktop/zig-linux-x86_64/lib/std/start.zig:583:37: 0x21d847 in posixCallMainAndExit (x)
            const result = root.main() catch |err| {
                                    ^
/home/wooster/Desktop/zig-linux-x86_64/lib/std/start.zig:251:5: 0x21d371 in _start (x)
    asm volatile (switch (native_arch) {
    ^
???:?:?: 0x0 in ??? (???)
Aborted (core dumped)
```

After:
```
$ zig run x.zig --zig-lib-dir lib
General protection exception
/home/wooster/Desktop/zig/x.zig:5:5: 0x21d907 in main (x)
    addr.* = 1;
    ^
/home/wooster/Desktop/zig/lib/std/start.zig:583:37: 0x21d8c7 in posixCallMainAndExit (x)
            const result = root.main() catch |err| {
                                    ^
/home/wooster/Desktop/zig/lib/std/start.zig:251:5: 0x21d3f1 in _start (x)
    asm volatile (switch (native_arch) {
    ^
???:?:?: 0x0 in ??? (???)
Aborted (core dumped)
```

As @IntegratedQuantum pointed out in <https://github.com/ziglang/zig/issues/17745#issuecomment-1783815386>, it seems that if `code` of the `siginfo_t` instance is a certain value (128), you are able to distinguish between a general protection exception and a segmentation fault.

This does not seem to be documented on `man sigaction`:
```
The following values can be placed in si_code for a SIGSEGV signal:

           SEGV_MAPERR
                  Address not mapped to object.

           SEGV_ACCERR
                  Invalid permissions for mapped object.

           SEGV_BNDERR (since Linux 3.19)
                  Failed address bound checks.

           SEGV_PKUERR (since Linux 4.6)
                  Access was denied by memory protection keys.  See pkeys(7).  The protection key which applied to this access is available via si_pkey.
```
(those constants are 1, 2, 3, and 4; none of them are the 128)

I can't find a lot of documentation about this but it seems to work consistently for me on x86_64-linux. Here is a gist which provides additional evidence that this is a reliable way of checking for a general protection fault: https://gist.github.com/ytoshima/5682393 (read comment in first line)

See also: https://stackoverflow.com/questions/64309366/why-is-the-segfault-address-null-when-accessing-memory-that-has-any-of-the-16-mo

This only seems to affect x86_64 and on 32-bit x86 this does not seem to be a problem.

Helps with #17745 but doesn't close it because the issue still exists on Windows and other POSIX OSs.

I also limited this to x86_64-linux for now because that's the only platform where I tested it. Might work on more POSIX OSs.

### CODE REVIEW

**Comment by rootbeer** [comment]
Looks like a reasonable improvement to me.  I did find another StackExchange answer with confirming details: https://unix.stackexchange.com/a/71268/10992.

Here's the kernel source that sets SI_KERNEL in si_info: https://github.com/torvalds/linux/blob/2af9b20dbb39f6ebf9b9b6c090271594627d818e/kernel/signal.c#L1674  I believe that function (`force_sig`) gets called from the [x86 GP trap handler](https://github.com/torvalds/linux/blob/2af9b20dbb39f6ebf9b9b6c090271594627d818e/arch/x86/kernel/traps.c#L665-L674) via  [gp_user_force_sig_segv](https://github.com/torvalds/linux/blob/2af9b20dbb39f6ebf9b9b6c090271594627d818e/arch/x86/kernel/traps.c#L633-L639).  So this means other force_sig() calls might manifest in a similar way in userspace.  It does seem reasonable to assume that if `SI_KERNEL` is set, there are no other details in the `siginfo_t` worth printing.

As an aside, to reproduce on 32-bit, you might need 32-bit hardware.  On a 64-bit CPU, the mapping of the full 4GB address space for a 32-bit process is defined, I think.  In some 32-bit Linux configurations the top 1GB is unmapped and might trigger this sort of fault?

**Comment by wooster0** [comment]
Great, that confirms that at least this way of detecting a general protection fault on x86_64 is reliable on Linux. I don't have 32-bit x86 hardware available but I think I briefly tried it with an emulator and it was able to print out 0xffffffff just fine. This could still be extended in the future if I'm wrong anyway.

**Comment by Jarred-Sumner** [comment]
Can the error message mention that the address is unavailable? At first read, I thought this was removing the address (which would make debugging memory issues harder in Zig)

Something like

> General protection exception (address unavailable)

**Comment by wooster0** [comment]
Yup, I understand that confusion and I was going to do that but I read that a general protection fault/exception can also happen in situations where there is no memory address involved:

> Anyway, many possible causes of #GP don't arise from a memory access at all (e.g. trying to read or write control registers from unprivileged mode), in which case there is no faulting address.

So it'd be misleading to mention any address. I'm not sure if this applies to this specific case though. Maybe I can test it later.

**Comment by wooster0** [comment]
It should be less confusing now.

**Pull request merged**
