### PR TITLE
fix: Add error notes for method calls on double pointers

### LINKED ISSUE #19963: Bad error message for method call on double pointer
### Zig Version

0.13.0-dev.75+5c9eb4081

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

const Foo = struct {
  fn bar(self: *Foo) void {
    std.debug.print("{*}\n", .{self});
  }
};

pub fn main() !void {
  var gpa = std.heap.GeneralPurposeAllocator(.{}){};
  var map = std.AutoHashMap(*Foo, void).init(gpa.allocator());
  var key = Foo{};
  try map.put(&key, {});

  map.getKey(&key).?.*.bar(); // Does work
  map.getKey(&key).?.bar(); // Does work
  var it = map.keyIterator();
  while(it.next()) |foo| foo.*.bar(); // Does work
  while(it.next()) |foo| foo.bar(); // Doesn't work
}
```
…produces the following error:
```
code.zig:19:29: error: no field or member function named 'bar' in '*code.Foo'
  while(it.next()) |foo| foo.bar(); // Doesn't work
                         ~~~^~~~
```

### Expected Behavior

The code already says it all.

### PR DESCRIPTION
**Pull request by WillLillis**
Fixes the error message and adds a note when an attempt is made to invoke a method on a double pointer. Consider the following code:

```zig
const S = struct {
    fn b() void {}
};

export fn entry(a: **S) void {
    _ = a.b();
}
```

Before:

```shell
install
└─ install test_zig
   └─ zig build-exe test_zig Debug native 2 errors
src/main.zig:6:10: error: no field or member function named 'b' in '*main.S'
    _ = a.b();
        ~^~
```

After:

```shell
install
└─ install test_zig
   └─ zig build-exe test_zig Debug native 2 errors
src/main.zig:6:10: error: no field or member function named 'b' in '*main.S'
    _ = a.b();
        ~^~
src/main.zig:6:10: note: method invocation only supports up to one level of implicit pointer dereferencing
src/main.zig:6:10: note: use '.*' to dereference pointer
```

<details>
<Summary>Original revised messages </Summary>

```shell
install
└─ install test_zig
   └─ zig build-exe test_zig Debug native 2 errors
src/main.zig:6:10: error: type '*const **main.S' does not support member function invocation
    _ = a.b();
        ~^~
src/main.zig:6:10: note: consider dereferencing using '.*'
```
</details>

Closes #19963

### CODE REVIEW

**Comment by nektro** [comment]
notes tend to avoid action statements and not assume what was meant to happen.
i'd go with `note: method invocation only supports up to one level of implicit pointer defererencing`

**Comment by WillLillis** [comment]
> notes tend to avoid action statements and not assume what was meant to happen. i'd go with:
`note: method invocation only supports up to one level of implicit pointer defererencing`
`note: the dereference operator is '.*'`

Seems reasonable to me, thanks!

**Comment by Vexu** [comment]
You could also copy the existing `use '.*' to dereference pointer` error note.

**Comment by nektro** [comment]
fwiw the word "use" is also telling them what to do

**Comment by WillLillis** [comment]
> fwiw the word "use" is also telling them what to do

That's fair, although I'm sure there's a reason the existing note was written that way. I don't have a strong preference, and am happy to either 
- keep it as it stands in the PR currently
-   update both error notes to something more along the lines of `the dereference operator is '.*'`. 

For now I'll assume the maintainers prefer the latter unless stated otherwise.

**Comment by andrewrk** [comment]
Nice work, thanks!

**Pull request merged**
