### PR TITLE
std.Build.LazyPath: add sub path method

### LINKED ISSUE #16067: Feature Request: subpath derived FileSource in build.zig
Hey, I'd like to get a FileSource relative to another FileSource representing a directory in build.zig.

**Example Use-Case**:
I am unzipping some binaries and want to then install/link some subdirectories/files from the unzip.
Im trying to avoid implementing a custom Step and just use the builtin ones in a Makeish way.

```zig
    ...
    const fetch_skia_zip = b.addSystemCommand(.{ "curl", "-L", "-o" });
    const skia_zip = fetch_skia_zip.addOutputFileArg("skia-bin.zip");
    fetch_skia_zip.addArg(skia_zip_url);

    const unzip_skia_zip = b.addSystemCommand(.{"unzip"});
    unzip_skia_zip.step.dependOn(skia_zip);
    unzip_skia_zip.addFileSourceArg(skia_zip);
    unzip_skia_zip.addArg("-d");
    const skia_dir = unzip_skia_zip.addOutputFileArg("skia-bin");

    // want to:
    // install skia_dir/out/.../libskia.a and others
    // link above libskia.a with my zig project
    // add the skia_dir/include directory to the include for my zig project
    
    // would be awesome:
    const skia_include_dir = skia_dir.sub_path("include"); // This produces a new FileSource relative to skia_dir.
    ...
```

### PR DESCRIPTION
**Pull request by RossComputerGuy**
Closes #16067

This implements joined lazy paths (sub path)

### CODE REVIEW

**Comment by lacc97** [comment]
Wouldn't this make it really easy to dangle a LazyPath since the parent now requires a stable address?

**Comment by lacc97** [comment]
How about adding a nullable subpath field to the LazyPath?

Ideally something like
```
const LazyPath = struct {
    subpath: ?[]const u8 = null,
    data: union(enum) {
        // ...
    },
};
```
but for backwards compatibility maybe flip it around and add the subpath to the other union fields instead?

Actually, wouldn't this only be needed for the `generated*` cases? Since the other union fields implicitly support subpaths given their payloads are already a path.

**Comment by RossComputerGuy** [comment]
Probably, that sounds like it'll work the best. I'll try things out after work today.

**Comment by castholm** [comment]
Does this implementation implementation prevent something like `path.subPath("../../../../secret.txt")` from reaching outside of the root of the underlying path (`zig-cache/` for generated paths, the build root for regular paths, cwd for cwd-relative paths, etc.) in the same way that `LazyPath.dirname` does? Protecting against this was an important concern for `dirname`, so I figure it is just as important here.

You might want to take a look at the `dirname` issue https://github.com/ziglang/zig/issues/17411 and the  related PR that implemented it for inspiration. A few tests that verify the correctness of the behavior would probably be good as well.

**Comment by RossComputerGuy** [comment]
I don't think it does protect from that in its current state. I'll see if I can prevent escaping when I work on the changes tonight.

**Comment by RossComputerGuy** [comment]
Looking at how much would have to be changed, this is too much for now. Gonna close this PR, if someone wishes to finish this then I recommend some discussion on how this should be implemented so it doesn't break everything.

**Pull request closed without merging**
