### PR TITLE
stage2: add error for returning pointer to local variable

### LINKED ISSUE #2646: Add Compiler Error when returning pointer to stack variable
I'm new to zig and low level programming in general. Naturally when I encountered the code for setting up an allocater I tried to encapsulate it.

```
    var direct = std.heap.DirectAllocator.init();
    defer direct.deinit();
    var arena = std.heap.ArenaAllocator.init(&direct.allocator);
    defer arena.deinit();
```

I tried to (in retrospect naively) create a struct to take care of the repetition in my tests:

```
const MyStruct = struct {
    
    _alloc1: *std.heap.DirectAllocator,
    _alloc2: *std.heap.ArenaAllocator,

    pub fn init() !MyStruct {
        var direct = std.heap.DirectAllocator.init();
        var arena = std.heap.ArenaAllocator.init(&direct.allocator);
        return MyStruct{
            ._alloc1 = &direct,
            ._alloc2 = &arena,
        };
    }
    pub fn deinit(self: MyStruct) void {
        self._alloc2.deinit();
        self._alloc1.deinit();
    }
};
```

When using this I get a segfault though. 

In #zig @shawnl was helpful enough to explain the issue. The allocators are created on the stack of the `init` function and so the pointers to them that are set on the struct are invalid once the `init` function returns.

I am opening this issue because @shawnl claims there may be a way to figure out when such pointers are created and survive beyond the lifetime of the stack variables.

### PR DESCRIPTION
**Pull request by Vexu**
The check does not apply to inline functions and wont apply to functions called at comptime depending on #11152.
Most simple cases are caught but it is easy to bypass if needed.

Some cases might be too aggressive but they are easy to remove if deemed so.

Closes  #2646

### CODE REVIEW

**Comment by andrewrk** [comment]
One thing we need to do here is make sure we can manage to make the language specification compatible with this compile error.

cc @SpexGuy

**Comment by Jarred-Sumner** [comment]
> This is valid zig code

I do this currently when implementing a large interface for something function by function

Just so the code compiles even though the implementation is incomplete

**Comment by andrewrk** [comment]
@Jarred-Sumner why not instead `@panic("TODO")`? Or even just `unreachable`?

**Comment by andrewrk** [comment]
Closing since we currently have no workable plan to make this a legal compile error according to the lang spec. We can revisit this patch when dealing with #2646 which now has a link to this closed PR. **The next step towards landing this patch is coming up with a lang spec proposal that allows this compile error.** Please make such proposals as comments on #2646.

**Pull request closed without merging**
