### PR TITLE
stage2: disable some parts of `@Type`, add `@Int`, `@Float`, `@Array`

### PR DESCRIPTION
**Pull request by nektro**
Ref: #10710

### CODE REVIEW

**Comment by tauoverpi** [comment]
Wonder if `@Array` is needed given that it can be constructed using syntax alone `[len:sentinel]T` and `[len]T` which I assume is the desired notation.

**Comment by InKryption** [comment]
> Wonder if `@Array` is needed given that it can be constructed using syntax alone `[len:sentinel]T` and `[len]T` which I assume is the desired notation.

Could argue the same for pointers, but I would contend that nobody would want to, given the numerous permutations (`*align(4) const allowzero T` vs `[*:s]addrspace(.fs) volatile T`).
Just seems more simple to have a way to reify it, the same as the other syntactically constructible types here.

**Comment by tauoverpi** [comment]
The argument against pointer would likely be performance as otherwise it's [not too bad to implement](https://gist.github.com/tauoverpi/e8fc90d44659d86a0ac25dc7fb1081bc#file-type-zig-L58-L137) just a bit annoying.

**Comment by nektro** [comment]
unable to rebase without redoing the work because of too many blob changes

**Pull request closed without merging**
