### PR TITLE
std: add helper functions to std.zig.Ast for extracting data out of nodes

### PR DESCRIPTION
**Pull request by Techatrix**
When dealing with zig's ast you will often see this code pattern:
```zig
const container_field: Ast.full.ContainerField = switch (node_tags[node]) {
    .container_field_init => tree.containerFieldInit(node),
    .container_field_align => tree.containerFieldAlign(node),
    .container_field => tree.containerField(node),
    else => unreachable,
}
```
This PR adds some helper functions in std/zig/Ast.zig so that you can instead write:
```zig
const container_field: Ast.full.ContainerField = tree.fullContainerField(node).?;
```

### CODE REVIEW

**Comment by rohlem** [comment]
Good idea!
Just my 2 cents of bikeshedding, I don't think the new function names are an improvement (although I'm not familiar with the style currently used in the compiler code).

My own recommendation would be to suffix the functions constructing new objects `(type-)FromComponents` (rather than just `(type-)Components`),
and prefix the optional-returning functions `as(-Type)` or even `nodeAs(-Type)`, since it's semantically more of a cast-operation.
But let's see what others think.

**Review by Vexu — APPROVED** [review]

**Comment by Techatrix** [comment]
> How's the `zig fmt` performance before and after this change?

zig compiler version: 0.11.0-dev.1183+2b9478ce1 (taken from ziglang.org)

zig-old is 1878bdfbb127321d327ce3cfd8ec148959302b95
zig-new is 1878bdfbb127321d327ce3cfd8ec148959302b95 merged into this PR

`hyperfine -u millisecond -m 100 "./zig-old fmt src lib" "./zig-new fmt src lib"`
| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `./zig-old fmt src lib` | 1025.0 ± 2.9 | 1021.4 | 1041.7 | 1.00 ± 0.00 |
| `./zig-new fmt src lib` | 1023.7 ± 2.9 | 1019.0 | 1030.5 | 1.00 |

**Comment by Vexu** [comment]
> (taken from ziglang.org)

Did you compile locally with `-Dcpu=baseline` and using musl libc?

**Comment by Techatrix** [comment]
> > (taken from ziglang.org)
> 
> Did you compile locally with `-Dcpu=baseline` and using musl libc?

I used the pre build binary as the compiler. zig-old and zig-new are release builds without llvm. I didn't specify -Dcpu or -Dtarget so i think it defaults to x86-64_native_musl, right?

**Comment by Vexu** [comment]
I understood that as you having used the prebuilt binary for zig-old, if you built both yourself then it doesn't matter.

**Pull request merged**
