### PR TITLE
Fix GetFileInformationByHandle compile error

### PR DESCRIPTION
**Pull request by rdunnington**
The wrapper function was mistakenly referencing ntdll.zig when the actual function is declared in kernel32.zig.

### CODE REVIEW

**Comment by matu3ba** [comment]
LGTM. Eventually we'd like to use the Ntdll calls for file stuff, because this is highly unlikely to change. For file information this would be NtQueryInformationFile. see #1840.

**Comment by squeek502** [comment]
> Eventually we'd like to use the Ntdll calls for file stuff

This is already the case. `std.os.windows.GetFileInformationByHandle` is entirely unused in the std library (hence why this compile error was not found until now) and the only other related reference to `GetFileInformationByHandle` is one usage of `std.os.windows.kernel32.GetFileInformationByHandleEx` [here](https://github.com/ziglang/zig/blob/36d47dd1991f0ccd7a9673075624f09500cc415e/lib/std/os.zig#L3223).

**Comment by rdunnington** [comment]
Ok cool, is there anything else I can do to get this merged? Or just wait until an admin approves the PR? It's my first contribution so I'm not sure how this works.

**Comment by squeek502** [comment]
Nothing you need to do, just need to wait.

**Comment by andrewrk** [comment]
Thank you for the patch.

I think I would prefer to entirely remove this function from the standard library rather than fix it.

**Comment by rdunnington** [comment]
Ok, that makes sense given the std lib doesn't use this function at all.

**Comment by rdunnington** [comment]
Latest change delete the function so no one will make the same mistake again. :) I think #14814 should probably clean up the dangling GetFileInformationByHandleEx declaration in kernel32.zig as well.

**Pull request merged**
