### PR TITLE
ci: use static-qemu linux-x86_64 tarball and test against 4737

### PR DESCRIPTION
**Pull request by mikdusan**
no way this works the first time

### CODE REVIEW

**Comment by mikdusan** [comment]
@andrewrk, linux test failed but it got further than where #4737 test failed. Here's a compare:

#### failed test from `#4737`
```
876/906 behavior.vector.test "behavior-x86_64-linux-none-Debug-bare-multi vector bitwise not operator"...OK
877/906 behavior.vector.test "behavior-x86_64-linux-none-Debug-bare-multi vector shift operators"...expected 2147483648, found 2147483649
/home/vsts/work/1/s/lib/std/testing.zig:60:32: 0x27f31a in std.testing.expectEqual (test)
                std.debug.panic("expected {}, found {}", .{ expected, actual });
                               ^
/home/vsts/work/1/s/test/stage1/behavior/vector.zig:399:28: 0x2b17f9 in behavior.vector.S.doTheTestShift (test)
                expectEqual(x[i] << y[i], v);
                           ^
/home/vsts/work/1/s/test/stage1/behavior/vector.zig:423:31: 0x292857 in behavior.vector.S.doTheTest (test)
                doTheTestShift([_]u32{ 0, 2, 4, math.maxInt(u32) }, [_]u5{ 2, 0, 2, 31 });
                              ^
/home/vsts/work/1/s/test/stage1/behavior/vector.zig:453:16: 0x27672c in behavior.vector.test "behavior-x86_64-linux-none-Debug-bare-multi vector shift operators" (test)
    S.doTheTest();
               ^
/home/vsts/work/1/s/lib/std/special/test_runner.zig:47:28: 0x2fff45 in std.special.main (test)
        } else test_fn.func();
                           ^
/home/vsts/work/1/s/lib/std/start.zig:259:37: 0x2931cb in std.start.posixCallMainAndExit (test)
            const result = root.main() catch |err| {
                                    ^
/home/vsts/work/1/s/lib/std/start.zig:123:5: 0x292fff in std.start._start (test)
    @call(.{ .modifier = .never_inline }, posixCallMainAndExit, .{});
    ^
qemu: uncaught target signal 6 (Aborted) - core dumped

Tests failed. Use the following command to reproduce the failure:
/home/vsts/work/1/s/zig-cache/o/MjLL1O_klWlOABKSvnCafkBVLX5lo2P3zPq5PX1IyrBq0X2PR23ep6RK7mBo6mF9/test
The following command exited with error code 255:
/home/vsts/work/1/s/build/zig test /home/vsts/work/1/s/test/stage1/behavior.zig --test-name-prefix behavior-x86_64-linux-none-Debug-bare-multi  --cache-dir /home/vsts/work/1/s/zig-cache --name test -target x86_64-linux-none --test-cmd qemu-x86_64 --test-cmd-bin --override-lib-dir /home/vsts/work/1/s/lib 

Build failed. The following command failed:
/home/vsts/work/1/s/zig-cache/o/fk_U3HYEccOBjkQeYxj8YbGVl8erWS61FgR2LoPeH6gNJuvoOqjONVgCqqqrGOiF/build /home/vsts/work/1/s/build/zig /home/vsts/work/1/s /home/vsts/work/1/s/zig-cache test -Denable-qemu

##[error]Bash exited with code '1'.
Finishing: Build and test
```

#### failed test from this PR
```
879/909 behavior.vector.test "behavior-aarch64-linux-none-Debug-bare-multi vector bitwise not operator"...OK
880/909 behavior.vector.test "behavior-aarch64-linux-none-Debug-bare-multi vector shift operators"...expected 1, found 8388607
/home/vsts/work/1/s/lib/std/testing.zig:60:32: 0x2cda13 in std.testing.expectEqual (test)
                std.debug.panic("expected {}, found {}", .{ expected, actual });
                               ^
/home/vsts/work/1/s/test/stage1/behavior/vector.zig:395:28: 0x2b9323 in behavior.vector.S.doTheTestShift (test)
                expectEqual(x[i] >> y[i], v);
                           ^
/home/vsts/work/1/s/test/stage1/behavior/vector.zig:422:31: 0x29cb33 in behavior.vector.S.doTheTest (test)
                doTheTestShift([_]u24{ 0, 2, 4, math.maxInt(u24) }, [_]u5{ 2, 0, 2, 23 });
                              ^
/home/vsts/work/1/s/test/stage1/behavior/vector.zig:453:16: 0x27ed43 in behavior.vector.test "behavior-aarch64-linux-none-Debug-bare-multi vector shift operators" (test)
    S.doTheTest();
               ^
/home/vsts/work/1/s/lib/std/special/test_runner.zig:47:28: 0x2fc24b in std.special.main (test)
        } else test_fn.func();
                           ^
/home/vsts/work/1/s/lib/std/start.zig:253:37: 0x29d643 in std.start.posixCallMainAndExit (test)
            const result = root.main() catch |err| {
                                    ^
/home/vsts/work/1/s/lib/std/start.zig:123:5: 0x29d403 in std.start._start (test)
    @call(.{ .modifier = .never_inline }, posixCallMainAndExit, .{});
    ^
qemu: uncaught target signal 6 (Aborted) - core dumped

Tests failed. Use the following command to reproduce the failure:
/home/vsts/work/1/s/zig-cache/o/Zavok85FgUuSBRcIqdIerjUzhpsXAe8wX1dPiC6mWgIscSfzvv2j2FlLFJu7TZ_H/test
The following command exited with error code 255:
/home/vsts/work/1/s/build/zig test /home/vsts/work/1/s/test/stage1/behavior.zig --test-name-prefix behavior-aarch64-linux-none-Debug-bare-multi  --cache-dir /home/vsts/work/1/s/zig-cache --name test -target aarch64-linux-none --test-cmd qemu-aarch64 --test-cmd-bin --override-lib-dir /home/vsts/work/1/s/lib 

Build failed. The following command failed:
/home/vsts/work/1/s/zig-cache/o/NOV4yu2NHRvrN7W8PBs7bnrM3Uxui3MsiK06x9fwfQRRFA7O2wJv29wx35XvCYYC/build /home/vsts/work/1/s/build/zig /home/vsts/work/1/s /home/vsts/work/1/s/zig-cache test -Denable-qemu

##[error]Bash exited with code '1'.
Finishing: Build and test
```

**Comment by andrewrk** [comment]
Wow amazing! Sounds like it's time to try this against master branch, and if tests pass then merge that in, and @LemonBoy should be unblocked.

**Comment by mikdusan** [comment]
also drone CI just failed at exactly the same point, same unexpected result value:
```
880/909 behavior.vector.test "behavior-native-Debug-bare-multi vector shift operators"...expected 1, found 8388607
/drone/src/lib/std/testing.zig:60:32: 0x2cc3b7 in std.testing.expectEqual (test)
                std.debug.panic("expected {}, found {}", .{ expected, actual });
                               ^
/drone/src/test/stage1/behavior/vector.zig:395:28: 0x2b7beb in behavior.vector.S.doTheTestShift (test)
                expectEqual(x[i] >> y[i], v);
                           ^
/drone/src/test/stage1/behavior/vector.zig:422:31: 0x29b063 in behavior.vector.S.doTheTest (test)
                doTheTestShift([_]u24{ 0, 2, 4, math.maxInt(u24) }, [_]u5{ 2, 0, 2, 23 });
                              ^
/drone/src/test/stage1/behavior/vector.zig:453:16: 0x27d477 in behavior.vector.test "behavior-native-Debug-bare-multi vector shift operators" (test)
    S.doTheTest();
               ^
/drone/src/lib/std/special/test_runner.zig:47:28: 0x2fb1df in std.special.main (test)
        } else test_fn.func();
                           ^
/drone/src/lib/std/start.zig:253:37: 0x29bb9f in std.start.posixCallMainAndExit (test)
            const result = root.main() catch |err| {
                                    ^
/drone/src/lib/std/start.zig:123:5: 0x29b95f in std.start._start (test)
    @call(.{ .modifier = .never_inline }, posixCallMainAndExit, .{});
    ^

Tests failed. Use the following command to reproduce the failure:
/drone/src/zig-cache/o/9nxxtvYy8b0gXQr2qPFxK3YczV1LCowju_Ztw3b3C58UtISCgJdOql039yGniD_k/test
The following command exited with error code 255:
/drone/src/build/zig test /drone/src/test/stage1/behavior.zig --test-name-prefix behavior-native-Debug-bare-multi  --cache-dir /drone/src/zig-cache --name test --override-lib-dir /drone/src/lib 

Build failed. The following command failed:
/drone/src/zig-cache/o/ZMQP6E2LHRVR73HZsIUFd4NqQdB8lFzWKiY1SkpXpYOBJPx7xb2SJSl9Xg3Ufki_/build /drone/src/build/zig /drone/src /drone/src/zig-cache test -Dskip-release -Dskip-non-native
```

**Comment by mikdusan** [comment]
opened #4906 with cherry-pick c1581799f53e1bad644e38af826b271217a45fcc for merge to master

**Pull request closed without merging**
