### PR TITLE
Update glibc to 2.37

### LINKED ISSUE #12808: add support for targeting glibc 2.35
Previous release issue: https://github.com/ziglang/zig/issues/10308

[glibc 2.35 was released](https://sourceware.org/pipermail/libc-alpha/2022-February/136040.html). Time to follow the [update procedure](https://github.com/ziglang/zig/wiki/Updating-libc#glibc).

Major new features that may be relevant:

```
* All programs and the testsuite in glibc are now built as position independent
  executables (PIE) by default on toolchains and architectures that support it.
  Further, if the toolchain and architecture supports it, even static programs
  are built as PIE and the resultant glibc can be used to build static PIE
  executables.  A new option --disable-default-pie has been added to disable
  this behavior and get a non-PIE build.  This option replaces
  --enable-static-pie, which no longer has any effect on the build
  configuration.
```

```
* A symbolic link to the dynamic linker is now installed under
  /usr/bin/ld.so (or more precisely, '${bindir}/ld.so').
```

```
* Support for OpenRISC running on Linux has been added.  This port requires
  as least binutils 2.35, GCC 11, and Linux 5.4.  Currently only soft-float
  ABI is supported:

    - or1k-linux-gnu

  The OpenRISC ABI is 32-bit big-endian and uses 64-bit time (y2038 safe) and
  64-bit file offsets (LFS default).
```

### LINKED ISSUE #12809: add support for targeting glibc 2.36
Previous release issue: https://github.com/ziglang/zig/issues/12808

[glibc 2.36 was released](https://sourceware.org/pipermail/libc-alpha/2022-August/141193.html). Time to follow the [update procedure](https://github.com/ziglang/zig/wiki/Updating-libc#glibc).

Major new features that may be relevant:

```
* Support for DT_RELR relative relocation format has been added to
  glibc.  This is a new ELF dynamic tag that improves the size of
  relative relocations in shared object files and position independent
  executables (PIE).  DT_RELR generation requires linker support for
  -z pack-relative-relocs option, which is supported for some targets
  in recent binutils versions.  Lazy binding doesn't apply to DT_RELR.
```

```
* Support for LoongArch running on Linux has been added.  This port requires
  as least binutils 2.38, GCC 12, and Linux 5.19.  Currently only hard-float
  ABI is supported:

    - loongarch64-linux-gnu

  The LoongArch ABI is 64-bit little-endian.
```

### LINKED ISSUE #14798: add support for targeting glibc 2.37
Previous release issue: https://github.com/ziglang/zig/issues/12809

[glibc 2.37 was released](https://sourceware.org/pipermail/libc-alpha/2023-February/145190.html). Time to follow the [update procedure](https://github.com/ziglang/zig/wiki/Updating-libc#glibc).

Major new features that may be relevant:

```
Deprecated and removed features, and other changes affecting compatibility:

* The dynamic linker no longer loads shared objects from the "tls"
  subdirectories on the library search path or the subdirectory that
  corresponds to the AT_PLATFORM system name, or employs the legacy AT_HWCAP
  search mechanism, which was deprecated in version 2.33.

### PR DESCRIPTION
**Pull request by The-King-of-Toasters**
Closes #12808
Closes #12809
Closes #14798

See also: ziglang/glibc-abi-tool#4.

### CODE REVIEW

**Comment by The-King-of-Toasters** [comment]
The process involves copying over all the new sources/headers, so the only benefit would be to bisect any build failures (which I'm probably going to have to do anyway judging by the CI...)

**Comment by motiejus** [comment]
For the sake of future maintainability please update `lib/libc/glibc/README.md` with the new commit hashes. Since this will likely be rebased, it's probably OK to do separately though.

Also, I find it easier to apply out-of-tree patches when they are separate commits instead of having a single larger one bundled. Up to you — but consider it.

**Comment by motiejus** [comment]
> Also, I find it easier to apply out-of-tree patches when they are separate commits instead of having a single larger one bundled. Up to you — but consider it.

I take it back. With commits like #15573 it would become a mess quickly.

**Comment by andrewrk** [comment]
Closing this for multiple reasons:
 * failing CI checks
 * no action in months
 * a core team member must do the glibc update process for security reasons

**Pull request closed without merging**
