### PR TITLE
std: add progress module

### PR DESCRIPTION
**Pull request by lun-4**
This is mosly a draft for #2865 as this is the first time I'm contributing to the standard library, ~~it follows the same api described in the issue.~~ (it does not, after suggestions) The implementation is simple since I'm not sure what we should display.

### CODE REVIEW

**Comment by SamTebbs33** [comment]
Nice work. It would be cool to be able to specify another measure of progress, other than always time.

**Comment by lnyaa** [comment]
I'm unsure how to approach "multiple thresholds until printing", because you could do:
 - only print after 200ms
 - print after 30 "items"
 - or both! or any other combination if we get any other threshold in the future

**Comment by SamTebbs33** [comment]
Perhaps the bar could take a callback that returns an integer representing how much progress has been made.

**Comment by lnyaa** [comment]
maybe something like this?

```zig
fn timeCheckCallback(node: *ProgressNode) bool {
    const cur_time = std.time.milliTimestamp();
    const delta = cur_time - node.timestamp;
    return delta >= config.milliseconds_until_print;
}

pub const Config = struct {
    milliseconds_until_print: usize = 200,
    suppress_output: bool = false,
    callback: fn (*ProgressNode) bool = timeCheckCallback,
};
```

the node would check if it should print itself with
```zig
        self.print_flag = config.callback(self);
```

the node already has information such as amount of completed and total items that the callback can use (or not)

**Comment by SamTebbs33** [comment]
Something like that, definitely. You could even remove all mentions of time in the file and let the user decide what the progress metric is, and add the callback as a field in the ProgressNode. Then when the user calls `update`, you call the callback and do the required printing based on the return value.

**Comment by lnyaa** [comment]
Putting the callback in `ProgressNode.init` sounds like it'd make the API cumbersome...

Unless we made `Config` be able to create the nodes with the given parameters as such...?

```zig
var config = std.progress.Config{...};
var node = config.createNode(...);
```

 I may be a bit confused.

**Comment by SamTebbs33** [comment]
What is the reason for making a `Config` struct in the first place? Can't everything be stored in the `ProgressNode` struct? On second thoughts, a callback shouldn't even be needed since the user could just pass the number of completed items to the update function. My ideal (very bare) implementation would be along the lines of:

```
const ProgressNode = struct {
    itemsCompleted: u32,
    fn update(self: *ProgressNode, itemsCompleted: u32) void {
        if (itemsCompleted > self.itemsCompleted)
            drawItems(itemsCompleted - self.itemsCompleted) // Draw more progress items
    }
}
```
This removes the need for any time tracking and keeps the measure of progress completely black-boxed from the update function.

**Comment by lnyaa** [comment]
I was mostly following the API described in the issue, but making it more general sounds like a good idea as well.

**Comment by lnyaa** [comment]
Wrote a bit to see how a general approach would look like in the first place, and the changes are:
 - remove a global `Config`, move to a `PrintConfig` that is inside `ProgressNode`
 - instead of timestamp/measuring how many completed items, it's responsibility of the user to set `PrintConfig.flag` to `true` when we're supposed to print-on-update().
 - if, in the future, we get color support, the user could disable those via a future `PrintConfig.display_colors`, or the user can supress all output with `PrintConfig.suppress`, maybe if the zig compiler gets a `--no-progress` flag, it could use that.

Would that be allright? I didn't understand how to have the "don't do anything but print based on X" behavior in your snippet, so I went with `PrintConfig`.

**Pull request closed without merging**
