### PR TITLE
Set `c_char` signedness based on the target

### PR DESCRIPTION
**Pull request by ehaas**

### CODE REVIEW

**Review by andrewrk — APPROVED** [review]
I'm sorry to do this to you but do you mind rebasing?

**Comment by ehaas** [comment]
Don't mind at all. Is a standalone test the right way to test this? I just realized those debug asserts won't trip in unsafe build modes.

**Comment by andrewrk** [comment]
Behavior test would be best, and you can use `std.testing.expect` instead of assertions.

**Comment by ehaas** [comment]
It actually ended up being easier to just recreate the PR instead of rebasing, since the bulk of the original was getting the `Module` into `Type.isSignedInt` as a parameter, which the intern pool change already took care of. I'm having some hardware issues so I'm not able to test locally - if the CI doesn't come up green I might need someone else to take it across the finish line.

**Comment by andrewrk** [comment]
No problem! I'll take it from here in either case.

**Pull request merged**
