### PR TITLE
Correct the isEmpty function

### LINKED ISSUE #2693: A new queue is not empty?
I'm using zig from the master branch. I encountered this problem when using `std.atomic.Queue` in my project (here a simple file to reproduce the issue):

```
const std = @import("std");

pub fn main() void {
    var q = std.atomic.Queue([]u8).init();

    if (!q.isEmpty())
        std.debug.warn("asdf");
}
```

```
$ zig build-exe test.zig
$ ./test
asdf
```

Am I doing something wrong?

### PR DESCRIPTION
**Pull request by joachimschmidt557**
Fixes #2693

A queue was previously considered empty when it wasn't empty and vice versa.

### CODE REVIEW

**Comment by andrewrk** [comment]
Looks good - would you mind adding test coverage? I believe they are in the same file at the bottom.

**Comment by joachimschmidt557** [comment]
Ok, I'll try to add that.

**Comment by joachimschmidt557** [comment]
Should I create a separate test or should I integrate the `isEmpty` function into the existing tests?

**Comment by andrewrk** [comment]
Up to you. Either is fine

**Comment by andrewrk** [comment]
Looks like your commits got kinda messed up, can you rebase them all into 1 commit?

**Comment by joachimschmidt557** [comment]
Yup, I will do that

**Comment by andrewrk** [comment]
There's still a "merge master into" commit here which I don't think is necessary for a patch this small. Can we just have 1 commit?

**Comment by joachimschmidt557** [comment]
Hmm, seems like a test is not passing, did I mess up my commits?

**Comment by andrewrk** [comment]
It's an issue with the Azure DevOps, not with your code. The tests passed on the non-macOS operating systems, and that's good enough for this patch. Thanks!

**Comment by joachimschmidt557** [comment]
No problem!

**Pull request merged**
