### PR TITLE
macho: add preliminary non-prealloc path to the linker

### LINKED ISSUE #9990: larger than expected macOS binaries
### Zig Version

0.8.1 and 0.9.0-dev.1433+4a76523b9

### Steps to Reproduce

mylib.c:

```c
#include <stdio.h>
#include <math.h>

int foobar (int n) {
  printf("Hello World");

  if (n <= 10) {
    return pow(2, n);
  } else {
    return pow(n, 2);
  }
}
```

build.zig:

```zig
const std = @import("std");

pub fn build(b: *std.build.Builder) void {
    const target = b.standardTargetOptions(.{});
    const mode = b.standardReleaseOptions();

    const lib = b.addSharedLibrary("mylib", "mylib.c", b.version(0, 0, 1));
    lib.linkLibC();
    lib.setTarget(target);
    lib.setBuildMode(mode);
    lib.install();
}
```

Finally, run `zig build -Drelease-fast -Dtarget=x86_64-macos`

### Expected Behavior

The shared library should work properly on macOS (for me it's macOS 10.13).

### Actual Behavior

I tested in zig 0.8.1 and 0.9.0-dev.1433+4a76523b9, and the issue is different is these two versions.

With zig 0.8.1, when I try to use the shared library in macOS, I got an error: `Symbol not found: dyld_stub_binder`.

With zig 0.9.0-dev.1433+4a76523b9, I can use the shared library in macOS without errors, but the shared library size is almost 40 times larger. (with zig 0.8.1, `libmylib.0.0.1.dylib` is 8.7KB; and with zig 0.9.0-dev.1433+4a76523b9, `libmylib.0.0.1.dylib` is 345KB)

### PR DESCRIPTION
**Pull request by kubkon**
The non-prealloc path is currently enabled for stage1 by default, and in the future, it might also apply to release builds if we decide not to have incremental updates then. What it means is that, when the linker uses this codepath, it doesn't preallocate segment and section sizes, much like it's done in any traditional linker.

The reason I reintroduced this is to minimize the binary size blow up that many have observed when building with stage1. With this PR, we now get the following binary size improvements (linking speed is largely the same for both codepaths):

_(everything measured on my M1 MBA)_
* __stage2 (with `-Dlog -Denable-llvm -Dlink-snapshot` flags)__
    * 17.5% size reduction from 237.8MB down to 196.1MB
* __multi-file small C program__
    * 86.8% size reduction from 378KB down to 49KB
* Andrew's __zig-sdl__ library
    * 17.4% size reduction from 292.6MB down to 241.6MB

Fixes #9990

### CODE REVIEW

**Comment by andrewrk** [comment]
Looks like this addresses #9990. Would you say it closes it?

**Comment by kubkon** [comment]
> Looks like this addresses #9990. Would you say it resolves it?

Nice one, well spotted! Let me link this issue as resolved by this PR. Thanks Andrew!

**Comment by andrewrk** [comment]
Possibly relevant to this, in a local branch I have this diff:

```diff
--- a/src/Compilation.zig
+++ b/src/Compilation.zig
@@ -69,6 +69,8 @@ failed_c_objects: std.AutoArrayHashMapUnmanaged(*CObject, *CObject.ErrorMsg) = .
 /// Miscellaneous things that can fail.
 misc_failures: std.AutoArrayHashMapUnmanaged(MiscTask, MiscError) = .{},
 
+cache_mode: CacheMode,
+
 keep_source_files_loaded: bool,
 use_clang: bool,
 sanitize_c: bool,
@@ -632,6 +634,8 @@ pub const ClangPreprocessorMode = enum {
 
 pub const SystemLib = link.SystemLib;
 
+pub const CacheMode = enum { incremental, whole };
+
 pub const InitOptions = struct {
     zig_lib_directory: Directory,
     local_cache_directory: Directory,
@@ -668,6 +672,7 @@ pub const InitOptions = struct {
     /// is externally modified - essentially anything other than zig-cache - then
     /// this flag would be set to disable this machinery to avoid false positives.
     disable_lld_caching: bool = false,
+    cache_mode: CacheMode = .incremental,
     object_format: ?std.Target.ObjectFormat = null,
     optimize_mode: std.builtin.Mode = .Debug,
     keep_source_files_loaded: bool = false,
```

This is actually part of a bug fix to #9439, as well as a compilation speed performance enhancement - idea being that for some compilations we actually want to opt out of incremental compilation and just cache the whole frickin thing. For example, there is no sense in incrementally building compiler-rt, which we build using the LLVM backend, using `-OReleaseFast`. With incremental compilation enabled, every compilation is waiting for LLVM to optimize the exact same compiler-rt LLVM module. Same with libc and other commonly shared files.

Anyway point being, I wanted to alert you to this addition because I get the sense that the linker code may benefit from observing this `cache_mode` setting.

**Comment by kubkon** [comment]
> Possibly relevant to this, in a local branch I have this diff:
> 
> ```diff
> --- a/src/Compilation.zig
> +++ b/src/Compilation.zig
> @@ -69,6 +69,8 @@ failed_c_objects: std.AutoArrayHashMapUnmanaged(*CObject, *CObject.ErrorMsg) = .
>  /// Miscellaneous things that can fail.
>  misc_failures: std.AutoArrayHashMapUnmanaged(MiscTask, MiscError) = .{},
>  
> +cache_mode: CacheMode,
> +
>  keep_source_files_loaded: bool,
>  use_clang: bool,
>  sanitize_c: bool,
> @@ -632,6 +634,8 @@ pub const ClangPreprocessorMode = enum {
>  
>  pub const SystemLib = link.SystemLib;
>  
> +pub const CacheMode = enum { incremental, whole };
> +
>  pub const InitOptions = struct {
>      zig_lib_directory: Directory,
>      local_cache_directory: Directory,
> @@ -668,6 +672,7 @@ pub const InitOptions = struct {
>      /// is externally modified - essentially anything other than zig-cache - then
>      /// this flag would be set to disable this machinery to avoid false positives.
>      disable_lld_caching: bool = false,
> +    cache_mode: CacheMode = .incremental,
>      object_format: ?std.Target.ObjectFormat = null,
>      optimize_mode: std.builtin.Mode = .Debug,
>      keep_source_files_loaded: bool = false,
> ```
> 
> This is actually part of a bug fix to #9439, as well as a compilation speed performance enhancement - idea being that for some compilations we actually want to opt out of incremental compilation and just cache the whole frickin thing. For example, there is no sense in incrementally building compiler-rt, which we build using the LLVM backend, using `-OReleaseFast`. With incremental compilation enabled, every compilation is waiting for LLVM to optimize the exact same compiler-rt LLVM module. Same with libc and other commonly shared files.
> 
> Anyway point being, I wanted to alert you to this upcoming addition because I get the sense that the linker code may benefit from observing this `cache_mode` setting.

Nice! That's going to be very relevant for disambiguating the two code paths in stage2 I think :-)

**Comment by kubkon** [comment]
Hmm, I don't think that failing aarch64 drone CI is my fault so I'm going to merge and if the failure persists on master, I'll try investigating what's up.

**Pull request merged**
