### PR TITLE
Faster tokenizer

### PR DESCRIPTION
**Pull request by RetroDev256**
Update the zig tokenizer to use labeled switch statements :)

The benchmarks (and binary size) speaks for itself:

image

### CODE REVIEW

**Comment by RetroDev256** [comment]
image
image

I may be wrong, but I don't think stage1 supports labeled switch statements. Is there something I should do about this?

**Comment by Rexicon226** [comment]
Run `zig update-zig1` locally and make it a commit. A core member will replace that commit when ready to merge.

**Comment by andrewrk** [comment]
Nice work!

Looks like the LLVM backend is having trouble lowering this on wasm32-wasi. Feel free to leave that to ZSF core team, we can take it from here.

**Comment by RetroDev256** [comment]
Imma push one more commit fixing a few minor details I forgot about then :)

**Comment by alexrp** [comment]
This needs a rebase after #21371.

**Comment by RetroDev256** [comment]
I'll get to it later today :)
#21371 made a few minor changes to the tokenizer, when converting the changes I'll want to make sure I don't mess up.

If time is a concern, feel free to give it a go earlier.

ETA: 6 hours

**Comment by RetroDev256** [comment]
Managed to fit in my lunch break :)

**Comment by andrewrk** [comment]
Thanks for the rebase!

**Comment by andrewrk** [comment]
I have rebased and force-pushed the branch to your fork and set to auto-merge. If my work here looks OK, please sit tight and this will be landed soon.

**Pull request merged**
