### PR TITLE
mem.order manual byte packing

### PR DESCRIPTION
**Pull request by fengb**
We can eek out some cycles by comparing u8 bytes in chunks ([benchmark source](https://github.com/fengb/mem-order)):

| | master | master<br> `safety=false` | packed | packed<br>`safety=false` |
|:-- | --:|  --:| --:| --:|
| debug | 8103 | 5189 | 7356 | 4717 |
| release-safe | 1432 | (!!) **15** | 594 | (!!) **25** |
| release-fast | 488 | 483 | 464 | 429 |
| release-small | 717 | 726 | 644 | 642 |

I have no idea why the release-safe version is so much faster...

Godbolt diff: https://godbolt.org/z/-N8WT8

### CODE REVIEW

**Comment by JesseRMeyer** [comment]
Just a hunch -- LLVM likes to aggressively (ahem, excessively) unroll loops.  So it may be putting a load on the instruction cache / decoder.

**Comment by fengb** [comment]
Fiddling with `@setRuntimeSafety`, I managed to convince the existing function to generate the very fast variant (51 ns) in release-safe and _only_ for release-safe.

Just to be spiteful, I set `@setRuntimeSafety(true)` for release-fast and it's ~35% faster.

I have no idea what's going on.

**Comment by fengb** [comment]
I'm inclined to believe the magic performance is due to LLVM somehow inlining everything. Once I force the execution path to go through an exported function, the performance is basically identical.

**Comment by JesseRMeyer** [comment]
Ah, maybe I shouldn't have deleted my comment.  Is LLVM unrolling all those loops in your benchmark code for release-safe?

**Comment by JesseRMeyer** [comment]
What if you force inline?

**Comment by fengb** [comment]
I'm trying to do an unbiased test so making sure it's never inlined is the ideal "worst case scenario", although if I can convince it to always inline that'd be even better.

My assembly skills aren't that great, and my attempts at inspecting the outputted function causes it to create the slow version.

**Comment by andrewrk** [comment]
Given that this is not strictly an improvement (15 => 25), and the areas it is improved are not large margins, and the mystery of release-safe mode, I'd like to leave the code as the simpler status quo.

**Comment by andrewrk** [comment]
Let's revisit closer to 1.0.

**Pull request closed without merging**
