### PR TITLE
🐛 std.fs.Dir.makePath: fix for libc systems

### PR DESCRIPTION
**Pull request by Jamim**
_Hello everyone,_

When I was working on updating **zig** to `0.13.0` on [Gentoo Linux](https://www.gentoo.org/), I found and fixed a bug in `std.fs.Dir.makePath`. Hope you'll find this fix useful.

The `fs.test.test.makepath relative walks` test reveals a malfunction in the `makePath` function when using the libc API.

Paths like `first/../second/..` are considered existing although some of their components might be missing.

<details><summary>zig build test-std (before the fix, truncated)</summary>
<p>

```
test-std
└─ run test std-x86_64-linux.4.19...6.5.7-gnu.2.28-x86_64-Debug-libc 2722/2760 passed, 1 failed, 37 skipped
error: 'fs.test.test.makepath relative walks' failed: /var/tmp/portage/dev-lang/zig-0.13.0/work/zig-0.13.0/lib/std/posix.zig:2875:19: 0x2b69826 in mkdiratZ (test)
        .EXIST => return error.PathAlreadyExists,
                  ^
/var/tmp/portage/dev-lang/zig-0.13.0/work/zig-0.13.0/lib/std/posix.zig:2833:9: 0x288120f in mkdirat (test)
        return mkdiratZ(dir_fd, &sub_dir_path_c, mode);
        ^
/var/tmp/portage/dev-lang/zig-0.13.0/work/zig-0.13.0/lib/std/fs/Dir.zig:1116:5: 0x240b4af in makeDir (test)
    try posix.mkdirat(self.fd, sub_path, default_mode);
    ^
/var/tmp/portage/dev-lang/zig-0.13.0/work/zig-0.13.0/lib/std/posix.zig:4356:19: 0x28a01b0 in fstatatZ (test)
        .NOENT => return error.FileNotFound,
                  ^
/var/tmp/portage/dev-lang/zig-0.13.0/work/zig-0.13.0/lib/std/posix.zig:4330:9: 0x240ba32 in fstatat (test)
        return fstatatZ(dirfd, &pathname_c, flags);
        ^
/var/tmp/portage/dev-lang/zig-0.13.0/work/zig-0.13.0/lib/std/fs/Dir.zig:2643:16: 0x21fcdfd in statFile (test)
    const st = try posix.fstatat(self.fd, sub_path, 0);
               ^
/var/tmp/portage/dev-lang/zig-0.13.0/work/zig-0.13.0/lib/std/fs/Dir.zig:1162:37: 0x21f5d78 in makePath (test)
                        else => |e| return e,
                                    ^
/var/tmp/portage/dev-lang/zig-0.13.0/work/zig-0.13.0/lib/std/fs/test.zig:1195:5: 0x2806241 in test.makepath relative walks (test)
    try tmp.dir.makePath(relPath);
    ^
```

</p>
</details> 

_Best regards!_

### CODE REVIEW

**Comment by Jamim** [comment]
_Hello @BratishkaErik,_

Would you mind reviewing this PR?

_Thanks in advance!_

**Comment by rootbeer** [comment]
Can you clarify the behavior you're seeing?  It seems odd to me that this test would fail on Gentoo, when this test should be running regularly on Linux as part of the Zig pre-checkin suite.  (And the test seems to be passing for me just fine on my Debian box.)

In particular when you say "Paths like first/../second/.. are considered existing although some of their components might be missing." do you know which parts in particular are problematic?  Is it the ".."?  I don't think any of the other components should exist because the test should be running in a clean temporary directory.

Its also very strange to `mkdir(x)` and get PathAlreadyExists and then do a `statFile(x)` and get a FileNotFound error.  This seems like it might be due to a race with another program messing with the same test directory?  (That shouldn't happen because of how the tests are run, I think.)

Finally, the comment you added implies the libc `mkdirat` always returns a PathAlreadyExists even if (some part of) the path does not exist?  If so, that seems like the problem, not this code?  (Especially if its just Gentoo?)

Which glibc version are you using on Gentoo?

**Comment by Jamim** [comment]
_Hello @rootbeer,_

I continued to investigate the issue and eventually figured out that the root cause was [a Gentoo sandbox bug](https://bugs.gentoo.org/921581#c10).
I've submitted a related fix here:
  - gentoo/sandbox#27

So I suppose this PR should be closed now.

_Thanks!_

**Comment by rootbeer** [comment]
Nice find in the sandbox!  Glad the Zig makepath tests are useful beyond Zig.  :)

**Pull request closed without merging**
