### PR TITLE
elf: add riscv eflag collisions

### PR DESCRIPTION
**Pull request by Rexicon226**
upstream of https://github.com/kubkon/zld/pull/151
cc @kubkon

### CODE REVIEW

**Review by kubkon — APPROVED** [review]
Looks great!

**Comment by andrewrk** [comment]
Can you change this instead to validate based on the Target? This will eliminate one shared data dependency making this check contention-free.

**Comment by Rexicon226** [comment]
> Can you change this instead to validate based on the Target? This will eliminate one shared data dependency making this check contention-free.

Could you clarify what you mean by "based on the Target"? Which target?

**Comment by alexrp** [comment]
The `std.Target` for the link job effectively encodes all the information needed to decide whether the eflags in an object are acceptable. So you could *probably* validate the eflags against that rather than against prior eflags seen in another object.

**Comment by Rexicon226** [comment]
Ah, I understand what you mean now. For `fabi` and `rve` I can see how that would work.

I wonder how we store whether any of the objects have `rvc` enabled without shared state?

**Comment by alexrp** [comment]
I see these possible scenarios:

* You compile some code with Zig using `c` and don't link in anything else. This is fine. Result has `rvc` set because the target CPU feature set does.
* You compile some code with Zig using `c` and link in objects that don't use `c`. This is fine. Result has `rvc` set because the target CPU feature set does.
* You compile some code with Zig using `c` and link in objects that use `c`. This is fine. Result has `rvc` set because the target CPU feature set does.
* You compile some code with Zig not using `c` and don't link in anything else. This is fine. Result doesn't have `rvc` set because the target CPU feature set doesn't.
* You compile some code with Zig not using `c` and link in objects that don't use `c`. This is fine. Result doesn't have `rvc` set because the target CPU feature set doesn't.
* You compile some code with Zig not using `c` and link in objects that use `c`. This is a link error.

I know there's also the case where Zig is only invoked to link objects together without compiling any code, but I don't *think* that actually changes anything in practice, because there's still a target in play for that use case.

Assuming I haven't missed anything here, the key takeaway is that, in all cases, it's appropriate to decide the `rvc` field's value based just on the target and nothing else.

**Comment by alexrp** [comment]
I guess it's conceivable that you could link some objects together that don't use `c` while specifying a target that has `c`, but then... if you don't actually want the result to have `rvc` set, just don't lie to the compiler? :sweat_smile: In pretty much every other area of the codebase, we assume that if you specify certain target properties, you actually mean it. So I think that's fine here too.

**Comment by Rexicon226** [comment]
Makes sense. I was raking my brain on how to do this for `tso`, until I realized that's just behind the `ztso` feature flag. I will make the PR for this tomorrow :)

**Pull request merged**
