### PR TITLE
ArrayList: remove unneeded overflow checks

### PR DESCRIPTION
**Pull request by erikarvstedt**
Context: https://github.com/ziglang/zig/issues/18413#issuecomment-1897510042

cc @andrewrk, @notcancername

### CODE REVIEW

**Comment by andrewrk** [comment]
Brilliant! Thank you.

**Comment by erikarvstedt** [comment]
どういたしまして :smiley:

**Comment by erikarvstedt** [comment]
The CI failure seems unrelated to these changes.

**Comment by andrewrk** [comment]
Indeed it is. Unfortunately I have other priorities than diagnosing that CI failure today

**Pull request merged**
