### PR TITLE
mem.sliceTo on C pointers should return an optional slice

### PR DESCRIPTION
**Pull request by daurnimator**
https://github.com/ziglang/zig/pull/8698/files#r632922210

Also makes the compile errors from `SliceTo` more consistent

### CODE REVIEW

**Review by ifreund — CHANGES_REQUESTED** [review]
I'm not 100% sure this makes sense with the current semantics of C pointers, if https://github.com/ziglang/zig/issues/6597 were accepted I would think otherwise.

If this is the way to go, I think we need to update `std.mem.span` to match this behavior, and you need to correct the doc comment for `std.mem.sliceTo()`.

**Comment by daurnimator** [comment]
> If this is the way to go, I think we need to update `std.mem.span()` to match this behavior,

hmm. I think I'd only like to do that if #6597 is accepted.



>  you need to correct the doc comment for `std.mem.sliceTo()`.

done.

**Comment by ifreund** [comment]
> hmm. I think I'd only like to do that if #6597 is accepted.

I think having consistent behavior between the two is pretty important, what's your reasoning here?

**Comment by daurnimator** [comment]
> I think having consistent behavior between the two is pretty important, what's your reasoning here?

`span` looks like it shouldn't accept C pointers at all; and users should instead be using `sliceTo`.
Rather than change it, I'd rather remove the `.C` branch entirely.

**Comment by andrewrk** [comment]
Please re-open against master branch with passing tests

**Pull request closed without merging**
