### PR TITLE
translate-c fixes

### PR DESCRIPTION
**Pull request by mlugg**
Okay, one of these is actually in `AstGen`, but I found it through `translate-c` emitting code which triggered this error.

See commit messages for details.

### CODE REVIEW

**Comment by wooster0** [comment]
``````
Consider this C macro:
```
```
``````
I think the C macro went missing

**Comment by mlugg** [comment]
Uhhh, that's... odd? No idea how I messed that up, sorry. Amending the commit now!

**Comment by andrewrk** [comment]
translate-c test cases are here: https://github.com/ziglang/zig/blob/master/test/run_translated_c.zig

if text comparison would be more handy instead of checking behavior, then https://github.com/ziglang/zig/blob/master/test/translate_c.zig

**Comment by mlugg** [comment]
`aarch64-linux-debug` failure is a random unrelated one (`BrokenPipe`)

**Pull request merged**
