### PR TITLE
Update glibc 2.32 attempt 2

### PR DESCRIPTION
**Pull request by Jan200101**
same as #6137 except this time without any regressions (I hope)
I went through the git diff and tried making sure everything required is commited this time

I am currently unsure about endianness.h and a.out.h since both seem to originally be for mips yet I have not encountered any issues because of this

I threw zig against [tinyraycaster](https://github.com/ssloy/tinyraycaster) and [simdjson](https://github.com/simdjson/simdjson) both of which ended up with a working binary and working shared object respectively (tests for simdjson failed for reasons beyond glibc)

### CODE REVIEW

**Comment by andrewrk** [comment]
Thanks for the follow-up! Can you share a little bit about what happened? Maybe the wiki can be improved to help future contributors in this regard?

**Comment by Jan200101** [comment]
I had simply forgotten to stage some files that were newly imported

**Comment by Jan200101** [comment]
I've gone ahead and compiled some more C++ and C projects with zig so I am going to assume everything is working as intended now

**Comment by andrewrk** [comment]
Thanks! I'm working on merging this now.

**Comment by Jan200101** [comment]
I have went ahead and ran tests using the newly suggested `enable-foreign-glibc` but also with `enable-qemu` and came through clean

**Comment by andrewrk** [comment]
OK I went through this process and `git status` shows me a different set of header files than this PR shows me. I'm seeing the process_headers tool regressed since glibc 2.31 because it does not give me the same set of header files for glibc 2.31 as we have in master branch. Did you do something extra that the wiki page does not mention to come up with this PR?

**Comment by andrewrk** [comment]
After fixing the bug in process_headers.zig (see eeadd55d15852b6bc67b459b452e83a8a8ba2933) and doing [the process](https://github.com/ziglang/zig/wiki/Updating-libc#glibc), I have this (as a diff from this PR):

```
On branch Jan200101-update/glibc-2.32-2
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    ../lib/libc/include/aarch64-linux-gnu/bits/floatn.h
	deleted:    ../lib/libc/include/aarch64_be-linux-gnu/bits/floatn.h
	deleted:    ../lib/libc/include/arm-linux-gnueabi/bits/semaphore.h
	deleted:    ../lib/libc/include/arm-linux-gnueabihf/bits/semaphore.h
	deleted:    ../lib/libc/include/armeb-linux-gnueabi/bits/semaphore.h
	deleted:    ../lib/libc/include/armeb-linux-gnueabihf/bits/semaphore.h
	modified:   ../lib/libc/include/generic-glibc/bits/a.out.h
	modified:   ../lib/libc/include/generic-glibc/bits/endianness.h
	modified:   ../lib/libc/include/generic-glibc/bits/environments.h
	modified:   ../lib/libc/include/generic-glibc/bits/epoll.h
	modified:   ../lib/libc/include/generic-glibc/bits/fcntl.h
	modified:   ../lib/libc/include/generic-glibc/bits/fenv.h
	modified:   ../lib/libc/include/generic-glibc/bits/floatn.h
	modified:   ../lib/libc/include/generic-glibc/bits/flt-eval-method.h
	modified:   ../lib/libc/include/generic-glibc/bits/fp-logb.h
	modified:   ../lib/libc/include/generic-glibc/bits/indirect-return.h
	modified:   ../lib/libc/include/generic-glibc/bits/ipctypes.h
	modified:   ../lib/libc/include/generic-glibc/bits/iscanonical.h
	modified:   ../lib/libc/include/generic-glibc/bits/link.h
	modified:   ../lib/libc/include/generic-glibc/bits/long-double.h
	modified:   ../lib/libc/include/generic-glibc/bits/math-vector.h
	modified:   ../lib/libc/include/generic-glibc/bits/mman.h
	modified:   ../lib/libc/include/generic-glibc/bits/procfs-id.h
	modified:   ../lib/libc/include/generic-glibc/bits/procfs.h
	modified:   ../lib/libc/include/generic-glibc/bits/pthreadtypes-arch.h
	modified:   ../lib/libc/include/generic-glibc/bits/setjmp.h
	modified:   ../lib/libc/include/generic-glibc/bits/sigcontext.h
	modified:   ../lib/libc/include/generic-glibc/bits/siginfo-arch.h
	modified:   ../lib/libc/include/generic-glibc/bits/stat.h
	modified:   ../lib/libc/include/generic-glibc/bits/struct_mutex.h
	modified:   ../lib/libc/include/generic-glibc/bits/struct_rwlock.h
	modified:   ../lib/libc/include/generic-glibc/bits/timesize.h
	modified:   ../lib/libc/include/generic-glibc/bits/types/struct_semid_ds.h
	modified:   ../lib/libc/include/generic-glibc/bits/typesizes.h
	modified:   ../lib/libc/include/generic-glibc/bits/wordsize.h
	modified:   ../lib/libc/include/generic-glibc/finclude/math-vector-fortran.h
	modified:   ../lib/libc/include/generic-glibc/fpu_control.h
	modified:   ../lib/libc/include/generic-glibc/gnu/lib-names.h
	modified:   ../lib/libc/include/generic-glibc/gnu/stubs.h
	modified:   ../lib/libc/include/generic-glibc/sys/elf.h
	modified:   ../lib/libc/include/generic-glibc/sys/ptrace.h
	modified:   ../lib/libc/include/generic-glibc/sys/ucontext.h
	modified:   ../lib/libc/include/generic-glibc/sys/user.h
	deleted:    ../lib/libc/include/i386-linux-gnu/bits/select.h
	deleted:    ../lib/libc/include/i386-linux-gnu/bits/semaphore.h
	deleted:    ../lib/libc/include/powerpc-linux-gnu/bits/semaphore.h
	deleted:    ../lib/libc/include/powerpc64-linux-gnu/bits/semaphore.h
	deleted:    ../lib/libc/include/powerpc64le-linux-gnu/bits/semaphore.h
	deleted:    ../lib/libc/include/riscv64-linux-gnu/bits/floatn.h
	deleted:    ../lib/libc/include/riscv64-linux-gnu/bits/semaphore.h
	deleted:    ../lib/libc/include/s390x-linux-gnu/bits/floatn.h
	deleted:    ../lib/libc/include/s390x-linux-gnu/bits/semaphore.h
	deleted:    ../lib/libc/include/sparc-linux-gnu/bits/floatn.h
	deleted:    ../lib/libc/include/sparc-linux-gnu/bits/semaphore.h
	deleted:    ../lib/libc/include/sparcv9-linux-gnu/bits/floatn.h
	deleted:    ../lib/libc/include/sparcv9-linux-gnu/bits/semaphore.h
	deleted:    ../lib/libc/include/x86_64-linux-gnu/bits/select.h
	deleted:    ../lib/libc/include/x86_64-linux-gnu/bits/semaphore.h
	deleted:    ../lib/libc/include/x86_64-linux-gnux32/bits/select.h
	deleted:    ../lib/libc/include/x86_64-linux-gnux32/bits/semaphore.h

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	../lib/libc/include/aarch64-linux-gnu/bits/mman.h
	../lib/libc/include/aarch64_be-linux-gnu/bits/mman.h
	../lib/libc/include/generic-glibc/gnu/stubs-64.h
	../lib/libc/include/generic-glibc/sys/asm.h
	../lib/libc/include/generic-glibc/sys/cachectl.h
	../lib/libc/include/generic-glibc/sys/single_threaded.h
	../lib/libc/include/i386-linux-gnu/bits/types/
	../lib/libc/include/mips-linux-gnu/bits/floatn.h
	../lib/libc/include/mips-linux-gnu/bits/semaphore.h
	../lib/libc/include/mips-linux-gnu/bits/signum-arch.h
	../lib/libc/include/mips-linux-gnu/bits/types/struct_msqid_ds.h
	../lib/libc/include/mips-linux-gnu/bits/types/struct_semid_ds.h
	../lib/libc/include/mips-linux-gnu/bits/types/struct_shmid_ds.h
	../lib/libc/include/mips64-linux-gnuabi64/bits/floatn.h
	../lib/libc/include/mips64-linux-gnuabi64/bits/semaphore.h
	../lib/libc/include/mips64-linux-gnuabi64/bits/signum-arch.h
	../lib/libc/include/mips64-linux-gnuabi64/bits/types/struct_msqid_ds.h
	../lib/libc/include/mips64-linux-gnuabi64/bits/types/struct_semid_ds.h
	../lib/libc/include/mips64-linux-gnuabi64/bits/types/struct_shmid_ds.h
	../lib/libc/include/mips64-linux-gnuabin32/bits/floatn.h
	../lib/libc/include/mips64-linux-gnuabin32/bits/semaphore.h
	../lib/libc/include/mips64-linux-gnuabin32/bits/signum-arch.h
	../lib/libc/include/mips64-linux-gnuabin32/bits/types/struct_msqid_ds.h
	../lib/libc/include/mips64-linux-gnuabin32/bits/types/struct_semid_ds.h
	../lib/libc/include/mips64-linux-gnuabin32/bits/types/struct_shmid_ds.h
	../lib/libc/include/mips64el-linux-gnuabi64/bits/floatn.h
	../lib/libc/include/mips64el-linux-gnuabi64/bits/semaphore.h
	../lib/libc/include/mips64el-linux-gnuabi64/bits/signum-arch.h
	../lib/libc/include/mips64el-linux-gnuabi64/bits/types/struct_msqid_ds.h
	../lib/libc/include/mips64el-linux-gnuabi64/bits/types/struct_semid_ds.h
	../lib/libc/include/mips64el-linux-gnuabi64/bits/types/struct_shmid_ds.h
	../lib/libc/include/mips64el-linux-gnuabin32/bits/floatn.h
	../lib/libc/include/mips64el-linux-gnuabin32/bits/semaphore.h
	../lib/libc/include/mips64el-linux-gnuabin32/bits/signum-arch.h
	../lib/libc/include/mips64el-linux-gnuabin32/bits/types/struct_msqid_ds.h
	../lib/libc/include/mips64el-linux-gnuabin32/bits/types/struct_semid_ds.h
	../lib/libc/include/mips64el-linux-gnuabin32/bits/types/struct_shmid_ds.h
	../lib/libc/include/mipsel-linux-gnu/bits/floatn.h
	../lib/libc/include/mipsel-linux-gnu/bits/semaphore.h
	../lib/libc/include/mipsel-linux-gnu/bits/signum-arch.h
	../lib/libc/include/mipsel-linux-gnu/bits/types/struct_msqid_ds.h
	../lib/libc/include/mipsel-linux-gnu/bits/types/struct_semid_ds.h
	../lib/libc/include/mipsel-linux-gnu/bits/types/struct_shmid_ds.h
	../lib/libc/include/powerpc-linux-gnu/bits/types/
	../lib/libc/include/powerpc64-linux-gnu/bits/types/
	../lib/libc/include/powerpc64le-linux-gnu/bits/types/
	../lib/libc/include/sparc-linux-gnu/bits/signum-arch.h
	../lib/libc/include/sparc-linux-gnu/bits/types/
	../lib/libc/include/sparcv9-linux-gnu/bits/signum-arch.h
	../lib/libc/include/sparcv9-linux-gnu/bits/types/
	../lib/libc/include/x86_64-linux-gnu/bits/types/
	../lib/libc/include/x86_64-linux-gnux32/bits/types/
```

I'm not sure how you got these changes but I don't think they are correct.

**Pull request closed without merging**
