### PR TITLE
Move s3cmd config into AppData/Roaming/s3cmd.ini

### PR DESCRIPTION
**Pull request by kubkon**
**Do not merge**

I've purposely set the uploads for *every* build including any PR to verify the fix actually works. If it does, I'll put the `if` back in place, and the PR will be mergeable.

### CODE REVIEW

**Comment by andrewrk** [comment]
FYI pull requests don't have access to that file

**Comment by kubkon** [comment]
@andrewrk yeah, I kinda figured that out the "long" way ;-) Either way, I think Windows CI should be fixed with this but I can't figure out a fix for macOS though. Any ideas?

**Comment by andrewrk** [comment]
macOS builds are working fine in master branch, why mess with them?

**Comment by kubkon** [comment]
@andrewrk Oh, I thought that within the last couple of hours azure updated their images and this PR failed in macOS without even touching it. That was before I started trying to figure it out. Sadly, we don't have any PRs submitted within the last 10hours but this one to test this out again. I can submit something real quick and we can have a look though!

**Comment by andrewrk** [comment]
Hang on let me push your one liner to master and let's see what happens

**Comment by kubkon** [comment]
> Hang on let me push your one liner to master and let's see what happens

Sounds good!

**Pull request closed without merging**
