### PR TITLE
Optimize `comptime_int` arithmetic when both operands have fixed storage

### LINKED ISSUE #18471: Utilisation of `BigInt` by `comptime_int` arithmetic is under 1 percent
### Zig Version

0.12.0-dev.2063+804cee3b9

### Steps to Reproduce and Observed Behavior

Any resolved value arithmetic where `scalar_ty` is `comptime_int_type`.

### Expected Behavior

Prefer arithmetic using fixed-size integers where possible.

### PR DESCRIPTION
**Pull request by amp-59**
Fixes #18471.

### CODE REVIEW

**Comment by mlugg** [comment]
A cursory glance at the implementation of `Value.toSignedInt` and/or `InternPool.Key.Int.Storage` will show you that this is not safe. We have 5 integer storage strategies; your optimization is only currently sound for resolved values in the range of an `i64`. Values which fit in a `u64` but not an `i64`, or unresolved lazy values, will cause this code to hit safety-checked Undefined Behavior.

A quick run of the test suite would likely catch the issues here (at a glance, I believe the behavior test `@sizeOf optional of previously unresolved union` would fail for instance). Please run the test suite locally (at an absolute minimum, native debug mode behavior tests) before opening a PR and wasting CI resources on an incorrect change.

Also, any PR aimed at improving performance should provide [benchmarks](https://github.com/andrewrk/poop). Please give a performance comparison for some non-trivial test cases; this could be the behavior tests, std tests, building the compiler itself, or even a bespoke test written to stress this component of the compiler.

**Comment by andrewrk** [comment]
This is for sure going to get closed if it does not come with any performance measurements.

**Comment by mlugg** [comment]
This logic does not account for the not unlikely case of the LHS being `i64`, the RHS being `u64`, but both values being representable by an `i64`.
Have you considered instead upgrading both values to an `i65` for simplicity? Indeed, in that case you may as well jump all the way to `i128` to maximise the number of results which can use this fast path:
```zig
simple: {
    const lhs_int: i128 = switch (lhs_key.int.storage) {
        inline .i64, .u64 => |x| x,
        .big_int, .lazy_align, .lazy_size => break :simple,
    };
    const rhs_int: i128 = switch (rhs_key.int.storage) {
        inline .i64, .u64 => |x| x,
        .big_int, .lazy_align, .lazy_size => break :simple,
    };
    const result, const overflow = @addWithOverflow(lhs_int, rhs_int);
    if (overflow) break :simple;
    return mod.intValue(scalar_ty, result);
}
```
Of course, `i128` arithmetic is slower than `u64`/`i64` arithmetic, but it's pretty trivial in the context of all the surrounding semantic analysis logic, and still much faster than bigint arithmetic.

**Comment by amp-59** [comment]
If you are interested to pursue this optimisation in `src/Sema.zig`, I would also draw your attention to the 11 other places in `src/value.zig` where this optimisation has been noted, but not yet implemented. They can be found by searching `TODO is this a performance issue?`. I doubt I will add these before Andrew closes the PR, as I am very busy performance testing the panic handler issue and it is bothersome to keep switching and rebuilding.

You might also be interested to see an already existing, related optimisation in `src/Sema.zig`, which can be found in `RangeSetUnhandledIterator.addOne`. 

It should be said that this is an insignificant optimisation, aimed more at reducing needless waste than drastically improving the performance of the average compilation. I only opened it because it seemed so non-controversial and I wanted to get the ball rolling.

Before making this PR I predicted that the difference would not be observable, but after running some more tests compiling loops incrementing `comptime_int`, there is apparently a consistent advantage of 5-10% for this patch. The most consistently advantaged statistic was branch misses, which--compiling a loop incrementing to 10,000,000--decreased  from 170,000,000 to 110,000,000, or 0.73% to 0.49%. IPC had also consistently improved from 1.56 to 1.68.

**Comment by Vexu** [comment]
Looks to be closer to a 1-2% improvement even in an extreme case:
```
Benchmark 1: zig build-obj a.zig
  Time (mean ± σ):      4.654 s ±  0.092 s    [User: 4.572 s, System: 0.107 s]
  Range (min … max):    4.533 s …  4.780 s    10 runs
 
Benchmark 2: zig-dev build-obj a.zig
  Time (mean ± σ):      4.619 s ±  0.106 s    [User: 4.549 s, System: 0.106 s]
  Range (min … max):    4.460 s …  4.808 s    10 runs
 
Summary
  zig-dev build-obj a.zig ran
    1.01 ± 0.03 times faster than zig build-obj a.zig
```
`zig`: 2e7d28dd0 ReleaseFast
`zig-dev`: 2e7d28dd0 + this PR ReleaseFast
`a.zig`:
```zig
comptime {
    @setEvalBranchQuota(std.math.maxInt(u32));
    var a: u64 = 0;
    while (a < 1_000_000) {
        a += 1;
    }
    while (a > 1) {
        a -= 1;
    }
}
```

**Comment by andrewrk** [comment]
It's not worth the extra logic in the compiler then. #17796 is going to be the real improvement here, which removes memory allocation from inside that comptime loop.

**Comment by andrewrk** [comment]
A new PR is welcome if it comes with a reproducible demonstration of performance difference. The perf issues attempted to be addressed here are already tracked in #363 and already have other efforts by me partially started as mentioned above. This PR is not a good enough solution to be merged.

**Comment by amp-59** [comment]
@andrewrk I see no reason to dissent from this conclusion. This patch is incomplete (as I mentioned above, there are 11 other places where this change could be implemented) and I think that alone is enough to block the merge.

However the results posted by Vexu are not relevant to this discussion.

Below is the source code used to produce the results referenced by my last comment. Observe that the counters I mentioned two weeks ago are almost exactly reproduced.

Test program that reaches the control flow added by this patch:
```zig
comptime {
    @setEvalBranchQuota(~@as(u32, 0));
    var i: comptime_int = 0;
    while (i != 10_000_000) {
        i = i + 1;
    }
}
```

Results compiling with my branch:
```
Performance counter stats for 'zig-comptime_int_arith_opt-fast build-obj increment_comptime_int.zig':

    11,302,149,051      stalled-cycles-backend:u         #   13.71% backend cycles idle         (62.30%)
   137,789,527,159      instructions:u                   #    1.67  insn per cycle
                                                         #    0.08  stalled cycles per insn     (62.40%)
         21,205.90 msec task-clock:u                     #    1.005 CPUs utilized
            23,349      page-faults:u                    #    1.101 K/sec
    82,425,177,748      cycles:u                         #    3.887 GHz                         (62.67%)
     4,872,618,970      stalled-cycles-frontend:u        #    5.91% frontend cycles idle        (62.82%)
     5,114,530,407      cache-references:u               #  241.184 M/sec                       (63.01%)
        55,998,335      cache-misses:u                   #    1.095 % of all cache refs         (62.86%)
    22,516,553,045      branches:u                       #    1.062 G/sec                       (62.49%)
       105,312,241      branch-misses:u                  #    0.47% of all branches             (62.26%)

      21.109002824 seconds time elapsed

      20.655691000 seconds user
       0.452967000 seconds sys
```
Results compiling the same program with master:
```
Performance counter stats for 'zig-master-fast build-obj increment_comptime_int.zig':

     9,366,234,999      stalled-cycles-backend:u         #   10.38% backend cycles idle         (62.22%)
   142,138,636,631      instructions:u                   #    1.58  insn per cycle
                                                         #    0.07  stalled cycles per insn     (62.09%)
         23,096.78 msec task-clock:u                     #    1.000 CPUs utilized
            23,893      page-faults:u                    #    1.034 K/sec
    90,214,060,793      cycles:u                         #    3.906 GHz                         (62.30%)
     6,458,913,395      stalled-cycles-frontend:u        #    7.16% frontend cycles idle        (62.66%)
     6,792,978,412      cache-references:u               #  294.109 M/sec                       (62.86%)
        56,876,999      cache-misses:u                   #    0.837 % of all cache refs         (62.97%)
    22,958,420,823      branches:u                       #  994.010 M/sec                       (62.98%)
       165,466,457      branch-misses:u                  #    0.72% of all branches             (62.61%)

      23.086012267 seconds time elapsed

      22.443780000 seconds user
       0.548328000 seconds sys
```

Vexu's test (scaled-up):
```zig
comptime {
    @setEvalBranchQuota(~@as(u32, 0));
    var i: u64 = 0;
    while (i != 10_000_000) {
        i = i + 1;
    }
}
```
Note: `src/Sema.zig`:
```zig
fn intAddScalar(sema: *Sema, lhs: Value, rhs: Value, scalar_ty: Type) !Value {
    const mod = sema.mod;
    if (scalar_ty.toIntern() != .comptime_int_type) {
        const res = try sema.intAddWithOverflowScalar(lhs, rhs, scalar_ty);
        if (res.overflow_bit.compareAllWithZero(.neq, mod)) return error.Overflow;
        return res.wrapped_result;
    }
    // ...
```

For `scalar_ty != .comptime_int_type` the control flow is forwarded to `intAddWithOverflowScalar` which uses `BigInt` like master. For this test `scalar_ty` is `u64_type`, so we expect the results to be the same because the logic added by this patch is unreachable.

Results compiling with my branch:
```
 Performance counter stats for 'zig-comptime_int_arith_opt-fast build-obj increment_u64.zig':

    15,794,829,410      stalled-cycles-backend:u         #   13.94% backend cycles idle         (62.28%)
   173,569,252,176      instructions:u                   #    1.53  insn per cycle
                                                         #    0.09  stalled cycles per insn     (62.46%)
         28,935.28 msec task-clock:u                     #    1.003 CPUs utilized
            25,044      page-faults:u                    #  865.518 /sec
   113,278,014,331      cycles:u                         #    3.915 GHz                         (62.61%)
     6,647,915,641      stalled-cycles-frontend:u        #    5.87% frontend cycles idle        (62.64%)
     9,886,677,120      cache-references:u               #  341.682 M/sec                       (62.77%)
        63,085,743      cache-misses:u                   #    0.638 % of all cache refs         (62.83%)
    27,796,842,743      branches:u                       #  960.656 M/sec                       (62.60%)
       348,370,222      branch-misses:u                  #    1.25% of all branches             (62.34%)

      28.838395676 seconds time elapsed

      28.231857000 seconds user
       0.574512000 seconds sys
```
Results compiling with master:
```
Performance counter stats for 'zig-master-fast build-obj increment_u64.zig':

    15,393,002,708      stalled-cycles-backend:u         #   14.00% backend cycles idle         (62.37%)
   173,125,718,353      instructions:u                   #    1.57  insn per cycle
                                                         #    0.09  stalled cycles per insn     (62.56%)
         28,327.59 msec task-clock:u                     #    1.003 CPUs utilized
            30,279      page-faults:u                    #    1.069 K/sec
   109,925,706,252      cycles:u                         #    3.881 GHz                         (62.72%)
     4,295,430,998      stalled-cycles-frontend:u        #    3.91% frontend cycles idle        (62.84%)
     9,602,306,908      cache-references:u               #  338.974 M/sec                       (62.88%)
        63,445,096      cache-misses:u                   #    0.661 % of all cache refs         (62.66%)
    27,921,618,289      branches:u                       #  985.669 M/sec                       (62.39%)
       245,762,053      branch-misses:u                  #    0.88% of all branches             (62.25%)

      28.234233648 seconds time elapsed

      27.670977000 seconds user
       0.530815000 seconds sys
```
They are effectively the same, as expected. The only noteworthy aspect of this last set of results is that for integers with runtime sizes compile-time addition is significantly slower than for `comptime_int`.

**Comment by Vexu** [comment]
Changing to `comptime_int` does indeed improve the performance:
```
Benchmark 1 (15 runs): zig build-obj a.zig
  measurement          mean ± σ            min … max           outliers         delta
  wall_time          3.55s  ± 29.4ms    3.51s  … 3.59s           0 ( 0%)        0%
  peak_rss            313MB ±  416KB     312MB …  313MB          0 ( 0%)        0%
  cpu_cycles         14.4G  ±  115M     14.2G  … 14.6G           0 ( 0%)        0%
  instructions       27.9G  ± 15.0K     27.9G  … 27.9G           0 ( 0%)        0%
  cache_references   13.9M  ±  203K     13.6M  … 14.4M           0 ( 0%)        0%
  cache_misses       5.33M  ±  124K     5.14M  … 5.51M           0 ( 0%)        0%
  branch_misses      9.27M  ±  106K     9.13M  … 9.54M           0 ( 0%)        0%
Benchmark 2 (15 runs): zig-dev build-obj a.zig
  measurement          mean ± σ            min … max           outliers         delta
  wall_time          3.37s  ±  123ms    3.30s  … 3.80s           1 ( 7%)        ⚡-  5.3% ±  1.9%
  peak_rss            270MB ±  138KB     270MB …  270MB          0 ( 0%)        ⚡- 13.6% ±  0.1%
  cpu_cycles         13.3G  ±  489M     13.0G  … 15.0G           1 ( 7%)        ⚡-  8.1% ±  1.8%
  instructions       26.5G  ± 6.23K     26.5G  … 26.5G           0 ( 0%)        ⚡-  4.8% ±  0.0%
  cache_references   10.8M  ±  199K     10.3M  … 11.1M           0 ( 0%)        ⚡- 22.5% ±  1.1%
  cache_misses       5.01M  ±  104K     4.83M  … 5.22M           0 ( 0%)        ⚡-  6.1% ±  1.6%
  branch_misses      6.30M  ±  145K     6.19M  … 6.61M           0 ( 0%)        ⚡- 32.0% ±  1.0%
```

**Pull request closed without merging**
