### PR TITLE
std: One more cpuid fix

### PR DESCRIPTION
**Pull request by LemonBoy**
Don't read from stale eax value, rework the logic a bit so that's clear
what's going on.

### CODE REVIEW

**Comment by LemonBoy** [comment]
I've noticed that `zig builtin` gets the correct info while `zig targets` shows a generic CPU as native, don't know if that's a recent regression or something else.

**Comment by Rocknest** [comment]
@LemonBoy for me `zig targets` also gets os version wrong https://github.com/ziglang/zig/issues/4670#issuecomment-596153311

**Comment by LemonBoy** [comment]
What's your kernel version? `x86_64-linux.3.16...5.5.5-gnu.2.17` reports `5.5.5`

**Comment by Rocknest** [comment]
Oh i actually been running it on WSL instead WSL2.  The kernel version is `4.4.0-Microsoft`...

**Comment by LemonBoy** [comment]
Oh that's the default `VersionRange` for Linux, it seems that the platform detection code isn't called at all by `zig target`...

**Comment by Rocknest** [comment]
`zig builtin` also fails on WSL
```zig
pub const os = Os{
    .tag = .linux,
    .version_range = .{ .linux = .{
        .range = .{
            .min = .{
                .major = 3,
                .minor = 16,
                .patch = 0,
            },
            .max = .{
                .major = 5,
                .minor = 5,
                .patch = 5,
            },
        },
        .glibc = .{
            .major = 2,
            .minor = 27,
            .patch = 0,
        },
    }},
};
```

**Pull request merged**
