### PR TITLE
@bitreverse intrinsic, part of #767

### PR DESCRIPTION
**Pull request by vegecode**
I'm not sure why 39f975b is in this pull request? I think that was already pulled in.

### CODE REVIEW

**Comment by vegecode** [comment]
Shoot. Do I need to add a bitreverse function to std/special/built-in.zig?

**Comment by andrewrk** [comment]
> Shoot. Do I need to add a bitreverse function to std/special/built-in.zig?

Why would you need to do that?

**Comment by vegecode** [comment]
#767 says something to that effect? I don't understand when that is needed.

**Comment by andrewrk** [comment]
Ah, I see. `std/special/builtin.zig` is for functions that LLVM sometimes generates calls to. For example, if you do this Zig code:

```zig
for (source) |s, i|
    dest[i] = s;
```

with optimizations on, LLVM turns this into a function call to `memcpy`. When not linking libc, you would get a missing symbol error for `memcpy`. It's not clearly documented exactly which functions LLVM can generate calls to, but they generally correspond to libc functions, or compiler-rt functions.

In practice, you can not worry about compiler-rt or builtins unless you get a linker error saying that a function is missing.

**Comment by vegecode** [comment]
Nice, thanks.

**Pull request merged**
