### PR TITLE
std.os.windows: add missing null terminator on various kernel32 signatures

### LINKED ISSUE #19949: Missing null terminator on various kernel32 signatures
### Zig Version

0.13.0-dev.75+5c9eb4081

### Mismatched signatures

1. `GetCurrentDirectoryW`
https://github.com/ziglang/zig/blob/084c2cd90f79d5e7edf76b7ddd390adb95a27f0c/lib/std/os/windows/kernel32.zig#L178
`lpBuffer` should be null-terminated according to https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getcurrentdirectory
2. `FormatMessageW`
https://github.com/ziglang/zig/blob/084c2cd90f79d5e7edf76b7ddd390adb95a27f0c/lib/std/os/windows/kernel32.zig#L160
`lpBuffer` should be null-terminated according to https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-formatmessagew
3. `GetEnvironmentVariableW`
https://github.com/ziglang/zig/blob/084c2cd90f79d5e7edf76b7ddd390adb95a27f0c/lib/std/os/windows/kernel32.zig#L189
`lpBuffer` should be null-terminated according to https://learn.microsoft.com/en-us/windows/win32/api/processenv/nf-processenv-getenvironmentvariablew
4. `GetModuleFileNameW`
https://github.com/ziglang/zig/blob/084c2cd90f79d5e7edf76b7ddd390adb95a27f0c/lib/std/os/windows/kernel32.zig#L199
`lpFilename` should be null-terminated according to https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-getmodulefilenamew
5. `GetFullPathNameW`
https://github.com/ziglang/zig/blob/084c2cd90f79d5e7edf76b7ddd390adb95a27f0c/lib/std/os/windows/kernel32.zig#L220-L225
`lpBuffer` should be null-terminated according to https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfullpathnamew

Fixing these would be a breaking change.

### Expected Behavior

extern signatures should be correct

### PR DESCRIPTION
**Pull request by HydroH**
Closes #19949 .

### CODE REVIEW

**Review by alexrp — APPROVED** [review]

**Comment by squeek502** [comment]
I'm not sure these changes make sense. All of these are *out* parameters, meaning the null terminator is written by the function, so the *input* being null-terminated is irrelevant. Further, in terms of usage, I think it makes more sense for these parameters to *not* be defined as null-terminated.

For example, if these parameters are defined with a null-terminator, the correct usage would look something like this:

```
var wtf16le_buf: [std.os.windows.PATH_MAX_WIDE:0]u16 = undefined;
// Have to pass len + 1 since the NUL-terminator should be included in the buffer length
const result = std.os.windows.kernel32.GetCurrentDirectoryW(wtf16le_buf.len + 1, &wtf16le_buf);

if (result == 0) return error.Foo;

// GetCurrentDirectoryW returns the length not including the terminator
const cur_dir = wtf16le_buf[0..result:0];
```

If it's not defined, the usage is more intuitive since just passing the length of the buffer is correct:

```
var wtf16le_buf: [std.os.windows.PATH_MAX_WIDE]u16 = undefined;
const result = std.os.windows.kernel32.GetCurrentDirectoryW(wtf16le_buf.len, &wtf16le_buf);

if (result == 0) return error.Foo;

// GetCurrentDirectoryW returns the length not including the terminator
const cur_dir = wtf16le_buf[0..result:0];
```

So, the buffer being defined as NUL-terminated doesn't gain us anything and makes it less likely that the correct length of the buffer will be passed to the function.

(I've made this same point before on [this issue](https://github.com/ziglang/zig/pull/19641#discussion_r1574168441), but wasn't aware of https://github.com/ziglang/zig/issues/19949)

**Comment by alexrp** [comment]
Good catch, I hadn't considered that nuance. I think I agree with your reasoning.

It does seem a bit unfortunate that the language feature designed specifically to represent this concept doesn't apply cleanly here, though. But I don't know that I have any concrete suggestions for improving that. :confused:

**Comment by squeek502** [comment]
I would argue that `[*]u16` does apply fairly cleanly here. If there was to be a more accurate parameter type, it'd have to represent "is an arbitrary buffer that will become sentinel-terminated after this function returns." That sort of thing seems like the domain of doc comments, though.

**Comment by HydroH** [comment]
> I'm not sure these changes make sense. All of these are *out* parameters, meaning the null terminator is written by the function, so the *input* being null-terminated is irrelevant. Further, in terms of usage, I think it makes more sense for these parameters to *not* be defined as null-terminated.
> 
> For example, if these parameters are defined with a null-terminator, the correct usage would look something like this:
> 
> ```zig
> var wtf16le_buf: [256:0]u16 = undefined;
> // Have to pass len + 1 since the NUL-terminator should be included in the buffer length
> const result = std.os.windows.kernel32.GetCurrentDirectoryW(wtf16le_buf.len + 1, &wtf16le_buf);
> 
> if (result == 0) return error.Foo;
> 
> // GetCurrentDirectoryW returns the length not including the terminator
> const cur_dir = wtf16le_buf[0..result :0];
> ```
> 
> If it's not defined with a null terminator, the usage is more intuitive since just passing the length of the buffer is correct:
> 
> ```zig
> var wtf16le_buf: [256]u16 = undefined;
> const result = std.os.windows.kernel32.GetCurrentDirectoryW(wtf16le_buf.len, &wtf16le_buf);
> 
> if (result == 0) return error.Foo;
> 
> // GetCurrentDirectoryW returns the length not including the terminator
> const cur_dir = wtf16le_buf[0..result :0];
> ```
> 
> So, the buffer being defined as NUL-terminated doesn't gain us anything and makes it less likely that the correct length of the buffer will be passed to the function.
> 
> (I've made this same point before on [this PR](https://github.com/ziglang/zig/pull/19641#discussion_r1574168441), but wasn't aware of https://github.com/ziglang/zig/issues/19949)
> 
> ---
> 
> [This comment](https://github.com/ziglang/zig/pull/19641/files#diff-9cd15c4dfa0fa8bde204dc38c68df184f0e072f0c1c46b05c8990b79ab5e9292) is also relevant:
> 
> > I believe this `lpBuffer` change [for `GetEnvironmentVariableW`] would actually cause a compile error in `std.os.windows.GetEnvironmentVariableW`, but since it's not used anywhere, it's not detected (we have `std.process.getenvW` that serves the same purpose).

I think you are correct. I will close this PR. Maybe the issue should also get closed now?

**Pull request closed without merging**
