### PR TITLE
ability to build stage1 using only a zig tarball

### PR DESCRIPTION
**Pull request by andrewrk**
The main idea here is that there are now 2 ways to get a stage1 zig
binary:

 * The cmake path. Requirements: cmake, system C++ compiler, system
   LLVM, LLD, Clang libraries, compiled by the system C++ compiler.

 * The zig path. Requirements: a zig installation, system LLVM, LLD,
   Clang libraries, compiled by the zig installation.

Note that the former can be used to now take the latter path.

Removed config.h.in and config.zig.in. The build.zig script no longer is
coupled to the cmake script.

cmake no longer tries to determine the zig version. A build with cmake
will yield a stage1 zig binary that reports 0.0.0+zig0. This is going to
get reverted.

`zig build` now accepts `-Dstage1` which will build the stage1 compiler,
and put the stage2 backend behind a feature flag.

build.zig is simplified to only support the use case of enabling LLVM
support when the LLVM, LLD, and Clang libraries were built by zig. This
part is probably sadly going to have to get reverted to make package
maintainers happy.

Zig build system addBuildOption supports a couple new types.

The biggest reason to make this change is that the zig path is an
attractive option for doing compiler development work on Windows. It
allows people to work on the compiler without having MSVC installed,
using only a .zip file that contains Zig + LLVM/LLD/Clang libraries.

### CODE REVIEW

**Comment by andrewrk** [comment]
With this branch, I was able to build a stage1 zig binary using this command:

```
./zig build -Dstage1 --search-prefix ~/dev/zig-bootstrap/out/x86_64-linux-gnu-native
```

The point of the `--search-prefix` using a zig-bootstrap path is due to that C++ ABI incompatibility thing. If I use `--search-prefix` with the LLVM libs that I compiled with my system C++ compiler (which is not zig/clang) then I get many errors such as these:

```
ld.lld: error: undefined symbol: std::thread::detach()
>>> referenced by Filesystem.cpp
>>>               Filesystem.cpp.o:(lld::unlinkAsync(llvm::StringRef)) in archive /home/andy/local/llvm11-release/lib/liblldCommon.a
>>> referenced by Parallel.cpp
>>>               Parallel.cpp.o:(llvm::parallel::detail::(anonymous namespace)::ThreadPoolExecutor::~ThreadPoolExecutor()) in archive /home/andy/local/llvm11-release/lib/libLLVMSupport.a

ld.lld: error: undefined symbol: std::condition_variable::wait(std::unique_lock<std::mutex>&)
>>> referenced by Filesystem.cpp
>>>               Filesystem.cpp.o:(lld::unlinkAsync(llvm::StringRef)) in archive /home/andy/local/llvm11-release/lib/liblldCommon.a
>>> referenced by Parallel.cpp
>>>               Parallel.cpp.o:(std::thread::_State_impl<std::thread::_Invoker<std::tuple<llvm::parallel::detail::(anonymous namespace)::ThreadPoolExecutor::ThreadPoolExecutor(llvm::ThreadPoolStrategy)::'lambda'()::operator()() const::'lambda'()> > >::_M_run()) in archive /home/andy/local/llvm11-release/lib/libLLVMSupport.a
>>> referenced by Parallel.cpp
>>>               Parallel.cpp.o:(std::thread::_State_impl<std::thread::_Invoker<std::tuple<llvm::parallel::detail::(anonymous namespace)::ThreadPoolExecutor::ThreadPoolExecutor(llvm::ThreadPoolStrategy)::'lambda'()> > >::_M_run()) in archive /home/andy/local/llvm11-release/lib/libLLVMSupport.a
>>> referenced 3 more times

ld.lld: error: undefined symbol: std::condition_variable::~condition_variable()
>>> referenced by Filesystem.cpp
>>>               Filesystem.cpp.o:(lld::unlinkAsync(llvm::StringRef)) in archive /home/andy/local/llvm11-release/lib/liblldCommon.a
>>> referenced by Parallel.cpp
>>>               Parallel.cpp.o:(llvm::parallel::detail::(anonymous namespace)::ThreadPoolExecutor::~ThreadPoolExecutor()) in archive /home/andy/local/llvm11-release/lib/libLLVMSupport.a
>>> referenced by Parallel.cpp
>>>               Parallel.cpp.o:(llvm::parallel::detail::TaskGroup::~TaskGroup()) in archive /home/andy/local/llvm11-release/lib/libLLVMSupport.a
>>> referenced 2 more times

ld.lld: error: undefined symbol: std::chrono::_V2::system_clock::now()
>>> referenced by Timer.cpp
>>>               Timer.cpp.o:(lld::ScopedTimer::ScopedTimer(lld::Timer&)) in archive /home/andy/local/llvm11-release/lib/liblldCommon.a
>>> referenced by Timer.cpp
>>>               Timer.cpp.o:(lld::ScopedTimer::stop()) in archive /home/andy/local/llvm11-release/lib/liblldCommon.a
>>> referenced by ArchiveWriter.cpp
>>>               ArchiveWriter.cpp.o:(llvm::writeArchive(llvm::StringRef, llvm::ArrayRef<llvm::NewArchiveMember>, bool, llvm::object::Archive::Kind, bool, bool, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >)) in archive /home/andy/local/llvm11-release/lib/libLLVMObject.a
>>> referenced 9 more times

ld.lld: error: undefined symbol: std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(unsigned long, unsigned long, char const*) const
>>> referenced by X86ISelLowering.cpp
>>>               X86ISelLowering.cpp.o:(llvm::X86TargetLowering::ExpandInlineAsm(llvm::CallInst*) const) in archive /home/andy/local/llvm11-release/lib/libLLVMX86CodeGen.a
>>> referenced by X86ISelLowering.cpp
>>>               X86ISelLowering.cpp.o:(llvm::X86TargetLowering::ExpandInlineAsm(llvm::CallInst*) const) in archive /home/andy/local/llvm11-release/lib/libLLVMX86CodeGen.a
>>> referenced by ARMISelLowering.cpp
>>>               ARMISelLowering.cpp.o:(llvm::ARMTargetLowering::ExpandInlineAsm(llvm::CallInst*) const) in archive /home/andy/local/llvm11-release/lib/libLLVMARMCodeGen.a

ld.lld: error: undefined symbol: std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()
>>> referenced by HexagonAsmBackend.cpp
>>>               HexagonAsmBackend.cpp.o:((anonymous namespace)::HexagonAsmBackend::HandleFixupError(int, int, long, char const*) const (.isra.0.constprop.0)) in archive /home/andy/local/llvm11-release/lib/libLLVMHexagonDesc.a

ld.lld: error: undefined symbol: std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()
>>> referenced by InstructionSelect.cpp
>>>               InstructionSelect.cpp.o:(_GLOBAL__sub_I_InstructionSelect.cpp) in archive /home/andy/local/llvm11-release/lib/libLLVMGlobalISel.a
>>> referenced by COFFImportFile.cpp
>>>               COFFImportFile.cpp.o:(_GLOBAL__sub_I_COFFImportFile.cpp) in archive /home/andy/local/llvm11-release/lib/libLLVMObject.a
```

(and many more)

This is what I meant by "compiled by the system C++ compiler" vs "compiled by the zig installation" above.

Next step is getting it to work on Windows. I am close. The first obstacle is that zig-bootstrap produces `libfoo.a` files but LLD expects `foo.lib` files. Manually renaming the libraries does make it work, so I think this is something where zig can simply choose better output names for static libraries when targeting `x86_64-windows-gnu`.

The next 2 problems are:

 * need to add some `linkSystemLibrary` for some missing symbols 

 * debug zig + release llvm produces an undefined symbol on `llvm::cfg::Update<llvm::BasicBlock*>::dump()`

**Comment by daurnimator** [comment]
> This
> part is probably sadly going to have to get reverted to make package
> maintainers happy.

Taking off my package maintainer hat (which is indeed unhappy), this messes with my local zig development workflow where I rely on my system LLVM/clang/lld.

**Comment by andrewrk** [comment]
> Taking off my package maintainer hat (which is indeed unhappy), this messes with my local zig development workflow where I rely on my system LLVM/clang/lld.

-----


Yep that's the main reason this is still a draft. But the good news is that restoring that functionality doesn't mean losing this new ability.

And on that end - good news! With that latest commit I got it working :tada:

**Comment by andrewrk** [comment]
Using only a .zip file that I produced using zig-bootstrap + a git clone of the zig sources (msys was only used for git, nothing else here) + cmd.exe I have produced a viable debug build of zig with a release build of llvm/lld/clang.

```
c:\msys64\home\andy\dev\zig>C:\Users\andy\Downloads\zig+llvm+lld+clang-x86_64-windows-gnu-0.7.0+fd8fa5512\bin\zig.exe build -Dstage1 -Dtarget=native-native-gnu --search-prefix C:\Users\andy\Downloads\zig+llvm+lld+clang-x86_64-windows-gnu-0.7.0+fd8fa5512

c:\msys64\home\andy\dev\zig>

c:\msys64\home\andy\dev\zig>zig-cache\bin\zig.exe
info: Usage: zig [command] [options]

Commands:

  build            Build project from build.zig
  build-exe        Create executable from source or object files
  build-lib        Create library from source or object files
  build-obj        Create object from source or object files
  cc               Use Zig as a drop-in C compiler
  c++              Use Zig as a drop-in C++ compiler
  env              Print lib path, std path, cache directory, and version
  fmt              Reformat Zig source into canonical form
  help             Print this help and exit
  init-exe         Initialize a `zig build` application in the cwd
  init-lib         Initialize a `zig build` library in the cwd
  libc             Display native libc paths file or validate one
  run              Create executable and run immediately
  translate-c      Convert C code to Zig code
  targets          List available compilation targets
  test             Create and run a test build
  version          Print version number and exit
  zen              Print Zen of Zig and exit

General Options:

  -h, --help       Print command-specific usage

error: expected command argument

c:\msys64\home\andy\dev\zig>
```

**Pull request merged**
