### PR TITLE
Tar: add executable_bit_only support.

### PR DESCRIPTION
**Pull request by Rexicon226**
Closes: #17462

Still working on polishing this and seeing if there any any issues with this. To be honest, I'm just doubting that it's this simple, so I need some time to make sure.

Trying it on something like `ci` folder, it seems to be working.
image

if I'm missing something super obvious please let me know.

### CODE REVIEW

**Comment by Rexicon226** [comment]
Would it make sense to change the properties of the file, after it has been confirmed to successfully been written?

**Comment by ianprime0509** [comment]
From what I understand, the more difficult part of #17462 is implementing the necessary support for Windows using ACLs (the last part of the referenced TODO comment). I'm not familiar with Windows development, so I'm not sure specifically what ACL is being referred to or how to interact with it using Windows APIs, however.

While completely ignoring the executable bit on Windows is simpler to implement, it would cause problems when #17463 is implemented, because it would cause package hashes to differ on Windows vs other platforms: the executable bit would be considered in the hash on POSIX platforms but unavailable on Windows. (This will also be an issue on WASI, but it looks like WASI preview 2 is intended to support file modes similar to POSIX at some point: https://github.com/WebAssembly/wasi-filesystem/blob/d86efbe6c8b7590cfc1306c7bb02dbf960041434/wit/types.wit#L145-L157)

**Comment by Rexicon226** [comment]
So, Windows ACL, from what I understand, is quite a lot different from other ACL implementations. ACL standing for "Access-control List". It's just a general term for a file permissions "format" I guess you could call it. 

Here is good article I found for analyzing the Windows ACL using the win32api [here](https://learn.microsoft.com/en-us/windows/win32/secauthz/getting-information-from-an-acl). And this one for creating and modifying them [here](https://learn.microsoft.com/en-us/windows/win32/secauthz/creating-or-modifying-an-acl). I've never delved deep into the Windows file system methods, but they seem quite interesting and doable. I'm going to spend a couple days exploring implementations for ACL control on windows. Current std simply forces things like "chmod()" to just accept u0, and are useless.

**Comment by andrewrk** [comment]
`std.fs.File.chmod` should move to `std.os` (to be renamed to `std.posix` in #5019) since it is a POSIX-only API. And then `std.fs.File` can be augmented with cross-platform API, if possible.

**Comment by Rexicon226** [comment]
Makes sense. I will make a draft pr to track when I have something. Once the reformat of `std.fs.File` is done, I'll come back to this PR and re-implement it with the "new" api.

**Comment by andrewrk** [comment]
Needs a test, needs a rebase on the updated tar implementation. If you want to continue this work please open a new PR.

**Pull request closed without merging**
