### PR TITLE
fix #6552

### LINKED ISSUE #6552: [build system] cannot build static library for any windows-gnu target
The build.zig

```zig
const Builder = @import("std").build.Builder;

pub fn build(b: *Builder) void {
    const target = b.standardTargetOptions(.{});
    const mode = b.standardReleaseOptions();
    const lib = b.addStaticLibrary("demo", "src/main.zig");
    lib.setTarget(target);
    lib.setBuildMode(mode);
    lib.install();

    var main_tests = b.addTest("src/main.zig");
    main_tests.setBuildMode(mode);

    const test_step = b.step("test", "Run library tests");
    test_step.dependOn(&main_tests.step);
}
```

command:
```batch
D:\Temp\demo> zig build -Dtarget=x86_64-windows-gnu
error: FileNotFound
```

some details:
it seems try to copy libdemo.a but there only demo.lib in cache folder.
crash in 
https://github.com/ziglang/zig/blob/0e2d858d69ee1595bb58d936f83f0e0248d54d68/lib/std/build.zig#L2415
and got `zig build ... --name demo ...` here
https://github.com/ziglang/zig/blob/0e2d858d69ee1595bb58d936f83f0e0248d54d68/lib/std/build.zig#L2102-L2103

### PR DESCRIPTION
**Pull request by codehz**
use libX.a for any-windows-gnu target

### CODE REVIEW

**Comment by codehz** [comment]
Oh, it is not enough, please convert into draft

**Comment by codehz** [comment]
@alexnask It actually works, I forgot to clear the cache...

**Comment by codehz** [comment]
The ci failed seems caused by another reason

**Comment by IridescentRose** [comment]
Reading some of the logs, it looks like the CI failed to link against libc on windows.

**Comment by andrewrk** [comment]
Fixed by https://github.com/ziglang/zig/commit/33bc1ebe37ef6ba5dfe73e458d662b5b516723ba

**Pull request closed without merging**
