### PR TITLE
gettimeofday takes nullable pointers

### PR DESCRIPTION
**Pull request by ProkopRandacek**

### CODE REVIEW

**Comment by nekopsykose** [comment]
hmm, is `tv` definitely nullable? it doesn't seem to be invalid to pass, but at least man-pages documents only `tz` as nullable. is there a use to using it this way?

**Comment by ProkopRandacek** [comment]
> If either tv or tz is NULL, the corresponding structure is not set or returned.  (However, compilation warnings will result if tv is NULL.)

https://man7.org/linux/man-pages/man2/settimeofday.2.html

musl implementation seems to only set `tv` when it is non-null and never even touches `tz`.

I agree that passing tv as `NULL` is questionable. I don't see a problem with making `tv` not nullable. But then the `gettimeofday` wrapper in [`stdlib/os.zig`](https://github.com/ziglang/zig/blob/master/lib/std/os.zig#L4749) has to be updated too since currently it is a compiler error when one tries to call it. (the nullablilty doesn't match) (that's why i created this PR, i should have mentioned that)

**Comment by nekopsykose** [comment]
> But then the gettimeofday wrapper in [stdlib/os.zig](https://github.com/ziglang/zig/blob/master/lib/std/os.zig?rgh-link-date=2023-07-10T15%3A29%3A05Z#L4749) has to be updated too since currently it is a compiler error when one tries to call it. (the nullablilty doesn't match) (that's why i created this PR, i should have mentioned that)  

yeah, that's fair. i was just curious :)

**Comment by andrewrk** [comment]
Looks like this PR is correct on both counts:

```c
SYSCALL_DEFINE2(gettimeofday, struct __kernel_old_timeval __user *, tv,
		struct timezone __user *, tz)
{
	if (likely(tv != NULL)) {
		struct timespec64 ts;

		ktime_get_real_ts64(&ts);
		if (put_user(ts.tv_sec, &tv->tv_sec) ||
		    put_user(ts.tv_nsec / 1000, &tv->tv_usec))
			return -EFAULT;
	}
	if (unlikely(tz != NULL)) {
		if (copy_to_user(tz, &sys_tz, sizeof(sys_tz)))
			return -EFAULT;
	}
	return 0;
}
```

**Pull request merged**
