### PR TITLE
M:N threading

### PR DESCRIPTION
**Pull request by andrewrk**
* add std.atomic.QueueMpsc.isEmpty
 * make std.debug.global_allocator thread-safe
 * std.event.Loop: now you have to choose between
   - initSingleThreaded
   - initMultiThreaded
 * std.event.Loop multiplexes coroutines onto kernel threads
 * Remove std.event.Loop.stop. Instead the event loop run() function
   returns once there are no pending coroutines.
 * fix crash in ir.cpp for calling methods under some conditions
 * small progress self-hosted compiler, analyzing top level declarations
 * Introduce std.event.Lock for synchronizing coroutines
 * introduce std.event.Locked(T) for data that only 1 coroutine should
   modify at once.
 * make the self hosted compiler use multi threaded event loop
 * make std.heap.DirectAllocator thread-safe

See #174

TODO:
 * [x] call sched_getaffinity instead of hard coding thread pool size 4
 * [x] support for Windows
 * [x] support for MacOS
 * #1194
 * #1197

### CODE REVIEW

**Comment by kristate** [comment]
Wondering if we need an abstraction for FDs;
On windows we have to work with `typedef void * HANDLE`

Better to get threading out of the way first before we fine tune event loops, though.

**Comment by kristate** [comment]
Also, this might be of curiosity to you:
https://blog.marcgravell.com/2018/07/pipe-dreams-part-1.html

**Comment by andrewrk** [comment]
Got it working on MacOS, next up Windows

**Comment by andrewrk** [comment]
@bnoordhuis looks like libuv uses IO Completion Ports. Do you recommend this approach?

**Comment by andrewrk** [comment]
nevermind, it's already done. that was a surprisingly nice API.

**Pull request merged**
