### PR TITLE
macOS: temporarily fall back to ld linker when native

### LINKED ISSUE #6812: Building Zig + C++ mixed projects fail to compile on macOS
This is related to the regression from #6773. C++ compilation fails with just `Segmentation fault: 11`. As mentioned in #6773, `0.6.0+68bf29c31` is the last working version I have that can compile C++ code on macos.

You can reproduce by just testing on this repo (https://github.com/prime31/zig-upaya) that has C code (Sokol) and C++ (Dear ImGui) mixed with the zig. I made a branch that is updated to be compatible with Zig master as of todays Zig version. Repro steps:

```
git clone --recursive https://github.com/prime31/zig-upaya
cd zig-upaya
git checkout zig-master-10-24
zig build
```

### PR DESCRIPTION
**Pull request by kubkon**
This commit ensures that when compiling Zig natively on macOS
we use the system linker, `ld`, instead of the LLVM `lld` linker.
Since macOS Big Sur, the OS requires generated binaries (including
dylibs) to be codesigned. If the condition is not met, we receive
an automatic `SIGKILL`.

This commit is hopefully only a temporary solution until either `lld`
fixes this upstream, or self-hosted is in a position to link complex
projects and generate a valid code signature.

This commit is a temp fix for #6971 to make Zig fully-functional
on latest impending macOS release, BigSur. I envision the fix
to remain in the codebase until either `lld` is fixed, or we
advance self-hosted enough that we can link complex projects.

Many thanks to @jedisct1 for doing due diligence and coming up
with a set of patches with great explanation in #6318.

Closes #6812

### CODE REVIEW

**Comment by kubkon** [comment]
Incidentally, this also makes more tests pass on `aarch64`. I guess `lld` is not yet ready for `aarch64` prime time.

**Comment by kubkon** [comment]
I'm putting this on hold until I double check that code signing issue is relevant to Big Sur x86_64 (currently, on my MBP doesn't seem like it is). I'll do a clean install and re-verify.

**Comment by kubkon** [comment]
OK, the good news is: this is not needed on x86_64 Big Sur (double checked on my x86_64 Big Sur Public Beta with a clean install today), so 0.7.0 release is not hindered by this, hence we don't have to worry about VM addressing mismatched in stack traces between LLD and LD (yay!). The bad news is: this is needed on ARM64 Big Sur since LLD doesn't code sign the MachO binaries by default, and I have absolutely no idea why ARM64 Big Sur requires this all of a sudden. Since ARM64 macOS is not mainstream yet, I'd say that anyone who is experimenting with Zig on this platform will want to build from source anyhow meaning they'll be able to apply the patch themselves if need be.

Therefore, I'm closing this PR for now, and leaving a link to #6971 for more context. If anyone finds a different result on x86_64 Big Sur, please by all means report that in #6971 and reopen this PR, etc.

**Comment by kubkon** [comment]
> I still feel like we may want to support this, as an option (disabled by default). Here is why:
> 
> * This also works around C++ linking issues that also apply to other OS versions.

I think it used to be like this, `ld` available behind a feature flag. Perhaps we should re-introduce it? @andrewrk what do you think? FWIW, I'm more inclined to introduce the flag so that we fix C++ projects encountered by @prime31 than fix the codesigning issue on ARM64 Big Sur.

> * We don't know if code signing requirements are not going to be enforced in the final version of Big Sur/x86_64. Apple being quite unpredictable, it may very well be the case. But what is very likely is that Big Sur will be released before the another release of Zig.

Given that we're at public beta now, I find this unlikely as it would break virtually every open-source project on macOS.

> * Having such an option makes Zig already compatible (ignoring the stack trace issues) with Apple Silicon. This is big. Virtually all other languages, including Go and Rust, are not ready yet.

Agreed, I just want to avoid introducing rushed changes into the codebase, and the stack trace issue is worrying as the errors reported to users will be wrong. I could be convinced to have it feature-gated though as I expressed above.

**Comment by semarie** [comment]
to mention another case where it could be useful to invoke local linker instead of embedded llvm one: on OpenBSD, we use a patched version of lld (currently llvm-10). For being able to build zig master on OpenBSD, I needed to port serveral patches to llvm-11 first to have a working lld library.

**Pull request closed without merging**
