### PR TITLE
Beginnings of msp430 ABI support in compiler_rt.

### PR DESCRIPTION
**Pull request by nmichaels**
Addresses bug #9807, plenty of room for further implementation and
improvements.

### CODE REVIEW

**Comment by LemonBoy** [comment]
Not so fast, all the builtin functions must be declared with a specific calling convention that Zig doesn't support yet. The plan is to have the compiler understand the `builtin` CC first and then to implement a few ones, having all of them stubbed out like this is a bad idea and a PITA for the unsuspecting user that happens to trigger one.

**Comment by nmichaels** [comment]
> ... having all of them stubbed out like this is a bad idea and a PITA for the unsuspecting user that happens to trigger one.

I think it's better to get a compiler error the ones in this patch than the one I pasted in #9807 .

That said, I was really just hoping to get the discussion started and point this in the right direction.

It looked from the ABI like the majority of the functions just use the C calling convention (see comments in, e.g., `__mspabi_cmpd` for exceptions). Should those just use `.Naked` and hack around it with inline asm (like in arm.zig), or do you think we should wait until Zig supports the calling convention natively?

**Comment by LemonBoy** [comment]
Fair enough, I didn't see the compileerror calls.

Adding a new CC takes [only a few LoC](https://github.com/ziglang/zig/commit/9ebdbca379fb71da7236e7534e1d3465f7fb151f), I'd start from that.

**Comment by nmichaels** [comment]
That does look pretty easy. I'm still not totally clear on why this needs a new calling convention though. The functions I added are called the same way other C functions are called. There are bunches of other functions in compiler_rt.zig that use `callconv(.C)`. Are you saying we should change all of those before making Zig usable on msp430?

Or maybe I'm completely misunderstanding the point.

**Comment by LemonBoy** [comment]
> Or maybe I'm completely misunderstanding the point.

You are. As stated in the LLM [frontend](https://www.llvm.org/doxygen/MSP430ISelLowering_8cpp_source.html#l00455) many of the msp-specific functions expect a given special CC, the arguments and return values are passed in some specific registers and the usable register set is also different from the usual `.C` CC.

**Comment by andrewrk** [comment]
I do think it would be worth following @LemonBoy's guidance on this. I'm closing this because no recent activity, and it does not appear to be in a mergeable state. Please feel free to open a fresh one if you decide to pick it up.

**Pull request closed without merging**
