### PR TITLE
(WIP) translate-c: handle bitfield

### LINKED ISSUE #1499: translate-c converts struct to OpaqueType when it includes a bitfield
```
struct Test {
    unsigned foobar : 1;
};

```
pub const struct_Test = @OpaqueType();

### PR DESCRIPTION
**Pull request by locriacyber**
Because I don't know Clang, I left 1 TODO in the code

fix #1499

- [ ] custom padding (implementation defined)
- [ ] padding
- [ ] unnamed field

### CODE REVIEW

**Review by Vexu — CHANGES_REQUESTED** [review]
Zig's integer backed packed structs are not compatible with C structs and cannot be directly used to implement structs with bitfields.

**Comment by locriacyber** [comment]
Thanks!

Turns out struct size with bitfield is implementation defined.

```c
#include <stdio.h>
struct S1 {

    unsigned char b1 : 1;
    //unsigned :0; // #1. start a new byte
    unsigned char b2 : 1;

};

struct S2 {
    unsigned int b1 : 1;
    unsigned int b2 : 1;

};

int main()
{
    printf("%d\n", sizeof(char)); 
    printf("%d\n", sizeof(int)); 
    printf("%d\n", sizeof(struct S1)); // usually prints 1
    printf("%d\n", sizeof(struct S2)); // usually prints 4
}
```

**Comment by Vexu** [comment]
> Turns out struct size with bitfield is implementation defined.

Yup, this is all correctly implemented by https://github.com/Vexu/arocc and the plan is to make translate-c use it instead of Clang.

**Comment by locriacyber** [comment]
Page 14: https://www.uclibc.org/docs/psABI-x86_64.pdf says:

- bit-fields are allocated from right to left
- bit-fields must be contained in a storage unit appropriate for its declared type
- bit-fields may share a storage unit with other struct / union members
- Unnamed bit-fields’ types do not affect the alignment of a structure or union. (used to separate storage unit only)

From experimenting with GCC:

- char:1 + char:1 = 1 byte (`struct S1` above)
- char:1 + int:1 = 4 bytes
- int:1 + char:1 = 4 bytes
- int:1 + int:1 = 4 bytes (`struct S2` above)

**Pull request closed without merging**
