### PR TITLE
Add zig fmt to cli tests

### PR DESCRIPTION
**Pull request by squeek502**
Should help to reduce the number of regressions that have been happening with `zig fmt`.

This is failing for me locally on Windows with unexpected status 0xC0000056 (`STATUS_DELETE_PENDING`), but is working on Linux. `zig fmt` is misbehaving for me on Windows currently though (AccessDenied or unexpected 0xC0000103 (`NOT_A_DIRECTORY`)) when invoking it normally, so I think it's catching an actual regression.

### CODE REVIEW

**Comment by andrewrk** [comment]
> This is failing for me locally on Windows

Is this after https://github.com/ziglang/zig/commit/edea7a46e5484e30c338699207c8f4b4d8370c97? I did test that commit on windows before merging like this:

```
zig-cache\bin\zig.exe fmt ..\lib\std
```

**Comment by andrewrk** [comment]
Also, I think this change might be able to be much simpler, just by changing https://github.com/ziglang/zig/blob/56220449abcbbb0e308e0eadeb2e0e7c8a9e4cba/build.zig#L50 from `build.zig` to a directory.

**Comment by andrewrk** [comment]
Thanks BTW 👍

**Comment by squeek502** [comment]
> > This is failing for me locally on Windows
> 
> Is this after [edea7a4](https://github.com/ziglang/zig/commit/edea7a46e5484e30c338699207c8f4b4d8370c97)? I did test that commit on windows before merging like this:
> 
> ```
> zig-cache\bin\zig.exe fmt ..\lib\std
> ```

Yes, after edea7a4.

```
C:\Users\Ryan\Programming\Zig\zig\build-release>".\bin\zig.exe" fmt ..\lib\std
unable to format '..\lib\std\os.zig': error.AccessDenied
```
(this is likely #5643)
```
C:\Users\Ryan\Programming\Zig\zig\build-release>".\bin\zig.exe" fmt ..\lib\std\os.zig
error.Unexpected NTSTATUS=0xc0000103
Unable to dump stack trace: debug info stripped
Unexpected
```
(this is likely caused by some change in edea7a46)

I'm still using Windows 7, though, so that could be the difference?

**Comment by squeek502** [comment]
> Also, I think this change might be able to be much simpler, just by changing
> 
> https://github.com/ziglang/zig/blob/56220449abcbbb0e308e0eadeb2e0e7c8a9e4cba/build.zig#L50
> from `build.zig` to a directory.

This would still be an incomplete test, since it doesn't actually make changes to the file (`".\bin\zig.exe" fmt ..\build.zig` works fine for me [not sure why it avoids the errors in the previous comment though...]). The added cli tests in this PR intentionally create files that will be changed by `zig fmt`, so they should be much more complete.

**Pull request merged**
