### PR TITLE
std wasi tests

### PR DESCRIPTION
**Pull request by fengb**
Attempt to shim enough of the WASI layer to enable CI tests

### CODE REVIEW

**Comment by kubkon** [comment]
Hey @fengb! I'm trying to add basic WASI preopen support to `libstd`. Perhaps we could sync up and join forces?

**Comment by kubkon** [comment]
Oh, for the record, my early draft PR #5231.

**Comment by fengb** [comment]
Yeah I noticed you were starting on some WASI. This was a pretty old branch where I made some headway but got a little distracted. 

My goal here was getting the stdlib tests to compile and possibly pass, so it may or may not overlap with your ideas. But it makes sense to make a WIP PR so we don't unnecessarily duplicate work.

**Comment by kubkon** [comment]
> Yeah I noticed you were starting on some WASI. This was a pretty old branch where I made some headway but got a little distracted.
> 
> My goal here was getting the stdlib tests to compile and possibly pass, so it may or may not overlap with your ideas. But it makes sense to make a WIP PR so we don't unnecessarily duplicate work.

That's excellent! My knowledge of zig is still very rudimentary so I'd very much appreciate someone to discuss this stuff with. And vice versa, if you need anyone to look at anything WASI -related more from Wasm+WASI perspective, don't hesitate to cc me in! Oh, and totally agree on WIP PRs so that we don't duplicate any work. :+1:

**Comment by fengb** [comment]
Superseded by https://github.com/ziglang/zig/pull/5303#issuecomment-630478692

**Pull request closed without merging**
