### PR TITLE
Extract doc comments

### LINKED ISSUE #10682: ZIR encoding optimization: store doc comments in separate arrays
Example:

```zig
    /// Trailing:
    /// { // for every fields_len
    ///      field_name: u32 // null terminated string index
    ///     doc_comment: u32 // null terminated string index
    /// }
    pub const ErrorSetDecl = struct {
        fields_len: u32,
    };
```

Sema does not actually need to care about those `doc_comment` indexes at all. So this would be better stored as a separate array, like this:

```zig
    /// Trailing:
    /// field_name: u32 // for every fields_len; null terminated string index
    /// doc_comment: u32 // for every fields_len; null terminated string index
    pub const ErrorSetDecl = struct {
        fields_len: u32,
    };
```

This way when Sema loads the code, it can avoid loading these indexes unnecessarily. The following diff is the downgrade that we did by introducing doc comments:

```diff
@@ -2103,7 +2106,6 @@ fn zirErrorSetDecl(
     const inst_data = sema.code.instructions.items(.data)[inst].pl_node;
     const src = inst_data.src();
     const extra = sema.code.extraData(Zir.Inst.ErrorSetDecl, inst_data.payload_index);
-    const fields = sema.code.extra[extra.end..][0..extra.data.fields_len];
 
     var new_decl_arena = std.heap.ArenaAllocator.init(gpa);
     errdefer new_decl_arena.deinit();
@@ -2121,8 +2123,12 @@ fn zirErrorSetDecl(
     errdefer sema.mod.abortAnonDecl(new_decl);
 
     var names = Module.ErrorSet.NameMap{};
-    try names.ensureUnusedCapacity(new_decl_arena_allocator, fields.len);
-    for (fields) |str_index| {
+    try names.ensureUnusedCapacity(new_decl_arena_allocator, extra.data.fields_len);
+
+    var extra_index = @intCast(u32, extra.end);
+    const extra_index_end = extra_index + (extra.data.fields_len * 2);
+    while (extra_index < extra_index_end) : (extra_index += 2) { // +2 to skip over doc_string
+        const str_index = sema.code.extra[extra_index];
         const name = try new_decl_arena_allocator.dupe(u8, sema.code.nullTerminatedString(str_index));
 
         // TODO: This check should be performed in AstGen instead.
```

This could be reverted by using separate arrays for doc comments. 

The same principle can be applied to all the places doc comments are stored, such as for each Decl.

### PR DESCRIPTION
**Pull request by I-mikan-I**
Closes #10682

Opening as a draft for now.  

todo: decl's and fields

### CODE REVIEW

**Comment by I-mikan-I** [comment]
Should be done, I left params as is, because every single param has exactly one doc comment.

**Review by andrewrk — CHANGES_REQUESTED** [review]
Hi, thank you for the patch. I would like to request the following things:

 * clean up the git commit history
 * rebase against latest master, address the conflicts
 * avoid the std lib changes which should be unnecessary now since the flaky test has been disabled
 * provide some kind of perf measurement to share whether this had any noticeable impact

**Comment by I-mikan-I** [comment]
> Hi, thank you for the patch. I would like to request the following things:
> 
>     * clean up the git commit history
> 
>     * rebase against latest master, address the conflicts
> 
>     * avoid the std lib changes which should be unnecessary now since the flaky test has been disabled
> 
>     * provide some kind of perf measurement to share whether this had any noticeable impact

Thanks, about the last point:
Do you think benchmarking the entire compilation process makes sense in this case? Or should I constrain benchmarks to some smaller unit (maybe there's an obvious one)? Perhaps the impact wouldn't be noticeable otherwise.

**Comment by andrewrk** [comment]
Here's one possible strategy:

```
$ ./zig build -p stage2-release -Denable-llvm -Dskip-install-lib-files -Drelease
$ perf stat -e branch-instructions -e branch-misses -e cache-misses -e cache-references -e cpu-cycles -e instructions ./stage2-release/bin/zig build -p stage3 -Dskip-install-lib-files
```

Then compare this against master branch.

**Comment by I-mikan-I** [comment]
After changes:
```
 Performance counter stats for './stage2-release/bin/zig build -p stage3 -Dskip-install-lib-files':

    40,390,993,583      branch-instructions:u                                         (83.38%)
     1,412,832,604      branch-misses:u           #    3.50% of all branches          (83.36%)
       716,631,229      cache-misses:u            #    7.516 % of all cache refs      (83.24%)
     9,535,235,940      cache-references:u                                            (83.32%)
   167,487,191,242      cpu-cycles:u                                                  (66.72%)
   215,611,750,504      instructions:u            #    1.29  insn per cycle           (83.40%)

      36.498526829 seconds time elapsed

      35.546125000 seconds user
       1.035131000 seconds sys
```
Master:
```
    40,355,037,914      branch-instructions:u                                         (83.37%)
     1,410,952,944      branch-misses:u           #    3.50% of all branches          (83.39%)
       685,439,676      cache-misses:u            #    7.303 % of all cache refs      (83.28%)
     9,385,122,977      cache-references:u                                            (83.28%)
   166,070,827,653      cpu-cycles:u                                                  (66.70%)
   215,319,747,032      instructions:u            #    1.30  insn per cycle           (83.35%)

      36.359394807 seconds time elapsed

      35.454425000 seconds user
       0.867833000 seconds sys
```

I suppose cache misses did go down slightly, but I'm not sure if there's any scenario where it's noticeable.

**Comment by I-mikan-I** [comment]
After changes:
```
 Performance counter stats for './stage2-release/bin/zig build -p stage3 -Dskip-install-lib-files':

    35,821,892,069      branch-instructions:u                                         (83.36%)
     1,261,309,893      branch-misses:u           #    3.52% of all branches          (83.37%)
       596,529,490      cache-misses:u            #    7.062 % of all cache refs      (83.36%)
     8,446,664,652      cache-references:u                                            (83.36%)
   149,459,102,707      cpu-cycles:u                                                  (66.57%)
   191,475,789,729      instructions:u            #    1.28  insn per cycle           (83.36%)

      32.894469784 seconds time elapsed

      31.754609000 seconds user
       0.833348000 seconds sys
```
Master:
```
    35,845,471,420      branch-instructions:u                                         (83.37%)
     1,255,935,732      branch-misses:u           #    3.50% of all branches          (83.39%)
       597,490,049      cache-misses:u            #    7.177 % of all cache refs      (83.35%)
     8,324,773,521      cache-references:u                                            (83.34%)
   147,175,855,756      cpu-cycles:u                                                  (66.59%)
   191,619,988,270      instructions:u            #    1.30  insn per cycle           (83.31%)

      32.326098637 seconds time elapsed

      31.228449000 seconds user
       0.902049000 seconds sys
```
So it doesn't seem like there's a huge impact, the differences could be due to noise. Maybe you would notice a difference if the compiled source code was constructed just to highlight these changes.

**Comment by I-mikan-I** [comment]
I profiled a few compilation for both master and this branch on a simple executable, which consisted of a large enum and a doc comment per field declaration, with main only referencing all field decls. I got the following results.
With changes:
```
 Performance counter stats for './stage2-release/bin/zig build-exe example.zig':

       541,573,346      branch-instructions:u                                         (84.59%)
        19,729,595      branch-misses:u           #    3.64% of all branches          (84.99%)
         3,212,026      cache-misses:u            #    2.409 % of all cache refs      (83.77%)
       133,351,996      cache-references:u                                            (77.51%)
     2,052,089,774      cpu-cycles:u                                                  (69.53%)
     2,860,628,570      instructions:u            #    1.39  insn per cycle           (84.86%)

       0.484928942 seconds time elapsed

       0.480242000 seconds user
       0.042289000 seconds sys
```
Master:
```
       545,891,898      branch-instructions:u                                         (84.32%)
        19,776,797      branch-misses:u           #    3.62% of all branches          (84.97%)
         3,518,289      cache-misses:u            #    2.778 % of all cache refs      (80.71%)
       126,670,523      cache-references:u                                            (81.89%)
     2,067,844,968      cpu-cycles:u                                                  (68.55%)
     2,861,980,633      instructions:u            #    1.38  insn per cycle           (84.70%)

       0.483269667 seconds time elapsed

       0.446572000 seconds user
       0.075916000 seconds sys
```
There were some deviations between individual runs, the master branch seems to have on average around ~0.3% more cache misses. This is a very unscientific method though.

**Comment by andrewrk** [comment]
Thank you for all this work. The implementation looks good to me, and I think this PR could be merged. However, given that we can't seem to find any evidence for this being a performance improvement, and this encoding is slightly more complex than master branch, perhaps the best move here will be to close the issue and explain why it is not worth pursuing.

What do you think, @I-mikan-I?

**Comment by I-mikan-I** [comment]
> Thank you for all this work. The implementation looks good to me, and I think this PR could be merged. However, given that we can't seem to find any evidence for this being a performance improvement, and this encoding is slightly more complex than master branch, perhaps the best move here will be to close the issue and explain why it is not worth pursuing.
> 
> What do you think, @I-mikan-I?

I agree, in this case it would add complexity to the codebase without any direct benefit.
The only reason I see to merge the changes is if the types sema operates on get more such "meta-fields" in the future. It could make sense to save them in a separate array (I imagine eventually there would be a noticeable impact on indexing).
Maybe just something to keep in mind when adding fields in the future.

If you think we'd rather wait on this we can close the PR and issue 🙂.

**Comment by andrewrk** [comment]
@kristoff-it can you share your opinion on this?

1. Merge the PR, change the way doc comments are accessed from ZIR (potentially simpler for autodocs?)
2. Close the PR, leave it as status quo at least for now

**Comment by kristoff-it** [comment]
I don't have a strong opinion either way. 
I'm happy to do the work necessary to adapt autodoc in case you decide to proceed with the merge.
Even better, I'd be happy receive a patch for autodoc in such case :^)

With regards to future meta-fields, I can't think of any.

**Comment by andrewrk** [comment]
OK given all of this, I think the move here will be closing the issue and not merging the patch. Thanks again for your work @I-mikan-I. The closed issue will still contain a link to this closed PR in case we want to revisit.

**Pull request closed without merging**
