### PR TITLE
std.tar: add support for file path in pax attributes

### LINKED ISSUE #15342: [std.http] zig build fails to download large archives from github
### Zig Version

0.11.0-dev.2648+3cd19dd89

### Steps to Reproduce and Observed Behavior

**Note: This is almost certainly a bug in `std.http` rather than the build system.**

1. Create a minimal `build.zig`:
```zig
const std = @import("std");

pub fn build(b: *std.Build) void {
    _ = b;
}
```

2. Create a `build.zig.zon` with a link to reproduce the bug:
```zig
.{
    .name = "test",
    .version = "0.0.0",

    .dependencies = .{
        .test_dep = .{
            // The code of this repo is likely not important, it's just a link that allows to reproduce this.
            .url = "https://github.com/lordmzte/dawn/archive/9e2a193db129ebaf42eccfb9d6bb40055645c5d9.tar.gz",
        },
    },
}
```

3. `zig build`

4. The build will fail with one of two errors, seemingly at random:
- `error: TarComponentsOutsideStrippedPrefix`
- `error: BadReaderState`

Note that the tar archive the link points to is very large (>90MB). I suspect that this causes the GitHub server to use chunked encoding, which may cause either invalid data or a crash in the HTTP implementation in the two possible cases.

This is the stack trace produced by a debug build of Zig in the former case:
```
error: TarComponentsOutsideStrippedPrefix
/home/lordmzte/dev/zig/lib/std/tar.zig:181:13: 0x6000f17 in stripComponents (zig)
            return error.TarComponentsOutsideStrippedPrefix;
            ^
/home/lordmzte/dev/zig/lib/std/tar.zig:130:35: 0x6001c2c in pipeToFileSystem__anon_49378 (zig)
                const file_name = try stripComponents(unstripped_file_name, options.strip_components);
                                  ^
/home/lordmzte/dev/zig/src/Package.zig:561:5: 0x6002a57 in unpackTarball__anon_49145 (zig)
    try std.tar.pipeToFileSystem(out_dir, decompress.reader(), .{
    ^
/home/lordmzte/dev/zig/src/Package.zig:490:13: 0x60139ea in fetchAndUnpack (zig)
            try unpackTarball(gpa, &req, tmp_directory.handle, std.compress.gzip);
            ^
/home/lordmzte/dev/zig/src/Package.zig:282:25: 0x6018e6b in fetchAndAddDependencies (zig)
        const sub_pkg = try fetchAndUnpack(
                        ^
/home/lordmzte/dev/zig/src/main.zig:4402:13: 0x5e7a46a in cmdBuild (zig)
            try fetch_result;
            ^
/home/lordmzte/dev/zig/src/main.zig:298:9: 0x5e46dfb in mainArgs (zig)
        return cmdBuild(gpa, arena, cmd_args);
        ^
/home/lordmzte/dev/zig/src/main.zig:211:5: 0x5e458eb in main (zig)
    return mainArgs(gpa, arena, args);
    ^
```

### Expected Behavior

The dependency is downloaded.

### PR DESCRIPTION
**Pull request by 189900**
Handles .extended_header type to parse PAX attributes and check if they override the path of the next file. Increases maximum file path length from 255 to ~1014~ `std.fs.MAX_PATH_BYTES`.

Fixes #15342

### CODE REVIEW

**Comment by truemedian** [comment]
Is there a reason you chose 1014 specifically instead of something like `std.fs.MAX_PATH_BYTES`?

**Comment by 189900** [comment]
I went with 1014 to maintain the existing read buffer characteristics and avoid extra overhead.

We can definitely switch to `std.fs.MAX_PATH_BYTES` if that would be more preferable.

**Comment by truemedian** [comment]
PAX path attributes technically have no length limitation, so we need to allocate as much space as we can reasonably handle so that the issue of not being able to handle long file paths doesn't appear again. Any path > MATH_PATH_BYTES can't be sent to the os anyway, so it's a good upper limit.

**Comment by squeek502** [comment]
Going to link to my idea for parsing a component-at-a-time to support arbitrarily long file paths without needing an allocator: https://github.com/ziglang/zig/pull/15382#discussion_r1278370631

**Comment by 189900** [comment]
Thank you both. Updated the branch to support `std.fs.MAX_PATH_BYTES`. A sample tar with long a path: [4k.tar.gz](https://github.com/ziglang/zig/files/12468509/4k.tar.gz)

**Pull request merged**
