### PR TITLE
Fix #18913: compiler crash ptrCast'ing optional slice to allowzero-many-pointer

### LINKED ISSUE #18913: compiler crash ptrCast'ing optional slice to allowzero-many-pointer
### Zig Version

0.12.0-dev.2701+d18f52197

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

test {
    const a: ?[]const u32 = null;
    const b: [*]allowzero const u8 = @ptrCast(a);
    const c = @intFromPtr(b);
    try std.testing.expect(c == 0);
}
```

```
LLVM Emit Object... thread 265006 panic: reached unreachable code
Analyzing test2.zig: test2.zig:test_0
      %6 = dbg_block_begin()
      %7 = dbg_stmt(2, 5)
      %8 = block_comptime({
        %9 = ptr_type(@u32_type, const, Slice) node_offset:4:15 to :4:26
        %10 = optional_type(%9) node_offset:4:14 to :4:26
        %11 = break(%8, %10)
      }) node_offset:4:14 to :4:26
      %12 = as_node(%8, @null_value) node_offset:4:29 to :4:33
      %13 = dbg_var_val(%12, "a")
      %14 = dbg_stmt(3, 5)
      %15 = block_comptime({
        %16 = ptr_type(@u8_type, allowzero, const, Many) node_offset:5:14 to :5:35
        %17 = break(%15, %16)
      }) node_offset:5:14 to :5:35
      %18 = dbg_stmt(3, 38)
    > %19 = ptr_cast(%15, %12) node_offset:5:38 to :5:49
      %20 = as_node(%15, %19) node_offset:5:38 to :5:49
      %21 = dbg_var_val(%20, "b")
      %22 = dbg_stmt(4, 5)
      %23 = dbg_stmt(4, 15)
      %24 = int_from_ptr(%20) node_offset:6:15 to :6:29
      %25 = dbg_var_val(%24, "c")
      %26 = dbg_stmt(5, 5)
      %27 = decl_ref("std") token_offset:7:9 to :7:12
      %28 = dbg_stmt(5, 12)
      %29 = field_ptr(%27, "testing") node_offset:7:9 to :7:20
      %30 = dbg_stmt(5, 20)
      %31 = dbg_stmt(5, 27)
      %32 = field_call(.auto, %29, "expect", [
        {
          %33 = cmp_eq(%24, @zero) node_offset:7:28 to :7:34
          %34 = break_inline(%32, %33)
        },
      ]) node_offset:7:9 to :7:35
      %35 = try(%32, {
        %36 = err_union_code(%32) node_offset:7:5 to :7:35
        %37 = dbg_stmt(5, 5)
        %38 = ret_node(%36) node_offset:7:5 to :7:35
      }) node_offset:7:5 to :7:35
      %39 = ensure_result_used(%35) node_offset:7:5 to :7:35
      %40 = dbg_block_end()
      %41 = restore_err_ret_index(%5.none)
      %42 = break(%5, @void_value)
    For full context, use the command
      zig ast-check -t test2.zig

  in test2.zig: test2.zig:test_0
    > %5 = block({%6..%42}) node_offset:3:6 to :3:6

/home/meghan/src/zig/src/InternPool.zig:6997:17: 0x1b5653d in slicePtrType (zig)
        else => unreachable, // not a slice type
                ^
/home/meghan/src/zig/src/type.zig:1724:62: 0x186e36b in slicePtrFieldType (zig)
        return Type.fromInterned(mod.intern_pool.slicePtrType(ty.toIntern()));
                                                             ^
/home/meghan/src/zig/src/Sema.zig:32585:49: 0x2324708 in analyzeSlicePtr (zig)
    const result_ty = slice_ty.slicePtrFieldType(mod);
                                                ^
/home/meghan/src/zig/src/Sema.zig:22818:44: 0x27ffbdd in ptrCastFull (zig)
        break :ptr try sema.analyzeSlicePtr(block, operand_src, operand, operand_ty);
                                           ^
/home/meghan/src/zig/src/Sema.zig:22552:28: 0x2295a26 in zirPtrCast (zig)
    return sema.ptrCastFull(
                           ^
/home/meghan/src/zig/src/Sema.zig:1138:65: 0x1e3d4e8 in analyzeBodyInner (zig)
            .ptr_cast                     => try sema.zirPtrCast(block, inst),
                                                                ^
/home/meghan/src/zig/src/Sema.zig:5978:34: 0x27e41c7 in resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
/home/meghan/src/zig/src/Sema.zig:5961:33: 0x230950f in zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                ^
/home/meghan/src/zig/src/Sema.zig:1602:49: 0x1e4926b in analyzeBodyInner (zig)
                    break :blk try sema.zirBlock(block, inst, tags[@intFromEnum(inst)] == .block_comptime);
                                                ^
/home/meghan/src/zig/src/Sema.zig:922:30: 0x215e7b8 in analyzeBody (zig)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                             ^
/home/meghan/src/zig/src/Module.zig:4878:21: 0x1e0be57 in analyzeFnBody (zig)
    sema.analyzeBody(&inner_block, fn_info.body) catch |err| switch (err) {
                    ^
/home/meghan/src/zig/src/Module.zig:3552:32: 0x1b299c1 in ensureFuncBodyAnalyzed (zig)
    var air = zcu.analyzeFnBody(func_index, sema_arena) catch |err| switch (err) {
                               ^
/home/meghan/src/zig/src/Compilation.zig:3579:42: 0x1b27b53 in processOneJob (zig)
            module.ensureFuncBodyAnalyzed(func) catch |err| switch (err) {
                                         ^
/home/meghan/src/zig/src/Compilation.zig:3508:30: 0x18d1ffa in performAllTheWork (zig)
            try processOneJob(comp, work_item, main_progress_node);
                             ^
/home/meghan/src/zig/src/Compilation.zig:2191:31: 0x18cdc7b in update (zig)
    try comp.performAllTheWork(main_progress_node);
                              ^
/home/meghan/src/zig/src/main.zig:4500:24: 0x18fdcfc in updateModule (zig)
        try comp.update(main_progress_node);
                       ^
/home/meghan/src/zig/src/main.zig:3353:17: 0x191c107 in buildOutputType (zig)
    updateModule(comp, color) catch |err| switch (err) {
                ^
/home/meghan/src/zig/src/main.zig:283:31: 0x17069a9 in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .zig_test);
                              ^
/home/meghan/src/zig/src/main.zig:223:20: 0x17037f5 in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/home/meghan/src/zig/lib/std/start.zig:511:37: 0x170326e in main (zig)
            const result = root.main() catch |err| {
                                    ^
???:?:?: 0x7f8dca63dacd in ??? (libc.so.6)
Unwind information for `libc.so.6:0x7f8dca63dacd` was not available, trace may be incomplete

Aborted (core dumped)
```

### Expected Behavior

test pass

### PR DESCRIPTION
**Pull request by garrisonhh**
`ptrCastFull` in Sema now considers that the source type could be an optional slice type being cast to an allowzero pointer. Also added a behavior test case which reproduces the issue

Closes #18913

### CODE REVIEW

**Comment by nektro** [comment]
nice work! can you add both cases from the issue?

**Comment by Rexicon226** [comment]
note: you should add `fixes #18913` in your initial comment here for it to close. not in the title :)

**Comment by mlugg** [comment]
This logic is incorrect since it forces the operation to occur at runtime for null values (the `orelse` drops us into the runtime path) - I haven't checked, but I'm pretty sure this would fail if the test were run in a comptime scope. I can explain how to fix this correctly at some point - drop me a ping tomorrow since I'll forget!

**Comment by garrisonhh** [comment]
Thanks for the help everyone. I think I figured it out, I was confused about how `Value.optionalValue` behaves. Is this correct? (@mlugg) I tested this on my own machine, would creating a file in `tests/cases` be the proper way to add a test for this?

**Pull request merged**
