### PR TITLE
Replace deprecated default initializations with decl literals

### PR DESCRIPTION
**Pull request by linusg**
Follow-up to https://github.com/ziglang/zig/commit/0b9fccf508dc85fa522947d1cf6ff84f78f2dcb4.

### CODE REVIEW

**Comment by linusg** [comment]
ah, I suppose this needs a zig1.wasm update to work...

**Comment by mlugg** [comment]
Yep, that's why I held off on doing it in that PR. However, this work is still valuable, so keep it around! Once we've done a zig1.wasm update we can merge this.

By the way, I haven't looked over all of the changes here, but `InternPool` shouldn't use default values at all -- instead, it should probably expose a `pub const empty: InternPool = ...`. That's because many of the field values are tied together.

**Comment by mlugg** [comment]
@linusg #21367 contained a zig1.wasm update, so you should be good to go ahead with this branch now if you rebase!

**Comment by linusg** [comment]
Rebased, did a quick sweep of newly added `= .{}`, added `InternPool.empty` in a separate commit.

**Review by mlugg — APPROVED** [review]

**Pull request merged**
