### PR TITLE
Fixes to divsf3

### PR DESCRIPTION
**Pull request by vegecode**
Embarrassingly failed to notice a section that was unchanged from where
it was copied from mulXf3.zig. The test cases for this function series
div{s,d,t}f3 are very incomplete and don't exercise all code paths.

Remove unnecessary switch from divsf3 left during development from when
I tried to make it generic to support f32, f64, and f128 in one go.

Make runtime safety dependent on whether a test is being run.

### CODE REVIEW

**Comment by vegecode** [comment]
Sorry! I was trying to go faster so that someone else didn't get it in before me and made this mistake. I went back through everything again with a fresh eye and the rest seem fine to me.

I am working on the other functions divdf3, divtf3 now.

**Comment by andrewrk** [comment]
Thanks for the follow-up.

Are you basing the code on the corresponding llvm compiler rt code or on mulXf3.zig? In general the code should be ported from the llvm compiler rt code.

**Comment by vegecode** [comment]
I am porting it from the compiler-rt code like the file header says. When I originally did the mulXf3 code (which you completed before I managed to), I did it differently than you and so I was heavily referencing your implementation so that the other compiler-rt functions would have the same style.

This was just a mistake copy. I don't remember exactly but my intention was probably to just grab the top part with all the definitions from "fplib.h".

When I did mulXf3, I made a generic structure with the functions and constants from fplib.h that I was going to instantiate in each of the mulsf3, muldf3, multf3 functions. I haven't written a lot of Zig code, but that seemed the most direct translation I could think of from the way it's implemented in compiler-rt.

I wonder if it's possible to do something like:
```
usingnamespace @import("generic.zig").generic_struct(f32);
```
to get all the constants imported. 

Would having one file that contains "normalize" for example lead to reduced code size for when fdiv and fmul are both used in a program since they both use the normalize function? In the C implementations I think that code would literally be duplicated inline instead of being called. I was going to experiment with that once I got these functions I need in.

**Comment by vegecode** [comment]
I've got the divdf3 done now too. Is it ok to attach it to this pull request also?

**Comment by andrewrk** [comment]
I went ahead and merged this one, can you do a new one for divdf3?

**Pull request merged**
