### PR TITLE
wasm: do not default to pic and re-enable tests

### LINKED ISSUE #16937: LLVM 17 regression: link.wasm.export-data.test
In the llvm17 branch, this test is failing:

```
└─ link.wasm.export-data.test transitive failure
   └─ CheckObject failure
```

```
test.link.wasm.export-data.CheckObject: error: 
========= expected to find: ==========================
index 1
========= but parsed file does not contain it: =======
Section import
size 26
entries 1
module env
name __memory_base
kind global
type i32
mutable true
Section table
size 8
entries 1
type funcref
min 0
Section memory
size 7
entries 1
min 11
Section global
size 23
entries 3
type i32
mutable true
i32.const 100010
type i32
mutable false
i32.const 4
type i32
mutable false
i32.const 0
Section export
size 26
entries 3
name foo
kind global
index 2
name bar
kind global
index 3
name memory
kind memory
index 0
Section data
size 18
entries 1
memory index 0x0
i32.const 0
size 8
Section custom
size 55
name name
type function
size 1
names 0
type global
size 33
names 2
index 0
name __stack_pointer
index 0
name __memory_base
type data_segment
size 10
names 1
index 0
name .rodata
Section custom
size 1777
name .debug_info
Section custom
size 523
name .debug_pubtypes
Section custom
size 212
name .debug_abbrev
Section custom
size 250
name .debug_line
Section custom
size 2136
name .debug_str
Section custom
size 427
name .debug_pubnames
Section custom
size 93
name producers
fields 2
field_name language
values 1
value_name Zig
version 0.12.0-dev.193+0aa9b5d32
field_name processed-by
values 1
value_name Zig
version 0.12.0-dev.193+0aa9b5d32
Section custom
size 44
name target_features
features 2
+ mutable-globals
+ sign-ext
```

Reproduce by running `zig build test-link`.

### LINKED ISSUE #16938: LLVM 17 regression: link.wasm.archive.test
In the llvm17 branch, this test is failing:

```
test-link transitive failure
├─ link.wasm.archive.test transitive failure
│  ├─ CheckObject transitive failure
│  │  └─ zig build-lib main Debug wasm32-freestanding failure
│  ├─ CheckObject transitive failure
│  │  └─ zig build-lib main ReleaseFast wasm32-freestanding failure
│  ├─ CheckObject transitive failure
│  │  └─ zig build-lib main ReleaseSmall wasm32-freestanding failure
│  └─ CheckObject transitive failure
│     └─ zig build-lib main ReleaseSafe wasm32-freestanding failure
```

```
test.link.wasm.archive.zig build-lib main Debug wasm32-freestanding: error: thread 3640431 panic: reached unreachable code
/home/andy/misc/zig/lib/std/os.zig:303:18: 0x64630f3 in close (zig)
        .BADF => unreachable, // Always a race condition.
                 ^
/home/andy/misc/zig/lib/std/fs/file.zig:211:21: 0x626202a in close (zig)
            os.close(self.handle);
                    ^
/home/andy/misc/zig/src/link/Wasm/Archive.zig:218:31: 0x6cb1bef in parseObject (zig)
    errdefer object_file.close();
                              ^
/home/andy/misc/zig/src/link/Wasm.zig:851:49: 0x6cb6b7e in resolveSymbolsInArchives (zig)
            var object = try archive.parseObject(wasm.base.allocator, offset.items[0]);
                                                ^
/home/andy/misc/zig/src/link/Wasm.zig:3396:38: 0x689f8f9 in flushModule (zig)
    try wasm.resolveSymbolsInArchives();
                                     ^
/home/andy/misc/zig/src/link/Wasm.zig:3140:32: 0x65d44e6 in flush (zig)
        return wasm.flushModule(comp, prog_node);
                               ^
/home/andy/misc/zig/src/link.zig:814:70: 0x636fa73 in flush (zig)
            .wasm => return @fieldParentPtr(Wasm, "base", base).flush(comp, prog_node),
                                                                     ^
/home/andy/misc/zig/src/Compilation.zig:2214:24: 0x636f145 in flush (zig)
    comp.bin_file.flush(comp, prog_node) catch |err| switch (err) {
                       ^
/home/andy/misc/zig/src/Compilation.zig:2171:23: 0x63a48e3 in update (zig)
        try comp.flush(main_progress_node);
                      ^
/home/andy/misc/zig/src/main.zig:3662:36: 0x63d0d44 in serve (zig)
                    try comp.update(main_progress_node);
                                   ^
/home/andy/misc/zig/src/main.zig:3476:22: 0x63f3f7d in buildOutputType (zig)
            try serve(
                     ^
/home/andy/misc/zig/src/main.zig:272:31: 0x625f717 in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .{ .build = .Lib });
                              ^
/home/andy/misc/zig/src/main.zig:214:20: 0x625c9c5 in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/home/andy/misc/zig/lib/std/start.zig:486:37: 0x625c3de in main (zig)
    std.os.argv = @as([*][*:0]u8, @ptrCast(c_argv))[0..@as(usize, @intCast(c_argc))];
                                    ^
???:?:?: 0x7f56becee24d in ??? (libc.so.6)
Unwind information for `libc.so.6:0x7f56becee24d` was not available, trace may be incomplete

???:?:?: 0x7ffc205397c5 in ??? (???)

test.link.wasm.archive.zig build-lib main Debug wasm32-freestanding: error: the following command terminated unexpectedly:
/home/andy/misc/zig/build-release/stage4/bin/zig build-lib -fno-llvm -fno-lld /home/andy/misc/zig/test/link/wasm/archive/main.zig -fno-strip --cache-dir /home/andy/misc/zig/zig-cache --global-cache-dir /home/andy/.cache/zig --name main -dynamic -target wasm32-freestanding -mcpu generic --listen=- 
test.link.wasm.archive.zig build-lib main ReleaseSafe wasm32-freestanding: error: thread 3640557 panic: reached unreachable code
/home/andy/misc/zig/lib/std/os.zig:303:18: 0x64630f3 in close (zig)
        .BADF => unreachable, // Always a race condition.
                 ^
/home/andy/misc/zig/lib/std/fs/file.zig:211:21: 0x626202a in close (zig)
            os.close(self.handle);
                    ^
/home/andy/misc/zig/src/link/Wasm/Archive.zig:218:31: 0x6cb1bef in parseObject (zig)
    errdefer object_file.close();
                              ^
/home/andy/misc/zig/src/link/Wasm.zig:851:49: 0x6cb6b7e in resolveSymbolsInArchives (zig)
            var object = try archive.parseObject(wasm.base.allocator, offset.items[0]);
                                                ^
/home/andy/misc/zig/src/link/Wasm.zig:3396:38: 0x689f8f9 in flushModule (zig)
    try wasm.resolveSymbolsInArchives();
                                     ^
/home/andy/misc/zig/src/link/Wasm.zig:3140:32: 0x65d44e6 in flush (zig)
        return wasm.flushModule(comp, prog_node);
                               ^
/home/andy/misc/zig/src/link.zig:814:70: 0x636fa73 in flush (zig)
            .wasm => return @fieldParentPtr(Wasm, "base", base).flush(comp, prog_node),
                                                                     ^
/home/andy/misc/zig/src/Compilation.zig:2214:24: 0x636f145 in flush (zig)
    comp.bin_file.flush(comp, prog_node) catch |err| switch (err) {
                       ^
/home/andy/misc/zig/src/Compilation.zig:2171:23: 0x63a48e3 in update (zig)
        try comp.flush(main_progress_node);
                      ^
/home/andy/misc/zig/src/main.zig:3662:36: 0x63d0d44 in serve (zig)
                    try comp.update(main_progress_node);
                                   ^
/home/andy/misc/zig/src/main.zig:3476:22: 0x63f3f7d in buildOutputType (zig)
            try serve(
                     ^
/home/andy/misc/zig/src/main.zig:272:31: 0x625f717 in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .{ .build = .Lib });
                              ^
/home/andy/misc/zig/src/main.zig:214:20: 0x625c9c5 in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/home/andy/misc/zig/lib/std/start.zig:486:37: 0x625c3de in main (zig)
    std.os.argv = @as([*][*:0]u8, @ptrCast(c_argv))[0..@as(usize, @intCast(c_argc))];
                                    ^
???:?:?: 0x7f345457a24d in ??? (libc.so.6)
Unwind information for `libc.so.6:0x7f345457a24d` was not available, trace may be incomplete

???:?:?: 0x7fffa8bfb7b7 in ??? (???)

test.link.wasm.archive.zig build-lib main ReleaseSafe wasm32-freestanding: error: the following command terminated unexpectedly:
/home/andy/misc/zig/build-release/stage4/bin/zig build-lib -fno-llvm -fno-lld /home/andy/misc/zig/test/link/wasm/archive/main.zig -fno-strip -OReleaseSafe --cache-dir /home/andy/misc/zig/zig-cache --global-cache-dir /home/andy/.cache/zig --name main -dynamic -target wasm32-freestanding -mcpu generic --listen=- 
test.link.wasm.archive.zig build-lib main ReleaseSmall wasm32-freestanding: error: thread 3640503 panic: reached unreachable code
/home/andy/misc/zig/lib/std/os.zig:303:18: 0x64630f3 in close (zig)
        .BADF => unreachable, // Always a race condition.
                 ^
/home/andy/misc/zig/lib/std/fs/file.zig:211:21: 0x626202a in close (zig)
            os.close(self.handle);
                    ^
/home/andy/misc/zig/src/link/Wasm/Archive.zig:218:31: 0x6cb1bef in parseObject (zig)
    errdefer object_file.close();
                              ^
/home/andy/misc/zig/src/link/Wasm.zig:851:49: 0x6cb6b7e in resolveSymbolsInArchives (zig)
            var object = try archive.parseObject(wasm.base.allocator, offset.items[0]);
                                                ^
/home/andy/misc/zig/src/link/Wasm.zig:3396:38: 0x689f8f9 in flushModule (zig)
    try wasm.resolveSymbolsInArchives();
                                     ^
/home/andy/misc/zig/src/link/Wasm.zig:3140:32: 0x65d44e6 in flush (zig)
        return wasm.flushModule(comp, prog_node);
                               ^
/home/andy/misc/zig/src/link.zig:814:70: 0x636fa73 in flush (zig)
            .wasm => return @fieldParentPtr(Wasm, "base", base).flush(comp, prog_node),
                                                                     ^
/home/andy/misc/zig/src/Compilation.zig:2214:24: 0x636f145 in flush (zig)
    comp.bin_file.flush(comp, prog_node) catch |err| switch (err) {
                       ^
/home/andy/misc/zig/src/Compilation.zig:2171:23: 0x63a48e3 in update (zig)
        try comp.flush(main_progress_node);
                      ^
/home/andy/misc/zig/src/main.zig:3662:36: 0x63d0d44 in serve (zig)
                    try comp.update(main_progress_node);
                                   ^
/home/andy/misc/zig/src/main.zig:3476:22: 0x63f3f7d in buildOutputType (zig)
            try serve(
                     ^
/home/andy/misc/zig/src/main.zig:272:31: 0x625f717 in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .{ .build = .Lib });
                              ^
/home/andy/misc/zig/src/main.zig:214:20: 0x625c9c5 in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/home/andy/misc/zig/lib/std/start.zig:486:37: 0x625c3de in main (zig)
    std.os.argv = @as([*][*:0]u8, @ptrCast(c_argv))[0..@as(usize, @intCast(c_argc))];
                                    ^
???:?:?: 0x7feaa4a7c24d in ??? (libc.so.6)
Unwind information for `libc.so.6:0x7feaa4a7c24d` was not available, trace may be incomplete

???:?:?: 0x7fff749107b6 in ??? (???)

test.link.wasm.archive.zig build-lib main ReleaseSmall wasm32-freestanding: error: the following command terminated unexpectedly:
/home/andy/misc/zig/build-release/stage4/bin/zig build-lib -fno-llvm -fno-lld /home/andy/misc/zig/test/link/wasm/archive/main.zig -fno-strip -OReleaseSmall --cache-dir /home/andy/misc/zig/zig-cache --global-cache-dir /home/andy/.cache/zig --name main -dynamic -target wasm32-freestanding -mcpu generic --listen=- 
test.link.wasm.archive.zig build-lib main ReleaseFast wasm32-freestanding: error: thread 3640467 panic: reached unreachable code
/home/andy/misc/zig/lib/std/os.zig:303:18: 0x64630f3 in close (zig)
        .BADF => unreachable, // Always a race condition.
                 ^
/home/andy/misc/zig/lib/std/fs/file.zig:211:21: 0x626202a in close (zig)
            os.close(self.handle);
                    ^
/home/andy/misc/zig/src/link/Wasm/Archive.zig:218:31: 0x6cb1bef in parseObject (zig)
    errdefer object_file.close();
                              ^
/home/andy/misc/zig/src/link/Wasm.zig:851:49: 0x6cb6b7e in resolveSymbolsInArchives (zig)
            var object = try archive.parseObject(wasm.base.allocator, offset.items[0]);
                                                ^
/home/andy/misc/zig/src/link/Wasm.zig:3396:38: 0x689f8f9 in flushModule (zig)
    try wasm.resolveSymbolsInArchives();
                                     ^
/home/andy/misc/zig/src/link/Wasm.zig:3140:32: 0x65d44e6 in flush (zig)
        return wasm.flushModule(comp, prog_node);
                               ^
/home/andy/misc/zig/src/link.zig:814:70: 0x636fa73 in flush (zig)
            .wasm => return @fieldParentPtr(Wasm, "base", base).flush(comp, prog_node),
                                                                     ^
/home/andy/misc/zig/src/Compilation.zig:2214:24: 0x636f145 in flush (zig)
    comp.bin_file.flush(comp, prog_node) catch |err| switch (err) {
                       ^
/home/andy/misc/zig/src/Compilation.zig:2171:23: 0x63a48e3 in update (zig)
        try comp.flush(main_progress_node);
                      ^
/home/andy/misc/zig/src/main.zig:3662:36: 0x63d0d44 in serve (zig)
                    try comp.update(main_progress_node);
                                   ^
/home/andy/misc/zig/src/main.zig:3476:22: 0x63f3f7d in buildOutputType (zig)
            try serve(
                     ^
/home/andy/misc/zig/src/main.zig:272:31: 0x625f717 in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .{ .build = .Lib });
                              ^
/home/andy/misc/zig/src/main.zig:214:20: 0x625c9c5 in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/home/andy/misc/zig/lib/std/start.zig:486:37: 0x625c3de in main (zig)
    std.os.argv = @as([*][*:0]u8, @ptrCast(c_argv))[0..@as(usize, @intCast(c_argc))];
                                    ^
???:?:?: 0x7f8aa5c3824d in ??? (libc.so.6)
Unwind information for `libc.so.6:0x7f8aa5c3824d` was not available, trace may be incomplete

???:?:?: 0x7ffddb2bf7b7 in ??? (???)

test.link.wasm.archive.zig build-lib main ReleaseFast wasm32-freestanding: error: the following command terminated unexpectedly:
/home/andy/misc/zig/build-release/stage4/bin/zig build-lib -fno-llvm -fno-lld /home/andy/misc/zig/test/link/wasm/archive/main.zig -fno-strip -OReleaseFast --cache-dir /home/andy/misc/zig/zig-cache --global-cache-dir /home/andy/.cache/zig --name main -dynamic -target wasm32-freestanding -mcpu generic --listen=- 
```

Reproduce by running `zig build test-link`.

Note that this test actually does not use LLVM or LLD:

```zig
    lib.use_llvm = false;
    lib.use_lld = false;
```

More investigation is needed to understand the connection to this test failure and the LLVM 17 upgrade.

### PR DESCRIPTION
**Pull request by Luukdegram**
For WebAssembly we want DynamicNoPIC for relocation mode. PIC is experimental, but will also force a shared library for WebAssembly which is not what the user expects as that will require runtime relocations to be performed.
This also re-enables the linker tests that regressed with llvm17

Closes #16937
Closes #16938 

#16938 mentions:
> Note that this test actually does not use LLVM or LLD:

The linker test verifies being able to link with an archive file. Since the Zig toolchain doesn't have an ar implementation yet, the test depends on compiler_rt, which is generated by LLVM. Due to LLVM17 actually supporting outputting PIC for WebAssembly, it generates a bunch of sections and relocations the in-house linker hasn't implemented yet. (Unfortunately, the stack trace is 💩 due to a double `close` to the file handle, which will be fixed in a separate PR).

### CODE REVIEW

**Comment by andrewrk** [comment]
Thanks!

**Comment by andrewrk** [comment]
hmmm for compiler_rt specifically, we're passing static:

https://github.com/ziglang/zig/blob/dd6a9caeaf98b0f1c3c91291dab46e62b224c94f/src/Compilation.zig#L5487

**Comment by andrewrk** [comment]
OK the reason that link_mode is being set to Dynamic is because the tests are literally asking for it:

```
    const lib = b.addSharedLibrary(.{
```

> force a shared library

that's exactly what's being asked for in the build.zig script.

**Comment by Luukdegram** [comment]
> OK the reason that link_mode is being set to Dynamic is because the tests are literally asking for it:
> 
> ```
>     const lib = b.addSharedLibrary(.{
> ```
> 
> > force a shared library
> 
> that's exactly what's being asked for in the build.zig script.

You're completely right, but we're currently in this odd position where users really just want a singular Wasm binary that's static and doesn't have an entry point but doesn't want an archive file (so don't build a static library). Perhaps we should instead use `build-exe/addExecutable` and use `-no-entry`, just like other compilers such as Clang and Rust do. For context, in https://github.com/ziglang/zig/pull/8857 the original behavior was changed by Jakub and users have to use `-dynamic` to build a loadable WebAssembly module. However, WebAssemly does in fact have a concept of dynamic libraries now, which is not what the test wants to build. There's currently (in llvm17 branch) no way to express a single static Wasm binary that can be loaded into a runtime/browser but does not have an entry point.

**Comment by andrewrk** [comment]
I agree with your reasoning -  build-exe with `-fno-entry` is the way to go. Also I think it's generally good to join in with Clang and Rust unless there is some really good reason to be different.

**Comment by Luukdegram** [comment]
No worries about the force push - Let's close this PR for now and I'll work on the proper fixes in a separate branch so the llvm17 work can get merged into master when ready. We can re-enable the linker tests in the branch with the proper fix in master later.

**Pull request closed without merging**
