### PR TITLE
Use struct_init_one for no-initializer struct

### LINKED ISSUE #18093: Translate-C panics on static empty struct
### Zig Version

0.12.0-dev.1710+2bffd8101

### Steps to Reproduce and Observed Behavior

Run `zig translate-c header.h` on the following `header.h`:
```
struct empty_struct {};

static inline void foo() {
    static struct empty_struct bar = {};
}
```

### Expected Behavior

Translate-c should not panic.

### PR DESCRIPTION
**Pull request by garrettlennoxbeck**
Closes #18093 
`test.h`:
```
struct empty_struct {};

static inline void foo() {
    static struct empty_struct bar = {};
}
```
`zig translate-c test.h` relevant output:
```
pub const struct_empty_struct = extern struct {};
pub fn foo() callconv(.C) void {
    const bar = struct {
        var static: struct_empty_struct = struct_empty_struct{};
    };
    _ = &bar;
}
```

### CODE REVIEW

**Comment by Vexu** [comment]
Could you add that reduction as a test case?

You can see an example tests in `test/cases/translate_c/enums.c` and `test/cases/README.md`.

**Comment by garrettlennoxbeck** [comment]
1. I added the test case as `test/cases/translate_c/static empty struct.c`
2. The needed to change some code in `test/src/Cases.zig` to allow the manifest to contain spaces before code, as the output is an indented function. Otherwise, the output would never match because a `trim` call would remove the indentation. Now, the manifest must be in the form of a forward slash, forward slash, space, then code, which is how all cases currently do it. Please check that I got that correct as well.

**Comment by garrettlennoxbeck** [comment]
One other note: the test I added is only run for the clang frontend, not the aro frontend, because if I try to add the aro frontend I hit this panic:

https://github.com/ziglang/zig/blob/3acb0e30a06d7ef7ece9257bc3423b9c85a12c06/src/aro_translate_c.zig#L299-L301

**Comment by Vexu** [comment]
> 2\. I needed to change some code in `test/src/Cases.zig` to allow the manifest to contain spaces before code, as the output is an indented function

Ah, looks like I missed that because my test cases didn't have any indentation. Looks good except I'd check the length after trimming to not require a space on empty lines:
```zig
const trimmed = std.mem.trimRight(next_inner, " \t");
if (trimmed.len == 2) return "";
return trimmed[3..];
```

**Comment by garrettlennoxbeck** [comment]
I think I worded my comment poorly; blank lines don't require a space because of the `if (next_inner.len == 2)` check at the beginning of line `979`. I just meant to say that non-blank lines will strip a single character off the beginning after the `//` because existing tests use that space for non-blank lines, rather than the previous behavior of stripping all spaces/tabs from the beginning. For example, `test/cases/translate_c/enums.c` contains a blank line with no spaces and passes with the new code. I believe your code is functionally identical to mine.

**Review by Vexu — APPROVED** [review]
My version also handles empty lines with trailing whitespace but I guess that won't be an issue as long as the files are properly formatted.

**Pull request merged**
