### PR TITLE
snake_case std.zig

### PR DESCRIPTION
**Pull request by Vexu**
If we want to apply #2101 to `std.zig` now is a good time to do so.

### CODE REVIEW

**Comment by andrewrk** [comment]
Agreed.

Godspeed.

**Comment by squeek502** [comment]
Was it decided that errors would be affected by this? From https://github.com/ziglang/zig/issues/2101#issuecomment-570954377:

> > Will this style be applied to errors too? (Tangentially related: #2647)
> 
> No, I think errors can remain as is.

**Comment by andrewrk** [comment]
I don't see any reason to change errors. Note that some things in this PR look like errors but those are actually enum tags.

Oh, @Vexu, there is *one* possible reason to delay doing this change, which is that it's in the future we may have the ability to offer powerful IDE-like identifier rename functionality. If we had this, it would make this task easier, but, more importantly, it would also make it easier for all the users to update to the new names.

That said, I'm perfectly content with you doing this change now regardless. It's your call.

**Comment by pixelherodev** [comment]
@andrewrk @Vexu I'm taking a break from #5422 to finish implementing a renamer over the self-hosted parser  :)

I hope to have basic usability in the next few days  :)

**Comment by andrewrk** [comment]
this effort looks abandoned

**Pull request closed without merging**
