### PR TITLE
`std.equalRange`: Compute lower and upper bounds simultaneously.

### PR DESCRIPTION
**Pull request by LucasSantos91**
The current implementation of `equalRange` just calls `lowerRange` and `upperRange`, but a lot of
the work done by these two functions can be shared. Specifically, each iteration gives information about whether the lower bound or the upper bound can be tightened. This leads to fewer iterations and, since there is one comparison per iteration, fewer comparisons.
Implementation adapted from [GCC](https://github.com/gcc-mirror/gcc/blob/519ec1cfe9d2c6a1d06709c52cb103508d2c42a7/libstdc%2B%2B-v3/include/bits/stl_algo.h#L2063).
This sample demonstrates the difference between the current implementation and mine:

```zig
fn S(comptime T: type) type {
    return struct {
        needle: T,
        count: *usize,

        pub fn order(context: @This(), item: T) std.math.Order {
            context.count.* += 1;
            return std.math.order(item, context.needle);
        }
        pub fn orderLength(context: @This(), item: []const u8) std.math.Order {
            context.count.* += 1;
            return std.math.order(item.len, context.needle);
        }
    };
}
pub fn main() !void {
    var count: usize = 0;

    try std.testing.expectEqual(.{ 0, 0 }, equalRange(i32, &[_]i32{}, S(i32){ .needle = 0, .count = &count }, S(i32).order));
    try std.testing.expectEqual(.{ 0, 0 }, equalRange(i32, &[_]i32{ 2, 4, 8, 16, 32, 64 }, S(i32){ .needle = 0, .count = &count }, S(i32).order));
    try std.testing.expectEqual(.{ 0, 1 }, equalRange(i32, &[_]i32{ 2, 4, 8, 16, 32, 64 }, S(i32){ .needle = 2, .count = &count }, S(i32).order));
    try std.testing.expectEqual(.{ 2, 2 }, equalRange(i32, &[_]i32{ 2, 4, 8, 16, 32, 64 }, S(i32){ .needle = 5, .count = &count }, S(i32).order));
    try std.testing.expectEqual(.{ 2, 3 }, equalRange(i32, &[_]i32{ 2, 4, 8, 16, 32, 64 }, S(i32){ .needle = 8, .count = &count }, S(i32).order));
    try std.testing.expectEqual(.{ 5, 6 }, equalRange(i32, &[_]i32{ 2, 4, 8, 16, 32, 64 }, S(i32){ .needle = 64, .count = &count }, S(i32).order));
    try std.testing.expectEqual(.{ 6, 6 }, equalRange(i32, &[_]i32{ 2, 4, 8, 16, 32, 64 }, S(i32){ .needle = 100, .count = &count }, S(i32).order));
    try std.testing.expectEqual(.{ 2, 6 }, equalRange(i32, &[_]i32{ 2, 4, 8, 8, 8, 8, 15, 22 }, S(i32){ .needle = 8, .count = &count }, S(i32).order));
    try std.testing.expectEqual(.{ 2, 2 }, equalRange(u32, &[_]u32{ 2, 4, 8, 16, 32, 64 }, S(u32){ .needle = 5, .count = &count }, S(u32).order));
    try std.testing.expectEqual(.{ 1, 1 }, equalRange(f32, &[_]f32{ -54.2, -26.7, 0.0, 56.55, 100.1, 322.0 }, S(f32){ .needle = -33.4, .count = &count }, S(f32).order));
    try std.testing.expectEqual(.{ 3, 5 }, equalRange(
        []const u8,
        &[_][]const u8{ "Mars", "Venus", "Earth", "Saturn", "Uranus", "Mercury", "Jupiter", "Neptune" },
        S(usize){ .needle = 6, .count = &count },
        S(usize).orderLength,
    ));

    std.debug.print("Count: {}\n", .{count});
}
```
For each comparison, we bump the count. With the current implementation, we get 57 comparisons. With mine, we get 43.

This optimization is orthogonal to left-bias proposed by [21278](https://github.com/ziglang/zig/pull/21278)

### CODE REVIEW

**Comment by Olvilock** [comment]
After the equal element is found, you discard information about bounds already computed in `low` and `high`, essentially precomputing `binarySearch`, and using `lowerBound` and `upperBound` on both halves. This can still be improved with little effort:
`pub fn equalRange(
    comptime T: type,
    items: []const T,
    context: anytype,
    comptime compareFn: fn (@TypeOf(context), T) std.math.Order,
) struct { usize, usize } {
    var low: usize = 0;
    var high: usize = items.len;

    while (low < high) {
        const mid = low + (high - low) / 2;
        switch (compareFn(context, items[mid])) {
            .lt => low = mid + 1,
            .gt => high = mid,
            .eq => return .{
                low + lowerBound(T, items[low..mid], context, compareFn),
                mid + upperBound(T, items[mid..high], context, compareFn),
            },
        }
    }
    return .{ low, low };
}`

**Comment by LucasSantos91** [comment]
Thanks, @Olvilock.

**Comment by Olvilock** [comment]
I've (re)implemented a little [benchmark](https://gist.github.com/Olvilock/c17cf69b37bdcfea9366202a84eb7bf1) that compares this pull request with [21278](https://github.com/ziglang/zig/pull/21278) and the current stdlib implementation on random requests over a dictionary sorted by first two letters. To reproduce the results, `curl` this [words.txt](https://raw.githubusercontent.com/dwyl/english-words/master/words.txt) file.
My results (using the latest zig master):

$ zig/build/stage3/bin/zig run bench.zig -O ReleaseFast
Vanilla function: 2363 ms
Center-left function: 1992 ms
Center-left with 0.13.0 API function: 1965 ms
Simul function: 1610 ms
Totals: { 3872200000, 3872200000, 3872200000, 3872200000 }

$ zig/build/stage3/bin/zig run bench.zig -O ReleaseSafe
Vanilla function: 2386 ms
Center-left function: 2181 ms
Center-left with 0.13.0 API function: 2118 ms
Simul function: 1690 ms
Totals: { 3872200000, 3872200000, 3872200000, 3872200000 }

$ zig/build/stage3/bin/zig run bench.zig -O ReleaseSmall
Vanilla function: 2900 ms
Center-left function: 2540 ms
Center-left with 0.13.0 API function: 2583 ms
Simul function: 1995 ms
Totals: { 3872200000, 3872200000, 3872200000, 3872200000 }

The benchmark indicates that this pull request is the best of the three implementations tested on this use case.

**Comment by Olvilock** [comment]
Also, this implementation in the current form is incorrect, since the equalRange, lower- and upperBound functions use a confusing choice of ordering in the API, which led to incorrect (swapped) branches in the `.le` and the `.ge` prongs in this pull.

The analogous nasty bug happened in my pull, [21278](https://github.com/ziglang/zig/pull/21278), and in the tests present on the master branch too, I believe. It seems to me a change in the API is necessary.

**Comment by LucasSantos91** [comment]
Could you show an example that returns the incorrect result? I'm getting the correct result in all my tests.

**Comment by Olvilock** [comment]
Example test in this [gist](https://gist.github.com/Olvilock/6eb470cfae70aa4bd589a148e6e7826f).
Seek equal range of element 5 in array [_]u32{ 2, 3, 4, 5, 5 }

**Comment by LucasSantos91** [comment]
Ops, messed up the rebase. I will fix the bug mentioned by @Olvilock and reopen.

**Pull request closed without merging**
