### PR TITLE
Compiler: move checking function-scope-only builtins to AstGen

### PR DESCRIPTION
**Pull request by wrongnull**

### CODE REVIEW

**Review by Vexu — CHANGES_REQUESTED** [review]
This check should be in AstGen.

**Comment by wrongnull** [comment]
> This check should be in AstGen.

should I move check of all the functions such as ```@src``` or ```@setAlignStack``` to AstGen? If so, should I change the wording of the error message? Most of other builtins there use ```{builtinName} outside function scope``` meanwile ```@src``` for instance uses ```"@src outside function"```

**Comment by Vexu** [comment]
> should I move check of all the functions such as `@src` or `@setAlignStack` to AstGen?

Yes please.

> If so, should I change the wording of the error message?

That would be nice, and easier to implement since you can just switch on the builtin kind at the top of `builtinCall`.

**Comment by wrongnull** [comment]
> > should I move check of all the functions such as `@src` or `@setAlignStack` to AstGen?
> 
> Yes please.
> 
> > If so, should I change the wording of the error message?
> 
> That would be nice; and easier to implement since you can just switch on the builtin kind at the top of `builtinCall`.

It looks like ```astgen.fn_block``` is not ```null``` at least for comptime and test blocks. It's not yet clear for me, how to detect being exactly in function scope.

**Comment by nektro** [comment]
test blocks are indeed functions and should allow the builtins. it being non-null in comptime blocks seems sus though

**Comment by Vexu** [comment]
> It looks like `astgen.fn_block` is not `null` at least for comptime and test blocks. It's not yet clear for me, how to detect being exactly in function scope.

It is null for comptime blocks and correctly not null for tests:
```zig
comptime {
    try 1; //error: 'try' outside function scope
}
```

**Comment by wrongnull** [comment]
> > It looks like `astgen.fn_block` is not `null` at least for comptime and test blocks. It's not yet clear for me, how to detect being exactly in function scope.
> 
> It is null for comptime blocks and correctly not null for tests:
> 
> ```zig
> comptime {
>     try 1; //error: 'try' outside function scope
> }
> ```

not sure if latest commit contains complete list of such functions but I'm think it is

**Comment by wrongnull** [comment]
@Vexu forgot about ```@src``` sorry

**Review by andrewrk — COMMENTED** [review]
Before, there was only one branch on the builtin tag. Now it does it twice. The way it was before was better, where it had if statements inside each of the branches of the switch.

If you wish to consolidate this information and make it declarative, then add a field to src/BuiltinFn.zig, don't add another switch like this.

@Vexu

**Comment by wrongnull** [comment]
> Before, there was only one branch on the builtin tag. Now it does it twice. The way it was before was better, where it had if statements inside each of the branches of the switch.
> 
> If you wish to consolidate this information and make it declarative, then add a field to src/BuiltinFn.zig, don't add another switch like this.
> 
> @Vexu

I can rewrite it in next pr

**Comment by andrewrk** [comment]
Thanks

**Pull request merged**
