### PR TITLE
fix build on Ubuntu

### PR DESCRIPTION
**Pull request by shawnl**
Not sure why this is now broken, but it isn't a big deal to take this test out.

### CODE REVIEW

**Comment by andrewrk** [comment]
Can you explain why this doesn't work in Ubuntu? That static assert is protecting the kfreebsd target. What is the compile error you are getting?

**Comment by shawnl** [comment]
`[1/3] Building CXX object CMakeFiles/zig_cpp.dir/src/zig_llvm.cpp.o
FAILED: CMakeFiles/zig_cpp.dir/src/zig_llvm.cpp.o 
/usr/bin/c++   -I../deps/lld/include -I/usr/lib/llvm-7/include -I../deps/SoftFloat-3e/source/include -I../ -I. -I../src -g   -std=c++11 -Werror -Wall -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -D_GNU_SOURCE -fno-exceptions -fno-rtti  -Werror=strict-prototypes -Werror=old-style-definition -Werror=type-limits -Wno-missing-braces -MD -MT CMakeFiles/zig_cpp.dir/src/zig_llvm.cpp.o -MF CMakeFiles/zig_cpp.dir/src/zig_llvm.cpp.o.d -o CMakeFiles/zig_cpp.dir/src/zig_llvm.cpp.o -c ../src/zig_llvm.cpp
../src/zig_llvm.cpp:1032:59: error: ‘KFreeBSD’ is not a member of ‘llvm::Triple’
 static_assert((Triple::OSType)ZigLLVM_KFreeBSD == Triple::KFreeBSD, "");
                                                           ^~~~~~~~
ninja: build stopped: subcommand failed.
`

It appears that Ubuntu removed KFreeBSD from llvm

**Comment by shawnl** [comment]
This is Ubuntu 19.04,  but I also experienced this on Ubuntu 18.10

**Comment by andrewrk** [comment]
Here's the way I see this:

Ubuntu has mangled their LLVM package and it is no longer suitable to build Zig. At first my response is to say, sorry, Ubuntu LLVM packages are not supported, because they have patched out an OS that Zig supports.

However I looked up more details about kFreeBSD and it appears to be discontinued due to not being popular enough. So, I think an acceptable course of action is to remove kFreeBSD from the list of Zig supported OS targets. This would mean we can drop the static assert and Ubuntu's LLVM package will satisfy Zig's requirements.

**Comment by andrewrk** [comment]
I'd like to push back on Ubuntu with this. Why did they remove the kfreebsd target?

**Pull request closed without merging**
