### PR TITLE
fix autodoc comments formatting for atan2 and hypot

### PR DESCRIPTION
**Pull request by expikr**

### CODE REVIEW

**Comment by der-teufel-programming** [comment]
You can get the tables to render if you wrap them in ` ``` `

**Comment by der-teufel-programming** [comment]
obraz

**Review by Vexu — APPROVED** [review]

**Review by andrewrk — CHANGES_REQUESTED** [review]
The table is valid markdown, and it looks correct in source code. There should not be workarounds in .zig code to work around autodoc markdown parser being incorrect. The markdown parser in autodocs should be fixed instead.

**Comment by Vexu** [comment]
The CommonMark specification doesn't include tables.

**Comment by andrewrk** [comment]
CommonMark is [one person's effort](https://xkcd.com/927/) to standardize markdown. In practice, the popular markdown implementations support tables with this syntax.

**Comment by Vexu** [comment]
Autodocs will need to use a different markdown parser then.

**Pull request closed without merging**
