### PR TITLE
std.Progress: Fix Windows console API implementation

### PR DESCRIPTION
**Pull request by squeek502**
3a3d2187f986066859cfb793fb7ee1cae4dfea08 unintentionally broke some of the Windows console API implementation.

- The 'marker' character was no longer being written at all
- The ANSI escape codes for syncing were being written unconditionally

Unsure if this fixes the Wine behavior. Will test that in a second.

### CODE REVIEW

**Comment by andrewrk** [comment]
Thanks!

**Comment by squeek502** [comment]
Wine still incorrectly clears to the top of the screen with this, but that looks like a separate issue.

**Comment by andrewrk** [comment]
If it only happens on Wine then I don't think it's something we need to worry about other than reporting a bug on their issue tracker.

**Comment by squeek502** [comment]
As far as I can tell, Wine uses coordinates that are relative to the first line of the program's output. When printing `dwCursorPosition`:

```
$ wine console.exe
os.windows.COORD{ .X = 0, .Y = 0 }
os.windows.COORD{ .X = 0, .Y = 1 }
os.windows.COORD{ .X = 0, .Y = 2 }
os.windows.COORD{ .X = 0, .Y = 3 }
os.windows.COORD{ .X = 0, .Y = 4 }
```

(always the same regardless of where the lines are on the screen)

and `SetConsoleCursorPosition`/`FillConsoleOutputCharacterW` also take the same relative-to-the-start-of-output coordinates. But, for whatever reason, sometimes `SetConsoleCursorPosition`/`FillConsoleOutputCharacterW` will just start treating the coordinates as absolute (relative to the top of the screen) instead.

Have not figured out a pattern as to why it starts treating the coordinates as absolute.

**Pull request merged**
