### PR TITLE
Fill out windows PEB definition

### PR DESCRIPTION
**Pull request by daurnimator**
The PEB has evolved over the lifetime of windows, this PR adds more fields.

### CODE REVIEW

**Comment by daurnimator** [comment]
@andrewrk now with selectable OS version support: how can we customise the PEB for the target?
i.e. how can we write:
```zig
struct {
   foo: usize,
   if (version >= 0xABC) {
       bar: usize,
       baz: usize,
       qux: usize,
   } 
};
```

Options:
  - anonymous embedded structs? (https://github.com/ziglang/zig/issues/985)
  - `usingnamespace` could support fields?
  - helpers and `@reify` (https://github.com/ziglang/zig/issues/383)

**Comment by andrewrk** [comment]
> how can we customise the PEB for the target?

`field_name: VersionCheckedType(T, min_version),`

**Comment by andrewrk** [comment]
Nice - this led to 6fcf6716be3021d99d4972e8ca9b2139e1f8f40b

**Comment by daurnimator** [comment]
> `field_name: VersionCheckedType(T, min_version),`

And it would return void on non matches?

**Pull request merged**
