### PR TITLE
make self-hosted the default compiler

### LINKED ISSUE #89: self-hosted compiler: ship it!
This is a tracking issue for when we can completely replace stage1 with self-hosted in official builds of Zig.

 * [x] add debug info to the LLVM backend
   - [x] initial implementation #11085
   - [x]  #11095
   - [x]  #11096
   - [x]  #11097
   - [x]  #11145
   - [x]  #11158
   - [x]  #11160
 * [x] #11674
 * [x] get compilation errors into an acceptable state
   - [x] #11288
   - [x] #11632
 * [x] adjust the default backend to be LLVM until other backends reach full behavior test coverage
 * [ ] ~#6025~ async/await/suspend/resume will not be available in 0.10.0
 * [x] #6034
 * [x] #11159
 * [x] #11169
 * [x] #11251
 * [x] #11259
 * [x] all std lib tests passing with the LLVM backend
   - [x] #11898
   - [x] #11897
   - [x] #11857
   - [x] #11856
   - [x] #11853
   - [x] #12029
 * [x] #11450
 * [x] #11498
 * [x] #11767
 * [x] #11274
 * [x] full test suite passing with the LLVM backend
 * [ ] ~check all the TODO comments in stage2 source code and convert relevant ones into issues blocking this one~ #363
 * [x] Eliminate use of conditional compilation on zig_backend in compiler-rt, freestanding libc, test runner, and default panic
 * [x] use the real start code
 * [x] eliminate conditional compilation on zig_backend in the std lib
 * [x] Eliminate the other TODO items from generated builtin.zig file
 * [ ] work with individual third party projects to make sure the stage2 transition completes successfully
   - [ ] Bun (cc @Jarred-Sumner)
   - [ ] zig-gamedev (cc @michal-z)
   - [ ] mach (cc @slimsag)
   - [ ] River (cc @ifreund)
   - [ ] aquila (cc @nektro)
   - [ ] https://github.com/ominitay/zigvale-barebones (cc @ominitay)
   - [ ] [ncdu](https://dev.yorhel.nl/ncdu)
   - [ ] https://github.com/ZigEmbeddedGroup/microzig (`zig build -Drelease-small`)
   - [ ] https://github.com/mattnite/gyro (`zig build`, good amount of zig and C code in here)
   - [ ] [ZLS](https://github.com/zigtools/zls)
   - [ ] https://github.com/sin-ack/zigself
   - [ ] https://github.com/floooh/sokol-zig

### PR DESCRIPTION
**Pull request by andrewrk**
stage1 is available behind the `-fstage1` flag.

closes #89

### General
* [x] [create an upgrade guide to help smooth the process out for people who want to try the new compiler before the 0.10.0 release.](https://github.com/ziglang/zig/wiki/Self-Hosted-Compiler-Upgrade-Guide)
* [x] #12222
* [x] #12386
* [ ] ~add valgrind integration to self-hosted~ I'll do this later

### x86_64-freebsd
* [x] LavaTech outage
* [x] ZIG_EXECUTABLE set to bad value in ci script
* [x] stale CI tarball
* [x] ld: error: undefined symbol, compiler rt functions
* [x] not picking up libc headers, sys/endian.h

### aarch64-linux:
* [x] stage3 crashing building behavior tests
* [x] stage3 crashing building one of the test-compare-output cases

### x86_64-linux:
* [x] test-cases hanging
* [x] run-translated-c remainder test failing

### x86_64-macos:
* [x] error return traces on the wrong column
* [x] #12387
* [x] LLVM module verification failed
* [x] crashing when building langref

### x86_64-windows:
* [x] #12380
* [x] TLS miscompilation
* [x] stage1 OOM when building stage2
* [x] stage2 zig build failing with "error: FileNotFound"
* [x] not doing proper mangling of DLL export names

### CODE REVIEW

**Comment by EleanorNB** [comment]
YOOOOOOOOOOOOOOOOO

**Comment by EleanorNB** [comment]
Hang on a minute. #89 now says
> async/await/suspend/resume will not be available in 0.10.0
So what's the plan there? Do we fall back to stage1 if we see it? Do we just break all code? I feel like I must be out of the loop here.

**Comment by Vexu** [comment]
See #12345

**Comment by kubkon** [comment]
I did hit this when running a couple of test suites on arm64 macOS:

```
zig/build on  stage3-default [$!?] via C v13.1.6-clang via △ v3.22.3 via ↯ v0.10.0-dev.3433+cbac7a019                                                                                                                                
❯ ./stage3/bin/zig build test-link -Denable-macos-sdk                                                                                                                                                                                 
info: PASS build test/link/bss/build.zig (Debug)                                                                                                                                                                                      
All 2 tests passed.                                                                                                                                                                                                                   
info: PASS build test/link/common_symbols/build.zig (Debug)                                                                                                                                                                           
All 2 tests passed.                                                                                                                                                                                                                   
info: PASS build test/link/common_symbols/build.zig (ReleaseSafe)                                                                                                                                                                     
All 2 tests passed.                                                                                                                                                                                                                   
info: PASS build test/link/common_symbols/build.zig (ReleaseFast)                                                                                                                                                                     
All 2 tests passed.                                                                                                                                                                                                                   
info: PASS build test/link/common_symbols/build.zig (ReleaseSmall)                                                                                                                                                                    
All 1 tests passed.                                                                                                                                                                                                                   
info: PASS build test/link/common_symbols_alignment/build.zig (Debug)                                                                                                                                                                 
All 1 tests passed.                                                                                                                                                                                                                   
info: PASS build test/link/common_symbols_alignment/build.zig (ReleaseSafe)                                                                                                                                                           
All 1 tests passed.                                                                                                                                                                                                                   
info: PASS build test/link/common_symbols_alignment/build.zig (ReleaseFast)                                                                                                                                                           
All 1 tests passed.                                                                                                                                                                                                                   
info: PASS build test/link/common_symbols_alignment/build.zig (ReleaseSmall)                                                                                                                                                          
Segmentation fault at address 0x70                                                                                                                                                                                                    
???:?:?: 0x1025dcc24 in __ZN4llvm16cast_convert_valIN5clang16EnumConstantDeclEPNS1_4DeclES4_E4doitERKS4_ (???)                                                                                                                        
???:?:?: 0x10243ac67 in _ZigClangPreprocessingRecord_iterator_deref (???)                                                                                                                                                             
/Users/kubkon/dev/zig/src/translate_c.zig:452:32: 0x1010f9e7f in prepopulateGlobalNameTable (zig)                                                                                                                                     
        const entity = it.deref();                                                                                                                                                                                                    
                               ^                                                                                                                                                                                                      
/Users/kubkon/dev/zig/src/translate_c.zig:423:35: 0x101107563 in translate (zig)                                                                                                                                                      
    try prepopulateGlobalNameTable(ast_unit, &context);                                                                                                                                                                               
                                  ^                                                                                                                                                                                                   
/Users/kubkon/dev/zig/src/Compilation.zig:3446:41: 0x10111fd0f in cImport (zig)                                                                                                                                                       
        var tree = translate_c.translate(                                                                                                                                                                                             
                                        ^                                                                                                                                                                                             
/Users/kubkon/dev/zig/src/Sema.zig:4741:42: 0x1017ce66f in zirCImport (zig)                                                                                                                                                           
    const c_import_res = mod.comp.cImport(c_import_buf.items) catch |err|                                                                                                                                                             
                                         ^                                                                                                                                                                                            
/Users/kubkon/dev/zig/src/Sema.zig:717:65: 0x10166f8af in analyzeBodyInner (zig)                                                                                                                                                      
            .c_import                     => try sema.zirCImport(block, inst),                                                                                                                                                        
                                                                ^                                                                                                                                                                     
/Users/kubkon/dev/zig/src/Sema.zig:620:45: 0x10153d1ab in analyzeBodyBreak (zig)                                                                                                                                                      
    const break_inst = sema.analyzeBodyInner(block, body) catch |err| switch (err) {                                                                                                                                                  
                                            ^                                                                                                                                                                                         
/Users/kubkon/dev/zig/src/Module.zig:4500:50: 0x10153a8bb in semaDecl (zig)                                                                                                                                                           
    const result_ref = (try sema.analyzeBodyBreak(&block_scope, body)).?.operand;                                                                                                                                                     
                                                 ^                                                                                                                                                                                    
/Users/kubkon/dev/zig/src/Module.zig:4141:38: 0x1013c01ab in ensureDeclAnalyzed (zig)                                                                                                                                                 
    const type_changed = mod.semaDecl(decl_index) catch |err| switch (err) {                                                                                                                                                          
                                     ^                                                                                                                                                                                                
/Users/kubkon/dev/zig/src/Sema.zig:25231:32: 0x1019e3a47 in ensureDeclAnalyzed (zig)                                                                                                                                                  
    sema.mod.ensureDeclAnalyzed(decl_index) catch |err| {                                                                                                                                                                             
                               ^                                                                                                                                                                                                      
/Users/kubkon/dev/zig/src/Sema.zig:25273:32: 0x101846e07 in analyzeDeclRef (zig)                                                                                                                                                      
    try sema.ensureDeclAnalyzed(decl_index);                                                                                                                                                                                          
                               ^                                                                                                                                                                                                      
/Users/kubkon/dev/zig/src/Sema.zig:5326:31: 0x1017d19af in zirDeclRef (zig)                                                                                                                                                           
    return sema.analyzeDeclRef(decl_index) catch |err| switch (err) {                                                                                                                                                                 
                              ^                                                                                                                                                                                                       
/Users/kubkon/dev/zig/src/Sema.zig:727:65: 0x10166ff7f in analyzeBodyInner (zig)                                                                                                                                                      
            .decl_ref                     => try sema.zirDeclRef(block, inst),                                                                                                                                                        
                                                                ^                                                                                                                                                                     
/Users/kubkon/dev/zig/src/Sema.zig:603:30: 0x10166e66f in analyzeBody (zig)                                                                                                                                                           
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {                                                                                                                                                                 
                             ^                                                                                                                                                                                                        
/Users/kubkon/dev/zig/src/Module.zig:5517:21: 0x10152fc4f in analyzeFnBody (zig)                                                                                                                                                      
    sema.analyzeBody(&inner_block, fn_info.body) catch |err| switch (err) {                                                                                                                                                           
                    ^                                                                                                                                                                                                                 
/Users/kubkon/dev/zig/src/Module.zig:4227:40: 0x1013bf53f in ensureFuncBodyAnalyzed (zig)                                                                                                                                             
            var air = mod.analyzeFnBody(func, sema_arena) catch |err| switch (err) {                                                                                                                                                  
                                       ^                                                                                                                                                                                              
/Users/kubkon/dev/zig/src/Compilation.zig:2941:42: 0x1013bdf93 in processOneJob (zig)                                                                                                                                                 
            module.ensureFuncBodyAnalyzed(func) catch |err| switch (err) {              

/Users/kubkon/dev/zig/src/Compilation.zig:2879:30: 0x1012f8867 in performAllTheWork (zig)                                                                                                                                             
            try processOneJob(comp, work_item);
                             ^
/Users/kubkon/dev/zig/src/Compilation.zig:2220:31: 0x1012f5f43 in update (zig)
    try comp.performAllTheWork(main_progress_node);
                              ^
/Users/kubkon/dev/zig/src/main.zig:3327:20: 0x101317d67 in updateModule (zig)
    try comp.update();
                   ^
/Users/kubkon/dev/zig/src/main.zig:3016:17: 0x1011456ab in buildOutputType (zig)
    updateModule(gpa, comp, hook) catch |err| switch (err) {
                ^
/Users/kubkon/dev/zig/src/main.zig:236:31: 0x1010e519b in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .zig_test);
                              ^
/Users/kubkon/dev/zig/src/stage1.zig:48:24: 0x1010e49ef in main (zig)
        stage2.mainArgs(gpa, arena, args) catch unreachable;
                       ^
???:?:?: 0x10d8f108b in ??? (???)
???:?:?: 0xaf58ffffffffffff in ??? (???)
error: test...
error: The following command terminated unexpectedly:
/Users/kubkon/dev/zig/build/stage3/bin/zig test /Users/kubkon/dev/zig/test/link/interdependent_static_c_libs/main.zig /Users/kubkon/dev/zig/test/link/interdependent_static_c_libs/zig-cache/o/3dca64fe37149040acf5e5f1f76b3493/liba.a
 /Users/kubkon/dev/zig/test/link/interdependent_static_c_libs/zig-cache/o/42a1147a229d50846f350c2c0f4d2eb4/libb.a --cache-dir /Users/kubkon/dev/zig/test/link/interdependent_static_c_libs/zig-cache --global-cache-dir /Users/kubkon/
.cache/zig --name test -I /Users/kubkon/dev/zig/test/link/interdependent_static_c_libs --enable-cache 
error: the following build command failed with exit code 6:
/Users/kubkon/dev/zig/test/link/interdependent_static_c_libs/zig-cache/o/1d2b0f7660520185ebb1ada8ad4c2034/build /Users/kubkon/dev/zig/build/stage3/bin/zig /Users/kubkon/dev/zig/test/link/interdependent_static_c_libs /Users/kubkon/
dev/zig/test/link/interdependent_static_c_libs/zig-cache /Users/kubkon/.cache/zig test
```

**Comment by Jarred-Sumner** [comment]
Instead of breaking existing projects with the upgrade, could sema detect usage of async (or other unsupported feature) and automatically switch to stage1?

**Comment by andrewrk** [comment]
> Instead of breaking existing projects with the upgrade, could sema detect usage of async (or other unsupported feature) and automatically switch to stage1?

I thought about this. I think that the convenience it brings is outweighed by the confusion it might cause, of people not knowing which compiler implementation they are using. I think it should be an intentional choice, and the first question I'm going to ask someone when they report a bug is, "what CLI invocation are you using?" which will tell me which compiler they are using. If it depended on the code, bugs would be harder to diagnose.

**Comment by andrewrk** [comment]
The aarch64-linux CI failure is #12360

**Comment by kamidev** [comment]
> I did hit this when running a couple of test suites on arm64 macOS:
> 
> ```
> zig/build on  stage3-default [$!?] via C v13.1.6-clang via △ v3.22.3 via ↯ v0.10.0-dev.3433+cbac7a019                                                                                                                                
> ```

I fail at the same test 
```
➜  build git:(master) ✗ sw_vers;clang --version; zig version
ProductName:	macOS
ProductVersion:	12.5
BuildVersion:	21G72
Homebrew clang version 14.0.6
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /opt/homebrew/opt/llvm/bin
0.10.0-dev.3498+d769fd010
```

```
➜  build git:(master) ✗ ./stage3/bin/zig build test-link -Denable-macos-sdk
info: PASS build test/link/bss/build.zig (Debug)
All 2 tests passed.
info: PASS build test/link/common_symbols/build.zig (Debug)
All 2 tests passed.
info: PASS build test/link/common_symbols/build.zig (ReleaseSafe)
All 2 tests passed.
info: PASS build test/link/common_symbols/build.zig (ReleaseFast)
All 2 tests passed.
info: PASS build test/link/common_symbols/build.zig (ReleaseSmall)
All 1 tests passed.
info: PASS build test/link/common_symbols_alignment/build.zig (Debug)
All 1 tests passed.
info: PASS build test/link/common_symbols_alignment/build.zig (ReleaseSafe)
All 1 tests passed.
info: PASS build test/link/common_symbols_alignment/build.zig (ReleaseFast)
All 1 tests passed.
info: PASS build test/link/common_symbols_alignment/build.zig (ReleaseSmall)
thread 2794218 panic: Segmentation fault at address 0x70
Analyzing /Users/jonas/src/zig/zig/test/link/interdependent_static_c_libs/main.zig: main.zig:c
    > %10 = c_import({
        %11 = str("b.h")
        %12 = as_node(@Zir.Inst.Ref.const_slice_u8_type, %11)
        %13 = extended(c_include(%12))
        %14 = ensure_result_used(@Zir.Inst.Ref.void_value)
        %15 = break_inline(%10, @Zir.Inst.Ref.void_value)
      })
      %16 = break_inline(%9, %10)
    For full context, use the command
      zig ast-check -t /Users/jonas/src/zig/zig/test/link/interdependent_static_c_libs/main.zig

  in /Users/jonas/src/zig/zig/test/link/interdependent_static_c_libs/main.zig: main.zig:test.import C sub
    > %21 = decl_ref("c")

???:?:?: 0x106b2cbc8 in __ZN4llvm16cast_convert_valIN5clang16EnumConstantDeclEPNS1_4DeclES4_E4doitERKS4_ (???)
???:?:?: 0x1063caa1f in _ZigClangPreprocessingRecord_iterator_deref (???)
/Users/jonas/src/zig/zig/src/translate_c.zig:452:32: 0x102415aff in prepopulateGlobalNameTable (zig)
        const entity = it.deref();
                               ^
/Users/jonas/src/zig/zig/src/translate_c.zig:423:35: 0x1024231e3 in translate (zig)
    try prepopulateGlobalNameTable(ast_unit, &context);
                                  ^
/Users/jonas/src/zig/zig/src/Compilation.zig:3482:41: 0x102a75173 in cImport (zig)
        var tree = translate_c.translate(
                                        ^
/Users/jonas/src/zig/zig/src/Sema.zig:4741:42: 0x102895657 in zirCImport (zig)
    const c_import_res = mod.comp.cImport(c_import_buf.items) catch |err|
                                         ^
/Users/jonas/src/zig/zig/src/Sema.zig:717:65: 0x102740cd3 in analyzeBodyInner (zig)
            .c_import                     => try sema.zirCImport(block, inst),
                                                                ^
/Users/jonas/src/zig/zig/src/Sema.zig:620:45: 0x1025ffbf3 in analyzeBodyBreak (zig)
    const break_inst = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                                            ^
/Users/jonas/src/zig/zig/src/Module.zig:4500:50: 0x1025fd303 in semaDecl (zig)
    const result_ref = (try sema.analyzeBodyBreak(&block_scope, body)).?.operand;
                                                 ^
/Users/jonas/src/zig/zig/src/Module.zig:4141:38: 0x102468777 in ensureDeclAnalyzed (zig)
    const type_changed = mod.semaDecl(decl_index) catch |err| switch (err) {
                                     ^
/Users/jonas/src/zig/zig/src/Sema.zig:25233:32: 0x102a9fa2f in ensureDeclAnalyzed (zig)
    sema.mod.ensureDeclAnalyzed(decl_index) catch |err| {
                               ^
/Users/jonas/src/zig/zig/src/Sema.zig:25275:32: 0x10290ddf7 in analyzeDeclRef (zig)
    try sema.ensureDeclAnalyzed(decl_index);
                               ^
/Users/jonas/src/zig/zig/src/Sema.zig:5326:31: 0x102898997 in zirDeclRef (zig)
    return sema.analyzeDeclRef(decl_index) catch |err| switch (err) {
                              ^
/Users/jonas/src/zig/zig/src/Sema.zig:727:65: 0x1027413a3 in analyzeBodyInner (zig)
            .decl_ref                     => try sema.zirDeclRef(block, inst),
                                                                ^
/Users/jonas/src/zig/zig/src/Sema.zig:603:30: 0x10273fa8b in analyzeBody (zig)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                             ^
/Users/jonas/src/zig/zig/src/Module.zig:5517:21: 0x1025f2697 in analyzeFnBody (zig)
    sema.analyzeBody(&inner_block, fn_info.body) catch |err| switch (err) {
                    ^
/Users/jonas/src/zig/zig/src/Module.zig:4227:40: 0x102467b0b in ensureFuncBodyAnalyzed (zig)
            var air = mod.analyzeFnBody(func, sema_arena) catch |err| switch (err) {
                                       ^
/Users/jonas/src/zig/zig/src/Compilation.zig:2962:42: 0x10246655f in processOneJob (zig)
            module.ensureFuncBodyAnalyzed(func) catch |err| switch (err) {
                                         ^
/Users/jonas/src/zig/zig/src/Compilation.zig:2894:30: 0x10239643f in performAllTheWork (zig)
            try processOneJob(comp, work_item);
                             ^
/Users/jonas/src/zig/zig/src/Compilation.zig:2234:31: 0x102393a3b in update (zig)
    try comp.performAllTheWork(main_progress_node);
                              ^
/Users/jonas/src/zig/zig/src/main.zig:3327:20: 0x1023b593f in updateModule (zig)
    try comp.update();
                   ^
/Users/jonas/src/zig/zig/src/main.zig:3016:17: 0x1021e5297 in buildOutputType (zig)
    updateModule(gpa, comp, hook) catch |err| switch (err) {
                ^
/Users/jonas/src/zig/zig/src/main.zig:236:31: 0x1021c2c1f in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .zig_test);
                              ^
/Users/jonas/src/zig/zig/src/main.zig:174:20: 0x1021c24f7 in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/Users/jonas/src/zig/zig/build/stage2/lib/zig/std/start.zig:576:37: 0x1021c39c7 in main (zig)
            const result = root.main() catch |err| {
                                    ^
???:?:?: 0x10e9cd08b in ??? (???)
???:?:?: 0xbf037fffffffffff in ??? (???)
error: test...
error: The following command terminated unexpectedly:
/Users/jonas/src/zig/zig/build/stage3/bin/zig test /Users/jonas/src/zig/zig/test/link/interdependent_static_c_libs/main.zig /Users/jonas/src/zig/zig/test/link/interdependent_static_c_libs/zig-cache/o/53b36e50ce70877cd479c2434a2457f3/liba.a /Users/jonas/src/zig/zig/test/link/interdependent_static_c_libs/zig-cache/o/8bad882ec5f57577e522c8c74924c9ee/libb.a --cache-dir /Users/jonas/src/zig/zig/test/link/interdependent_static_c_libs/zig-cache --global-cache-dir /Users/jonas/.cache/zig --name test -I /Users/jonas/src/zig/zig/test/link/interdependent_static_c_libs --enable-cache
error: the following build command failed with exit code 6:
/Users/jonas/src/zig/zig/test/link/interdependent_static_c_libs/zig-cache/o/88be37ed130f9e8fabcccd4a0685ea45/build /Users/jonas/src/zig/zig/build/stage3/bin/zig /Users/jonas/src/zig/zig/test/link/interdependent_static_c_libs /Users/jonas/src/zig/zig/test/link/interdependent_static_c_libs/zig-cache /Users/jonas/.cache/zig test
The following command exited with error code 1 (expected 0):
cd /Users/jonas/src/zig/zig && build/stage3/bin/zig build --build-file /Users/jonas/src/zig/zig/test/link/interdependent_static_c_libs/build.zig test
error: UnexpectedExitCode
```

**Comment by itsmontoya** [comment]
Congratulations @andrewrk ! This is huge!

**Comment by linux-admin0001** [comment]
@andrewrk https://github.com/ziglang/zig/issues/1481

**Pull request merged**
