### PR TITLE
std.fs: tests for makePath and symlinks

### LINKED ISSUE #17330: Dir.makePath infinite loops when a path component is a symlink
### Zig Version

0.12.0-dev.163+6780a6bbf

### Steps to Reproduce and Observed Behavior

1. Paste into `repro.zig`
```zig
const std = @import("std");
test {
    try std.fs.cwd().symLink("../../boop", "folder", .{});
    try std.fs.cwd().makePath("folder/infinite-loop");
}
```
2. zig test repro.zig
3. Infinite loop

### Expected Behavior

It shouldn't infinite loop

It is a valid question whether it should follow the symlink and "continue" creating the directory through the symlink, joining the path. There is an argument for either case. 

But it shouldn't infinite loop

### PR DESCRIPTION
**Pull request by rootbeer**
Refactor tests around makePath and symlinks.

### CODE REVIEW

**Comment by squeek502** [comment]
This is a duplicate of https://github.com/ziglang/zig/pull/16878. I like its implementation better but these added tests look good.

Both are somewhat blocked by https://github.com/ziglang/zig/issues/17034

**Comment by rootbeer** [comment]
Thanks for the links, I'm happy to put my test cases into #16878 if you'd rather see that fix.  I find the flow control with the inline named block harder to reason about ... and its not clear to me that #16878 handles the case where statFile() returns FileNotFound (which I believe is the error returned from statFile() when a dangling symlink is found).  I guess this would be made clear one way or another by the test cases. :)

After fixing some embarassing fmt and wasi platform errors, I'm still seeing an odd (but consistent) failure on aarch64-windows.  I'll look into those.  I guess I need to figure out how to run tests locally.

I'll try digging into the fstatat bug a bit too.  Mostly a good exercise for me to learn about the syscall wrapping works in Zig (vs. actually being finding the root cause), but I'll update the PR with anything I learn.

**Comment by squeek502** [comment]
> the case where statFile() returns FileNotFound

I don't think we can say for certain that `FileNotFound` from `statFile` is a dangling symlink issue, as it's possible that e.g. a totally normal directory existed during the `makeDir` call but was deleted before the `statFile` call.

**Comment by rootbeer** [comment]
> I don't think we can say for certain that `FileNotFound` from `statFile` is a dangling symlink, as it's possible that e.g. a totally normal directory existed during the `makeDir` call but was deleted before the `statFile` call.

Ah, yeah, it could be a race with a parallel delete.  Is that sort of race condition something makePath() should worry about though? I'm not sure that the behavior of this change (failing the makePath() operation) is unacceptable.  Wouldn't that happen anyway in many cases?  E.g., if I makePath("a/b/c"), and something else deletes "b" at just the wrong time, the makePath() attempt to create "c" would fail obtusely?

**Comment by squeek502** [comment]
I'm just saying converting `FileNotFound` to `NotDir` is not always the correct thing to do, returning the error as `FileNotFound` seems like the better option (which is how it's handled in https://github.com/ziglang/zig/pull/16878)

**Comment by squeek502** [comment]
I've cherry-picked most of the tests from this PR into #18453. https://github.com/ziglang/zig/pull/17702 being merged means that both this and https://github.com/ziglang/zig/pull/16878 no longer need to skip when targeting GNU libc (excellent work on that, btw, it'll be a huge relief to not have to worry about `stat` calls breaking things).

Note that neither this nor https://github.com/ziglang/zig/pull/16878 is currently sufficient to resolve https://github.com/ziglang/zig/issues/17330, since resolving it on Windows is going to take a bit of effort (see https://github.com/ziglang/zig/issues/17330#issuecomment-1878111220).

My current thoughts are:
- https://github.com/ziglang/zig/pull/16878 can be merged as-is, since it fixes one bug (the `makepath existing file (fails)` test case in this PR), but not https://github.com/ziglang/zig/issues/17330
- This PR can drop the tests that were included in #18453 and the `makepath existing file (fails)` test since it overlaps with #16878
- This PR can then be made to focus specifically on the dangling symlink test and get the test to pass on all platforms, or a new PR can be opened for that purpose

Let me know if that sounds okay to you.

**Comment by rootbeer** [comment]
Sounds like a good plan.  Once the dust settles a bit, I'll trim this down to the test dangling symlink test.  Thanks for getting the other tests merged and isolating the Windows problems!

**Comment by rootbeer** [comment]
@squeek502 Can you give this a quick look over?  All that really remained from this CL after separating out the makepath fix and the already-present tests was a bunch of misc cleanup.  Add to that some cleanup I inserted when trying to get these tests to pass on Wine (that's not happening).  Not sure if I should resurrect this on this PR, or close this PR and start a new one.  Thanks!

**Comment by squeek502** [comment]
Test changes look good to me. We can tackle fixing https://github.com/ziglang/zig/issues/17330 in a separate PR.

**Pull request merged**
