### PR TITLE
introduce the `zig fetch` subcommand and symlink support in zig packages

### LINKED ISSUE #16678: std.tar: handle tar files with symbolic links
### Zig Version

0.11.0-dev.4404+4f6013bf5

### Steps to Reproduce and Observed Behavior

Use any `data.tar.gz` below that contains a symbolic link.

You'll get a `TarUnsupportedFileType` which is explicitly returned from `std.tar` if it seems a symlink.

```zig
const std = @import("std");

/// USE BAD TAR.GZ HERE
const data = @embedFile("data.tar.gz");

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const alloc = gpa.allocator();

    var out_dir = try std.fs.cwd().openDir("test-out", .{});

    var stream = std.io.fixedBufferStream(data);
    var decompress = try std.compress.gzip.decompress(alloc, stream.reader());
    defer decompress.deinit();

    try std.tar.pipeToFileSystem(out_dir, decompress.reader(), .{
        .strip_components = 1,
        .mode_mode = .ignore,
    });
}
```

### Expected Behavior

This should work. A lot of source archives for the Zig package manager contain symbolic links. Major source archives that I use that have symbolic links:

  - libxml2
  - harfbuzz

This will also impair #16643 (not block) because downloading source archives for me will be a big use case.

### LINKED ISSUE #16972: build.zig.zon improve workflow to update dependency hash
Here's my typical process for synchronizing the hash field for a dependency in `build.zig.zon`:

1. Set the hash field to a bogus value
2. Run `zig build`
3. Update `build.zig.zon` with the actual hash displayed in the error message
4. Run `zig build` again to verify it worked

My initial proposal is to introduce a special value `"?"` that tells Zig to update `build.zig.zon` for us.  The new flow becomes.

1. Set the hash field to `"?"`
2. Run `zig build` to update the hash/verify it works

There have since been other good suggestions:

from @zenMaya: add a command for zig to download and report the hash of a URL (i.e. `zig download URL`).  This might be a good command to make available regardless of whether we need it for this specific use case?

from @mpfaff: put hashes into a separate "lock file" meant to be managed more "automatically" instead of manually.  This isn't a full solution but could make other ideas easier.

from @Pyrolistical: add a flag (or maybe a separate command?) that tells zig to update hashes (instead of using a special hash value).  I believe this would require zig to assume that all hashes could be invalid meaning it would need to download/recalculate all dependency hashes and update them accordingly, or, zig could maintain a known URL to HASH mapping and only update hashes where this mapping has not been calculated yet.  In other words, if the user modifies a URL, zig will see that it hasn't calculated a hash for it yet.

### PR DESCRIPTION
**Pull request by andrewrk**
```
zig fetch [options] <url>
zig fetch [options] <path>
```

Fetches a package which is found at `<url>` or `<path>` into the global cache directory, printing the package hash to stdout.

Closes #16972
Related to #14280

Additionally, this branch:

* Adds uncompressed .tar support to package fetching
* Introduces symlink support to package fetching (closes #16678)

### Merge Checklist

* [x] support symlinks in Package/git.zig
* [ ] ~more kinds of symlink metadata in std.tar~ eagerly awaiting @vesim987's upcoming PR for this
* [x] handle Diagnostics from std.tar

### CODE REVIEW

**Comment by andrewrk** [comment]
cc @ianprime0509 - would you be willing to add the git.zig logic to add symlink support here?

**Comment by ianprime0509** [comment]
Awesome! Sure, I'll take a closer look at this after work and send a patch to add support for this in Git.

**Comment by andrewrk** [comment]
> more kinds of symlink metadata in std.tar

eagerly awaiting @vesim987's upcoming PR for this

**Comment by andrewrk** [comment]
Note that `zig fetch` on a directory will be a bit useless until #14311 is resolved, because the package will potentially include files from version control which would not make it into a tarball.

**Comment by ianprime0509** [comment]
@andrewrk not sure what would be most convenient for you (maybe I should just send a follow-up PR once this is merged), but here's a patch to integrate this with `git.zig` as well: https://gist.github.com/ianprime0509/f097b73a77e0c9412fe4a11824bd169d

This is able to fetch the dependency in this PR: https://github.com/kristoff-it/orca-ui-hello-zig/pull/1

```
⬢[ian@toolbox orca-ui-hello-zig]$ ~/src/zig/build/stage4/bin/zig build
Fetch Packages... orca [9MiB] /var/home/ian/src/tmp/orca-ui-hello-zig/build.zig.zon:8:20: error: dependency is missing hash field
            .url = "git+https://git.handmade.network/hmn/orca.git#c4a1ad52a07bae2e6710c38f41a3c64ed8f93136",
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: expected .hash = "1220a913fdaac3962e4331bd71d729b70da9ecfa2a959d62d6c491f18b4619cdca61",
```

Sample when the underlying filesystem doesn't support symlinks:

```
⬢[ian@toolbox orca-ui-hello-zig]$ ZIG_GLOBAL_CACHE_DIR=$HOME/src/tmp/fat.mnt ~/src/zig/build/stage4/bin/zig build
Fetch Packages... orca [8MiB] Checkout... /var/home/ian/src/tmp/orca-ui-hello-zig/build.zig.zon:8:20: error: unable to unpack packfile
            .url = "git+https://git.handmade.network/hmn/orca.git#c4a1ad52a07bae2e6710c38f41a3c64ed8f93136",
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: unable to create symlink from 'src/ext/wasm3/platforms/android/app/src/main/cpp/m3' to '../../../../../../source': AccessDenied
note: unable to create symlink from 'src/ext/wasm3/platforms/embedded/arduino/lib/wasm3' to '../../../../source': AccessDenied
note: unable to create symlink from 'src/ext/wasm3/platforms/embedded/bluepill/lib/wasm3/src' to '../../../../../source': AccessDenied
note: unable to create symlink from 'src/ext/wasm3/platforms/embedded/esp32-idf-wasi/main/wasm3' to '../../../../source': AccessDenied
note: unable to create symlink from 'src/ext/wasm3/platforms/embedded/esp32-pio/lib/wasm3/src' to '../../../../../source': AccessDenied
note: unable to create symlink from 'src/ext/wasm3/platforms/embedded/esp8266/lib/wasm3' to '../../../../source': AccessDenied
note: unable to create symlink from 'src/ext/wasm3/platforms/embedded/fomu/src/wasm3' to '../../../../source': AccessDenied
note: unable to create symlink from 'src/ext/wasm3/platforms/embedded/hifive1/lib/wasm3' to '../../../../source': AccessDenied
note: unable to create symlink from 'src/ext/wasm3/platforms/embedded/particle/lib/wasm3/src' to '../../../../../source': AccessDenied
note: unable to create symlink from 'src/ext/wasm3/platforms/embedded/wm_w600/wasm3' to '../../../source': AccessDenied
note: unable to create symlink from 'tests/files/data/jail/dir_escape' to '..': AccessDenied
note: unable to create symlink from 'tests/files/data/jail/file_escape' to '../regular.txt': AccessDenied
note: unable to create symlink from 'tests/files/data/symlink' to 'regular.txt': AccessDenied
```

**Comment by andrewrk** [comment]
If you're fine with it, I can cherry-pick from your zig fork into this branch

**Comment by ianprime0509** [comment]
That sounds like an easier idea, I just pushed it up here: https://github.com/ianprime0509/zig/tree/tar-symlinks

**Comment by andrewrk** [comment]
Commit looks great :+1:

**Pull request merged**
