### PR TITLE
Update the thread sanitizer from llvm 17.0.3

### LINKED ISSUE #15241: Thread sanitizer - missing references to internal functions
### Zig Version

0.11.0-dev.2477+2ee328995

### Steps to Reproduce and Observed Behavior

1. Create a zig program, can be just an empty main function
```zig
pub fn main() void {}
```
2. Attempt to compile with enabled thread sanitizer:
zig build-exe -fsanitize-thread main.zig

Error for me:
error: ld.lld: undefined symbol: __tsan_memcpy
    note: referenced by target.zig:779 (/usr/lib/zig/lib/std/target.zig:779)
    note:               main.o:(target.Target.Cpu.Feature.feature_set_fns(target.x86.Feature).featureSet)
    note: referenced by target.zig:783 (/usr/lib/zig/lib/std/target.zig:783)
    note:               main.o:(target.Target.Cpu.Feature.feature_set_fns(target.x86.Feature).featureSet)
    note: referenced by debug.zig:348 (/usr/lib/zig/lib/std/debug.zig:348)
    note:               main.o:(debug.panicImpl)
    note: referenced 1423 more times
error: ld.lld: undefined symbol: __tsan_memset
    note: referenced by debug.zig:302 (/usr/lib/zig/lib/std/debug.zig:302)
    note:               main.o:(debug.panicExtra__anon_2549)
    note: referenced by debug.zig:302 (/usr/lib/zig/lib/std/debug.zig:302)
    note:               main.o:(debug.panicExtra__anon_2551)
    note: referenced by debug.zig:302 (/usr/lib/zig/lib/std/debug.zig:302)
    note:               main.o:(debug.panicExtra__anon_4333)
    note: referenced 103 more times
error: ld.lld: undefined symbol: __tsan_memmove
    note: referenced by cxa_demangle.cpp
    note:               /home/potato/.cache/zig/o/073ee8acaad27d019ff4131bc8f7d10c/cxa_demangle.o:((anonymous namespace)::itanium_demangle::AbstractManglingParser<(anonymous namespace)::itanium_demangle::ManglingParser<(anonymous namespace)::DefaultAllocator>, (anonymous namespace)::DefaultAllocator>::parseEncoding()) in archive /home/potato/.cache/zig/o/fd65b4244a3737173c8f0c43adda5b36/libc++abi.a
    note: referenced by cxa_demangle.cpp
    note:               /home/potato/.cache/zig/o/073ee8acaad27d019ff4131bc8f7d10c/cxa_demangle.o:((anonymous namespace)::itanium_demangle::AbstractManglingParser<(anonymous namespace)::itanium_demangle::ManglingParser<(anonymous namespace)::DefaultAllocator>, (anonymous namespace)::DefaultAllocator>::parseEncoding()) in archive /home/potato/.cache/zig/o/fd65b4244a3737173c8f0c43adda5b36/libc++abi.a
    note: referenced by cxa_demangle.cpp
    note:               /home/potato/.cache/zig/o/073ee8acaad27d019ff4131bc8f7d10c/cxa_demangle.o:((anonymous namespace)::itanium_demangle::AbstractManglingParser<(anonymous namespace)::itanium_demangle::ManglingParser<(anonymous namespace)::DefaultAllocator>, (anonymous namespace)::DefaultAllocator>::parseType()) in archive /home/potato/.cache/zig/o/fd65b4244a3737173c8f0c43adda5b36/libc++abi.a
    note: referenced 12 more times

### Expected Behavior

Successful compilation with thread sanitization

### PR DESCRIPTION
**Pull request by IntegratedQuantum**
Fixes #15241

Now, since you shouldn't trust me, someone from the team should probably redo the steps I took:
1. I removed all the source files from `lib/tsan` `lib/tsan/interception` `lib/tsan/sanitizer_common` `lib/tsan/ubsan`
2. I downloaded the source code of the llvm 17.0.3 release from their github page.
3. I copied all source files from `llvm-project/compiler-rt/lib/tsan/rtl` to `lib/tsan`
4. I copied the files `ubsan_flags.h`, `ubsan_flags.inc`, `ubsan_init.h` and `ubsan_platform.h` from `llvm-project/compiler-rt/lib/ubsan` to `lib/tsan/ubsan`
5. I copied all source files from `llvm-project/compiler-rt/lib/sanitizer_common` to `lib/tsan/sanitizer_common`
6. I copied all source files from `llvm-project/compiler-rt/lib/interception` to `lib/tsan/interception`
7. I modified `src/libtsan.zig` to accomodate for all the file changes.

I tested it on a project of mine, were it runs fine and it even pointed out a bunch of data races.

### CODE REVIEW

**Comment by andrewrk** [comment]
Nice work, thank you!

**Comment by adrian4096** [comment]
Any status update with this?

**Comment by IntegratedQuantum** [comment]
> Any status update with this?

At least from my side it's all done and it appears to be all working. I'm also just waiting.

**Review by nullptrdevs — COMMENTED** [review]
Thank you for doing the work, @IntegratedQuantum .

Rebased onto master zig builds fine, but when trying to build my app I get FileNotFound errors.
Had to remove them from `sanitizer_common_sources`

```diff
diff --git a/src/libtsan.zig b/src/libtsan.zig
index 1ef1fd4b8..9b5fcf4b6 100644
--- a/src/libtsan.zig
+++ b/src/libtsan.zig
@@ -317,8 +317,8 @@ const sanitizer_common_sources = [_][]const u8{
     "sanitizer_mac.cpp",
     "sanitizer_mutex.cpp",
     "sanitizer_netbsd.cpp",
-    "sanitizer_openbsd.cpp",
-    "sanitizer_persistent_allocator.cpp",
     "sanitizer_platform_limits_freebsd.cpp",
     "sanitizer_platform_limits_linux.cpp",
     "sanitizer_platform_limits_netbsd.cpp",

```

**Comment by IntegratedQuantum** [comment]
Thanks for pointing out this issue.

**Comment by jordanisaacs** [comment]
Did a compiler bootstrap with llvm with this PR rebased onto master and confirmed it worked. Without this pr couldn't get `-fsanitize-thread` to work as it was erroring on missing `crypt.h`. Is there anything blocking this from being merged?

**Comment by andrewrk** [comment]
Closing in favor of #18505.

Thanks, it was useful to reference your work.

**Pull request closed without merging**
