### PR TITLE
Allocator: `allocBytes` and `reallocBytes`

### LINKED ISSUE #10348: Allocgate missing runtime-known alignment functions
To quote @andrewrk on #10112:

> [...] I agree that this use case will need to continue to be supported - runtime-known alignment.

However, the new allocator interface does not feature any high-level functions to support this. Ideally there would be a `reallocAdvancedWithRetAddrRuntimeAlignment` (though that name is rather unwieldy).

### PR DESCRIPTION
**Pull request by leecannon**
Reimplement `reallocBytes` after regression from #9394/#10112
Also adds an analogous `allocBytes` function.

@silversquirl / @mlugg: do these functions satisfy your requirements?
As the these functions don't return a slice with the alignment as part of the type I choose not to name them something like `reallocAdvancedWithRetAddrRuntimeAlignment` to seperate them from the other `alloc`/`realloc` functions.

closes #10348

### CODE REVIEW

**Comment by mlugg** [comment]
Quickly skimming through, it looks like that should be fine for my use case yeah. Thanks!

**Review by andrewrk — CHANGES_REQUESTED** [review]
Thanks for the patch!

Needs simple test coverage and then it's good to go.

**Comment by leecannon** [comment]
Tests added

**Review by andrewrk — APPROVED** [review]
Thank you :+1:

**Pull request merged**
