### PR TITLE
macos: vendored libc: bump to SDK 15.1

### PR DESCRIPTION
**Pull request by mikdusan**

### CODE REVIEW

**Comment by alexrp** [comment]
We also need the headers added here: https://github.com/ziglang/fetch-them-macos-headers/tree/main/headers

Doing that should close https://github.com/ziglang/fetch-them-macos-headers/issues/31 and https://github.com/ziglang/fetch-them-macos-headers/issues/32.

**Comment by mikdusan** [comment]
I cannot seem to recall the purpose of adding those headers to `fetch-them-macos-headers` repo. Is it perhaps for the deprecated howto?

**Comment by andrewrk** [comment]
Thanks @mikdusan! What process did you follow to make these changes?

**Review by alexrp — APPROVED** [review]

**Comment by alexrp** [comment]
> Thanks @mikdusan! What process did you follow to make these changes?

https://github.com/ziglang/fetch-them-macos-headers/blob/6b7d3a008debdc947102e8885c47935362118b62/README.md

(We discussed this on Zulip, but just posting this here as well.)

**Comment by mikdusan** [comment]
> > Thanks @mikdusan! What process did you follow to make these changes?

- fetch-them-macos-headers readme has been updated
- see https://github.com/ziglang/fetch-them-macos-headers#howto item 5

**Pull request merged**
