### PR TITLE
Fix std.mem.Allocator.resize for non-u8 types

### PR DESCRIPTION
**Pull request by SpexGuy**
Three fixes: a typo, a const problem, and a failure to handle empty types.

### CODE REVIEW

**Comment by daurnimator** [comment]
Related?  #5306

**Comment by andrewrk** [comment]
> Related? #5306

I just tested it - appears to be unrelated.

@SpexGuy mind attaching a test to this PR?

**Comment by daurnimator** [comment]
> I just tested it - appears to be unrelated.

related in that the same
```zig
    if (@sizeOf([*]T) == 0) {
        return @as([*]T, undefined)[0..new_n];
    }
```

should probably be added to `reallocAdvancedWithRetAddr` which I think would fix #5306 ?

**Comment by SpexGuy** [comment]
> mind attaching a test to this PR?

Can do, what file has tests for Allocator?  There aren't any in this file.

**Comment by komuw** [comment]
> > mind attaching a test to this PR?
> 
> Can do, what file has tests for Allocator? There aren't any in this file.

probably https://github.com/ziglang/zig/blob/master/lib/std/mem.zig

**Comment by SpexGuy** [comment]
I added a more thorough test, which exposed a bunch more parts of std.mem.Allocator (and std.fmt) that didn't support zero-sized types.
I attempted to fix them, but I'm now getting an internal compiler error:
```batch
> zig test lib\std\mem.zig --override-lib-dir lib
Semantic Analysis [81/329] Assertion failed at D:\a\1\s\src\stage1\analyze.cpp:5481 in hash_const_val. This is a bug in the Zig compiler.
Unable to dump stack trace: debug info stripped
```
The branch is here if any compiler people want to take a look at it: https://github.com/SpexGuy/zig/tree/broken-allocator

It was a much more invasive change than I expected, because
- attempting to specify alignment for a pointer to zero-sized type is a compile error
- attempting to read the `alignment` field of `TypeInfo.Pointer` is a compile error when the child is a zero-sized type

**Comment by SpexGuy** [comment]
Found a minimal repro: #6942

**Comment by SpexGuy** [comment]
Working around that, I hit #6944.  Working around that also, I now hit a new assert failure.  Working on a repro...

**Comment by SpexGuy** [comment]
Hmm, so I implemented this under the assumption that since `@typeInfo([]void).Pointer.alignment` is a compile error, `[]align(4) void` would also be a compile error.  But apparently it's not?  Also the expression between the parentheses is compiled but not used, and `@alignOf(void)` is only a compile error if it's used.  So all of those weird things cancel out and `[]align(@alignOf(void)) void` technically compiles.  Is this intentional?

**Comment by SpexGuy** [comment]
I think these failures were something else (looks like std.crypto.gimli), so going to close and reopen.

**Comment by SpexGuy** [comment]
A lot of this code is working around zero sized pointers.  Since that's about to change, I'm going to close this PR.

**Pull request closed without merging**
