### PR TITLE
Fix missing newline in render_cmake()

### PR DESCRIPTION
**Pull request by isrvoid**
- remove fragile 'last_line' check: it assumed last line of 'contents' is valid (ends with '\n')
- terminate every line with '\n' (as POSIX defines it)

### CODE REVIEW

**Comment by matu3ba** [comment]
What bug does this fix? There was https://github.com/ziglang/zig/pull/16220 fixing #16203 and this sounds like it reintroduces it, but maybe I am missing something.

**Comment by isrvoid** [comment]
Thanks for the clarification. This change does not reintroduce #16203. I was skimming through latest commits and saw line 306 in #16220. 'last_line' check seemed to have a bug: it's never true, if last line of the input is truncated (no terminating '\n'). I thought it would result in missing '\n' at the end. However, 'last_line' is used in a way that always appends terminating '\n'. At most, my commit simplifies the logic, but the message is definitely wrong: there is no missing newline. I apologize.

**Comment by matu3ba** [comment]
>  At most, my commit simplifies the logic, but the message is definitely wrong: there is no missing newline. I apologize.

No problem and sorry, if I sounded offensive. I could have formulated my reply in a better way. 
To prevent things like this happen, the usual approach is to create an issue explaining the bug/problem/feature before implementing it. Unless, the problem if obvious, but then the PR should explain it.

Minor improvements are of course also accepted, but it was not clear to me how it simplifies/d things.

**Comment by isrvoid** [comment]
No worries, you were not offensive. I should have tested and not just assume, that there might be an issue. Thank you for the advice.

**Pull request closed without merging**
