### PR TITLE
Correctly set uid and gid to void instead of null on wasi

### PR DESCRIPTION
**Pull request by alexnask**

### CODE REVIEW

**Comment by kubkon** [comment]
Interesting. Was this change needed to fix some bug or something? I'm asking since WASI currently doesn't support a concept of a child process (and probably never will as it would affect its strict capability model of security). Oh, and also, there is no concept of process id in WASI.

**Comment by alexnask** [comment]
@kubkon This will probably not be needed by the end of it but I'm trying to get stage2 working on wasi (https://github.com/alexnask/zig-wasi) as an experiment :)

**Comment by kubkon** [comment]
> @kubkon This will probably not be needed by the end of it but I'm trying to get stage2 working on wasi (https://github.com/alexnask/zig-wasi) as an experiment :)

It'd be awesome if you could pull that off! We could then have Zig playground with the code compiled entirely on the client (without the need to send any source files to the server for compilation). Having said that, this might be impossible at this stage due to several things still missing in WASI spec plus Zig spawning child processes which are not supported in WASI. Also, off the top of my head, I think one of the things needed badly is cache_hash.zig in WASI. I started working on that a while back and it's definitely possible, but didn't have time to come at a good API that would satisfy both native platforms as well as WASI. Anyhow, I'll be happy to review your PRs or lend a hand if you need any!

**Comment by alexnask** [comment]
@kubkon Yes, this was my idea as well.  
At the moment I'm just looking to get something very basic to work, like just `zig -> zir`, nothing to do with `zig build`, `zig run`, etc. which need to spawn child processes.  
Thanks for the heads up about cache_hash, I'm not at that stage yet but I'm guessing this is what will be blocking me when I do get there :P

**Review by kubkon — APPROVED** [review]

**Pull request merged**
