### PR TITLE
std.sort: lower/upperBound() and equalRange() use compareFn

### LINKED ISSUE #20110: upperBound and lowerBound has inconsistent callback types
### Zig Version

0.13.0-dev.274+c0da92f71

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");
pub fn main() void {
    const R = struct {
        b: i32,
        
        fn r(b: i32) @This() {
            return @This(){ .b = b };
        }
        
        fn lessThan(context: void, key: i32, mid_item: @This()) bool {
            _ = context;
            
            if (key < mid_item.b) {
                return true;
            }
            
            return false;
        }
    };
    std.debug.print("{} {}\n", .{
        std.sort.upperBound(R, @as(i32, -20), &[_]R{ R.r(-100), R.r(-40), R.r(-10), R.r(30) }, {}, R.lessThan),
        std.sort.lowerBound(R, @as(i32, -20), &[_]R{ R.r(-100), R.r(-40), R.r(-10), R.r(30) }, {}, R.lessThan),
    });
}
```

Produces the following error for the lowerBound call:

```
./zig-linux-x86_64-0.13.0-dev.274+c0da92f71/lib/std/sort.zig:530:36: error: expected type 'i32', found 'main.main.R'
        if (lessThan(context, items[mid], key)) {
                              ~~~~~^~~~~
src/main.zig:3:15: note: struct declared here
    const R = struct {
              ^~~~~~
src/main.zig:10:41: note: parameter type declared here
        fn lessThan(context: void, key: i32, mid_item: @This()) bool {
                                        ^~~
referenced by:
    main: src/main.zig:22:28
    callMain: ./zig-linux-x86_64-0.13.0-dev.274+c0da92f71/lib/std/start.zig:514:17
```

### Expected Behavior

Since upperBound and lowerBound both share the same type signature for the lessThan argument used to compare the key to be searched with the current mid-point item, lowerBound should also accept a lessThan function whose rhs argument has a type different from that of the search key.

The lowerBound function needs to check if the mid-point item is less than the search key, which may be impossible to do with the type signature of the current lessThan function. This could be fixed if either:

1. The lowerBound and upperBound functions have the following signature, which would disallow searching for a key in a slice with different element types:

```zig
pub fn lowerBound(
    comptime T: type,
    key: T,
    items: []const T,
    context: anytype,
    comptime lessThan: fn (context: @TypeOf(context), lhs: T, rhs: T) bool,
) usize {}

pub fn upperBound(
    comptime T: type,
    key: T,
    items: []const T,
    context: anytype,
    comptime lessThan: fn (context: @TypeOf(context), lhs: T, rhs: T) bool,
) usize {}
```

2. or, the two functions could take in a comparator function like in the binarySearch function.

### PR DESCRIPTION
**Pull request by travisstaloch**
closes #20110. addresses issue in #18718.

lowerBound() was added in #18718 with lhs and rhs params reversed.  I believe in this was meant to express !lessThan().  However, this resulted in a subtle bug which wasn't noticed because it wasn't tested, discussion https://github.com/ziglang/zig/pull/18718/files#r1614611124.

Previously all these lessThan callbacks had type
`fn(@TypeOf(context), @TypeOf(key), T) bool`.

This patch changes them to compareFn with type
`fn (@TypeOf(context), @TypeOf(key), T) math.Order`.  This allows searching for a key in a slice with different element types as suggested in #20110.  The new test demonstrates this and prevents the previous 'reversed arguments' bug.

### CODE REVIEW

**Comment by travisstaloch** [comment]
> The lowerBound and upperBound functions have the following signature, which would disallow searching for a key in a slice with different element types:

@g2mt I went with option 2 and used compareFns like sort.binarySearch.  Hope I understood you correctly.  Let me know if you have any suggestions.  

cc @schmee

**Comment by ThreeFx** [comment]
I've run into the same issue and can confirm that this patch successfully fixes it.

**Comment by travisstaloch** [comment]
Reviewer: please consider closing this in favor of #20927 which makes similar changes but seems more complete.  I'll leave this open and allow you to decide.

**Comment by andrewrk** [comment]
Superseded by #20927

**Pull request closed without merging**
