### PR TITLE
stage2: astgen for `try`

### PR DESCRIPTION
**Pull request by g-w1**
I used `orelseCatchExpr` as inspiration for most of the `tryExpr` function. This is my first astgen expr, so please tell me if something is not idomatic.

I also moved the -femit-zir code higher up in the `updateModule` function so that even if sema fails, you still get the ir in $file.zir.

I couldn't find a way to test this.

### CODE REVIEW

**Comment by LemonBoy** [comment]
See #3461 for a stage1 bug related to how `try` is desugared.
See #7541 for another stage1 bug that's related to the very same thing, this time caused by the explosion of `try` in many simple (and unlinked) IR pieces that may get constant-folded separately,

**Comment by g-w1** [comment]
Wow, everything is coming together. I was just thinking about how to implement inferred error sets yesterday. Both of these issues stem from that. The call that checks if the errorset matches the return type is this: https://github.com/ziglang/zig/pull/7606/files#diff-2600885f5a9e88bc263d2b47daab6d1c33418966af8f42b26c188597c108201bR930-R940 I think since I will probably also be implementing inferred error sets soon, I will keep this in the back of my head. If these bugs were to happen, they would not happen in astgen for `try` but in the coercion code and semantic analysis code for inferred/regular error sets.

**Comment by LemonBoy** [comment]
> If these bugs were to happen, they would not happen in astgen for try but in the coercion code and semantic analysis code for inferred/regular error sets.

We'll see.

**Review by andrewrk — CHANGES_REQUESTED** [review]
I'd like to get orelse/catch hooked up all the way through the compiler with test coverage before adding more astgen that uses similar logic, to make sure we are going in the right direction here.

**Comment by g-w1** [comment]
I would too, #7628 will do that, then we can look at this.

**Comment by andrewrk** [comment]
This PR will have to be re-done now that #7847 is landed.

**Pull request closed without merging**
