### PR TITLE
InternPool: introduce TrackedInst to prepare for incremental compilation

### PR DESCRIPTION
**Pull request by mlugg**
See commit messages for details. I will provide performance data points shortly.

### CODE REVIEW

**Comment by mlugg** [comment]
Oh, just to document a change that I snuck into the first commit, our ZIR mapping algorithm is now more effective in that we no longer ignore unnamed decls and tests. These were previously just never mapped, which in practice would have resulted in re-analysis on every update!

**Comment by mlugg** [comment]
## Building behavior tests with x86_64 backend:
```
Benchmark 1 (31 runs): /home/mlugg/zig/master/build/stage3/bin/zig test -I/home/mlugg/zig/master/test /home/mlugg/zig/master/test/behavior.zig -fno-llvm -fno-lld --test-no-exec --cache-dir c1 --global-cache-dir c2
  measurement          mean ± σ            min … max           outliers         delta
  wall_time          1.62s  ±  142ms    1.43s  … 1.87s           0 ( 0%)        0%
  peak_rss            121MB ±  200KB     120MB …  121MB          0 ( 0%)        0%
  cpu_cycles         4.98G  ± 4.06M     4.98G  … 4.99G           0 ( 0%)        0%
  instructions       6.51G  ± 25.3K     6.51G  … 6.51G           2 ( 6%)        0%
  cache_references    398M  ± 1.66M      395M  …  404M           1 ( 3%)        0%
  cache_misses       91.9M  ±  358K     91.2M  … 92.7M           3 (10%)        0%
  branch_misses      41.9M  ± 24.6K     41.8M  … 41.9M           0 ( 0%)        0%
Benchmark 2 (31 runs): /home/mlugg/zig/incremental-the-second/stage4-release/bin/zig test -I/home/mlugg/zig/master/test /home/mlugg/zig/master/test/behavior.zig -fno-llvm -fno-lld --test-no-exec --cache-dir c3 --global-cache-dir c4
  measurement          mean ± σ            min … max           outliers         delta
  wall_time          1.63s  ±  160ms    1.45s  … 1.99s           0 ( 0%)          +  0.6% ±  4.8%
  peak_rss            123MB ±  168KB     123MB …  123MB          0 ( 0%)        💩+  2.1% ±  0.1%
  cpu_cycles         5.02G  ± 3.02M     5.01G  … 5.02G           1 ( 3%)          +  0.7% ±  0.0%
  instructions       6.51G  ± 24.7K     6.51G  … 6.51G           0 ( 0%)          -  0.1% ±  0.0%
  cache_references    406M  ± 1.52M      403M  …  411M           1 ( 3%)        💩+  2.0% ±  0.2%
  cache_misses       93.9M  ±  473K     92.8M  … 95.1M           2 ( 6%)        💩+  2.2% ±  0.2%
  branch_misses      42.6M  ± 19.5K     42.6M  … 42.7M           2 ( 6%)        💩+  1.8% ±  0.0%
```
Peak RSS increased slightly, which is to be expected, and led to a few more cache references, but the resulting performance delta is insignificant.

---
## `AstGen` on `Sema.zig`:
```
Benchmark 1 (461 runs): /home/mlugg/zig/master/build/stage3/bin/zig ast-check /home/mlugg/zig/master/src/Sema.zig
  measurement          mean ± σ            min … max           outliers         delta
  wall_time           108ms ± 6.28ms     104ms …  130ms         48 (10%)        0%
  peak_rss           64.8MB ± 28.5KB    64.7MB … 64.8MB         45 (10%)        0%
  cpu_cycles          342M  ± 3.34M      336M  …  357M           8 ( 2%)        0%
  instructions        550M  ± 77.7       550M  …  550M         107 (23%)        0%
  cache_references   8.51M  ±  152K     8.13M  … 9.42M          12 ( 3%)        0%
  cache_misses        514K  ± 19.8K      476K  …  619K          15 ( 3%)        0%
  branch_misses      4.01M  ± 3.29K     4.00M  … 4.02M           2 ( 0%)        0%
Benchmark 2 (472 runs): /home/mlugg/zig/incremental-the-second/stage4-release/bin/zig ast-check /home/mlugg/zig/master/src/Sema.zig
  measurement          mean ± σ            min … max           outliers         delta
  wall_time           106ms ± 4.98ms     103ms …  128ms         36 ( 8%)        ⚡-  2.3% ±  0.7%
  peak_rss           64.7MB ± 14.7KB    64.4MB … 64.7MB          5 ( 1%)          -  0.2% ±  0.0%
  cpu_cycles          335M  ± 1.53M      333M  …  341M           8 ( 2%)        ⚡-  2.1% ±  0.1%
  instructions        550M  ± 78.1       550M  …  550M         112 (24%)          -  0.0% ±  0.0%
  cache_references   8.98M  ±  144K     8.63M  … 9.71M          10 ( 2%)        💩+  5.6% ±  0.2%
  cache_misses        588K  ± 28.7K      523K  …  722K           7 ( 1%)        💩+ 14.3% ±  0.6%
  branch_misses      3.95M  ± 7.70K     3.93M  … 3.97M           0 ( 0%)        ⚡-  1.5% ±  0.0%
```
Interestingly, there's a big jump in cache misses, but an overall performance improvement! This probably comes from the fact that we're not doing as much bit fiddling when constructing declarations anymore.

---
## ZIR size of `Sema.zig`
| Branch | Total ZIR bytes |
|------------|-----------------------|
| `master` | `4.851020812988281MiB` |
| PR | `4.848020553588867MiB` |

That's an insignificant change in ZIR bytes; a reduction of less than 0.1%.

**Comment by mlugg** [comment]
@andrewrk assuming remaining checks pass (they should) this is ready for merge, but I'd like to check you're okay with it first.

**Comment by andrewrk** [comment]
Yes please let me review this. My immediate reaction is that I think you have once again tried to add something inappropriate to InternPool, but I will keep an open mind and fully understand these changes before complaining about it.

**Comment by mlugg** [comment]
Okay - let me know if there's anything you would like me to clarify. FWIW, the sole purpose of this change is to *reduce* the amount of unstable (as in, must be modified across incremental updates) data in the InternPool, so I believe it is appropriate. (Garbage will be relatively low; garbage values will appear only when ZIR mapping fails to correlate an instruction, such as when a declaration is deleted, and in future I suspect we may be able to reuse these dead indices without a full GC sweep.)

**Comment by andrewrk** [comment]
One more data point that would be interesting would be the size of a serialized InternPool before and after this change for e.g. building the compiler. You can obtain this with the `--debug-incremental` flag. Note that this will require additional logic in `Compilation.saveState` since there is a new array added to InternPool.

**Comment by mlugg** [comment]
Sure, I'm happy to introduce that logic and check the size of this state. Would you like that to be ready before you review?

**Comment by mlugg** [comment]
Serialized InternPool state is 2.83 MiB before, 2.95 MiB after; 4% increase. I will push these changes shortly.

**Comment by mlugg** [comment]
Serialized InternPool state for building the compiler itself is 36.11 MiB before, 36.41 MiB after; 0.8% increase.

**Comment by andrewrk** [comment]
Can you provide a demonstration of running `zig changelist` on some examples to show how these changes produce better or equivalent results?

**Comment by mlugg** [comment]
Your comment doesn't make much sense to me given the material of this PR, so I suspect I may have unintentionally misled you somewhere. Let me clarify what's going on in this change.

The key improvement here isn't about the ZIR mapping we generate, but instead how we apply that mapping - i.e. the logc in `Zcu.updateZirRefs`. On `master` branch, after we generate the mapping, we attempt to traverse all `Decl`s which originate from the file in question, assuming that they form a connected graph (well, a tree really). For each of these `Decl`s, we update all required information: the ZIR index of the declaration, and the data associated with any `InternPool` data it owns (e.g. if the decl owns a struct type, we update the ZIR index associated with that struct type). This approach has several problems:
* We actually *can't* just traverse the graph like this, because generic instantiations are essentially "orphaned", i.e. are not reachable with our traversal strategy. This means we will never update the ZIR associated with any `Decl` which is a generic instantiation or a child of one, which alone kind of discounts the strategy.
* This requires specific logic for everywhere the `InternPool` might reference a ZIR instruction. This isn't a huge deal, but it is easy to forget!
* This could make the amount of work arbitrarily large; in the presence of generic instantiations, we must update all instantiations, which there could be hundreds of in the case of something like `std.ArrayList`!

So, this PR changes this logic. Instead of doing this complex graph traversal, we now just update all ZIR indices referenced by the flat array `tracked_insts`. The intention here is that where the `InternPool` wishes to reference a ZIR instruction, it can store an index into this array, and this acts as a **stable reference** to a single ZIR instruction; unchanging across incremental updates, even as the ZIR for that file might undergo constant changes. This simplifies and speeds up the application of the ZIR mapping, makes the system less bug-prone, and is also important for the dependency system I have begun to specify informally, where we need to represent dependencies on the source of ZIR instructions (declarations).

With all this being said, this PR *does* change the ZIR mapping algorithm slightly - I mentioned this in an earlier comment. It's essentially just a bugfix: before, unnamed declarations (`test`, `usingnamespace`, `comptime`) weren't handled correctly by the algorithm, in that it just assumed they were all named the empty string, so would correlate the first unnamed decl with the first unnamed decl and leave the rest unmapped. Here's a super trivial example showing this bug and that it is now fixed:
```shellsession
[mlugg@polaris test]$ cat foo.zig
comptime {}
comptime {}
[mlugg@polaris test]$ ~/zig/master/stage4/bin/zig changelist foo.zig foo.zig
Instruction mappings:
 %Zir.Inst.Index.main_struct_inst => %Zir.Inst.Index.main_struct_inst
Extra mappings:
 Zir.ExtraIndex(20) => Zir.ExtraIndex(20)
[mlugg@polaris test]$ ~/zig/incremental-the-second/stage4/bin/zig changelist foo.zig foo.zig
Instruction mappings:
 %1 => %1
 %0 => %0
 %3 => %3
```
Note that master gives 1 mapping (ignoring the main struct inst),while this branch gives 2.

**Comment by andrewrk** [comment]
> Your comment doesn't make much sense to me given the material of this PR, so I suspect I may have unintentionally misled you somewhere. Let me clarify what's going on in this change.

This is very charitable, thank you for taking the time to give an in-depth explanation. I think I'll save this for tomorrow and set aside a good chunk of time to dive into it, rather than trying to pack a review into the end of my long day.

**Comment by andrewrk** [comment]
Here is a perf measurement of building the self-hosted compiler with these changes:

```
Benchmark 1 (3 runs): zig build-exe ... (0.12.0-dev.2481+8a0429e88)
  measurement          mean ± σ            min … max           outliers         delta
  wall_time          76.6s  ± 2.02s     74.3s  … 78.2s           0 ( 0%)        0%
  peak_rss           4.60GB ±  341KB    4.60GB … 4.60GB          0 ( 0%)        0%
  cpu_cycles          302G  ±  553M      301G  …  302G           0 ( 0%)        0%
  instructions        418G  ± 55.9M      418G  …  418G           0 ( 0%)        0%
  cache_references   18.7G  ± 26.3M     18.7G  … 18.8G           0 ( 0%)        0%
  cache_misses       1.40G  ± 7.06M     1.39G  … 1.41G           0 ( 0%)        0%
  branch_misses      2.09G  ± 1.54M     2.08G  … 2.09G           0 ( 0%)        0%
Benchmark 2 (3 runs): zig build-exe ... (this branch)
  measurement          mean ± σ            min … max           outliers         delta
  wall_time          77.2s  ± 3.09s     73.7s  … 79.3s           0 ( 0%)          +  0.8% ±  7.7%
  peak_rss           4.62GB ± 44.5MB    4.60GB … 4.68GB          0 ( 0%)          +  0.6% ±  1.5%
  cpu_cycles          303G  ± 1.89G      302G  …  305G           0 ( 0%)          +  0.5% ±  1.0%
  instructions        422G  ± 2.45G      420G  …  425G           0 ( 0%)          +  0.9% ±  0.9%
  cache_references   18.9G  ± 17.5M     18.9G  … 18.9G           0 ( 0%)          +  0.8% ±  0.3%
  cache_misses       1.40G  ± 14.5M     1.39G  … 1.42G           0 ( 0%)          +  0.3% ±  1.8%
  branch_misses      2.10G  ± 14.6M     2.09G  … 2.11G           0 ( 0%)          +  0.5% ±  1.1%
```

Mostly insignificant. But an overall increase in all the stats across the board. It's not accurate to call this change a performance improvement.

**Comment by mlugg** [comment]
To be clear, I didn't call it a performance improvement; if you look back at my analysis, I found, similarly to you, an (insignificant) increase in most stats. The thing that got slightly faster is `AstGen` (`zig ast-check`).

**Pull request merged**
