### PR TITLE
Update std.zig.c_translation.zig to fix issue #15066

### PR DESCRIPTION
**Pull request by Banacial**
In issue [#15066](https://github.com/ziglang/zig/issues/15066), the cImport of a header with a definition for casting to `c_long` creates a cImport.zig, with: 
```
pub const LONG = https://github.com/import("std").zig.c_translation.Macros.L_SUFFIX; 
pub const X = LONG(@as(c_int, 10));
```
But since `@import("std).zig.c_translation.Macros.L_SUFFIX` only accepted `comptime_int`s, every cast to a `c_int` would cause a compile error. Instead going by the proposed typeInfo .Int and .ComptimeInt, this bug can be fixed.

Additionally I added a test for casting c Integers up to c_long to c_long.

### CODE REVIEW

**Comment by ehaas** [comment]
As an additional test - can you add the problematic macros:
```c
#define LONG(x) x##L
#define X LONG(10)
```

(or something like those) to `translate_c_macros.h` and then add a test to `translate_c_macros.zig` that tests that `h.X` is 10

**Comment by Banacial** [comment]
Added the original error as a test.
I just think that this file might be the wrong place to test for a specific macro. After all the macro is already being translated into zig by another step/process/file and the actual error occurs when zig attempted to call the translated macro.

```
pub const __MSABI_LONG = @import("std").zig.c_translation.Macros.L_SUFFIX;
pub const API_SET_SCHEMA_VERSION = __MSABI_LONG(@as(c_uint, 2));
```
The orignal issue occured when zig tried to call L_SUFFIX on a `c_uint` instead of a `compiletime_int`

**Comment by ehaas** [comment]
That test file will do what you want - If you run `zig test -I. behavior/translate_c_macros.zig` from the zig `test` directory, without your fix, you should see the error from issue #15066 (assuming you've added the defines to the `translate_c_macros.h` header and an appropriate test to the zig file, such as:

```zig
test "L suffix in macro" {
    if (builtin.zig_backend == .stage2_wasm) return error.SkipZigTest; // TODO
    if (builtin.zig_backend == .stage2_arm) return error.SkipZigTest; // TODO
    if (builtin.zig_backend == .stage2_aarch64) return error.SkipZigTest; // TODO
    if (builtin.zig_backend == .stage2_sparc64) return error.SkipZigTest; // TODO
    if (builtin.zig_backend == .stage2_spirv64) return error.SkipZigTest; // TODO

    try expectEqual(10, h.X);
}
```

With your fix, the test passes.

**Comment by Banacial** [comment]
My work is done here. I have no idea how to investigate why the linux build failed, since the only thing reported in the details is that it failed and I have no linux machine.

**Comment by ehaas** [comment]
It's complaining about the formatting - you need to run `zig fmt` on `lib/std/zig/c_translation.zig`

I still think the test should use `translate_c_macros.h` but that's a separate issue :)

**Comment by Banacial** [comment]
Why would that only cause an issue on linux then is the build process so inconsistent ? All for I care, the test could be removed entirely.

**Comment by ehaas** [comment]
The [x86_64 Linux CI script](https://github.com/ziglang/zig/blob/1a0e6bcdb140c844384d62b78a7f4247753f9ffd/ci/x86_64-linux-release.sh#L55) checks formatting; the ones that passed do not.

**Comment by Banacial** [comment]
> The [x86_64 Linux CI script](https://github.com/ziglang/zig/blob/1a0e6bcdb140c844384d62b78a7f4247753f9ffd/ci/x86_64-linux-release.sh#L55) checks formatting; the ones that passed do not.

How about we just dont check the fmt, but just run it instead ?
```
# TODO: move this to a build.zig step (check-fmt)
echo "Looking for non-conforming code formatting..."
stage3-release/bin/zig fmt --check .. \
  --exclude ../test/cases/ \
  --exclude ../build-debug \
  --exclude ../build-release
```
There was an additional space between the switch type and the arrow in one line (388).

**Comment by Banacial** [comment]
Ok now what is this madness ? All tests passed, but since the brnach was out of date with the main one and had to be updated, all checks have to run again?
This still is my first PR with no prior Github experience, how do I just get this PR over with ?

**Comment by andrewrk** [comment]
The first step to getting it over with would be to add test coverage for your fix.

**Comment by Banacial** [comment]
> As an additional test - can you add the problematic macros:
> 
> ```c
> #define LONG(x) x##L
> #define X LONG(10)
> ```
> 
> (or something like those) to `translate_c_macros.h` and then add a test to `translate_c_macros.zig` that tests that `h.X` is 10

Added this specific test and another general test in the main file

**Comment by Banacial** [comment]
> All tests passed, but since the branch was out of date with the main one and had to be updated, all checks have to run again? 

> The first step to getting it over with would be to add test coverage for your fix.

Whats the next step ? 
1. Waiting for a maintainer to merge the branch, or 
2. Updating the branch, checking the updated branch, and then wait for later merge

**Comment by Vexu** [comment]
The branch doesn't need to be updated unless conflicting or otherwise interfering changes were added to master.

**Comment by Banacial** [comment]
thx for the information, help and merge!

**Pull request merged**
