### PR TITLE
Add OpenBSD support (WIP)

### PR DESCRIPTION
**Pull request by ibara**
Hi --

This pull request will provide support for zig on OpenBSD. It is a work-in-progress right now; the syscall parts need to be finished up.

### CODE REVIEW

**Comment by andrewrk** [comment]
ooh this is exciting. looks really good so far. let me know if you have any questions or suggestions.

**Comment by andrewrk** [comment]
Also note: since we have lazy top level declarations, this code that you're adding is strictly an improvement, so as far as I'm concerned it's already good to merge, and we can keep working on getting closer towards all tests passing on OpenBSD.

**Comment by ibara** [comment]
My guess is at the moment OpenBSD will just fail spectacularly since it will try to access Linux syscalls (which of course don't map onto OpenBSD syscalls at all). But if you think it's good enough to import, great, and I'll keep on working on this.

**Comment by andrewrk** [comment]
My mistake. I assumed that you had looked up the syscalls for OpenBSD.

I would like to follow a different approach for development, which is, start with nothing, instead of starting with an incorrect copy, and slowly grow the nothing into complete OpenBSD support.

It's too error prone to start with an incorrect copy and then try to remember to fix everything. Let the errors be compile errors for missing functions.

**Comment by ibara** [comment]
The Linux skeleton was for me to ensure proper coding style for you. I'm ok with starting with nothing and building up.

That's why I mentioned this is a WIP :). I won't ask to have this committed until I'm finished with at least amd64 (I assume there's a reason you have disabled i386 on Linux, and I simply followed suit).

**Comment by andrewrk** [comment]
> (I assume there's a reason you have disabled i386 on Linux, and I simply followed suit).

Before I had travis set up to test automatically, the 32 bit one bit rotted, so I disabled it. When 32 bit support is desired we can work on getting it back up to speed.

Which reminds me, one thing we should figure out as part of OpenBSD support is how to test it. Even if we don't get some kind of continuous integration going, however, we can at least verify that the tests compile for OpenBSD by adding it to the cross compile matrix.

**Pull request closed without merging**
