### PR TITLE
Hex float parsing

### PR DESCRIPTION
**Pull request by mattnite**
Only f128 right now, but just want to get this in for andrew and add other floating point types later

### CODE REVIEW

**Comment by andrewrk** [comment]
@lemonboy this might be interesting to you:

```
Test [751/1834] fmt.parse_float.test "std-powerpc-linux-none-Debug-bare-multi fmt.parseHe... 
thread 21170 panic: expected 8.0e+00, found 0.0e+00
/home/vsts/work/1/s/lib/std/testing.zig:78:32: 0x107c770f in testing.expectEqual (test)
                std.debug.panic("expected {}, found {}", .{ expected, actual });
                               ^
/home/vsts/work/1/s/lib/std/fmt/parse_float.zig:498:16: 0x1017e2b7 in fmt.parse_float.test "std-powerpc-linux-none-Debug-bare-multi fmt.parseHexFloat" (test)
    expectEqual(@as(f128, 0x1.p3), try parseHexFloat("0x1.p3"));
               ^
```

**Comment by andrewrk** [comment]
@mattnite I got a bunch of crashes like this:

```
thread 31608 panic: reached unreachable code
/home/andy/dev/zig/src/AstGen.zig:5784:55: 0x5f37d0 in AstGen.floatLiteral (zig)
            error.Overflow, error.InvalidCharacter => unreachable,
                                                      ^
/home/andy/dev/zig/src/AstGen.zig:627:46: 0x54470a in AstGen.expr (zig)
        .float_literal => return floatLiteral(gz, scope, rl, node),
                                             ^
/home/andy/dev/zig/src/AstGen.zig:4178:24: 0x5e47dc in AstGen.simpleBinOp (zig)
        .lhs = try expr(gz, scope, .none, node_datas[node].lhs),
                       ^
```

also this:

```
thread 31756 panic: index out of bounds
/home/andy/dev/zig/lib/std/fmt/parse_float.zig:484:71: 0x2dd481 in std.fmt.parse_float.parseHexFloat (zig)
            @clz(u4, @truncate(u4, try std.fmt.charToDigit(decimal_str[leading_zeroes], 16)));
                                                                      ^
/home/andy/dev/zig/src/AstGen.zig:5783:30: 0x5f37e2 in AstGen.floatLiteral (zig)
        std.fmt.parseHexFloat(bytes) catch |e| switch (e) {
                             ^
/home/andy/dev/zig/src/AstGen.zig:627:46: 0x54476a in AstGen.expr (zig)
        .float_literal => return floatLiteral(gz, scope, rl, node),
                                             ^
```

if you grep for any hex float in lib/std/math/* I think most of them are crashing the parser. here are some of them that definitely failed:

```
math/trunc.zig:49:36: error: internal compiler error parsing hex float
        math.doNotOptimizeAway(x + 0x1p120);
                                   ^
math/expo2.zig:35:18: error: internal compiler error parsing hex float
    const kln2 = 0x1.62066151ADD8BP+10;
                 ^
math/complex/sinh.zig:63:23: error: internal compiler error parsing hex float
            const h = 0x1p127 * x;
                      ^
math/complex/cosh.zig:63:23: error: internal compiler error parsing hex float
            const h = 0x1p127 * x;
                      ^
```

**Comment by LemonBoy** [comment]
> this might be interesting to you:

Nope, it's a boring-ass case of endianness being wrong. See the patch below.

I don't really like this parser using `mem.split`, a state-machine one would be best IMO.
It also doesn't support positive/negative nan/inf nor underscores in the hex groups.
The test cases should test the parsing of `fNN_{max,min}` and subnormal numbers. I can't remember if we support unnormalized fp constants but if that's the case those should be tested too.

```patch
diff --git a/lib/std/fmt/parse_float.zig b/lib/std/fmt/parse_float.zig
index 0b3398c8d..1895babc6 100644
--- a/lib/std/fmt/parse_float.zig
+++ b/lib/std/fmt/parse_float.zig
@@ -418,12 +418,6 @@ test "fmt.parseFloat" {
     }
 }
 
-const F128 = packed struct {
-    mantissa: u112,
-    exponent: u15,
-    sign: u1,
-};
-
 pub fn parseHexFloat(bytes: []const u8) !f128 {
     if (bytes.len < 6)
         return error.InvalidCharacter;
@@ -485,11 +479,10 @@ pub fn parseHexFloat(bytes: []const u8) !f128 {
         break :blk @truncate(u112, decimal << leading_bits);
     };
 
-    return @bitCast(f128, F128{
-        .sign = sign,
-        .exponent = @bitCast(u15, exp) +% 0x3fff,
-        .mantissa = mantissa,
-    });
+    const as_int = @as(u128, sign) << 127 |
+        @as(u128, (@bitCast(u15, exp) +% 0x3fff)) << 112 |
+        mantissa;
+    return @bitCast(f128, as_int);
 }
 
 test "fmt.parseHexFloat" {

```

**Comment by andrewrk** [comment]
=>  #8634

**Pull request closed without merging**
