### PR TITLE
Added support for no red zone

### PR DESCRIPTION
**Pull request by leecannon**
I have been writing a kernel in zig and never thought to check about the red zone until I saw #7436.

This pull requests adds the option to not use the red zone, the functionality is accessible in two ways:

- In `build.zig` set `no_red_zone` on `*LibExeObjStep` to true
- When calling `zig build-exe/lib/obj` pass `-fno-red-zone`

I have verified using `--verbose-llvm-ir` that `noredzone` is included in the function attributes.

This is the first time I have looked at the compiler internals so I'm sure I missed something, any feedback is appreciated.

### CODE REVIEW

**Comment by LemonBoy** [comment]
You also want `-fred-zone` to complement `-fno-red-zone`.

**Comment by leecannon** [comment]
Added `-fred-zone`

**Comment by BinaryWarlock** [comment]
Awesome, this mirrors what GCC/Clang do and provides guarantees about it. :+1:, haven't tested it though.

**Comment by leecannon** [comment]
@BinaryWarlock I made it private as there are parts of the design I'm not happy with. But I've split parts out into other repos.

**Comment by andrewrk** [comment]
Thanks! Landed in 0edde40c25c033aec67f235365593ee26ff52740 with some minor adjustments.

**Pull request closed without merging**
