### PR TITLE
Bump zig-bootstrap and wasmtime versions in linux CI

### PR DESCRIPTION
**Pull request by kubkon**
cc @Luukdegram as it touches stage2 Wasm code which might be of interest according to git blame.

### CODE REVIEW

**Review by ifreund — APPROVED** [review]
I originally wrote the stage2 test this touches and the change LGTM. Nice to see that wasmtime prints floats properly now :)

**Comment by Luukdegram** [comment]
> cc @Luukdegram as it touches stage2 Wasm code which might be of interest according to git blame.

Thanks!

**Comment by kubkon** [comment]
I'll need to revert wasmtime to v0.22.1 as this is the latest version that our libstd supports; for later versions of wasmtime, we're blocked by this issue #8742.

**Comment by kubkon** [comment]
I've also had to revert wasm stage2 test fixup since printing of floats is fixed in later version wasmtime than we can support: blocked on the same issue #8742.

**Pull request merged**
