### PR TITLE
Check the file type after open() in Dir.openFile() when using WASI

### PR DESCRIPTION
**Pull request by jedisct1**
When the `O_DIRECTORY` flag is not present, Wasmtime now opens files and directories the same way, and returns a descriptor in any case.

So, explicitly check the file type after opening it, and return `err.IsDir` if what we actually have is a directory.

Fixes the `lib/std/fs` `"file operations on directories"` test on WASI with Wasmtime 9.0.0

### CODE REVIEW

**Comment by squeek502** [comment]
I would guess that wasmtime behaves differently here on Windows vs non-Windows. Related: https://github.com/ziglang/zig/issues/13157

I'm having a very hard time navigating wasmtime/wasi spec/etc to understand if/where this behavior is specified, why it changed, how it changed, etc. On first glance it seems like it'd be a wasmtime/wasi spec bug (assuming at least that wasmtime wants each host platform to behave the same, again see https://github.com/ziglang/zig/issues/13157#issuecomment-1297742484).

**Comment by jedisct1** [comment]
[Here](https://github.com/bytecodealliance/wasmtime/commit/efdfc361f83294cc520d1f2f9f05479050e3baa2) is where the change may have been introduced.

I think the intent was to be In line with how `O_DIRECTORY` works on POSIX.

**Comment by squeek502** [comment]
Also related: https://github.com/ziglang/zig/issues/5732

https://github.com/ziglang/zig/blob/a0652fb93077322c331345e1aeff25d5338f30b0/lib/std/fs/test.zig#L458-L460

I wonder if this would be considered a wasmtime bug, in that it seems like it's allowing opening directories for writing.

**Comment by squeek502** [comment]
I can't reproduce the `file operations on directories` test failure with `wasmtime 9.0.1` with Linux as the host OS.

```console
$ wasmtime --version
wasmtime-cli 9.0.1
$ zig version
0.11.0-dev.3277+a0652fb93
$ zig test --zig-lib-dir lib --main-pkg-path lib/std -target wasm32-wasi --test-cmd wasmtime --test-cmd --dir=. --test-cmd-bin lib/std/std.zig
...
1106/2505 test.file operations on directories... OK
...
2354 passed; 151 skipped; 0 failed.
```

**Comment by jedisct1** [comment]
Still failing for me with wasmtime 9.0.1:

```
run test std-wasm32-wasi-Debug-libc: error: 'test.file operations on directories' failed: expected error.IsDir, found fs.file.File{ .han
dle = 1098, .capable_io_mode = io.ModeOverride__enum_7224.blocking, .intended_io_mode = io.ModeOverride__enum_7224.blocking }
```

**Comment by jedisct1** [comment]
Is that the intended behavior, or a wasmtime bug? /cc @jameysharp

**Comment by jameysharp** [comment]
I don't understand what this test is trying to do, and I also don't understand WASI very well, either in spec or in implementation. So I don't know how to answer that question.

I do think the idea of a `FILE_NON_DIRECTORY_FILE`-like flag as the opposite of `O_DIRECTORY` is an interesting idea that would be worth taking to the WASI folks.

And I'm curious about this as well:
> Actually, why isn't the `openat` syscall within wasmtime returning `EISDIR` here? Is it not being called with `O_RDWR` even though the test is passing `.read_write`?

**Comment by jedisct1** [comment]
@jameysharp The test opens a directory (without `O_DIRECTORY`) for writes, and a proper handle is returned instead of an error.

I think this is a recent change. On CI which is still running Wasmtime 2.0.2, the test passes.

**Comment by squeek502** [comment]
Looks like `wasi-libc` is translating `openat` to an [`openat2`](https://man.archlinux.org/man/openat2.2.en) syscall. From strace (which doesn't recognize the openat2 syscall number):

```c
// notes: 0x1b5 = 437 which is openat2, 0x3 is the cwd's fd, 0x18 is sizeof(struct open_how)
syscall_0x1b5(0x3, 0x7ffe0db39fc8, 0x7ffe0db39f68, 0x18, 0, 0) = 0x5
```

According to the openat2 docs, all the possible errors of `openat` should apply to `openat2`, so my guess is that this is either a bug in the `wasi-libc` implementation of `openat2` or `wasi-libc` is effectively dropping the `O_RDWR` somewhere before calling `openat2`. Need to somehow figure out what's in the `open_how` struct being passed to `openat2`.

Here's how I'm testing:

```zig
// open-dir-rw.zig
const std = @import("std");

pub fn main() !void {
    const test_dir_name = "testdir";
    try std.fs.cwd().makePath("testdir");

    try std.testing.expectError(error.IsDir, std.fs.cwd().openFile(test_dir_name, .{ .mode = .read_write }));
}
```

```
zig build-exe -target wasm32-wasi open-dir-rw.zig -lc
```

```
wasmtime --dir=. open-dir-rw.wasm
```
or with strace
```
strace wasmtime --dir=. open-dir-rw.wasm
```

**Comment by squeek502** [comment]
Update `strace` so that it recognizes `openat2`.

With `libc` linked (no `EISDIR`):

```c
openat2(3, "testdir", {flags=O_RDONLY|O_CLOEXEC, resolve=RESOLVE_NO_MAGICLINKS|RESOLVE_BENEATH}, 24) = 5
```

Without `libc` linked (gets `EISDIR`):

```c
openat2(3, "testdir", {flags=O_RDWR|O_APPEND|O_NOFOLLOW|O_CLOEXEC, resolve=RESOLVE_NO_MAGICLINKS|RESOLVE_BENEATH}, 24) = -1 EISDIR (Is a directory)
```

**Comment by jedisct1** [comment]
This is actually a bug in Wasmtime: https://github.com/bytecodealliance/wasmtime/pull/6462

And more importantly, they are planning to released a fixed version soon, so we don't need the extra `stat()s`.

That was also a good reminder that we should constantly keep `wasmtime` up to date on the CI, and eventually run the tests with other runtimes to spot inconsistencies.

Thanks a lot @squeek502 for your help and investigation!

**Pull request closed without merging**
