### PR TITLE
Fortified libc functions

### PR DESCRIPTION
**Pull request by LemonBoy**
@MasterQ32 please check if this patch solves your problems.

### CODE REVIEW

**Comment by MasterQ32** [comment]
Now crashes with `error.FileNotFound` somewhere in the cache system (see #6483), i don't know if it works or not :disappointed:

**Comment by alexnask** [comment]
The MSVC failure here (as well as a couple of other recent PRs) happens because the msys2 package repository appears to be down at the moment.

**Comment by MasterQ32** [comment]
> @MasterQ32 please check if this patch solves your problems
> 
> The stage2 patch is here because it was too silly to deserve its own PR.

Sadly, it does not help :(
You can build https://github.com/MasterQ32/cg-workbench with `zig build -Dtarget=x86_64-windows-gnu -Dstrip -Drelease-safe` to reproduce the problem. I'm currently at `9952a072cc120f5dc134bb1070ad02dfab59cefa` + your two commits

**Comment by LemonBoy** [comment]
> Sadly, it does not help :(

It seems that `c.zig` is not linked in for `zig cc` objects, @andrewrk can you confirm?

**Comment by LemonBoy** [comment]
@MasterQ32 I got `cg-workbench` to build and link successfully, but it doesn't seem to work under Wine :( 
Can you try again if the PR fixes the problem for you?

**Comment by MasterQ32** [comment]
I can confirm: It now builds for windows with the patches :)

**Comment by andrewrk** [comment]
> It seems that `c.zig` is not linked in for `zig cc` objects, @andrewrk can you confirm?

Sorry for the late response; I see that you found the relevant code paths. This is some nice work, thanks a bunch.

**Pull request merged**
