### PR TITLE
std: add CCRandomGenerateBytes macOs native api.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by devnexen** [comment]
cc @kubkon 

I think it can replace, for iOs/macOs only tough, the actual arc4random_buf call from the getrandom wrapper for similar reasons as [openssl did](https://github.com/openssl/openssl/commit/f0b9e75e4f9d6ae74389cd1b019b77cf2bd01033) (e.g. this call returning a status, possible issue with no len with arc4random_buf, ...), what do you think ?

**Comment by kubkon** [comment]
> cc @kubkon
> 
> I think it can replace, for iOs/macOs only tough, the actual arc4random_buf call from the getrandom wrapper for similar reasons as [openssl did](https://github.com/openssl/openssl/commit/f0b9e75e4f9d6ae74389cd1b019b77cf2bd01033) (e.g. this call returning a status, possible issue with no len with arc4random_buf, ...), what do you think ?

If this is what openssl did I think it's a good idea. @jedisct1 thoughts?

**Comment by jedisct1** [comment]
As far as I know the underlying RNG is exactly the same. The only difference being that using that API increases the chances of getting an app accepted on the App Store.

Still not a bad thing.

**Comment by kubkon** [comment]
Mhm, I see. Is there a minimum OS version where this is available? If this is a fairly recent addition we need to either version-gate, or wait a couple of macOS releases for it to be supported across the latest OS versions.

**Comment by devnexen** [comment]
Since Yosemite/iOs 8.

**Comment by kubkon** [comment]
Just to double check, `CCRandomGenerateBytes` is part of `libSystem` and not of `Security.framework`?

**Comment by devnexen** [comment]
not part of Security.framework.

**Comment by kubkon** [comment]
In that case I would be in favour of moving from `arc4random_buf` to `CCRandomGenerateBytes`. Also, as per https://www.niap-ccevs.org/Documents_and_Guidance/view_td.cfm?TD=0510 it's apparently faster and as per https://github.com/microsoft/mimalloc/pull/390 it doesn't silently fail unlike the old interface.

**Comment by devnexen** [comment]
@kubkon what do you think now ? 🙂

**Comment by kubkon** [comment]
Are the macOS CI failures related?

**Comment by devnexen** [comment]
does not seem to be the case, beside it happens only on x86 64 arch.

**Comment by devnexen** [comment]
seems all pass @kubkon 🙂

**Comment by devnexen** [comment]
cc @Vexu 🙂

**Pull request merged**
