### PR TITLE
Support inline keyword as well as callconv(.Inline)

### LINKED ISSUE #6429: support both inline keyword as well as callconv(.Inline)
[accepted proposal](https://github.com/ziglang/zig/issues/6429#issuecomment-843757556)

--------------

`inline` is mutually exclusive with a custom calling convention, I think this makes it simpler.
`noinline` is unaffected.

### PR DESCRIPTION
**Pull request by ifreund**
Closes #6429

### CODE REVIEW

**Comment by marler8997** [comment]
Poor inline feeling the whiplash

**Comment by jedisct1** [comment]
Welcome back, `inline`! 🎉

**Comment by ifreund** [comment]
Ah, looks like I forgot about translate-c, will fix shortly

**Comment by andrewrk** [comment]
Thanks!

**Pull request merged**
