### PR TITLE
Add std.math.degrees and std.math.radians

### PR DESCRIPTION
**Pull request by frmdstryr**
Implements simple conversion functions for `degrees` and `radians`. 

A quick search brings up https://github.com/ziglang/zig/issues/9889

### CODE REVIEW

**Comment by topolarity** [comment]
It'd be clearer to mention both sides of the conversion in the function names, such as the relatively-standard `deg2rad`/`rad2deg` or the expanded `degreesToRadians`/`radiansToDegrees`

**Comment by r00ster91** [comment]
I actually needed this recently.

As for the naming, if you think the expanded variants are too long, I'd go with a hybrid that is not old-fashioned but also not too long: `degToRad` and `radToDeg`.
But personally I'd prefer the expanded variants anyway.

**Comment by InKryption** [comment]
I would also prefer the expanded variants. `radToDeg` and `degToRad` look weird.

**Comment by frmdstryr** [comment]
Thanks!

**Pull request merged**
