### PR TITLE
The Great Decl Split (preliminary work): refactor source locations and eliminate `Sema.Block.src_decl`.

### PR DESCRIPTION
**Pull request by mlugg**
See commit messages for details. In short, this PR performs a large refactor of the `LazySrcLoc` system used during semantic analysis, and ultimately eliminates the `src_decl` field from `Sema.Block`, which drops a huge amount of unreasonable responsibilities from `Zcu.Decl`. This work is all done in preparation for splitting `Decl` into two separate types `Nav` (Named Addressable Value, representing effectively a global name with an address, which may be comptime; in practice, a source-level declaration, or a generic function instantiation) and `Cau` (Comptime Analysis Unit, representing the subject of comptime semantic analysis; in practice, a source-level declaration, or a namespace type). This change has two ultimate goals: codebase simplification and incremental compilation.

### CODE REVIEW

**Comment by Snektron** [comment]
SPIR-V related changes seem fine

**Comment by mlugg** [comment]
(sorry, ignore the request robin, GH mobile app sucks)

**Comment by andrewrk** [comment]
Performance data point on the self-hosted compiler (merge-base vs this PR):

```
Benchmark 1 (5 runs): /home/andy/dev/zig/build-release/stage3/bin/zig build-exe --stack 33554432 -fno-sanitize-thread -ODebug --dep aro --dep aro_translate_c --dep build_options -Mroot=/home/andy/dev/zig/src/main.zig -Maro=/home/andy/dev/zig/lib/compiler/aro/aro.zig --dep aro -Maro_translate_c=/home/andy/dev/zig/lib/compiler/aro_translate_c.zig -Mbuild_options=/home/andy/src/zig/.zig-cache/c/8e749f7664ff8b5ea386edcbb3b21788/options.zig -fno-emit-bin --cache-dir /home/andy/dev/zig/.zig-cache --global-cache-dir /home/andy/.cache/zig --name zig
  measurement          mean ± σ            min … max           outliers         delta
  wall_time          4.25s  ± 42.3ms    4.20s  … 4.32s           0 ( 0%)        0%
  peak_rss            231MB ±  304KB     231MB …  232MB          1 (20%)        0%
  cpu_cycles         22.9G  ± 83.3M     22.8G  … 23.0G           0 ( 0%)        0%
  instructions       42.5G  ± 15.9K     42.5G  … 42.5G           0 ( 0%)        0%
  cache_references   2.14G  ± 6.12M     2.14G  … 2.15G           0 ( 0%)        0%
  cache_misses       87.2M  ± 1.02M     86.1M  … 88.6M           0 ( 0%)        0%
  branch_misses      74.2M  ±  490K     73.4M  … 74.7M           0 ( 0%)        0%
Benchmark 2 (5 runs): /home/andy/src/zig/build-release/stage3/bin/zig build-exe --stack 33554432 -fno-sanitize-thread -ODebug --dep aro --dep aro_translate_c --dep build_options -Mroot=/home/andy/src/zig/src/main.zig -Maro=/home/andy/src/zig/lib/compiler/aro/aro.zig --dep aro -Maro_translate_c=/home/andy/src/zig/lib/compiler/aro_translate_c.zig -Mbuild_options=/home/andy/src/zig/.zig-cache/c/8e749f7664ff8b5ea386edcbb3b21788/options.zig -fno-emit-bin --cache-dir /home/andy/src/zig/.zig-cache --global-cache-dir /home/andy/.cache/zig --name zig
  measurement          mean ± σ            min … max           outliers         delta
  wall_time          4.44s  ± 74.4ms    4.36s  … 4.51s           0 ( 0%)        💩+  4.4% ±  2.1%
  peak_rss            223MB ±  399KB     222MB …  223MB          1 (20%)        ⚡-  3.6% ±  0.2%
  cpu_cycles         23.8G  ±  176M     23.6G  … 24.0G           0 ( 0%)        💩+  4.2% ±  0.9%
  instructions       46.9G  ±  508K     46.9G  … 46.9G           0 ( 0%)        💩+ 10.2% ±  0.0%
  cache_references   2.15G  ± 8.53M     2.14G  … 2.16G           0 ( 0%)          +  0.3% ±  0.5%
  cache_misses       98.5M  ± 2.75M     95.8M  …  102M           0 ( 0%)        💩+ 12.9% ±  3.5%
  branch_misses      75.8M  ±  533K     75.0M  … 76.5M           0 ( 0%)        💩+  2.1% ±  1.0%
```

Seems to be doing significantly more work and hitting a lot more cache misses too.

**Comment by andrewrk** [comment]
Performance data point - hello world (merge-base vs this PR):

```
Benchmark 1 (60 runs): /home/andy/dev/zig/build-release/stage3/bin/zig build-exe ../test/standalone/simple/hello_world/hello.zig -fno-emit-bin
  measurement          mean ± σ            min … max           outliers         delta
  wall_time          84.1ms ± 5.46ms    74.6ms … 96.0ms          0 ( 0%)        0%
  peak_rss           89.4MB ±  675KB    87.8MB … 91.2MB          2 ( 3%)        0%
  cpu_cycles          324M  ± 1.20M      321M  …  327M           2 ( 3%)        0%
  instructions        569M  ± 6.31K      569M  …  569M           0 ( 0%)        0%
  cache_references   31.1M  ±  162K     30.9M  … 31.9M           1 ( 2%)        0%
  cache_misses       1.84M  ± 22.9K     1.79M  … 1.90M           2 ( 3%)        0%
  branch_misses      1.74M  ± 10.8K     1.71M  … 1.77M           4 ( 7%)        0%
Benchmark 2 (59 runs): /home/andy/src/zig/build-release/stage3/bin/zig build-exe ../test/standalone/simple/hello_world/hello.zig -fno-emit-bin
  measurement          mean ± σ            min … max           outliers         delta
  wall_time          85.9ms ± 4.03ms    77.3ms … 94.8ms          0 ( 0%)          +  2.2% ±  2.1%
  peak_rss           85.5MB ±  551KB    84.4MB … 87.0MB          3 ( 5%)        ⚡-  4.3% ±  0.3%
  cpu_cycles          336M  ± 1.49M      332M  …  340M           0 ( 0%)        💩+  3.6% ±  0.2%
  instructions        619M  ± 53.7K      619M  …  619M           0 ( 0%)        💩+  8.8% ±  0.0%
  cache_references   31.7M  ±  251K     31.4M  … 33.3M           3 ( 5%)        💩+  1.7% ±  0.2%
  cache_misses       2.03M  ± 29.7K     1.95M  … 2.09M           0 ( 0%)        💩+ 10.3% ±  0.5%
  branch_misses      1.78M  ± 10.3K     1.75M  … 1.80M           3 ( 5%)        💩+  2.0% ±  0.2%
```

**Review by andrewrk — APPROVED** [review]
This all looks very nice - simplified logic, and one less pesky field in Decl is a great step towards incremental. I'm looking forward to this landing. I do think we should figure out what's going on with the perf regression however.

**Comment by mlugg** [comment]
Performance issue resolved by 2b677d1. After replicating @andrewrk's results, I identified the issue using valgrind (callgrind), and verified the fix by building `test/standalone/simple/hello_world/hello.zig` on a `ReleaseFast` compiler. We now see within-error or slightly better metrics across the board:
```
Benchmark 1 (196 runs): <snip>
  measurement          mean ± σ            min … max           outliers         delta
  wall_time           102ms ± 2.64ms    97.3ms …  119ms          6 ( 3%)        0%
  peak_rss           45.8MB ±  185KB    45.3MB … 46.3MB          2 ( 1%)        0%
  cpu_cycles          361M  ± 8.78M      348M  …  426M          12 ( 6%)        0%
  instructions        556M  ±  536K      555M  …  557M           0 ( 0%)        0%
  cache_references   32.8M  ±  490K     31.8M  … 36.8M           8 ( 4%)        0%
  cache_misses       2.37M  ±  135K     2.15M  … 3.31M           6 ( 3%)        0%
  branch_misses      2.07M  ± 34.7K     2.01M  … 2.32M           4 ( 2%)        0%
Benchmark 2 (200 runs): <snip>
  measurement          mean ± σ            min … max           outliers         delta
  wall_time           100ms ± 2.11ms    95.9ms …  113ms          2 ( 1%)        ⚡-  2.0% ±  0.5%
  peak_rss           46.1MB ±  203KB    45.5MB … 46.6MB          1 ( 1%)          +  0.8% ±  0.1%
  cpu_cycles          353M  ± 5.11M      342M  …  368M           2 ( 1%)        ⚡-  2.3% ±  0.4%
  instructions        542M  ±  291K      541M  …  543M           1 ( 1%)        ⚡-  2.4% ±  0.0%
  cache_references   32.8M  ±  327K     32.0M  … 33.8M           5 ( 3%)          +  0.0% ±  0.2%
  cache_misses       2.27M  ±  111K     2.04M  … 2.68M           2 ( 1%)        ⚡-  4.1% ±  1.0%
  branch_misses      2.02M  ± 29.1K     1.97M  … 2.14M           2 ( 1%)        ⚡-  2.5% ±  0.3%
```

**Pull request merged**
