### PR TITLE
Support CRLF line endings in multiline string literals in the stdlib tokenizer

### PR DESCRIPTION
**Pull request by alexnask**
Before tokenizer change

### CODE REVIEW

**Comment by MasterQ32** [comment]
Will these be included verbatim in the final string or will they be replaced by `\n`? I don't think it's a good idea to have this as these strings might differ between checkouts (see `autocrlf`)

**Comment by LemonBoy** [comment]
Needs a test!

**Comment by alexnask** [comment]
@MasterQ32 This is not the tokenizer's job but I will modify stage2's astgen to take it into account and remove the carriage return in case it's immediately before the line feed.  
zig fmt already seems to handle this correctly with the fix but I will double check.

**Comment by LemonBoy** [comment]
> I will modify stage2's astgen to take it into account and remove the carriage return in case it's immediately before the line feed.

That's awful! What if the user explicitly inserted a `cr lf` sequence?
They'd have no idea it was removed until the tests start failing, `zig fmt` should not mess with the string literals content.

**Comment by alexnask** [comment]
I could go with either tbh.  
On the one hand, I love the fact that multiline string literals include every byte as-is (except for ascii control codes whch are disallowed).  
On the other hand, a big reason we support `\r\n` in stage2 is to make it easier for (often inexperienced) Windows users to use zig.  
I feel like supporting CRLF line endings also means that `\r\n` at the end of a multiline string literal should be interpreted as a single newline.  
Anyway, this is trivial to change, I will go with whatever is decided.

**Comment by data-man** [comment]
@alexnask 
What about other newlines? https://github.com/ziglang/zig/issues/6754#issuecomment-713687898

**Comment by MasterQ32** [comment]
> They'd have no idea it was removed until the tests start failing, `zig fmt` should not mess with the string literals content.

The string literals don't contain a line ending though (to my understanding) and will be joined together by the parser, not the tokenizer. This means that zig *should* always use the same line endings in multiline literals and *not* depend on the encoding of the file! Otherwise, nobody will ever use multiline literals as you cannot rely on them being deterministic

**Comment by alexnask** [comment]
@data-man 
I believe the plan is to support `\n` and `\r\n` exclusively, someone correct me if I'm wrong.

**Comment by LemonBoy** [comment]
> > They'd have no idea it was removed until the tests start failing, `zig fmt` should not mess with the string literals content.
> 
> The string literals don't contain a line ending though (to my understanding) and will be joined together by the parser, not the tokenizer. This means that zig _should_ always use the same line endings in multiline literals and _not_ depend on the encoding of the file! Otherwise, nobody will ever use multiline literals as you cannot rely on them being deterministic

Hmm, I never paid much attention to this but I always assumed the multiline literals were left untouched.
The language reference is pretty light on details and doesn't tell much, if the compiler implicitly inserts `\n` that should be at least documented.

Anyway, I'm still not convinced by the idea of silently dropping `CR`s as that's really hard to debug if you don't know about this behaviour.

**Comment by MasterQ32** [comment]
> Anyway, I'm still not convinced by the idea of silently dropping CRs as that's really hard to debug if you don't know about this behaviour.

Imho it should never be "inserted" in the first place. Multiline string literals are not c++ raw literals (that might even contain non-printable bytes or illegal byte sequences whereas zig source is defined to always be correct utf-8.

I don't think it should matter at all how the lines in a zig source file are terminated, it should not affect the outcome of the final product

**Review by Vexu — APPROVED** [review]
I agree with trimming CR, if the user wants CRLF line ending they should be explicit about it and use normal strings with escape sequences.

**Pull request closed without merging**
