### PR TITLE
 use * for pointer type instead of &

### PR DESCRIPTION
**Pull request by andrewrk**
This is part of Pointer Reform (See #770).

To help automatically translate code, see the
`zig-fmt-pointer-reform-2` branch. It will convert all `&` into `*`. Due to the syntax
ambiguity (which is why we are making this change),
even address-of `&` will turn into `*`, so you'll have
to manually fix these instances. You will be guaranteed
to get compile errors for them - `expected 'type', found 'foo'`

This fixes the cause of a lot of comptime bugs - the fact that
you could not have a pointer to a type (See #588)

This patch does *not* implement a new pointer type. It only changes the syntax and then fixes the bugs that were caused by the syntactic ambiguity. Further progress on Pointer Reform will happen gradually.

### CODE REVIEW

**Comment by andrewrk** [comment]
Hm, I just realized that AppVeyor has not been running since the rename from zig-lang. Fixing now.

**Comment by andrewrk** [comment]
All checks passed. I will merge this tomorrow morning.

**Comment by andrewrk** [comment]
@Hejsil I'd be happy to deal with merging master into `std-meta` for you and solve the merge conflicts. And also look into that TypeInfo thing.

**Comment by Hejsil** [comment]
@andrewrk Sure thing. Idk if I got all redundant builtin removed, but I guess that can wait :)

**Comment by andrewrk** [comment]
Ok, I pushed `std-meta-rebased`. This has conflicts with master fixed and I ran `zig fmt` to minimize future conflicts. Now I'll look into the TypeInfo problem.

**Comment by andrewrk** [comment]
I think this can be fixed to actually use nullables now:
`            if (UnionTag == @typeOf(undefined))`

**Pull request merged**
