### PR TITLE
std: Avoid deadlocking in ChildProcess.exec

### PR DESCRIPTION
**Pull request by LemonBoy**
This is my MVP for #6343 and, after some brief testing sessions, it seems to work.
I've left a few comments to outline some areas where this can & should be improved.
Putting this out as a Draft to let the many Windows users test it (@mlarouche) and the reviewers with WinAPI experience chime in.

### CODE REVIEW

**Comment by mlarouche** [comment]
Will make some time today to test it on Windows :)

**Comment by mlarouche** [comment]
Still deadlocking when building C code :(

**Comment by LemonBoy** [comment]
> Still deadlocking when building C code :(

Have you changed the code in `Compilation.zig` to use `ChildProcess.exec` ?

**Comment by xackus** [comment]
I think a `collectOutput` function should be publicly exposed. It would be useful when using `spawn` directly, rather than through `exec`.

**Comment by LemonBoy** [comment]
> I think a collectOutput function should be publicly exposed. It would be useful when using spawn directly, rather than through exec.

The idea I've outlined in #6343 is that `exec` is the DWIM function that runs the subprocess and returns the stderr/stdout, meant to be used when you just want the output data and don't care about how it's retrieved. Using `spawn` means you plan on ignoring the output/processing the output asynchronously (using threads or async i/o or whatever) or, as an additional working mode, to merge stdin and stdout in a single combined stream. The difference between the two modes is that the latter gives you a stream (or two) to work with, while the former gives you a buffer instead.

**Comment by xackus** [comment]
I guess a more flexible solution would be to make a function that takes a list of files and a list of writers and does the same thing as `collectOutput`.

```zig
pub fn collectOutput(files: []File, writers: []Writer, maxBytes: usize) !void
```

**Comment by andrewrk** [comment]
I did a partial merge of this in e54fd2578195ce7857d921ac22b800d376fb870b.

**Comment by andrewrk** [comment]
Closing this month-old draft. I made a comment over on the issue to point to the PR so that we know there is un-merged code to pick up from.

**Pull request closed without merging**
