### PR TITLE
linux syscall numbers as extensible enums

### PR DESCRIPTION
**Pull request by daurnimator**

### CODE REVIEW

**Comment by daurnimator** [comment]
Oops, `if (@hasDecl(SYS, "mmap2")) {` doesn't work to check if an enum has a particular value. Trying to use `stringToEnum` rightfully errors due to the huge potential number of backwards branches.

Is there an efficient way to check if an enum contains a given member?

**Comment by travisstaloch** [comment]
`@hasField` works for enums: https://ziglang.org/documentation/master/#hasField

**Comment by daurnimator** [comment]
CI failure unrelated:
```
failed with: pkg: wrong architecture: FreeBSD:12.0:amd64 instead of FreeBSD:12:amd64
```

**Comment by daurnimator** [comment]
@andrewrk do you want me to rebase?

**Comment by andrewrk** [comment]
Yeah rebase plz

**Comment by andrewrk** [comment]
Tests failed; needs rebasing; 25 days old. Resubmit if you still have interest in this please.

**Comment by daurnimator** [comment]
> Tests failed; needs rebasing; 25 days old. Resubmit if you still have interest in this please.

They only failed because of the freebsd issue we were having at the time.
I'll rebase after #4856 is merged.

**Pull request closed without merging**
