### PR TITLE
std/build: change default install prefix to zig-out 

### LINKED ISSUE #7296: change the default installation directory from ./zig-cache to ./
[Accepted Proposal](https://github.com/ziglang/zig/issues/7296#issuecomment-756432370)

----

If you run `zig init-exe` and then `zig build --help` you see this:

```
Steps:
  install (default)           Copy build artifacts to prefix path
  uninstall                   Remove build artifacts from prefix path
  run                         Run the app

General Options:
  -h, --help                  Print this help and exit
  --verbose                   Print commands before executing them
  --prefix [path]             Override default install prefix
  --search-prefix [path]      Add a path to look for binaries, libraries, headers
  --color [auto|off|on]       Enable or disable colored error messages

Project-Specific Options:
  -Dtarget=[string]           The CPU architecture, OS, and ABI to build for
  -Drelease-safe=[bool]       Optimizations on and safety on
  -Drelease-fast=[bool]       Optimizations on and safety off
  -Drelease-small=[bool]      Size optimizations on and safety off

Advanced Options:
...
```

As you can see, the default step is `install`. If you pass explicit steps on the command line, those steps are executed instead of the default. Currently, the install step has a default prefix path of `zig-cache`:

https://github.com/ziglang/zig/blob/fd18252a7165f04c07289c422eb0b808cc245b05/lib/std/build.zig#L194-L210

This proposal is to make the default installation directory named after the output mode:

https://github.com/ziglang/zig/blob/fd18252a7165f04c07289c422eb0b808cc245b05/lib/std/builtin.zig#L144-L149

So, if you were to run `zig build` with the defaults for init-exe, you would get:

```
Debug/bin/foo.exe
```

With `zig build -Drelease-safe` you would get:

```
ReleaseSafe/bin/foo.exe
```

However, I further propose that this changes when one takes advantage of `setPreferredReleaseMode`, in which case

```
Project-Specific Options:
  -Dtarget=[string]           The CPU architecture, OS, and ABI to build for
  -Drelease-safe=[bool]       Optimizations on and safety on
  -Drelease-fast=[bool]       Optimizations on and safety off
  -Drelease-small=[bool]      Size optimizations on and safety off
```

turns into

```
Project-Specific Options:
  -Dtarget=[string]           The CPU architecture, OS, and ABI to build for
  -Drelease=[bool]            Create a release build (ReleaseSafe)
```

where "ReleaseSafe" is whatever the preferred release mode is. In this case, `zig build -Drelease` would give you a default installation directory of "Release":

```
Release/bin/foo.exe
```

As a reminder, it is always possible to override the install prefix with the `--prefix` CLI parameter.

-----

Comments / suggestions / counter proposals welcome! Nobody will be accused of doing the B-word in this thread!

### PR DESCRIPTION
**Pull request by ifreund**
Closes #7296

### CODE REVIEW

**Comment by ifreund** [comment]
This turns out to be awkward for the zig repository itself as a plain `zig build` in the root of the repo now creates `./bin/zig` (totally OK) and `./lib/zig/**` (a little awkward, as the other children of `./lib` are tracked in by git).

We can certainly add these paths to the `.gitignore` before merge, but I'd rather have a more clear division between which files in `./lib` are version control and which are the result of a build.

**Comment by andrewrk** [comment]
Hmm yeah let's reconsider this in light of this new observation. I think we didn't take it into account when making the decision, and it could very well be an issue with any project in general.

**Comment by ifreund** [comment]
> Hmm yeah let's reconsider this in light of this new observation. I think we didn't take it into account when making the decision, and it could very well be an issue with any project in general.

One solution to this (which is starting to grow on me) is to *require* `-p`/`--prefix` in all cases. This makes it abundantly clear to the user where the artifacts will be placed, simplifies the behavior of the zig build system, and dodges this awkwardness.

For the zig repository, we already have `build/` and `build-*` ignored so user could simply use those directories as their prefix.

**Comment by marler8997** [comment]
Much like tar files, I think if install creates more than one entry it can be "annoying".  I would be fine if the default was just to put everything in a single subdirectory, named "install" or something.

**Comment by g-w1** [comment]
I was imagining that it would be like CMAKE where you have to run it in the `build` directory, or use `-p build`. (s/build/anything_else/) I'm not sure how this is a problem. I find it pretty easy to just remember to use cmake from `build`.

**Comment by jmc-88** [comment]
> I was imagining that it would be like CMAKE where you have to run it in the `build` directory, or use `-p build`. (s/build/anything_else/) I'm not sure how this is a problem. I find it pretty easy to just remember to use cmake from `build`.

I don't think the suggestion was to generate a (potentially out-of-tree) build directory and do things from there, but rather to invoke `zig build` from the directory containing `build.zig`, and pass an explicit `-p`/`--prefix` pointing to the location where build artifacts should be installed.

What you're suggesting can instead already be done with something like:

```
$ mkdir build
$ cd build
$ zig build --build-file ../build.zig
```

**Comment by g-w1** [comment]
You don't need build file, it searches upwards. Either of these two options is satisfactory for me: 
```
zig build -p build # makes build directory
```
```
mkdir build; cd build; zig build
```

**Comment by Jarred-Sumner** [comment]
> I was imagining that it would be like CMAKE where you have to run it in the build directory, or use -p build. (s/build/anything_else/) I'm not sure how this is a problem. I find it pretty easy to just remember to use cmake from build.

imo, depends on the target audience. Zig developers? It's fine to learn that. 

But a random developer installing a CLI utility they saw on Hacker News? If it doesn't install successfully on the first try, they might not bother. Every barrier means a lower conversion rate. Can't expect developers to always write build instructions and can't expect users to read them.

**Comment by ifreund** [comment]
Implemented the changes to the proposal decided upon in the stage2 meeting just now.

**Review by lastthyme — APPROVED** [review]

**Review by andrewrk — APPROVED** [review]

**Comment by ifreund** [comment]
I decided to not yet implement a way to override the default in the interest of avoiding future breaking changes as the build system matures and new features become available. In particular, #7959 could significantly change the way paths are treated and allow for the defaults to be overridden in a more flexible way.  Futhermore, we don't yet have a concrete motivating use-case for a way to override the default install prefix in the first place.

**Comment by daurnimator** [comment]
Shouldn't this have been implemented more like a default `DEST_DIR`?

**Comment by ifreund** [comment]
@daurnimator What exactly do you think should be different?

**Pull request merged**
