### PR TITLE
compiler: implement destructuring syntax

### PR DESCRIPTION
**Pull request by mlugg**
There are a few unrelated minor changes in the first couple of commits.

In general, see commit messages for details.

### CODE REVIEW

**Comment by mlugg** [comment]
A grammar note I forgot to mention in the commit message:

Trailing commas are not allowed for this syntax form - in a sense, the `=` fulfils the role of a trailing comma. Moreover, the canonical form (emitted by `zig fmt`) is for every LHS to be on the same line. In theory, we could allow splitting the LHS across lines like this:
```zig
const x,
var y,
foo.bar =
    something;
```
After some discussion with @andrewrk, I opted not to do this for now, since this form is somewhat difficult to read and not really necessary in most cases. We can revisit this decision down the line if it proves to be a problem.

**Comment by Jarred-Sumner** [comment]
nice!! 

I think requiring each declaration to have `const` or `var` before defeats the purpose though. 

99% of the time, they'll all either be `const` or `var` - not a mix.  And when you do want to mix them up, you can put it on another line. What if the `const` or `var` was implicit after the first usage?

Current:
```zig
const x, const y = .{1,2};
```

Proposed:
```zig
const x, const y = .{1,2};
const x, y = .{1,2};
```

IMO, it would be reasonable to ban the following:
```zig
const x, y, var z = .{1,2,3};
var x, const y, z = .{1,2,3};
const x, var y, z = .{1,2,3};
```

**Comment by mlugg** [comment]
> I think requiring each declaration to have `const` or `var` before defeats the purpose though to some extent

Regardless of the rest of your comment, "defeats the purpose" seems to me a very strong way to put this. Compared to the alternatives, destructuring is syntactically clearer in both the declaration and the result, and easier on the optimizer; having the declaration be a few characters longer doesn't somehow negate this.

> 99% of the time, they'll all either be `const` or `var` - not a mix.

I probably agree with this in general, but don't see it as a reason to change the syntax.

> And when you do want to mix them up, you can put it on another line.

The common pattern I anticipate for this syntax, and the way I've started using it in the compiler, is in code like this:

```zig
const x: Foo, const y: Bar = blk: {
    // big block of logic with many breaks
};
```

Suppose here that we actually wanted to mutate `y` later in the function, but weren't allowed to mix `const` and `var`. You can't just magically split this across multiple lines - the best you could do is `var y: Bar = undefined` first and write to it everywhere you break with a result (using the `break :blk` just for `x`). That change is a big diff, removes symmetry between the two variables being assigned for no good reason, and is more bug-prone (by not giving `y` a value): fairly unambiguously worse in my eyes.

> What if the `const` or `var` was implicit after the first usage?

I believe that the current syntax reads more naturally, even if it is a few more characters. Just in terms of how I naturally read Zig code, a comma is a fairly "major" separator, so IMO it makes sense to re-specify the `const`/`var`.

**Review by andrewrk — APPROVED** [review]
Great work! I'm in the process of merging this now.

**Comment by mlugg** [comment]
@andrewrk
> Great work! I'm in the process of merging this now.

(I pinged you on Discord, but mentioning here too to make sure you see)

I just realised I forgot to import `behavior/destructure.zig` from `behavior.zig` - I don't know if you want to re-run CI with that change, since the tests might fail on some backends (I haven't checked)

**Comment by andrewrk** [comment]
Thanks for the heads up, I'll force push and let the CI run again.

**Comment by tecanec** [comment]
I'm not sure if this is the right place to write this, but whatever. In my excitement to see this new feature for myself, I came to find a compile error in `const a, const b = .{1, 2};`. It says that, for some reason, `comptime_int` values are dependant on runtime control flow.

I know this is not the intended use-case, but I find it odd, nontheless. I thought I should mention it in case you weren't aware of it yourselves.

I'm excited to use this feature, though!

**Comment by BratishkaErik** [comment]
> I'm not sure if this is the right place to write this, but whatever. In my excitement to see this new feature for myself, I came to find a compile error in `const a, const b = .{1, 2};`. It says that, for some reason, `comptime_int` values are dependant on runtime control flow.
> 
> I know this is not the intended use-case, but I find it odd, nontheless. I thought I should mention it in case you weren't aware of it yourselves.
> 
> I'm excited to use this feature, though!

Check tests added by https://github.com/ziglang/zig/pull/17171

**Pull request merged**
