### PR TITLE
Add meson config headers to ConfigHeaderStep

### PR DESCRIPTION
**Pull request by RossComputerGuy**
This PR adds support for the meson-style config headers. It is similar to CMake's so I based it around how we do the CMake style header files.

### CODE REVIEW

**Comment by Radvendii** [comment]
Maybe I'm holding it wrong, but does the `cmake` option actually support `@@FOO@@` syntax, and does this support `@FOO@` syntax? I couldn't get it to work and also can't see in the code why it would. It immediately ignores any file that doesn't start with `#`

**Comment by RossComputerGuy** [comment]
I know meson accepts `@FOO@` but not sure about `@@FOO@@` for CMake. I copied the CMake code that already exists and I didn't see anything to actually handle `@@FOO@@`.

**Comment by eli-schwartz** [comment]
I am pretty sure cmake only supports `@FOO@`, no double at-symbols. In fact, there's an open ticket proposing to implement `@@FOO@@` as an escape mechanism that produces the output `@FOO@`.

> I copied the CMake code that already exists

Note that meson and cmake style are very different:
- `#cmakedefine`: has various complicated ways to handle it based on what type of cmakedefine you use and whether the variable evaluates as boolean truthiness in the cmake language. It also uses two passes, values are processed via at-symbol
- `#mesondefine`: mandates that your variable is strongly typed, and dumps its value into the config header

So you get issues like e.g. in cmake, you set a variable `MYVAL` equal to `myval` and then format it into the config header as `#cmakedefine MYVAL "@MYVAL@"` and the cmakedefine part merely governs whether it shall be defined or `undef`'ed. If you use `#cmakedefine MYVAL` you produce `#define MYVAL`, no actual value. While in meson, you must set `MYVAL` to `"myval"`, and then `#mesondefine MYVAL` dumps the value of MYVAL to `#define MYVAL "myval"`.

You cannot copy the code across for both cmake and meson, if you do then one or the other is broken. For example, Meson is broken since it only halfheartedly supports cmakedefine as a mesondefine-alike (someone who actually enjoys working with cmake is *welcome* to fix that, it's low-priority :P).

Many cmake configure_file inputs are written somewhat sensibly, and always use `#cmakedefine FOO "@FOO@"`, in which case hasty assumptions hold true and that file is compatible with both meson and cmake, and possibly with zig too.

**Comment by RossComputerGuy** [comment]
From the comments already it place, I thought CMake used `@@FOO@@`. I wasn't aware the way you mentioned is how Meson handles its defines since from my experience, it seems pretty similar to CMake.

**Comment by eli-schwartz** [comment]
Meson docs: https://mesonbuild.com/Configuration.html
CMake docs: https://cmake.org/cmake/help/latest/command/configure_file.html

Indeed, the at-symbol replacements are pretty comparable. It's the `#<buildsystem>define ...` forms that are very specific, and clash. cmake ***requires*** values to be spelled out after the token name, meson ***forbids*** them. They are sort of polar opposites.

autoconf is pretty similar to meson here. The signifier for a define is `#undef MYVAL` rather than `#mesondefine MYVAL`, but otherwise it acts the same; the proper value is expected to come from the configuration (`AC_DEFINE` in configure.ac, `confdata.set*()` in meson.build). The cmake behavior is unusual IMO, though of course I am biased.

**Review by andrewrk — CHANGES_REQUESTED** [review]
Thanks for working on this. Can you please add some unit tests in this file for your new logic?

**Comment by andrewrk** [comment]
Closing abandoned pull request

**Pull request closed without merging**
