### PR TITLE
stage2: add error for comptime control flow in runtime block

### PR DESCRIPTION
**Pull request by Vexu**
AstGen contains a bunch of hacks that I haven't fixed yet since I don't expect this solution to pass on the first try.

### CODE REVIEW

**Comment by andrewrk** [comment]
Are you not able to test locally?

**Comment by Vexu** [comment]
I can, I just don't like all the mess created by adding source nodes to all breaks especially since the only place it seems to be needed is in continues inside inline loops.

**Comment by Vexu** [comment]
I did the now obvious thing of copying stage1 and adding a new instruction for this.

**Comment by topolarity** [comment]
FWIW, I think many of these examples can be supported if the code following the runtime control flow is treated as a runtime block.

I don't have a use case in mind - just wanted to mention there's probably room to relax this if we feel the need to later

**Pull request merged**
