### PR TITLE
std: Make parseInt/parseUnsigned detect the radix

### PR DESCRIPTION
**Pull request by LemonBoy**

### CODE REVIEW

**Comment by data-man** [comment]
Proposal: detect a number as hex if last byte == `h`.

**Comment by LemonBoy** [comment]
> Proposal: detect a number as hex if last byte == h.

This notation is not supported anywhere else in Zig so I'd stick to the `0x` way

**Comment by travv0** [comment]
Proposal: since this is the behavior people want 99.9% of the time, make this function not take a radix parameter and use the detection, and make a separate function that lets you specify the radix.  that avoids having to put the magic number 0 in every time you use it

**Comment by Rocknest** [comment]
I dont like that radix=0 means special behaviour, null makes more sense.

**Comment by LemonBoy** [comment]
> I dont like that radix=0 means special behaviour, null makes more sense.

I'll defer the api-breaking decisions to the big boss.

> Proposal: since this is the behavior people want 99.9% of the time, make this function not take a radix parameter and use the detection, and make a separate function that lets you specify the radix. that avoids having to put the magic number 0 in every time you use it

That's an interesting idea, but it adds one more function to do the same thing. Passing the extra null/0 is not that much extra work, no?

**Comment by travv0** [comment]
> Passing the extra null/0 is not that much extra work, no?

It's not, but I do forget to pass the radix a lot of the time so it was a bit of a selfish request 😛

**Comment by MasterQ32** [comment]
> Proposal: since this is the behavior people want 99.9% of the time, make this function not take a radix parameter and use the detection, and make a separate function that lets you specify the radix. that avoids having to put the magic number 0 in every time you use it

I hate APIs that do that for one reason: `0x11` is just not a valid number in same cases, but you'll never find that error if your parsing function switches between hex and decimal. Specifying the radix doesn't hurt imho, and passing `null` for autodetection is a good idea in the code as well

**Comment by andrewrk** [comment]
I support this function that detects a radix. This is the concept of parsing a human readable string into a number. However, there is also an important use case for the simpler function that always requires a radix, and does a direct parsing of digits - "0xff" and "1_000" would both be parse errors.

My counter proposal here is:

 * `parseInt` loses the `radix` parameter. It is 10 unless overridden by a prefix in the input string.
 * `parseUnsigned` is the simpler function that always takes a radix parameter and does nothing except direct parsing of digits.

**Comment by LemonBoy** [comment]
> I support this function that detects a radix. This is the concept of parsing a human readable string into a number. However, there is also an important use case for the simpler function that always requires a radix, and does a direct parsing of digits - "0xff" and "1_000" would both be parse errors.
> 

If a radix is specified the prefix is ignored.

> My counter proposal here is:
> 
>     * `parseInt` loses the `radix` parameter. It is 10 unless overridden by a prefix in the input string. (breaking)
> 
>     * `parseUnsigned` is the simpler function that always takes a radix parameter and does nothing except direct parsing of digits. (I think this matches master branch)

And signed numbers? And why do we have a signed/unsigned split when we already take a type parameter?

**Comment by andrewrk** [comment]
> If a radix is specified the prefix is ignored.

That's clunky, a security footgun, and (admittedly small but) unnecessary code bloat.

> And signed numbers? 

`parseInt` would be sufficient, no?

> And why do we have a signed/unsigned split when we already take a type parameter?

It was an implementation detail, but with this split between `parseInt` (supporting more syntax) and `parseUnsigned` (direct parsing) then there is cause for it to exist as a separate API.

**Comment by travv0** [comment]
With that change there would be no way to parse something like "-ABCD", for example.

**Comment by LemonBoy** [comment]
> It was an implementation detail, but with this split between parseInt (supporting more syntax) and parseUnsigned (direct parsing) then there is cause for it to exist as a separate API.

What does `unsigned` have to do with direct parsing? 

> That's clunky, a security footgun, and (admittedly small but) unnecessary code bloat.

Yeah definitely clunky if compared to having a thousand different APIs to parse a number. How is that a security problem? The prefix is guaranteed to cause a parse error unless you fuck up royally and pick a huge base.

**Comment by andrewrk** [comment]
> What does `unsigned` have to do with direct parsing?

It at least communicates that "-" would not be accepted. But suggestions welcome for a different name.

> How is that a security problem?

Let's say a number that corresponds to a user input is being parsed. The code passes 10 as the radix. So the programmer thinks the range is limited based on base 10, but the user input has the ability to pass `0x` and get access to a larger range. Essentially the radix represents a limit on the set of valid data, so the API should be designed to not accidentally give the user input the ability to ignore that limit.

> thousand different APIs to parse a number

I really don't see this as a problem, as long as they have descriptive names, proper doc comments, and it's easy to explore the available functions. 

I think everyone can get what they want here.

**Comment by LemonBoy** [comment]
> > What does `unsigned` have to do with direct parsing?
> 
> It at least communicates that "-" would not be accepted. But suggestions welcome for a different name.
> 

What does the sign have to do with the prefix?

> > How is that a security problem?
> 
> Let's say a number that corresponds to a user input is being parsed. The code passes 10 as the radix. So the programmer thinks the range is limited based on base 10, but the user input has the ability to pass `0x` and get access to a larger range. Essentially the radix represents a limit on the set of valid data, so the API should be designed to not accidentally give the user input the ability to ignore that limit.
> 

Again, if 10 is explicitly specified as base the `0xwhatever` input causes a parse error by the time the `x` is parsed.

> > thousand different APIs to parse a number
> 
> I really don't see this as a problem, as long as they have descriptive names, proper doc comments, and it's easy to explore the available functions.
> 

One flexible API beats a thousand single-use one, especially here that there's little or nothing to win.

**Comment by andrewrk** [comment]
OK I just realized that I read this backwards:

> If a radix is specified the prefix is ignored.

Sorry, I thought it said "If a prefix is specified, the radix is ignored."

**Pull request merged**
