### PR TITLE
Translate-C Remainder Macro Fix

### LINKED ISSUE #13346: stage2, translate-c: mod math with signed ints results in compile error
### Zig Version

0.10.0-dev.4634+c36eb4ede

### Steps to Reproduce and Observed Behavior

`translate-c` the following and use the resulting function

```c
#define GLAD_VERSION_MINOR(version) (version % 10000)
```

```zig
c.GLAD_VERSION_MINOR(@as(c_int, 20000));
```

```
cimport.zig:1372:60: error: remainder division with 'c_int' and 'c_int': signed integers and floats must use @rem or @mod
```

Note that if I use a `c_uint` it works fine, as expected.

### Expected Behavior

Works!

### PR DESCRIPTION
**Pull request by IridescentRose**
Should fix #13346
Needs testing -- running out of RAM on my machine for this...

### CODE REVIEW

**Comment by topolarity** [comment]
Please test on stage1 if you can (CI does not cover this). See https://github.com/ziglang/zig/pull/13329#issuecomment-1296324526

**Comment by IridescentRose** [comment]
I did see that, I think the issue is that the Macro is getting defined with return type of `@TypeOf(the whole div or mod expression)` when it should be defined with return type of `ArithmeticConversion(@TypeOf(a), @TypeOf(b))`. I'll have to test & figure out fixing it on my desktop when I get home.

**Comment by IridescentRose** [comment]
Discovered something slightly more interesting. By changing the offending code to rely on comptime, we get stage1 to actually work fine.

```zig
pub inline fn DIVIDE_CONSTANT(comptime version: anytype) @TypeOf(@import("std").zig.c_translation.MacroArithmetic.div(version, @as(c_int, 1000))) {
    return @import("std").zig.c_translation.MacroArithmetic.div(version, @as(c_int, 1000));
}
pub inline fn DIVIDE_ARGS(comptime A: anytype, comptime B: anytype) @TypeOf(@import("std").zig.c_translation.MacroArithmetic.div(A, B)) {
    return @import("std").zig.c_translation.MacroArithmetic.div(A, B);
}
pub inline fn MODULUS_CONSTANT(comptime version: anytype) @TypeOf(@import("std").zig.c_translation.MacroArithmetic.mod(version, @as(c_int, 10000))) {
    return @import("std").zig.c_translation.MacroArithmetic.mod(version, @as(c_int, 10000));
}
pub inline fn MODULUS_ARGS(comptime A: anytype, comptime B: anytype) @TypeOf(@import("std").zig.c_translation.MacroArithmetic.mod(A, B)) {
    return @import("std").zig.c_translation.MacroArithmetic.mod(A, B);
}
```

However, that's not what the semantics of a macro should be -- the types of A & B should be compile time known, but the values don't need to be compile time known -- they should be allowed to vary. I'm not really sure how to fix this, as diving into finding the @TypeOf return type code seems buried in the translate C code. 

It's not really a regression for stage1, as stage1 never handled this case correctly before #13329 but at the same time it is a "parity" gap

**Comment by ehaas** [comment]
C's `%` operator is `@rem` and not `@mod`. There's also a stage1 vs stage2 discrepancy with `@rem` - stage1 does not allow negative divisors, while stage2 does. You'll want to use `signedRemainder` (in `c_translation.zig`) if the converted type is signed; otherwise you can use the `%` operator.

**Comment by IridescentRose** [comment]
Thanks, I'll make sure to change that!

**Comment by IridescentRose** [comment]
Swapped over the names to reflect remainder (rem) and also used signedRemainder. Added to the test to also check the signed remainder as working as well.

**Comment by IridescentRose** [comment]
Seems like there's a linker test or something that relies on hardcoded translate-C code and that's what's failing

**Comment by IridescentRose** [comment]
Noticed that https://github.com/ziglang/zig/blob/master/.github/CONTRIBUTING.md#improving-translate-c does not have up to date information -- these tests while they still exist, no longer can be ran with commands like `zig test test/translate_c.zig`

**Pull request merged**
