### PR TITLE
Use 0-indexing for incremental compile error tests

### PR DESCRIPTION
**Pull request by topolarity**
Follow-up to #11417.

I went ahead and reverted the reported `update_index` to also be 0-indexed.

P.S. I took a look to move over any existing incremental tests, but I don't think we have any yet for stage2

### CODE REVIEW

**Comment by andrewrk** [comment]
We do! Here are some, for example:

https://github.com/ziglang/zig/blob/99657dca1fac04e5015203699e3eb0d656d66b09/test/stage2/aarch64.zig#L61-L113

https://github.com/ziglang/zig/blob/99657dca1fac04e5015203699e3eb0d656d66b09/test/stage2/arm.zig#L45-L91

https://github.com/ziglang/zig/blob/99657dca1fac04e5015203699e3eb0d656d66b09/test/stage2/cbe.zig#L12-L57

https://github.com/ziglang/zig/blob/99657dca1fac04e5015203699e3eb0d656d66b09/test/stage2/llvm.zig#L31-L54

https://github.com/ziglang/zig/blob/99657dca1fac04e5015203699e3eb0d656d66b09/test/stage2/plan9.zig#L21-L54

https://github.com/ziglang/zig/blob/99657dca1fac04e5015203699e3eb0d656d66b09/test/stage2/wasm.zig#L10-L62

https://github.com/ziglang/zig/blob/99657dca1fac04e5015203699e3eb0d656d66b09/test/stage2/x86_64.zig#L24-L65

**Comment by topolarity** [comment]
Oh sweet, I missed those. Let me see about moving them over later today.

**Comment by topolarity** [comment]
Hmm, I think we'll have to implement more of the enhanced test suite proposal before these are ready to be moved over. They all either involve "run" tests or include specific targets/backends, neither of which are supported in manifests yet.

Feel free to ping me if I missed any other tests, though

**Comment by andrewrk** [comment]
These were some of the earliest test cases we had for stage2. It should be possible to run most of them for all backends at this point.

**Pull request merged**
