### PR TITLE
Fix os_path_join for case where dirname is empty

### PR DESCRIPTION
**Pull request by isaachier**

### CODE REVIEW

**Comment by isaachier** [comment]
Saw an issue here when I ran the fuzz test. When `dirname` is empty, `c` sets itself to `buf_ptr(dirname) + 0 - 1`, which accesses out-of-bounds memory.

**Comment by isaachier** [comment]
Probably easier to just write the regression test by hand. Fuzz test will easily reproduce the error, but better to catch this in regular testing cycle.

**Comment by andrewrk** [comment]
thanks!

**Comment by isaachier** [comment]
Anytime

**Pull request merged**
