### PR TITLE
Move __zig_fail_unwrap locals on stack

### PR DESCRIPTION
**Pull request by LemonBoy**
Less global state,
Cleaner code,
More comments

### CODE REVIEW

**Comment by andrewrk** [comment]
This is an improvement over status quo, so I'm going to merge it. However it does conflict a bit with the goal of being able to compute stack size at compile-time (#157). I'll open a new issue to track this.

**Comment by andrewrk** [comment]
I just added a comment instead of making a new issue: https://github.com/ziglang/zig/issues/157#issuecomment-496605187

**Comment by LemonBoy** [comment]
> However it does conflict a bit with the goal of being able to compute stack size at compile-time

If you end up in `__zig_fail_unwrap` it means you're going to die after `panic()` prints the error, I think this allocation doesn't really belong to the function "budget".

**Comment by andrewrk** [comment]
I see your point, but panicking is defined to call the panic function, which may be user-defined. So I think the budget would include the possibility that any safety checks could call the panic handler. If the budget is missing this allocation for the panic message that seems like a problem to me.

**Pull request merged**
