### PR TITLE
Pass `ArrayBitSet` by `*const` instead of by value

### PR DESCRIPTION
**Pull request by Jarred-Sumner**
`ArrayBitSet.isSet` was doing a memcpy of the entire `masks` array when you call a function like `isSet`. This is mostly noticeable in debug builds.

For larger bitsets, that is very expensive in debug builds

image
image

For a release build of bun, it's a very slight performance improvement (note how the max is lower)

```zig

❯ hyperfine "bun-before bun index.js" "bun bun index.js" --warmup=2
Benchmark 1: bun-before bun index.js
  Time (mean ± σ):      1.701 s ±  0.008 s    [User: 3.227 s, System: 0.135 s]
  Range (min … max):    1.686 s …  1.713 s    10 runs

Benchmark 2: bun bun index.js
  Time (mean ± σ):      1.680 s ±  0.005 s    [User: 3.188 s, System: 0.136 s]
  Range (min … max):    1.673 s …  1.689 s    10 runs

Summary
  'bun bun index.js' ran
    1.01 ± 0.01 times faster than 'bun-before bun index.js'
```

### CODE REVIEW

**Comment by andrewrk** [comment]
Thanks. Please give me some time to investigate fixing this in the compiler rather than in the standard library. Since the compiler is allowed to pass this data by reference, it should have made this choice here.

**Comment by Jarred-Sumner** [comment]
Sounds good. It would be better if the compiler just did this

**Comment by r00ster91** [comment]
Here's a similar case btw: #13518 maybe this change can also be reverted and instead be fixed in the compiler.

**Comment by andrewrk** [comment]
I created a reduction of this issue: #17580

I made it a high priority issue but denying any more requests to do the workaround in the standard library.

**Pull request closed without merging**
