### PR TITLE
Enhance std.ascii.indexOfIgnoreCase with Boyer-Moore-Horspool algorithm

### PR DESCRIPTION
**Pull request by tensorush**
* Port Boyer-Moore-Horspool algorithm and relevant tests from std.mem.indexOfPos
* Remove TODO doc comment
* Fix/provide doc comments

### CODE REVIEW

**Comment by r00ster91** [comment]
I think what could accelerate the reviewing process is if you could provide some benchmarks maybe comparing old vs new? You might want to try `hyperfine` for that.

**Comment by tensorush** [comment]
Thank you for the suggestion! I benchmarked `indexOfIgnoreCasePos` and `indexOfIgnoreCasePosLinear` on the langref with `hyperfine 'zig test my_test_indexOfIgnoreCasePos.zig' 'zig test my_test_indexOfIgnoreCasePosLinear.zig'`:

`Benchmark 1: zig test my_test_indexOfIgnoreCasePos.zig
  Time (mean ± σ):     284.3 ms ±  30.5 ms    [User: 114.8 ms, System: 356.1 ms]
  Range (min … max):   250.1 ms … 337.6 ms    11 runs

Benchmark 2: zig test my_test_indexOfIgnoreCasePosLinear.zig
  Time (mean ± σ):     358.6 ms ±  41.9 ms    [User: 156.2 ms, System: 414.1 ms]
  Range (min … max):   307.7 ms … 439.3 ms    10 runs

Summary
  'zig test my_test_indexOfIgnoreCasePos.zig' ran
    1.26 ± 0.20 times faster than 'zig test my_test_indexOfIgnoreCasePosLinear.zig'`

Contents of `indexOfIgnoreCasePosLinear`:

`const std = @import("std");

const langref = @embedFile("doc/langref.html.in");

test "indexOfIgnoreCasePos" {
    try std.testing.expect(std.ascii.indexOfIgnoreCasePosLinear(langref, 0, "All Your Base Are Belong To Us").? == 403_529);
    try std.testing.expect(std.ascii.indexOfIgnoreCasePosLinear(langref, 0, "All Your Codebase Are Belong To Us!") == null);
}`

Contents of `indexOfIgnoreCasePos`:

`const std = @import("std");

const langref = @embedFile("doc/langref.html.in");

test "indexOfIgnoreCasePos" {
    try std.testing.expect(std.ascii.indexOfIgnoreCasePos(langref, 0, "All Your Base Are Belong To Us").? == 403_529);
    try std.testing.expect(std.ascii.indexOfIgnoreCasePos(langref, 0, "All Your Codebase Are Belong To Us!") == null);
}`

**Comment by r00ster91** [comment]
For me it recompiles the test every run so I don't think these results would be very accurate. Also, to measure real-world performance I think we would have to compile with the release fast build mode.
I've had some attempts of my own and I don't think I'm very successful at this:
`a.zig`
```zig
const std = @import("std");
const ascii = @import("new_ascii.zig");
pub fn main() void {
    const langref = @embedFile("doc/langref.html.in");
    std.mem.doNotOptimizeAway(langref);
    std.mem.doNotOptimizeAway(ascii.indexOfIgnoreCasePos(langref, 0, "</html>").? == 455235);
    std.mem.doNotOptimizeAway(ascii.indexOfIgnoreCasePos(langref, 0, "dowodk") == null);
}
```
`b.zig`
```zig
const std = @import("std");
const ascii = @import("new_ascii.zig");
pub fn main() void {
    const langref = @embedFile("doc/langref.html.in");
    std.mem.doNotOptimizeAway(langref);
    std.mem.doNotOptimizeAway(ascii.indexOfIgnoreCasePosLinear(langref, 0, "</html>").? == 455235);
    std.mem.doNotOptimizeAway(ascii.indexOfIgnoreCasePosLinear(langref, 0, "dowodk") == null);
}
```
```
$ zig build-exe a.zig -O ReleaseFast
$ zig build-exe b.zig -O ReleaseFast
$ hyperfine --warmup 1000 ./a ./b
Benchmark 1: ./a
  Time (mean ± σ):      19.1 ms ±   6.3 ms    [User: 18.5 ms, System: 0.6 ms]
  Range (min … max):    15.0 ms …  41.9 ms    172 runs

Benchmark 2: ./b
  Time (mean ± σ):       1.0 ms ±   0.1 ms    [User: 0.9 ms, System: 0.2 ms]
  Range (min … max):     0.8 ms …   2.2 ms    1142 runs

Summary
  './b' ran
   19.17 ± 6.85 times faster than './a'
```
It always tells me b.zig (the linear version) is faster. Not sure what's up with that. Maybe we need more data or more tests?

**Comment by tensorush** [comment]
Oh, when testing I also commented out these lines in `indexOfIgnoreCasePos`:

```zig
pub fn indexOfIgnoreCasePos(haystack: []const u8, start_index: usize, needle: []const u8) ?usize {
    // if (needle.len > haystack.len) return null;
    // if (needle.len == 0) return start_index;

    // if (haystack.len < 52 or needle.len <= 4)
        // return indexOfIgnoreCasePosLinear(haystack, start_index, needle);
```

**Comment by andrewrk** [comment]
Thanks!

**Pull request merged**
