### PR TITLE
Add documentation for functions in Zig std

### PR DESCRIPTION
**Pull request by cat1000101**
This pull request adds documentation to functions within the Zig build system,

it is my first pull request hope it helped

### CODE REVIEW

**Comment by BratishkaErik** [comment]
Good start but I think they should be more verbose, these one-line comments are not much better than just reading signature of the function.

**Comment by cat1000101** [comment]
> Good start but I think they should be more verbose, these one-line comments are not much better than just reading signature of the function.

should i work on this more like expand on the input and output?
or explain what happens on the inside?
ty

**Comment by BratishkaErik** [comment]
> should i work on this more like expand on the input and output?
> or explain what happens on the inside?
> ty
Leaved some comments here, but I'm just another Zig user, there is no official style guide for docs writing yet unfortunately. Thank you too for this work.

> and should i close this and then make a new pull request?
It's not neccessary, you can add new commits on top of this and push them, you can squash/collapse them into single commit later.

**Comment by wooster0** [comment]
* No consistency: some comments start capitalized, most don't. One comment has a period, all others don't. Suggestion: use capitalization and periods everywhere.
* Redundancy: there does not need to be a documentation comment for every single thing if you might as well just read the name of the thing to figure out the same information. As it stands right now I would probably just close the PR except for maybe the `findProgram` functions which could use some elaborate documentation maybe.

**Comment by nektro** [comment]
i would recommend writing a blog post about a use case you solved and sharing it in a [Community](https://github.com/ziglang/zig/wiki/Community) since these comments as is dont provide much value over reading the source, which is highly encouraged when writing Zig, and a blog post would better tell the story of how and why you used the functions you did

**Comment by mlugg** [comment]
Closing. @wooster0 summarised this well -- these comments are inconsistent and unhelpful. I would also note that the final (furthest down the file) doc comment added here is entirely unfit for purpose: describing how a function happens to be *implemented* is not the goal of a doc comment.

**Pull request closed without merging**
