### PR TITLE
Allow for omitting patch digit in std.SemanticVersion.parse()

### PR DESCRIPTION
**Pull request by yamashitax**
The idea here is that there are some situations where the version number that is provided has the patch digit omitted.

`std.SemanticVersion.parse()` will now take a second argument, where the option `omit_patch` can be set to either `true` or `false`. The default value is set to `false` as to not disrupt existing functionality.

### CODE REVIEW

**Comment by Cloudef** [comment]
Omitting patch isn't a valid semantic version https://semver.org/

**Comment by BratishkaErik** [comment]
> > Omitting patch isn't a valid semantic version https://semver.org/
> 
> Hiya! I am aware of that. This was just something that has been a bit of a paper cut in a project I've been working on. So I opted for suggesting it as a change in the standard library. 🙂

You might want to take a look at `Target.Query.parseVersion`:

https://github.com/ziglang/zig/blob/3069669bc13450988d58d650c82289ba796ab966/lib/std/Target/Query.zig#L368-L371

**Comment by yamashitax** [comment]
> > > Omitting patch isn't a valid semantic version https://semver.org/
> > 
> > 
> > Hiya! I am aware of that. This was just something that has been a bit of a paper cut in a project I've been working on. So I opted for suggesting it as a change in the standard library. 🙂
> 
> You might want to take a look at `Target.Query.parseVersion`:
> 
> https://github.com/ziglang/zig/blob/3069669bc13450988d58d650c82289ba796ab966/lib/std/Target/Query.zig#L368-L371

@BratishkaErik That's great! Thanks for the tip.

**Comment by yamashitax** [comment]
> but I wouldn't rely on it and instead 

Why would you recommend I do not rely on it?

**Comment by Cloudef** [comment]
It's very specific API meant for parsing Build Targets, it might be moved, removed, or have unexpected behavior in future.

**Comment by yamashitax** [comment]
> It's very specific API meant for parsing Build Targets

Ah okay, gotcha.

> it might be moved, removed, or have unexpected behavior in future.

This is probably true for most things in the standard library, so I usually proceed with caution anyhow. 
Thanks for the tip!

**Pull request closed without merging**
