### PR TITLE
stage2 ARM: implement basic binary bitwise operations

### PR DESCRIPTION
**Pull request by joachimschmidt557**
A small intermezzo while I'm working on conditional branching in the stage2 ARM backend.

TODO in this PR:

- [ ] ~~implement comptime calculation~~ needs more work in `std.math.big.int` afaik
- [x] add test

### CODE REVIEW

**Comment by joachimschmidt557** [comment]
As far as I have understood the semantics of comptime bitwise operations, the comptime calculation bit might be non-trivial here. `comptime_int` relies on BigInt functionality. In the stage1 compiler, bitwise operations transform the BigInts into twos-complement and transform them back into BigInts. On the other hand, the BigInt implementation of the standard library does not operate on twos-complement. Should the implementation of the standard library be changed or the twos-complement functionality be added as another option?

**Comment by Rocknest** [comment]
Do you mean something like this `-5 | 6 == -1`? I think it should not work, only unambiguous operation should be allowed.

**Comment by joachimschmidt557** [comment]
@Rocknest The current behaviour of the stage1 compiler is `-5 | 6 == 1`. Are there any issues/proposals to change this behaviour? I think a discussion on whether to keep, change or disallow this behaviour is out of scope of this PR. Unless a proposal was accepted/will be accepted that the current behaviour should change, we'll have to replicate the behaviour of stage1 in stage2.

**Comment by Rocknest** [comment]
It feels wrong to automatically select some type for these kind of operations, just like negation of comptime_int. Its an opportunity to reconsider what is allowed. Unfortunately i dont have time to research this further.

**Pull request merged**
