### PR TITLE
Pick up WinMain with proper CC

### LINKED ISSUE #3712: root source file has no member called 'main' when WinMain is defined.
On Zig 0.5.0+a11da3773.

zig build-exe ../src/test.zig --subsystem windows 
C:\dev\Zig\lib\zig\std\special\start.zig:227:35: error: root source file has no member called 'main'

```zig
usingnamespace @import("std").os.windows;

extern "user32" stdcallcc fn MessageBoxA(hWnd: ?HANDLE, lpText: ?LPCTSTR, lpCaption: ?LPCTSTR, uType: UINT) c_int;

export stdcallcc fn WinMain(hInstance: ?HINSTANCE, hPrevInstance: ?HINSTANCE, lpCmdLine: ?LPWSTR, nShowCmd: INT) INT {
    _ = MessageBoxA(null, c"hello", c"world", 0);

    return 0;
}
```

Interestingly, the error is only prompted if stdcallcc is not provided, but it's required otherwise the parameters are not accessible to the function as the calling convention is not observed.

If main() is defined then WinMain() is never called.

### PR DESCRIPTION
**Pull request by LemonBoy**
Closes #3712

### CODE REVIEW

**Comment by daurnimator** [comment]
Could we add a regression test?

**Comment by LemonBoy** [comment]
> Could we add a regression test?

That's an exercise left to the reader :) You need some os-detection tricks to have a portable test case.

**Comment by JesseRMeyer** [comment]
> This is all assuming that `WinMain` & friends are supposed to be stdcallcc and not ccc, which appears to be the case.

MSDN is inconsistent on this, but WINAPI is typedef'd to __stdcall on VS2019's version of Windows.h, which qualifies WinMain (and friends).

https://docs.microsoft.com/en-us/cpp/cpp/stdcall?redirectedfrom=MSDN&view=vs-2019

'The __stdcall calling convention is used to call Win32 API functions. The callee cleans the stack, so the compiler makes vararg functions __cdecl. Functions that use this calling convention require a function prototype.'

**Comment by andrewrk** [comment]
Thanks for the follow-up

**Pull request merged**
