### PR TITLE
port cachegrind.h to zig

### PR DESCRIPTION
**Pull request by ProkopRandacek**
port [cachegrind.h](https://sourceware.org/git/?p=valgrind.git;a=blob;f=cachegrind/cachegrind.h;h=ddc10abe597f1346ea9b57f5849e2d0ac7b42523;hb=HEAD) to zig.

### CODE REVIEW

**Comment by nektro** [comment]
can u import this in a relevant file so that it is parsed in tests and doesnt bitrot?

**Review by andrewrk — CHANGES_REQUESTED** [review]
[Avoid Redundant Names in Fully-Qualified Namespaces](https://ziglang.org/documentation/master/#Avoid-Redundant-Names-in-Fully-Qualified-Namespaces)

**Comment by ProkopRandacek** [comment]
> [Avoid Redundant Names in Fully-Qualified Namespaces](https://ziglang.org/documentation/master/#Avoid-Redundant-Names-in-Fully-Qualified-Namespaces)

Perhaps the other two valgrind files would deserve the same treatment?

**Comment by andrewrk** [comment]
Thank you

**Pull request merged**
