### PR TITLE
cc,wasi: support WASI reactors via -mexec-model flag.

### PR DESCRIPTION
**Pull request by mathetake**
Based on this patch to LLVM (https://reviews.llvm.org/D62922). This partially resolves (only for zig cc) #6757

### CODE REVIEW

**Comment by mathetake** [comment]
reopened from https://github.com/ziglang/zig/pull/8978

**Comment by kubkon** [comment]
> reopened from #8978

Thanks @mathetake, and sorry for the trouble!

**Comment by kubkon** [comment]
@mathetake are you on Zig's discord by any chance? Would you be able to provide an example C that acts as a reactor, and one that acts as a command, and then how to invoke either using a runtime such as Wasmtime?

**Comment by kubkon** [comment]
@mathetake merged! It'd be awesome if you joined our Discord server and we could discuss how to use reactor/command and perhaps come up with a plan on how to tackle that in Zig's libstd. Thanks for your great contribution!

**Comment by mathetake** [comment]
@kubkon yeah I joined a few days ago but not login since then.. let me post some examples in a few days, see you there! Thanks!

**Pull request merged**
