### PR TITLE
std.static_string_map: Cast length of input for runtime initialization

### PR DESCRIPTION
**Pull request by burgerindividual**
In the `init` function, there seems to be a missing `@intCast` for the length of the input to a u32, which breaks usage of the function with a slice input. This should be possible, and the change reflects the cast in `initComptime`.

### CODE REVIEW

**Comment by travisstaloch** [comment]
Thanks for catching that. Would you mind adding a small test which would otherwise fail without this patch?

**Comment by nektro** [comment]
why is the len field u32 instead of usize?

**Comment by travisstaloch** [comment]
> why is the len field u32 instead of usize?

This was done as an optimization in #19719

> i noticed a speedup reducing the size of the struct from 48 to 32
bytes and thus use u32s instead of usize for all length fields

**Comment by burgerindividual** [comment]
I updated the test case and verified that it does not compile without the additional `@intCast`, and with the cast it runs successfully.

**Comment by travisstaloch** [comment]
> I updated the test case and verified that it does not compile without the additional `@intCast`, and with the cast it runs successfully.

Thanks!  Looks good.

**Pull request merged**
