### PR TITLE
Update wasi-libc to a00bf321eeeca836ee2a0d2d25aeb8524107b8cc

### PR DESCRIPTION
**Pull request by jedisct1**
It includes a port of emscripten's allocator that performs performs much better than the old one.

Most importantly, it includes the prerequisites to later add support for POSIX threads.

### CODE REVIEW

**Comment by matu3ba** [comment]
I think you need to rebase on top of master or force push to get the CI working.

**Review by kubkon — APPROVED** [review]
Looks great to me! I have only one request that is not directly related to the code changes, but rather to our Wiki. @jedisct1 since you went through the process of upgrading the WASI libc just now, would mind adding a section to https://github.com/ziglang/zig/wiki/Updating-libc for future reference? I apologise I haven't done it yet!

**Comment by jedisct1** [comment]
Sure! Having that upgrade process document would indeed be super useful. I'll do it.

**Comment by jedisct1** [comment]
@kubkon Done :)

**Pull request merged**
