### PR TITLE
CLI: support - to mean stdin

### PR DESCRIPTION
**Pull request by andrewrk**
* `-` is supported as an alias for stdin.
* `-x [extension]` is provided as a way to override the extension of a positional argument, but it only currently works for .zig and .zir files.
    
See #6780. Issue remains open until a regression test is added.

-----

Now that I went ahead and implemented this, I want to make an argument for why I think **the decision to accept #6780 should be reversed, and this branch should be deleted** instead of merged (except for the changes to `std.fs.File` in the first commit).

 * The code is messy, and not because of the way that I've written it, it's just fundamentally clunky to solve this use case, because the cache directory depends on the root source file, but when it is stdin then the root source file depends on the cache directory. It's a lot of logic for an obscure use case.
 * `execve` has to be disabled so that it can delete the .zig temp files that it creates.
 * It doesn't work with `--main-pkg-path` because Package expects the source path to be relative to the package root directory, and so it would require writing temp files to the directory passed with `--main-pkg-path` which is not viable; normally this is a read-only operation.
 * It leaves leftover junk in the cache; every time you execute for example `echo 'pub fn main() !void { try @import("std").io.getStdOut().outStream().print("Hello, world!\n", .{}); }' | ./zig run -x zig -` it will create a directory in the `o` subdir of the global zig-cache. `zig run` is designed for a use case to be executed on the same file multiple times.
 * I tried making the `-x` thing work for more types of files but it turned out to be too janky, especially considering external projects such as clang and lld do not support the overrides that we want to recognize.

The use case outlined in #6780 is code.golf and trying to prevent cheating with quines. While code golf is explicitly not a design goal of the zig language, and trying to provide non-compliant implementations of zig is also not something I want to actively support, I do think there is a solution readily available for this case, which is to wrap the call to zig in a script which creates a temporary file with a random filename that ends in ".zig", use `build-exe` with `-femit-bin=foo`, execute it, and then delete the project-local cache directory. This would actually have better behavior than using stdin with the code in this branch - no unwanted cache growth, perfect stack traces, quine cheating prevented.

cc @JRaspass

### CODE REVIEW

**Comment by daurnimator** [comment]
> `execve` has to be disabled so that it can delete the .zig temp files that it creates.

Why can't the source file be deleted before we `execve`?

> It doesn't work with --main-pkg-path because Package expects the source path to be relative to the package root directory, and so it would require writing temp files to the directory passed with --main-pkg-path which is not viable; normally this is a read-only operation.

Great point.

> The use case outlined in #6780 is code.golf and trying to prevent cheating with quines. While code golf is explicitly not a design goal of the zig language, and trying to provide non-compliant implementations of zig is also not something I want to actively support, I do think there is a solution readily available for this case, which is to wrap the call to zig in a script which creates a temporary file with a random filename that ends in ".zig", use `build-exe` with `-femit-bin=foo`, execute it, and then delete the project-local cache directory. This is all, I think, reasonable to ask the user to do, and does not need to go into the compiler.

I don't think this would work: code golf needs to prevent `@embedFile` being able to specify the source file

--------------

I think there is a different issue and solution here: at the moment zig expects source files to be.... files. This means you can't pass in e.g. pipes as source files: `zig build-exe -o someexe <(echo ''pub fn main() !void { try @import("std").io.getStdOut().outStream().print("Hello, world!\n", .{}); }')` this is a bash-shell thing that I at least use in many languages.
If we solve for *that*, then taking input from stdin because simply mapping `-` to the stdin file descriptor, and would be the same as running `zig run /dev/fd/0`

**Comment by andrewrk** [comment]
> Why can't the source file be deleted before we `execve`?

Because if a stack trace occurs the source file being available makes for a nicer stack trace.

> I don't think this would work: code golf needs to prevent `@embedFile` being able to specify the source file

What's wrong with my solution of 

> temporary file with a random filename that ends in ".zig",

?

> I think there is a different issue and solution here: at the moment zig expects source files to be.... files.

Yes and I think that expectation is warranted. Source files being actual files provides many crucial benefits:

 * a straightforward and effective cache system
 * debug info with source mappings
 * runtime stack traces
 * package system / well-defined `@import`

**Comment by daurnimator** [comment]
> What's wrong with my solution of
> 
> > temporary file with a random filename that ends in ".zig",
> 
> ?

`@embedFile(@src().file)`

**Comment by andrewrk** [comment]
Oh right, I forgot we had that now. Well that is still a problem with the strategy in this PR too. Even more reason to not merge this.

**Pull request closed without merging**
