### PR TITLE
Sema: Add a note on @evalBranchQuota() when branch limit exceeded

### LINKED ISSUE #11996: comptime base64 decode error for long input?
### Zig Version

0.8.1

### Steps to Reproduce

I am compiling down to wasm.  This builds and runs if I only call getPlay(), the other two functions generate the error below.  So I assume it is something to do with the length of the input into the base64 decoder?

const std = @import("std");
const b64 = @import("std").base64.standard;

const PLAY = "PHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDMyIDMyIiB3aWR0aD0iMzIiIGhlaWdodD0iMzIiPjxyZWN0IGZpbGw9IiMwMDAwMDAiIGZpbGwtb3BhY2l0eT0iMC4zIiB3aWR0aD0iMzIiIGhlaWdodD0iMzIiLz48cGF0aCBzdHJva2U9IiNGQUZBRkEiIHN0cm9rZS13aWR0aD0iMyIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIgc3Ryb2tlLW1pdGVybGltaXQ9IjEwIiBmaWxsPSJub25lIiBkPSJNMTIsMTAgMTIsMjIgMjAsMTYgWiIvPjwvc3ZnPg==";
const PAUSE = "PHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDMyIDMyIiB3aWR0aD0iMzIiIGhlaWdodD0iMzIiPjxyZWN0IGZpbGw9IiMwMDAwMDAiIGZpbGwtb3BhY2l0eT0iMC4zIiB3aWR0aD0iMzIiIGhlaWdodD0iMzIiLz48cGF0aCBzdHJva2U9IiNGQUZBRkEiIHN0cm9rZS13aWR0aD0iMyIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiBzdHJva2UtbWl0ZXJsaW1pdD0iMTAiIGZpbGw9Im5vbmUiIGQ9Ik0xMiwxMCAxMiwyMiIvPjxwYXRoIHN0cm9rZT0iI0ZBRkFGQSIgc3Ryb2tlLXdpZHRoPSIzIiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIHN0cm9rZS1taXRlcmxpbWl0PSIxMCIgZmlsbD0ibm9uZSIgZD0iTTIwLDEwIDIwLDIyIi8+PC9zdmc+";
const CLOSE = "PHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDMyIDMyIiB3aWR0aD0iMzIiIGhlaWdodD0iMzIiPjxyZWN0IGZpbGw9IiMwMDAwMDAiIGZpbGwtb3BhY2l0eT0iMC4zIiB3aWR0aD0iMzIiIGhlaWdodD0iMzIiLz48cGF0aCBzdHJva2U9IiNGRkZGRkYiIHN0cm9rZS13aWR0aD0iMyIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbWl0ZXJsaW1pdD0iMTAiIGZpbGw9Im5vbmUiIGQ9Ik0yMCwxMiAxMiwyMCIvPjxwYXRoIHN0cm9rZT0iI0ZGRkZGRiIgc3Ryb2tlLXdpZHRoPSIzIiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1taXRlcmxpbWl0PSIxMCIgZmlsbD0ibm9uZSIgZD0iTTEyLDEyIDIwLDIwIi8+PC9zdmc+";

const PLAY_DECODED = decodeB64(PLAY);
const PAUSE_DECODED = decodeB64(PAUSE);
const CLOSE_DECODED = decodeB64(CLOSE);

fn decodeB64(comptime encoded: []const u8) [*:0]const u8 { //strange that this has to be comptime for the destLen to be comptime...
    const destLen: usize = b64.Decoder.calcSizeForSlice(encoded) catch unreachable;
    //var buffer: [destLen]u8 = undefined; //looks strange that it is usable but undefined?
    var buffer: [destLen]u8 = [_]u8{0} ** destLen; //maybe this is safer anyway...
    const dest: []u8 = buffer[0..destLen];
    b64.Decoder.decode(dest, encoded) catch unreachable;
    return @ptrCast([*:0]const u8, dest); //is it okay to return a slice onto a comptime array var?
}

pub fn getPlay() [*:0]const u8 {
    return PLAY_DECODED;
}
pub fn getPause() [*:0]const u8 {
    return PAUSE_DECODED;
}
pub fn getClose() [*:0]const u8 {
    return CLOSE_DECODED;
}

### Expected Behavior

no compile error.  
Apologies if this has been fixed in later versions.  I am unable to test beyond 0.8.1 since support for older macos was dropped.

### Actual Behavior

~/Downloads/zig081/lib/std/base64.zig:203:9: error: evaluation exceeded 1000 backwards branches
        for (source) |c, src_idx| {
        ^
./abc.zig:17:23: note: called from here
    b64.Decoder.decode(dest, encoded) catch unreachable;
                      ^
./abc.zig:9:32: note: called from here
const PAUSE_DECODED = decodeB64(PAUSE);
                               ^
./abc.zig:9:32: note: called from here
const PAUSE_DECODED = decodeB64(PAUSE);
                               ^
./abc.zig:17:23: note: referenced here
    b64.Decoder.decode(dest, encoded) catch unreachable;
                      ^
./abc.zig:9:32: note: referenced here
const PAUSE_DECODED = decodeB64(PAUSE);
                               ^
./abc.zig:25:12: note: referenced here
    return PAUSE_DECODED;

### PR DESCRIPTION
**Pull request by voroskoi**
closes #11996

### CODE REVIEW

**Comment by voroskoi** [comment]
Thanks for the feedback!

I have changed the stage1 error message too, rebuilt it and then ran `./build/zig build test` to test it (still running).
I have tried to figure out which test group should I run, but I was unable to figure out.

**Comment by ominitay** [comment]
Looks good, though you'll need to make the same change to stage1 (and its respective tests) :)

**Comment by ominitay** [comment]
> I don't think there is a patter regarding this. I also prefer them as separate notes but before I go changing other errors I want to stop stage2 from printing the same source line of code multiple times.

Well, good I think to do it right in the first place :)

> It is okay to leave worse errors in stage1, it is going to be deprecate in a matter of months.

Fair enough, but then it's a minimal effort -- I'm happy to do it, if not @voroskoi.

**Comment by voroskoi** [comment]
Working on stage1 now, trying to fix that one too

**Comment by voroskoi** [comment]
Ok, it should be good now.

The stage1 tests do not expect matching note unlike stage2 so I did not change those.

**Pull request merged**
