### PR TITLE
implement building via cgo for windows/arm64 (aarch64-windows-gnu)

### PR DESCRIPTION
**Pull request by marler8997**
fix issue #9519 by adding some missing stuff from mingw and compiler_rt to support windows aarch64.

### CODE REVIEW

**Comment by marler8997** [comment]
This appears to be now blocked by https://github.com/ziglang/zig/issues/1290

I added `__chkstk` but then got more missing symbols:

```
lld-link: error: undefined symbol: __udivti3
>>> referenced by compiler_rt.lib(compiler_rt.obj):(.weak.__muloti4.default._alloca)

lld-link: error: undefined symbol: __divti3
>>> referenced by compiler_rt.lib(compiler_rt.obj):(.weak.__muloti4.default._alloca)

```

**Comment by marler8997** [comment]
Ok I've adding the missing compiler_rt functions.  I'm able to compile a basic hello world program for `aarch64-windows-gnu`, but I'm not sure what I need to modify in order to add `aarch64-windows-gnu` to the list of cross platforms that are tested.

**Comment by andrewrk** [comment]
Wow very cool!

**Comment by marler8997** [comment]
wow I can't believe the new target is already passing the test suite

**Comment by marler8997** [comment]
With the `aarch64-windows-gnu` target now working, I confirmed this fixes the original issue and I can use `zig cc` to cross compile the original Go project.

**Comment by marler8997** [comment]
Ping

**Pull request merged**
