### PR TITLE
Add ability to test Aro based `translate-c`

### PR DESCRIPTION
**Pull request by Vexu**
This should make the Aro based `translate-c` ready for contributing.

### CODE REVIEW

**Comment by andrewrk** [comment]
Very cool! So if I understand correctly, the goals after this are:
1. Start moving test cases from test/translate_c.zig and test/run_translated_c.zig into test/cases/*
2. Start changing test cases from only `c_frontend=clang` to `c_frontend=clang,aro`.

**Comment by Vexu** [comment]
Yes, same as when self-hosting translate-c. Though it'll be easier to track progress if test cases are only moved when they pass on both frontends.

**Comment by andrewrk** [comment]
Another interesting thing to do will be to hook up the Aro translate-c pipeline as a way to produce object files from .c files without libclang. Currently that looks like:

```
$ stage4/bin/zig build-exe hello.c
hello.c:1:1: error: unable to build C object: aro does not support compiling C objects yet
```

But this can produce zig code via translate-c which then goes through the build-obj pipeline.

**Comment by andrewrk** [comment]
The CI failure is not a flaky test failure - it is hitting this assertion:
```
/home/ci/actions-runner9/_work/zig/zig/src/aro_translate_c.zig:427:21: 0x4b7c40f in transExpr (zig)
    std.debug.assert(node != .none);
                    ^
```

**Comment by Vexu** [comment]
That's easy to fix for now by just commenting out the problematic line, but why is it only crashing on `aarch64-linux-debug`?

**Comment by ehaas** [comment]
That's a good question. I'm running on x86_64 linux with a stage4 debug build of your branch and I hit that assert if I try to `zig translate-c` a C file with an enum with inferred enumeration values. The only explanation that seems possible is that the other ones aren't actually using aro for some reason? Even if the assert is removed I don't think the current code could generate a value of 6 for `Foo1`.

**Comment by andrewrk** [comment]
Perhaps because of something specific with musl libc headers on aarch64? You should be able to reproduce it with `-target aarch64-linux-musl -lc`.

**Comment by andrewrk** [comment]
Ah, I see there are no `#include` directives in that file, so my conjecture makes no sense. Next suggestion: maybe try Valgrind and see if there is some undefined value being branched on. Related: #17209

**Comment by ehaas** [comment]
Before we go too far down that road I'd want to verify that it's actually using aro in the tests - I updated my local copy to print out the value map after parsing and indeed it only has an entry for explicitly-set enumerators; the assert happens when it tries to pass `.none` (the special non-node index) to the translation function, because there is no node (nothing in the C source) for the implicitly defined enumerator values. We compute them during parsing but discard them after the parse since they're typically not needed. I think it would just be a matter of storing all enumerator values since we know we're going to want to translate them.

**Pull request merged**
