### PR TITLE
astgen: fix result info for catch switch_block_err_union

### LINKED ISSUE #19881: incorrect peer type resolution taking the address of `catch |err| switch (err)`
### Zig Version

0.12

### Steps to Reproduce and Observed Behavior

```zig
test {
    @compileLog(@TypeOf(&(try @as(anyerror!usize, 0))));
    @compileLog(@TypeOf(&(@as(anyerror!usize, 0) catch {})));
    @compileLog(@TypeOf(&(@as(anyerror!usize, 0) catch |err| return err)));
    @compileLog(@TypeOf(&(@as(anyerror!usize, 0) catch |err| switch (err) {
        else => return err,
    })));
}
```
```
Compile Log Output:
@as(type, *const usize)
@as(type, *const usize)
@as(type, *const usize)
@as(type, usize)
```
this didnt happen in 0.11, im guessing its caused by #18173
interestingly if you take the address of the switch itself it becomes correct
```zig
@compileLog(@TypeOf((@as(anyerror!usize, 0) catch |err| &switch (err) {
    else => return err,
})));

```
`@as(type, *const usize)`

### Expected Behavior

all logs should be `*const usize`
```
Compile Log Output:
@as(type, *const usize)
@as(type, *const usize)
@as(type, *const usize)
@as(type, *const usize)
```

### PR DESCRIPTION
**Pull request by dweiller**
Fixes #19881.

### Todo
  - [x] add behaviour tests to catch any future regressions

### CODE REVIEW

**Comment by dweiller** [comment]
Looks like the new tests as hitting a TODO in the wasm backend for lowering error union payload pointers. I'd probably need some guidance on how to implement that unless it's acceptable the skip the tests on wasm.

**Comment by Vexu** [comment]
> unless it's acceptable the skip the tests on wasm.

It is.

**Comment by dweiller** [comment]
Okay - I've disabled the address-of tests with the wasm backend.

**Review by andrewrk — CHANGES_REQUESTED** [review]
>  test: disable failing err union switch tests on wasm 

This commit message doesn't reflect what is happening in that commit. You're making a lot of changes to behavior tests, what's going on there?

**Comment by dweiller** [comment]
> > test: disable failing err union switch tests on wasm
> 
> This commit message doesn't reflect what is happening in that commit. You're making a lot of changes to behavior tests, what's going on there?

Each of the commented out function calls in test "switch on error union if else capture" would fail on wasm (I didn't check, but I'm pretty sure it will be the same reason as for the address-of tests). The commit is just cut-pasting them into the test "ptr tests" (which probably needs a better name), and unfortunately the diff algorithm doesn't seem to handle it well.

**Comment by mlugg** [comment]
Yeah, don't restructure the tests to favor slightly better testing of a backend which is unused in practice. Just disable the whole test for the WASM backend, and it can be re-enabled when the backend is improved.

**Comment by dweiller** [comment]
Okay - I've just disabled all the tests rather than splitting apart those that did or didn't pass on wasm.

**Pull request merged**
