### PR TITLE
CMakeLists.txt and build.zig: remove deprecated options

### PR DESCRIPTION
**Pull request by BratishkaErik**
Depends on https://github.com/ziglang/release-cutter/pull/4

### CODE REVIEW

**Comment by andrewrk** [comment]
Thank you - the relevant scripts to update is here:

https://github.com/ziglang/www.ziglang.org/blob/master/.github/workflows/build-tarballs.sh

**Comment by BratishkaErik** [comment]
> Thank you - the relevant script to update is here:
> 
> https://github.com/ziglang/www.ziglang.org/blob/master/.github/workflows/build-tarballs.sh
> 
> I would like to transition to replacing this logic with build.zig logic.

looks like it was already updated at https://github.com/ziglang/www.ziglang.org/commit/918bd375f199394bd8ad7831b36eed5120573039 and https://github.com/ziglang/www.ziglang.org/commit/5fa8b4e78869341dac589731aa9a028bd08909c7 ?

**Comment by andrewrk** [comment]
Ah yes, that looks sufficient.

**Comment by BratishkaErik** [comment]
my thanks too!

**Pull request merged**
