### PR TITLE
std.http: add identity to content encodings

### PR DESCRIPTION
**Pull request by cgbur**
Some servers will respond with the identity encoding, meaning no encoding, especially when responding to range-get requests. Adding the identity encoding stops the header parser from failing when it encounters this.

### CODE REVIEW

**Comment by notcancername** [comment]
Should this not be handled by setting `transfer_compression` to `null` if `identity` is specified, since that would enable all existing code to handle it??

**Comment by cgbur** [comment]
I am not sure that would fix the issue but I am not the most familiar with this codebase. Currently the failure is in the parsing code here (https://github.com/ziglang/zig/blob/master/lib/std/http/Client.zig#L407C29-L407C29).

```zig
                if (std.meta.stringToEnum(http.ContentEncoding, trimmed)) |ce| {
```

The `stringToEnum` is using that new variant that added which is valid in the content-encoding field. Before this the parsing would fail as there was no entry for `identity`.

**Comment by truemedian** [comment]
Since `null` and `.identity` have the same meaning, `transfer_compression` shouldn't be optional anymore, and all cases of `null` should be replaced by `.identity`.

**Comment by cgbur** [comment]
This was working when I initially made the commit, but it appears things have changed since then. I'll take a look at this in the next few days and fix the missing arms in the enumerations so the CI works. 

I'll also take a look at how difficult it would be to replace the null use cases with identity, but I'm unsure of whether I'll be able to make those changes myself.

**Comment by cgbur** [comment]
I've reopened this after updating everything to the latest 0.12.0 version. 

I didn't change the `?ContentEncoding` option to `.identity` in either the server or client because it would alter the code's semantics. There are two issues requiring long-term reworking that go beyond the scope of this PR:

1. Changing [this line](https://github.com/ziglang/zig/blob/fb6fff2561b5a56917e5efee4c374130189ab8b0/lib/std/http/Client.zig#L385) from `null` to `.identity` would disable the code's ability to detect when the header has not been set. This change would permit the same header to be set multiple times.
2. As far as I can tell, the current code doesn't account for the possibility of multiple content encodings that must be recursively applied to fulfill a request.

**Pull request merged**
