### PR TITLE
beginnings of non-LLVM self-hosted backend

### PR DESCRIPTION
**Pull request by andrewrk**
I present to you Hello World in ZIR:

#### hello.zir

```
@0 = str("Hello, world!\n")
@1 = primitive(noreturn)
@2 = primitive(usize)
@3 = fntype([], @1, cc=Naked)
@4 = int(0)
@5 = int(1)
@6 = int(231)
@7 = str("len")

@8 = fn(@3, {
  %0 = as(@2, @5) ; SYS_write
  %1 = as(@2, @5) ; STDOUT_FILENO
  %2 = ptrtoint(@0) ; msg ptr
  %3 = fieldptr(@0, @7) ; msg len ptr
  %4 = deref(%3) ; msg len
  %sysoutreg = str("={rax}")
  %rax = str("{rax}")
  %rdi = str("{rdi}")
  %rsi = str("{rsi}")
  %rdx = str("{rdx}")
  %rcx = str("rcx")
  %r11 = str("r11")
  %memory = str("memory")
  %syscall = str("syscall")
  %5 = asm(%syscall, @2,
    volatile=1,
    output=%sysoutreg,
    inputs=[%rax, %rdi, %rsi, %rdx],
    clobbers=[%rcx, %r11, %memory],
    args=[%0, %1, %2, %4])

  %6 = as(@2, @6) ;SYS_exit_group
  %7 = as(@2, @4) ;exit code
  %8 = asm(%syscall, @2,
    volatile=1,
    output=%sysoutreg,
    inputs=[%rax, %rdi],
    clobbers=[%rcx, %r11, %memory],
    args=[%6, %7])

  %9 = unreachable()
})

@9 = str("_start")
@10 = export(@9, @8)
```

After this pull request, self-hosted is capable of parsing this, semantically analyzing it, and rendering it back to ZIR:

```
./zig build-exe ../src-self-hosted/ir.zig
./ir hello.zir > hello2.zir
```

#### hello2.zir

```
@0 = str("Hello, world!\n")
@1 = str("{rax}")
@2 = str("{rdi}")
@3 = str("{rsi}")
@4 = str("{rdx}")
@5 = str("rcx")
@6 = str("r11")
@7 = str("memory")
@8 = primitive(usize)
@9 = int(1)
@10 = as(@8, @9)
@11 = primitive(usize)
@12 = int(1)
@13 = as(@11, @12)
@14 = int(14)
@15 = str("syscall")
@16 = primitive(usize)
@17 = str("={rax}")
@18 = str("{rax}")
@19 = str("{rdi}")
@20 = str("rcx")
@21 = str("r11")
@22 = str("memory")
@23 = primitive(usize)
@24 = int(231)
@25 = as(@23, @24)
@26 = primitive(usize)
@27 = int(0)
@28 = as(@26, @27)
@29 = str("syscall")
@30 = primitive(usize)
@31 = str("={rax}")
@32 = primitive(noreturn)
@33 = fntype([], @32, cc=Naked)
@34 = fn(@33, {
  %0 = ptrtoint(@0)
  %1 = asm(@15, @16, volatile=1, output=@17, inputs=[@1, @2, @3, @4], clobbers=[@5, @6, @7], args=[@10, @13, %0, @14])
  %2 = asm(@29, @30, volatile=1, output=@31, inputs=[@18, @19], clobbers=[@20, @21, @22], args=[@25, @28])
  %3 = unreachable()
})
@35 = str("_start")
@36 = export(@35, @34)
```

Running hello2.zir  back through semantic analysis yields the same output.

There are many directions to go with this:

 * Emit the semantically analyzed ZIR code directly to an ELF and/or PE file and run it
    - Then hook it up to a new test suite and start adding passing test cases
 * Figure out how comptime code & control flow will work with ZIR code. I'm thinking it will be a SSAT (Single Static Assignment Tree) form.
    - Observe the resource usage and performance of some simple loops with function calls and use that to iterate on the design with respect to memory usage and perf
 * Start mapping parsed Zig AST to ZIR
 * Set up performance measurements and benchmarking
 * Work on the incremental compilation aspects of it
 * Work on the multi-threaded aspects of it

My plan is to get self-hosted to a point where all of these directions have been explored just enough for their designs to be coherent with each other, and so that all these areas will be contributor friendly.

### CODE REVIEW

**Comment by sorenbug** [comment]
Is ZIR intended to ever have other languages output to it (and maybe as a complement be able to use Zig over C for FFI)?

**Comment by pixelherodev** [comment]
Awesome work!

**Comment by andrewrk** [comment]
> Is ZIR intended to ever have other languages output to it (and maybe as a complement be able to use Zig over C for FFI)?

Currently, no but that is something that could potentially be in scope in the future. Too early to tell.

**Comment by andrewrk** [comment]
Merging now. My goal is to get to the point of having test coverage as soon as possible, and then branch out from there.

**Pull request merged**
