### PR TITLE
std.http: add connection pooling, handle keep-alive and compressed content

### PR DESCRIPTION
**Pull request by truemedian**
The connection pool is implemented as a TailQueue linked list, as there *shouldn't* be too many connections to loop over.

This should also fix a few problems that people were having where the server would try to read more data than the server was sending, leaving them in a deadlock.

Redirected requests now *always* read the content associated with the redirect, but the data is voided. This is required to prepare the connection for another request (but could potentially be avoided on a Connection:close)

### CODE REVIEW

**Review by alichraghi — CHANGES_REQUESTED** [review]
[test-filetimestamp.tmp](https://github.com/ziglang/zig/pull/14762/files#diff-621b19a2b2102ecc25b7bc12ffc6d76306d6d2251af7f691ee446f2130657666) what's this? lol

**Comment by truemedian** [comment]
Really good question, not sure how I missed that or what that came from.

**Comment by kcbanner** [comment]
> Really good question, not sure how I missed that or what that came from.

I've seen that file sometimes get leftover by running the tests.

**Comment by andrewrk** [comment]
It looks good; I'd like to merge it.

How have you been testing it? Do you have any inclination to help out with adding a testing system for this stuff?

**Comment by truemedian** [comment]
I've currently been testing the new features against http://httpbin.org (in http, to bypass all of the tls bugs in std.crypto). I can't really fuzz it against anything but it has worked for all of the things I've tested it against.

I don't see a way to seriously test std.http.Client without first implementing a std.http.Server to test against.

**Pull request merged**
