### PR TITLE
Have zig build steps automatically inherit mode of builder

### PR DESCRIPTION
**Pull request by daurnimator**
As mentioned in https://github.com/ziglang/zig/issues/7201#issuecomment-753333023

### CODE REVIEW

**Review by ifreund — COMMENTED** [review]
I would make `Builder.standardReleaseOptions()` return void. It seems to me that there will be very few cases where the return value would be useful and for such cases `Builder.release_mode` could be used instead.

**Comment by daurnimator** [comment]
> I would make `Builder.standardReleaseOptions()` return void. It seems to me that there will be very few cases where the return value would be useful and for such cases `Builder.release_mode` could be used instead.

That would be a follow up change (as accepted in #7201): the end goal is to have a single `b.standardOptions(.{})` that doesn't return anything.

**Comment by ifreund** [comment]
> That would be a follow up change (as accepted in #7201): the end goal is to have a single `b.standardOptions(.{})` that doesn't return anything.

Makes sense, that way we only break the API once.

**Comment by daurnimator** [comment]
> Makes sense, that way we only break the API once.

There should be no API break at all: the old functions will be marked deprecated and removed after the next release.

**Comment by andrewrk** [comment]
No good, I want the build script writer to explicitly set the stuff on all build artifacts.

**Pull request closed without merging**
