### PR TITLE
Fix formatting for multiline asm expressions

### PR DESCRIPTION
**Pull request by LemonBoy**
Having to check for `MultilineStringLiteral` every time is not that nice tho.

### CODE REVIEW

**Comment by LemonBoy** [comment]
> Could you pair this with a commit reformatting the standard library?

I've reformatted only `valgrind.zig` to fix the weirdness caused by c1793d61061a112dc3d58c33ac0d3a1ebc8fb35e

**Comment by andrewrk** [comment]
Can you add a std/zig/parser_test.zig case?

**Comment by LemonBoy** [comment]
> Can you add a std/zig/parser_test.zig case?

Sure thing, I didn't add one because I couldn't find where to put it (and `parser_test` doesn't really suggest it contains such tests heh)

**Comment by andrewrk** [comment]
> Having to check for `MultilineStringLiteral` every time is not that nice tho.

Agreed and open to suggestions

**Pull request merged**
