### PR TITLE
std.json u64 support

### PR DESCRIPTION
**Pull request by marler8997**
fix issue https://github.com/ziglang/zig/issues/7901

A minimal set of changes to std.json to support integers up to the maximum of a `u64`.

NOTE: A future change may want to add support for BigInt.  Another idea I had was to encapsulate all possible number types into a `Number` sub-union, so that when user code doesn't need to know the number representation, they can work with the Number type to avoid duplicating code for each representation.

### CODE REVIEW

**Review by daurnimator — COMMENTED** [review]
I don't think this is the right direction to be going in: it's climbing a local maximum.
e.g. you would never get an unsigned integer with the high byte unset.
and it brings up questions of e.g. "why 64 bits? why not just have `i65` instead?" or `i128`, or as you said: BigNum.

**Comment by marler8997** [comment]
@daurnimator I'm all ears to alternative suggestions :)

As to why `u64`, the answer is I have a use case for it.  Though I admit it's not a particularly good reason.  However, it seems to be low cost to go from `i64` to also supporting `u64`.  It climbing slightly higher on the local maximum for a low cost.  If you can pointer me towards a better maximum I'll gladly explore it :)

**Comment by pfgithub** [comment]
Could integer instead be changed to `[]const u8` and then users asked to parse it themselves with `std.fmt.parseInt`? Either that or BigNum would solve this.

**Comment by marler8997** [comment]
@pfgithub I mentioned in the description that could be future work.  I wanted to do the minimal change to get JSON working for my use case, is there a downside to that approach?

**Comment by marler8997** [comment]
Thinking on it, I like @pfgithub 's suggestion.  It allows the parser to support the JSON spec for any number in its entirety and lets the user decide how to deal with its type.  I'm going to close this and push a new PR with that idea.

**Pull request closed without merging**
