### PR TITLE
macho: fix __unwind_info sentinel entry not always being the upper bound

### PR DESCRIPTION
**Pull request by kcbanner**
If the last unwind info record was elided because it matched the preceding one, then the sentinel entry wouldn't take it into account. This change keeps track of the upper bound and use that instead of looking a the last added entry.

Question for @kubkon, are these records guaranteed to be sorted? ie. is `@max` needed?

For this code:
```
0000000000000380 <_frame1>:
     380: 48 83 ec 28                   subq    $40, %rsp
... snip ...
     41a: 66 0f 1f 44 00 00             nopw    (%rax,%rax)

0000000000000420 <_frame0>:
     420: 48 83 ec 28                   subq    $40, %rsp
... snip ...
     4bc: c3                            retq

Disassembly of section __TEXT,__cstring:

00000000000004bd <__cstring>:
     4bd: 43 3a 5c 63 79                cmpb    121(%r11,%r12,2), %bl
     4c2: 67 77 69                      ja      0x52e
     4c5: 6e                            outsb   (%rsi), %dx
```

Before:
```
  Top level indices: (count = 2)
    [0]: function offset=0x00000380, 2nd level page offset=0x00000034, LSDA offset=0x00000034
    [1]: function offset=0x00000420, 2nd level page offset=0x00000000, LSDA offset=0x00000034
  LSDA descriptors:
  Second level indices:
    Second level index[0]: offset in section=0x00000034, base function offset=0x00000380
      [0]: function offset=0x00000380, encoding[0]=0x02060000
```

After
```
  Top level indices: (count = 2)
    [0]: function offset=0x00000380, 2nd level page offset=0x00000034, LSDA offset=0x00000034
    [1]: function offset=0x000004bd, 2nd level page offset=0x00000000, LSDA offset=0x00000034
  LSDA descriptors:
  Second level indices:
    Second level index[0]: offset in section=0x00000034, base function offset=0x00000380
      Page encodings: (count = 1)
        encoding[0]: 0x02060000
      [0]: function offset=0x00000380, encoding[0]=0x02060000
```

### CODE REVIEW

**Review by kubkon — CHANGES_REQUESTED** [review]
Thanks for the PR! This however feels like a hack to me rather than a solution. I would argue that the existing code should work as expected and that the bug is somewhere deeper in unwind info generation code. Would you happen to have a minimal repro so that I can understand the problem better?

**Review by kubkon — CHANGES_REQUESTED** [review]
Also, on the topic of reproductions, I don't see a test case added to linker tests. Would you mind putting it togther please?

**Comment by kcbanner** [comment]
Minimal repro (extracted from (test/standalone/stack_iterator in https://github.com/ziglang/zig/pull/15823):

```
zig cc -target aarch64-macos -shared -o test.so shared_lib.c
```

shared_lib.c:
```
#include <stdint.h>

#ifndef LIB_API
#define LIB_API
#endif

__attribute__((noinline)) void frame1(
    void** expected,
    void** unwound,
    void (*frame2)(void** expected, void** unwound)) {
    expected[3] = __builtin_extract_return_addr(__builtin_return_address(0));
    frame2(expected, unwound);
}

LIB_API void frame0(
    void** expected,
    void** unwound,
    void (*frame2)(void** expected, void** unwound)) {
    expected[4] = __builtin_extract_return_addr(__builtin_return_address(0));
    frame1(expected, unwound, frame2);
}
```

**Comment by kubkon** [comment]
> Minimal repro (extracted from (test/standalone/stack_iterator in #15823):
> 
> ```
> zig cc -target aarch64-macos -shared -o test.so shared_lib.c
> ```
> 
> shared_lib.c:
> 
> ```
> #include <stdint.h>
> 
> #ifndef LIB_API
> #define LIB_API
> #endif
> 
> __attribute__((noinline)) void frame1(
>     void** expected,
>     void** unwound,
>     void (*frame2)(void** expected, void** unwound)) {
>     expected[3] = __builtin_extract_return_addr(__builtin_return_address(0));
>     frame2(expected, unwound);
> }
> 
> LIB_API void frame0(
>     void** expected,
>     void** unwound,
>     void (*frame2)(void** expected, void** unwound)) {
>     expected[4] = __builtin_extract_return_addr(__builtin_return_address(0));
>     frame1(expected, unwound, frame2);
> }
> ```

Believe it or not, but there's no unwind info being generated on `aarch64-macos`:

```
$ zig cc -shared a.c -o a.dylib -target aarch64-macos
$ zacho -u a.dylib
No __TEXT,__unwind_info section found.
```

On `x86_64-macos` there is however:

```
$ zig cc -shared a.c -o a.dylib -target x86_64-macos
$ zacho -u a.dylib
Contents of __TEXT,__unwind_info section:
  Version:                  1
  Common encodings offset:  0x1c
  Common encodings count:   0
  Personalities offset:     0x1c
  Personalities count:      0
  Indexes offset:           0x1c
  Indexes count:            2

  Common encodings: (count = 0)

  Personality functions: (count = 0)

  Top level indices: (count = 2)
    [0]: function offset=0x00000370, 2nd level page offset=0x00000034, LSDA offset=0x00000034
    [1]: function offset=0x00000410, 2nd level page offset=0x00000000, LSDA offset=0x00000034

  LSDA descriptors:

  Second level indices:
    Second level index[0]: offset in section=0x00000034, base function offset=0x00000370
      Page encodings: (count = 1)
        encoding[0]: 0x01000000
      [0]: function offset=0x00000370, encoding[0]=0x01000000
```

**Comment by kubkon** [comment]
I have pushed a cleaner fix that was my oversight when implementing this at first. Recording of the highest address should have been done before the records are folded which is now fixed. I will mark this as ready to merge conditional on adding a suitable linker test in a follow-up PR.

**Review by kubkon — APPROVED** [review]

**Pull request merged**
