### PR TITLE
Type coercion for pointers to anon literals

### PR DESCRIPTION
**Pull request by Vexu**
```zig
test "yay" {
    const a: []const []const u8 = &.{ "hello", "world" };
}
```

### CODE REVIEW

**Comment by Snektron** [comment]
How does this solve the following case?
```zig
const a = .{1, 2, 3};
const b: *const [3]f32 = &a;
const b: *const [3]i32 = &a;
```

**Comment by Vexu** [comment]
> How does this solve the following case?

`a` will be generated into two separate values which have different addresses.

```zig
test "" {
    const a = .{1, 2, 3};
    const b: *const [3]f32 = &a;
    const c: *const [3]i32 = &a;

    std.debug.print("{} {}\n", .{b, c}); // [3]f32@201f10 [3]i32@201f28
}
```

**Comment by daurnimator** [comment]
> `a` will be generated into two separate values which have different addresses.

I didn't expect that

**Comment by Snektron** [comment]
> > How does this solve the following case?
> 
> `a` will be generated into two separate values which have different addresses.
 
What will be the lifetimes of those variables? It might be surprising if its local to the block from where the reference took place, instead of the assignment of `a`.

**Comment by Vexu** [comment]
> What will be the lifetimes of those variables? It might be surprising if its local to the block from where the reference took place, instead of the assignment of `a`.
> 

`a` is fully comptime known so they will have static lifetimes, if you add a runtime calue to the tuple it will no longer coase to both `b` and `c`.

**Comment by Snektron** [comment]
> `a` is fully comptime known so they will have static lifetimes, if you add a runtime value to the tuple it will no longer coase to both `b` and `c`.

Is that the case for all pointers-to-struct-literals, or just for this case? I can imagine the following scenario for example:
```zig
fn a(b: i32) {
  const c = .{.d = 1, .e = b};
  const f: *const struct{d: i32, e: i32} = &c;
  const g: *const struct{d: f32, e: i32} = &c;
}
```

**Comment by andrewrk** [comment]
@Snektron 

```zig
export fn foo(b: i32) void {
    const c = .{ .d = 1, .e = b };
    const f: *const struct { d: i32, e: i32 } = &c;
    const g: *const struct { d: f32, e: i32 } = &c;
}
```
```
[nix-shell:~/dev/zig/build]$ ./zig build-obj test.zig
./test.zig:2:5: error: expected type '*struct:3:21', found '*const struct:2:16'
    const c = .{ .d = 1, .e = b };
    ^
./test.zig:2:5: note: cast discards const qualifier
    const c = .{ .d = 1, .e = b };
    ^
./test.zig:3:50: note: referenced here
    const f: *const struct { d: i32, e: i32 } = &c;
                                                 ^
```

**Comment by andrewrk** [comment]
Nice work @Vexu

**Pull request merged**
