### PR TITLE
move some of the installation from cmake to zig build

### LINKED ISSUE #2585: cmake build system: figure out how to make the `zig0 build` always execute
Currently the cmake build system will not rebuild libuserland.a unless a select number of files are modified:

https://github.com/ziglang/zig/blob/f9ada1cfba5140ef01baa138813241c6b93a1ea9/CMakeLists.txt#L6720-L6732

I was unable to figure out how to make cmake unconditionally run this `zig build` command (which does its own caching).

Maybe the `#cmake` IRC channel could help. I didn't get an easy answer when I asked:

```
<andrewrk> is there a way to tell add_custom_command to always, unconditionally run the command? the command does its own caching
<andrewrk> can I add something to the DEPENDS that is always considered out of date?
<ngladitz> use a custom target instead?
<andrewrk> I think I tried that and it didn't work for some reason. let me refresh my memory
<andrewrk> ngladitz, because I need to depend on the OUTPUT in a target_link_libraries
<andrewrk> https://github.com/ziglang/zig/blob/f9ada1cfba5140ef01baa138813241c6b93a1ea9/CMakeLists.txt#L6720-L6732
<andrewrk> I'm pretty sure I tried add_custom_target first
<ngladitz> add a target interdependency (add_dependencies()) and declare the output in BYPRODUCTS?
<andrewrk> BYPRODUCTS? are we looking at the same documentation? 
<andrewrk> https://cmake.org/cmake/help/v3.0/command/add_custom_target.html
<andrewrk> actually my cmake min version is 2.8.5
<ngladitz> hm you might start questions with that bit of info .. 2.8.5 is like 8(?) years old
<ngladitz> fwiw BYPRODUCTS was introduces in 3.2 but is only required for Ninja
<ngladitz> *introduced
```

### LINKED ISSUE #2874: move the list of installation files from CMakeLists.txt into build.zig
CMakeLists.txt has a giant list of files that we want to ship with zig. This is annoying for several reasons:

 * It's data in the middle of code. It obscures the rest of the build script.
 * If you edit this file, it triggers a rebuild of the c++ compiler even though that shouldn't be necessary.
 * CMake has no way to disable printing all the files to stdout, even when nothing is changed. This causes `make install` to take a long time even when the file system operations complete quickly.
 * Really those should be recursive globs. But CMake's gobbing is problematic for a few reasons, one of which is that new files are not detected.
 * The list of files is not available to stage2.

All of these issues can be solved by moving this from CMakeLists.txt to build.zig.

 * [ ] implement globbing of installation files in zig build scripts (properly, with detection of new files)
 * [ ] instead of cmake doing the install, it will call `zig0 build install-the-files` (or a better named step), just like it already does to build libuserland.

Another reason we list files explicitly is that there are some large test files that we wish to not install. For example `std/special/compiler_rt/udivmodti4_test.zig` is 9.8 MiB.

This can be solved with the zig build glob feature supporting a list of exceptions. Or perhaps even a globbed list of exceptions and we can except `*_test.zig`.

### PR DESCRIPTION
**Pull request by andrewrk**
This moves the installation of shipped source files from large
CMakeLists.txt lists to zig build recursive directory installation.

This means that manually keeping CMakeLists.txt up to date with zig std lib files is no longer necessary.

On my computer a cmake `make install` takes 2.4 seconds even when it has
to do nothing, and prints a lot of unnecessary lines to stdout that say
"up-to-date: [some file it is installing]".

After this commit, `make` when there is nothing to do is down to 1
second, and it does not print any junk to stdout. Further, a `make
install` is no longer required and `make` is sufficient.

This closes #2874.

It also closes #2585. `make` now always invokes `zig build` for
installing files and libuserland.a, and zig's own caching system makes
that go fast.

I believe the only thing left to do before merging is implement `std.fs.File.updateTimes` for Windows.

### CODE REVIEW

**Comment by andrewrk** [comment]
There's a macOS thing to fix here, and then I'd like to figure out why the build when there's nothing to do is taking 20 seconds on Windows. I would expect this PR to make it go faster. @emekoi would you be willing to try this branch and seeing how long `make` takes to run in your mingw environment (running  `make` again after it completes previously)?

**Comment by emekoi** [comment]
i think the files are being installed unconditionally. looking at the handles that are opened the build executable opens handles for all the folders that it installs after every build invocation.

**Comment by andrewrk** [comment]
I'd expect it to open the handles but not write any data. Have a look at the  std.fs.updateFile function. It should only be writing the data if the mtimes of source and dest don't match.

**Comment by emekoi** [comment]
the install step actually seems to be broken. only folders are copied, no actual files. furthermore when running the install step manually from the repo root (`zig build install --override-std-dir std --override-lib-dir .`), i get this gnarly error
```
Unable to hash C:\msys64\home\Ikem\projects\zig\array_list.zig;ascii.zig;atomic.zig;atomic\int.zig;atomic\queue.zig;atomic\stack.zig;base64.zig;buf_map.zig;buf_set.zig;buffer.zig;build.zig;build\fmt.zig;c.zig;c\darwin.zig;c\freebsd.zig;c\linux.zig;c\netbsd.zig;c\windows.zig;child_process.zig;coff.zig;crypto.zig;crypto\blake2.zig;crypto\chacha20.zig;crypto\gimli.zig;crypto\hmac.zig;crypto\md5.zig;crypto\poly1305.zig;crypto\sha1.zig;crypto\sha2.zig;crypto\sha3.zig;crypto\x25519.zig;cstr.zig;debug.zig;debug\failing_allocator.zig;debug\leb128.zig;dwarf.zig;dynamic_library.zig;elf.zig;event.zig;event\channel.zig;event\fs.zig;event\future.zig;event\group.zig;event\io.zig;event\lock.zig;event\locked.zig;event\loop.zig;event\net.zig;event\rwlock.zig;event\rwlocked.zig;fmt.zig;fmt\errol.zig;fmt\errol\enum3.zig;fmt\errol\lookup.zig;fmt\parse_float.zig;fs.zig;fs\file.zig;fs\get_app_data_dir.zig;fs\path.zig;hash.zig;hash\adler.zig;hash\crc.zig;hash\fnv.zig;hash\siphash.zig;hash\murmur.zig;hash\cityhash.zig;hash_map.zig;heap.zig;heap\logging_allocator.zig;http.zig;http\headers.zig;io.zig;io\c_out_stream.zig;io\seekable_stream.zig;json.zig;lazy_init.zig;linked_list.zig;macho.zig;math.zig;math\acos.zig;math\acosh.zig;math\asin.zig;math\asinh.zig;math\atan.zig;math\atan2.zig;math\atanh.zig;math\big.zig;math\big\int.zig;math\big\rational.zig;math\cbrt.zig;math\ceil.zig;math\complex.zig;math\complex\abs.zig;math\complex\acos.zig;math\complex\acosh.zig;math\complex\arg.zig;math\complex\asin.zig;math\complex\asinh.zig;math\complex\atan.zig;math\complex\atanh.zig;math\complex\conj.zig;math\complex\cos.zig;math\complex\cosh.zig;math\complex\exp.zig;math\complex\ldexp.zig;math\complex\log.zig;math\complex\pow.zig;math\complex\proj.zig;math\complex\sin.zig;math\complex\sinh.zig;math\complex\sqrt.zig;math\complex\tan.zig;math\complex\tanh.zig;math\copysign.zig;math\cos.zig;math\cosh.zig;math\exp.zig;math\exp2.zig;math\expm1.zig;math\expo2.zig;math\fabs.zig;math\floor.zig;math\fma.zig;math\frexp.zig;math\hypot.zig;math\ilogb.zig;math\inf.zig;math\isfinite.zig;math\isinf.zig;math\isnan.zig;math\isnormal.zig;math\ln.zig;math\log.zig;math\log10.zig;math\log1p.zig;math\log2.zig;math\modf.zig;math\nan.zig;math\pow.zig;math\powi.zig;math\round.zig;math\scalbn.zig;math\signbit.zig;math\sin.zig;math\sinh.zig;math\sqrt.zig;math\tan.zig;math\tanh.zig;math\trunc.zig;mem.zig;meta.zig;meta\trait.zig;mutex.zig;net.zig;os.zig;os\bits.zig;os\bits\darwin.zig;os\bits\freebsd.zig;os\bits\linux.zig;os\bits\linux\arm64.zig;os\bits\linux\errno.zig;os\bits\linux\x86_64.zig;os\bits\netbsd.zig;os\bits\wasi.zig;os\bits\windows.zig;os\darwin.zig;os\freebsd.zig;os\linux.zig;os\linux\arm64.zig;os\linux\tls.zig;os\linux\vdso.zig;os\linux\x86_64.zig;os\netbsd.zig;os\uefi.zig;os\wasi.zig;os\windows.zig;os\windows\advapi32.zig;os\windows\bits.zig;os\windows\error.zig;os\windows\kernel32.zig;os\windows\lang.zig;os\windows\ntdll.zig;os\windows\ole32.zig;os\windows\shell32.zig;os\windows\sublang.zig;os\zen.zig;packed_int_array.zig;pdb.zig;priority_queue.zig;process.zig;rand.zig;rand\ziggurat.zig;rb.zig;segmented_list.zig;sort.zig;special\start.zig;special\start_lib.zig;special\start_windows_tls.zig;special\build_runner.zig;special\c.zig;special\compiler_rt.zig;special\compiler_rt\addXf3.zig;special\compiler_rt\arm\aeabi_dcmp.zig;special\compiler_rt\arm\aeabi_fcmp.zig;special\compiler_rt\ashlti3.zig;special\compiler_rt\ashrti3.zig;special\compiler_rt\aulldiv.zig;special\compiler_rt\aullrem.zig;special\compiler_rt\comparedf2.zig;special\compiler_rt\comparesf2.zig;special\compiler_rt\comparetf2.zig;special\compiler_rt\divdf3.zig;special\compiler_rt\divsf3.zig;special\compiler_rt\divti3.zig;special\compiler_rt\extendXfYf2.zig;special\compiler_rt\fixdfdi.zig;special\compiler_rt\fixdfsi.zig;special\compiler_rt\fixdfti.zig;special\compiler_rt\fixint.zig;special\compiler_rt\fixsfdi.zig;special\compiler_rt\fixsfsi.zig;special\compiler_rt\fixsfti.zig;special\compiler_rt\fixtfdi.zig;special\compiler_rt\fixtfsi.zig;special\compiler_rt\fixtfti.zig;special\compiler_rt\fixuint.zig;special\compiler_rt\fixunsdfdi.zig;special\compiler_rt\fixunsdfsi.zig;special\compiler_rt\fixunsdfti.zig;special\compiler_rt\fixunssfdi.zig;special\compiler_rt\fixunssfsi.zig;special\compiler_rt\fixunssfti.zig;special\compiler_rt\fixunstfdi.zig;special\compiler_rt\fixunstfsi.zig;special\compiler_rt\fixunstfti.zig;special\compiler_rt\floatdidf.zig;special\compiler_rt\floatsiXf.zig;special\compiler_rt\floattidf.zig;special\compiler_rt\floattisf.zig;special\compiler_rt\floattitf.zig;special\compiler_rt\floatundidf.zig;special\compiler_rt\floatunditf.zig;special\compiler_rt\floatunsidf.zig;special\compiler_rt\floatunsitf.zig;special\compiler_rt\floatuntidf.zig;special\compiler_rt\floatuntisf.zig;special\compiler_rt\floatuntitf.zig;special\compiler_rt\lshrti3.zig;special\compiler_rt\modti3.zig;special\compiler_rt\mulXf3.zig;special\compiler_rt\mulodi4.zig;special\compiler_rt\muloti4.zig;special\compiler_rt\multi3.zig;special\compiler_rt\negXf2.zig;special\compiler_rt\popcountdi2.zig;special\compiler_rt\stack_probe.zig;special\compiler_rt\truncXfYf2.zig;special\compiler_rt\udivmod.zig;special\compiler_rt\udivmoddi4.zig;special\compiler_rt\udivmodti4.zig;special\compiler_rt\udivti3.zig;special\compiler_rt\umodti3.zig;special\init-exe\build.zig;special\init-exe\src\main.zig;special\init-lib\build.zig;special\init-lib\src\main.zig;special\panic.zig;special\test_runner.zig;spinlock.zig;statically_initialized_mutex.zig;std.zig;testing.zig;thread.zig;time.zig;time\epoch.zig;unicode.zig;valgrind.zig;valgrind\callgrind.zig;valgrind\memcheck.zig;zig.zig;zig\ast.zig;zig\parse.zig;zig\parse_string_literal.zig;zig\render.zig;zig\tokenizer.zig: file not found
The following command exited with error code 1:
C:\msys64\home\Ikem\projects\zig\build\bin\zig.exe build-exe C:\msys64\home\Ikem\projects\zig\src-self-hosted\main.zig --object C:\msys64\home\Ikem\projects\zig\build\zig_cpp\libzig_cpp.a --object C:\msys64\home\Ikem\projects\zig\build\zig_cpp\libembedded_lld_wasm.a --object C:\msys64\home\Ikem\projects\zig\build\zig_cpp\libembedded_lld_elf.a --object C:\msys64\home\Ikem\projects\zig\build\zig_cpp\libembedded_lld_coff.a --object C:\msys64\home\Ikem\projects\zig\build\zig_cpp\libembedded_lld_lib.a --object C:\msys64\mingw64\lib\libz.a --library psapi --library shell32 --library ole32 --library uuid --library advapi32 --library pthread --object C:\msys64\mingw64\lib\libLLVMLTO.a --object C:\msys64\mingw64\lib\libLLVMPasses.a --object C:\msys64\mingw64\lib\libLLVMObjCARCOpts.a --object C:\msys64\mingw64\lib\libLLVMMIRParser.a --object C:\msys64\mingw64\lib\libLLVMSymbolize.a --object C:\msys64\mingw64\lib\libLLVMDebugInfoPDB.a --object C:\msys64\mingw64\lib\libLLVMDebugInfoDWARF.a --object C:\msys64\mingw64\lib\libLLVMCoverage.a --object C:\msys64\mingw64\lib\libLLVMMCA.a --object C:\msys64\mingw64\lib\libLLVMTableGen.a --object C:\msys64\mingw64\lib\libLLVMDlltoolDriver.a --object C:\msys64\mingw64\lib\libLLVMXRay.a --object C:\msys64\mingw64\lib\libLLVMOrcJIT.a --object C:\msys64\mingw64\lib\libLLVMXCoreDisassembler.a --object C:\msys64\mingw64\lib\libLLVMXCoreCodeGen.a --object C:\msys64\mingw64\lib\libLLVMXCoreDesc.a --object C:\msys64\mingw64\lib\libLLVMXCoreInfo.a --object C:\msys64\mingw64\lib\libLLVMXCoreAsmPrinter.a --object C:\msys64\mingw64\lib\libLLVMWebAssemblyDisassembler.a --object C:\msys64\mingw64\lib\libLLVMWebAssemblyCodeGen.a --object C:\msys64\mingw64\lib\libLLVMWebAssemblyDesc.a --object C:\msys64\mingw64\lib\libLLVMWebAssemblyAsmPrinter.a --object C:\msys64\mingw64\lib\libLLVMWebAssemblyAsmParser.a --object C:\msys64\mingw64\lib\libLLVMWebAssemblyInfo.a --object C:\msys64\mingw64\lib\libLLVMSystemZDisassembler.a --object C:\msys64\mingw64\lib\libLLVMSystemZCodeGen.a --object C:\msys64\mingw64\lib\libLLVMSystemZAsmParser.a --object C:\msys64\mingw64\lib\libLLVMSystemZDesc.a --object C:\msys64\mingw64\lib\libLLVMSystemZInfo.a --object C:\msys64\mingw64\lib\libLLVMSystemZAsmPrinter.a --object C:\msys64\mingw64\lib\libLLVMSparcDisassembler.a --object C:\msys64\mingw64\lib\libLLVMSparcCodeGen.a --object C:\msys64\mingw64\lib\libLLVMSparcAsmParser.a --object C:\msys64\mingw64\lib\libLLVMSparcDesc.a --object C:\msys64\mingw64\lib\libLLVMSparcInfo.a --object C:\msys64\mingw64\lib\libLLVMSparcAsmPrinter.a --object C:\msys64\mingw64\lib\libLLVMPowerPCDisassembler.a --object C:\msys64\mingw64\lib\libLLVMPowerPCCodeGen.a --object C:\msys64\mingw64\lib\libLLVMPowerPCAsmParser.a --object C:\msys64\mingw64\lib\libLLVMPowerPCDesc.a --object C:\msys64\mingw64\lib\libLLVMPowerPCInfo.a --object C:\msys64\mingw64\lib\libLLVMPowerPCAsmPrinter.a --object C:\msys64\mingw64\lib\libLLVMNVPTXCodeGen.a --object C:\msys64\mingw64\lib\libLLVMNVPTXDesc.a --object C:\msys64\mingw64\lib\libLLVMNVPTXInfo.a --object C:\msys64\mingw64\lib\libLLVMNVPTXAsmPrinter.a --object C:\msys64\mingw64\lib\libLLVMMSP430Disassembler.a --object C:\msys64\mingw64\lib\libLLVMMSP430CodeGen.a --object C:\msys64\mingw64\lib\libLLVMMSP430AsmParser.a --object C:\msys64\mingw64\lib\libLLVMMSP430Desc.a --object C:\msys64\mingw64\lib\libLLVMMSP430Info.a --object C:\msys64\mingw64\lib\libLLVMMSP430AsmPrinter.a --object C:\msys64\mingw64\lib\libLLVMMipsDisassembler.a --object C:\msys64\mingw64\lib\libLLVMMipsCodeGen.a --object C:\msys64\mingw64\lib\libLLVMMipsAsmParser.a --object C:\msys64\mingw64\lib\libLLVMMipsDesc.a --object C:\msys64\mingw64\lib\libLLVMMipsInfo.a --object C:\msys64\mingw64\lib\libLLVMMipsAsmPrinter.a --object C:\msys64\mingw64\lib\libLLVMLanaiDisassembler.a --object C:\msys64\mingw64\lib\libLLVMLanaiCodeGen.a --object C:\msys64\mingw64\lib\libLLVMLanaiAsmParser.a --object C:\msys64\mingw64\lib\libLLVMLanaiDesc.a --object C:\msys64\mingw64\lib\libLLVMLanaiAsmPrinter.a --object C:\msys64\mingw64\lib\libLLVMLanaiInfo.a --object C:\msys64\mingw64\lib\libLLVMHexagonDisassembler.a --object C:\msys64\mingw64\lib\libLLVMHexagonCodeGen.a --object C:\msys64\mingw64\lib\libLLVMHexagonAsmParser.a --object C:\msys64\mingw64\lib\libLLVMHexagonDesc.a --object C:\msys64\mingw64\lib\libLLVMHexagonInfo.a --object C:\msys64\mingw64\lib\libLLVMBPFDisassembler.a --object C:\msys64\mingw64\lib\libLLVMBPFCodeGen.a --object C:\msys64\mingw64\lib\libLLVMBPFAsmParser.a --object C:\msys64\mingw64\lib\libLLVMBPFDesc.a --object C:\msys64\mingw64\lib\libLLVMBPFInfo.a --object C:\msys64\mingw64\lib\libLLVMBPFAsmPrinter.a --object C:\msys64\mingw64\lib\libLLVMARMDisassembler.a --object C:\msys64\mingw64\lib\libLLVMARMCodeGen.a --object C:\msys64\mingw64\lib\libLLVMARMAsmParser.a --object C:\msys64\mingw64\lib\libLLVMARMDesc.a --object C:\msys64\mingw64\lib\libLLVMARMInfo.a --object C:\msys64\mingw64\lib\libLLVMARMAsmPrinter.a --object C:\msys64\mingw64\lib\libLLVMARMUtils.a --object C:\msys64\mingw64\lib\libLLVMAMDGPUDisassembler.a --object C:\msys64\mingw64\lib\libLLVMAMDGPUCodeGen.a --object C:\msys64\mingw64\lib\libLLVMAMDGPUAsmParser.a --object C:\msys64\mingw64\lib\libLLVMAMDGPUDesc.a --object C:\msys64\mingw64\lib\libLLVMAMDGPUInfo.a --object C:\msys64\mingw64\lib\libLLVMAMDGPUAsmPrinter.a --object C:\msys64\mingw64\lib\libLLVMAMDGPUUtils.a --object C:\msys64\mingw64\lib\libLLVMAArch64Disassembler.a --object C:\msys64\mingw64\lib\libLLVMAArch64CodeGen.a --object C:\msys64\mingw64\lib\libLLVMAArch64AsmParser.a --object C:\msys64\mingw64\lib\libLLVMAArch64Desc.a --object C:\msys64\mingw64\lib\libLLVMAArch64Info.a --object C:\msys64\mingw64\lib\libLLVMAArch64AsmPrinter.a --object C:\msys64\mingw64\lib\libLLVMAArch64Utils.a --object C:\msys64\mingw64\lib\libLLVMObjectYAML.a --object C:\msys64\mingw64\lib\libLLVMLibDriver.a --object C:\msys64\mingw64\lib\libLLVMOption.a --object C:\msys64\mingw64\lib\libLLVMOptRemarks.a --object C:\msys64\mingw64\lib\libLLVMWindowsManifest.a --object C:\msys64\mingw64\lib\libLLVMTextAPI.a --object C:\msys64\mingw64\lib\libLLVMFuzzMutate.a --object C:\msys64\mingw64\lib\libLLVMX86Disassembler.a --object C:\msys64\mingw64\lib\libLLVMX86AsmParser.a --object C:\msys64\mingw64\lib\libLLVMX86CodeGen.a --object C:\msys64\mingw64\lib\libLLVMGlobalISel.a --object C:\msys64\mingw64\lib\libLLVMSelectionDAG.a --object C:\msys64\mingw64\lib\libLLVMAsmPrinter.a --object C:\msys64\mingw64\lib\libLLVMX86Desc.a --object C:\msys64\mingw64\lib\libLLVMMCDisassembler.a --object C:\msys64\mingw64\lib\libLLVMX86Info.a --object C:\msys64\mingw64\lib\libLLVMX86AsmPrinter.a --object C:\msys64\mingw64\lib\libLLVMX86Utils.a --object C:\msys64\mingw64\lib\libLLVMMCJIT.a --object C:\msys64\mingw64\lib\libLLVMLineEditor.a --object C:\msys64\mingw64\lib\libLLVMInterpreter.a --object C:\msys64\mingw64\lib\libLLVMExecutionEngine.a --object C:\msys64\mingw64\lib\libLLVMRuntimeDyld.a --object C:\msys64\mingw64\lib\libLLVMCodeGen.a --object C:\msys64\mingw64\lib\libLLVMTarget.a --object C:\msys64\mingw64\lib\libLLVMCoroutines.a --object C:\msys64\mingw64\lib\libLLVMipo.a --object C:\msys64\mingw64\lib\libLLVMInstrumentation.a --object C:\msys64\mingw64\lib\libLLVMVectorize.a --object C:\msys64\mingw64\lib\libLLVMScalarOpts.a --object C:\msys64\mingw64\lib\libLLVMLinker.a --object C:\msys64\mingw64\lib\libLLVMIRReader.a --object C:\msys64\mingw64\lib\libLLVMAsmParser.a --object C:\msys64\mingw64\lib\libLLVMInstCombine.a --object C:\msys64\mingw64\lib\libLLVMBitWriter.a --object C:\msys64\mingw64\lib\libLLVMAggressiveInstCombine.a --object C:\msys64\mingw64\lib\libLLVMTransformUtils.a --object C:\msys64\mingw64\lib\libLLVMAnalysis.a --object C:\msys64\mingw64\lib\libLLVMProfileData.a --object C:\msys64\mingw64\lib\libLLVMObject.a --object C:\msys64\mingw64\lib\libLLVMMCParser.a --object C:\msys64\mingw64\lib\libLLVMMC.a --object C:\msys64\mingw64\lib\libLLVMDebugInfoCodeView.a --object C:\msys64\mingw64\lib\libLLVMDebugInfoMSF.a --object C:\msys64\mingw64\lib\libLLVMBitReader.a --object C:\msys64\mingw64\lib\libLLVMCore.a --object C:\msys64\mingw64\lib\libLLVMBinaryFormat.a --object C:\msys64\mingw64\lib\libLLVMSupport.a --object C:\msys64\mingw64\lib\libLLVMDemangle.a --object C:\msys64\home\Ikem\projects\zig\array_list.zig;ascii.zig;atomic.zig;atomic\int.zig;atomic\queue.zig;atomic\stack.zig;base64.zig;buf_map.zig;buf_set.zig;buffer.zig;build.zig;build\fmt.zig;c.zig;c\darwin.zig;c\freebsd.zig;c\linux.zig;c\netbsd.zig;c\windows.zig;child_process.zig;coff.zig;crypto.zig;crypto\blake2.zig;crypto\chacha20.zig;crypto\gimli.zig;crypto\hmac.zig;crypto\md5.zig;crypto\poly1305.zig;crypto\sha1.zig;crypto\sha2.zig;crypto\sha3.zig;crypto\x25519.zig;cstr.zig;debug.zig;debug\failing_allocator.zig;debug\leb128.zig;dwarf.zig;dynamic_library.zig;elf.zig;event.zig;event\channel.zig;event\fs.zig;event\future.zig;event\group.zig;event\io.zig;event\lock.zig;event\locked.zig;event\loop.zig;event\net.zig;event\rwlock.zig;event\rwlocked.zig;fmt.zig;fmt\errol.zig;fmt\errol\enum3.zig;fmt\errol\lookup.zig;fmt\parse_float.zig;fs.zig;fs\file.zig;fs\get_app_data_dir.zig;fs\path.zig;hash.zig;hash\adler.zig;hash\crc.zig;hash\fnv.zig;hash\siphash.zig;hash\murmur.zig;hash\cityhash.zig;hash_map.zig;heap.zig;heap\logging_allocator.zig;http.zig;http\headers.zig;io.zig;io\c_out_stream.zig;io\seekable_stream.zig;json.zig;lazy_init.zig;linked_list.zig;macho.zig;math.zig;math\acos.zig;math\acosh.zig;math\asin.zig;math\asinh.zig;math\atan.zig;math\atan2.zig;math\atanh.zig;math\big.zig;math\big\int.zig;math\big\rational.zig;math\cbrt.zig;math\ceil.zig;math\complex.zig;math\complex\abs.zig;math\complex\acos.zig;math\complex\acosh.zig;math\complex\arg.zig;math\complex\asin.zig;math\complex\asinh.zig;math\complex\atan.zig;math\complex\atanh.zig;math\complex\conj.zig;math\complex\cos.zig;math\complex\cosh.zig;math\complex\exp.zig;math\complex\ldexp.zig;math\complex\log.zig;math\complex\pow.zig;math\complex\proj.zig;math\complex\sin.zig;math\complex\sinh.zig;math\complex\sqrt.zig;math\complex\tan.zig;math\complex\tanh.zig;math\copysign.zig;math\cos.zig;math\cosh.zig;math\exp.zig;math\exp2.zig;math\expm1.zig;math\expo2.zig;math\fabs.zig;math\floor.zig;math\fma.zig;math\frexp.zig;math\hypot.zig;math\ilogb.zig;math\inf.zig;math\isfinite.zig;math\isinf.zig;math\isnan.zig;math\isnormal.zig;math\ln.zig;math\log.zig;math\log10.zig;math\log1p.zig;math\log2.zig;math\modf.zig;math\nan.zig;math\pow.zig;math\powi.zig;math\round.zig;math\scalbn.zig;math\signbit.zig;math\sin.zig;math\sinh.zig;math\sqrt.zig;math\tan.zig;math\tanh.zig;math\trunc.zig;mem.zig;meta.zig;meta\trait.zig;mutex.zig;net.zig;os.zig;os\bits.zig;os\bits\darwin.zig;os\bits\freebsd.zig;os\bits\linux.zig;os\bits\linux\arm64.zig;os\bits\linux\errno.zig;os\bits\linux\x86_64.zig;os\bits\netbsd.zig;os\bits\wasi.zig;os\bits\windows.zig;os\darwin.zig;os\freebsd.zig;os\linux.zig;os\linux\arm64.zig;os\linux\tls.zig;os\linux\vdso.zig;os\linux\x86_64.zig;os\netbsd.zig;os\uefi.zig;os\wasi.zig;os\windows.zig;os\windows\advapi32.zig;os\windows\bits.zig;os\windows\error.zig;os\windows\kernel32.zig;os\windows\lang.zig;os\windows\ntdll.zig;os\windows\ole32.zig;os\windows\shell32.zig;os\windows\sublang.zig;os\zen.zig;packed_int_array.zig;pdb.zig;priority_queue.zig;process.zig;rand.zig;rand\ziggurat.zig;rb.zig;segmented_list.zig;sort.zig;special\start.zig;special\start_lib.zig;special\start_windows_tls.zig;special\build_runner.zig;special\c.zig;special\compiler_rt.zig;special\compiler_rt\addXf3.zig;special\compiler_rt\arm\aeabi_dcmp.zig;special\compiler_rt\arm\aeabi_fcmp.zig;special\compiler_rt\ashlti3.zig;special\compiler_rt\ashrti3.zig;special\compiler_rt\aulldiv.zig;special\compiler_rt\aullrem.zig;special\compiler_rt\comparedf2.zig;special\compiler_rt\comparesf2.zig;special\compiler_rt\comparetf2.zig;special\compiler_rt\divdf3.zig;special\compiler_rt\divsf3.zig;special\compiler_rt\divti3.zig;special\compiler_rt\extendXfYf2.zig;special\compiler_rt\fixdfdi.zig;special\compiler_rt\fixdfsi.zig;special\compiler_rt\fixdfti.zig;special\compiler_rt\fixint.zig;special\compiler_rt\fixsfdi.zig;special\compiler_rt\fixsfsi.zig;special\compiler_rt\fixsfti.zig;special\compiler_rt\fixtfdi.zig;special\compiler_rt\fixtfsi.zig;special\compiler_rt\fixtfti.zig;special\compiler_rt\fixuint.zig;special\compiler_rt\fixunsdfdi.zig;special\compiler_rt\fixunsdfsi.zig;special\compiler_rt\fixunsdfti.zig;special\compiler_rt\fixunssfdi.zig;special\compiler_rt\fixunssfsi.zig;special\compiler_rt\fixunssfti.zig;special\compiler_rt\fixunstfdi.zig;special\compiler_rt\fixunstfsi.zig;special\compiler_rt\fixunstfti.zig;special\compiler_rt\floatdidf.zig;special\compiler_rt\floatsiXf.zig;special\compiler_rt\floattidf.zig;special\compiler_rt\floattisf.zig;special\compiler_rt\floattitf.zig;special\compiler_rt\floatundidf.zig;special\compiler_rt\floatunditf.zig;special\compiler_rt\floatunsidf.zig;special\compiler_rt\floatunsitf.zig;special\compiler_rt\floatuntidf.zig;special\compiler_rt\floatuntisf.zig;special\compiler_rt\floatuntitf.zig;special\compiler_rt\lshrti3.zig;special\compiler_rt\modti3.zig;special\compiler_rt\mulXf3.zig;special\compiler_rt\mulodi4.zig;special\compiler_rt\muloti4.zig;special\compiler_rt\multi3.zig;special\compiler_rt\negXf2.zig;special\compiler_rt\popcountdi2.zig;special\compiler_rt\stack_probe.zig;special\compiler_rt\truncXfYf2.zig;special\compiler_rt\udivmod.zig;special\compiler_rt\udivmoddi4.zig;special\compiler_rt\udivmodti4.zig;special\compiler_rt\udivti3.zig;special\compiler_rt\umodti3.zig;special\init-exe\build.zig;special\init-exe\src\main.zig;special\init-lib\build.zig;special\init-lib\src\main.zig;special\panic.zig;special\test_runner.zig;spinlock.zig;statically_initialized_mutex.zig;std.zig;testing.zig;thread.zig;time.zig;time\epoch.zig;unicode.zig;valgrind.zig;valgrind\callgrind.zig;valgrind\memcheck.zig;zig.zig;zig\ast.zig;zig\parse.zig;zig\parse_string_literal.zig;zig\render.zig;zig\tokenizer.zig --library c --cache-dir C:\msys64\home\Ikem\projects\zig\zig-cache --name zig -isystem C:\msys64\home\Ikem\projects\zig\src -isystem C:\msys64\home\Ikem\projects\zig\build -isystem C:\msys64\mingw64\include --library-path C:\msys64\mingw64/lib --override-std-dir C:\msys64\home\Ikem\projects\zig\std --override-lib-dir C:\msys64\home\Ikem\projects\zig --cache on 

Build failed. The following command failed:
C:\msys64\home\Ikem\projects\zig\zig-cache\o\0foNXeuVfMpalcginyld8Vs8or-9XavdxWgHZQwxIK4Wjszfpko2UxjQw0HiQUuQ\build.exe C:\msys64\home\Ikem\projects\zig\build\bin\zig.exe C:\msys64\home\Ikem\projects\zig C:\msys64\home\Ikem\projects\zig\zig-cache install --override-std-dir std --override-lib-dir .
```

**Comment by emekoi** [comment]
this causes a major slowdown when installing lib files. install times have gone from ~3 min to ~30 min.

**Comment by andrewrk** [comment]
Goodness. What is taking so long?

**Comment by emekoi** [comment]
a clean build/install seems to have fixed the problem.

**Pull request merged**
