### PR TITLE
`std.http` namespace documentation

### PR DESCRIPTION
**Pull request by vexy**
This PR contains function annotations and code comments for `std.http` namespace.

Public facing documentation TODO:
- [x] `Server`
- [x] `Client`
- [x]  `Request`
- [x] `Response`
- [x] `Connection`
- [x] `Proxy`
- [ ] `ContentEncoding`
- [ ] `TransferEncoding`
- [x]  `Field`
- [x] `Headers`
- [ ] `Method`  (reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods)
- [ ] `Version`

### CODE REVIEW

**Comment by vexy** [comment]
Hello there. First off, **yes**, obviously "some" comments are redundant (perhaps confusing or plain simply wrong). Keep in mind that "draft" state of this PR has a purpose of exploring this issues and eventually resolving them on community level.

Side note; thanks for all the valuable inputs.

I'm working with other contributors (eg. person who wrote `http` lib) on our discord server (https://discord.gg/zig) in making this package documentation "a zig" style. Also, as main consumers of this documentation would probably be other developers, I'm totally for picking all the details.

Also, what would be best way to document error sets or return values - from a linguistically perspective ?

This question would, hopefully, help solidify entire documentation making it consistent in terms of terminology and semantics.

Open to further discussion.

**Comment by InKryption** [comment]
> Also, what would be best way to document error sets or return values - from a linguistically perspective ?

In terms of annotating return types and possible error values, function signatures already do this. When a person reads a function signature, they already see the return type `E!T`. Adding a comment stating that same information doesn't add anything. Nor does it help to state in a comment what is plain from the name. Any comment which does these things should not exist.

Generally, you should add a comment which documents behavior or information which isn't already plain in the code itself. For example, answering "why does this return this?", "what is the meaning of this return value?", "when would this be returned", etc. Statements that add context and narrow down the semantics of code.

On another note, it would also behoove you to ensure you do not write comments which are potentially misleading. For example, in this change:
```zig
    /// Reads specified number of bytes (`len`) from given buffer of data
    /// Throws `ReadError` in case of errors.
    pub fn readAtLeast(conn: *Connection, buffer: []u8, len: usize) ReadError!usize {
```
The first line of the added comment actually creates confusion.
The general convention in zig for a function with a name derivative of `read` which accepts some form of argument like `buffer: []u8`, is that it is going to read data from some source, and write it to the caller's buffer such that the contents can be stored and used. However, the comment as written uses vague language, with one interpretation being that the connection is going to read a number of bytes from the `buffer` argument, which is quite the opposite of the truth. This type of comment should either use more more specific and descriptive language, or simply not exist in the first place.

By the way,
> Hello there. First off, yes, obviously "some" comments are redundant (perhaps confusing or plain simply wrong). Keep in mind that "draft" state of this PR has a purpose of exploring this issues and eventually resolving them on community level.

Yes, I am simply a community member sharing my thoughts.

**Comment by vexy** [comment]
> Yes, I am simply a community member sharing my thoughts.  

I'm glad we're on a same page and pointed in same direction 🙏  for that.

Keep in mind, though, we're generally dealing with two different things, no matter what `std` namespace we comment:
- (pure) function/code commenting
- generated documentation (out of source code) - aka autodoc team (@kristoff-it)

With second thing in mind, we all have to pay extra certain attention to the "documentation rendering" and provide contextual yet, sane and clear, **not misleading** comments (as you've pointed out) for most of the internals. Try visiting this ink: https://ziglang.org/documentation/master/std/#A;std:http.Client, on your end, OS and your browser, to have a better overview of the generated documentation look and feel.

Also, considering this line of `Client` struct:
```zig
ca_bundle: if (disable_tls) void else std.crypto.Certificate.Bundle = if (disable_tls) {} else .{},
```

What would be the best way to (code) comment this ?

Also, the "comment" of the struct itself:
```
Connecting and opening requests are threadsafe. Individual requests are not.
```
May seem a bit terse or perhaps not explanatory enough (imho)? Although "a Client" should be known http abstraction, right ? But what about public documentation ?

Lastly, bottom part of the generated documentation shows "error types". This is where we may start spinning in circles of commenting obvious vs not providing enough generated documentation... Open to further discussion on this end, anyhow.

_Attached simple annotated screenshot(s) for better clarity_ 👇 
Screenshot_2023-11-25_at_15_12_09
Screenshot_2023-11-25_at_14_53_13

**Comment by InKryption** [comment]
> Also, considering this line of Client struct:
>
> ```zig
> ca_bundle: if (disable_tls) void else std.crypto.Certificate.Bundle = if (disable_tls) {} else .{},
> ```
>
> What would be the best way to (code) comment this ?

I don't think there's any inherent need to comment this field, it is inherently self-explanatory. It's called "ca_bundle", wherein "ca" is a common abbreviation for "Certificate Authority" in the context of HTTP[S]. Its type is a conditional expression, such that when `disable_tls` is true, it's of type `void`; and when it's false, it's of type `std.crypto.Certificate.Bundle`. This is even rendered in the generated documentation, so there's no ambiguity in that respect. Unless there's some extra context or information you want to provide, it's perfectly fine to simply leave it without comment.

> Also, the "comment" of the struct itself:
> ```
> Connecting and opening requests are threadsafe. Individual requests are not.
> ```
> May seem a bit terse or perhaps not explanatory enough (imho)? Although "a Client" should be > known http abstraction, right ? But what about public documentation ?

This particular comment is a bit redundant. All of the functions being referenced all state their thread-safety, and nothing in `Request` claims any semblance of thread-safety, indicating it is not thread safe. This comment seems like it could be removed.

> Lastly, bottom part of the generated documentation shows "error types". This is where we may start spinning in circles of commenting obvious vs not providing enough generated documentation... Open to further discussion on this end, anyhow.

I don't quite understand your train of logic here. The generated documentation does not benefit by having the doc comment be redundant with the name of the declaration in question. If you're referring to potential instances where the generated documentation doesn't properly annotate code or resolve a reference, that is an issue that should be resolved by improving autodoc, not by adding redundant information in comments.

**Comment by vexy** [comment]
@InKryption thanks for all the redundancy claims. I'm still struggling stay sure you actually understood the purpose of this PR - as the main goal is to actually **add** comments for the sake of publicly facing documentation ?

To clarify: "... _feeling a redundancy_..." and claiming functions should be left uncommented as they are clear and obvious results in empty space or "No documentation" at the official documentation website for `zig` lang.
Are you sure you want us to stay on that level ? 😄

If so, I can easily close entire PR and leave `http` namespace completely undocumented...

---

Meanwhile, I've:
- added missing comments to the functions, making sure they align with `zig` error philosophy in general.
- went through internal fields adding to what was already commented
- added general `struct` description for the most prominent types.

Generally, as the `autodoc` pickups all the code comments and the creates interactive HTML out of that, I'd have two more general questions:
- should all internal fields of the (public) structs be commented or skipped ? (current codebase kinda does both)
- what's the best markup tags to use when marking specific function parameters (that may be clicked through on the documentation website)

**Comment by InKryption** [comment]
> To clarify: "... feeling a redundancy..." and claiming functions should be left uncommented as they are clear and obvious results in empty space or "No documentation" at the official documentation website for zig lang.
Are you sure you want us to stay on that level ?

The "no documentation provided" is not a mark of shame or a sign of something wrong. It simply indicates that whoever wrote the code, and everyone who has changed it since, has not felt the need to add additional context, meaning the code itself already provides all the necessary information information. You can click on the declaration and see its definition. If the only purpose of this PR is to fill in those blanks, then yes, it ought to be closed.

However, the other comments you've recently added concerning the thread safety of many methods seem like a valuable clarification, and I would be pleased to see them make it through.

**Comment by vexy** [comment]
> If the only purpose of this PR is to fill in those blanks, then yes, it ought to be closed.

_taking current screenshot of the PR_ 😄 

I'll let others express their emotions too :)

**Comment by nektro** [comment]
I think the energy would be better spent writing autodoc "guides" since as mentioned above zig's focus on readability means many of the decls don't really need comments. but a tutorial on how to wire them together would be much appreciated. reading the source code isnt something that should be shy'd away from in zig

**Comment by vexy** [comment]
Moved to another branch

**Pull request closed without merging**
