### PR TITLE
Sema: resolveStructLayout when use packed struct child type

### PR DESCRIPTION
**Pull request by kkHAIKE**
Closes https://github.com/ziglang/zig/issues/13159

This may not be the best solution..

### CODE REVIEW

**Comment by Vexu** [comment]
IMO the bug is the LLVM backend not handling the possibility of namespace like packed structs.

**Comment by kkHAIKE** [comment]
> IMO the bug is the LLVM backend not handling the possibility of namespace like packed structs.

Indeed it is.
another way, call resolveStructLayout in LLVM.dbg_var instead of Sema.field_val ?

**Comment by Vexu** [comment]
> another way, call resolveStructLayout in LLVM.dbg_var instead of Sema.field_val ?

Backends should not do any semantic analysis.

**Comment by kkHAIKE** [comment]
LLVM.dbg_var ignore backing_int_ty field if it is no_return ? (packed struct default init value)

**Comment by Vexu** [comment]
`lowerDebugTypeImpl` for packed structs should check `haveFieldTypes` as is done for regular structs a few lines down.

**Pull request closed without merging**
