### PR TITLE
compiler-rt: Add __divsi3, __aeabi_idiv

### PR DESCRIPTION
**Pull request by LemonBoy**
One more step towards a complete ARM32 port.

CC @vegecode since I see you're working on some ARM platform as well.

### CODE REVIEW

**Comment by vegecode** [comment]
Did you see this file?

https://github.com/llvm/llvm-project/blob/master/compiler-rt/lib/builtins/arm/divsi3.S

I'm confused about how compiler-rt uses the assembly routines instead of the c routines. Do you understand how that works?

I'd also be curious to see what kind of assembly this Zig code generates compared to the hand tuned one.

It's good to have someone else working on arm, too!

**Comment by LemonBoy** [comment]
> Did you see this file?

Yup, I've used it as base instead of the C version heh

> I'm confused about how compiler-rt uses the assembly routines instead of the c routines. Do you understand how that works?

Some silly CMake shenigans, check out the [CMakeLists.txt](https://github.com/llvm/llvm-project/blob/master/compiler-rt/lib/builtins/CMakeLists.txt) and the use of `filter_builtin_sources`.

> I'd also be curious to see what kind of assembly this Zig code generates compared to the hand tuned one.

Ranges from atrocious in debug mode to quite good in release mode, see for yourself:

```

0001a0ec <__aeabi_idiv>:
   1a0ec:	e3510000 	cmp	r1, #0
   1a0f0:	03a00000 	moveq	r0, #0
   1a0f4:	012fff1e 	bxeq	lr
   1a0f8:	e92d4010 	push	{r4, lr}
   1a0fc:	e3500000 	cmp	r0, #0
   1a100:	e1a02000 	mov	r2, r0
   1a104:	42620000 	rsbmi	r0, r2, #0
   1a108:	e3510000 	cmp	r1, #0
   1a10c:	e0214002 	eor	r4, r1, r2
   1a110:	42611000 	rsbmi	r1, r1, #0
   1a114:	eb000002 	bl	1a124 <__aeabi_uidiv>
   1a118:	e0200fc4 	eor	r0, r0, r4, asr #31
   1a11c:	e0400fc4 	sub	r0, r0, r4, asr #31
   1a120:	e8bd8010 	pop	{r4, pc}
```

**Comment by vegecode** [comment]
The generated code is good. In fact, I don't see the point in maintaining an assembly version of the same function for arm at all. 

I guess that's up to @andrewrk how exactly the port should match. I don't think it needs to match exactly. 

It is important to note here that without one specific version of the assembly, architectures that support the  signed divide instruction are not going to use it? I'll have to look into which ones those are.

How's this idea:
It would be much quicker to do a port of just the c versions of all the aeabi functions, when possible. Then benchmarking could be done against a Zig program using the ported c functions and the same program linked against a build of llvm's compiler-rt running on actual hardware. Then it would be plain what the cost/benefit is for doing the assembly versions.

I have lots of cortex m0/3/4 boards, but no R's or A's. I also have no v6 or earlier boards.

**Comment by vegecode** [comment]
From: https://developer.arm.com/docs/dui0473/latest/arm-and-thumb-instructions/sdiv

> Architectures
> This 32-bit Thumb instruction is available in ARMv7-R and ARMv7-M.
> This ARM instruction is optional in ARMv7-R.
> This ARM and 32-bit Thumb instruction is available in ARMv7-A if Virtualization Extensions are implemented, and optional if not.
> There is no 16-bit Thumb SDIV instruction.

It would make sense then in this pull request to add the sdiv supported instruction path for the architectures that are guaranteed to support the instruction.

That would be:
v7m
v7em
v7ve

I don't know about armv8 at all.

Of course, we're all doing this work for free, so if you don't want to, I can do it.

**Comment by LemonBoy** [comment]
> It would make sense then in this pull request to add the sdiv supported instruction path for the architectures that are guaranteed to support the instruction.

Not really, LLVM's instruction selector is smart enough to emit those opcodes directly if the target architecture has a HW divider and it's available in the selected mode (either ARM or THUMB).

What's possibly more interesting is detecting the presence of the HW divider at runtime (eg. using `AT_HWCAP` on linux) and dispatch a more efficient version of the builtins.

**Comment by vegecode** [comment]
After checking on godbolt, you are quite right. Llvm does automatically emit the correct instruction for the three architectures I listed. Why then does compiler-rt even have that path?

I see that clang defines the hardware division available define depending on the architecture and CPU selected, but it looks like llvm already has that information if you set the CPU correctly, so that aeabi function would never be called as it would just emit the instruction directly. 

I'm looking here for CPU specific features, btw:

www.llvm.org/svn/llvm-project/llvm/trunk/lib/Target/ARM/ARM.td

Too bad it doesn't also emit floating point instructions directly, unless you know how to make it do that? I'm going to experiment on that a bit more.

**Comment by andrewrk** [comment]
> I guess that's up to @andrewrk how exactly the port should match. I don't think it needs to match exactly.

My primary concern is getting correct implementations of all the compiler-rt functions, to completely eliminate the possibility of linker errors.

I don't think it needs to match exactly. It's only a matter of maintainability and the risk of bugs. When there's a direct port, upstream improvements can be ported downstream with little effort and low risk. But small deviations from that are OK as long as these tradeoffs are kept in mind.

> What's possibly more interesting is detecting the presence of the HW divider at runtime (eg. using `AT_HWCAP` on linux) and dispatch a more efficient version of the builtins.

Related issue: #1018

**Pull request merged**
