### PR TITLE
thread: simplify and remove useless return in spawn

### PR DESCRIPTION
**Pull request by vrischmann**

### CODE REVIEW

**Comment by jedisct1** [comment]
Sure, why not!

Thank you!

**Comment by andrewrk** [comment]
This is measurably worse! Zig's error return traces will point to the `return` token if they happen to occur, so having multiple `return` statements makes those stack traces really helpful. This destroys debuggability. Reverting immediately!

**Comment by vrischmann** [comment]
Sorry about that. I initially just wanted to remove the superfluous return and thought I might as well use `return switch`, but I didn't think about the error return traces.

**Comment by andrewrk** [comment]
No worries! It's a bit of institutional knowledge to pass on.

**Pull request merged**
