### PR TITLE
[Documentation] Add Error Union Documentation and ArgType

### PR DESCRIPTION
**Pull request by BraedonWooding**
I think this is the right place for it?  I've tried to follow the other code style and level of detail.

Just adds a few missing pieces, will probably be helping to polish up the docs over the next week or two :).

### CODE REVIEW

**Comment by BraedonWooding** [comment]
Everything should work now :).

**Comment by BraedonWooding** [comment]
@andrewrk just confirming is this the place for this??

**Comment by andrewrk** [comment]
@BraedonWooding I'm sorry, I intended to merge this this weekend and it slipped my mind. I'll be sure to get to it today.

**Comment by BraedonWooding** [comment]
Np :D

**Comment by andrewrk** [comment]
merged in 938d791b23d58abf2bad4aa90ae3496ae9bb2435

**Pull request closed without merging**
