### PR TITLE
Fix the ELF binaries for freestanding target created with self-hosted linker

### PR DESCRIPTION
**Pull request by alex14fr**
The ELF specification (generic ABI) states that ``loadable process segments must have congruent
values for p_vaddr and p_offset, modulo the page size''. Linux refuses to load binaries that
don't meet this requirement (execve() fails with EINVAL).
Ensures that output binaries always satisfy this condition.

### CODE REVIEW

**Comment by alex14fr** [comment]
> What is wrong with having the virtual address always page aligned? This way it's always congruent by definition. 

This is true, the thing is that, for freestanding targets (ie. has_os is false), the alignment (in the file, not the VA) is done on a ptr_size and this produces invalid binaries, because in the VA we are page-aligned. 

For instance, this is invalid on a 4k-page arch:

``
    LOAD off    0x0000000000000198 vaddr 0x000000000c000000
``

this is valid:

``
    LOAD off    0x0000000000001708 vaddr 0x000000000c000708
``

**Comment by kubkon** [comment]
> > What is wrong with having the virtual address always page aligned? This way it's always congruent by definition.
> 
> The thing is that, for freestanding targets (ie. has_os is false), the alignment (in the file, not the VA) is done on a ptr_size and this produces invalid binaries, because in the VA we are page-aligned. What the quoted sentence says is that offset (in the file) and vaddr must be congruent modulo page size.
> 
> For instance, this is invalid on a 4k-page arch:
> 
> `LOAD off 0x0000000000000198 vaddr 0x000000000c000000`
> 
> this is valid:
> 
> `LOAD off 0x0000000000001708 vaddr 0x000000000c000708`

The fix should therefore ensure we use correct alignment for file offsets on freestanding targets. I do not have much experience in freestanding ELF targets but perhaps we should just drop this distinction? It's funny as I had this exact discussion with @jacobly0 the other day.

**Comment by alex14fr** [comment]
I updated my branch to always align on a page (not doing so seems to break debug builds).

**Comment by kubkon** [comment]
> I updated my branch to always align on a page (not doing so seems to break debug builds).

Nice! Can you please open a new PR?

**Comment by alex14fr** [comment]
> > I updated my branch to always align on a page (not doing so seems to break debug builds).
> 
> Nice! Can you please open a new PR?

Sure :-) #19766

**Pull request closed without merging**
