### PR TITLE
std.unicode: add trim, reverse iteration, contains only matching codepoints

### PR DESCRIPTION
**Pull request by leifhelm**
I needed some code for working with UTF-8 strings that are currently not present in the standard library. `Utf8View` seemed a good fit to add the new functions, because then functions can be composed like this:
```zig
fn asciiWord(bytes: []const u8) !?Utf8View {
    const s = (try Utf8View.init(bytes)).trim({}, isWhitespace);
    return if(s.containsOnlyMatchingCodepoints({}, isAsciiLetter)) s else null;
}
```
Maybe `Utf8View` should then be renamed to something like `Utf8StringSlice`. 

For the functions taking a `comptime fn` I decided to include only the basic variant. I can imagine three other ones (with no context and/or `u21`).
#### Breaking changes
`Utf8Iterator.peek`: `it: *Utf8Iterator` -> `it: Utf8Iterator`: This communicates better the fact that the iterator is not modified (because now it actually does not).

### CODE REVIEW

**Comment by andrewrk** [comment]
These are not valid operations. You can't do stuff on codepoints alone without Unicode awareness.

**Comment by leifhelm** [comment]
What do you mean? I know it does not work for codepoint sequences but for single codepoints it works. `isWhitespace` and `isAsciiLetter` in my example are functions of the right type. Should I add them?

**Comment by andrewrk** [comment]
Let's start with this:

> Removes all codepoints from the start of this view where `shouldBeStripped`
> returns true. `shouldBeStripped` will only be called with valid codepoints.

This operation is worse than useless, because it is a red herring. It looks like something that could be useful for several applications, but in reality, it would be buggy if it were used. You can't do things like trim, upcase, alignment, or manipulation of characters without full Unicode awareness.

**Comment by andrewrk** [comment]
Let me try to make this conversation more productive, because I think my previous comments are not helpful.

Can you share some example use cases that you have in mind for this new API? For what purpose do you intend to use these functions?

BTW have you seen [ziglyph](https://github.com/jecolon/ziglyph)?

**Comment by leifhelm** [comment]
I was using it to trim punctuation from words. And then checking if the words only contain a certain subset of latin letters. I guess I was naive and thought that it would be useful to have these methods.

**Pull request closed without merging**
