### PR TITLE
stage1: remove obsolete branch in ir_analyze_cast

### PR DESCRIPTION
**Pull request by kubkon**
Branch handling `*[N]T` to `E![]T` is already handled in a more complete
branch handling `*[N]T` to `[]T` *and* `*[N]T` to `E![]T` so it seems
safe to remove this one.

### CODE REVIEW

**Comment by kubkon** [comment]
Hmm, this is super bizarre. For some reason, Azure CI didn't fire up 🤷‍♂️ I'll try adding another dummy commit on top of this one to see if it correctly triggers it.

**Comment by daurnimator** [comment]
> I'll try adding another dummy commit on top of this one to see if it correctly triggers it.

close and reopen your pr

**Comment by kubkon** [comment]
@daurnimator worked like a charm, thanks!

**Comment by andrewrk** [comment]
Thanks @kubkon !

**Pull request merged**
