### PR TITLE
Do not run asserts for WASI alignment when not targeting WASI

### LINKED ISSUE #19665: assert(@alignof(i16) == 2) fails on 8-bit AVR MCU
### Zig Version

0.12.0-dev.3630+215de3ee6

### Steps to Reproduce and Observed Behavior

Trying to build a static lib for an AVR MCU, Atmega328p specifically.
The following code
```
const std = @import("std");

export fn app_main() void {
    var buf: [20]u8 = undefined;
    var fba = std.heap.FixedBufferAllocator.init(&buf);
    const alloc = fba.allocator();

    const mem = alloc.alloc(u8, 10) catch |err| {
        err catch {};
        return;
    };
    _ = mem;
}
```

results in the following compiler error:
```
install
+- install app
   +- zig build-lib app Debug avr-freestanding-none 1 errors
/home/noxet/dev/tools/zig/zig-0.12.0/lib/std/debug.zig:403:14: error: reached unreachable code
/home/noxet/dev/tools/zig/zig-0.12.0/lib/std/os/wasi.zig:12:11: note: called from here
    if (!ok) unreachable; // assertion failure
             ^~~~~~~~~~~
/home/noxet/dev/tools/zig/zig-0.12.0/lib/std/os/wasi.zig:12:11: note: called from here
    assert(@alignOf(i16) == 2);
    ~~~~~~^~~~~~~~~~~~~~~~~~~~
error: the following command failed with 1 compilation errors:
/home/noxet/dev/tools/zig/zig-0.12.0/zig build-lib -ODebug -target avr-freestanding-none -mcpu atmega328p -Mroot=/home/noxet/dev/avr/app/src/main.zig --cache-dir /home/noxet/dev/avr/app/zig-cache --global-cache-dir /home/noxet/.cache/zig --name app -static --listen=- 
Build Summary: 0/3 steps succeeded; 1 failed (disable with --summary none)
install transitive failure
+- install app transitive failure
   +- zig build-lib app Debug avr-freestanding-none 1 errors
error: the following build command failed with exit code 1:
/home/noxet/dev/avr/app/zig-cache/o/fa9f7ff03f1b36a46011aeeafddb06d5/build /home/noxet/dev/tools/zig/zig-0.12.0/zig /home/noxet/dev/avr/app /home/noxet/dev/avr/app/zig-cache /home/noxet/.cache/zig --seed 0x46dca3b3 -Z13d2886cbd8e8d28
```

The build configuration:
```
const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = std.Target.Query{
        .abi = .none,
        .cpu_arch = .avr,
        .cpu_model = .{ .explicit = &std.Target.avr.cpu.atmega328p },
        .os_tag = .freestanding,
    };

    const optimize = b.standardOptimizeOption(.{});

    const lib = b.addStaticLibrary(.{
        .name = "app",
        .root_source_file = .{ .path = "src/main.zig" },
        .target = b.resolveTargetQuery(target),
        .optimize = optimize,
    });

    b.installArtifact(lib);

    const main_tests = b.addTest(.{
        .root_source_file = .{ .path = "src/main.zig" },
        .target = b.resolveTargetQuery(target),
        .optimize = optimize,
    });

    const run_main_tests = b.addRunArtifact(main_tests);
    const test_step = b.step("test", "Run library tests");
    test_step.dependOn(&run_main_tests.step);
}
```

### Expected Behavior

The 8-bit AVR MCUs do not have any alignment requirements for words, since a word is accessed by loading/storing 2 bytes (8-bit) at a time.

### PR DESCRIPTION
**Pull request by 190n**
Fixes #19665

It seems possible that the last two asserts should now be uncommented as well. I don't know enough about why they were commented in the first place.

### CODE REVIEW

**Comment by nektro** [comment]
how is the file getting referenced in a non-wasi build?

**Comment by 190n** [comment]
I think this is at least one of the culprits:

https://github.com/ziglang/zig/blob/e69caaa39f06b7ddf00c1e439c3df91f4efbdef3/lib/std/std.zig#L115-L119

I had a reproduction in #19919, although I closed that issue since I didn't realize it was a duplicate of #19665. The issue went away for me when I removed a call to `std.log`, which was indirectly using my Options struct.

**Comment by 190n** [comment]
Tests still pass locally with the i64/u64 alignment checks enabled, including x86-linux which seems to be the original reason they got disabled, so I'm pushing that change as well.

**Comment by nektro** [comment]
I'd recommend changing `std.options.wasiCwd` to be a `void` on non-wasi rather than editing the wasi file. files named for a target shouldn't have to worry about not being on that target, the bug imo is the spillage causing that to be evaluated.

**Comment by 190n** [comment]
Oh, that's failing on 32-bit x86 again. It must be referenced somewhere else too.

**Comment by 190n** [comment]
It seems like a few WASI-specific functions in std.posix get analyzed on all targets, and they reference WASI types in their signatures/returns. e.g. (targeting x86):

```
error: the following command failed with 1 compilation errors:
/home/ben/zig/build/stage4/bin/zig test -freference-trace=256 -ODebug -target x86-linux-gnu -mcpu baseline -Mroot=/home/ben/zig/lib/std/std.zig -lc --test-filter std-wasm32-wasi.0.1...0.1-musl-generic-Debug-libc --cache-dir /home/ben/zig/zig-cache --global-cache-dir /home/ben/.cache/zig --name test --zig-lib-dir /home/ben/zig/lib --listen=- 
test-std
└─ run test std-wasm32-wasi.0.1...0.1-musl-generic-Debug
   └─ zig test Debug wasm32-wasi 1 errors
/home/ben/zig/lib/std/posix.zig:1659:5: error: found compile log statement
    @compileLog("openatWasi");
    ^~~~~~~~~~~~~~~~~~~~~~~~~
```

Should we
- make all these params conditional on `builtin.os.tag` (and I'm not sure if this is the only place causing such issues, as `-freference-trace` isn't being very helpful)?
- move these all into a module that's only called on WASI?
- switch back to checking the OS inside `std/os/wasi.zig`?
- something else?

**Comment by Vexu** [comment]
> * switch back to checking the OS inside `std/os/wasi.zig`?

Like I said in the issue https://github.com/ziglang/zig/issues/19665#issuecomment-2057789773

**Comment by 190n** [comment]
Yeah, that seems probably easier at this point. I wanted to try @nektro's option but it seems like there are a lot more WASI references throughout std and it'll be hard to find them all.

**Pull request merged**
