### PR TITLE
std.os.accept: add error Interrupted and allow user to manually retry

### PR DESCRIPTION
**Pull request by nektro**
when a signal such as SIGINT or SIGTERM is received by a program under the default circumstances, it will cause the program to terminate immediately.

if however a listener for these is added using `signal(2)` or `sigaction(2)` then it is possible to run a function as a result of the signal instead and syscalls currently blocking will exit with EINTR.

however under status quo the logic used by `std.os.accept()` and thus `std.http.Server` and any others, this error is undetectable and unable to be handled. now in any other case this errno result is perfectly resumable, but the consumer of std.os.accept() is likely already running a loop of their own that they can then continue through when getting this new error. most notably, is that it allows for a safe and proper exit. consider the following pseudo code

```zig
var running = true;

fn main() !void {
    var server = Server{ ... }
    try server.listen(...);

   signal(SIGINT, handleSignal);
   signal(SIGTERM, handleSignal);

   while (running) {
      const conn = server.accept() catch continue;
      handleConnection(conn);
   }
}

fn handleSignal() void {
    running = false;
}
```

### CODE REVIEW

**Comment by marler8997** [comment]
The pseudo-code looks strange to me.  Setting a boolean to exit the loop without popping the listener socket is odd, as it means the loop won't exit until a new connection is attempted, at which point the connection will be accepted/handled but then the loop willl immediately exit right afterwards.

I believe the convention here would be to call `shutdown` on the listener socket inside `handleSignal` to get the `accept` function to return immediately.  With this change I think the program behaves as you would expect without the caller needing to handle `EINTR`?

**Comment by nektro** [comment]
closing of the socked is handled by `std.http.Server.deinit()` and so closing it in the signal handler would be a file double-free

**Comment by marler8997** [comment]
Right, that's why you call `shutdown` instead of `close`.

**Comment by nektro** [comment]
doing so in the example I provided would require hosting the server instance out from main into global scope which I would rather try and avoid, but I'll give it a shot and see how it behaves and report back

**Comment by nektro** [comment]
oh i missed that because I had to call `std.os.shutdown(server_global.socket.sockfd.?, .both);` rather than `std.net.StreamServer.shutdown()`. trying this now

**Comment by nektro** [comment]
yep that worked

**Pull request closed without merging**
