### PR TITLE
build.zig: Forward LLVM lib/include dirs from CMake

### PR DESCRIPTION
**Pull request by topolarity**
As-is, we might obtain, e.g. `-lLLVM-15`, from the CMake configuration, but then be unable to locate the library if it's not in your system library path. We need to get the lib/include dirs from CMake to fix that.

### CODE REVIEW

**Comment by jacobly0** [comment]
This successfully fixes one of the build issues I was having on gentoo.

**Comment by BratishkaErik** [comment]
> This successfully fixes one of the build issues I was having on gentoo.

Did you build Zig using ebuild from the tree, or it was manually builded? If the latter, take a look at this line: https://github.com/gentoo/gentoo/blob/118a16b58df7410ada6b0a741f6a0444a206239e/dev-lang/zig/zig-9999.ebuild#L56 .
If passing `-DCMAKE_PREFIX_PATH=/usr/lib/llvm/15` to CMake fixes your build issue, you can use this in the future in case searching logic will be broken again. (with changing `15` to correct version)

**Comment by jacobly0** [comment]
Building manually, my first build issue was that `-l` was passed without `-L`, which this PR fixes.  My other build issue is that `-L/usr/lib/llvm/15/lib -L/usr/lib/llvm/15/lib64` is being passed to LLD by CMake, which causes it to error about libraries being for the wrong arch.  Using either `-L/usr/lib/llvm/15/lib -L/usr/lib/llvm/15/lib64` or `-L/usr/lib/llvm/15/lib64` works, but I was unable to figure out how to tell CMake to do that.

**Comment by topolarity** [comment]
> If passing -DCMAKE_PREFIX_PATH=/usr/lib/llvm/15 to CMake fixes your build issue, you can use this in the future in case searching logic will be broken again.

This bug meant that any paths found by CMake were not being added to the stage3 compilation/link, no matter how CMake was configured. So this fix is needed for `-DCMAKE_PREFIX_PATH` to work properly, just as a heads up

> My other build issue is that -L/usr/lib/llvm/15/lib -L/usr/lib/llvm/15/lib64 is being passed to LLD by CMake

@jacobly0 Let's see if we can fix this for you. Can you share a complete CMake config + make output in a pastebin? Is the link for zig0, zig2, or stage3 failing for you?

**Comment by jacobly0** [comment]
> @jacobly0 Let's see if we can fix this for you. Can you share a complete CMake config + make output in a pastebin, as well as the output of `llvm-config --libdir` and the contents of `build/config.h`? Is the link for zig0, zig2, or stage3 failing for you?

Oh, I forgot but `-DCMAKE_PREFIX_PATH=/usr/lib/llvm/15` is actually what was causing the `lib`/`lib64` issue in the first place, which I only needed because of a missing `-I`.  That means that this PR actually fixes both of my issues, since the build works fine now if I don't set `CMAKE_PREFIX_PATH`.

[Here](https://gist.github.com/jacobly0/5c6e3a965a2d8c41fea3bb9fbdfa8226) is the output in case someone wants to look into it anyway, but it seemed to me like some CMake/LLD issue.

**Comment by topolarity** [comment]
Great, thanks for the details @jacobly0

**Pull request merged**
