### PR TITLE
Make primitive values not keywords

### LINKED ISSUE #2897: Make primitive values not keywords
#1803 was a grammatical cleanup that made all primitive types (`anyerror`, `void`, `bool`) into non-keywords. I think we could do the same for primitive values (`true`, `null`, `undefined`). Types and values are both just values, unlike keywords.

If it's anything like #1803 this will result in deleting code with no downside.

### PR DESCRIPTION
**Pull request by Vexu**
Closes #2897

### CODE REVIEW

**Comment by hryx** [comment]
Oh wow, that was fast. I probably should have mentioned that I was also working on a fix, although I attempted a different approach (based on my interpretation of an IRC conversation). It doesn't currently build, and in hindsight I may have been overcomplicating it. https://github.com/ziglang/zig/compare/master...hryx:de-keyword-primitive-values

**Comment by hryx** [comment]
@Vexu Your implementation seems to be passing and is a smaller/simpler change than mine. If you're satisfied with your implementation then I'm gonna cease work on my branch. Please feel free to take anything you find useful from it.

**Comment by Vexu** [comment]
Sorry for the duplicate work.

**Comment by Vexu** [comment]
Is declaring to `_` supposed to be allowed?
```zig
pub fn _() void {}
```
Currently no error is emitted.

Also the sourcehut check seems broken.
```
The process will require 42 MiB more space.
8 MiB to be downloaded.
[1/13] Fetching cmake-3.14.5.txz: .......... done
pkg: cached package cmake-3.14.5: size mismatch, fetching from remote
[2/13] Fetching cmake-3.14.5.txz: .......... done
pkg: cached package cmake-3.14.5: size mismatch, cannot continue
[#77191] 2019/07/22 10:46:08 Tearing down build VM
[#77191] 2019/07/22 10:46:14 Processing post-failed triggers...
[#77191] 2019/07/22 10:46:14 Sending webhook...
[#77191] 2019/07/22 10:46:15 Webhook response: 200
[#77191] 2019/07/22 10:46:15 Sent build status to GitHub
[#77191] 2019/07/22 10:46:15 Error: exit status 3
```

**Comment by hryx** [comment]
> Is declaring to _ supposed to be allowed?

It's not the declaration that would cause an error, but the usage of it in a reachable expression. Because of lazy evaluation, if you write `_()` somewhere, `pub fn _() void {}` then gets analyzed and produces this error:

```
error: `_` may only be used to assign things to
```

However, multiple declarations of `_` cause `error: redefinition of '_'` even before being used in an expression, so maybe what you mention should be illegal at the point of declaration.

---

Side note: Now that I think of it, this might cause problems with C compatibility, since `_` is a legal identifier in C (if I recall correctly), however unlikely. Maybe we should allow externs called `_` but only via `@"_"`.

**Comment by andrewrk** [comment]
@Vexu thanks for implementing this. Here's the situation:

It has come to my attention that #2897, which was accepted when you took on this task, actually has a potential issue that needs to be resolved before continuing on with the implementation (see #1802). So I un-accepted the issue and there is some design consideration to do. I'm sorry for misleading you.

Given that this PR has conflicts and looks like it was never passing the tests, I'm going to close it. It's still linked from the relevant issue, so if it gets re-accepted, you, or someone else, can pick up where you left off.

**Pull request closed without merging**
