### PR TITLE
Update the bundled musl libc version to 1.1.22

### PR DESCRIPTION
**Pull request by LemonBoy**
This PR contains the pristine contents of the release tarball, chopping away files we don't need (yet) doesn't save that much space (and the time saved when you have to update the sources easily outweighs any gain).

Maybe I should've run the `process_headers.zig` script, maybe not. What I know for sure is that I'm not going to configure by hand all those targets.

### CODE REVIEW

**Comment by andrewrk** [comment]
btw did you see that I documented my process? https://github.com/ziglang/zig/wiki/Updating-libc-Headers

**Comment by LemonBoy** [comment]
Yes, but I still don't know if/how to process the headers.

**Comment by marler8997** [comment]
@LemonBoy what are you doing here?  I remember seeing some commits from you in dmd.

**Comment by shawnl** [comment]
What is the reason we can't use a git submodule for this?

**Comment by andrewrk** [comment]
This is now done with musl 1.1.23. I updated the instructions on the wiki as well: https://github.com/ziglang/zig/wiki/Updating-libc#musl. The process now uses the pristine contents of the release tarball (or source checkout), and there are instructions for how to produce the header files for all the targets (and it only takes a few dozen seconds).

**Comment by andrewrk** [comment]
Oh, also I forgot to mention - I improved the way we handle musl's headers, and consequently shaved off 3 MiB of zig's installation size.

**Pull request closed without merging**
