### PR TITLE
compiler-rt: add aeabi_dcmp, comparedf2

### PR DESCRIPTION
**Pull request by vegecode**

### CODE REVIEW

**Comment by andrewrk** [comment]
I think the test isn't getting run, because it's never imported. Can you double check the test is getting run? I think that applies to #2299 as well.

**Comment by vegecode** [comment]
Oh snap! You're correct. I did run the tests manually on my machine. I'll
fix that tonight.

**Comment by vegecode** [comment]
Done.

**Comment by vegecode** [comment]
I rebased and force-pushed. Is that a good workflow for changes to a pull request?

**Comment by andrewrk** [comment]
> I rebased and force-pushed. Is that a good workflow for changes to a pull request?

Yep.

**Pull request merged**
