### PR TITLE
pay off some result location technical debt with regards to "mem slots"

### PR DESCRIPTION
**Pull request by andrewrk**
Previously, there was hacky code to deal with result locations and how they work with regards to comptime values and runtime values. In addition, there was a hacky "mem_slot" mechanism that managed the memory for local variables, and acted differently depending on comptime vs
runtime situations. All that is deleted in this branch, and as a result, result locations code has one less complication.

Importantly, this means that a comptime result location is now passed to a function when it is evaluated at comptime, which now matches how it works for runtime result locations.

Checklist:
 * [x] get behavior tests passing
 * [x] get std lib tests passing
 * [x] compile error tests passing
 * [x] rest of the test suite passing

### CODE REVIEW

**Comment by mikdusan** [comment]
- reduction for failing test: `test/stage1/behavior/undefined.zig`
- this is a stage1 compiler segfault

```zig
fn ainit() [2]i32 {
    var array: [2]i32 = undefined;
    array[0] = 1; // comment me out to avoid segfault
    return array;
}   
        
const foo = ainit();
    
export fn entry() void {
    const x = foo;
}   
    
pub fn panic(msg: []const u8, error_return_trace: ?*@import("builtin").StackTrace) noreturn {
    while (true) {}
} 
```

<br/>

#### IR0 section (identical for `master` and `ir-clean-up-vars`)
```
{
    var array: [2]i32 = undefined;
    array[0] = 1;
    return array;
}
fn ainit() { // (IR)
Entry_0:
...
  #24 | VarPtr                | (unknown)   | 1 | &array
  #25 | ResetResult           | (unknown)   | - | ResetResult(none)
  #26 | Const                 | comptime_int| 2 | 0
  #27 | EndExpr               | (unknown)   | - | EndExpr(result=none,value=0)
  #28 | ElemPtr               | (unknown)   | 1 | &#24[0]
...
```

<br/>

#### snippet following IR0 from `master`
```diff
  ~ /Users/mike/project/zig/work/z_undefined_02.zig:3:5
  ~ #23 | ResetResult           | (unknown)   | - | ResetResult(none)
  -> #27 | Const                 | void        | 0 | {}
  ~ /Users/mike/project/zig/work/z_undefined_02.zig:3:5
  ~ #24 | VarPtr                | (unknown)   | 1 | &array
! -> #28 | VarPtr                | *[2]i32     | 0 | &array
```

<br/>

#### snippet following IR0 from `ir-clean-up-vars`
```diff
  ~ /Users/mike/project/zig/work/z_undefined_02.zig:3:5
  ~ #23 | ResetResult           | (unknown)   | - | ResetResult(none)
  -> #28 | Const                 | void        | 0 | {}
  ~ /Users/mike/project/zig/work/z_undefined_02.zig:3:5
  ~ #24 | VarPtr                | (unknown)   | 1 | &array
! -> #19 | AllocaGen             | *[2]i32     | 0 | Alloca(align=0,name=array)
```

<br/>

- `AllocaGen` looks like a hint at the issue?

**Comment by andrewrk** [comment]
btw @mikdusan and @LemonBoy I also added in this branch a dump() method of `ZigValue`. This turned out to be really helpful when debugging. It prints a representation with pointer addresses of the actual implementation layout of a value (rather than what the value would look like as a zig expression).

So that will be useful in the future for debugging, especially when combined with 

```c
void dbg_ir_break(const char *src_file, uint32_t line);
void dbg_ir_clear(void);
```

and `ira->break_debug_id`. I'll take the time to add a section to CONTRIBUTING.md for how to use these debugger things because they can be really helpful for ir stuff.

**Comment by mikdusan** [comment]
- reduction for failing test: `test/stage1/behavior/var_args.zig`
- this is an erroneous stage1 compiler error

```zig
export fn entry() void {
    const x = .{ @as(u32, 111) };
}
        
pub fn panic(msg: []const u8, error_return_trace: ?*@import("builtin").StackTrace) noreturn {
    while (true) {}
}       
```

<br/>

This is probably a good hint: in debug frame comparing `master` and` ir-clean-up-vars ` the `field_count` is different:

```diff
-(size_t) field_count = 1
+(size_t) field_count = 2
```

**Comment by mikdusan** [comment]
- reduction for failing test: `test/stage1/behavior/optional.zig`
- this presents as an erroneous stage1 compiler error:

```zig
const global: i32 = 1234;

fn foo() ?*const i32 {
    return &global;
}

export fn entry() void {
    comptime _ = foo().?.* == 1234;
}
```

```
/Users/mike/project/zig/work/z_optional_01.zig:8:21: error: expected optional type, found '*const i32'
    comptime _ = foo().?.* == 1234;
                    ^
/Users/mike/project/zig/work/z_optional_01.zig:8:23: note: referenced here
    comptime _ = foo().?.* == 1234;
                      ^
```

**Comment by mikdusan** [comment]
- reduction for failing test: `test/stage1/behavior/misc.zig`
- this presents as stage1 compiler error:

```zig
export fn entry() void {
    _ = global_ptr == &gdt[0];
}   

const GDTEntry = struct {
    field: i32,
};  
var gdt = [_]GDTEntry{
    GDTEntry{ .field = 1 },
    GDTEntry{ .field = 2 },
};
var global_ptr = &gdt[0];
```

```
./z_misc_02.zig:12:18: error: cannot store runtime value in compile time variable
var global_ptr = &gdt[0];
                 ^
./z_misc_02.zig:2:9: note: referenced here
    _ = global_ptr == &gdt[0];
        ^
```

**Comment by andrewrk** [comment]
Behavior tests are now passing, and the fixes for the regressions were generally not hacky, but in the direction of better code. So I think this change is going to be helpful.

Still need to get std lib tests passing and then the rest of the test suite. I'll try to extract std lib test failures into extra behavior tests, for better language coverage.

**Comment by mikdusan** [comment]
- reduction for failure from `zig test lib/std/fmt.zig`
- presents as compile error

```zig
export fn entry() void {
    testFmt("f64: 1.00000e-09", "f64: {e:.5}", .{@bitCast(f32, @as(u32, 814313563))});
}

fn testFmt(expected: []const u8, comptime template: []const u8, args: var) void {}
```

```
./z_std_fmt.zig:7:73: error: cannot assign to constant
    testFmt("f64: 1.00000e-09", "f64: {e:.5}", .{@bitCast(f32, @as(u32, 814313563))});
                                                                        ^
```

**Comment by mikdusan** [comment]
- reduction for failure from `lib/std/hash/murmur.zig`
- presents as compile error

```zig
export fn entry() void {
    const str: []const u8 = "hello";

    for (@ptrCast([*]allowzero align(1) const u64, str.ptr)) |v| {}
}   
```

```
./z_std_hash_murmer.zig:4:5: error: type '[*]align(1) const allowzero u64' does not support field access
    for (@ptrCast([*]allowzero align(1) const u64, str.ptr)) |v| {}
    ^
```

**Comment by mikdusan** [comment]
- reduction for failure from `zig test lib/std/rand.zig`
- presents as compile error from comptime panic
- `@compileLog(bar())` outputs `undefined`

```zig
const std = @import("std");
const expect = std.testing.expect;

export fn entry() void {
    comptime foo();
}

fn foo() void {
    expect(bar() == 0);
}

fn bar() u0 {
    var bytes: [0]u8 = undefined;
    const result = std.mem.readIntSliceLittle(u0, &bytes);
    return @bitCast(u0, result);
}   
```

```
./lib/std/testing.zig:177:10: error: use of undefined value here causes undefined behavior
    if (!ok) @panic("test failure");
         ^
./z_std_rand.zig:9:11: note: called from here
    expect(bar() == 0);
          ^
./z_std_rand.zig:5:17: note: called from here
    comptime foo();
                ^
./z_std_rand.zig:4:24: note: called from here
export fn entry() void {
                       ^
```

**Comment by mikdusan** [comment]
The failure for `zig test lib/std/io/test.zig` is a little involved but  I think it might be related to https://github.com/ziglang/zig/pull/4152#issuecomment-573992148 because it presents when bit-size is 0 for an inline test. The following patch sidesteps the stage1 segfaul:

```diff
diff --git a/lib/std/io/test.zig b/lib/std/io/test.zig
index 92259fd6e..228d0d55d 100644
--- a/lib/std/io/test.zig
+++ b/lib/std/io/test.zig
@@ -352,7 +352,7 @@ fn testIntSerializerDeserializer(comptime endian: builtin.Endian, comptime packi
     }
     try serializer.flush();
 
-    i = 0;
+    i = 1;
     inline while (i <= max_test_bitsize) : (i += 1) {
         const U = @IntType(false, i);
         const S = @IntType(true, i);
```

<br/>

and highlighted lines trigger segfault:
```diff
  i = 1;
  inline while (i <= max_test_bitsize) : (i += 1) {
      const U = @IntType(false, i);
      const S = @IntType(true, i);
!     const x = try deserializer.deserializeInt(U);
!     const y = try deserializer.deserializeInt(S);
      expect(x == @as(U, i));
      if (i != 0) expect(y == @as(S, -1)) else expect(y == 0);
  }
```

**Comment by mikdusan** [comment]
- as of https://github.com/ziglang/zig/pull/4152/commits/b96872ef2f619de476fb79c0bb142ebdace62382
- this reduction is cleaner than https://github.com/ziglang/zig/pull/4152#issuecomment-573992148
- reduction for failure from `zig test lib/std/rand.zig`
- presents as compile error

```zig
export fn entry() void {
    comptime {
        if (foo_zero() == 0) {} // compile error
        if (foo_undefined() == 0) {} // same compile error
    }
}

fn foo_zero() u0 {
    return 0;
}
fn foo_undefined() u0 {
    return undefined;
}
```

```
./reduction.zig:3:24: error: use of undefined value here causes undefined behavior
        if (foo_zero() == 0) {}
                       ^
./reduction.zig:1:24: note: referenced here
export fn entry() void {
                       ^
```

**Pull request merged**
