### PR TITLE
std.mem: add indexOfMin and indexOfMax

### LINKED ISSUE #9891: std.mem: add indexOfMin/Max
I think the usefulness of the index is obvious.

### PR DESCRIPTION
**Pull request by zzyxyzz**
Find the index of the smallest/largest number in a slice, without traversing it twice.

closes #9891

### CODE REVIEW

**Comment by zzyxyzz** [comment]
Drone failure unrelated?

**Comment by Snektron** [comment]
There is already an equivalent of the minIndex and maxIndex function in std.sort:
https://github.com/ziglang/zig/blob/ee98d8700818aa667137e3aa580b16df2ba6d680/lib/std/sort.zig#L1413-L1418
https://github.com/ziglang/zig/blob/ee98d8700818aa667137e3aa580b16df2ba6d680/lib/std/sort.zig#L1361-L1366

**Review by SpexGuy — APPROVED** [review]

**Comment by SpexGuy** [comment]
Going to close and reopen to kick off CI

**Comment by zzyxyzz** [comment]
Drone failure looks unrelated, but I'm not quite sure. Has it been seen before? Something about missing references to "ceill" and "florl".

**Pull request merged**
