### PR TITLE
std.os.linux: Add cancel and io_uring_prep_cancel

### PR DESCRIPTION
**Pull request by hnakamur**
This pull request adds IO_Uring.cancel method and io_uring_prep_cancel function

### CODE REVIEW

**Comment by lithdew** [comment]
Awesome, helps me remove a bit of code from my io_uring runtime :smile: https://github.com/lithdew/rheia/blob/master/runtime.zig#L790-L800.

As a consideration, what do you think about simplifying `io_uring_prep_cancel` down to:
```zig
fn io_uring_prep_cancel(sqe: *os.linux.io_uring_sqe, user_data: u64, flags: u32) void {
    os.linux.io_uring_prep_rw(.ASYNC_CANCEL, sqe, -1, user_data, 0, 0);
    sqe.rw_flags = flags;
}
```

**Comment by hnakamur** [comment]
@lithdew Thanks for your comment. Yes, I noticed some functions such as `io_uring_prep_recv` uses `io_uring_prep_rw`.

```
pub fn io_uring_prep_recv(sqe: *io_uring_sqe, fd: os.fd_t, buffer: []u8, flags: u32) void {
    io_uring_prep_rw(.RECV, sqe, fd, @ptrToInt(buffer.ptr), buffer.len, 0);
    sqe.rw_flags = flags;
}
```

However, other functions such as `io_uring_prep_timeout_remove` directly set values to `sqe.*`.

```
pub fn io_uring_prep_timeout_remove(sqe: *io_uring_sqe, timeout_user_data: u64, flags: u32) void {
    sqe.* = .{
        .opcode = .TIMEOUT_REMOVE,
        .flags = 0,
        .ioprio = 0,
        .fd = -1,
        .off = 0,
        .addr = timeout_user_data,
        .len = 0,
        .rw_flags = flags,
        .user_data = 0,
        .buf_index = 0,
        .personality = 0,
        .splice_fd_in = 0,
        .__pad2 = [2]u64{ 0, 0 },
    };
}
```

I followed the latter, but the former is OK for me too.
Should I change `io_uring_prep_cancel` to use `io_uring_prep_rw`?

**Comment by lithdew** [comment]
Either one is fine to me :+1:.

cc @ifreund @jorangreef

**Comment by jorangreef** [comment]
Thanks @hnakamur and @lithdew.

That's a good suggestion to use `io_uring_prep_rw`, and let's do that here too, also since it's how liburing does it for `io_uring_prep_cancel`: https://github.com/axboe/liburing/blob/master/src/include/liburing.h#L463-L468

I tried to follow liburing's API and implementation as closely as possible, it's very clean, and it's also kind of the reference implementation for io_uring, so if anyone is familiar with it then they should be pretty comfortable with what we have here.

**Review by ifreund — APPROVED** [review]
LGTM, just needs a rebase before it can be merged due to a conflict.

**Comment by hnakamur** [comment]
Thanks @ifreund, I rebased this pull request.

**Comment by hnakamur** [comment]
@ifreund Hi, I rebased again to rerun the checks above since previous checks had failed due to the server problems.

**Pull request merged**
