### PR TITLE
More std.fmt goodness

### PR DESCRIPTION
**Pull request by LemonBoy**
I'm pushing this branch so you can give it a spin to make sure there are no regressions and, if possible, find an answer to a few open questions.

**The good**

* `comptime` seems to work, stage1 didn't catch fire
* Named arguments are here, enjoy
* Runtime-specified width & precision are now supported
* Thanks to the quasi-equivalence between tuples and anonymous structs (the former are anonymous structures where every field name is equal to its index) we can use the same syntax for named and positional arguments (`{[NAME]}` or `{[POSITION]}`)

**The bad**

* Runtime parameters means the options structure is now built at runtime, expect a (small) speed/size hit
* More tests! (Do we need more tests?)
* Documentation needs updating (for the love of $DEITY don't let me write docs)
* You tell me

**The ugly**

* Duplicate syntax for positionals, you can use both `{N}` and `{[N]}` for referring to the N-th parameter. Is this unacceptable and dis*c*usting? Is this fine?
  * If we're in for some (Do _you_ use positional specifiers in your format strings?) breakage what about requiring positionals & named arguments to be enclosed in `[]`?
* I hope none of the supposed-to-stay-in-the-compiler machinery finds its way into the final binary
* You

There's no specifier to tell the width/precision is taken from the following argument, do we want that?

### CODE REVIEW

**Comment by data-man** [comment]
> Named arguments are here, enjoy

Maybe use `@` as additional feature?
```zig
try testFmt("hello world!", "{@greeting @who!}", .{ .greeting = "hello", .who = "world" });
```

**Comment by FireFox317** [comment]
> Maybe use `@` as additional feature?

I wouldn't use `@`. `@` should only be used for compiler builtins in my opinion.

**Comment by data-man** [comment]
@FireFox317 

> `@` should only be used for compiler builtins in my opinion.

and `[` and `]` should only be used for access by index? :)

**Comment by FireFox317** [comment]
@data-man
> and [ and ] should only be used for access by index? :)

I guess so? I just think we should treat compiler builtins as quite special and thus not use the `@` symbol.

**Comment by LemonBoy** [comment]
Hmm, the Windows failure looks legit... Can anyone pinpoint where (and/or on what file) it's crashing?

**Comment by marler8997** [comment]
I feel like the description is just a test to see who will read it till the end?

**Comment by Rocknest** [comment]
> The ugly (1)(a) 'what about requiring positionals & named arguments to be enclosed in []?'

Seems like a good idea 👍🏻

**Comment by andrewrk** [comment]
I don't think the issue is caused by this branch - I'm seeing a similar failure in master. I suspect 0f3111379b940823090b3a0e540aa04fac64dc5b

**Comment by andrewrk** [comment]
can you try rebasing to after f8b3543cabc28df15e85085a72adb474b345cf93 ?

**Comment by LemonBoy** [comment]
> can you try rebasing to after f8b3543 ?

Done, but the failure's still there :(

**Comment by andrewrk** [comment]
I'll help with this eventually, but I do want to focus on my branch #6250 until it's done

**Comment by ifreund** [comment]
This will be very nice to have for [code generation in zig-wayland](https://github.com/ifreund/zig-wayland/blob/a336fec68db98a04d81b73f34be2f2bc4ec2d247/src/scanner.zig#L273-L283).

**Review by andrewrk — APPROVED** [review]
I'm happy with merging this as-is. Mind dealing with the conflict(s)?

**Pull request merged**
