### PR TITLE
Add std.debug.bruh

### PR DESCRIPTION
**Pull request by haze**
🧠

### CODE REVIEW

**Comment by watzon** [comment]
The PR we need, not the PR we deserve

**Comment by Jordin** [comment]
bruh

**Comment by hah** [comment]
https://www.youtube.com/watch?v=NzishIREebw

**Comment by except** [comment]
I think this a long awaited feature. I have not seen any other languages that support this.

**Comment by vlakreeh** [comment]
I don't think we can let zig hit 1.0 without this.

**Comment by half-cambodian-hacker-man** [comment]
What advantages does this have over the conventional solution?

For example, you're advising people to do this:

```zig
if (something_weird_happened) {
  std.debug.bruh();
}
```

But I'm currently happy with:

```zig
if (something_weird_happened) {
  const message = @embedFile("navy_seals_copypasta.txt");
  @panic(message);
}
```

**Comment by haze** [comment]
@half-cambodian-hacker-man the advantage is that we don't have to ship a 1.5kb copy pasta (which will also be embedded in your executables, `—release-small` would be sad)

**Comment by andrewrk** [comment]
Counter proposal, hear me out...

rename `unreachable` to `unreachabruh`

**Comment by except** [comment]
> Counter proposal, hear me out...
> 
> 
> 
> rename `unreachable` to `unreachabruh`

`unreachabruh` doesn't have the same impact as a good old `bruh moment`

**Comment by andrewrk** [comment]
ok i was going to click merge, but this cat was mad dogging me so i dont think i can sry
berlioz-staring

**Pull request closed without merging**
