### PR TITLE
Build: Add PIE option to addExecutable

### PR DESCRIPTION
**Pull request by xtexChooser**
As the title, a simple change.
Also added some test cases.

### CODE REVIEW

**Comment by nektro** [comment]
how does `.pie` differ from `.pic` ?

where is the code that connects it to the compiler to use this new option?

**Comment by mlugg** [comment]
This change does not do anything: the `pie` field is not observed anywhere.

**Comment by xtexChooser** [comment]
@mlugg @nektro
the `Compile.pie` has been here before this change, and https://github.com/ziglang/zig/blob/0884a434117dee3458eea8890b2e47e432844ac3/lib/std/Build/Step/Compile.zig#L1642 connects it to the linker. I was just adding a shortcut for specifying PIE flag in `Build.addExecutable`, but not adding a whole new flag.

**Comment by mlugg** [comment]
Apologies, I misread the diff here. The change makes more sense now.

That said, we don't aim to have an equivalent in `ExecutableOptions` etc for every field of `Step.Compile`; that's just unnecessary boilerplate. There are well over 50 fields on `Step.Compile`, and most of them are options that can be set post-creation: you should just do that.

**Pull request closed without merging**
