### PR TITLE
More translate-c fixes

### PR DESCRIPTION
**Pull request by LemonBoy**
* Translate OpaqueValueExpr
* Translate BinaryConditionalOperator
* Fix translation of boolean->int casts
* Reoder some tokens to avoid rendering errors

Fixes more stuff here and there, the boolean conversions are still messed up here and there so I'll give up for now.

### CODE REVIEW

**Comment by andrewrk** [comment]
That's my fault the failed test isn't telling you which one it is. Let me see if I can tweak that...

**Comment by LemonBoy** [comment]
> That's my fault the failed test isn't telling you which one it is. Let me see if I can tweak that...

Yeah, I don't even know what set of tests is failing nor why. I wonder if it's the use of `assert.h` in the tests...

**Comment by andrewrk** [comment]
I'm guessing you can reproduce with `zig translate-c -target x86_64-macos foo.c` on one of your new test cases, but yeah I'll improve the harness to be more clear about what's going on

**Comment by andrewrk** [comment]
Alright if you rebase to pick up 4e4ba6c3e1273fda8137f9f7e26325051f92bfa4 you'll get the annotated test case name and which step (translate-c, build-exe, run) it was doing that failed.

**Comment by andrewrk** [comment]
```
run-translated-c ternary operator build-exe...The following command exited with error code 1:
/Users/runner/runners/2.163.1/work/1/s/build/release/bin/zig build-exe zig-cache/o/7cCL-vYhfGJanTJRdqWvPJpTldG4cdMQN-Q1-3dddc2Qy29x5dmJURrcJVU1H6K2/source.zig --library c --cache-dir /Users/runner/runners/2.163.1/work/1/s/zig-cache --name translated_c --cache on 
```

so it's the run-translated-c test called "ternary operator", in the part where it runs `build-exe` on the translated c code.

**Pull request merged**
