### PR TITLE
Implement @externWeak builtin

### PR DESCRIPTION
**Pull request by LemonBoy**
This PR implements the proposal outlined in #1917

### CODE REVIEW

**Comment by LemonBoy** [comment]
> Messing with result locations is not needed to implement this feature:

If you don't take pointer types (thus making it impossible to ask for an `allowzero` pointer) then the result location can be avoided.

> The type parameter is not necessarily a pointer, it's the type of the symbol, and then @externWeak will give you an optional pointer to that type.

No strong preference on my end, if you feel it's better to just ask for a type I'll change the implementation accordingly.

**Comment by LemonBoy** [comment]
> No strong preference on my end, if you feel it's better to just ask for a type I'll change the implementation accordingly.

Oh, here's a possible advantage: you can easily ask for a `const` pointer without having to go trough a `ptrCast`. It's not much of a problem but that use case came to my mind while adjusting the patch.

**Comment by andrewrk** [comment]
@LemonBoy do you want to hand this one off to me? Otherwise I'm still open to reconsidering if you wanted to press the case for the other API you proposed.

**Comment by LemonBoy** [comment]
> @LemonBoy do you want to hand this one off to me? Otherwise I'm still open to reconsidering if you wanted to press the case for the other API you proposed.

I'm still torn about this, I really don't like how a builtin call (maybe hidden behind various layers of abstractions) has the same side effects of a global symbol declaration.

Wrt the API, I found this quote in the original proposal:
> PointerType could be any pointer type. The reason we supply the pointer type and not the element type is so that the default alignment can optionally be overridden by using a pointer type with an explicit alignment.
So it's something more to think about.

**Comment by andrewrk** [comment]
> I'm still torn about this, I really don't like how a builtin call (maybe hidden behind various layers of abstractions) has the same side effects of a global symbol declaration.
> 
> Wrt the API, I found this quote in the original proposal:

Makes sense.

Hmm. What about making it even more generic - `@extern` rather than `@externWeak` - and taking a struct of options, with defaults?

```zig
pub const ExternOptions = struct {
    /// If this is `GlobalLinkage.Weak`, `@extern` returns an optional pointer. Otherwise,
    /// it returns a non-optional pointer.
    linkage: GlobalLinkage = .Strong,
    is_const: bool = false,
    is_thread_local: bool = false,
    /// `null` means to use ABI alignment. Otherwise must be a non-zero power of two.
    alignment: ?u29 = null,
};
```

Yeah, thread local externs are a thing:

https://github.com/ziglang/zig/blob/b5ac079f88e9098ea9c95356518820a5c3fb42a8/lib/std/c/dragonfly.zig#L3

**Comment by andrewrk** [comment]
I added [this comment](https://github.com/ziglang/zig/issues/1917#issuecomment-587931922) so that this diff is not lost to the world, and I'm closing the PR since it's not merge-ready and hasn't seen any progress in over a month.

**Pull request closed without merging**
