### PR TITLE
ci: make directory structure in releases consistent

### PR DESCRIPTION
**Pull request by BratishkaErik**
Rebased https://github.com/ziglang/zig/pull/12611
Closes https://github.com/ziglang/zig/issues/9158

### CODE REVIEW

**Comment by BratishkaErik** [comment]
I'll fix CI failures when all checks will be completed.

**Comment by BratishkaErik** [comment]
Succesfully passed

**Comment by andrewrk** [comment]
Thank you, I will have a look at this now

**Comment by andrewrk** [comment]
Reverted in 3b2f0c3eeefa188e57cb1ee0874306f1d3734031 due to CI failures.

**Comment by BratishkaErik** [comment]
> Reverted in 3b2f0c3eeefa188e57cb1ee0874306f1d3734031 due to CI failures.

Looks like only Azure failed?

**Pull request merged**
