### PR TITLE
Move more startup code to std lib

### LINKED ISSUE #3793: Invalid source code crashes compiler rather than giving an error
typing a bit too fast, this minimal example crashed the compiler (syncd to commit f0d6447569e89a7b862da806a78da52d15160ef4 in master):

```zig
pub fn(main) void
}
```
replace `fn(main)` with `fn main()` fixed the issue but I was hoping for an error message instead :-)

Call stack:
```
Program received signal SIGSEGV, Segmentation fault.
add_source_file (g=g@entry=0x55555c30dd90, package=<optimized out>, resolved_path=resolved_path@entry=0x55555c332e30,
    source_code=source_code@entry=0x55555c3383c0, source_kind=source_kind@entry=SourceKindRoot) at /home/qbradley/src/zig/src/analyze.cpp:4806
(gdb) bt
#0  add_source_file (g=g@entry=0x55555c30dd90, package=<optimized out>, resolved_path=resolved_path@entry=0x55555c332e30,
    source_code=source_code@entry=0x55555c3383c0, source_kind=source_kind@entry=SourceKindRoot) at /home/qbradley/src/zig/src/analyze.cpp:4806
#1  0x0000555556338fcf in gen_root_source (g=g@entry=0x55555c30dd90) at /home/qbradley/src/zig/src/codegen.cpp:9223
#2  0x00005555563399e9 in codegen_build_and_link (g=0x55555c30dd90) at /home/qbradley/src/zig/src/codegen.cpp:10244
#3  0x000055555627c8e3 in main (argc=3, argv=0x7fffffffe458) at /home/qbradley/src/zig/src/main.cpp:1286
(gdb) list
4801                    assert(proto_node->type == NodeTypeFnProto);
4802                    Buf *proto_name = proto_node->data.fn_proto.name;
4803
4804                    bool is_pub = (proto_node->data.fn_proto.visib_mod == VisibModPub);
4805                    if (is_pub) {
4806                        if (buf_eql_str(proto_name, "main")) {
4807                            g->have_pub_main = true;
4808                        }
4809                    }
4810                }
(gdb) print proto_name
$1 = (Buf *) 0x0
```

### PR DESCRIPTION
**Pull request by Vexu**
Closes #3793.
Alternative to #3798 based on https://github.com/ziglang/zig/pull/3798#issuecomment-559902253.

Not sure how correct the windows related stuff is.

### CODE REVIEW

**Comment by Vexu** [comment]
Seems like weak linkage doesn't work.
```zig
extern fn a() u64 {
    return 2;
}

extern fn b() u64 {
    return 3;
}
comptime {
    @export("A", a, .Weak);
    @export("A", b, .Strong);
}

extern fn A() u64;
test "linkage" {
    if (A() != 3) unreachable;
}
```

**Comment by andrewrk** [comment]
I believe this error is correct, you can only export 1 same-named global symbol:

```
/home/andy/dev/zig/build/test.zig:10:5: error: exported symbol collision: 'A'
    @export("A", b, .Strong);
    ^
/home/andy/dev/zig/build/test.zig:9:5: note: other symbol is here
    @export("A", a, .Weak);
    ^
```

If you meant to do instead:

```zig
extern fn a() u64 {
    return 2;
}

extern fn b() u64 {
    return 3;
}
comptime {
    @export("A", a, .Weak);
    @export("B", b, .Strong);
}

extern fn A() u64;
test "linkage" {
    if (A() != 3) unreachable;
}

const std = @import("std");
pub fn panic(msg: []const u8, error_return_trace: ?*std.builtin.StackTrace) noreturn {
    @breakpoint();
    unreachable;
}
```

With `zig build-obj test.zig --verbose-llvm-ir --strip` this gives:

```llvm
; ModuleID = 'test'
source_filename = "test"
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

%"[]u8" = type { i8*, i64 }
%std.builtin.StackTrace = type { i64, %"[]usize" }
%"[]usize" = type { i64*, i64 }

@panic.1 = internal unnamed_addr constant void (%"[]u8"*, %std.builtin.StackTrace*)* @panic, align 8
@0 = internal unnamed_addr constant [25 x i8] c"reached unreachable code\00", align 1
@1 = internal unnamed_addr constant %"[]u8" { i8* getelementptr inbounds ([25 x i8], [25 x i8]* @0, i64 0, i64 0), i64 24 }, align 8

; Function Attrs: nobuiltin noreturn nounwind
define internal fastcc void @panic(%"[]u8"* nonnull readonly align 8, %std.builtin.StackTrace* align 8) unnamed_addr #0 {
Entry:
  %error_return_trace = alloca %std.builtin.StackTrace*, align 8
  store %std.builtin.StackTrace* %1, %std.builtin.StackTrace** %error_return_trace, align 8
  call void @llvm.debugtrap()
  call fastcc void @panic(%"[]u8"* @1, %std.builtin.StackTrace* null)
  unreachable
}

; Function Attrs: nounwind
declare void @llvm.debugtrap() #1

; Function Attrs: nobuiltin nounwind
define weak_odr i64 @A() #2 {
Entry:
  ret i64 2
}

; Function Attrs: nobuiltin nounwind
define i64 @B() #2 {
Entry:
  ret i64 3
}

attributes #0 = { nobuiltin noreturn nounwind "no-frame-pointer-elim"="true" "no-frame-pointer-elim-non-leaf" "probe-stack"="__zig_probe_stack" }
attributes #1 = { nounwind }
attributes #2 = { nobuiltin nounwind "no-frame-pointer-elim"="true" "no-frame-pointer-elim-non-leaf" "probe-stack"="__zig_probe_stack" }

!llvm.module.flags = !{!0, !1}
!llvm.dbg.cu = !{!2}

!0 = !{i32 2, !"Debug Info Version", i32 3}
!1 = !{i32 2, !"Dwarf Version", i32 4}
!2 = distinct !DICompileUnit(language: DW_LANG_C99, file: !3, producer: "zig 0.5.0", isOptimized: false, runtimeVersion: 0, emissionKind: NoDebug, enums: !4)
!3 = !DIFile(filename: "test", directory: ".")
!4 = !{}
```

We are in fact giving the weak_odr linkage to LLVM.

**Comment by emekoi** [comment]
i think he expected that the `@export("A", b, .Strong);` would override the previous `Weak` definition of `A.

**Comment by andrewrk** [comment]
Hmm. That makes sense if you think about it one way. Another way to think about it is that you are generating an object file, which is going to either not have A, have weak A, or have strong A, and there should only be 1 declarative place in the code that makes this decision. Happy to consider a proposal that makes this change.

**Comment by andrewrk** [comment]
Thanks! I'll take it from here

**Pull request closed without merging**
