### PR TITLE
stage1: don't filter test blocks with empty label

### PR DESCRIPTION
**Pull request by LemonBoy**
The common pattern of including a file containing all the tests in a
empty-label test block breaks down when using --test-filter.

### CODE REVIEW

**Comment by andrewrk** [comment]
Sounds good, although perhaps the language should recognize this usage pattern and allow omitting the string literal in the syntax?

**Comment by mikdusan** [comment]
```zig
usingtestspace {
}
usingtestspace "alt" {
}
```

**Comment by LemonBoy** [comment]
> Sounds good, although perhaps the language should recognize this usage pattern and allow omitting the string literal in the syntax?

Wouldn't that go against the "there's only one obvious way to do X" mantra?
`test { foo }` and `test "" { foo }` would be identical, unless we start limiting what's inside the test block... but that's not cool and a huge can of worms we can leave on the shelf IMO.

**Comment by andrewrk** [comment]
I'm suggesting that if you could omit the string literal, it would not be eligible for test filtering, and there would be no reason to ever do `test "" { foo }` (only omitting the string literal would make it exempt from test name filtering)

**Pull request merged**
