### PR TITLE
change `++` and `**` to not return mutable pointers

### PR DESCRIPTION
**Pull request by Rexicon226**
previously doing `++` or `**` with array-pointers, that being either `*[N]T ++ *[N]T` or `*[N]T ++ [N]T` the result value would be `*[N]T`. this violates Zig's principle of not allowing mutable references to temporary values. this PR changes these cases to return `*const [N]T`.

a bonus improvement is changing `*[N]T ++ *[N]T` to emit two `memcpy` AIR instructions instead of manually aggregating.

```diff
-%36 = alloc(*[4]u32)
-%37 = ptr_elem_ptr(*u32, %36, @Air.Inst.Ref.zero_usize)
-%38 = ptr_elem_ptr(*u32, %17!, @Air.Inst.Ref.zero_usize)
-%39 = load(u32, %38!)
-%40!= store(%37!, %39!)
-%41 = ptr_elem_ptr(*u32, %36, @Air.Inst.Ref.one_usize)
-%42 = ptr_elem_ptr(*u32, %27, @Air.Inst.Ref.zero_usize)
-%43 = load(u32, %42!)
-%44!= store(%41!, %43!)
-%45 = ptr_elem_ptr(*u32, %36, <usize, 2>)
-%46 = ptr_elem_ptr(*u32, %27, @Air.Inst.Ref.one_usize)
-%47 = load(u32, %46!)
-%48!= store(%45!, %47!)
-%49 = ptr_elem_ptr(*u32, %36, <usize, 3>)
-%50 = ptr_elem_ptr(*u32, %27!, <usize, 2>)
-%51 = load(u32, %50!)
-%52!= store(%49!, %51!)
+ %36 = alloc(*const [4]u32)
+ %37 = slice([]u32, %36, @Air.Inst.Ref.one_usize)
+ %38!= memcpy(%37!, %17!)
+ %39 = ptr_add([*]u32, %36, @Air.Inst.Ref.one_usize)
+ %40 = slice([]u32, %39!, <usize, 3>)
+ %41!= memcpy(%40!, %27!)
```

### CODE REVIEW

**Comment by N00byEdge** [comment]
Would close #8644

**Comment by andrewrk** [comment]
Great!

**Comment by jacobly0** [comment]
> ```diff
> + %36 = alloc(*const [4]u32)
> + %37 = slice([]u32, %36, @Air.Inst.Ref.one_usize)
> ```

The first operand to the `slice` instruction is required to match the slice ptr field type.  This invalid air is causing excess warnings in CBE generated code during CI runs, which will affect all bootstraps after the next zig1 update.

**Comment by mlugg** [comment]
Also, the `alloc` should be a `*[4]u32` (mutable), and later bitcast to a `*const [4]u32` for the result -- even in AIR you can't store to an immutable pointer (or at least, other parts of Sema emit `alloc`s with types based on that assumption).

**Comment by Rexicon226** [comment]
Ah interesting, understood. I didn't know that was a requirement! 
Could we add safety checks in the Liveness pass for this? Although, that pass isn't geared towards this.

Would AIR like this to fix the issues?
```
%36 = alloc(*[4]u32)
%37 = slice([]u32, %36, @Air.Inst.Ref.one_usize)
%38!= memcpy(%37!, %17!)
%39 = ptr_add([*]u32, %36, @Air.Inst.Ref.one_usize)
%40 = slice([]u32, %39!, <usize, 3>)
%41!= memcpy(%40!, %27!)
%42 = bitcast(*const [4]u32, %36!)
```

**Comment by mlugg** [comment]
The `alloc` instruction is still invalid because of Jacob's issue: you need to bitcast to a `[*]u32` first (`Type.slicePtrFieldType` of `[]u32`).

At some point we should probably take a closer look at AIR to redefine the exact constraints on instructions to take some load off Sema, but that's a task for another day.

**Comment by Rexicon226** [comment]
> The alloc instruction is still invalid because of Jacob's issue: you need to bitcast to a [*]u32 first

Ok so,
```
%36 = alloc(*[4]u32)
%37 = bitcast([*]u32, %36!)
%38 = slice([]u32, %37, @Air.Inst.Ref.one_usize)
%39!= memcpy(%38!, %17!)
%40 = ptr_add([*]u32, %37, @Air.Inst.Ref.one_usize)
%41 = slice([]u32, %40!, <usize, 3>)
%42!= memcpy(%41!, %27!)
%43 = bitcast(*const [4]u32, %37!)
```
?

**Comment by mlugg** [comment]
Sure, that seems about right.

**Pull request merged**
