### PR TITLE
gdb pretty printers for slices and optionals

### PR DESCRIPTION
**Pull request by xackus**

### CODE REVIEW

**Comment by daurnimator** [comment]
Oh wow, I didn't know this file existed.
Is it worth it for distros to package this up under /usr/share/gdb somewhere?

**Comment by xackus** [comment]
@daurnimator Seems like we can add a section to the executable to tell gdb to load a script: https://sourceware.org/gdb/onlinedocs/gdb/dotdebug_005fgdb_005fscripts-section.html
In that case, the stage1 printers should be extracted into a separate file. I kept them because I wanted to avoid breaking users' configs (at least until the current C++ stage1 is nuked).

**Comment by daurnimator** [comment]
> stage1 printers should be extracted into a separate file

This makes sense to me.

Could your additions go into a new file (that is useful for all zig users) that is imported from the existing one (which can remain for people working on the zig compiler?)

**Comment by xackus** [comment]
@daurnimator Looks like the best we can do is creating a `zig-gdb` script like rust did: https://github.com/rust-lang/rust/blob/master/src/etc/rust-gdb
I think the `.debug_gdb_scripts` section wasn't really intended for compilers because it only looks at the program's source code directory.
There is no way to make gdb load a script from `/usr/share/gdb/auto-load` except maybe hard-coding the absolute path in the binary.

**Comment by xackus** [comment]
This can be merged in its current state.

**Review by daurnimator — APPROVED** [review]

**Pull request merged**
