### PR TITLE
[priority_queue] Simplify sifting & fix edge case

### PR DESCRIPTION
**Pull request by Validark**
- Adds the overflow guard from https://github.com/ziglang/zig/pull/16127 to std.PriorityQueue.
- Simplified logic so that the algorithms only write the sifted item into heap memory once rather than log(`self.len`) times.
- Removes the copying of every item into the siftDown function's stack. This helps avoid a 2-3x slowdown (in my tests, obviously), particularly with complex structs. For the record I tried my tests with a variety of structs, integers, and with different amounts of code executed prior (to vary layout). I found that copying values to the stack can be marginally beneficial in some cases, but can lead to halving performance in other cases. I haven't looked at the assembly but I would guess it has to do with how many instructions are necessary to copy a value to the stack and/or whether it's even worth it to do so due to it already being a convenient size.

### CODE REVIEW

**Comment by andrewrk** [comment]
Can you provide a unit test to cover the new edge case that is fixed?

**Comment by Validark** [comment]
I am not sure that I know of a reasonable way to test it. The edge case is when `queue.len*2 > maxInt(usize)`, i.e. when the most significant bit in `queue.len` is set. It would require allocating at least `@as(usize, 1) << (@bitSizeOf(usize) - 1)` items. I doubt that is something you want to test on most hardware/architectures? It is admittedly a pretty unlikely/extreme edge case. I am not sure how necessary it is for Zig to support such extreme cases (without my `std.math.mul(usize, index, 2) catch break`, it could wrap-around and get stuck in an infinite loop).

Another alternative to having the check in the `siftDown` function would be to just disallow queues of that size, which seems reasonable. In that case, we could have a check or assertion in `fromOwnedSlice`/`ensureTotalCapacity`/`ensureUnusedCapacity`. Honestly, I am not sure how many of these cases of undefined behavior are valid "implicit contracts" that the programmer should understand implicitly versus how many should return an error.

E.g., what happens if I called `ensureUnusedCapacity` and overflowed `self.len + additional_count`? 

```zig
pub fn ensureUnusedCapacity(self: *Self, additional_count: usize) !void {
    return self.ensureTotalCapacity(self.len + additional_count);
}
```

Should that be an error or is the programmer expected to think about whether such an edge case is possible if they are able to run into such limits? I know on "typical" hardware environments it is highly improbable, and likely kinda your own fault if it happens (you'd have to pass maxInt or something very close to it into the function). However, it may be more possible to run into in 32-bit mode, and embedded applications might be at risk in odd situations. How should Zig approach situations like this?

**Comment by andrewrk** [comment]
> E.g., what happens if I called `ensureUnusedCapacity` and overflowed `self.len + additional_count`?

Instead of asserting no overflow, it should handle overflow by returning `error.OutOfMemory`.

**Comment by Validark** [comment]
I have been thinking about this more and I agree. I think libraries like this should provide the logic for what should happen if such things go wrong, and hopefully a sufficiently intelligent static analysis could optimize it out when the condition is impossible to meet.

**Pull request merged**
