### PR TITLE
cmake: separate installing and building (again)

### LINKED ISSUE #12722: Separate installing and building self-hosted compiler
Regressed since https://github.com/ziglang/zig/commit/e69973beddcd8a42dbc7ebcfb96187e5a6f61b61, this can be a problem for package maintainers, for example https://bugs.gentoo.org/867592:
> dev-lang/zig-9999: sandbox violation (tries to create /usr/lib/zig)

and https://aur.archlinux.org/packages/zig-git#comment-880012:
> With the latest changes to the Zig build process the PKGBUILD no longer works. Problem is that the "cmake --build build" attempts to write directly to /usr/lib. The last part of the build uses zig (stage2) and wants to use -DCMAKE_INSTALL_PREFIX=/usr as written when building stage3. This is the second version of this PKGBUILD.

https://github.com/ziglang/zig/blob/f7784a081fb399025b579ee7e1337a414af16d49/CMakeLists.txt#L1046-L1065

### PR DESCRIPTION
**Pull request by BratishkaErik**
Extracted from #12747
Closes #12722

### CODE REVIEW

**Comment by BratishkaErik** [comment]
Doesn't it just copies from cache to install prefix tho?

**Comment by andrewrk** [comment]
Hmm that's a fair point. I suppose instead of this I could enhance incremental cache mode to detect when there are no changes. Let me try that and get back to you...

**Comment by andrewrk** [comment]
Enhancing incremental compilation will be a sub-project in and of itself. For now I made self-hosted act closer to the behavior of stage1, which I think will be a satisfactory solution for the 0.10.0 release, and will allow us to merge this PR. See the commit that I force-pushed for more details.

**Comment by andrewrk** [comment]
Alright I solved the bug that was causing the Windows CI to fail. Hopefully it will pass now.

**Pull request merged**
