### PR TITLE
don't crash when can't evaluate comptime expression with inferred type

### PR DESCRIPTION
**Pull request by yujiri8**

### CODE REVIEW

**Comment by yujiri8** [comment]
While writing the test I noticed something weird: the error doesn't seem to be triggered if the declaration of `a` is moved into `main`.

**Review by Vexu — CHANGES_REQUESTED** [review]
This is not the correct fix, a note should never have `src == .unneeded` if the parent doesn't also have it.

The calls in `zirArrayInit` and `zirStructInit` should pass `.unneeded` as the first source and null as the second.
You could also add an assertion to `Module.errNoteNonLazy` to check for that requirement.

**Comment by yujiri8** [comment]
Hmm. I don't fully understand this solution, but it works and I've updated the PR. I tried to add the assertion `assert(src_loc.lazy != .unneeded)` to `errNoteNonLazy`, but this led to one of the other tests crashing:
```
zig build-obj wrong_pointer_coerced_to_pointer_to_opaque_{} Debug native: error: the following command terminated unexpectedly:
/home/yujiri/code/zig/build/stage3/bin/zig build-obj -fno-LLVM -fno-LLD /home/yujiri/code/zig/zig-cache/o/1bdb55daad5b126dd049ba4c270b593d/tmp.zig --cache-dir /home/yujiri/code/zig/zig-cache --global-cache-dir /home/yujiri/.cache/zig --name wrong_pointer_coerced_to_pointer_to_opaque_{} --listen=-
zig build-obj wrong_function_type Debug native: error: thread 26015 panic: reached unreachable code
Analyzing zig-cache/o/95685f4f1417d8383ba3ace3a1d4cda7/tmp.zig: tmp.zig:fns
      %2 = int(3)
      %3 = block_inline({
        %4 = func(ret_ty=@Zir.Inst.Ref.void_type, body={}) node_offset:1:16 to :1:25
        %5 = break_inline(%3, %4)
      }) node_offset:1:16 to :1:25
      %6 = array_type(%2, %3) node_offset:1:13 to :1:25
      %7 = decl_val("a") token_offset:1:28 to :1:29
      %8 = decl_val("b") token_offset:1:31 to :1:32
      %9 = decl_val("c") token_offset:1:34 to :1:35
    > %10 = array_init(%6{%7, %8, %9}) node_offset:1:13 to :1:37
      %11 = break_inline(%1, %10)
    For full context, use the command
      zig ast-check -t zig-cache/o/95685f4f1417d8383ba3ace3a1d4cda7/tmp.zig

  in zig-cache/o/95685f4f1417d8383ba3ace3a1d4cda7/tmp.zig: tmp.zig:entry
    > %68 = decl_val("fns") token_offset:5:50 to :5:53
  in zig-cache/o/95685f4f1417d8383ba3ace3a1d4cda7/tmp.zig: tmp.zig:entry
    > %67 = typeof_builtin({%68, %69}) node_offset:5:42 to :5:54
  in zig-cache/o/95685f4f1417d8383ba3ace3a1d4cda7/tmp.zig: tmp.zig:entry
    > %66 = block_comptime({%67, %70}) node_offset:5:42 to :5:54
  in zig-cache/o/95685f4f1417d8383ba3ace3a1d4cda7/tmp.zig: tmp.zig:entry
    > %62 = block({%63..%78}) node_offset:5:25 to :5:58

/home/yujiri/code/zig/lib/std/debug.zig:260:14: 0x41bae06 in assert (zig)
    if (!ok) unreachable; // assertion failure
             ^
/home/yujiri/code/zig/src/Module.zig:6024:11: 0x4f4c1d8 in errNoteNonLazy__anon_162529 (zig)
    assert(src_loc.lazy != .unneeded);
          ^
/home/yujiri/code/zig/src/Sema.zig:2142:30: 0x4a50a21 in errNote__anon_133407 (zig)
    return mod.errNoteNonLazy(src.toSrcLoc(src_decl), parent, format, args);
                             ^
/home/yujiri/code/zig/src/Sema.zig:26371:33: 0x4a4d81f in report (zig)
                try sema.errNote(block, src, msg, "return type '{}' cannot cast into return type '{}'", .{
                                ^
/home/yujiri/code/zig/src/Sema.zig:26095:36: 0x46b6516 in coerceExtra (zig)
        try in_memory_result.report(sema, block, inst_src, msg);
                                   ^
/home/yujiri/code/zig/src/Sema.zig:25397:28: 0x44b4ca4 in coerce (zig)
    return sema.coerceExtra(block, dest_ty_unresolved, inst, inst_src, .{}) catch |err| switch (err) {
                           ^
/home/yujiri/code/zig/src/Sema.zig:18150:39: 0x498a8c6 in zirArrayInit (zig)
        resolved_args[i] = sema.coerce(block, elem_ty, resolved_arg, .unneeded) catch |err| switch (err) {
                                      ^
/home/yujiri/code/zig/src/Sema.zig:1009:67: 0x4687844 in analyzeBodyInner (zig)
            .array_init                   => try sema.zirArrayInit(block, inst, false),
                                                                  ^
/home/yujiri/code/zig/src/Sema.zig:821:45: 0x44bc7e1 in analyzeBodyBreak (zig)
    const break_inst = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                                            ^
/home/yujiri/code/zig/src/Module.zig:4731:50: 0x44b893c in semaDecl (zig)
    const result_ref = (try sema.analyzeBodyBreak(&block_scope, body)).?.operand;
                                                 ^
/home/yujiri/code/zig/src/Module.zig:4250:32: 0x42eaa35 in ensureDeclAnalyzed (zig)
        break :blk mod.semaDecl(decl_index) catch |err| switch (err) {
                               ^
/home/yujiri/code/zig/src/Sema.zig:28954:32: 0x4eb0315 in ensureDeclAnalyzed (zig)
    sema.mod.ensureDeclAnalyzed(decl_index) catch |err| {
                               ^
/home/yujiri/code/zig/src/Sema.zig:29005:32: 0x4f37062 in analyzeDeclRefInner (zig)
    try sema.ensureDeclAnalyzed(decl_index);
                               ^
/home/yujiri/code/zig/src/Sema.zig:28924:50: 0x4e83987 in analyzeDeclVal (zig)
    const decl_ref = try sema.analyzeDeclRefInner(decl_index, false);
                                                 ^
/home/yujiri/code/zig/src/Sema.zig:6019:31: 0x4949406 in zirDeclVal (zig)
    return sema.analyzeDeclVal(block, src, decl);
                              ^
/home/yujiri/code/zig/src/Sema.zig:934:65: 0x46836be in analyzeBodyInner (zig)
            .decl_val                     => try sema.zirDeclVal(block, inst),
                                                                ^
/home/yujiri/code/zig/src/Sema.zig:821:45: 0x44bc7e1 in analyzeBodyBreak (zig)
    const break_inst = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                                            ^
/home/yujiri/code/zig/src/Sema.zig:770:50: 0x4e6b873 in resolveBody (zig)
    const break_data = (try sema.analyzeBodyBreak(block, body)) orelse
                                                 ^
/home/yujiri/code/zig/src/Sema.zig:16696:41: 0x498525a in zirTypeofBuiltin (zig)
    const operand = try sema.resolveBody(&child_block, body, inst);
                                        ^
/home/yujiri/code/zig/src/Sema.zig:1001:71: 0x4687139 in analyzeBodyInner (zig)
            .typeof_builtin               => try sema.zirTypeofBuiltin(block, inst),
                                                                      ^
/home/yujiri/code/zig/src/Sema.zig:821:45: 0x44bc7e1 in analyzeBodyBreak (zig)
    const break_inst = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                                            ^
/home/yujiri/code/zig/src/Sema.zig:770:50: 0x4e6b873 in resolveBody (zig)
    const break_data = (try sema.analyzeBodyBreak(block, body)) orelse
                                                 ^
/home/yujiri/code/zig/src/Sema.zig:5501:32: 0x4eaa8b8 in resolveBlockBody (zig)
        return sema.resolveBody(child_block, body, body_inst);
                               ^
/home/yujiri/code/zig/src/Sema.zig:5486:33: 0x4a0f64d in zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                ^
/home/yujiri/code/zig/src/Sema.zig:1461:49: 0x469698b in analyzeBodyInner (zig)
                    break :blk try sema.zirBlock(block, inst, tags[inst] == .block_comptime);
                                                ^
/home/yujiri/code/zig/src/Sema.zig:5503:34: 0x4eaa909 in resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
/home/yujiri/code/zig/src/Sema.zig:5486:33: 0x4a0f64d in zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                ^
/home/yujiri/code/zig/src/Sema.zig:1461:49: 0x469698b in analyzeBodyInner (zig)
                    break :blk try sema.zirBlock(block, inst, tags[inst] == .block_comptime);
                                                ^
/home/yujiri/code/zig/src/Sema.zig:804:30: 0x48eaae8 in analyzeBody (zig)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                             ^
/home/yujiri/code/zig/src/Module.zig:5753:21: 0x466994b in analyzeFnBody (zig)
    sema.analyzeBody(&inner_block, fn_info.body) catch |err| switch (err) {
                    ^
/home/yujiri/code/zig/src/Module.zig:4342:40: 0x449cd7e in ensureFuncBodyAnalyzed (zig)
            var air = mod.analyzeFnBody(func, sema_arena) catch |err| switch (err) {
                                       ^
/home/yujiri/code/zig/src/Compilation.zig:3134:42: 0x449ad73 in processOneJob (zig)
            module.ensureFuncBodyAnalyzed(func) catch |err| switch (err) {
                                         ^
/home/yujiri/code/zig/src/Compilation.zig:3071:30: 0x4346cae in performAllTheWork (zig)
            try processOneJob(comp, work_item, main_progress_node);
                             ^
/home/yujiri/code/zig/src/Compilation.zig:2026:31: 0x43433bf in update (zig)
    try comp.performAllTheWork(main_progress_node);
                              ^
/home/yujiri/code/zig/src/main.zig:3413:36: 0x436ec78 in serve (zig)
                    try comp.update(main_progress_node);
                                   ^
/home/yujiri/code/zig/src/main.zig:3227:22: 0x4209333 in buildOutputType (zig)
            try serve(
                     ^
/home/yujiri/code/zig/src/main.zig:273:31: 0x41bcf03 in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .{ .build = .Obj });
                              ^
/home/yujiri/code/zig/src/main.zig:213:20: 0x41ba285 in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/home/yujiri/code/zig/lib/std/start.zig:609:37: 0x41b9d08 in main (zig)
            const result = root.main() catch |err| {
                                    ^
???:?:?: 0x7fc6f442baac in ??? (???)
???:?:?: 0x7ffcb1844a9b in ??? (???)
```

**Comment by yujiri8** [comment]
Another thing I meant to ask about is why does the note `operation is runtime due to this operand` only appear with an inferred struct type? Is that also a bug?

**Comment by Vexu** [comment]
> Another thing I meant to ask about is why does the note `operation is runtime due to this operand` only appear with an inferred struct type? Is that also a bug?

`finishStructInit` doesn't pass a `runtime_src` to `requireRuntimeBlock` like `zirStructInitAnon` does. Not exactly a bug but more an unimplemented feature.

**Pull request merged**
