### PR TITLE
Fix segmentation fault on invalid enum field

### LINKED ISSUE #1079: Tricky enum leads to unclean exit
```
pub const VkResult = extern enum {
    VK_ERROR_OUT_OF_POOL_MEMORY_KHR = VkResult.VK_ERROR_OUT_OF_POOL_MEMORY,
    VK_ERROR_INVALID_EXTERNAL_HANDLE_KHR = VK_ERROR_INVALID_EXTERNAL_HANDLE,
};

pub fn main() void {
    var s : VkResult = VkResult.VK_SUCCESS;
}
```
That's as much as I can reduce it, of course it looks very strange at this point. Note the "VkResult.VK.." in the enum. I'm not expecting the enum to work.

The specific error I get is:

> The following command terminated unexpectedly: .... error: UncleanExit

### PR DESCRIPTION
**Pull request by isaachier**
Fixes #1079. Would add a test case, but not sure how to test that the compiler errors without a segfault.

### CODE REVIEW

**Comment by andrewrk** [comment]
You can add compile error tests in `test/compile_errors.zig` then run

`make install && bin/zig build --build-file ../build.zig test-compile-errors`

Feel free to put your new test at the top, so it runs first.

**Comment by andrewrk** [comment]
I'm not convinced this is the best solution though. Let me take a look.

**Comment by isaachier** [comment]
Sure. Keep in mind the example in #1079 is intentionally malformed. But I'm guessing you already knew that :).

**Comment by isaachier** [comment]
Withdrawn. Glad you found a solution.

**Pull request closed without merging**
