### PR TITLE
stage2: fix handling of aggregates with mixed comptime-only fields

### PR DESCRIPTION
**Pull request by andrewrk**

### CODE REVIEW

**Comment by andrewrk** [comment]
@Luukdegram would you be willing to help me diagnose this?

```
compiler [29/1144] binary_operands (stage2, wasm32-wasi) [4/26] update [2/3] parse/analysis/cod... thread 131039 panic: index out of bounds
/workspace/src/link/Dwarf.zig:1910:16: 0x59c1ea in link.Dwarf.writeDbgInfoNopsBuffered (test)
            buf[offset + content.len + padding_left] = @enumToInt(AbbrevKind.pad1);
               ^
/workspace/src/link/Dwarf.zig:1144:49: 0x591511 in link.Dwarf.updateDeclDebugInfoAllocation (test)
                        writeDbgInfoNopsBuffered(wasm_file.debug_info.items, atom.off, 0, &.{0}, atom.len, false);
                                                ^
/workspace/src/link/Dwarf.zig:1040:43: 0x704d1c in link.Dwarf.commitDeclState (test)
    try self.updateDeclDebugInfoAllocation(file, atom, @intCast(u32, dbg_info_buffer.items.len));
                                          ^
/workspace/src/link/Wasm.zig:590:34: 0x7e97a7 in link.Wasm.updateFunc (test)
        try dwarf.commitDeclState(
                                 ^
/workspace/src/link.zig:472:77: 0x6d0b1d in link.File.updateFunc (test)
            .wasm  => return @fieldParentPtr(Wasm,  "base", base).updateFunc(module, func, air, liveness),
                                                                            ^
/workspace/src/Module.zig:3767:41: 0x6c9b54 in Module.ensureFuncBodyAnalyzed (test)
            mod.comp.bin_file.updateFunc(mod, func, air, liveness) catch |err| switch (err) {
                                        ^
/workspace/src/Compilation.zig:2792:42: 0x550827 in Compilation.processOneJob (test)
            module.ensureFuncBodyAnalyzed(func) catch |err| switch (err) {
                                         ^
/workspace/src/Compilation.zig:2734:30: 0x53e46b in Compilation.performAllTheWork (test)
            try processOneJob(comp, work_item);
                             ^
/workspace/src/Compilation.zig:2120:31: 0x4e0256 in Compilation.update (test)
    try comp.performAllTheWork(main_progress_node);
                              ^
/workspace/src/test.zig:1521:28: 0x4caad0 in TestContext.runOneCase (test)
            try comp.update();
                           ^
/workspace/src/test.zig:1236:23: 0x4bcff3 in TestContext.run (test)
            runOneCase(
                      ^
/workspace/src/test.zig:50:16: 0x49a14c in test "" (test)
    try ctx.run();
               ^
/workspace/_debug/staging/lib/zig/test_runner.zig:79:28: 0x9f03bc in (root).main (test)
        } else test_fn.func();
                           ^
/workspace/_debug/staging/lib/zig/std/start.zig:571:22: 0x88476c in std.start.callMain (test)
            root.main();
                     ^
/workspace/_debug/staging/lib/zig/std/start.zig:515:12: 0x686cce in std.start.callMainWithArgs (test)
    return @call(.{ .modifier = .always_inline }, callMain, .{});
           ^
/workspace/_debug/staging/lib/zig/std/start.zig:425:17: 0x4bd926 in std.start.posixCallMainAndExit (test)
    std.os.exit(@call(.{ .modifier = .always_inline }, callMainWithArgs, .{ argc, argv, envp }));
                ^
/workspace/_debug/staging/lib/zig/std/start.zig:338:5: 0x4bd732 in std.start._start (test)
    @call(.{ .modifier = .never_inline }, posixCallMainAndExit, .{});
    ^
error: the following test command crashed:
/workspace/zig-cache/o/49a61cbe037d8c1a63fe3c4e776200b9/test /workspace/_debug/staging/bin/zig
```

The problem is on update index 3 of binary_operands. It does not reproduce without an incremental compilation, however, I can reproduce it with only 1 update. Start with this file:

```zig
pub fn main() void {
    var i: i4 = 7;
    if (i +% 1 != -8) unreachable;
    return;
}
```

Build with `zig build-exe test.zig -fno-LLVM -target wasm32-wasi --watch`. Then update the file to:

```zig
pub fn main() u8 {
    var i: u8 = 255;
    return i +% 1;
}
```

Then give an "update" command to the Zig REPL.

I'll keep looking into it myself, but thought I'd ask for your help in case I can't figure it out.

**Comment by andrewrk** [comment]
Ah, I think I have it sorted out. I understand what this function is doing now.

**Comment by andrewrk** [comment]
OK I think I figured this out. The function `writeDbgInfoNopsBuffered` is based on the function `pwriteDbgInfoNops`, originally written by me, and then modified to write to a memory buffer instead of an open file. When writing to a file, any extra bytes beyond the end of the file extend the size of the file, and the function body of `pwriteDbgInfoNops` takes advantage of this when `next_padding_bytes` extends beyond the end of the file. However, when writing to a memory buffer, the underlying array list must be expanded if the write would cause the buffer to expand.

**Comment by andrewrk** [comment]
Fix pushed :slightly_smiling_face:

**Comment by kubkon** [comment]
> OK I think I figured this out. The function `writeDbgInfoNopsBuffered` is based on the function `pwriteDbgInfoNops`, originally written by me, and then modified to write to a memory buffer instead of an open file. When writing to a file, any extra bytes beyond the end of the file extend the size of the file, and the function body of `pwriteDbgInfoNops` takes advantage of this when `next_padding_bytes` causes the write to go beyond the end of the file. However, when writing to a memory buffer, the underlying array list must be expanded if the write would cause the buffer to expand.

NIce! Thanks for the fix @andrewrk!

**Comment by Luukdegram** [comment]
Thank you for the fix Andrew.

**Pull request merged**
