### PR TITLE
fmt.parseWithSign(): prevent edge case overflows

### LINKED ISSUE #18157: fmt.parseInt() overflows in edge-cases when it shouldn't
### Zig Version

0.12.0-dev.1717+54f4abae2

### Steps to Reproduce and Observed Behavior

The following test should pass but it doesn't.  This happens because base (2,8,16) overflows T (i2, i4, i5).
```zig
// /tmp/tmp.zig
test {
    try std.testing.expectEqual(@as(i2, -2), try std.fmt.parseInt(i2, "-10", 2));
    try std.testing.expectEqual(@as(i4, -8), try std.fmt.parseInt(i4, "-10", 8));
    try std.testing.expectEqual(@as(i5, -16), try std.fmt.parseInt(i5, "-10", 16));
}
```

```console
~/.../zig/zig $ zig test /tmp/tmp.zig 
Test [1/1] test_0... FAIL (Overflow)
/home/travis/dev/zig/zig/download/0.12.0-dev.1717+54f4abae2/files/lib/std/fmt.zig:1841:66: 0x225ca3 in parseWithSign__anon_1133 (test)
            x = try math.mul(T, x, math.cast(T, buf_base) orelse return error.Overflow);
                                                                 ^
/home/travis/dev/zig/zig/download/0.12.0-dev.1717+54f4abae2/files/lib/std/fmt.zig:1735:24: 0x224284 in parseInt__anon_1122 (test)
    if (buf[0] == '-') return parseWithSign(T, buf[1..], base, .neg);
                       ^
/tmp/tmp.zig:4:46: 0x223e74 in test_0 (test)
    try std.testing.expectEqual(@as(i2, -2), try std.fmt.parseInt(i2, "-10", 2));

```

I have a fix which I'll to PR for this shortly...

### Expected Behavior

the test should pass

### PR DESCRIPTION
**Pull request by travisstaloch**
previously when T was smaller than 8 bits, it was possible for base to overflow T (because base is a u8).  this patch prevents this by accumulating into a U rather than T which is at least 8 bits wide.

this is the best way i could think of to maintain performance.  this will only affect parsing of integers less than 8 bits by adding one additional cast at return.  additionally, this patch may be slightly slower to return an error for integers less than 8 bits which overflow because it will accumulate a few more digits before the overflow check at return.

* add tests which previously overflowed when they shouldn't have

closes #18157

NOTE: i'll post a perf comparison shortly.

### CODE REVIEW

**Comment by travisstaloch** [comment]
Looks like patch this is between 3-8% slower depending on opt level compared to status-quo.  the benchmark is a script i previously made which parses 1000 random numbers stored in a file, each with a random type (signed and unsigned between 0..128 bits)  and base (2, 8, 10, or 16).

Let me know and I can post the file and script if anyone wants to see or use it.

Here are the comparisons separated by opt level.
```console
$ ./bench.sh 
--- Debug ---
Benchmark 1 (3 runs): zig-out/bin/number-parsing-std
  measurement          mean ± σ            min … max           outliers         delta
  wall_time          1.99s  ± 17.9ms    1.97s  … 2.01s           0 ( 0%)        0%
  peak_rss           1.18MB ±    0      1.18MB … 1.18MB          0 ( 0%)        0%
  cpu_cycles         9.20G  ± 73.3M     9.15G  … 9.28G           0 ( 0%)        0%
  instructions       13.2G  ±  190      13.2G  … 13.2G           0 ( 0%)        0%
  cache_references   15.4M  ±  497K     14.9M  … 15.9M           0 ( 0%)        0%
  cache_misses       6.63M  ±  157K     6.53M  … 6.81M           0 ( 0%)        0%
  branch_misses      4.77M  ± 55.9K     4.73M  … 4.84M           0 ( 0%)        0%
Benchmark 2 (3 runs): zig-out/bin/number-parsing
  measurement          mean ± σ            min … max           outliers         delta
  wall_time          2.05s  ± 6.83ms    2.04s  … 2.06s           0 ( 0%)        💩+  3.4% ±  1.5%
  peak_rss           1.57MB ±    0      1.57MB … 1.57MB          0 ( 0%)        💩+ 33.3% ±  0.0%
  cpu_cycles         9.50G  ± 28.8M     9.47G  … 9.53G           0 ( 0%)        💩+  3.3% ±  1.4%
  instructions       13.2G  ±  193      13.2G  … 13.2G           0 ( 0%)          -  0.0% ±  0.0%
  cache_references   30.8M  ± 1.51M     29.0M  … 31.9M           0 ( 0%)        💩+100.0% ± 16.6%
  cache_misses       14.1M  ± 35.2K     14.0M  … 14.1M           0 ( 0%)        💩+112.0% ±  3.9%
  branch_misses      7.76M  ± 63.0K     7.70M  … 7.83M           0 ( 0%)        💩+ 62.5% ±  2.8%
--- ReleaseSafe ---
Benchmark 1 (23 runs): zig-out/bin/number-parsing-std
  measurement          mean ± σ            min … max           outliers         delta
  wall_time           223ms ± 1.22ms     221ms …  225ms          0 ( 0%)        0%
  peak_rss            881KB ±    0       881KB …  881KB          0 ( 0%)        0%
  cpu_cycles         1.02G  ± 5.07M     1.01G  … 1.03G           0 ( 0%)        0%
  instructions       2.49G  ± 18.3      2.49G  … 2.49G           0 ( 0%)        0%
  cache_references   2.09M  ± 14.9K     2.04M  … 2.11M           1 ( 4%)        0%
  cache_misses       36.7K  ± 10.7K     24.7K  … 57.5K           0 ( 0%)        0%
  branch_misses      2.82M  ± 18.0K     2.80M  … 2.85M           0 ( 0%)        0%
Benchmark 2 (22 runs): zig-out/bin/number-parsing
  measurement          mean ± σ            min … max           outliers         delta
  wall_time           228ms ± 1.14ms     226ms …  230ms          0 ( 0%)        💩+  2.3% ±  0.3%
  peak_rss            909KB ±    0       909KB …  909KB          0 ( 0%)        💩+  3.3% ±  0.0%
  cpu_cycles         1.04G  ± 4.97M     1.03G  … 1.05G           0 ( 0%)        💩+  2.3% ±  0.3%
  instructions       2.48G  ± 17.1      2.48G  … 2.48G           0 ( 0%)          -  0.5% ±  0.0%
  cache_references   3.43M  ± 22.2K     3.37M  … 3.46M           1 ( 5%)        💩+ 64.3% ±  0.5%
  cache_misses        115K  ± 27.9K     84.0K  …  163K           0 ( 0%)        💩+211.8% ± 34.4%
  branch_misses      3.82M  ± 21.9K     3.78M  … 3.86M           0 ( 0%)        💩+ 35.3% ±  0.4%
--- ReleaseSmall ---
Benchmark 1 (20 runs): zig-out/bin/number-parsing-std
  measurement          mean ± σ            min … max           outliers         delta
  wall_time           251ms ±  592us     250ms …  252ms          0 ( 0%)        0%
  peak_rss            881KB ±    0       881KB …  881KB          0 ( 0%)        0%
  cpu_cycles         1.15G  ± 2.32M     1.15G  … 1.16G           1 ( 5%)        0%
  instructions       3.64G  ± 19.1      3.64G  … 3.64G           0 ( 0%)        0%
  cache_references   1.64M  ± 22.4K     1.60M  … 1.69M           0 ( 0%)        0%
  cache_misses       47.4K  ± 25.6K     24.1K  …  131K           1 ( 5%)        0%
  branch_misses      2.88M  ± 29.5K     2.85M  … 2.98M           1 ( 5%)        0%
Benchmark 2 (19 runs): zig-out/bin/number-parsing
  measurement          mean ± σ            min … max           outliers         delta
  wall_time           270ms ±  603us     269ms …  271ms          0 ( 0%)        💩+  7.4% ±  0.2%
  peak_rss            909KB ±    0       909KB …  909KB          0 ( 0%)        💩+  3.3% ±  0.0%
  cpu_cycles         1.24G  ± 2.12M     1.23G  … 1.24G           2 (11%)        💩+  7.5% ±  0.1%
  instructions       3.81G  ± 18.6      3.81G  … 3.81G           0 ( 0%)        💩+  4.7% ±  0.0%
  cache_references   3.41M  ± 25.2K     3.37M  … 3.48M           0 ( 0%)        💩+108.5% ±  1.0%
  cache_misses        102K  ± 34.1K     58.8K  …  164K           0 ( 0%)        💩+114.6% ± 41.5%
  branch_misses      3.63M  ± 20.4K     3.60M  … 3.66M           0 ( 0%)        💩+ 25.9% ±  0.6%
--- ReleaseFast ---
Benchmark 1 (24 runs): zig-out/bin/number-parsing-std
  measurement          mean ± σ            min … max           outliers         delta
  wall_time           212ms ± 1.33ms     209ms …  214ms          0 ( 0%)        0%
  peak_rss            881KB ±    0       881KB …  881KB          0 ( 0%)        0%
  cpu_cycles          966M  ± 6.12M      955M  …  974M           0 ( 0%)        0%
  instructions       2.19G  ± 15.3      2.19G  … 2.19G           0 ( 0%)        0%
  cache_references   2.09M  ± 8.72K     2.08M  … 2.11M           0 ( 0%)        0%
  cache_misses       29.0K  ± 7.46K     21.6K  … 50.6K           1 ( 4%)        0%
  branch_misses      2.88M  ± 15.2K     2.87M  … 2.92M           0 ( 0%)        0%
Benchmark 2 (23 runs): zig-out/bin/number-parsing
  measurement          mean ± σ            min … max           outliers         delta
  wall_time           217ms ± 1.48ms     216ms …  220ms          0 ( 0%)        💩+  2.7% ±  0.4%
  peak_rss            909KB ±    0       909KB …  909KB          0 ( 0%)        💩+  3.3% ±  0.0%
  cpu_cycles          992M  ± 7.19M      983M  … 1.00G           0 ( 0%)        💩+  2.7% ±  0.4%
  instructions       2.19G  ± 16.8      2.19G  … 2.19G           0 ( 0%)          -  0.1% ±  0.0%
  cache_references   3.16M  ± 21.2K     3.13M  … 3.20M           0 ( 0%)        💩+ 50.9% ±  0.5%
  cache_misses       88.1K  ± 34.6K     46.5K  …  186K           0 ( 0%)        💩+204.3% ± 50.5%
  branch_misses      3.73M  ± 35.5K     3.68M  … 3.85M           1 ( 4%)        💩+ 29.2% ±  0.6%
```

**Comment by travisstaloch** [comment]
i've created a repo w/ my benchmark code here https://github.com/travisstaloch/number-parsing-bench

you can run it with: `./bench.sh`

hopefully you'll only need to change the path to `poop` in that file or maybe adjust the command to use something else like hyperfine

**Comment by Rexicon226** [comment]
benchmarked myself and found no performance loss or gain. all within margins.

**Comment by travisstaloch** [comment]
I just ran it again using and its much closer, ranging from 2.6 slower in Debug to 9.2 faster in ReleaseSmall.

**Comment by N00byEdge** [comment]
don't you need 9 bits if you're making it the same signedness as the target type (possibly signed) to fit 8 unsigned bits?

**Comment by travisstaloch** [comment]
> don't you need 9 bits if you're making it the same signedness as the target type (possibly signed) while still fitting 8 unsigned bits?

i think i know what you mean.  are you saying that this will also false-negative overflow for signed ints when base is greater than 127?

**Comment by N00byEdge** [comment]
> > don't you need 9 bits if you're making it the same signedness as the target type (possibly signed) while still fitting 8 unsigned bits?
> 
> i think i know what you mean. are you saying that this will also false-negative overflow for signed ints when base is greater than 127?

Yeah, that is what I am worried about.

**Comment by travisstaloch** [comment]
i agree.  but was under the impression that only bases from 2..36 are supported.

**Comment by travisstaloch** [comment]
i adjusted the benchmark code to read/write the expected int to/from the file with similar results. here are just the wall times:
```console
--- Debug ---
...
Benchmark 2 (4 runs): zig-out/bin/number-parsing
  measurement          mean ± σ            min … max           outliers         delta
  wall_time          1.51s  ± 4.26ms    1.51s  … 1.52s           0 ( 0%)        💩+  2.1% ±  0.6%
...
--- ReleaseSafe ---
...
Benchmark 2 (35 runs): zig-out/bin/number-parsing
  measurement          mean ± σ            min … max           outliers         delta
  wall_time           146ms ±  917us     145ms …  147ms          0 ( 0%)          +  0.0% ±  0.3%
...
--- ReleaseSmall ---
...
Benchmark 2 (27 runs): zig-out/bin/number-parsing
  measurement          mean ± σ            min … max           outliers         delta
  wall_time           189ms ± 5.58ms     186ms …  210ms          5 (19%)          +  2.2% ±  1.3%
...
--- ReleaseFast ---
...
Benchmark 2 (44 runs): zig-out/bin/number-parsing
  measurement          mean ± σ            min … max           outliers         delta
  wall_time           116ms ± 1.62ms     114ms …  124ms          1 ( 2%)          -  0.2% ±  0.5%
...
```

**Comment by travisstaloch** [comment]
> don't you need 9 bits if you're making it the same signedness as the target type (possibly signed) while still fitting 8 unsigned bits?

I am not sure whether it is necessary to support bases larger than 127 and so will wait for review input.

**Review by Vexu — APPROVED** [review]
`charToDigit` is only valid for `0-Z` so `u8` should be enough.

**Comment by N00byEdge** [comment]
so `"10"` in base 128 (aka value 128) should not be valid?

**Comment by travisstaloch** [comment]
> so `"10"` in base 128 (aka value 128) should not be valid?

i think you have a good point, parseInt() and friends don't reject invalid bases such as 128 and charToDigit() can't handle any base above 36.  i honestly don't know whether this is a bug or a feature.

but it seems like this should be discussed in another issue.  the purpose of this pr, from my perspective, was just to make some valid inputs (signed "-10" with bases 2, 8, 16) not incorrectly return error.Overflow.

**Pull request merged**
