### PR TITLE
std.fmt: fix unecessary deref on user-defined format function

### LINKED ISSUE #15335: format() is a foot-gun when used with pointers (segfault)
### Zig Version

0.11.0-dev.2317+46b2f1f70

### Steps to Reproduce and Observed Behavior

Here's repro - I hope I haven't messed up anything else, because it was originally in a different code.

```
const std = @import("std");

const Animal = extern struct {
    kind: enum(usize) { cat, dog },

    pub fn format(self: *const Animal, comptime _: []const u8, _: std.fmt.FormatOptions, writer: anytype) !void {
        switch (self.kind) {
            .cat => @panic("not implemented"),
            .dog => try writer.print("{}", .{@ptrCast(*const Dog, self)}),
        }
    }
};

const Dog = extern struct {
    base: Animal,
    name: [*:0]const u8,

    pub fn format(self: *const Dog, comptime _: []const u8, _: std.fmt.FormatOptions, writer: anytype) !void {
        try writer.print("Dog {s}", .{self.name});
    }
};

pub fn main() void {
    var dog = std.heap.c_allocator.create(Dog) catch unreachable;
    dog.* = Dog{ .base = Animal{ .kind = .dog }, .name = "Ziggy" };

    // this works fine, but only because it's *Dog
    std.debug.print("{}\n", .{dog});

    // this should still work, but it segfaults
    var animal = &dog.base;
    std.debug.print("{}\n", .{animal});
}
```

The problem here is that `std.fmt.formatType()` dereferences the value before calling `val.format()` which will turn it into `*const T`, and then the polymorphic of course `@ptrCast` cannot work, because it's a pointer to a copy of `Animal`, not the whole `Dog`.

The problem is that all of this was completely not obvious, and I was not getting any meaningful errors along the way.

Also, I'd argue (but this is subjective) that it should be possible to format pointer types, without making a copy.

image

### Expected Behavior

- It should not segfault.
- (Optional) There should be a way to provide `format()` for pointer types. Currently, it only works for `*const` pointers, and it's just by accident because it's not using the original pointer at all.

### PR DESCRIPTION
**Pull request by iceghost**
When formatting a pointer to user type, currently it needs to be dereferenced first, then call `formatType` on the child type, only then the user-defined `format` function is found and called. This is troublesome when you need to format something that needs stable addresses, for example, self-referencing structs.

This fixes the problem by checking for the "format" function on the type itself and the struct it points to.

Fixes #15335.

### CODE REVIEW

**Comment by iceghost** [comment]
I think this is trivial, but I'm willing to add some tests if necessary.

**Comment by Vexu** [comment]
`meta.trait` has been removed so this will need to be rewritten.

**Comment by iceghost** [comment]
@Vexu Alright, I rewrote the PR. Can you reopen this, or should I open another one?

**Comment by Vexu** [comment]
Make a new one, I can't reopen this for some reason.

**Pull request closed without merging**
