### PR TITLE
std.crypto: Expose y-parity on ECDSA Signatures

### PR DESCRIPTION
**Pull request by except**
Hello,

I had trouble with this and was wondering if it was okay to expose this @jedisct1?

Thanks

### CODE REVIEW

**Comment by jedisct1** [comment]
That boolean would be set only when creating a signature, and be left uninitialized everywhere else.

This is not great. 

I'm a little bit confused about the problem you are trying to solve, here. When creating a signature, the secret key is known, and the public key can already be recovered with `KeyPair.fromSecretKey()`.

**Comment by jedisct1** [comment]
We can add a generic function to recover the 2 possible public keys from an ECDSA `Signature`.

But does Bitcoin actually allow the Y sign to be safely encoded, independently from the signature? 

If we have both possible keys, would it be impossible to check which one is the original one?

**Comment by except** [comment]
I thought that isn't a problem because the it's only in the Signature struct?

The reason I want this value is explained well in the below issue. I am not a cryptography expert so do forgive me.

https://bitcoin.stackexchange.com/questions/38351/ecdsa-v-r-s-what-is-v/38909#38909

**Comment by jedisct1** [comment]
The `Signature` struct is public. So this leaving members uninitialized is an issue. This is likely to break all other functions. This is also semantically incorrect, as this information is not part of ECDSA signatures.

It could be a different signature function, that returns the `recid` (rather than the sign) in addition to the signature.

**Comment by except** [comment]
> The `Signature` struct is public. So leaving members uninitialized is an issue. This is likely to break all other functions. This is also semantically incorrect, as this information is not part of ECDSA signatures.
> 
> 
> 

I just realised this, whoops.

> It could be a different signature function, that returns the `recid` (rather than the sign) in addition to the signature. 
> 
> 
> 
> 

I think this is a good plan, and possibly a verify function which takes in the `recid` and returns the correct public key instead of returning both?

**Comment by jedisct1** [comment]
Tests are still passing. But this is by accident because we're not testing `Signature.fromBytes()`, and `fromDer()` is zeroing the entire struct. So `is_y_odd` ends up being always `false` even if would be expected to be `true`.

**Comment by except** [comment]
I started some work on this [here](https://github.com/except/zig/commit/c79f7143f22b81ca25e1a3aca77df293184ab54f), but I want your opinion if I am approaching it correctly .

I had an issue though because I am working on it for some Ethereum related project. I don't know if I am returning the correct `recovery_id`.

I have find some more understandable code [here which shows the calculation](https://github.com/RustCrypto/signatures/blob/2c3d90ed6f4f0052e76d66f6f61a4a0ec838bfc2/ecdsa/src/recovery.rs#L61) and [here shows the implementation](https://github.com/RustCrypto/signatures/blob/2c3d90ed6f4f0052e76d66f6f61a4a0ec838bfc2/ecdsa/src/hazmat.rs#L105). My understanding is the `is_x_reduced` does not apply here? Or have I wrongly assumed?

Thanks

> We can add a generic function to recover the 2 possible public keys from an ECDSA `Signature`.
> 

Is there something in the codebase I can go off of to work this out?

**Comment by jedisct1** [comment]
Untested, but something like that: https://gist.github.com/jedisct1/40e4d4d82af831bc13ffa4cee792856f

**Comment by except** [comment]
> Untested, but something like that: https://gist.github.com/jedisct1/40e4d4d82af831bc13ffa4cee792856f

Thanks, this works as expected based on my very limited testing. Looking at `libsecp256k1` for test vectors (although their recovery tests are limited), it seems like we need that a way of recovering public keys which unfortunately I cannot implement.

**Comment by jedisct1** [comment]
Ok, let's close this PR the, since this is still a work in progress.

I'll open another one with the proposed changes from the gist and the ability to recover keys from ECDSA signatures, with or without the `recid`.

**Comment by except** [comment]
> Ok, let's close this PR the, since this is still a work in progress.
> 
> I'll open another one with the proposed changes from the gist and the ability to recover keys from ECDSA signatures, with or without the `recid`.

Is there any chance this is being added soon?

**Pull request closed without merging**
