### PR TITLE
std: add json parsing option to skip unknown fields

### PR DESCRIPTION
**Pull request by daurnimator**
Requested by @Sobeston. 

I had to have the user pass in a buffer via `ParseOptions` to use for tracking the ignored state

### CODE REVIEW

**Comment by zigazeljko** [comment]
Why is this `unknown_field_buffer` necessary? For skipping over fields in properly nested json you only need a single integer for tracking the current nesting level. And the `StreamingParser` already checks that the json is properly nested (via the `stack` field).

**Comment by daurnimator** [comment]
> Why is this `unknown_field_buffer` necessary? For skipping over fields in properly nested json you only need a single integer for tracking the current nesting level. And the `StreamingParser` already checks that the json is properly nested (via the `stack` field).

You need to verify that the json is well formed as you ignore things: you need to track if you are expecting a brace vs square brackets, and in which order e.g. `]]]]}]]}}}}}]]]` vs `}]]}]}}]]]}]]]]`

**Comment by daurnimator** [comment]
> > And the `StreamingParser` already checks that the json is properly nested (via the `stack` field).
> 
> ah ha! I didn't know about this field.

Trying to rewrite this PR, the detection for this in StreamingParser doesn't seem to work correctly?
```zig

test "mismatched close" {
    var p = TokenStream.init("[102, 111, 111}");
    checkNext(&p, .ArrayBegin);
    checkNext(&p, .Number);
    checkNext(&p, .Number);
    checkNext(&p, .Number);
    testing.expectError(error.UnexpectedClosingBracket, p.next());
}
```
I get:
```
.expected error.UnexpectedClosingBracket, found Token{ .ObjectEnd = void }
```

**Comment by zigazeljko** [comment]
The detection for this is implemented here:

https://github.com/ziglang/zig/blob/75a720565bb72e7fab03346df6a35e9a8f380962/lib/std/json.zig#L372-L374
https://github.com/ziglang/zig/blob/75a720565bb72e7fab03346df6a35e9a8f380962/lib/std/json.zig#L398-L400

Closing brackets are handled in both the `ValueBegin` and `ValueEnd` states, but this check is missing from the latter. Copying those two checks to `ValueEnd` state should fix it.

**Comment by daurnimator** [comment]
converted to draft while I refactor to try to do #5959 at the same time.

**Comment by andrewrk** [comment]
Draft since july

**Pull request closed without merging**
