### PR TITLE
Stage2 runtime safety progress

### LINKED ISSUE #12049: stage2: comptime fields are not always checked for equality when initialized
### Zig Version

0.10.0-dev.2882+556f12174

### Steps to Reproduce

This fails as expected:
```zig
test {
    const T = struct {
        comptime x: i32 = 0,
        comptime y: u8 = 123,
    };
    var a: T = .{.x = -1234, .y = 0};
    _ = a;
}
```

However, both of these currently compile when they should not:

```zig
pub const U = struct {
    comptime foo: u32 = 1,
    bar: u32,
};
fn foo(x: U) void {
    _ = x;
}
test {
    _ = foo(U{ .foo = 2, .bar = 2 });
}
```

```zig
test {
    var x: u32 = 15;
    const T = @TypeOf(.{ @as(i32, -1234), @as(u32, 5678), x });
    var a: T = .{ -1234, 5678, x + 1 };
    _ = a;
}
```

### Expected Behavior

All three tests above should fail with the error message "value stored in comptime field does not match the default value of the field"

### Actual Behavior

The second test compiles successfully. The third test panics due to generating a runtime store to a comptime field.

### PR DESCRIPTION
**Pull request by Vexu**
After this there are 19 non-async runtime safety tests left.

Closes #12049

### CODE REVIEW

**Comment by nektro** [comment]
why were the cases changed from `backend=stage1` to `backend=llvm` instead of `backend=stage1,stage2` ?

**Comment by Vexu** [comment]
I don't care too much about stage1 and it's not going to regress itself with no one touching it and llvm is used instead of stage2 since CBE is the only self hosted backend that supports safety panics.

**Comment by andrewrk** [comment]
Still working on this? Need help with the CI failures?

**Comment by andrewrk** [comment]
Alright, I'm happy to help! I'll use the "assignee" feature of GitHub to indicate when I'm messing with it to help avoid stepping on your toes.

**Comment by andrewrk** [comment]
Are you sure this is working locally for you? I get the same error as the CI when I build locally:

```
thread 125199 panic: reached unreachable code
Analyzing /home/andy/dev/zig/lib/std/hash_map.zig: hash_map.zig:HashMapUnmanaged([]const u8,[]const u8,process.EnvMap.EnvNameHashContext,80).Metadata.slot_free
      %2998 = decl_val("Metadata") token_offset:776:44 to :776:52
      %2999 = validate_struct_init_ty(%2998) node_offset:776:44 to :776:75
      %3000 = field_type(%2998, fingerprint) node_offset:776:69 to :776:73
      %3001 = decl_val("free") token_offset:776:69 to :776:73
      %3002 = as_node(%3000, %3001) node_offset:776:69 to :776:73
    > %3003 = struct_init([%3000, %3002]) node_offset:776:44 to :776:75
      %3004 = bitcast(@Zir.Inst.Ref.u8_type, %3003) node_offset:776:31 to :776:76
      %3005 = break_inline(%2997, %3004)
    For full context, use the command
      zig ast-check -t /home/andy/dev/zig/lib/std/hash_map.zig

  in /home/andy/dev/zig/lib/std/hash_map.zig: hash_map.zig:HashMapUnmanaged([]const u8,[]const u8,process.EnvMap.EnvNameHashContext,80).Metadata.isFree
    > %3052 = decl_val("slot_free") token_offset:788:46 to :788:55

/home/andy/dev/zig/lib/std/debug.zig:281:14: 0x2ec2b78 in std.debug.assert (zig)
    if (!ok) unreachable; // assertion failure
             ^
/home/andy/dev/zig/src/type.zig:5505:23: 0x38265d7 in type.Type.structFieldValueComptime (zig)
                assert(struct_obj.layout != .Packed);
                      ^
/home/andy/dev/zig/src/Sema.zig:14216:53: 0x35fbd09 in Sema.zirStructInit (zig)
            if (resolved_ty.structFieldValueComptime(field_index)) |default_value| {
                                                    ^
/home/andy/dev/zig/src/Sema.zig:797:68: 0x3450f92 in Sema.analyzeBodyInner (zig)
            .struct_init                  => try sema.zirStructInit(block, inst, false),
                                                                   ^
/home/andy/dev/zig/src/Sema.zig:615:45: 0x3447aac in Sema.analyzeBodyBreak (zig)
    const break_inst = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                                            ^
/home/andy/dev/zig/src/Module.zig:4077:50: 0x327d0b2 in Module.semaDecl (zig)
    const result_ref = (try sema.analyzeBodyBreak(&block_scope, body)).?.operand;
                                                 ^
/home/andy/dev/zig/src/Module.zig:3714:38: 0x3259bf0 in Module.ensureDeclAnalyzed (zig)
    const type_changed = mod.semaDecl(decl_index) catch |err| switch (err) {
                                     ^
/home/andy/dev/zig/src/Sema.zig:23428:32: 0x3822fa1 in Sema.ensureDeclAnalyzed (zig)
    sema.mod.ensureDeclAnalyzed(decl_index) catch |err| {
                               ^
/home/andy/dev/zig/src/Sema.zig:23470:32: 0x36548c4 in Sema.analyzeDeclRef (zig)
    try sema.ensureDeclAnalyzed(decl_index);
                               ^
/home/andy/dev/zig/src/Sema.zig:23417:45: 0x380154e in Sema.analyzeDeclVal (zig)
    const decl_ref = try sema.analyzeDeclRef(decl_index);
                                            ^
/home/andy/dev/zig/src/Sema.zig:5170:31: 0x35cdfb8 in Sema.zirDeclVal (zig)
    return sema.analyzeDeclVal(block, src, decl);
                              ^
/home/andy/dev/zig/src/Sema.zig:723:65: 0x344d41e in Sema.analyzeBodyInner (zig)
            .decl_val                     => try sema.zirDeclVal(block, inst),
                                                                ^
/home/andy/dev/zig/src/Sema.zig:598:30: 0x344093a in Sema.analyzeBody (zig)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                             ^
/home/andy/dev/zig/src/Module.zig:5072:21: 0x3275fe6 in Module.analyzeFnBody (zig)
    sema.analyzeBody(&inner_block, fn_info.body) catch |err| switch (err) {
                    ^
/home/andy/dev/zig/src/Module.zig:3800:40: 0x3258ae0 in Module.ensureFuncBodyAnalyzed (zig)
            var air = mod.analyzeFnBody(func, sema_arena) catch |err| switch (err) {
                                       ^
/home/andy/dev/zig/src/Compilation.zig:2970:42: 0x2fd0e6a in Compilation.processOneJob (zig)
            module.ensureFuncBodyAnalyzed(func) catch |err| switch (err) {
                                         ^
/home/andy/dev/zig/src/Compilation.zig:2902:30: 0x2fbcbed in Compilation.performAllTheWork (zig)
            try processOneJob(comp, work_item);
                             ^
/home/andy/dev/zig/src/Compilation.zig:2250:31: 0x2fb5242 in Compilation.update (zig)
    try comp.performAllTheWork(main_progress_node);
                              ^
/home/andy/dev/zig/src/main.zig:3294:20: 0x2f2028f in updateModule (zig)
    try comp.update();
                   ^
/home/andy/dev/zig/src/main.zig:3886:21: 0x2ef2591 in cmdBuild (zig)
        updateModule(gpa, comp, .none) catch |err| switch (err) {
                    ^
/home/andy/dev/zig/src/main.zig:250:24: 0x2ecc93c in mainArgs (zig)
        return cmdBuild(gpa, arena, cmd_args);
                       ^
/home/andy/dev/zig/src/main.zig:174:20: 0x2ecb124 in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/home/andy/dev/zig/lib/std/start.zig:580:37: 0x2ecd9ef in std.start.main (zig)
            const result = root.main() catch |err| {
                                    ^
Aborted (core dumped)
```

**Comment by Vexu** [comment]
Are comptime fields not allowed in packed structs?
```zig
pub fn structFieldValueComptime(ty: Type, index: usize) ?Value {
    switch (ty.tag()) {
        .@"struct" => {
            const struct_obj = ty.castTag(.@"struct").?.data;
            assert(struct_obj.layout != .Packed);
```
I don't see any errors being emitted for this.

**Comment by andrewrk** [comment]
> Are comptime fields not allowed in packed structs?

mmmm, apologies for that assert. I don't remember why I put it there. I think comptime fields should be allowed in packed structs, for consistency.

**Comment by andrewrk** [comment]
I get this locally:

```
$ stage2/bin/zig test -fno-LLVM ../test/behavior.zig -I../test -target arm-linux
thread 353425 panic: reached unreachable code
/home/andy/Downloads/zig/src/arch/arm/CodeGen.zig:3076:25: 0x3ca0da6 in arch.arm.CodeGen.binOp (zig)
                else => unreachable,
                        ^
/home/andy/Downloads/zig/src/arch/arm/CodeGen.zig:1381:23: 0x3aca7b3 in arch.arm.CodeGen.airBinOp (zig)
        try self.binOp(tag, lhs, rhs, lhs_ty, rhs_ty, BinOpMetadata{
                      ^
/home/andy/Downloads/zig/src/arch/arm/CodeGen.zig:566:50: 0x3ac2973 in arch.arm.CodeGen.genBody (zig)
            .bit_or          => try self.airBinOp(inst, .bit_or),
                                                 ^
/home/andy/Downloads/zig/src/arch/arm/CodeGen.zig:443:25: 0x3919fb7 in arch.arm.CodeGen.gen (zig)
        try self.genBody(self.air.getMainBody());
                        ^
/home/andy/Downloads/zig/src/arch/arm/CodeGen.zig:326:17: 0x36f4e81 in arch.arm.CodeGen.generate (zig)
    function.gen() catch |err| switch (err) {
                ^
/home/andy/Downloads/zig/src/codegen.zig:83:59: 0x36ed28b in codegen.generateFunction (zig)
        => return @import("arch/arm/CodeGen.zig").generate(bin_file, src_loc, func, air, liveness, code, debug_output),
                                                          ^
/home/andy/Downloads/zig/src/link/Elf.zig:2394:37: 0x34ab659 in link.Elf.updateFunc (zig)
        try codegen.generateFunction(&self.base, decl.srcLoc(), func, air, liveness, &code_buffer, .{
                                    ^
/home/andy/Downloads/zig/src/link.zig:509:77: 0x32cbfad in link.File.updateFunc (zig)
            .elf   => return @fieldParentPtr(Elf,   "base", base).updateFunc(module, func, air, liveness),
                                                                            ^
/home/andy/Downloads/zig/src/Module.zig:4140:41: 0x32ac2b5 in Module.ensureFuncBodyAnalyzed (zig)
            mod.comp.bin_file.updateFunc(mod, func, air, liveness) catch |err| switch (err) {
                                        ^
/home/andy/Downloads/zig/src/Compilation.zig:2979:42: 0x2ff1b4a in Compilation.processOneJob (zig)
            module.ensureFuncBodyAnalyzed(func) catch |err| switch (err) {
                                         ^
/home/andy/Downloads/zig/src/Compilation.zig:2911:30: 0x2fdb6bd in Compilation.performAllTheWork (zig)
            try processOneJob(comp, work_item);
                             ^
/home/andy/Downloads/zig/src/Compilation.zig:2251:31: 0x2fd3b93 in Compilation.update (zig)
    try comp.performAllTheWork(main_progress_node);
                              ^
/home/andy/Downloads/zig/src/main.zig:3294:20: 0x2f3ebbf in updateModule (zig)
    try comp.update();
                   ^
/home/andy/Downloads/zig/src/main.zig:2983:17: 0x2f06985 in buildOutputType (zig)
    updateModule(gpa, comp, hook) catch |err| switch (err) {
                ^
/home/andy/Downloads/zig/src/main.zig:225:31: 0x2eeaa06 in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .zig_test);
                              ^
/home/andy/Downloads/zig/src/main.zig:174:20: 0x2ee9a54 in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/home/andy/Downloads/zig/lib/std/start.zig:580:37: 0x2eec31f in std.start.main (zig)
            const result = root.main() catch |err| {
                                    ^
Aborted (core dumped)
```

**Comment by andrewrk** [comment]
Another one:

```
$ stage2/bin/zig test ../test/behavior.zig -I../test -target powerpc-linux-musl -lc
LLVM Emit Object... 
Invalid operand types for ICmp instruction
  %3 = icmp eq label %TryCont12, %TryCont12, !dbg !45942
Invalid operand types for ICmp instruction
  %6 = icmp eq label %TryCont12, %TryCont12, !dbg !45968
Invalid operand types for ICmp instruction
  %2 = icmp eq label %TryCont12, %TryCont12, !dbg !46132

thread 367244 panic: LLVM module verification failed
```

**Comment by andrewrk** [comment]
What is your command you are using to test locally? And what host system are you running it on?

**Comment by andrewrk** [comment]
And here is how to reproduce the other problem the CI ran into:

```
[nix-shell:~/Downloads/zig/build-release]$ stage2/bin/zig build -p stage3-bootstrap -Dtarget=native-native-musl -Dstatic-llvm --search-prefix ~/dev/bootstrap-zig/out/x86_64-linux-musl-baseline -Dskip-install-lib-files

[nix-shell:~/Downloads/zig/build-release]$ stage3-bootstrap/bin/zig test ../test/behavior.zig -I../test
Semantic Analysis [3498] doTest... thread 374054 panic: Segmentation fault at address 0x0
???:?:?: 0x33b88c2 in ??? (???)
Aborted (core dumped)
```

**Pull request merged**
