### PR TITLE
Make self hosted compiler capable of building itself

### LINKED ISSUE #11375: stage2: defers are generated incorrectly in labeled blocks
```zig
test "incorrect" {
    _ = blk: {
        defer foo();
        break :blk try bar();
    };
}
test "correct" {
    defer foo();
    try bar();
}
fn foo() void {
    std.debug.print("foo called\n", .{});
}
fn bar() !void {
    std.debug.print("bar called\n", .{});
}
```
```sh-session
$ zig test a.zig
Test [1/2] test "incorrect"... bar called
foo called
Test [2/2] test "correct"... bar called
foo called
All 2 tests passed.
$ zig2 test a.zig
Test [1/2] test.incorrect... foo called
bar called
Test [2/2] test.correct... bar called
foo called
All 2 tests passed.
```

### PR DESCRIPTION
**Pull request by Vexu**
```sh-session
$ zig build -Denable-llvm
$ zig2 build -p build-stage3
$ cat a.zig
const std = @import("std");
pub fn main() void {
    const stderr = std.io.getStdErr();
    stderr.writeAll("Hello, world!\n") catch {};
}
$ build-stage3/bin/zig run a.zig
Hello, world!
```

LLVM backend needs some adjustments still.

Closes #11375

### CODE REVIEW

**Comment by Vexu** [comment]
Recursion:
```sh-session
$ cd build
$ cmake .. -DZIG_PREFER_CLANG_CPP_DYLIB=ON -DZIG_OMIT_STAGE2=on -DCMAKE_BUILD_TYPE=Release
-- Configuring zig version 0.10.0-dev.1825+101aac92c
-- Configuring done
-- Generating done
-- Build files have been written to: /home/vexu/Documents/zig/zig/build
$ make -s -j 12
Consolidate compiler generated dependencies of target opt_c_util
Consolidate compiler generated dependencies of target zigcpp
Consolidate compiler generated dependencies of target embedded_softfloat
[  1%] Built target opt_c_util
[  5%] Built target zigcpp
[ 86%] Built target embedded_softfloat
Consolidate compiler generated dependencies of target zigstage1
[ 98%] Built target zigstage1
Consolidate compiler generated dependencies of target zig0
[ 99%] Building CXX object CMakeFiles/zig0.dir/src/stage1/zig0.cpp.o
[ 99%] Linking CXX executable zig0
[ 99%] Built target zig0
[ 99%] Building self-hosted component /home/vexu/Documents/zig/zig/build/zig1.o
Consolidate compiler generated dependencies of target zig
[ 99%] Linking CXX executable zig
[100%] Built target zig
$ cd ..
$ build/zig build -p build-stage2 -Denable-llvm -Dconfig_h=build/config.h
$ build-stage2/bin/zig build -p build-stage3 -Denable-llvm -Dconfig_h=build/config.h
$ build-stage3/bin/zig build -p build-stage4 -Denable-llvm -Dconfig_h=build/config.h
$ 
```

**Comment by Snektron** [comment]
Whats the time difference between the stage 2 and stage 3 build?

**Comment by txdv** [comment]
> Whats the time difference between the stage 2 and stage 3 build?

https://github.com/ziglang/zig/wiki/Building-Zig-From-Source#stage-3-rebuild-self-hosted-zig-using-the-self-hosted-compiler

**Comment by andrewrk** [comment]
> Whats the time difference between the stage 2 and stage 3 build?

I took one measurement on my computer:

```
stage1 (release) build stage2 (debug) (LLVM backend):
 * wall clock: 47.80 seconds
 * peak rss: 8.6 GiB

stage2 (release) build stage3 (debug) (LLVM backend):
 * wall clock: 43.26 seconds
 * peak rss: 2.3 GiB
```

While a 10% speedup is no joke, keep in mind this is only the beginning of a set of upcoming compiler milestones, each successively improving compilation speed. I talked about this at the Milan meetup last weekend and @kristoff-it will be posting the recordings soon.

**Pull request merged**
