### PR TITLE
std: valgrind client request support for aarch64

### PR DESCRIPTION
**Pull request by mitchellh**
Tested locally on my aarch64 machine.

### CODE REVIEW

**Review by daurnimator — APPROVED** [review]
Matches what I see in valgrind.h.

**Comment by andrewrk** [comment]
Nice!

I'd like to do the corresponding improvements to src/target.zig and src/codegen/llvm.zig (`valgriendClientRequest`) along with merging this. If you're up for doing that here, be my guest, otherwise sit tight and I'll take care of it.

**Comment by mitchellh** [comment]
> I'd like to do the corresponding improvements to src/target.zig and src/codegen/llvm.zig (valgriendClientRequest) along with merging this. If you're up for doing that here, be my guest, otherwise sit tight and I'll take care of it.

Ah, sorry for not seeing that. Target is easy but I'm not comfortable with the llvm side. I'll sit tight... no rush this is obviously not critical.

**Comment by andrewrk** [comment]
This is now done, but I was unable to test it on aarch64 due to #10086 (which I will be looking into shortly) or x86 due to not having an x86 machine lying around.

**Comment by andrewrk** [comment]
Tested on aarch64-linux Debian-bullseye:

```
$ cat test.zig
const std = @import("std");

pub fn main() !void {
foo();
}

fn foo() void {
    var data: bool = true;
    data = undefined;
    if (data) {
        std.debug.print("true\n", .{});
    }
}

```

```
$ valgrind ./test
==425462== Memcheck, a memory error detector
==425462== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==425462== Using Valgrind-3.16.1 and LibVEX; rerun with -h for copyright info
==425462== Command: ./test
==425462== 
==425462== Conditional jump or move depends on uninitialised value(s)
==425462==    at 0x21E14C: ??? (in /home/andy/zig/build-release/test)
==425462== 
==425462== 
==425462== HEAP SUMMARY:
==425462==     in use at exit: 0 bytes in 0 blocks
==425462==   total heap usage: 0 allocs, 0 frees, 0 bytes allocated
==425462== 
==425462== All heap blocks were freed -- no leaks are possible
==425462== 
==425462== Use --track-origins=yes to see where uninitialised values come from
==425462== For lists of detected and suppressed errors, rerun with: -s
==425462== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
```

Looks like the code here works, although I'm not sure why the debug info is missing.

**Pull request merged**
