### PR TITLE
link: Recognize `-z origin|noexecstack|now|relro` linker args.

### PR DESCRIPTION
**Pull request by alexrp**
These are some `-z` linker options that are fairly common in C/C++ projects in the wild.

As far as I can tell, this argument parsing code is just used for `zig cc`/`zig c++`. Do we want some way to surface these to `build-exe`/`build-lib`? `noexecstack`/`relro` are common for security, and `now` has real world usefulness (I once had to use it to due to a really nasty signal handler vs lazy dynamic linking issue - long story...).

### CODE REVIEW

**Comment by LemonBoy** [comment]
> Do we want some way to surface these to build-exe/build-lib? 

Yep, see #6977.

**Comment by alexrp** [comment]
Ok, I can look into adding `-z` support for the Zig commands in a later PR.

**Comment by N00byEdge** [comment]
There is also `-z max-page-size=0x1000` to set the section alignment, very useful for bare metal development.

**Comment by sreehax** [comment]
Just confirming that it general -z support would also be very good for my use case since I could also really use the max-page-size option. It would also be nice to support it in a LibExeObjStep in the final product, but this seems fairly trivial to me since that would just append to zig_args.

**Comment by alexrp** [comment]
That might be interesting to look at in a later PR, but it would probably need some consideration since it kind of partly exposes the underlying linker's command line interface directly as part of `zig cc`'s interface, which may or may not be desirable.

E.g. `zig cc` itself is always ~equivalent to `clang`, never `clang-cl`. That provides a nice and consistent CLI for users regardless of the target platform. That would no longer be the case if `-z` options were just blindly passed through to the linker, which can be `ld.lld`, `lld-link`, etc and therefore produce a warning/error if it doesn't recognize a particular option.

**Pull request merged**
