### PR TITLE
workflows | Avoid running workflow on non-relevant files

### PR DESCRIPTION
**Pull request by zraineri**
Adds paths-ignore param with files which do not need tests run on them to save resources for other jobs which do

### CODE REVIEW

**Comment by andrewrk** [comment]
Thank you but I do not think this is necessary. Also, 2 of those lines are incorrect, since the README and LICENSE file are both installed into the tarballs.

**Comment by zraineri** [comment]
No worries then, thought it might help

They still trigger the workflow when edited currently, you can see [here](https://github.com/ziglang/zig/actions/runs/5639021929) the readme edit took over 4 hours 

[paths-ignore](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths) just avoids the workflow if only ignored files are edited in the request

**Comment by zraineri** [comment]
@andrewrk do you think there would be value in [fail-fast](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast)? Or should all jobs run to completion regardless if others fail?

**Comment by andrewrk** [comment]
>the readme edit took over 4 hours

The readme goes into the tarball, therefore we want readme edits to trigger the pipeline

> do you think there would be value in [fail-fast](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast)?

No, it's often handy to have all the failures on different systems.

It feels to me like you're trying to solve a problem that we don't have.

**Pull request closed without merging**
