### PR TITLE
Sema: more helpful error message when switching on pointer instead of enum or tagged union

### PR DESCRIPTION
**Pull request by wrongnull**
Probably closes https://github.com/ziglang/zig/issues/13856

### CODE REVIEW

**Comment by mlugg** [comment]
This fix is not correct. Switching on a pointer value is valid Zig - the example in #13856 only emits an error because the switch prongs are not themselves pointers. This more helpful error must only be emitted in cases where an error would already be omitted, and it must not imply that you *can't* switch on a pointer. (Most likely it should be a conditional error note on the existing error in #13856.)

**Comment by wrongnull** [comment]
> This fix is not correct. Switching on a pointer value is valid Zig - the example in #13856 only emits an error because the switch prongs are not themselves pointers. This more helpful error must only be emitted in cases where an error would already be emitted, and it must not imply that you _can't_ switch on a pointer. (Most likely it should be a conditional error note on the existing error in #13856.)

+

**Comment by wrongnull** [comment]
> This fix is not correct. Switching on a pointer value is valid Zig - the example in #13856 only emits an error because the switch prongs are not themselves pointers. This more helpful error must only be emitted in cases where an error would already be emitted, and it must not imply that you _can't_ switch on a pointer. (Most likely it should be a conditional error note on the existing error in #13856.)

@mlugg But I done it in a different manner. Only checked if the prong type tag is ```.EnumLiteral``` and operand type tag is ```.Pointer```

**Comment by xdBronch** [comment]
switches on enums/unions arent always EnumLiterals

**Comment by andrewrk** [comment]
> Probably closes https://github.com/ziglang/zig/issues/13856

frankly this is not good enough for the zig project.

**Comment by wrongnull** [comment]
> > Probably closes https://github.com/ziglang/zig/issues/13856
> 
> frankly this is not good enough for the zig project.

Agree. I'll try to rewrite this and improve the quality of the code in the future.

**Pull request closed without merging**
