### PR TITLE
stage2: ask for more file descriptors

### PR DESCRIPTION
**Pull request by xackus**
Follow up to #6906.

### CODE REVIEW

**Comment by andrewrk** [comment]
I believe you also get to delete this code now too :)

https://github.com/ziglang/zig/blob/445d808bae4b9a2ff1c7a56a4ebff64ae848f46c/src/stage1/os.cpp#L981-L1003

**Review by andrewrk — APPROVED** [review]

**Comment by xackus** [comment]
I don't have a mac, so I would appreciate help with the EINVAL failure from someone who does. cc @kubkon
I made my linux machine go through the binary search path and it worked fine.

**Comment by kubkon** [comment]
@xackus 8dda64f should fix it on Darwin :-) The issue on Darwin is that you can't trust `getrlimit()` for `NOFILE`. According to the man pages:

> setrlimit() now returns with errno set to EINVAL in places that historically succeeded.  It no longer accepts "rlim_cur = RLIM_INFINITY" for RLIM_NOFILE.  Use "rlim_cur = min(OPEN_MAX, rlim_max)".

**Comment by xackus** [comment]
@kubkon Thank you, I missed the "COMPATIBILITY" section of the man page.

**Comment by xackus** [comment]
This looks like another argument against `EINVAL => unreachable`. See #6389, #6925.

**Comment by kubkon** [comment]
> This looks like another argument against `EINVAL => unreachable`. See #6389, #6925.

I guess, in this case, we could already map `EINVAL` to some proper error value. However, we just need to ensure we make it impossible to specify an incorrect resource value. For instance, on Darwin `EINVAL` can be returned in two instances. From the man pages:

>      [EINVAL]           resource is invalid.
>      [EINVAL]           The specified limit is invalid (e.g., RLIM_INFINITY or lower than rlim_cur).

Since we constrain the input resource to `resource_limit` enum, we should be OK mapping `EINVAL` exclusively to invalid limit error condition.

**Comment by kubkon** [comment]
The CI failure is unrelated to this PR, so proceeding with the merge.

**Pull request merged**
