### PR TITLE
all: rename `@maximum` to `@max` and `@minimum` to `@min`

### LINKED ISSUE #12994: Rename `@maximum` and `@minimum` to `@max` and `@min`
Every single time I use one of these I want to type "max" or "min" until I remember "ah, right, I can't use well-established abbreviations here; I have to spell it all out, ugh".

The naming choices of `@maximum` and `@minimum` are weird and inconsistent for various reasons:
* "max" and "min" are very well established abbreviations for "maximum" and "minimum"; why do we have to spell it all out like that? It seems so extra.
* Abbreviations are used all throughout builtin function names. It's inconsistent and makes these two builtin functions stick out for no reason. If we don't want to use abbreviations, I guess we have to rename `ptrCast` to `pointerCast`. "Max" or "min" are as much, if not more so, well-understood abbreviation for "maximum" and "minimum" as "ptr" is for "pointer".
* Every developer expects these to be called "max" and "min". Most libraries/languages etc. use the abbreviations.
* They didn't do the same mistake in `std.math`: it's not `std.math.maximumInt`, it's `std.math.maxInt` and it's not `std.math.maximum`, it's `std.math.max`, and so on.
  So these builtin function names are inconsistent with `std.math`'s equivalents (whatever the difference between these is supposed to be, anyway) as well. Especially if you change between the builtin functions and `math.max` or `math.min`, this weirdness in naming becomes especially noticeable and awkward.

### PR DESCRIPTION
**Pull request by alichraghi**
Closes #12994

### CODE REVIEW

**Comment by andrewrk** [comment]
Please rebase against master branch. Let's get those CI tests passing.

**Comment by Vexu** [comment]
This needs a new Windows CI tarball as does master due to my mistake in #13067
> Whoops, looks like the Windows failure wasn't spurious but caused by a need for a new tarball (sigh). https://github.com/ziglang/zig/pull/13055 also needs one so maybe these two should be handled together.

I'd build one but `zig-bootstrap` doesn't work on my machine.

**Comment by andrewrk** [comment]
I suggest that we focus first on replacing stage1 via the C backend before making more breaking changes like this. This will save a lot of time and annoyance of constantly updating the Windows CI tarball.

This will require a few components:
 * #6025 (started in the stage2-async branch)
 * Many C backend improvements
 * Finish solving the remaining test cases that stage1 is passing and self-hosted is failing, allowing us to fully remove the `-fstage1` flag from the compiler (and corresponding logic).

I am focusing on getting 0.10.0 out the door (Nov 1) before doing any of this work.

**Comment by Vexu** [comment]
It would be nice to get this into 0.10.0 since `@maximum` and `@minimum` were introduced after 0.9.1

**Comment by andrewrk** [comment]
Making new tarballs now. (These will also include LLVM 15.0.3 which was released today)

**Pull request merged**
