### PR TITLE
Add VirtualProtect function to std.os.windows.kernel32

### PR DESCRIPTION
**Pull request by tuket**
Just added the binding for this function

### CODE REVIEW

**Comment by mlugg** [comment]
There's already a wrapper in `os.windows.VirtualProtect` - the reason there isn't a binding for the original one is that we prefer to call into ntdll, so the wrapper uses `ntdll.NtProtectVirtualMemory` instead.

**Comment by tuket** [comment]
Ah, ok.
Is `VirtualProtect` the same as `NtProtectVirtualMemory`? I can't find `NtProtectVirtualMemory` in the MS documentation.

**Comment by mlugg** [comment]
Yeah, lots of ntdll is undodumented, but kernel32's `VirtualProtect` is just a wrapper around `NtProtectVirtualMemory`. The Zig wrapper in `os.windows.VirtualProtect` pretty much exactly mirrors the normal `VirtualProtect` API (only change is it returns a Zig error union), so it should be basically drop-in.

And yes, this was implemented since 0.10.0. (The 0.10.1 release was bugfixes only, so wouldn't have had it either way.) If you need it, you can either use `master` or just use a `extern` declaration within your project until 0.11.0 releases.

**Comment by tuket** [comment]
Cool, thanks :)
I will close this PR then.

**Pull request closed without merging**
