### PR TITLE
Add upperBound, lowerBound, and equalRange functions

### PR DESCRIPTION
**Pull request by CraigglesO**
Original Discussion: https://github.com/ziglang/zig/issues/9890

I already had to create these functions and test cases for my own project so I decided to contribute to the main code base in hopes it would simplify my own.

I realize this is still under discussion but this was a trivial amount of work so I thought I could help nudge the discussion towards a decision.

**Why add these to the standard library**

To better illustrate and solidify their value, the standard library's "sort" module already contains several binary search queries on arrays such as [`binarySearch`](https://ziglang.org/documentation/master/std/#A;std:sort.binarySearch) and internal functions [`binaryFirst`](https://github.com/ziglang/zig/blob/master/lib/std/sort.zig#L1057) & [`binaryLast`](https://github.com/ziglang/zig/blob/master/lib/std/sort.zig#L1080). A final example of its use: the Zig code itself created and [used a bounding search in the linker.](https://github.com/ziglang/zig/blob/master/src/link/MachO/zld.zig#L4131)

There still lacks the ability to allow the programmer themselves to search the array for a rough position and find an index to read &/ update.

Adding these functions would also help to complement dynamic structures like `ArrayList` with it's [insert](https://ziglang.org/documentation/master/std/#A;std:ArrayList.insert) function.

**Example Case**
I'm building a library in Zig for GIS geometry. To store points, lines, and polygons each 3D point is first translated into what's called an `S2CellId`. This is a fancy way of saying I reduce the Earth's spherical data into a 1D Hilbert Curve with cm precision. This gives me 2 convenient truths:
* Hilbert Curves have locality of reference.
* All points can be stored inside a 1D array

Since `lowerBound` and `upperBound` to find data inside a radius for instance. If I'm interested in a specific cell at a specific "level" and want to iterate all duplicates, `equalRange` is a best fit.

### CODE REVIEW

**Comment by schmee** [comment]
I have needed these on several occasions, would be a nice addition imo 👍

**Comment by andrewrk** [comment]
Closing abandoned PR. Multiple CI checks failing, conflicts with master branch, no activity in months.

**Comment by schmee** [comment]
@CraigglesO would you be OK with me rebasing this and trying to get it merged? I think it's a valuable addition.

**Comment by CraigglesO** [comment]
@schmee - go for it! I would really love to see this through as well. The reasoning behind it's closure has caused me to have 0 interest in contributing towards this project anymore so it's all yours.

**Comment by andrewrk** [comment]
Did you expect me to merge it with the CI checks failing, or did you expect me to finish it for you? I don't appreciate your passive aggressive attitude. Goodness.

**Comment by CraigglesO** [comment]
Huh, ok Andrew, I'll bite.

Do you genuinely expect me to, for months, keep updating to the latest branch hoping someone to eventually respond? Do you really think that's fair? Did you even bother to read the description & code and see how simple it is and how it doesn't have any dependencies?

You realize how simple it would have been to say:
1) Not interested in this getting pushed through. (would honestly be no problem)
2) Am potentially interested, please update to the latest branch so we can move this forward.

Honestly, I've also noticed you've had this same kind of attitude on Reddit with people as well when you don't agree with them. You have a combative attitude when genuine criticism has been presented.

Do you believe the way you handled the closure of this PR creates a sense of community?
I'm going to be direct with you, it makes me think you don't want people to contribute and so I don't want to try and contribute ever again.

**Comment by andrewrk** [comment]
I'll answer one of your questions, and then I want you to answer mine.

> Do you genuinely expect me to, for months, keep updating to the latest branch hoping someone to eventually respond?

No, I certainly do not expect that, not from you or from anyone.

OK, my turn. Was there ever a point in time in which this code was, in your opinion, ready to be merged?

**Comment by schmee** [comment]
Continued in https://github.com/ziglang/zig/pull/18718.

**Pull request closed without merging**
