### PR TITLE
std.fmt.fmtDuration: use μs instead of us

### PR DESCRIPTION
**Pull request by nektro**
cc @g-w1

### CODE REVIEW

**Review by andrewrk — CHANGES_REQUESTED** [review]
This character is outside of ascii range. Instead, a format string modifier should be used to decide between 'u', UTF-8 encoded 'μ', or a terminal sequence like this:

https://github.com/ziglang/zig/blob/ff835cce106c27603142533e4eb59792abcf1f13/lib/build_runner.zig#L547

**Comment by nektro** [comment]
why is being outside ascii a blocker when you can instruct windows to support utf-8 by default?

**Comment by andrewrk** [comment]
you expect the user to change a global setting? you expect the programmer to use the zig standard library start code? these are not premises that are given when writing zig code. the standard library may be used from a static library that is linked into third party code.

**Comment by nektro** [comment]
> you expect the user to change a global setting? you expect the programmer to use the zig standard library start code?

if the latter is not true then i do expect the former in 2023. it is long past the time to make supporting unicode the default imo
but i dont feel that strongly about this change so I will probably close

**Pull request closed without merging**
