### PR TITLE
Add math.Max

### PR DESCRIPTION
**Pull request by data-man**
Because of Min without Max as half a Twix. :)

Q: should min/max work for types with different signs?

```zig
testing.expect(min(@as(i32, -1), @as(u32, 2)) == -1);
// error: incompatible types: 'i32' and 'u32'
return @TypeOf(@as(A, 0) + @as(B, 0));
                         ^
```

### CODE REVIEW

**Comment by andrewrk** [comment]
Why would you ever use this? The goal is to have the narrowest type possible, otherwise we would just use `u999999999` for everything.

**Comment by data-man** [comment]
> Why would you ever use this?

In rank function:
```zig
pub const RankInfo = struct {
    minScalarType: type,
    maxScalarType: type,
    rank: usize,
};
```
```zig
pub fn rank(comptime T: type) RankInfo {
...
}
```

**Comment by data-man** [comment]
If `min` exists, then `max` also exists. This is a good tradition.

**Comment by andrewrk** [comment]
This is not a useful function - not even `max` would use it. Note that your pull request does not change `max` to use this function as the return type because it is not actually what is desired.

**Pull request closed without merging**
