### PR TITLE
std.mem.count

### PR DESCRIPTION
**Pull request by Sobeston**
Surprised that I couldn't find a function for this

### CODE REVIEW

**Comment by zigazeljko** [comment]
What is the expected behavior for `needle.len == 0`?

**Comment by Sobeston** [comment]
Made it clearer that:
1) needle.len = 0 is illegal behavior
2) it does not count overlapping needles (see the ff test case)

**Comment by andrewrk** [comment]
This is not needed to be part of this PR (I recognize that it is copying existing naming conventions) but @thejoshwolfe pointed out that it would be better to come up with more descriptive names than `needle` and `haystack` which depend on the idiom "needle in a haystack". For English-as-a-second-language speakers, it would be better to use words that make sense without depending on this extra knowledge.

**Comment by data-man** [comment]
> What is the expected behavior for needle.len == 0?

```zig
const std = @import("std");
const testing = std.testing;
const assert = std.debug.assert;

/// Returns the number of needles inside the haystack
/// does not count overlapping needles
pub fn count(comptime T: type, haystack: []const T, needle: []const T) ?usize {
    if (haystack.len == 0) return 0;
    if (needle.len == 0) return null;
    var i: usize = 0;
    var found: usize = 0;

    while (std.mem.indexOfPos(T, haystack, i, needle)) |idx| {
        i = idx + needle.len;
        found += 1;
    }

    return found;
}

test "mem.count" {
    testing.expect(count(u8, "", "h") == @as(usize, 0));
    testing.expect(count(u8, "h", "h") == @as(usize, 1));
    testing.expect(count(u8, "hh", "h") == @as(usize, 2));
    testing.expect(count(u8, "world!", "hello") == @as(usize, 0));
    testing.expect(count(u8, "hello world!", "hello") == @as(usize, 1));
    testing.expect(count(u8, "   abcabc   abc", "abc") == @as(usize, 3));
    testing.expect(count(u8, "udexdcbvbruhasdrw", "bruh") == @as(usize, 1));
    testing.expect(count(u8, "foo bar", "o bar") == @as(usize, 1));
    testing.expect(count(u8, "foofoofoo", "foo") == @as(usize, 3));
    testing.expect(count(u8, "fffffff", "ff") == @as(usize, 3));
    testing.expect(count(u8, "null", "") == null);
}
```

**Comment by daurnimator** [comment]
I would also add a function `contains` or `has`.
I believe that many people will use `if (mem.count(u8, slice, "myneedle") == 0)` which needlessly does many `indexOf` operations.
Infact I'm not sure when you would use `count` as a non-antipattern: wouldn't you usually be comparing to another number? Which suggests `mem.hasAtLeast` is da real MVP.....
Could you share some use-cases?

**Comment by data-man** [comment]
`mem.len` + `trait.isIndexable` + `meta.eql` == `more flexible search functions`

**Pull request merged**
