### PR TITLE
compiler: implement labeled switch/continue

### PR DESCRIPTION
**Pull request by mlugg**
TODO: PR message.

@Luukdegram, any chance you'd be able to un-regress the WASM backend here? I broke `loop` and probably fixed it (although I won't claim to have tested it), but I broke `switch_br` more fundamentally. It now directly represents range cases, whereas Sema previously lowered these to `cond_br` chains. I don't know enough about WASM to easily implement this myself! If you do get around to it, note the new `Air.switchIterator` to make it a little more convenient.

### CODE REVIEW

**Comment by mlugg** [comment]
Oh, I also need to work on SPIR-V, while it doesn't currently have CI coverage we probably don't want to regress that one. I'll take a look myself later, but in case it's non-trivial, cc @Snektron

**Comment by Luukdegram** [comment]
@mlugg Fixed it for the Wasm backend :)

**Comment by Ev1lT3rm1nal** [comment]
Any update?

**Comment by andrewrk** [comment]
Looks like this didn't make it to the finish line yet. Looking forward to its revival

**Pull request closed without merging**
