### PR TITLE
translate-c: Fix function pointers, add cast to subscripts in macros

### PR DESCRIPTION
**Pull request by tau-dev**

### CODE REVIEW

**Comment by Vexu** [comment]
>fix the remaining function pointer issues

What issues?

>fix #5305

How?

**Comment by tau-dev** [comment]
Sorry, those commit messages are not very comprehensive.

2ca503e just renders the callee as grouped. That solved the error described in #12263, but not the entire testcase; 
6be16ee replaces the various patch-ups in translate_c.trans* with logic in the translate_c.ast.render* handling of `.address_of` and `fn_identifier` to cover the function identifier->pointer decay correctly for stage2 and stage1 (I cannot currently test the latter, as test-run-translated-c crashes under -fstage1; will file an issue for that).

770a1aa fixes #5305 with a simple int cast in parseCPostfixExpr.

**Comment by Vexu** [comment]
> [770a1aa](https://github.com/ziglang/zig/commit/770a1aa967d22c51e7bf8a5999c289bdf959ecba) fixes #5305 with a simple int cast in parseCPostfixExpr.

Is that what caused the issue? It doesn't seem to mention array access anywhere.

**Comment by tau-dev** [comment]
The error mentioned there was fixed, probably by #5184, but the code that was given still did not compile due to
```zig
zig-cache/o/e2b8b2aa78a80d671e19c6b070f1d5b7/cimport.zig:2960:136: error: expected type 'usize', found 'c_int'
pub inline fn ScreenOfDisplay(dpy: anytype, scr: anytype) @TypeOf(&@import("std").zig.c_translation.cast(_XPrivDisplay, dpy).*.screens[scr]) {
                                                                                                                                       ^~~
```

**Pull request merged**
