### PR TITLE
lib/std/io: let the bring-your-own OS package handle stdio

### PR DESCRIPTION
**Pull request by Xe**
This lets you do things like this in the custom OS package:

```zig
pub const io = struct {
    pub fn getStdIn() bits.fd_t {
        if (bits.STDIN_FILENO == -1) {
            bits.STDIN_FILENO = resource.io_get_stdin();
        }

        return bits.STDIN_FILENO;
    }

    pub fn getStdErr() bits.fd_t {
        if (bits.STDERR_FILENO == -1) {
            bits.STDERR_FILENO = resource.io_get_stderr();
        }

        return bits.STDERR_FILENO;
    }

    pub fn getStdOut() bits.fd_t {
        if (bits.STDOUT_FILENO == -1) {
            bits.STDOUT_FILENO = resource.io_get_stdout();
        }

        return bits.STDOUT_FILENO;
    }
};
```

### CODE REVIEW

**Comment by Vexu** [comment]
You can already do this.
```zig
// zig build-obj a.zig -target x86_64-freestanding
pub const os = struct {
    pub const bits = struct {
        pub const fd_t = u32;
        pub const STDOUT_FILENO = 0;
        pub const STDIN_FILENO = 0;
        pub const STDERR_FILENO = 0;
    };
};

const std = @import("std");

export fn entry() void {
    var std_out = std.io.getStdOut();
    var std_in = std.io.getStdIn();
    var std_err = std.io.getStdErr();
}
```

**Comment by ls-christine-dodrill** [comment]
@Vexu my usecase involves file descriptors being randomly assigned without std{in|out|err} being preallocated at boot. I can't see a way around this that doesn't involve monkey-patching the getStd{In|Out|Err} functions to allocate the descriptors.

**Comment by Xe** [comment]
@Vexu my usecase involves file descriptors being randomly assigned without std{in|out|err} being preallocated at boot. I can't see a way around this that doesn't involve monkey-patching the getStd{In|Out|Err} functions to allocate the descriptors.

**Comment by Vexu** [comment]
In that case I think a better solution would be to add `getStdInHandle` and others to `std.os` and have `std.io` call those.

**Comment by andrewrk** [comment]
I agree with @Vexu that `getStdInHandle` is the right abstraction layer to solve this at, but it's not really a posixy API, so I think it should go next to `getStdIn` (in std.io rather than std.os).

**Comment by Xe** [comment]
With the latest patches to my branch, this works:

```zig
// from olin/olin.zig
pub const io = struct {
    pub fn getStdInHandle() bits.fd_t {
        if (bits.STDIN_FILENO == -1) {
            bits.STDIN_FILENO = resource.io_get_stdin();
        }

        return bits.STDIN_FILENO;
    }

    pub fn getStdErrHandle() bits.fd_t {
        if (bits.STDERR_FILENO == -1) {
            bits.STDERR_FILENO = resource.io_get_stderr();
        }

        return bits.STDERR_FILENO;
    }

    pub fn getStdOutHandle() bits.fd_t {
        if (bits.STDOUT_FILENO == -1) {
            bits.STDOUT_FILENO = resource.io_get_stdout();
        }

        return bits.STDOUT_FILENO;
    }
};
```

```zig
// allyourbase.zig
pub const os = @import("./olin/olin.zig");
const std = @import("std");

pub fn main() anyerror!void {
    std.debug.warn("All your base are belong to us.\n", .{});
}
```

```console
$ cwa -main-func _start allyourbase.zig
```

**Pull request merged**
