### PR TITLE
tools: fix update-linux-headers.zig and process_headers.zig

### PR DESCRIPTION
**Pull request by BratishkaErik**
I tried to update merge_anal_dumps.zig, but it looks abandoned since 2019, so IMHO it's too much work (a lot has changed since then) for too little gain. If you want, I can remove this file and/or include this commits to #11740.

Signed-off-by: BratishkaErik <bratishkaerik@getgoogleoff.me>

### CODE REVIEW

**Comment by LemonBoy** [comment]
Add a line [here](https://github.com/ziglang/zig/blob/ee651c3cd358f40f60db0bbcd82ffde99aed9b88/test/standalone.zig#L83) to prevent the tools from bit -rotting again.

**Comment by BratishkaErik** [comment]
> Add a line [here](https://github.com/ziglang/zig/blob/ee651c3cd358f40f60db0bbcd82ffde99aed9b88/test/standalone.zig#L83) to prevent the tools from bit -rotting again.

OK, thank you!

**Comment by BratishkaErik** [comment]
Added to #11740.

**Review by ifreund — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
