### PR TITLE
std.StaticStringMap: bump eval branch quota

### LINKED ISSUE #19803: `StaticStringMap` evaluation branch quota too low
### Zig Version

0.13.0-dev.47+c231d9496

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");
const TypeToByteSizeLUT = std.StaticStringMap(u32).initComptime(.{
    .{ "bool", 0 },
    .{ "c_int", 0 },
    .{ "c_long", 0 },
    .{ "c_longdouble", 0 },
    .{ "t20", 0 },
    .{ "t19", 0 },
    .{ "t18", 0 },
    .{ "t17", 0 },
    .{ "t16", 0 },
    .{ "t15", 0 },
    .{ "t14", 0 },
    .{ "t13", 0 },
    .{ "t12", 0 },
    .{ "t11", 0 },
    .{ "t10", 0 },
    .{ "t9", 0 },
    .{ "t8", 0 },
    .{ "t7", 0 },
    .{ "t6", 0 },
    .{ "t5", 0 },
    .{ "t4", 0 },
    .{ "t3", 0 },
    .{ "t2", 0 },
    .{ "t1", 0 },
});

pub fn main() void {
    _ = TypeToByteSizeLUT.kvs;
}
```

The above example results in `error: evaluation exceeded 1000 backwards branches`, you can change any key name you want and it may or may not compile. Or you can change the order of `t20` ~ `t1` to `t1` ~ `t20` and it will compile.

### Expected Behavior

Compile success.

### PR DESCRIPTION
**Pull request by travisstaloch**
closes #19803 by changing quota from (30 * N) to (10 * N * log2(N)) where
N = kvs_list.len

* adds reported adversarial test case
* update doc comment of getLongestPrefix()

EDITED

### CODE REVIEW

**Comment by mlugg** [comment]
Since the KVs are sorted, a linearly-growing bound will never be sufficient for extreme cases. Perhaps grow proportional to n^2 or something?

**Comment by travisstaloch** [comment]
> Since the KVs are sorted, a linearly-growing bound will never be sufficient for extreme cases. Perhaps grow proportional to n^2 or something?

Thanks, sounds good!  Checking if test-std passes after changing quota to (10 * N * N) where N = kvs_list.len.

**Comment by travisstaloch** [comment]
> Since the KVs are sorted, a linearly-growing bound will never be sufficient for extreme cases. Perhaps grow proportional to n^2 or something?

Done.

**Review by andrewrk — CHANGES_REQUESTED** [review]
N squared??? NOT OK

**Comment by travisstaloch** [comment]
> If StaticStringMap was recently changed to be N^2 then it needs to be reverted pronto

The comptime initialization has not changed significantly from the original ComptimeStringMap impl.  The limit was changed from 1500 to 30*N.  But this was found to be insufficient for adversarial key arrangements.  The N^2 limit is needed for sorting those keys which may require N^2 steps.

**Comment by andrewrk** [comment]
Sorting should be O(N * log2(N)). Related: #13642

**Comment by travisstaloch** [comment]
Sounds good. I will update the limit to C * N * log2(N).

**Comment by andrewrk** [comment]
Great. I love that it documents the compilation time complexity.

**Comment by travisstaloch** [comment]
Just pushed a change. Now using `math.log2_int_ceil(usize, kvs_list.len)` instead.

**Comment by andrewrk** [comment]
Thanks!

**Pull request merged**
