### PR TITLE
Fix crash on multiline library name

### LINKED ISSUE #4163: stage2 parser crash on `extern\\`
`extern\\` crashes the parser.
```
attempt to unwrap null
/home/mwa/code/zig/lib/std/zig/parse.zig:288:74: 0x23cbfa in std.zig.parse.parseTopLevelDecl (run)
            putBackToken(it, string_literal_node.cast(Node.StringLiteral).?.token);
                                                                         ^
/home/mwa/code/zig/lib/std/zig/parse.zig:113:34: 0x239377 in std.zig.parse.parseContainerMembers (run)
        if (try parseTopLevelDecl(arena, it, tree)) |node| {
                                 ^
/home/mwa/code/zig/lib/std/zig/parse.zig:70:43: 0x2367ae in std.zig.parse.parseRoot (run)
        .decls = try parseContainerMembers(arena, it, tree),
                                          ^
/home/mwa/code/zig/lib/std/zig/parse.zig:51:31: 0x209b49 in std.zig.parse.parse (run)
    tree.root_node = parseRoot(arena, &it, tree) catch |err| blk: {
                              ^
```

### PR DESCRIPTION
**Pull request by Vexu**
Closes #4163

### CODE REVIEW

**Comment by LemonBoy** [comment]
I think this should be a parse error, is there any use case for a multiline library name?

**Comment by Vexu** [comment]
Probably not, but the grammar doesn't make a distinction between multiline strings and normal strings.

**Comment by andrewrk** [comment]
This is an improvement over status quo, but I agree, the grammar should require a non-multiline string after `extern`.

**Comment by Vexu** [comment]
Should test names also be single line strings?

**Comment by andrewrk** [comment]
Yes

**Pull request merged**
