### PR TITLE
Allow wrapping in VDSO lookup

### LINKED ISSUE #3997: Integer overflow in libstd
The following code gives an integer overflow when runned with `zig test`:
```Zig
pub fn MaybeUninit(comptime T: type) type {
    return extern union {
        value: T,
        uninit: void,
    };
}

test "" {
    const x = MaybeUninit(u8);
}
```

Error message:
```
integer overflow
/home/ghost/.zig/zig-linux-x86_64-0.5.0+25e71216c/lib/zig/std/os/linux/vdso.zig:25:68: 0x234c39 in std.os.linux.vdso.lookup (test)
                elf.PT_LOAD => base = vdso_addr + this_ph.p_offset - this_ph.p_vaddr,
                                                                   ^
/home/ghost/.zig/zig-linux-x86_64-0.5.0+25e71216c/lib/zig/std/os/linux.zig:508:54: 0x206717 in std.os.linux.init_vdso_clock_gettime (test)
    const ptr = @intToPtr(?*const c_void, vdso.lookup(VDSO_CGT_VER, VDSO_CGT_SYM));
                                                     ^
/home/ghost/.zig/zig-linux-x86_64-0.5.0+25e71216c/lib/zig/std/os/linux.zig:497:25: 0x2311b3 in std.os.linux.clock_gettime (test)
            const rc = f(clk_id, tp);
                        ^
/home/ghost/.zig/zig-linux-x86_64-0.5.0+25e71216c/lib/zig/std/os.zig:2760:39: 0x22e6f0 in std.os.clock_gettime (test)
    switch (errno(system.clock_gettime(clk_id, tp))) {
                                      ^
/home/ghost/.zig/zig-linux-x86_64-0.5.0+25e71216c/lib/zig/std/time.zig:147:29: 0x22e4a5 in std.time.Timer.start (test)
            os.clock_gettime(monotonic_clock_id, &ts) catch return error.TimerUnsupported;
                            ^
/home/ghost/.zig/zig-linux-x86_64-0.5.0+25e71216c/lib/zig/std/progress.zig:112:46: 0x22c653 in std.progress.Progress.start (test)
        self.timer = try std.time.Timer.start();
                                             ^
/home/ghost/.zig/zig-linux-x86_64-0.5.0+25e71216c/lib/zig/std/special/test_runner.zig:10:37: 0x22835d in std.special.main (test)
    const root_node = progress.start("Test", test_fn_list.len) catch |err| switch (err) {
                                    ^
/home/ghost/.zig/zig-linux-x86_64-0.5.0+25e71216c/lib/zig/std/start.zig:263:37: 0x206a55 in std.start.posixCallMainAndExit (test)
            const result = root.main() catch |err| {
                                    ^
/home/ghost/.zig/zig-linux-x86_64-0.5.0+25e71216c/lib/zig/std/start.zig:127:5: 0x2068cf in std.start._start (test)
    @call(.{ .modifier = .never_inline }, posixCallMainAndExit, .{});
```

### PR DESCRIPTION
**Pull request by alexnask**
Fixes VDSO lookup on WSL.  
Closes #3997

### CODE REVIEW

**Comment by andrewrk** [comment]
@LemonBoy are you willing to give this a review?

@alexnask can you put some comments to explain why the wrapping operators are chosen? This will protect the code against being incorrectly reverted.

**Comment by LemonBoy** [comment]
@alexnask confirmed the symbol lookup succeeds so this is a typical case where two wrongs make a right, the computed `base` offset becomes negative and that makes the following operations work just fine.

**Comment by alexnask** [comment]
I will add some comments tomorrow (although tbh I'm not quite sure what the justification should be other than it appears WSL and potentially older Linux kernels set these values in a way where this arithmetic is correct).

**Comment by LemonBoy** [comment]
> although tbh I'm not quite sure what the justification should be other than it appears WSL and potentially older Linux kernels set these values in a way where this arithmetic is correct

Something like:

```
// Older kernels (and WSL1) pre-link the VDSO ELF image in the upper-half of the address
// space (eg. 0xffffffffff700000), wrapping ops are used here to ensure no overflow check
// is tripped
```

It 's also easy to see why it works, consider the first equation `base = vdso_addr + p_offset - p_vaddr` and then one of the two following ones such as `p = base + dynv[i + 1]`.

Now let's substitute the latter into the former `p = vdso_addr + p_offset - p_vaddr + dynv[i + 1]` and re-arrange it so that its meaning is easier to understand `p = vdso_addr + (dynv[i + 1] - p_vaddr) + p_offset`.

We are re-basing the huge `dynv` value using the huge `p_vaddr` value and then turn this into a file-offset into the ELF image starting at `vdso_addr`.

**Pull request merged**
