### PR TITLE
Add vendor/llvm

### PR DESCRIPTION
**Pull request by winksaville**
Add LLVM as a submodule to zig so that LLVM maybe easily compiled and
different versions of LLVM can be tested as LLVM evolves.

The acutal submodule is vendo/llvm/src which defaults to LLVM-8.0.0 and
vendor/llvm contain a Makefile that allows it to be compiled as simply as
issuing a `make -jN` command. But also allows different versions to be
created by including Makefiles (aka .cfg files) which set variables that
control the build process.

Adds LLVM_LINK_STATIC as a cmake variable and suggests linking
vendor/llvm statically if LLVM isn't found or is the wrong version.
This avoids the need to set RPATH or LD_LIBRARY_PATH.

Modify README.md adding instructions for building LLVM using the
submodule. Also add a link to `#build-llvm` in README.md in error
messages in cmake/Findllvm.cmake.

### CODE REVIEW

**Comment by andrewrk** [comment]
Sorry, I'm not willing to support this.

**Comment by winksaville** [comment]
If I may ask, what is it you don't like?

**Comment by andrewrk** [comment]
It adds git submodules and it modifies/complicates the stage1 build for a near-nonexistent use case.

**Comment by winksaville** [comment]
It's not necessary to use submodules, I could change it. But just to
mention, the developer does not need to use any submodule commands for
regular use cases, such as compiling any of the provided configurations or
even custom configurations.

As for the overall use case, many platforms do not natively support LLVM
8.0.0 as the default so many developers will need to compile it. In
addition, with the implementation I've provided it allows zig developers to
easily test newer/different versions by just adding a ".cfg", just a
makefile fragment, that is included by the actual Makefile. Or pass
variables on the command line.

Finally, if LLVM is installed natively or if manually downloading is
desired, there are no changes to the workflow, it works exactly as before.

I'm happy to answer any questions you may have and work on/discus any
changes you'd like me to make.

**Comment by andrewrk** [comment]
This is the supported process for building LLVM and clang from source: https://github.com/ziglang/zig/wiki/How-to-build-LLVM,-libclang,-and-liblld-from-source

This proposal adds another one, that I'm not convinced is better. It would just add confusion to the build process of Zig.

**Comment by winksaville** [comment]
I understand, but I believe this PR is easier than the current technique
and less error prone because of its fewer steps. For example, last week
when I downloaded the sources I was unable to verify the LLVM source file
because it wasn't signed correctly for use by newer gpg versions used on
Arch Linux. I did work with the Arch Release team and resolved the issue,
but just an example.

Also, the new technique requires less steps and we could streamline it
further by adding a cmake command line variable or eventually automatically
building LLVM when needed.

I'll not push you further if you still wish to keep this closed. Thanks for
considering it.

**Comment by andrewrk** [comment]
Related: #853

**Pull request closed without merging**
