### PR TITLE
stage2: add `zig ar` subcommand

### LINKED ISSUE #7915: ar-compatible command for zig cc
When using `zig cc` when trying to compile [xz][1], I get the following:

```
$ AR="zig build-lib" LD="zig build-lib" CC="zig cc" ./configure
<...>
$ make
<...>
libtool: link: zig build-lib cr .libs/liblzma.a  liblzma_la-tuklib_physmem.o liblzma_la-tuklib_cpucores.o liblzma_la-common.o liblzma_la-block_util.o liblzma_la-easy_preset.o liblzma_la-filter_common.o liblzma_la-hardware_physmem.o liblzma_la-index.o liblzma_la-stream_flags_common.o liblzma_la-vli_size.o liblzma_la-hardware_cputhreads.o liblzma_la-alone_encoder.o liblzma_la-block_buffer_encoder.o liblzma_la-block_encoder.o liblzma_la-block_header_encoder.o liblzma_la-easy_buffer_encoder.o liblzma_la-easy_encoder.o liblzma_la-easy_encoder_memusage.o liblzma_la-filter_buffer_encoder.o liblzma_la-filter_encoder.o liblzma_la-filter_flags_encoder.o liblzma_la-index_encoder.o liblzma_la-stream_buffer_encoder.o liblzma_la-stream_encoder.o liblzma_la-stream_flags_encoder.o liblzma_la-vli_encoder.o liblzma_la-outqueue.o liblzma_la-stream_encoder_mt.o liblzma_la-alone_decoder.o liblzma_la-auto_decoder.o liblzma_la-block_buffer_decoder.o liblzma_la-block_decoder.o liblzma_la-block_header_decoder.o liblzma_la-easy_decoder_memusage.o liblzma_la-filter_buffer_decoder.o liblzma_la-filter_decoder.o liblzma_la-filter_flags_decoder.o liblzma_la-index_decoder.o liblzma_la-index_hash.o liblzma_la-stream_buffer_decoder.o liblzma_la-stream_decoder.o liblzma_la-stream_flags_decoder.o liblzma_la-vli_decoder.o liblzma_la-check.o liblzma_la-crc32_table.o liblzma_la-crc32_fast.o liblzma_la-crc64_table.o liblzma_la-crc64_fast.o liblzma_la-sha256.o liblzma_la-lz_encoder.o liblzma_la-lz_encoder_mf.o liblzma_la-lz_decoder.o liblzma_la-lzma_encoder_presets.o liblzma_la-lzma_encoder.o liblzma_la-lzma_encoder_optimum_fast.o liblzma_la-lzma_encoder_optimum_normal.o liblzma_la-fastpos_table.o liblzma_la-lzma_decoder.o liblzma_la-lzma2_encoder.o liblzma_la-lzma2_decoder.o liblzma_la-price_table.o liblzma_la-delta_common.o liblzma_la-delta_encoder.o liblzma_la-delta_decoder.o liblzma_la-simple_coder.o liblzma_la-simple_encoder.o liblzma_la-simple_decoder.o liblzma_la-x86.o liblzma_la-powerpc.o liblzma_la-ia64.o liblzma_la-arm.o liblzma_la-armthumb.o liblzma_la-sparc.o
error: unrecognized file extension of parameter 'cr'
```

Autotools are running `zig build-lib` with command `cr`, which it does not understand, thus failing.

It would be good to expose a compatible interface to `ar`, so `zig cc` is easier to integrate to existing toolchains.

Barring other issues, once this is resolved, [xz][1] can be built only with gnu make and zig.

[1]: https://tukaani.org/xz/

### PR DESCRIPTION
**Pull request by andrewrk**
The same entrypoint supports the following commands:

 * ar
 * ranlib
 * dlltool
 * lib

For now, our strategy is to bundle the (renamed) `main()` function of
llvm-ar, same as our strategy for `zig clang`. However, as Zig matures,
a goal will be to replace the dependency on LLVM  with our own
implementation of this tool, so that it is available in builds of zig
that do not have LLVM extensions enabled.

This commit also categorizes the subcommands into categories in the
--help menu.

Closes #7915

### CODE REVIEW

**Review by kubkon — APPROVED** [review]
Looks great!

**Comment by daurnimator** [comment]
could you add `objcopy` as a wrapper around `llvm-objcopy` as well?

**Comment by kubkon** [comment]
> could you add `objcopy` as a wrapper around `llvm-objcopy` as well?

Great idea but I’d suggest adding it in a separate PR?

**Comment by andrewrk** [comment]
Please file a separate issue for `objcopy`. We already have some zig code for doing objcopy stuff, however it is available as a build.zig step rather than a sub-command. In the issue we can discuss implementation strategies.

**Pull request merged**
