### PR TITLE
Translate anonymous union/struct

### PR DESCRIPTION
**Pull request by LemonBoy**
Together with #4078 should fix all the problems with #2257

### CODE REVIEW

**Comment by LemonBoy** [comment]
@Vexu The weird behavior you've observed is because clang acts as MSVC-compatible when on Windows. Check out the difference between `clang-9 --target=x86_64-windows-none -Xclang -ast-dump <c file>` and `clang-9 --target=x86_64-windows-gnu -Xclang -ast-dump <c file>`.

**Comment by LemonBoy** [comment]
One more thought, how's a `cImport` user supposed to know the name of the translate-c generated fields?

**Comment by daurnimator** [comment]
A better solution would be available if either of #985 #1214 were accepted+implemented

**Comment by andrewrk** [comment]
> One more thought, how's a `cImport` user supposed to know the name of the translate-c generated fields?

Good question. This is an area where C has a feature that Zig doesn't have. So it makes sense that it's a bit awkward to try to auto-translate it.

**Pull request closed without merging**
