### PR TITLE
std.math.big.int.Const.order 0 == -0

### LINKED ISSUE #17296: std.math.int.big 0 != -0
### Zig Version

0.11.0 and 0.12.0-dev.596+2adb932ad

### Steps to Reproduce and Observed Behavior

`bug.zig`:
```zig
const std = @import("std");

pub fn main() !void {
    var arena_instance = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    const arena = arena_instance.allocator();
    
    var zero = try std.math.big.int.Managed.init(arena);
    try zero.setString(10, "0");
    std.debug.assert(zero.eql(zero));

    {
        var sum = try std.math.big.int.Managed.init(arena);
        try sum.add(&zero, &zero);
        std.debug.assert(zero.eql(sum));
    }

    {
        var diff = try std.math.big.int.Managed.init(arena);
        try diff.sub(&zero, &zero);
        std.debug.assert(zero.eql(diff));
    }
}

```

```sh
$zig run bug.zig
$ zig run bug.zig
thread 757563 panic: reached unreachable code
/home/marler8997/zig/0.12.0-dev.596+2adb932ad/files/lib/std/debug.zig:342:14: 0x220872 in assert (bug)
    if (!ok) unreachable; // assertion failure
             ^
/home/marler8997/git/zigscript/bug.zig:20:25: 0x2206d3 in main (bug)
        std.debug.assert(zero.eql(diff));
                        ^
/home/marler8997/zig/0.12.0-dev.596+2adb932ad/files/lib/std/start.zig:379:37: 0x21ecb5 in posixCallMainAndExit (bug)
            var i: usize = 0;
                                    ^
/home/marler8997/zig/0.12.0-dev.596+2adb932ad/files/lib/std/start.zig:251:5: 0x21e7a1 in _start (bug)
    asm volatile (switch (native_arch) {
    ^
???:?:?: 0x0 in ??? (???)
Aborted (core dumped)
````

### Expected Behavior

`zig run bug.zig` should run succesfully with no output and no assert failure.

### PR DESCRIPTION
**Pull request by luehmann**
Closes #17296

### CODE REVIEW

**Comment by matu3ba** [comment]
Afaiu, the user is not supposed to modify limbs directly unless the user knows exactly what to do as limb modification does not imply that the number representation is normalized.
Afaiu, the correct fix is to normalize after applying one high level operations (add, sub, mul etc).

See also https://github.com/ziglang/zig/pull/7926. Unless, which would be suprising to me, somebody wants users to normalize after every operation.

Would be nice to add a top level comment on what kind of operations are high and what are low level as to guide further contributors to do the correct thing directly.

**Comment by luehmann** [comment]
Currently `eqlZero` describes zero as all limbs being zero; independent of sign or whether the limbs are normalized.

Following that definition and the doc comment of `order`

> Returns `math.Order.lt`, `math.Order.eq`, `math.Order.gt` if `a < b`, `a == b` or `a > b` respectively.

`order` should handle both zeroes correctly IMO.

I don't see any benefits of making one of `-0` and `+0` an illegal state.

---

What I indeed find confusing is that #7926 changed `eqlZero` to its current implementation but the doc comment on limbs is still the following:

> Zero is represent as Managed.len() == 1 with limbs[0] == 0.

**Comment by matu3ba** [comment]
> I don't see any benefits of making one of -0 and +0 an illegal state.

The idea is that less branching for common operations means more performance.

> the doc comment on limbs is still the following

There is no top level  doc comment introducing the implementation idea.

cc @tiehuis: Would you be so kind to clarify and correct me, where I am wrong?

**Comment by tiehuis** [comment]
I agree with both comments.
 - We should normalize after every operation
 - The user shouldn't care about the internal representation and -0 should equal +0

The main issue is the internal representation allows both states. Requiring normalisation is good but this doesn't actual resolve the issue, as a user could just call `a.negate()` to get into the same state. I expect there are a number of edge cases where `-0` would have odd behaviour.

I will merge this for now as its better than status quo.

---

A future follow-up should look at changing the internal representation to disallow this. A good way to encode this would be to squash the sign + length into one field and allow the number of limbs be negative (absolute value is the length), indicating a negative integer. This is what GMP does and would ensure we only have one 0 representation: https://gmplib.org/manual/Integer-Internals/.

This has the bonus of reducing the `Mutable` struct size which is important. This is already done for the `Managed` int type where the length+sign is packed, however the same issue is still present as we do not use twos-complement and so still have the dual representation.

**Pull request merged**
