### PR TITLE
std.builtin.panic(uefi): usability improvements

### PR DESCRIPTION
**Pull request by fifty-six**
Inspired by the review in #16094. cc @wooster0?

### CODE REVIEW

**Comment by fifty-six** [comment]
Are there any blockers for this - or did it just fall into backlog? Not a huge deal either way, but it's been a bit so I wanted to check.

**Review by Vexu — APPROVED** [review]
Why does the first commit say "also outputs to std_err" when that was already done and what was added was outputting to con_out?

**Comment by fifty-six** [comment]
Oh whoops, just me writing the wrong thing down — I'll rewrite the commit description

**Comment by fifty-six** [comment]
Fixed that - and rebased onto the current master commit

**Comment by Vexu** [comment]
Could you also give a quick reasoning as to why you want to do so?

**Comment by fifty-six** [comment]
Yeah sure, added.

**Comment by Vexu** [comment]
```
+- test-fmt
   +- zig fmt --check failure
error: /home/ci/actions-runner1/_work/zig/zig/lib/std/builtin.zig: non-conforming formatting
```
You need to fix the formatting.

**Comment by fifty-six** [comment]
Ah ok

**Pull request merged**
