### PR TITLE
ArrayList: ptrAt function returns pointer to item at given index

### PR DESCRIPTION
**Pull request by giann**
Most of the time, I want to modify something in the list and lose 1 hour figuring out why it did nothing :)

### CODE REVIEW

**Comment by FireFox317** [comment]
Why would `toSlice()` not work? A slice is just a pointer and a length, so that would suffice. You just have to make sure that you capture the element by pointer: `for(list.toSlice()) |*elem| { doStuff(); }`

**Comment by giann** [comment]
> Why would `toSlice()` not work? A slice is just a pointer and a length, so that would suffice. You just have to make sure that you capture the element by pointer: `for(list.toSlice()) |*elem| { doStuff(); }`

To get the `i`th element directly? Not sure I get your remark.

**Comment by andrewrk** [comment]
This makes sense since we have `at`. So I'm happy to merge.

But just noting that I'm considering the following breaking change in the future:

 * Rename `items` field to `items_buffer`, to make it less likely to accidentally reference undefined elements.
 * Rename `toSlice()` to `items()` and make it `var` so that it works with both const and non-const.
 * Remove both `at` and `ptrAt`. Prefer to use `list.items()[x]` which can be used both as an l-value and an r-value.

**Comment by andrewrk** [comment]
Extracted my proposal from above comment into #4000.

**Comment by giann** [comment]
Ah great! Some refactoring to do again! :)

**Pull request merged**
