### PR TITLE
WIP Interface Reform (see: #1829)

### PR DESCRIPTION
**Pull request by tgschultz**
Update the standard library to use a new interface pattern that should be more friendly to the optimizer. Provides abstracted (type-erased) and non-abstracted interfaces.

Note: the way `async<allocator>` is currently implemented appears to be incompatible with the this pattern. Since the async rewrite (#1260) will eliminate allocators for `async`, I have implemented an ugly hack workaround that wraps the new interface pattern with the old one.

Current plan:
- [x] Update mem.Allocator interface
  - [x] Update test cases, self hosted, other non-std code
- [x] Update io.(In|Out)Stream interfaces
  - [x] Update test cases, self hosted, other non-std code

@tiehuis will take care of these
~- [ ] Update Random interface~
  ~- [ ] Update test cases, self hosted, other non-std code~

This may end up being a separate PR:
- [ ] Update all stdlib uses of interfaces to allow for use of non-abstracted version

We may also decide to move the 'convenience' functions currently implemented in the generated *Interface struct out into the broader namespace as regular functions.

### CODE REVIEW

**Comment by tiehuis** [comment]
I've got a local copy of the randomizer changes nearly done so you can leave that to me if you like.

**Comment by andrewrk** [comment]
It'll happen. Thanks for being patient with my copy elision stuff. I'm at 327/518 behavioral tests passing in my branch. I'm hoping to conclude the merge within the next week.

**Comment by tgschultz** [comment]
It was async., I'd missed some spots because I wasn't grepping properly. I've built a new VM server and now have a much less constrained environment, so I can run tests locally and work through stuff like this.

**Comment by tgschultz** [comment]
Unless he's changed his mind, I'm going to leave Random to @tiehuis .

**Comment by tiehuis** [comment]
Yeah I have it done although I've had some issues with attempting to get it to work at compile-time as the old method was able to. Will make a PR when this is merged and I can rebase off this.

**Comment by Hejsil** [comment]
@tiehuis Is [this](https://github.com/Hejsil/zig-interface/issues/1) related? The vtable dynamic dispatch doesn't work at comptime, but any static dispatch should work just fine right?

**Comment by tiehuis** [comment]
Yes, that is exactly the issue. Didn't see that. It isn't a huge deal right now, the only place that was depending on this was AutoHashMap which I'm sure we can perform at runtime until this is figured out.

**Comment by Hejsil** [comment]
@tiehuis Could the signature for `autoHash`s rng parameter be of type `var` and then we pass a statically known `Random` implementer? This should work at `comptime`

**Comment by andrewrk** [comment]
What should we do with this PR? What can I do to help?

**Comment by tgschultz** [comment]
My plan was to wait on this until after the co-routing rewrite, as currently a pretty ugly hack is used to deal with async's allocator handling. If we want to merge before then and are ok with the hack (or have a better idea) then I can rebase on current master, clean it up, add @tiehuis's changes and it should be ready to go.

**Comment by andrewrk** [comment]
Waiting until after the coroutine rewrite sounds reasonable. I'll keep that in mind. It's planned to happen like this:

 * 0.4.0 released on April 8th (estimated date; final date depends on llvm 8.0.0 official release)
 * Blog post with detailed Zig Package Manager proposal. I do reserve the right to re-arrange this to be the last bullet point in this list, since it depends on the following 2 items.
 * Non-copy semantics part 1a.
 * Coroutine rewrite.

These last 2 bullet points are long overdue. I'm planning on giving them laser focus after the release.

**Comment by andrewrk** [comment]
I made a note in https://github.com/ziglang/zig/issues/2377#issuecomment-487662136 to revisit this work-in-progress code once the stuff that it is blocking on is complete. Until then I'm going to close this.

**Pull request closed without merging**
