### PR TITLE
std.math.sqrt_int: fixed odd size integers types

### PR DESCRIPTION
**Pull request by Virv12**
I found a bug in the implementation of std.math.sqrt_int.
The implementation assumed the number of bits of the type was even.
I added some tests and fixed the bug.
I also added a shortcut for small number of bits to prevent edge cases.

### CODE REVIEW

**Comment by ehaas** [comment]
Perhaps this should be addressed as a separate PR but the current implementation (both in master and this PR) enters an infinite loop if the argument to `sqrt` is a runtime-known negative integer. e.g.

```zig
test "infinite loop" {
    var x: i8 = -1;
    _ = @import("std").math.sqrt(x);
}
```

At the very least this should be documented; perhaps instead the negative integer case should be checked and `@panic` called? Alternatively the signature would have to be changed to accomodate an error value.

**Comment by jedisct1** [comment]
> At the very least this should be documented; perhaps instead the negative integer case should be checked and `@panic` called? Alternatively the signature would have to be changed to accommodate an error value.

Having an `assert()` for that case would be reasonable.

**Comment by jedisct1** [comment]
Would you mind rebasing this and fixing the indentation?

**Comment by ehaas** [comment]
> > At the very least this should be documented; perhaps instead the negative integer case should be checked and `@panic` called? Alternatively the signature would have to be changed to accommodate an error value.
> 
> Having an `assert()` for that case would be reasonable.

It looks like that's no longer necessary; #8410 changed sqrt etc to only take unsigned integers.

**Comment by Virv12** [comment]
> Would you mind rebasing this and fixing the indentation?

I rebased it and the indentation looks good to me.
Is there anything else to do before merging?

**Pull request merged**
