### PR TITLE
std.fmt: 'any' specifier forces default formatting

### PR DESCRIPTION
**Pull request by hryx**
_Note: this a relatively low-effort change based on a brief conversation. I've made it a draft because there is room for discussion and validation of the use case._

At the moment, a custom formatting function has no easy way to fall back to default behavior, which is a pain for complex user types that only want to override formatting given certain values or format options. [In a Discord conversation](https://discord.com/channels/605571803288698900/1089691305430499428/1089988769119223920), it was proposed that the `any` specifier would be a reasonable solution to this.

I noticed a [suggestion to remove custom format functions](https://github.com/ziglang/zig/issues/7948#issuecomment-968594277) in general, so I assume this wouldn't be seen as a permanent solution.

### CODE REVIEW

**Comment by Jarred-Sumner** [comment]
As-is, this will subtly break existing projects and libraries

What if "use the default formatter" had an explicit name? Example: `{default}` or `{type}` or `{id}`

**Comment by hryx** [comment]
To be transparent here, I should say that I haven't thought thoroughly about the impact, and the issue doesn't currently affect me directly — it was a one-off based on the Discord conversation. I've updated the description to reflect that.

@Jarred-Sumner What are some specific ways in which this might break projects?

> What if "use the default formatter" had an explicit name?

In general I'm open to new format specifiers. I had it in my head that there was a conservative attitude toward new specifiers, but I can't find any hard evidence of that in past PRs/issues.

**Comment by Inve1951** [comment]
Test `formatType max_depth` is failing [here](https://github.com/ziglang/zig/blob/80e2c7283d2cdce171f3895b65e6b453d7844011/lib/std/fmt.zig#L2728) and I suspect the problem lies on [line 597](https://github.com/ziglang/zig/blob/80e2c7283d2cdce171f3895b65e6b453d7844011/lib/std/fmt.zig#L597).

There a structs child fields are formatted with `fmt = "any"`, which if the child itself is a struct translates to `actual_fmt = ""` through a call to `defaultSpec`.
The failing test relies on the custom format function getting called under these circumstances but the change in this PR explicitely bypasses it.

Changing line 597 to this might remedy the issue:
```zig
try formatType(
  @field(value, f.name),
  comptime if (std.mem.eql(u8, fmt, ANY)) ANY else defaultSpec(@TypeOf(@field(value, f.name))),
  options,
  writer,
  max_depth - 1,
);
```
However I have not tested it.

**Comment by andrewrk** [comment]
Closing abandoned draft

**Pull request closed without merging**
