### PR TITLE
`tsan`: Update to LLVM 19.1.0.

### PR DESCRIPTION
**Pull request by alexrp**
After this, in theory, TSan support should work for:

* aarch64, aarch64_be
* loongarch64
* mips64, mips64el
* powerpc64, powerpc64le
* riscv64
* s390x
* x86_64

### CODE REVIEW

**Comment by andrewrk** [comment]
can you share your testing methodology?

**Comment by alexrp** [comment]
I tried the obvious Zig/C/C++ hello world just to make sure TSan actually builds and links for the aforementioned architectures. For whatever reason, QEMU doesn't seem to like TSan binaries so I could only actually run the native ones, but these worked fine.

As for the compiler itself, I get this on my machine both before/after the update:

```
Program received signal SIGSEGV, Segmentation fault.
__tsan::SlotLock (thr=0x7ffff2f12c40) at lib/tsan/tsan_rtl.cpp:366
366       slot->mtx.Lock();
(gdb) p slot
$1 = (__tsan::TidSlot *) 0x0
(gdb) bt
#0  __tsan::SlotLock (thr=0x7ffff2f12c40) at lib/tsan/tsan_rtl.cpp:366
#1  0x00005555595d4b79 in __tsan::SlotLocker::SlotLocker (thr=0x7ffff2f12c40, thr@entry=0x7fffe826877c, recursive=false,
    this=<optimized out>) at lib/tsan/tsan_rtl.h:641
#2  __tsan::Release (thr=thr@entry=0x7ffff2f12c40, pc=pc@entry=93825059465258, addr=addr@entry=140737088227196)
    at lib/tsan/tsan_rtl_mutex.cpp:467
#3  0x0000555559572870 in guard_release (thr=0x7ffff2f12c40, pc=93825059465258, g=0x7fffe826877c, v=1)
    at lib/tsan/tsan_interceptors_posix.cpp:903
#4  ___interceptor_pthread_once (o=0x7fffe826877c, f=0x7fffe80c9e50) at lib/tsan/tsan_interceptors_posix.cpp:1586
#5  0x00007fffe80ca3bb in std::locale::facet::_S_get_c_locale() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007fffe80f1fef in std::ctype<char>::ctype(unsigned short const*, bool, unsigned long) ()
   from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007fffe80cb15a in std::locale::_Impl::_Impl(unsigned long) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007fffe80cbf14 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007fffe80cbfc7 in std::locale::locale() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007fffe80c8dc2 in std::ios_base_library_init() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x00007fffe80b3614 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#12 0x00007ffff7fcb36e in call_init (l=<optimized out>, argc=argc@entry=2, argv=argv@entry=0x7fffffffe138,
    env=env@entry=0x7fffffffe150) at ./elf/dl-init.c:90
#13 0x00007ffff7fcb473 in call_init (env=<optimized out>, argv=<optimized out>, argc=<optimized out>, l=<optimized out>)
    at ./elf/dl-init.c:136
#14 _dl_init (main_map=0x7ffff7ffe2d0, argc=2, argv=0x7fffffffe138, env=0x7fffffffe150) at ./elf/dl-init.c:137
#15 0x00007ffff7fe4b70 in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#16 0x0000000000000002 in ?? ()
#17 0x00007fffffffe56c in ?? ()
#18 0x00007fffffffe594 in ?? ()
#19 0x0000000000000000 in ?? ()
```

I'm assuming this is just some nonsense specific to my machine since IIRC other people have been using TSan on the compiler without issue? In any event, it does mean I can't test this use case.

Let me know if there's anything else that might be a good idea to test as part of this.

**Comment by Rexicon226** [comment]
> I'm assuming this is just some nonsense specific to my machine since IIRC other people have been using TSan on the compiler without issue?

Can confirm before this PR and after #21379 I get no TSan errors when running it on the compiler itself.

**Comment by andrewrk** [comment]
OK, so as a smoke test, at least someone should verify that tiny_race.c from https://clang.llvm.org/docs/ThreadSanitizer.html has the expected behavior before merging.

As for your situation, it seems related to incompatibility between libstdc++ (gcc) and clang libc++. If you built the compiler with zig build and used llvm libs provided by zig-bootstrap, you'll probably get TSAN working.

**Comment by alexrp** [comment]
```console
❯ zig4 cc tiny_race.c -fsanitize=thread -g -O1 -target x86_64-linux-gnu
❯ ./a.out
==================
WARNING: ThreadSanitizer: data race (pid=143370)
  Write of size 4 at 0x5555565ce3a0 by main thread:
    #0 main /home/alexrp/Source/stuff/tiny_race.c:10:10 (a.out+0xf4722)

  Previous write of size 4 at 0x5555565ce3a0 by thread T1:
    #0 Thread1 /home/alexrp/Source/stuff/tiny_race.c:4:10 (a.out+0xf46d9)

  Location is global 'Global' of size 4 at 0x5555565ce3a0 (a.out+0x107a3a0)

  Thread T1 (tid=143372, finished) created by main thread at:
    #0 pthread_create /home/alexrp/Source/zig/lib/tsan/tsan_interceptors_posix.cpp:1023:3 (a.out+0x5cab4)
    #1 main /home/alexrp/Source/stuff/tiny_race.c:9:3 (a.out+0xf4713)

SUMMARY: ThreadSanitizer: data race /home/alexrp/Source/stuff/tiny_race.c:10:10 in main
==================
ThreadSanitizer: reported 1 warnings
```

**Comment by andrewrk** [comment]
OK, good, thank you!

**Pull request merged**
