### PR TITLE
Fixes #7173

### LINKED ISSUE #7173: Peer type resolution: resolve unsigned ints with larger signed ints
Currently, the rules for subtyping say that `uN` is a subtype of `iM` if and only if M is strictly larger than N.  For example, this code works:
```zig
fn f(value: i32) void {}

var x: u31 = 7;
var y: i32 = x; // x upcasts to the larger i32 type
f(x); // x upcasts to the larger i32 type
```

However, this subtype relationship isn't respected by peer type resolution, so this is an error:
```zig
var x: u8 = 7;
var y: i32 = x;
var z = x + y;
```
Results in:
```
./test.zig:4:15: error: incompatible types: 'u8' and 'i32'
    var z = x + y;
              ^
```

It would be nice if this worked.

This is either a proposal or a bug report, depending on whether peer type resolution is intended to exactly follow the subtyping relation.

### PR DESCRIPTION
**Pull request by g-w1**
This deals with peer type resolution, checking if the two types are different signed and if they are diving the signed one by two to see if they are compatible.

### CODE REVIEW

**Comment by LemonBoy** [comment]
> This deals with peer type resolution, checking if the two types are different signed and if they are diving the signed one by two to see if they are compatible.

This check makes absolutely no sense.
You just need to make sure the type conversion is lossless and correct.

**Comment by g-w1** [comment]
I am not sure what you mean. If they are different signed, then the signed one's number of bits has to be 2 * the unsigned one's number of bits in order for it to be lossless, right.

In hindsight, I realize that I made it seem that I was dealing with the values instead number of bits of the types.
Sorry about the confusion.

Were you saying that the code made no sense, or my explanation made no sense?

**Comment by LemonBoy** [comment]
> If they are different signed, then the signed one's number of bits has to be 2 * the unsigned one's number of bits in order for it to be lossless, right.

No, you need a single extra bit if you're going from unsigned to signed.
Consider a `i8` value, it can accept values ranging from `-128` to `127` and is thus compatible with unsigned types of size less or equal to `i7`. Trying to shove a `u8` in a `i8` is _not_ safe as values greater than 127 are interpreted as negative (read up on two's complement).

Implicit casting from signed to unsigned is fine in theory but I wouldn't enable it for peer type resolution (and I doubt it's implicitly done by the compiler) because unless the value is positive you're in for some unexpected results.

**Comment by g-w1** [comment]
Ah, Ill only allow unsigned to signed. Thanks

**Comment by LemonBoy** [comment]
Come on, look again at the comparisons you wrote...
Can you see they are all checking that `cur` is wider than `prev`?

The check simplifies to:
If they're both signed or unsigned or prev is unsigned and cur is signed then check that the latter is wider than the former.

**Pull request merged**
