### PR TITLE
macho+zld: fix misc alignment issues when parsing object files in archives

### LINKED ISSUE #14558: bad alignment cast in macho linking code
A user on IRC reported the following stack trace against zig 0.10.1:

```
thread 473118 panic: incorrect alignment
/private/tmp/nix-build-zig-0.10.1.drv-0/source/src/link/MachO/Object.zig:114:72: 0x1030338ab in link.MachO.Object.parse (zig2)
                    @alignCast(@alignOf(macho.nlist_64), &self.contents[symtab.symoff]),
                                                                       ^
/private/tmp/nix-build-zig-0.10.1.drv-0/source/src/link/MachO/Archive.zig:230:21: 0x1030485f7 in link.MachO.Archive.parseObject (zig2)
    try object.parse(gpa, cpu_arch);
                    ^
/private/tmp/nix-build-zig-0.10.1.drv-0/source/src/link/MachO/zld.zig:1056:55: 0x102d4af7f in link.MachO.zld.Zld.resolveSymbolsInArchives (zig2)
                const object = try archive.parseObject(gpa, cpu_arch, offsets.items[0]);
                                                      ^
/private/tmp/nix-build-zig-0.10.1.drv-0/source/src/link/MachO/zld.zig:4219:41: 0x102ad5443 in link.MachO.zld.linkWithZld (zig2)
        try zld.resolveSymbolsInArchives(&resolver);
                                        ^
/private/tmp/nix-build-zig-0.10.1.drv-0/source/src/link/MachO.zig:427:44: 0x10281667f in link.MachO.flush (zig2)
        .one_shot => return zld.linkWithZld(self, comp, prog_node),
                                           ^
/private/tmp/nix-build-zig-0.10.1.drv-0/source/src/link.zig:797:72: 0x10281345b in link.File.flush (zig2)
            .macho => return @fieldParentPtr(MachO, "base", base).flush(comp, prog_node),
                                                                       ^
/private/tmp/nix-build-zig-0.10.1.drv-0/source/src/Compilation.zig:2516:24: 0x10278ca2f in Compilation.flush (zig2)
    comp.bin_file.flush(comp, prog_node) catch |err| switch (err) {
                       ^
/private/tmp/nix-build-zig-0.10.1.drv-0/source/src/Compilation.zig:2480:27: 0x10277fb67 in Compilation.update (zig2)
            try comp.flush(main_progress_node);
                          ^
/private/tmp/nix-build-zig-0.10.1.drv-0/source/src/main.zig:3361:20: 0x102701857 in main.updateModule (zig2)
    try comp.update();
                   ^
/private/tmp/nix-build-zig-0.10.1.drv-0/source/src/main.zig:3028:17: 0x10263e09f in main.buildOutputType (zig2)
    updateModule(gpa, comp, hook) catch |err| switch (err) {
                ^
/private/tmp/nix-build-zig-0.10.1.drv-0/source/src/main.zig:230:31: 0x1025c6f6b in main.mainArgs (zig2)
        return buildOutputType(gpa, arena, args, .{ .build = .Exe });
                              ^
/private/tmp/nix-build-zig-0.10.1.drv-0/source/src/stage1.zig:56:24: 0x1025c68a3 in main (zig2)
        stage2.mainArgs(gpa, arena, args) catch unreachable;
                       ^
```

I examined the corresponding master branch code, and it looks to me like the problem is still there:

https://github.com/ziglang/zig/blob/289e8fab7949bebfc39209b86a69317a53e747f8/src/link/MachO/Object.zig#L147

cc @kubkon

### LINKED ISSUE #14559: panic: index out of bounds in link.MachO.ZldAtom.resolveRelocsArm64
### Zig Version

0.10.1

### Steps to Reproduce and Observed Behavior

After fixing the `@alignCast` issue in #14558, stage3 fails to build on aarch64-darwin with a different error:
```
thread 666841 panic: index out of bounds
/private/tmp/nix-build-zig-0.10.1.drv-0/source/src/link/MachO/ZldAtom.zig:793:53: 0x105a2bd27 in link.MachO.ZldAtom.resolveRelocsArm64 (zig2)
                    mem.readIntLittle(i64, atom_code[rel_offset..][0..8])
                                                    ^
/private/tmp/nix-build-zig-0.10.1.drv-0/source/src/link/MachO/ZldAtom.zig:483:39: 0x105a2719f in link.MachO.ZldAtom.resolveRelocs (zig2)
        .aarch64 => resolveRelocsArm64(zld, atom_index, atom_code, atom_relocs, reverse_lookup, ctx),
                                      ^
/private/tmp/nix-build-zig-0.10.1.drv-0/source/src/link/MachO/zld.zig:1736:43: 0x1056db723 in link.MachO.zld.Zld.writeAtoms (zig2)
                    try Atom.resolveRelocs(
                                          ^
/private/tmp/nix-build-zig-0.10.1.drv-0/source/src/link/MachO/zld.zig:4290:27: 0x10545e997 in link.MachO.zld.linkWithZld (zig2)
        try zld.writeAtoms(reverse_lookups);
                          ^
/private/tmp/nix-build-zig-0.10.1.drv-0/source/src/link/MachO.zig:427:44: 0x10519e6d7 in link.MachO.flush (zig2)
        .one_shot => return zld.linkWithZld(self, comp, prog_node),
                                           ^
/private/tmp/nix-build-zig-0.10.1.drv-0/source/src/link.zig:797:72: 0x10519b4b3 in link.File.flush (zig2)
            .macho => return @fieldParentPtr(MachO, "base", base).flush(comp, prog_node),
                                                                       ^
/private/tmp/nix-build-zig-0.10.1.drv-0/source/src/Compilation.zig:2516:24: 0x105114a87 in Compilation.flush (zig2)
    comp.bin_file.flush(comp, prog_node) catch |err| switch (err) {
                       ^
/private/tmp/nix-build-zig-0.10.1.drv-0/source/src/Compilation.zig:2480:27: 0x105107bbf in Compilation.update (zig2)
            try comp.flush(main_progress_node);
                          ^
/private/tmp/nix-build-zig-0.10.1.drv-0/source/src/main.zig:3361:20: 0x1050898af in main.updateModule (zig2)
    try comp.update();
                   ^
/private/tmp/nix-build-zig-0.10.1.drv-0/source/src/main.zig:3028:17: 0x104fc60f7 in main.buildOutputType (zig2)
    updateModule(gpa, comp, hook) catch |err| switch (err) {
                ^
/private/tmp/nix-build-zig-0.10.1.drv-0/source/src/main.zig:230:31: 0x104f4efc3 in main.mainArgs (zig2)
        return buildOutputType(gpa, arena, args, .{ .build = .Exe });
                              ^
/private/tmp/nix-build-zig-0.10.1.drv-0/source/src/stage1.zig:56:24: 0x104f4e8fb in main (zig2)
        stage2.mainArgs(gpa, arena, args) catch unreachable;
                       ^
```

### Expected Behavior

For it to link correctly :)

### PR DESCRIPTION
**Pull request by kubkon**
Closes #14559 
Closes #14558

### CODE REVIEW

**Comment by mikdusan** [comment]
can you audit these two `@alignCast` uses in link codebase?

https://github.com/ziglang/zig/blob/a5b34a61ab61882bf55d87e4cbc8186215ecf320/src/link/MachO/Dylib.zig#L169

and

https://github.com/ziglang/zig/blob/a5b34a61ab61882bf55d87e4cbc8186215ecf320/src/link/MachO/zld.zig#L2707

**Comment by kubkon** [comment]
> can you audit these two `@alignCast` uses in link codebase?
> 
> https://github.com/ziglang/zig/blob/a5b34a61ab61882bf55d87e4cbc8186215ecf320/src/link/MachO/Dylib.zig#L169
> 
> and
> 
> https://github.com/ziglang/zig/blob/a5b34a61ab61882bf55d87e4cbc8186215ecf320/src/link/MachO/zld.zig#L2707

These are guaranteed to be at aligned adress/offset as they are in final linked images. We only need to loose up requirement in object files that are extracted from static archives, i.e., only casts in `Object.zig`.

**Comment by kubkon** [comment]
Looking at this some more, we should force appropriate alignment for the `locals_buf` slab which just so happens to always be 8-byte aligned upon `alloc`, but might not be guaranteed on non-64bit hosts.

**Comment by kubkon** [comment]
@mikdusan we now ensure the local symbols buffer when re-reading from file is appropriately aligned, thus avoiding a potential runtime panic. Thanks for spotting that one!

**Pull request merged**
