### PR TITLE
std.os: fix execv* doc comment

### PR DESCRIPTION
**Pull request by alichraghi**

### CODE REVIEW

**Review by Vexu — CHANGES_REQUESTED** [review]
Those lines refer to now deleted `os.execvp?e` functions and should be deleted instead.

**Comment by alichraghi** [comment]
they aren't deleted. moved to `std.process`

**Review by andrewrk — CHANGES_REQUESTED** [review]
This is a lower level API than std.process so the doc comments should be independent from referencing the higher level API.

**Comment by andrewrk** [comment]
Thanks!

**Pull request merged**
