### PR TITLE
Fix Linking for MinGW Libraries on *-windows-gnu Targets

### LINKED ISSUE #7799: Windows: Linking step fails when trying to use MinGW SDL2 library (@cimport + gnu target)
I welcome a better/more descriptive title; this seems to be a change that was introduced in 7.0, but it might entirely be user error (I.e. expected behaviour)

In 6.0 I've been building using the `...mingw.tar.gz` [SDL2 development libraries](https://www.libsdl.org/download-2.0.php) and `@cInclude` successfully inside Cygwin, but from Zig 7.0 onwards I get the error `lld-link: error: could not open 'sdl2.lib': no such file or directory`.

There are `lib` files in the SDL `...VC.zip`, but I'm specifying `.gnu` in build.zig, and aren't entirely sure why the linker would be searching for a `.lib`.

My project structure looks like:
```
test project
  |_ deps
      |_ include
          |_ SDL2
          <SDL2 includes>
      |_lib
      <SDL2 libs>
  |_ src
  build.zig
```

With a `build.zig` (which might be crazy):
```
const Builder = @import("std").build.Builder;
const std = @import("std");

pub fn build(b: *Builder) void {
    const mode = b.standardReleaseOptions();
    const exe = b.addExecutable("raycast", "src/main.zig");
    exe.setBuildMode(mode);
    exe.linkSystemLibrary("c");
    exe.linkSystemLibrary("sdl2");

    exe.addIncludeDir("deps/include");
    exe.addLibPath("deps/lib");
    exe.linkSystemLibrary("ole32");
    exe.linkSystemLibrary("oleaut32");
    exe.linkSystemLibrary("imm32");
    exe.linkSystemLibrary("winmm");
    exe.linkSystemLibrary("version");
    exe.linkSystemLibrary("gdi32");
    exe.linkSystemLibrary("setupapi");

    exe.setTarget(.{
        .cpu_arch = .x86_64,
        .os_tag = .windows,
        .abi = .gnu,
    });

    exe.install();

    const run_cmd = exe.run();
    run_cmd.step.dependOn(b.getInstallStep());

    const run_step = b.step("run", "Run the app");
    run_step.dependOn(&run_cmd.step);
}
```

With 0.6, this builds fine, with the linking step looking like this:

```
lld
-ERRORLIMIT:0
-NOLOGO
-DEBUG
-STACK:16777216
-MACHINE:X64
-OUT:C:\source\zig\raycast\zig-cache\o\hji2-6cGpLt0tN12_aezAG0SaiT_66qmOu-d_XAIBiiwi3rwoEnVIyRa3CcvbP0O\raycast.exe
-LIBPATH:deps/lib
C:\source\zig\raycast\zig-cache\o\hji2-6cGpLt0tN12_aezAG0SaiT_66qmOu-d_XAIBiiwi3rwoEnVIyRa3CcvbP0O\raycast.o
-SUBSYSTEM:console
-lldmingw
-ALTERNATENAME:__image_base__=__ImageBase
C:\Users\XXX\AppData\Local\zig\stage1\o\MQ6v78HnKTYFuv4SuWHexRBU5Gv70vRAYNDS30T15CMDvzk0ob_QUEAmvFEUUnY0\crt2.o
C:\Users\XXX\AppData\Local\zig\stage1\o\hQqJBKBJAMYLXNxMLc5ZzJ8avBY0OsvRt-Rr35zSalM8VMIUE3ibJrcWISUJP_IA\libmingw32.a
C:\Users\XXX\AppData\Local\zig\stage1\o\DvF3C744f2bqPu7s6Dx1JP27KTLt4x6PHR1itrBuUR8bIHyVO4CmpM0kbRV65vGh\libmingwex.a
C:\Users\XXX\AppData\Local\zig\stage1\o\84NTrwBQEQJG_7LlREF3-uMsI5wPPaOx-tJS2s4LhTZ7Gubnc2LS68xptha_F8CI\libmsvcrt-os.a
C:\Users\XXX\AppData\Local\zig\stage1\o\lOyjyshSkL3QG9wKqX9TZhZu0LV8X2_cl-ZhZuYOvIrIY5fmoLCz2BWY0xPLRdzO\advapi32.lib
C:\Users\XXX\AppData\Local\zig\stage1\o\GsgUr2ekZR4I4p9AXA5OV96ZaXviD_awS0gAPVUR7bJQ8qCGRZsOo6m_GjNFZ7zU\gdi32.lib
C:\Users\XXX\AppData\Local\zig\stage1\o\KZl7CIg2VmxtOo_c7_f8cduTMZM24B376o7EIv6_j6d3F4y9jEMsdUX_fmx2G0R9\imm32.lib
C:\Users\XXX\AppData\Local\zig\stage1\o\yEZKYysLwM-WZ3wGElKbLOj8dUygm0lAKI8NuiR-73Vi1rb6RMs_Sa9Zt1LGJxXS\kernel32.lib
C:\Users\XXX\AppData\Local\zig\stage1\o\KN2NdwZPmK5WcJ13ZpZL-dXoYHBIVcrQnwLM1xIdXkne0DBeYC0j4oO2LNKtWawR\msvcrt.lib
C:\Users\XXX\AppData\Local\zig\stage1\o\t46_cf5lqS6gETj2Hh_5J1RFIRovx-_rIHEalvjzcFCSsgUJKJBTgVHifC65Pv3L\ntdll.lib
C:\Users\XXX\AppData\Local\zig\stage1\o\GTAYDxEL8XmTCQru293u2LyJFU9BAAU-9WsA45DaNvV1mQ0IWxkrXJ051yjRnAfC\ole32.lib
C:\Users\XXX\AppData\Local\zig\stage1\o\mBFZDwDZwiE2Nagy63xGEzh-g-XPWusqJhAdg4GTdtDpLxcMj_H8dPGR4pfQ7klv\oleaut32.lib
C:\Users\XXX\AppData\Local\zig\stage1\o\LVTdhOrgQOGYKJ5HGHnMnPtAHV2eIOEF02TwaXih2b92rzpkOKbQE7XvB4KcGmHw\setupapi.lib
C:\Users\XXX\AppData\Local\zig\stage1\o\LiPf2O4EFJjw7buFP9B_qgwa4oCkHQLRkGHv6NWzhrMfuKTu6QLbIXWnJ-LQBI1o\shell32.lib
C:\Users\XXX\AppData\Local\zig\stage1\o\6BD1fzpHe_0X7wfkXS7w68pjCX-eOgYVPBKqQ42TT1hD_1l3qXGvU6G_HRjUcTRL\user32.lib
C:\Users\XXX\AppData\Local\zig\stage1\o\E2SnDXquZ2VJIvinfCduSzsHRF-ivm1Cl4TJAWjzcAVmqASNhjFLGHx234_YtzSN\version.lib
C:\Users\XXX\AppData\Local\zig\stage1\o\A4_962b1dc3hPwW35WVMJhFknQIl_-XmdnyAzrNIdIMv--Vb37JnNLvSvXuzPRWk\winmm.lib
C:\Users\XXX\AppData\Local\zig\stage1\o\8Se6jhg29U4GR4w3AaYvZbmnak-9GMEz2Rq0jlYQvANWWpvl8MDIMDy8QKL9gCEx\libcompiler_rt.a
libsdl2.a
```

When using the latest version from `master` I get the following (I'm not sure why it's looking for an `sdl2.lib`):
```
lld-link
-ERRORLIMIT:0
-NOLOGO
-DEBUG
-STACK:16777216
-MACHINE:X64
-OUT:C:\source\zig\raycast\zig-cache\o\1240779ef840c916b05c4db508e87faa\raycast.exe
-LIBPATH:deps/lib
C:\source\zig\raycast\zig-cache\o\1240779ef840c916b05c4db508e87faa\raycast.o
-SUBSYSTEM:console
-lldmingw
-ALTERNATENAME:__image_base__=__ImageBase
C:\Users\XXX\AppData\Local\zig\o\8775b519e307056a5874b9b0a4be4fd5\crt2.o
C:\Users\XXX\AppData\Local\zig\o\1f53bc99d3b393d2950605e723006a1a\mingw32.lib
C:\Users\XXX\AppData\Local\zig\o\b3ea6083722aba6f2a9ef411f685225c\mingwex.lib
C:\Users\XXX\AppData\Local\zig\o\b3440919bd7f63ba74e48c4a80c7f9e6\msvcrt-os.lib
C:\Users\XXX\AppData\Local\zig\o\c572ef686107a7fad4b348bc9ff5ccd0\ssp.lib
C:\Users\XXX\AppData\Local\zig\o\328af6ab1b720884f3e753728b9473c9\compiler_rt.lib
sdl2.lib
C:\Users\XXX\AppData\Local\zig\o\1a7b98f206b001844ab4a2fffda37487\ole32.lib
C:\Users\XXX\AppData\Local\zig\o\278860bd96ed5c71ed00321c6cd446e9\oleaut32.lib
C:\Users\XXX\AppData\Local\zig\o\2e021af4ac246d150865445477290915\imm32.lib
C:\Users\XXX\AppData\Local\zig\o\1bcdca56a96bec1d8329d38437450b3b\winmm.lib
C:\Users\XXX\AppData\Local\zig\o\f050ced5ac9c3f8c45229762dc8beec4\version.lib
C:\Users\XXX\AppData\Local\zig\o\6645d3c5dd8b151c588e724bb9c19607\gdi32.lib
C:\Users\XXX\AppData\Local\zig\o\7bf309fc8dcaa87e771cbb9d4d8a245e\setupapi.lib
C:\Users\XXX\AppData\Local\zig\o\cd34e21d1933f6a5e9cd488abdeceea5\advapi32.lib
C:\Users\XXX\AppData\Local\zig\o\ed31636928e38ae70fa7fa9c9c4b1c68\kernel32.lib
C:\Users\XXX\AppData\Local\zig\o\26402ac8948dc9941c64c22b33dc4887\msvcrt.lib
C:\Users\XXX\AppData\Local\zig\o\01834c42c39849f21c632588bab97396\ntdll.lib
C:\Users\XXX\AppData\Local\zig\o\6e644b6004cab7ab1edae86b8d642c0f\shell32.lib
C:\Users\XXX\AppData\Local\zig\o\2323f6e86fc64249ffe1b0279c48c306\user32.lib
lld-link: error: could not open 'sdl2.lib': no such file or directory
error: LLDReportedFailure
raycast...The following command exited with error code 1:
C:\Zig\zig.exe build-exe C:\source\zig\raycast\src\main.zig -lc -lsdl2 -lole32 -loleaut32 -limm32 -lwinmm -lversion -lgdi32 -lsetupapi --verbose-link --cache-dir C:\source\zig\raycast\zig-cache --global-cache-dir C:\Users\XXX\AppData\Local\zig --name raycast -target x86_64-windows-gnu -I C:\source\zig\raycast\deps\include -L deps/lib --enable-cache 
error: the following build command failed with exit code 1:
C:\source\zig\raycast\zig-cache\o\63d98521d63e5c5dbc51d88395649798\build.exe C:\Zig\zig.exe C:\source\zig\raycast C:\source\zig\raycast\zig-cache C:\Users\XXX\AppData\Local\zig --verbose-link
```

This might currently be expected behaviour, I found some potentially [related](https://gitlab.kitware.com/cmake/cmake/-/issues/20705) [issues](https://github.com/ziglang/zig/issues/7225), but this seemed slightly different.

I can get round this and build if I use the libs within `SDL2-devel-XXX-VC.zip` (provided I deploy SDL2.dll), but that doesn't quite seem right.

### PR DESCRIPTION
**Pull request by camconn**
When building for `*-windows-gnu` targets, link against `.dll.a` import libraries instead of `.dll` files directly. [LLD doesn't support linking against DLLs](https://reviews.llvm.org/D43964), but requires you to link against a `.lib` or `.dll.a` instead.

Fixes #7799.

### CODE REVIEW

**Comment by andrewrk** [comment]
Thanks for the PR. I have a different plan for this: #6565 

On windows zig will only deal with .lib files, not .dll.a files.

**Comment by camconn** [comment]
Thanks Andrew,

The issue with using `.lib` for linking **external** system libraries is that Mingw uses the `(.dll)?.a` extensions which e.g. cause #7799 and breaks Zig's `pkg-config` integration on Mingw. Mingw doesn't ship with `.lib` files, but rather ships static `.a` or dynamic import `.dll.a` libraries. If I'm wrong on any of that, please correct me.

This PR is *not* concerned with what Zig uses internally, so go on ahead with #6565. It's more concerned with compatibility for external packages and what Zig passes to lld for linking.

I've added a commit that *should* fix the CI build. Would you like any other changes, or should this PR just be closed?

**Comment by andrewrk** [comment]
If you don't mind, please leave it open, and when I implement #6565 I will have all the context loaded in my mind to know how the ideas in this PR should be merged (or not). Sound OK?

**Comment by camconn** [comment]
Yeah that's fine. It's your code, so ultimately your say.

In the meantime I've pushed added a patch that should fix builds for windows targets on non-windows OSs.

**Comment by KioriSun** [comment]
Hi all I tried compiling SDL2 on win with zig cc, and the current holdup is exactly that sdl ships with sdlLibs.a instead of .libs on the mingw devel.
I believe zig should just support the default for mingw.

**Comment by andrewrk** [comment]
Please see https://github.com/ziglang/zig/issues/7799#issuecomment-856352102 for how I am solving this.

**Pull request closed without merging**
