### PR TITLE
DONT MERGE ci: Extract fcntl struct_flock sizes

### PR DESCRIPTION
**Pull request by matu3ba**

### CODE REVIEW

**Comment by andrewrk** [comment]
You know you can just pass `-target` to find out what fcntl.h reports for any given target, right? No need to wait for the CI.

**Comment by matu3ba** [comment]
Yup, thanks: `zig test main.zig -lc --test-no-exec -target aarch64-linux-musl`.
I could've also used qemu. Contributor made an effort, so I'd like to double check.
Also I would like to rule out `kconfig` setup on CI machine having an effect.

**Comment by acarrico** [comment]
@matu3ba maybe you should have kept this branch open for further testing. It would be good to try the failing test  with fcntl imported from libc rather zig native.

**Comment by matu3ba** [comment]
> maybe you should have kept this branch open for further testing. It would be good to try the failing test with fcntl imported from libc rather zig native.

Do you have discord or a mail? Might be easier to communicate than over prs. Feel free to use the code. I'll look into this maybe this evening abit more after the stage2 meeting on discord, if I can make it.

**Comment by acarrico** [comment]
@matu3ba I'm usually in irc as acarrico, but often afk. my email is on my profile here. Don't often have discord up, but it is certainly possible.

**Pull request closed without merging**
