### PR TITLE
Use boyer-moore-horspool algorithm for indexOfPos and lastIndexOf

### LINKED ISSUE #1060: Better memory search algorithm
Just an idea for resolving this TODO: https://github.com/ziglang/zig/blob/652f4bdf6242462182005f4c7149f13beaaa3259/std/mem.zig#L283

* Look at musl for some really clever memory search algorithms like [memmem](https://git.musl-libc.org/cgit/musl/tree/src/string/memmem.c).
* There are a few Wikipedia articles on [string search algorithms](https://en.wikipedia.org/wiki/String_searching_algorithm).
* [the_silver_searcher](https://github.com/ggreer/the_silver_searcher) uses the [Boyer-Moore string search algorithm](https://en.wikipedia.org/wiki/Boyer%E2%80%93Moore_string_search_algorithm) to achieve better performance.

### PR DESCRIPTION
**Pull request by dec05eba**
This fixes #1060

### CODE REVIEW

**Comment by daurnimator** [comment]
Could you share any benchmarks you've run?

Is there some needle length where the previous algorithm was better?

**Comment by dec05eba** [comment]
Hmm i ran some benchmarks and it looks like the compiler is able to optimize the naive case (the old version) than this boyer-moore-horspool version. So im dropping this merge request. I should've made benchmarks before..

**Comment by LemonBoy** [comment]
This BMH implementation is suboptimal, the use of `lastIndexOfScalar` makes it `O(N*M)` where `N` is the haystack length and `M` is the needle length. I'd try first with a more canonical implementation with a pre-processing step to build the skipping table, this alone should give a substantial speed boost.

**Comment by dec05eba** [comment]
right, then it would be a special case where the haystack is not very small and T is u8 (for reasonable skipping table size) and otherwise it would fallback to this naive case

**Comment by dec05eba** [comment]
I created this merge request: https://github.com/ziglang/zig/pull/6259 that creates a skipping table and its significantly faster now than the old version.

**Pull request closed without merging**
