### PR TITLE
fix(std.Progress): some follow-ups

### LINKED ISSUE #13150: Progress panics in zig test when a terminal width is large.
### Zig Version

0.10.0-dev.4327+3a9344d8f

### Steps to Reproduce

Terminal width is larger than 256.
```console
$ tput cols
382
```
```zig
const std = @import("std");

test "hello" {
}
```
Saving above code as `main.zig` and executing `zig test main.zig`.

### Expected Behavior

`zig test` passes a test
```
$ zig test main.zig
All 1 tests passed
```

### Actual Behavior

`zig test` crashes
```
$ zig test main.zig
Test [1/1] test.hello... thread 3130 panic: index out of bounds: index 264, len 256
/home/naoki/.local/zig-master/lib/std/Progress.zig:349:5: 0x23653f in refreshWithHeldLock (test)
    self.output_buffer_slice = self.output_buffer[unprintables .. unprintables + self.max_width.?];
    ^
/home/naoki/.local/zig-master/lib/std/Progress.zig:134:45: 0x21605a in end (test)
            self.context.refreshWithHeldLock();
                                            ^
/home/naoki/.local/zig-master/lib/test_runner.zig:83:18: 0x213f54 in main (test)
    root_node.end();
                 ^
/home/naoki/.local/zig-master/lib/std/start.zig:568:22: 0x212f6d in posixCallMainAndExit (test)
            root.main();
                     ^
/home/naoki/.local/zig-master/lib/std/start.zig:340:5: 0x212a32 in _start (test)
    @call(.{ .modifier = .never_inline }, posixCallMainAndExit, .{});
    ^
error: the following test command crashed:
/home/naoki/.cache/zig/o/cd5362779103cec731f993673b81c28e/test
```

### PR DESCRIPTION
**Pull request by r00ster91**
Just some follow-ups to #12079

Some things mentioned here could still be fixed in the future in some way.

Fixes #13150

### CODE REVIEW

**Comment by andrewrk** [comment]
I've noticed, for the first time ever, my terminal getting into a weird locked-up state sometimes. I haven't managed to figure out how to reproduce it, but it happens after a compilation completes successfully. I suspect it has to do with the recent progress updates. I'm going to revert all the recent std.Progress changes in the meantime until this is diagnosed.

**Comment by andrewrk** [comment]
1952dd6437a73e3de211b649924a55fcb6e030be

**Comment by r00ster91** [comment]
@andrewrk sure, seems like the best thing to do for now. Sorry for the trouble.
Well I think the only reason this could possibly happen is because of `getTerminalCursorColumn`: https://github.com/ziglang/zig/blob/ab4e696e1fac3eda1ad0481cfbdc1829cb5c6847/lib/std/Progress.zig#L236

This function temporarily puts your terminal into a state that would be regarded as "broken" in order to read the escape sequence's output.
It restores your terminal state with that `defer os.tcsetattr`.
Maybe you are hitting this?
https://github.com/ziglang/zig/blob/ab4e696e1fac3eda1ad0481cfbdc1829cb5c6847/lib/std/Progress.zig#L247

One thing you could try is to panic in there in order to see if that's what you're hitting.

I can really not imagine any other place where what you are describing could be happening.

Or could it be a similar issue to #13198? That issue is caused by the same function (and more specifically those tc attr functions that manipulate the terminal).

Or actually... maybe this is a race condition?

As a last resort we could remove `getTerminalCursorColumn` altogether and always use 0.

**Comment by r00ster91** [comment]
I do think this could be a race condition because if you look at those two tc attr calls you can see we do `.NOW` which means we immediately do this change, so there could be some issues if you run multiple `std.Progress` instances in a single terminal in parallel... I doubt that's it because it only happens once at startup.

**Comment by andrewrk** [comment]
I noticed that it happens 100% consistently when I run zig-bootstrap (master branch) and the build completes successfully. This is on x86_64-linux.

One other possible factor - I was doing some advanced troubleshooting and had inadvertently left a process suspended in the background (i.e. with Ctrl+Z) so perhaps that had something to do with it?

**Comment by r00ster91** [comment]
Now that the zig sources aren't updated yet, can you put a panic here
https://github.com/ziglang/zig-bootstrap/blob/326b8a409688d91f6392d06a8d26c2f9dfe01421/zig/lib/std/Progress.zig#L247
and see what happens and then after that replace
https://github.com/ziglang/zig-bootstrap/blob/326b8a409688d91f6392d06a8d26c2f9dfe01421/zig/lib/std/Progress.zig#L203
with
```zig
            const chars_already_printed = 0;
```
and see what that does?

**Comment by andrewrk** [comment]
Sorry, I won't have time to troubleshoot this for a while. I'm typing up the release notes for 0.10.0 and also behind on a bunch of bug fixes that I really want to try to get in before the release is cut.

**Comment by marler8997** [comment]
> It restores your terminal state with that defer os.tcsetattr.
> Maybe you are hitting this?

Does Zig *need* to change the terminal mode?

If we do change the terminal mode, we should also be catching all terminating signals and vectored exceptions and restoring the mode there.  Also note that there's no full-proof way to always restore the mode when we exit, for example. if someone kills the Zig compiler process with certain signals then Zig won't even get a chance to restore the terminal.  This is just one of the drawbacks you have to accept when you decide you need to change the terminal mode.

If not changing the terminal mode means there are some more cases where we can't support progress update then maybe that's fine?  I don't know what we're changing about the mode though, maybe it is necessary?

**Comment by r00ster91** [comment]
@marler8997 
> Does Zig *need* to change the terminal mode?

This is why we were doing it in `getTerminalCursorColumn`: https://github.com/ziglang/zig/blob/ab4e696e1fac3eda1ad0481cfbdc1829cb5c6847/lib/std/Progress.zig#L241

It's so that if we have one `std.Progress` that's doing something like this:
```
doing something... 
```
then a second `std.Progress` instance can come in from a different process and allow this:
```
doing something... building llvm... 
```
etc. So here we have one `std.Progress` ("doing something") waiting for another ("building llvm") to finish, so they can stack up like that. I.e. we can have multiple `std.Progress` printing to the terminal.
`getTerminalCursorColumn` serves the purpose of knowing where we are. So if it's 0 it means no other `std.Progress` instance is before us (we'd be "doing something" in this example); if it's > 0 we know not too print past the terminal width (it makes the "hello world" -> "hello wo..." truncation still work properly because we truncate earlier because we checked where our cursor is).

So it's just so that we don't print over the terminal's width even if there has already been output on the same terminal line before us.

## As for the issue

I got the bootstrap finished eventually and was able to reproduce the issue of the terminal being broken after a successful compilation as well. Then I tried adding a `@panic` in a relevant place and tried to build again. Then I couldn't reproduce the issue anymore. I also tried deleting `zig/zig-cache`. Same problem. I tried it with a new terminal as well but on all other attempts the terminal didn't break.
So it looks like I would have to throw away the entire cache and build with zig-bootstrap from scratch again in order to do a run with that `@panic` in place. It's a very strange issue.

**Pull request merged**
