### PR TITLE
Fix typo in TLS initialization code

### PR DESCRIPTION
**Pull request by LemonBoy**
Come on guys, did you even try to run anything on ARM32?

### CODE REVIEW

**Comment by andrewrk** [comment]
I tested building it, which is how I found a7fd14096c8dbc9cb5ed9a3731753b24e32d5757. I don't personally have any hardware for testing arm32 currently. I believe @Snektron did plenty of testing for #3152 but made some typos when I asked for last-minute modifications before merging the PR.

I'm definitely open to suggestions on how we can get CI testing hooked up for ARM32.

**Comment by andrewrk** [comment]
In related news, I did order a PineBook Pro, which is expected to arrive in October. That's arm64 though.

**Comment by marler8997** [comment]
Does qemu not work for arm32 testing?

**Comment by andrewrk** [comment]
It works but the slowdown is something like 20x. Full zig test suite - including testing optimized builds - takes ~48 hours. A more custom CI solution would be needed for this, as most services have much lower limits. The most generous one is Azure at 6 hours.

See here for attempt to use qemu on sr.ht: https://github.com/ziglang/zig/pull/2978#issuecomment-516983867

**Comment by andrewrk** [comment]
I would still be interested in setting something like this up. We could have a dedicated instance that runs the latest master branch commit, however long it takes. When that finishes, instead of trying the *next* commit, skips to the latest. So at least we will find out results periodically, rather than never. With this strategy we can probably take advantage of qemu and greatly increase architecture/OS coverage.

**Comment by LemonBoy** [comment]
> It works but the slowdown is something like 20x.

I'm using QEMU's user-mode emulation to run the cross-compiled test artifacts.

**Comment by andrewrk** [comment]
That's good to know. I need to learn how to use that.

**Comment by andrewrk** [comment]
Ideally we could add it as a build option, e.g. `-Denable-qemu-testing`, and it will run the applicable cross-compiled test artifacts. Combined with `-Denable-wine-testing` I think we'd be able to run everything except for macOS.

**Pull request merged**
