### PR TITLE
std.Target: Remove some obsolete/dead specifiers.

### PR DESCRIPTION
**Pull request by alexrp**
See commit messages for details.

Additional notes:

* The kFreeBSD removal might be controversial since the discontinuation of the project is fairly recent (2023). I suppose one could argue that there might be a faint hope that somebody will pick it up again. I seriously doubt it, though, since development seemed to have already stalled in 2022.
* The removal of `gnuf64` is done to keep things simple. LoongArch is a relatively new architecture and it probably won't even be fully functional in Zig until 0.14.0 or so. As such, I don't think there's much value in accepting `gnuf64` even as just a legacy alias for `gnu`.
* The removal of `nacl` (and its associated `le32`/`le64` pseudo-architectures) should hopefully be uncontroversial since it was deprecated in 2017 and support ended in 2021, and even Google state on the NaCl website that WebAssembly is the future.
* The `coreclr` ABI specifier should likewise be uncontroversial. It was never really intended for use outside LLILC, which never graduated from experimental status and is now long dead.

### CODE REVIEW

**Comment by alexrp** [comment]
Assuming the general direction of removing these is okay, we might want to also consider the status of the `r600` arch specifier. This one is for quite old GPUs, ~2011 or so. CPU architectures have a tendency to gain a cult following that persists long after they cease to be relevant in the industry. AFAICT, that's not generally something that happens for GPU architectures. So not sure if keeping this specifier around makes much sense.

**Comment by alexrp** [comment]
In a similar vein, it *seems* that `amdil`/`amdil64` are very old aliases from ~2011 that were used before `r600` and `amdgcn` came about as part of the AMDGPU upstreaming in LLVM in ~2012. [These](https://github.com/search?q=repo%3Allvm%2Fllvm-project+amdil&type=code) are the only references to the term in LLVM, and they strongly indicate that "AMDIL" was just the old name for "AMDGPU". Seems safe to remove?

**Comment by alexrp** [comment]
Another candidate: `hsail`/`hsail64`. This seems to be either entirely dead or, in some sense, absorbed by AMDGPU.

**Comment by alexrp** [comment]
And another: `renderscript32`/`renderscript64`. [RenderScript was deprecated in Android 12 and is going away entirely.](https://developer.android.com/guide/topics/renderscript/migrate)

**Comment by Snektron** [comment]
- There's some mesa activity regarding r600, but the architecture is not really durable to target with Zig. It just doesn't really have the things we need.
- hsail/brig is not used by amd anymore. I'm fact, they will probably switch to spirv for the next IR.
- amdil: this is so obscure that even I don't know that it's for. 
- renderscript is stupid

I don't think we'll ever see support for these, and i dont think we should put any effort in them.

**Comment by andrewrk** [comment]
Thank you for the nice writeup and for the rebase. I agree with your reasoning. The only thing potentially missing is some comments to prevent someone from not realizing this is intentional and adding back things since they are still found in LLVM enums. However, we can keep an eye out for that, it doesn't need to block merging this.

**Comment by alexrp** [comment]
@andrewrk any thoughts on the [other candidates for removal](https://github.com/ziglang/zig/pull/20402#issuecomment-2185211466)? If you're fine with those, I'll do a follow-up PR for that (+ adding comments as you mentioned).

**Comment by andrewrk** [comment]
I think they are all OK to remove. Keep in mind, we do intend to support any *active* communities based on old or niche hardware or software.

**Pull request merged**
