### PR TITLE
Workaround MacOS build failure due to #6087

### PR DESCRIPTION
**Pull request by notCalle**
This adds a workaround for #6087 to the CMake config, gated by `-DZIG_WORKAROUND_6087=ON` command line option.

### CODE REVIEW

**Review by jedisct1 — APPROVED** [review]

**Comment by glepnir** [comment]
Hey got success with this patch. Thanks

**Review by kubkon — APPROVED** [review]
Looks great, thanks @notCalle!

**Comment by jbsolomon-fw** [comment]
works for me!  🙌

**Comment by aarvay** [comment]
Works for me too!! Thanks for this.

**Comment by kubkon** [comment]
@notCalle before I merge this, could you add a note to try this fix on macOS in the `README.md`, similarly to how it's been done wrt [fix 4799](https://github.com/ziglang/zig/blob/master/README.md#macos)? This should make this temp solution hopefully more visible.

**Comment by notCalle** [comment]
>  before I merge this, could you add a note to try this fix on macOS in the `README.md`

@kubkon Yes! Good idea. Done.

**Review by kubkon — APPROVED** [review]
LGTM!

**Pull request merged**
