### PR TITLE
MSVC CI: run tests individually

### PR DESCRIPTION
**Pull request by jedisct1**
This seems to solve the issues we have on Azure with the MSVC pipeline.

### CODE REVIEW

**Comment by kubkon** [comment]
I'm curious now. Why is there a problem running tests as a single binary on Windows? Is it as simple as OOM?

**Comment by jedisct1** [comment]
Yes, likely an OOM. Maybe due to memory fragmentation.

This also solves the mystery failure we couldn't reproduce in the constant-time memcmp.

**Comment by kubkon** [comment]
> Yes, likely an OOM. Maybe due to memory fragmentation.
> 
> This also solves the mystery failure we couldn't reproduce in the constant-time memcmp.

That's interesting. Makes me wonder, maybe it'd be worth making `zig build test` auto-split any internal test runs across multiple binaries? This is just me groping in the dark, as I don't know how difficult it'd be to modify our current build system. Making this the default however has the potential of fixing some Wasm issues as well (i.e., some tests which are currently disabled when targeting Wasm, might get fixed by constraining the binaries to more manageable sizes due to wasmtime exploding in memory, and whatnot).

**Comment by jedisct1** [comment]
Boom, Azure CI is all green again!

**Comment by kubkon** [comment]
Hmm, I wonder if this perhaps was Azure issue all along, or whether we've got some non-determinism going on? Check out status of #6752. All green with no changes to the CI.

**Comment by FireFox317** [comment]
@kubkon This is indeed the Windows CI being OOM. I guess it is non-deterministic, because sometimes the CI just has a tiny bit more memory available and than it succeeds. @andrewrk already moves some tests/code to the https://github.com/ziglang/std-lib-orphanage because of exactly this reason.

**Comment by kubkon** [comment]
> @kubkon This is indeed the Windows CI being OOM. I guess it is non-deterministic, because sometimes the CI just has a tiny bit more memory available and than it succeeds. @andrewrk already moves some tests/code to the https://github.com/ziglang/std-lib-orphanage because of exactly this reason.

Ah right, I forgot about the orphanage!

**Comment by andrewrk** [comment]
I'd like to revert this once we have a more resource friendly compiler, but it's a reasonable change given status quo.

**Pull request merged**
