### PR TITLE
codegen: lower field_ptr to memory across linking backends

### PR DESCRIPTION
**Pull request by kubkon**
This requires generating an addend for the target relocation as
the field pointer might point at a field inner to the container.

### CODE REVIEW

**Comment by Luukdegram** [comment]
This addition is great! The addition of addends makes `codegen.zig` Feature compatible with the Wasm backend’s ‘generateSymbol’. I’ll try to convert the Wasm backend to use this instead. It seems to only miss 128bit integers, floats and elem_ptr’s but perhaps I can add those in while I’m at it.

**Comment by kubkon** [comment]
> This addition is great! The addition of addends makes `codegen.zig` Feature compatible with the Wasm backend’s ‘generateSymbol’. I’ll try to convert the Wasm backend to use this instead. It seems to only miss 128bit integers, floats and elem_ptr’s but perhaps I can add those in while I’m at it.

Sounds good, although last time I saw, this will require a significant rewrite in the Wasm codegen and linker as it's handled differently to how Wasm handles it. My suggestion would be to regress Wasm first and try using the `codegen` and `link` APIs and see how that pans out. Afterwards, we can add the rest.

**Comment by Luukdegram** [comment]
> Sounds good, although last time I saw, this will require a significant rewrite in the Wasm codegen and linker as it's handled differently to how Wasm handles it. My suggestion would be to regress Wasm first and try using the `codegen` and `link` APIs and see how that pans out. Afterwards, we can add the rest.

Sounds great. Rather regress it now than after we get all tests passing :) (I had already started changing some of the linker API to make it a little more similar to the others).

**Comment by kubkon** [comment]
> > Sounds good, although last time I saw, this will require a significant rewrite in the Wasm codegen and linker as it's handled differently to how Wasm handles it. My suggestion would be to regress Wasm first and try using the `codegen` and `link` APIs and see how that pans out. Afterwards, we can add the rest.
> 
> Sounds great. Rather regress it now than after we get all tests passing :) (I had already started changing some of the linker API to make it a little more similar to the others).

So here's an added bonus: if we manage to unify the API of Wasm with the other linking backends, you'll almost get DWARF for free. And that's a promise ;-)

**Pull request merged**
