### PR TITLE
Treat vectors as indexable

### PR DESCRIPTION
**Pull request by data-man**

### CODE REVIEW

**Comment by data-man** [comment]
Some ideas:

- ~~add .len property for vectors - rejected~~
- supports array's and vector's length in mem.len
- deprecate .len property

**Comment by andrewrk** [comment]
> add .len property for vectors - rejected

can you link to the issue? might be worth revisiting

**Comment by data-man** [comment]
@andrewrk 
Your [comment](https://github.com/ziglang/zig/issues/903#issuecomment-459508820) (8 Jan redaction)
I tried implement `.len` in #3941.

**Comment by data-man** [comment]
I found [it](https://github.com/ziglang/zig/pull/3904#discussion_r363897129)! :smile:

>This is not a TODO; len for vectors is not planned. Vectors can be vectors of single-item pointers to structs, and .len will do a vectorized field access. #363

**Comment by daurnimator** [comment]
wait, is indexing a vector element access? How do you index the contents of a vector?
```zig
    const v: @Vector(4, *[10]u8) = undefined;
    @compileLog(@typeName(@TypeOf(v[1])));
```

**Comment by data-man** [comment]
@daurnimator 
```zig
if (std.meta.trait.isIndexable(@TypeOf(some_var))) {
   var i: usize = 0;
   // use some_var[i]
   i++;
}
```

**Comment by daurnimator** [comment]
@data-man I thought that vector indexing indexed it for each element in the vector.
And hence `isIndexable` would need to recurse into the child type to find out if a vector is indexable or not.

Any other behaviour for indexing a vector seems like a huge footgun!

**Comment by andrewrk** [comment]
@daurnimator you found an inconsistency in the SIMD design that needs to be worked out. => #5427

**Pull request merged**
