### PR TITLE
std.fmt.format — with generators

### PR DESCRIPTION
**Pull request by fengb**
Experiment to [convert `std.fmt.format` into an iterator](https://github.com/ziglang/zig/pull/3907#issuecomment-565740855) with userland generators. This pattern is a little rougher than I'd like, but it does work (as long as you don't hit async bugs). The biggest benefit here is the ability to seamlessly context dumping providing a nice iterator interface over the old errorset callback style.

```zig
var generator = Generator([]const u8).init();  // create the generator context
_ = async genFunction(&generator, args);  // prime the generator with async frame
while (generator.next()) |bytes| {
    consume(bytes);
}
```

Ideally, I would like to be able to _**return**_ generators, but embedding both the async frame and the yield location seems to be impossible at the moment (requires `@resultLocation()`), and even then requiring generators be comptime generic removes a lot of composability.

### TODO list:
- [x] resolve all the types
- [x] custom formatter — including recursive calls to `std.fmt.format` (blocked by https://github.com/ziglang/zig/issues/4096)
- [x] relink the rest of std with the new formatter (blocked by https://github.com/ziglang/zig/issues/4110)
- [ ] (stretch) enable async os.write
- [ ] either include the following or help resolve conflicts:
    - [ ] https://github.com/ziglang/zig/pull/3877
    - [x] ~~https://github.com/ziglang/zig/pull/3904~~
    - [x] ~~https://github.com/ziglang/zig/pull/3970~~
    - [ ] https://github.com/ziglang/zig/pull/3972
    - [x] https://github.com/ziglang/zig/pull/4192

[Discovered a way](https://github.com/ziglang/zig/pull/4059#issuecomment-571004959) to [remove the manual recursion stack](https://github.com/ziglang/zig/pull/4059/commits/42a47eb0efc3c1047e2644268cbf4e3050677e7b), thus these following problems no longer exist!
- precalculate the recursive frame size, possibly leave extra buffer in case of complex — e.g. when customer formatters call other custom formatters ad infinitum
- implement `FixedBufferAllocator.free` — need to enable freeing the last allocation for this recursion to work properly
- better default output when giving up recursion — `"??OOM??"` looks silly

### CODE REVIEW

**Comment by fengb** [comment]
Using async like this, we can't no longer have "simple" recursion that just works. This is especially apparent with custom formatters, which can theoretically invoke an arbitrary number of other recursive formatters. With the current design, I can definitely support 1 recursive invocation, but there needs to be some major refactoring to go beyond that. Thoughts on moving forward:

- limit it so custom formatters are not guaranteed to recursively call other custom formatters correctly
- separate the analysis pass so we can possibly do a better calculation — not sure how well this would work
- expose the allocator — this breaks "no errors"... but infinite recursion has a price

**Comment by fengb** [comment]
I stumbled upon an elegant solution to the recursion problem. By applying `comptime max_depth`, I'm able to convince Zig to analyze all possible depths (or infinite loop trying...) and let me use "real" recursion in async functions. This is incredibly elegant since it should automatically account for the correct frame size, instead of me trying to figure out depth and manually shifting things onto a separate stack.

My only concern is that this can easily bloat the generated code, since every recursion step would potentially be its own function (now that max_depth is comptime).

**Comment by fengb** [comment]
The [new atoi equivalent](https://godbolt.org/z/gSUpcP) is ~16x more lines of assembly than existing code.

**Comment by fengb** [comment]
Ran into a footgun. The generator currently checks after a `resume` to see whether the yielded value changes, and if not it's considered "done" (assumes the function completes with no more yields). The only other way is if there's a `suspend` without a corresponding `generator.yield`, which I had assumed is a user error.

Unfortunately, there's a separate case that I hadn't considered: an actual async function. This is re-exposing the ugly color problem, and to solve it there needs to be some advanced heuristics to differentiate between the generator context and a tracking async.

If we continue with the current behavior, any await/suspend would also terminate the generator. This is kludgy and gross and exhibits spooky action at a distance (e.g. some function somewhere calls os.read() and the generator fails), but it seems to be at least consistently reproducible.

If we want to allow async generators, I have a few ideas:
1. next() will probably have to be always async, which might re-expose the seam in unwarranted places.
2. Detecting frame liveness is most reliable, but it requires compiler support.
3. Require a manual `generator.terminate()`. This would break the current style of sharing the generator context across the stack since somebody will have to own the exit.
4. Manually refcount the function entrances/exits. This might be the least bad since every generator supported function can simply start with `generator.acquire(); defer generator.release();`

**Comment by fengb** [comment]
Regression — `format()` can no longer be used at comptime:

```zig
const std = @import("std");

comptime {
    var buf: [100]u8 = undefined;
    @compileError(std.fmtgen.bufPrint(&buf, "hello {}", .{12}) catch unreachable);
}
```

**Comment by fengb** [comment]
Encountered too many design flaws. And this usecase is now obsolete.

**Comment by andrewrk** [comment]
:rose: R.I.P. :rose:

**Pull request closed without merging**
