### PR TITLE
Fix a bug in std.Thread.Condition and add a basic Condition test.

### PR DESCRIPTION
**Pull request by afranchuk**
Condition in 0.9 is broken. This fixes it and adds a test to hopefully not have that happen again.

### CODE REVIEW

**Review by andrewrk — CHANGES_REQUESTED** [review]
Thanks for the patch. The fix looks good,however, the new test case failed on the FreeBSD CI run.

**Comment by afranchuk** [comment]
I almost expected as much since there were no tests at all before. I'll see if I can figure it out.

**Comment by afranchuk** [comment]
I expect there's a race at the end with the thread still up and waiting to unlock the mutex after the test body is done; should be a simple fix once I get back on my computer. Not related to bsd systems alone.

**Comment by andrewrk** [comment]
Thanks for the follow-up!

**Pull request merged**
