### PR TITLE
Improve the `DynamicLinker` API and fix `detectAbiAndDynamicLinker()` for non-Linux/Hurd ELF hosts

### LINKED ISSUE #9089: Improve *BSD native ABI detection
At the moment zig detects the native ABI as `.gnu`, that may cause some problems as many *BSD libcs are not fully gnu-compliant (eg. NetBSD has no `sincos`, a GNU extension, but since we're passing LLVM the wrong triple we end up with [some missing symbols](https://github.com/ziglang/zig-bootstrap/pull/60)).

cc @mikdusan as I guess you'd love some BSD action

### PR DESCRIPTION
**Pull request by alexrp**
Closes #9089.

### CODE REVIEW

**Comment by alexrp** [comment]
@mikdusan ok, I *believe* this + #21611 should do the trick for ABI detection on BSDs.

**Comment by mikdusan** [comment]
lgtm, `zig env | grep target` on various BSDs:

```json
"target": "x86_64-freebsd.14.1...14.1-none",
"target": "x86_64-netbsd.10.0...10.0-none",
"target": "x86_64-netbsd.9.4...9.4-none",
"target": "x86_64-openbsd.7.5...7.5-none",
"target": "x86_64-dragonfly.6.4...6.4-none",
```

**Comment by alexrp** [comment]
Nice, thanks for testing!

**Comment by alexrp** [comment]
@andrewrk just need your thoughts on the new `DynamicLinker.kind()` function and the direction of making `DynamicLinker.standard()` stricter in regards to what triples it's willing to return "standard" paths for (see the commit message).

**Pull request merged**
