### PR TITLE
std.math.complex:  c_Complex for C maths libraries

### PR DESCRIPTION
**Pull request by f3fora**
Popular mathematical C libraries require complex numbers, which are often represented
with a 2 element struct. 
The `Complex(...)` type does not guarantee the C ABI compatibility.
Thus, let's define once and only once a `c_Complex(...)` type in `std` to interact in 
an unique way and avoid re-definitions.

The name `c_Complex` is chosen in analogy with `c_int`.

E.g. a function for complex number in `cblas.h` header:
```
void   cblas_zdotc_sub(const CBLAS_INT N, const void *X, const CBLAS_INT incX,
                       const void *Y, const CBLAS_INT incY, void *dotc);
```
where usually `void *` is a pointer to an array of a struct of two elements
(in this particular case, of type `double`).

### CODE REVIEW

**Comment by f3fora** [comment]
If I understand correctly from [documentation](https://ziglang.org/documentation/master/#extern-struct) and from [this comment](https://github.com/ziglang/zig/issues/6700#issuecomment-710715422), order in `struct` is not guaranteed. Obviously, it is crucial in complex numbers.

**Comment by ehaas** [comment]
The C standard defines the size and alignment of `_Complex` types (same size and alignment as an array of 2 elements of the corresponding real type) but it does not define the calling convention. So I don't think it is possible to implement this without compiler support. If I recall correctly `i386-linux-gnu` will treat a return type of `_Complex float` differently than a return type of `"struct with 2 floats"`

**Comment by f3fora** [comment]
`<complex.h>` was introduced in C99, while some C mathematical and scientific libraries can be older and deal with complex numbers in their own way.

For example, LAPACK defines `lapack_complex_{float,double}` as `_Complex` or as a struct `{ double real, imag; }` according to some constant; GSL defines complex numbers with `#define GSL_COMPLEX_DEFINE(R, C) typedef struct { R dat[2]; } C ;`; BLAS accepts array of complex number as function arguments as `void *`.

With an `extern struct` all these definitions are a 'cast' away and it allows a simple and unique way to interact with C libraries.

Moreover, from another point of view, [a complex number is nothing more than an ordered pair of two real numbers](https://www.sciencedirect.com/topics/physics-and-astronomy/complex-numbers). After all @zigazeljko 's idea is not too wrong.

**Comment by ehaas** [comment]
> With an extern struct all these definitions are a 'cast' away and it allows a simple and unique way to interact with C libraries.

This is not guaranteed to be true - it's not required that a C compiler treat `_Complex T` and `struct C { T r; T i; }` (where `T` is some floating point type) the same, specifically when passing or returning it by value to a function. It's also not required to treat it the same as `T[2]` with regard to calling convention.

Adding this would be a subtle footgun - it would work on many platforms, but not, for example, on `i386-linux-gnu`. The only way to properly solve it is with a `c_complex` type in the language.

**Comment by Vexu** [comment]
One option is to inspect the LLVM ir generated by `clang -S -emit-llvm --target=?? file.c` and defining the type in a switch on the target and erroring on targets where `_Complex` is not representable by a struct like mips.
```c
_Complex double a;
struct Complex { double re[2]; } b;
// or struct Complex { double re, im; } b;
_Complex double foo(_Complex double a) {
    return a;
}
struct Complex bar(struct Complex a) {
    return a;
}
```

**Comment by f3fora** [comment]
See #8465

**Pull request closed without merging**
