### PR TITLE
libstd: add static archive header struct and definitions

### PR DESCRIPTION
**Pull request by kubkon**
I'm not sure whether this is the best place to host this, so looking for opinions!

cc @LemonBoy

### CODE REVIEW

**Comment by LemonBoy** [comment]
`os.zig` is not the right place, this stuff should get its own file a-la `elf.zig`/`coff.zig`.
Keep in mind there are a few variants of the archive format, LLVM exposes them as `object::Archive::K_{GNU,DARWIN,BSD}`.

**Comment by kubkon** [comment]
> `os.zig` is not the right place, this stuff should get its own file a-la `elf.zig`/`coff.zig`.

Good idea, thanks!

> Keep in mind there are a few variants of the archive format, LLVM exposes them as `object::Archive::K_{GNU,DARWIN,BSD}`.

Huh, now I'm intrigued. I was convinced there was literally no difference between GNU and DARWIN at least. Do you have a link handy perhaps?

**Comment by LemonBoy** [comment]
> Huh, now I'm intrigued. I was convinced there was literally no difference between GNU and DARWIN at least. Do you have a link handy perhaps?

Here you [go](https://www.freebsd.org/cgi/man.cgi?query=ar&sektion=5), the DARWIN format is derived from the BSD one with some extra record, while there's also a Windows' variant that's similar to GNU.

**Comment by kubkon** [comment]
> > Huh, now I'm intrigued. I was convinced there was literally no difference between GNU and DARWIN at least. Do you have a link handy perhaps?
> 
> Here you [go](https://www.freebsd.org/cgi/man.cgi?query=ar&sektion=5), the DARWIN format is derived from the BSD one with some extra record, while there's also a Windows' variant that's similar to GNU.

Hmm, as far as I can tell, the `ar_hdr` for GNU and Darwin are the same: [gnu](https://github.com/ziglang/zig/blob/bb636cb3bffadf5a03e592b97a1968492f16f8cd/lib/libc/include/generic-glibc/ar.h) and [darwin](https://opensource.apple.com/source/Libc/Libc-1439.40.11/include/ar.h.auto.html), or am I missing something?

**Comment by kubkon** [comment]
Oh unless you meant some additional `const`s?

**Comment by kubkon** [comment]
OK, I'm gonna go ahead and close it for now. After some offline discussion with @andrewrk and others, I think it makes more sense to have AR part of the compiler sources itself rather than the standard library.

**Comment by LemonBoy** [comment]
Please check out the link I've posted, it explains pretty well the main differences between the GNU and the BSD format.
Darwin uses the BSD format but adds its own way of defining the symbol table (`SYMDEF_64`), AFAIR that's the main difference.

**Comment by kubkon** [comment]
> Please check out the link I've posted, it explains pretty well the main differences between the GNU and the BSD format.
> Darwin uses the BSD format but adds its own way of defining the symbol table (`SYMDEF_64`), AFAIR that's the main difference.

Will do, thanks!

**Pull request closed without merging**
