### PR TITLE
wasm-linker: Implement linker tests

### PR DESCRIPTION
**Pull request by Luukdegram**
Implements the linker-tests framework for the self-hosted wasm linker.
This includes a few test cases, as well as small fixes within the self-hosted linker that were caught during the implementation of the tests.

Note: This adds the `-fno-LLD` and `-fLDD` options to `build.zig` to make sure the self-hosted linker is used, rather than wasm-ld when running the tests.

### CODE REVIEW

**Comment by kubkon** [comment]
Seems `wasm/type` test is failing on macOS:

```

========= Expected to find: ==========================
Section type
========= But parsed file does not contain it: =======
Section memory
size 7
entries 1
min 1
Section global
size 12
entries 1
type i32
mutable true
i32.const 10000
Section export
size 14
entries 1
name memory
kind memory
index 0
Section custom
size 31
name name
type function
size 1
names 0
type global
size 18
names 1
index 0
name __stack_pointer
type data_segment
size 1
names 0

error: TestFailed
/Users/runner/work/1/s/build/release/lib/zig/std/os.zig:2749:19: 0x102778a60 in std.os.mkdiratZ (build)
        .EXIST => return error.PathAlreadyExists,
                  ^
/Users/runner/work/1/s/build/release/lib/zig/std/os.zig:2709:9: 0x102778918 in std.os.mkdirat (build)
        return mkdiratZ(dir_fd, &sub_dir_path_c, mode);
        ^
/Users/runner/work/1/s/build/release/lib/zig/std/fs.zig:1283:9: 0x1027787c6 in std.fs.Dir.makeDir (build)
        try os.mkdirat(self.fd, sub_path, default_new_dir_mode);
        ^
/Users/runner/work/1/s/build/release/lib/zig/std/os.zig:1680:23: 0x1027ac1ce in std.os.openatZ (build)
            .NOENT => return error.FileNotFound,
                      ^
/Users/runner/work/1/s/build/release/lib/zig/std/fs.zig:1032:13: 0x10277e800 in std.fs.Dir.openFileZ (build)
            try os.openatZ(self.fd, sub_path, os_flags, 0);
            ^
/Users/runner/work/1/s/build/release/lib/zig/std/fs.zig:959:9: 0x10277e410 in std.fs.Dir.openFile (build)
        return self.openFileZ(&path_c, flags);
        ^
/Users/runner/work/1/s/build/release/lib/zig/std/os.zig:2754:19: 0x102778ad4 in std.os.mkdiratZ (build)
        .NOENT => return error.FileNotFound,
                  ^
/Users/runner/work/1/s/build/release/lib/zig/std/os.zig:2709:9: 0x102778918 in std.os.mkdirat (build)
        return mkdiratZ(dir_fd, &sub_dir_path_c, mode);
        ^
/Users/runner/work/1/s/build/release/lib/zig/std/fs.zig:1283:9: 0x1027787c6 in std.fs.Dir.makeDir (build)
        try os.mkdirat(self.fd, sub_path, default_new_dir_mode);
        ^
/Users/runner/work/1/s/build/release/lib/zig/std/io/reader.zig:233:31: 0x1027a04f3 in std.io.reader.Reader(*std.io.fixed_buffer_stream.FixedBufferStream([]const u8),std.io.fixed_buffer_stream.FixedBufferStream([]const u8).ReadError,std.io.fixed_buffer_stream.FixedBufferStream([]const u8).read).readByte (build)
            if (amt_read < 1) return error.EndOfStream;
                              ^
/Users/runner/work/1/s/build/release/lib/zig/std/build/CheckObjectStep.zig:293:25: 0x1027c02cf in std.build.CheckObjectStep.make (build)
                        return error.TestFailed;
                        ^
/Users/runner/work/1/s/build/release/lib/zig/std/build.zig:3622:9: 0x10277937e in std.build.Step.make (build)
        try self.makeFn(self);
        ^
/Users/runner/work/1/s/build/release/lib/zig/std/build.zig:507:9: 0x102778141 in std.build.Builder.makeOneStep (build)
        try s.make();
        ^
/Users/runner/work/1/s/build/release/lib/zig/std/build.zig:501:17: 0x1027780c5 in std.build.Builder.makeOneStep (build)
                return err;
                ^
/Users/runner/work/1/s/build/release/lib/zig/std/build.zig:462:13: 0x10276b79b in std.build.Builder.make (build)
            try self.makeOneStep(s);
            ^
/Users/runner/work/1/s/build/release/lib/zig/build_runner.zig:213:21: 0x1027668e6 in main (build)
            else => return err,
                    ^
error: the following build command failed with exit code 1:
/Users/runner/work/1/s/test/link/wasm/type/zig-cache/o/8d56a39c7dc6c7bf13cfea8e3eb6cd1f/build /Users/runner/work/1/s/build/release/bin/zig /Users/runner/work/1/s/test/link/wasm/type /Users/runner/work/1/s/test/link/wasm/type/zig-cache /Users/runner/.cache/zig test
```

**Comment by kubkon** [comment]
Some update: I tried reproing the issue locally on Intel MBP with macOS 12 on it without luck. I do realise though that the CI is running a macOS 10.15.7 install so I will try that next to see if I can repro the issue.

**Comment by kubkon** [comment]
@Luukdegram I tried reproing it locally on 10.15.7 but no luck. My suggestion would be to disable all other CI tests except for `test-link` and see if you can figure out why there is a failure in the CI and not locally.

**Comment by Luukdegram** [comment]
> @Luukdegram I tried reproing it locally on 10.15.7 but no luck. My suggestion would be to disable all other CI tests except for `test-link` and see if you can figure out why there is a failure in the CI and not locally.

Thanks for verifying. I'll be doing that next.

**Pull request merged**
