### PR TITLE
Fix argument forwarding to LLVM on Windows

### LINKED ISSUE #9225: Windows: `zig.exe: error: not ranlib, ar, lib or dlltool`
Hello! 

I have downloaded the zig compiler from the website hoping I could use it to replace my C build tools on Windows. When I run `.\zig.exe ar`, however, I receive the following error: `zig.exe: error: not ranlib, ar, lib or dlltool`. 

This happens for both versions 0.9.0-dev and 0.8.0.

### PR DESCRIPTION
**Pull request by SpexGuy**
Fixes #9225
Might also fix other windows issues like #9002

### CODE REVIEW

**Comment by mjoerussell** [comment]
For what it's worth, this has not fixed #9002 or #9124 for my project.

**Comment by SpexGuy** [comment]
Yeah I'm tracking 9002 down now, it's definitely a different bug.

**Review by andrewrk — COMMENTED** [review]
As long as this doesn't break non-Windows targets, looks good. How is it getting the argc, argv with this change?

**Comment by SpexGuy** [comment]
Zig is getting argc/argv the same way it always has, building a modified version for llvm, and then passing that in.  LLVM just doesn't ignore those values on windows anymore.

**Pull request merged**
