### PR TITLE
Implement `@depositBits` and `@extractBits`

### LINKED ISSUE #14995: Add `@pext` and `@pdep` builtins
Of the all the bit manipulation instructions available on a platform like x86_64, most of them are an optimization over fundamental operations.

https://en.wikipedia.org/wiki/X86_Bit_manipulation_instruction_set

For example, the BLSR x86_64 instruction is equivalent to `x & (x - 1)`, and can easily be written inline or put in a function at the discretion of the programmer. We would never need a `@blsr` builtin because the fundamental operation of resetting the lowest set bit is already in the language.

Some of the other operations are newer fundamental operations and are builtin to Zig already, through `@popCount`, `@ctz` and `@clz`. I would also consider `@bitReverse` to be a fundamental operation, even though for some reason x86_64 lacks an instruction for it.

`pdep` and `pext` on the other hand, are not in the language, (relatively) not trivial to implement manually, and to my knowledge will only appear in the output binary as PDEP/PEXT by using inline assembly. In my view `pdep` and `pext` are now fundamental bitwise operations, just like the aforementioned operations.

Since they were first proposed by Yedidya Hilewitz and Ruby B. Lee [[1](https://www.lirmm.fr/arith18/papers/hilewitz-PerformingBitManipulations.pdf), [2](http://palms.ee.princeton.edu/PALMSopen/hilewitz06FastBitCompression.pdf)] they [have seen a myriad of uses](https://stackoverflow.com/questions/69966389/what-are-assembly-instructions-like-pext-actually-used-for). Perhaps one of the biggest uses that I am aware of is in implementing the `select` function of `rank`/`select` data structures, which are the fundamental operations of [succinct data structures](https://en.wikipedia.org/wiki/Succinct_data_structure) and certain other bitwise structures like the [Counting Quotient Filter](https://users.cs.utah.edu/~pandey/courses/cs6530/fall22/papers/htfilters/3035918.3035963.pdf) (used for Approximate Membership Queries). [Here is an article](https://www.adrian.idv.hk/2018-11-05-pbj17-fastx86/) on how to implement `select` using `pdep`. 

They are also used to implement bitboards, which are important for chess programming or sudoku solvers: https://news.ycombinator.com/item?id=19137798
More praise of `pdep` and `pext`: https://news.ycombinator.com/item?id=20205743

I have personally used `pdep` recently to check that delimiting characters are in the proper positions with SIMD. Specifically, I had a file that was of the format `word\t123<digits>123\nword2\t456<digits2>456\n`, etc. I moved 64 byte chunks into a vector, got a bitmap for where the '\t' and '\n' characters are, or'ed them together, and used `pdep` to extract every other set bit, which I can then check against the newline or tab mask to make sure the file alternates between tabs and newlines as delimiters. To grab every other set bit, one can do:

```zig
inline fn maskEvenBits(bitstring: u64) u64 {
    return pdep(0xaaaaaaaaaaaaaaaa, bitstring);
}
```

Here is an excerpt of my code:

```zig
const vec: @Vector(VEC_SIZE, u8) = buf[0..VEC_SIZE].*;

// Note: we cannot just match digit characters because those characters can also appear in the string section.
const tab_mask = @bitCast(std.meta.Int(.unsigned, VEC_SIZE), vec == @splat(VEC_SIZE, @as(u8, '\t')));
const newline_mask = @bitCast(std.meta.Int(.unsigned, VEC_SIZE), vec == @splat(VEC_SIZE, @as(u8, '\n')));
const newline_tab_mask = tab_mask | newline_mask;

// Validate that the file alternates between tab and newlines.
if (maskEvenBits(newline_tab_mask) != if (state == 0) tab_mask else newline_mask)
    return error.InvalidFile;

// Note: state is flipped depending on whether the 64-byte chunk is supposed to be matching strings or digits at the start of the next loop
```

Conveniently, I have heard that LLVM supports `pdep` and `pext` as fundamental operations. If Zig becomes the new C for the next few decades, supporting operations like `pdep` and `pext` is important for bit twiddlers to ~~choose~~ love Zig. It is also important from the language's perspective to define the set of fundamental bit manipulations, which should be supported on new ISA's.

Also important: https://github.com/ziglang/zig/issues/9631

### PR DESCRIPTION
**Pull request by ominitay**
Implements `@depositBits` and `@extractBits`, corresponding to `pdep` and `pext`  from BMI2. The builtins are supported in the LLVM backend for any integer width, are supported in the x86 backend for integer widths below and including 64 bits, and are evaluated at compile-time when possible (also at any integer width). The functionality remains unimplemented in all other backends, and is out of the scope of this PR.

Apologies for how long it has taken me to find the time to get this merge-ready, but I'm happy for it to be merged now, and any further enhancements to be split out into further issues.

Continuation of #15285 
Closes #14995

### CODE REVIEW

**Comment by ominitay** [comment]
All checks passed, happy for this to be merged if approved :)

**Comment by ominitay** [comment]
Rebased onto master.

**Comment by ominitay** [comment]
Merge conflicts have happened now because this PR has been open so long, will resolve these tomorrow.

**Comment by ominitay** [comment]
Converted to draft as there are a couple of changes I'm part-way through making to this PR. Should be ready for review in a week or two.

**Comment by ominitay** [comment]
Emulation on unsupported targets and large int types has been moved to compiler-rt. Yet to implement calls to this from other backends, but x86 backend should now pass behaviour tests. Before ready for review, I'll look at implementing testing of the various implementations of this against each other to each other with random integers, as we have 4 of them: the two compiler-rt methods (generic and bigint), the comptime bigint, and the native instruction call, so any latent bugs I could have missed should be detected. This is kind of building off of @matu3ba's suggestions: https://github.com/ziglang/zig/pull/15285#discussion_r1167245563

**Comment by ominitay** [comment]
Disabled the failing behaviour tests caused by the bug in the x86 backend. My rationale here is that it's not within the scope of this PR to work around, as a user needing to use this functionality could simply just not use the x86 backend.

**Comment by andrewrk** [comment]
draft status for > 30 days

**Pull request closed without merging**
