### PR TITLE
Sema: add error for redundant '.compile_time' call modifier in a comptime scope

### PR DESCRIPTION
**Pull request by wrongnull**

### CODE REVIEW

**Comment by Vexu** [comment]
I don't think this is a good idea, and even if added `block.is_comptime` doesn't mean it was explicitly marked comptime with the `comptime` keyword.

**Comment by wrongnull** [comment]
> I don't think this is a good idea, and even if added `block.is_comptime` doesn't mean it was explicitly marked comptime with the `comptime` keyword.

The main idea here is to forbid redundant ```@call``` with ```.compile_time``` modifier in any comptime context. Since
```zig
comptime {
    _ = comptime f();
}
```
is a compilation error, I decided that
```zig
comptime {
    _ = @call(.compile_time, f, .{});
}
```
should be compilation error as well. Code from test case is just a syntactic reduction of this example.

**Comment by Vexu** [comment]
Yes, but your patch also makes this a compile error:
```zig
fn foo() void {
    _ = @call(.compile_time, f, .{});
}
comptime {
    foo();
}
```

**Comment by wrongnull** [comment]
> Yes, but your patch also makes this a compile error:
> ```zig
> fn foo() void {
>     _ = @call(.compile_time, f, .{});
> }
> comptime {
>     foo();
> }
> ```

I see. Probably I should move this check into AstGen

**Comment by mlugg** [comment]
This check cannot live in AstGen, as it requires semantic analysis to determine the value of the first argument. Implementing this would probably necessitate a new ZIR instruction or something like that to represent an `@call` in an explicitly-comptime scope.

However, Vexu disagrees with this language change, and so do I. As far as I know, no member of the core team has voiced support for it. Please open a proposal.

**Pull request closed without merging**
