### PR TITLE
remove `-fstage1` option

### PR DESCRIPTION
**Pull request by andrewrk**
After this commit, the self-hosted compiler does not offer the option to use stage1 as a backend anymore.

Merge blockers:
 * #6025
 * #12756
 * #12880
 * #13077

### CODE REVIEW

**Comment by jedisct1** [comment]
#12880 is major issue preventing stage2 from being used when targeting WebAssembly.

**Comment by Luukdegram** [comment]
> #12880 is major issue preventing stage2 from being used when targeting WebAssembly.

I was unaware of that issue, but I'll happily investigate and fix the issue before this is merged.

**Comment by billzez** [comment]
Please don't take away stage1 until we can create multi-file modules again:

https://github.com/ziglang/zig/issues/13077

I have multiple projects that are blocked by this (and async/await).

**Comment by IridescentRose** [comment]
Also would like to bring up #12756 where stage2 actually regresses on the abilities of stage1 in terms of inline assembly. In that thread it was also mentioned that this affects aarch64

**Comment by andrewrk** [comment]
Thanks all - I added more merge blockers in the PR description.

**Comment by Luukdegram** [comment]
> #12880 is major issue preventing stage2 from being used when targeting WebAssembly.

#13396 :)

**Comment by nektro** [comment]
https://github.com/ziglang/zig/issues/12404 would like this to be added as a blocker please

**Comment by andrewrk** [comment]
Superseded by #13560. We will be temporarily regressing async/await/suspend/resume in master branch.

**Pull request closed without merging**
