### PR TITLE
Add doc comments to alignment functions

### LINKED ISSUE #2774: alignBackward and alignForward cause integer underflow when called with 0
`std.mem.alignBackward` and `alignForward` cause integer underflow when called with an alignment of 0 respectively.  This is a result of the implementation (the subtraction) that a programmer shouldn't be concerned about, so I propose that if they are called with an alignment of 0, they return 0. Otherwise it should be made clear in the doc comment that an alignment of 0 is not allowed.

### PR DESCRIPTION
**Pull request by SamTebbs33**
This patch fleshes out the doc comments for the alignment functions in std.mem, clarifying that they shouldn't be called with an alignment of 0. Closes #2774

### CODE REVIEW

**Comment by andrewrk** [comment]
I think it can be an even stronger requirement: alignment must be a power of 2.

pow(2, 0) == 1
pow(2, 1) == 2
pow(2, 2) == 4

Note that 0 is not one of the powers of 2

**Comment by SamTebbs33** [comment]
> I think it can be an even stronger requirement: alignment must be a power of 2.
> 
> pow(2, 0) == 1
> pow(2, 1) == 2
> pow(2, 2) == 4
> 
> Note that 0 is not one of the powers of 2

Should I add an assertion to check for powers of 2? I don't see where this would be caught currently.

**Comment by andrewrk** [comment]
> Should I add an assertion to check for powers of 2?

Sounds good.

**Comment by SamTebbs33** [comment]
> > Should I add an assertion to check for powers of 2?
> 
> Sounds good.

Cool, done :)

**Pull request merged**
