### PR TITLE
translate-c: int and pointer cast fix

### LINKED ISSUE #17427: error: @bitCast size mismatch: destination type 'usize' has 64 bits but source type 'c_long' has 32 bits
### Zig Version

0.12.0-dev.3+9c05810be

### Steps to Reproduce and Observed Behavior

1. `git clone https://github.com/kora-org/headstart`
2. `zig build -Darch=riscv64`
3. This error should pop up:
```
zig build-exe headstart Debug riscv64-uefi-msvc: error: the following command failed with 1 compilation errors:
C:\Users\User\AppData\Local\Microsoft\WinGet\Packages\zig.zig.nightly_Microsoft.Winget.Source_8wekyb3d8bbwe\zig-windows-x86_64-0.12.0-dev.3+9c05810be\zig.exe build-exe D:\Azzam\kora\headstart\src\main.zig -cflags -ffreestanding -nostdlib -mno-red-zone -- D:\Azzam\kora\headstart\external\flanterm\flanterm.c D:\Azzam\kora\headstart\external\flanterm\backends\fb.c --cache-dir D:\Azzam\kora\headstart\zig-cache --global-cache-dir C:\Users\User\AppData\Local\zig --name headstart -mcmodel medium -target riscv64-uefi-msvc -mcpu baseline_rv64 --mod build_options::D:\Azzam\kora\headstart\zig-cache\c\617d0a7ef579f0c5c8f720583a81a2fe\options.zig --deps build_options -I D:\Azzam\kora\headstart\external --listen=- 
Build Summary: 1/6 steps succeeded; 1 failed (disable with --summary none)
run transitive failure
└─ run sh transitive failure
   └─ install transitive failure
      └─ install headstart transitive failure
         └─ zig build-exe headstart Debug riscv64-uefi-msvc 1 errors
D:\Azzam\kora\headstart\zig-cache\o\ba881674b31c5b5c615cc912c8122d92\cimport.zig:207:175: error: @bitCast size mismatch: destination type 'usize' has 64 bits but source type 'c_long' has 32 bits
    return flanterm_fb_init(null, null, framebuffer, width, height, pitch, null, null, null, null, null, null, null, @as(?*anyopaque, @ptrFromInt(@as(c_int, 0))), @as(usize, @bitCast(@as(c_long, @as(c_int, 0)))), @as(usize, @bitCast(@as(c_long, @as(c_int, 0)))), @as(usize, @bitCast(@as(c_long, @as(c_int, 1)))), @as(usize, @bitCast(@as(c_long, @as(c_int, 1)))), @as(usize, @bitCast(@as(c_long, @as(c_int, 1)))), @as(usize, @bitCast(@as(c_long, @as(c_int, 0)))));
                                                                                                                                
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
    init: src\console\flanterm.zig:11:16
    main: src\main.zig:25:12
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

### Expected Behavior

It should compiles fine like in x86_64 and aarch64.

### LINKED ISSUE #18543: `translate-c`: negative pointer to void
Take this C for example:
```c
#include <stdio.h>

int main() {
    void *x = (void *)-1;
    printf("ptr: %p\n", x);
}
```

when compiled with `gcc` the result is:
```
ptr: 0xffffffffffffffff
```

however, when compiler with `translate-c`
```
out.zig:295:55: error: type 'usize' cannot represent integer value '-1'
    var x: ?*anyopaque = @as(?*anyopaque, @ptrFromInt(-@as(c_int, 1)));
```

the solution would be to use `-%` wrapping negation for the `-1` I guess.

### PR DESCRIPTION
**Pull request by f-cozzocrea**
Closes #18543, closes #18178, closes #17427.

Fixes an issue where translate-c would not create the correct cast between pointers and non-usize types (or int types that don't coerce to usize). This fix generates correct code that casts between pointers and C integer types of any width or signedness.

I moved several test cases from `test/translate_c.zig` and `test/run_translated_c.zig` into the `test/cases/` dir when I updated them for the new behavior. I also added a `target: std.Target` parameter to `translate_c.translate` in order to detect the size of C integer types and platform specific pointer widths. Let me know if I need to modify how this was done.

Lastly, I manually verified that the behavior is correct for several 32-bit platforms, but when I added a test case targeting 32-bit platforms, I saw a failure. It looks like the test harness targeted a 64-bit platform even though I specified 32-bit only. I may have created the testcase incorrectly. Here's the test case for reference:

```c
#include <stdint.h>

int main() {
  void* ptr = (void *)-1;
  short s = (short)ptr;
  unsigned short us = (unsigned short)ptr;
  int64_t bigint = -1;
  uint64_t biguint = -1;
  ptr = (void *)bigint;
  ptr = (void *)biguint;
  return 0;
}

// translate-c
// c_frontends=clang
// targets=x86-linux-none
//
// var s: c_short = @as(c_short, @bitCast(@as(c_ushort, @truncate(@intFromPtr(ptr)))));
//
// var us: c_ushort = @as(c_ushort, @truncate(@intFromPtr(ptr)));
//
// ptr = @as(?*anyopaque, @ptrFromInt(@as(usize, @bitCast(@as(isize, @truncate(bigint))))));
//
// ptr = @as(?*anyopaque, @ptrFromInt(@as(usize, @truncate(biguint))));
```

cc: @Rexicon226

### CODE REVIEW

**Comment by Rexicon226** [comment]
Awesome, thanks! I'll close my PR.

**Comment by ehaas** [comment]
The only potential problem with detecting the pointer width this way is that the generated code will only be guaranteed to work on the specified target (which may or may not be a problem). The alternative would be to add a runtime check against `@sizeOf(usize)` for the argument to `ptrFromInt` and call `@truncate` if necessary.

**Comment by f-cozzocrea** [comment]
@ehaas Agreed. My assumption was that the generated code is target-specific. If the goal is portable code, then an `@sizeOf(usize)` check will need to be generated.

**Comment by andrewrk** [comment]
The goal is indeed portable code.

**Comment by f-cozzocrea** [comment]
Sounds good, I'll modify the approach to be non-target-specific.

**Comment by f-cozzocrea** [comment]
Superseded by #18758.

**Pull request closed without merging**
