### PR TITLE
cmake: Honor LLVM_DIR in the findLLVM script

### PR DESCRIPTION
**Pull request by LemonBoy**
Allow the user to set a custom path where llvm, clang and lld are built
without having to muck too much with the build system.

### CODE REVIEW

**Comment by andrewrk** [comment]
This changes a lot of cmake build stuff which I'm worried will break something. Can you explain your use case, why you need these changes?

Is there a reason `CMAKE_PREFIX_PATH` isn't solving the problem?

**Comment by LemonBoy** [comment]
> This changes a lot of cmake build stuff which I'm worried  will break something. Can you explain your use case, why you need these  changes?

It's mostly a cleanup that removes a bit of duplicated code, the chances of breaking something are quite low since the added code adds another code path without touching the old one.

> Is there a reason CMAKE_PREFIX_PATH isn't solving the problem?

Doing `-DLLVM_DIR=<path to my llvm root>` is much simpler than wresting the many hardcoded paths in the cmake script.

**Comment by andrewrk** [comment]
What OS is this? What error do you get when you try to build without your changes?

**Comment by LemonBoy** [comment]
> What OS is this? 

Linux.

> What error do you get when you try to  build without your changes?

Don't remember anymore, it took me less time to fix up this cmake script than to find the correct combo of defines to make it work. Build systems ain't no fun.

> LLVM and Clang built from source or using  system package manager?

Patched & freshly built, LLVM, Clang and LLD.

**Comment by andrewrk** [comment]
I'm sorry, I understand your frustration. But I'm not willing to accept this without an explanation of why the [officially supported way](https://github.com/ziglang/zig/wiki/How-to-build-LLVM%2C-libclang%2C-and-liblld-from-source#posix) didn't work. That link describes not only how to build Zig but how to use cmake in general to build anything. I would like to avoid special case code when the common best practice will suffice.

**Comment by andrewrk** [comment]
@LemonBoy do you still want to pursue this?

**Pull request closed without merging**
