### PR TITLE
Add builtin.Signedness, use it instead of is_signed

### PR DESCRIPTION
**Pull request by tadeokondrak**
https://github.com/ziglang/zig/pull/6713#discussion_r506992541

### CODE REVIEW

**Comment by andrewrk** [comment]
Don't lie, you were halfway through implementing this when I made that comment that mentioned your name, weren't you?

**Comment by andrewrk** [comment]
Hmm I'm not sure what's causing those CI failures. Mind rebasing and force pushing so we can check if it was a temporary build failure of master branch?

**Review by andrewrk — APPROVED** [review]

**Comment by tadeokondrak** [comment]
Don't know why FreeBSD is failing, but macOS is trying to compile something with an old compiler but new stdlib.

**Comment by andrewrk** [comment]
> macOS is trying to compile something with an old compiler but new stdlib.

Ah! Right. I made a mental note to myself to fix this before this happened, but here we are. On it.

**Comment by andrewrk** [comment]
Can you try rebasing after a0f4606f32bab6df88d0afc1bf9ff479470b68cc? (sorry, this is a change to the CI system so the only way to test it is with CI builds)

The freebsd problem seems to be an operational issue with the SourceHut instance, and Luna is looking into it.

**Comment by tadeokondrak** [comment]
macOS is failing with
```
invalid target: unrecognized operating system
See `/Users/runner/work/1/s/build/zig0 --help` for detailed usage information
make[2]: *** [CMakeFiles/zig_build_zig1] Error 1
make[1]: *** [CMakeFiles/zig_build_zig1.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by andrewrk** [comment]
OK I'm really sorry for all the stuff that was not your fault causing the delay of merging this. Would you mind shouldering the burden of rebasing this and dealing with the conflicts? I expect the CI to pass now that #6830 is solved.

**Comment by andrewrk** [comment]
OK now we're on to legitimate failures

**Pull request merged**
