### PR TITLE
Stage2: floats

### PR DESCRIPTION
**Pull request by Vexu**

### CODE REVIEW

**Comment by andrewrk** [comment]
Looks like an issue with the stage1 changes

**Comment by Vexu** [comment]
Azure ci is broken same happened with #5904. Drone is likely caused by some `f128` or `f16` operation, thankfully LLVM is being super helpful with its error messages.

**Comment by andrewrk** [comment]
I think we should disable the new behavior test case on aarch64 for now, I think there is already an open issue for it. Code looks good otherwise, ready to merge :+1:

**Comment by andrewrk** [comment]
I just pushed a slightly disruptive commit 8ee629aa4c7fb0127c71aec0b2c81353c4291ebb - hopefully it should be clear how to resolve any conflicts that come up

**Pull request merged**
