### PR TITLE
Moar SIMD stuff

### LINKED ISSUE #4050: Compiler error with float vectors
`repro.zig`
```zig
pub fn main() void {
    @setFloatMode(.Optimized);
    var x: @Vector(3, f64) = undefined;
    const y = x / x;
}
```

Output: 
```
➜  zig-experiments git:(master) ✗ zig build-exe repro.zig
Code Generation [98/345] std.fs.path.joinSep...broken LLVM module found: Both operands to FCmp instruction are not of the same type!
  %13 = fcmp fast oeq <3 x double> %12, double 0.000000e+00, !dbg !1044
Branch condition is not 'i1' type!
  br <3 x i1> %13, label %DivZeroFail, label %DivZeroOk, !dbg !1044
  %13 = fcmp fast oeq <3 x double> %12, double 0.000000e+00, !dbg !1044

This is a bug in the Zig compiler.
Unable to dump stack trace: FileNotFound
```

Any of these changes makes the code compile:
- Change float mode to Strict
- Change `var x` to `const x`
- Change `const y` to `_`

Versions:
```
➜  zig-experiments git:(master) ✗ zig version
0.5.0+a90fa45ae
```
macOS Mojave 10.14.6

### PR DESCRIPTION
**Pull request by LemonBoy**
The tests don't cover the error checks and so on because I got bored, patches welcome.

Closes #4050

### CODE REVIEW

**Comment by LemonBoy** [comment]
The Windows failure is a LLVM bug, the usual problems with f16 that can be safely skipped, but the Linux failure is because QEMU is too old and I'm not sure if we should skip it somehow (?) or just bite the bullet and upgrade the QEMU binaries.

**Comment by andrewrk** [comment]
I'll work on upgrading the qemu binaries

**Comment by andrewrk** [comment]
Now that #4906 is merged you should be unblocked

**Comment by andrewrk** [comment]
Green CI, beautiful. This looks like a bunch of nice work. The next step to merging is to write runtime_safety.zig test cases for all the new safety checks (whether such tests are written by @LemonBoy, myself, or another contributor).

**Comment by andrewrk** [comment]
I tried to add a runtime safety test for overflow on signed integer overflow on division:

```zig
pub fn main() !void {
    var a: @Vector(4, i16) = [_]i16{ 1, 2, -32768, 4 };
    var b: @Vector(4, i16) = [_]i16{ 1, 2, -1, 4 };
    const x = div(a, b);
    if (x[2] == 32767) return error.Whatever;
}
fn div(a: @Vector(4, i16), b: @Vector(4, i16)) @Vector(4, i16) {
    return @divTrunc(a, b);
}
```

I get SIGFPE:

```
[nix-shell:~/dev/zig/build]$ ./zig build-exe test3.zig 

[nix-shell:~/dev/zig/build]$ ./test3
Floating point exception (core dumped)

[nix-shell:~/dev/zig/build]$ gdb ./test3 -ex run
GNU gdb (GDB) 8.3.1
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./test3...
Starting program: /home/andy/dev/zig/build/test3 

Program received signal SIGFPE, Arithmetic exception.
0x000000000022e49a in div (a=..., b=...) at /home/andy/dev/zig/build/test3.zig:8
8	    return @divTrunc(a, b);
(gdb) p a
$1 = {1, 2, -32768, 4}
(gdb) p b
$2 = {1, 2, -1, 4}
(gdb) ptype a
type = i16 __attribute__ ((vector_size(4)))
(gdb) ptype b
type = i16 __attribute__ ((vector_size(4)))
(gdb) 
```

**Comment by LemonBoy** [comment]
> I get SIGFPE:

My bad, I forgot to re-add some logic after a refactor.

**Pull request closed without merging**
