### PR TITLE
linux-i386 support

### PR DESCRIPTION
**Pull request by LemonBoy**
I didn't add a `socketcall` stub for `sendmmsg` because it's horribly messy and lost all the motivation halfway trough.

Enjoy :tada:

### CODE REVIEW

**Comment by andrewrk** [comment]
> TODO implement target_dynamic_linker for mips

That one should hopefully be straightforward:

https://github.com/ziglang/zig/blob/85e1e3b95f1f1699a842a5e889d8987692a829a4/src/target.cpp#L1307-L1311

Here's the relevant code from clang:

```c++
  case llvm::Triple::mips: {
    std::string MT = IsMipsR6 ? "mipsisa32r6-linux-gnu" : "mips-linux-gnu";
    if (D.getVFS().exists(SysRoot + "/lib/" + MT))
      return MT;
    break;
  }
  case llvm::Triple::mipsel: {
    if (IsAndroid)
      return "mipsel-linux-android";
    std::string MT = IsMipsR6 ? "mipsisa32r6el-linux-gnu" : "mipsel-linux-gnu";
    if (D.getVFS().exists(SysRoot + "/lib/" + MT))
      return MT;
    break;
  }
  case llvm::Triple::mips64: {
    std::string MT = std::string(IsMipsR6 ? "mipsisa64r6" : "mips64") +
                     "-linux-" + (IsMipsN32Abi ? "gnuabin32" : "gnuabi64");
    if (D.getVFS().exists(SysRoot + "/lib/" + MT))
      return MT;
    if (D.getVFS().exists(SysRoot + "/lib/mips64-linux-gnu"))
      return "mips64-linux-gnu";
    break;
  }
  case llvm::Triple::mips64el: {
    if (IsAndroid)
      return "mips64el-linux-android";
    std::string MT = std::string(IsMipsR6 ? "mipsisa64r6el" : "mips64el") +
                     "-linux-" + (IsMipsN32Abi ? "gnuabin32" : "gnuabi64");
    if (D.getVFS().exists(SysRoot + "/lib/" + MT))
      return MT;
    if (D.getVFS().exists(SysRoot + "/lib/mips64el-linux-gnu"))
      return "mips64el-linux-gnu";
    break;
  }
```

**Comment by andrewrk** [comment]
2 new targets gaining test coverage here, still pretty great

**Comment by andrewrk** [comment]
Also I went ahead and filed https://todo.sr.ht/~sircmpwn/builds.sr.ht/252

**Comment by daurnimator** [comment]
Doesn't linux now have non-`socketcall` syscalls? e.g. `recvmsg` should be syscall `372`?

**Comment by andrewrk** [comment]
Our current minimum Linux is 3.16. But it's planned to have #1907, so both impls would be OK. Also in a separate issue, anyone is free to make a case for raising the minimum supported version, if the vast majority of Linux distributions are on a newer kernel.

**Comment by andrewrk** [comment]
I'll have a look at that windows failure locally. I suspect we may be hitting memory limits (see #471) on the Windows CI.

**Comment by LemonBoy** [comment]
> Even if i386-linux-gnu and the mips targets couldn't be enabled, there are still 2 new targets gaining test coverage here, which is still pretty great

The work required to get i386+glibc to work outweighs any possible advantage:
- You'd have to provide the `get_pc_thunk` stubs [1] and find out why clang doesn't generate them (afaics they use a slightly different strategy to get the current IP that requires no stubs)
- Change the stdlib to use the 64-bit version of all the I/O functions (`open64`, `lseek64`, `fstat64`...)
- Try to understand why glibc exports lseek64 with version 2.2 on every architecture but i386, where the only `lseek64` symbol has version 2.1. This makes the change outlined above non-trivial.

The mips+glibc target requires some glibc build-system debugging, a dull and boring task that excites no one.

> Linux (since 4.2) has non-socketcall syscalls. e.g. recvmsg is syscall 372

Backwards compatibility with `3.6` (and possibly older kernels) requires those calls to go through `socketcall`.

[1] https://raw.githubusercontent.com/gcc-mirror/gcc/master/gcc/config/i386/i386.c

**Comment by daurnimator** [comment]
>     * You'd have to provide the `get_pc_thunk` stubs [1] and find out why clang doesn't generate them (afaics they use a slightly different strategy to get the current IP that requires no stubs)

If clang doesn't need them... why do we? Is this a libgcc thing? or a glibc thing?


> Change the stdlib to use the 64-bit version of all the I/O functions (`open64`, `lseek64`, `fstat64`...)

We'll need to do that anyway at some point right?



> Backwards compatibility with `3.6` (and possibly older kernels) requires those calls to go through `socketcall`.

Yeah fair enough: that needs to wait for #1907

**Comment by LemonBoy** [comment]
> If clang doesn't need them... why do we? Is this a libgcc thing? or a glibc thing?

Good question, the glibc sources Zig ships with include a [definition](https://github.com/ziglang/zig/blob/3f4abe97bdbe666dbb3532c14a97e414aae4caca/lib/libc/glibc/sysdeps/i386/sysdep.h#L98-L111) of those stubs in the `.gnu.linkonce` section to avoid code bloat. Nowadays the very same is achieved by a comdat section so `lld` helpfully [discards those](https://github.com/ziglang/zig/blob/e81156b87364a31bee892aee2e6145f65c02fa35/deps/lld/ELF/InputFiles.cpp#L1015) as the [compiler](https://raw.githubusercontent.com/gcc-mirror/gcc/master/gcc/config/i386/i386.c) is expected to generate them. Lo and behold, we end up with a relocation against a symbol that's been discarded and LLD is very sad about that.

The real question is whether glibc can be successfully built with clang or not.

**Pull request merged**
