### PR TITLE
Implement more intrinsics in new LLVM IR builder API and remove uses of LLVM owns API

### PR DESCRIPTION
**Pull request by antlilja**
This PR implements more intrinsics in zigs own LLVM IR builder and removes usages of the old LLVM API. All bit op and floating point intrinsics should now be implemented.

Intrinsics implemented
* llvm.ceil
* llvm.cos
* llvm.exp
* llvm.exp2
* llvm.fabs
* llvm.floor
* llvm.log
* llvm.log10
* llvm.log2
* llvm.round
* llvm.sin
* llvm.trunc
* llvm.fma
* llvm.bitreverse
* llvm.bswap
* llvm.ctpop
* llvm.ctlz
* llvm.cttz

### CODE REVIEW

**Comment by jacobly0** [comment]
Thanks!  Just keep in mind that the intrinsic instructions are temporary and the goal is to have enough information to be able to emit the intrinsic declarations and just use normal instrsuctions without any dependence on the LLVM APIi.

**Comment by antlilja** [comment]
> Thanks! Just keep in mind that the intrinsic instructions are temporary and the goal is to have enough information to be able to emit the intrinsic declarations (including attributes) and just use normal instructions without any dependence on the LLVM API.

Yes, I'm guessing the plan is to transition all the LLVM codegen code to the new builder and then transistion the builder into doing its own bitcode output.

**Comment by jacobly0** [comment]
I have designed a non-temporary intrinsic api over at #16708

**Comment by antlilja** [comment]
> I have designed a non-temporary intrinsic api over at #16708

Nice! I'll take a look.

**Pull request merged**
