### PR TITLE
translate-c: support goto statements

### LINKED ISSUE #11992: zig `translate-c` - Error on functor type
### Zig Version

0.10.0-dev.2836+2360f8c49

### Steps to Reproduce

During the code translation a type mismatch occurs.

### Original C code:

Full code:
- https://github.com/LykenSol/rust-demangle.c/blob/eed29f57732ddb2be434ec89f8ede9b695e5e157/rust-demangle.c#L904-L937

```c
static void str_buf_append(struct str_buf *buf, const char *data, size_t len) {
  str_buf_reserve(buf, len);
  if (buf->errored)
    return;

  memcpy(buf->ptr + buf->len, data, len);
  buf->len += len;
}

static void str_buf_demangle_callback(const char *data, size_t len,
                                      void *opaque) {
  str_buf_append(opaque, data, len);
}

char *rust_demangle(const char *mangled, int flags) {
  struct str_buf out;

  out.ptr = NULL;
  out.len = 0;
  out.cap = 0;
  out.errored = false;

  bool success = rust_demangle_with_callback(mangled, flags,
                                             str_buf_demangle_callback, &out);

  if (!success) {
    free(out.ptr);
    return NULL;
  }

  str_buf_append(&out, "\0", 1);
  return out.ptr;
}
```
---

### Zig translated

Full code:
- https://zig.godbolt.org/z/nrf9ndqEx
- 
```zig
pub fn str_buf_append(arg_buf: [*c]struct_str_buf, arg_data: [*c]const u8, arg_len: usize) callconv(.C) void {
    var buf = arg_buf;
    var data = arg_data;
    var len = arg_len;
    str_buf_reserve(buf, len);
    if (buf.*.errored) return;
    _ = memcpy(@ptrCast(?*anyopaque, buf.*.ptr + buf.*.len), @ptrCast(?*const anyopaque, data), len);
    buf.*.len +%= len;
}
pub fn str_buf_demangle_callback(arg_data: [*c]const u8, arg_len: usize, arg_opaque: ?*anyopaque) callconv(.C) void {
    var data = arg_data;
    var len = arg_len;
    var @"opaque" = arg_opaque;
    str_buf_append(@ptrCast([*c]struct_str_buf, @alignCast(@import("std").meta.alignment(struct_str_buf), @"opaque")), data, len);
}
pub export fn rust_demangle(arg_mangled: [*c]const u8, arg_flags: c_int) [*c]u8 {
    var mangled = arg_mangled;
    var flags = arg_flags;
    var out: struct_str_buf = undefined;
    out.ptr = null;
    out.len = 0;
    out.cap = 0;
    out.errored = @as(c_int, 0) != 0;
    var success: bool = rust_demangle_with_callback(mangled, flags, str_buf_demangle_callback, @ptrCast(?*anyopaque, &out));
    if (!success) {
        free(@ptrCast(?*anyopaque, out.ptr));
        return null;
    }
    str_buf_append(&out, "\x00", @bitCast(usize, @as(c_long, @as(c_int, 1))));
    return out.ptr;
}
```

### Expected Behavior

No error

### Actual Behavior

```bash
./src/demangle.zig:1283:69: error: expected type '*const fn([*c]const u8, usize, ?*anyopaque) callconv(.C) void', found 'fn([*c]const u8, usize, ?*anyopaque) callconv(.C) void'
    var success: bool = rust_demangle_with_callback(mangled, flags, str_buf_demangle_callback, @ptrCast(?*anyopaque, &out));
                                                                    ^
```

### PR DESCRIPTION
**Pull request by rpkak**
Goto support works by creating a boolean variable per label, which is false by default. A goto changes this variable to `true` and breaks to the highest common scope of the goto and the label. Now, `if` and `while` statements, which are controlled by the boolean variable, jump over the execution part of the code to get to the label.

closes #11992

### CODE REVIEW

**Comment by rpkak** [comment]
I think I completed this PR now. It lacks the ability to use `goto` to jump out of or within a statement expression, but I don't think there is much need for this.
As I stated in a87c4700247c7e1f15b40e777bc16fdf66bdf275 this PR also fixes #14809.
This PR inserts `while` loops which exist not as `while` loops in the c code. These loops have the same issues as descripted in #15155/#16790.

**Comment by mnemnion** [comment]
Shouldn't a feature like this wait on #19812? That will be a more performant and general way to translate gotos into Zig, without adding extra conditionals to the code.

**Comment by rpkak** [comment]
> Shouldn't a feature like this wait on #19812? That will be a more performant and general way to translate gotos into Zig, without adding extra conditionals to the code.

@mnemnion I don't see how #19812 will make this more performant or general.
I have not seen any c code snippet, where llvm does not optimize away the goto-variable generated by this PR.

For the translation of c-switch statements, I argree. Translate-c outputs zig code multiple times, if the code is accessible by multiple cases. This PR makes translate-c also output case code once more, if the case is accessed by a goto. But this rewrite would be translate-c-switch specific and not translate-c-goto specific.

**Comment by mnemnion** [comment]
> This PR makes translate-c also output case code once more, if the case is accessed by a goto. But this rewrite would be translate-c-switch specific and not translate-c-goto specific.

Thanks for the reply. My main intention was to bring that branch to your attention, if you weren't aware of it, I apologize if it came across as second-guessing. 

Many non-trivial uses of goto are in complex case statements, particularly those implementing a VM dispatch loop, a case (heh) that the labeled continue branch is specifically designed to handle. You say that would constitute a distinct branch? I believe you. Cheers.

**Comment by rpkak** [comment]
I close this PR, because it has not been merged yet and new features in zig allow for better code in these changes as well as the generated code.

**Pull request closed without merging**
