### PR TITLE
prevent pointer casts that allow writing invalid values

### LINKED ISSUE #15874: Invalid pointer casts permitted by in-memory coercion to covariant types
### Zig Version

0.11.0-dev.3031+f40539e5d

### Steps to Reproduce and Observed Behavior

```zig
pub fn main() void {
    var e: error{Foo} = error.Foo;
    const p: *error{ Foo, Bar } = &e;
    p.* = error.Bar;
    @import("std").log.info("{}", .{e});
}
```
Output:
`info: error.Bar`
This output should be impossible, since `e` is of type `error{Foo}` so should not be able to hold the value `error.Bar`.

### Expected Behavior

A compile error should be triggered.

This happens because a pointer `*T` is allowed to coerce to a pointer `*U` whenever `T` is in-memory coercible to `U`. When the target pointer is not `const`, this is insufficient: it is also a requirement that `U` be in-memory coercible to `T`, so that writes to the pointer cannot assign invalid values to the destination.

### PR DESCRIPTION
**Pull request by yujiri8**
Closes #15874

At first I tried to block this kind of coercion for all types, but I ran into a case where the compiler coerces `[][:0]u8` to `[][:0]const u8` which was disallowed, and I had trouble allowing that while disallowing the problematic cases, so I tried making it specific to errors as @mlugg suggested in the issue.

As far as I can tell, this works for both error sets and error unions and I'm not aware of any other problematic cases.

I don't know how to add a test for a compile error. I see the tests in `test/cases/compile_errors`, but I don't know they work because they don't seem to be referenced from anywhere and I don't know how to run them.

### CODE REVIEW

**Comment by r00ster91** [comment]
> I don't know how to add a test for a compile error. I see the tests in test/cases/compile_errors, but I don't know they work because they don't seem to be referenced from anywhere and I don't know how to run them.

Usually you have a function called `export fn entry() void {}` (or multiple `entry1`, `entry2`, etc.) that contains the code that is supposed to error. The expected errors go at the end. Example: [`test/cases/compile_errors/@intCast_on_vec.zig`](https://github.com/ziglang/zig/pull/15879/files#diff-e574836a280428fd6410d0e1f62cea78a5c7af9d988bd6d78aeab8f385807fe4)

To test, run `zig-out/bin/zig build test-cases` where `zig-out/bin/zig` is the compiler containing your changes. IIRC there is a way to run only a single test case by building an executable of `test/src/Cases.zig` but I don't remember an easy way to do that. `zig build test-cases` doesn't take long though (maybe 2-3 mins).

**Comment by yujiri8** [comment]
Done! Added test and the suite passed.

**Review by Vexu — COMMENTED** [review]
This suffers from the issue described in #13586. I think it would also be useful to add a note along the lines of `"mutable destination error set contains errors not present in source error set"`.

**Comment by Vexu** [comment]
> Do you mean the type names are reversed? I think it makes sense. It's assigning to a value of type `*error{Bar,Foo}`, so it's expecting `*error{Bar,Foo}`, but found `*error{Foo}`.

Yes but the error notes say that `error.Bar` is not a member of destination error set when that is the only error set it is a member of:
```zig
//:3:35: error: expected type '*error{Bar,Foo}', found '*error{Foo}'
//:3:35: note: pointer type child 'error{Foo}' cannot cast into pointer type child 'error{Bar,Foo}'
//:3:35: note: 'error.Bar' not a member of destination error set
```

**Comment by yujiri8** [comment]
Oh, I see. I'll see if I can fix it.

**Comment by yujiri8** [comment]
I understand the cause of the problem, I think, but it's not obvious how to fix it.

So, the InMemoryCoercionResult returned is `.ptr_child`, containing an inner InMemoryCoercionResult that is `.missing_error`. `.missing_error` results don't contain information about which direction the coercion was going (probably because this is the only cause where it's reversed), and where they're stringified, there's no information about whether it was caused by this reversed comparison.

**Comment by yujiri8** [comment]
Well. I thought of a solution and it works. It's not pretty, but I'll go ahead and update the PR so you can see what you think.

**Comment by yujiri8** [comment]
Fixed merge conflicts.

**Comment by yujiri8** [comment]
I see this has been broken by intermediate changes. Oh well. I'm not putting in the work to figure out how to fix it just for it to be left to sit for 2 more weeks and then need to be rebased again.

**Comment by andrewrk** [comment]
Thanks for taking a stab at it. Who knows, maybe the person who ends up solving the issue in the future will get a head start based on your commits.

**Pull request closed without merging**
