### PR TITLE
build.zig: Support shared LLVM libraries on macOS

### PR DESCRIPTION
**Pull request by topolarity**
Link libc++ dynamically by providing it as an object file instead of `-lc++`.

This is a workaround for #12147, and we already do something similar when using system LLVM/Clang/LLD on Linux.

This change also adds logic to look-up the system libc++ includes on Linux and BSD-likes. This was needed to fix a bug on Linux where we were using Zig-provided libc++ includes even when linking against the system-provided lib.

### CODE REVIEW

**Comment by kubkon** [comment]
How do we test this on macOS?

**Comment by topolarity** [comment]
> How do we test this on macOS? I'd like to double check this works as intended before we merge it.

I tested this on x86_64-macos using `cmake .. -DCMAKE_PREFIX_PATH="$(brew --prefix llvm);$(brew --prefix zstd)"`

You can also provide `-DZIG_SHARED_LLVM=ON` to force Zig to link LLVM dynamically.

> It might also make sense to add this as an alternative building method on macOS in the Wiki.

Yeah, the main user impact is that they no longer need `-DZIG_STATIC_LLVM=ON` when building with Homebrew LLVM.

**Comment by kubkon** [comment]
> > How do we test this on macOS? I'd like to double check this works as intended before we merge it.
> 
> I tested this on x86_64-macos using `cmake .. -DCMAKE_PREFIX_PATH="$(brew --prefix llvm);$(brew --prefix zstd)"`
> 
> You can also provide `-DZIG_SHARED_LLVM=ON` to force Zig to link LLVM dynamically, although that's already the default for Homebrew LLVM.
> 
> > It might also make sense to add this as an alternative building method on macOS in the Wiki.
> 
> Yeah, the main user impact is that you no longer need `-DZIG_STATIC_LLVM=ON` when building with Homebrew LLVM.

Excellent! Lemme try it locally on my M1 first and I think we are good to go!

**Comment by kubkon** [comment]
@topolarity would you mind rebasing and fixing conflicts so we can revisit merging this in?

**Comment by andrewrk** [comment]
Closing due to conflicts and needs more CI checks.

**Pull request closed without merging**
