### PR TITLE
stage1: support @alignOf(T) aligned member inside struct T

### LINKED ISSUE #1832: Compiler crashes when using a struct T which contains a field of type ArrayList(T)
When running the code below zig fails without printing any information as to what went wrong (or any other information for that matter). No files are being created either.
I'm expecting the compiler to tell me if I do something wrong.

Zig version:

    0.3.0+bbdc1289

Platform:

    Windows 10 Pro N

Return Code:

    -1073741819

Code:
```
const std = @import("std");

pub fn main() void {
    _ = Node {
        .subList = undefined
    };
}

const Node = struct {
    subList: std.ArrayList(Node)
};
```

### PR DESCRIPTION
**Pull request by kristate**
Fixes #1832 

* [X] Implementation
* [X] Documentation (comments)
* [X] Tests

### CODE REVIEW

**Comment by kristate** [comment]
@bdoner All tests passed; can you please test your code regarding #1845 ?

**Comment by bdoner** [comment]
Will check it out later this evening!

**Comment by andrewrk** [comment]
Here's a problematic case:

```zig
export fn entry() void {
    var n1: Node1 = undefined;
    var n2: Node2 = undefined;
}

const Node1 = struct {
    data: [@alignOf(Node1)]u8,
};

const Node2 = struct {
    data: [1]u8,
};
```

```llvm
  %n1 = alloca %Node1, align 8
  %n2 = alloca %Node2, align 1
```

This will also cause under-alignment problems when #1512 is implemented. The problem is that the assumption that if we hit a recursion loop then the answer is pointer alignment is not always correct.

A more correct solution involves a larger change that introduces "lazy type values" where you can query information, such as, "are you zero bits or not?", "what is your alignment?" while minimally evaluating the sub-expressions in the type. For example, for the expression `[]align(@alignOf(Node)) Node`, we can answer the alignment query without evaluating the expression `@alignOf(Node)` because the pointer alignment is irrelevant to the query; based on the fact that it is a slice we already know it is pointer size aligned.

That said, this is stage1, and this is an improvement. So I think we can merge this and I'll make a separate issue for the problematic cases.

**Comment by andrewrk** [comment]
Merged. Thanks @kristate

**Comment by kristate** [comment]
> A more correct solution involves a larger change that introduces "lazy type values" where you can query information, such as ...

Yes, I spent a day thinking about such a system and even thought about piggybacking ontop of `ResolveStatus` and friends, but in the end I decided on this solution as a stop-gap until copy elision lands.

It would be nice to have some sort of graph to query like you mentioned.

**Pull request merged**
