### PR TITLE
Add missing compiler error for @import on absolute paths

### PR DESCRIPTION
**Pull request by wrongnull**
According to #3393 ```@import```
is not supposed to accept absolute path. So this pr may close this issue.

### CODE REVIEW

**Comment by wrongnull** [comment]
@nektro
Whether a path is relative or absolute depends on os determination which is comptime control-flow. I have no idea how to communicate an error message.

**Comment by nektro** [comment]
you can set the target like so https://github.com/ziglang/zig/blob/master/test/cases/conditional_branches.0.zig#L19 to make the separator used in the error deterministic

**Review by Vexu — CHANGES_REQUESTED** [review]
Importing with absolute path should either result in an import outside of package path error like `@embedFile` (better, fewer special cases), or `@embedFile` should also detect absolute paths.

**Comment by rohlem** [comment]
@Vexu Does your first suggestion lead to the user receiving an error stating the path is outside their package, even if the provided absolute path is actually inside their package?
The second option, of adding the absolute path check to `@embedFile`, seems less confusing to me.

**Comment by Vexu** [comment]
In that case the error being about the absolute path would be better but the import outside package path error should still be preferred otherwise. And `@import` should of course behave in the same way.

**Comment by andrewrk** [comment]
Closing abandoned PR (CI checks failing).

**Pull request closed without merging**
