### PR TITLE
std.{ArrayList,ArrayHashMap,MultiArrayList,BoundedArray}: popOrNull() -> pop()

### PR DESCRIPTION
**Pull request by nektro**

### CODE REVIEW

**Comment by thejoshwolfe** [comment]
is there a discussion of this elsewhere i can read? what's the motivation for this change?

**Comment by nektro** [comment]
https://github.com/ziglang/zig/pull/19406#discussion_r1536731443 and that having both Is redundant

**Comment by nektro** [comment]
carefully looked over my code again and didn't see anything that stuck out that seemed to be the cause of the CI issue i'm seeing, which i unfortunately believe is a bug in the c backend. will try to reproduce separately.

**Comment by nektro** [comment]
if the type names are correct its while using a `std.AutoArrayHashMapUnmanaged(void, void)`

**Comment by andrewrk** [comment]
CI checks failing; no update in 30+ days

**Pull request closed without merging**
