### PR TITLE
translate-c edge case: negating void pointer

### LINKED ISSUE #18543: `translate-c`: negative pointer to void
Take this C for example:
```c
#include <stdio.h>

int main() {
    void *x = (void *)-1;
    printf("ptr: %p\n", x);
}
```

when compiled with `gcc` the result is:
```
ptr: 0xffffffffffffffff
```

however, when compiler with `translate-c`
```
out.zig:295:55: error: type 'usize' cannot represent integer value '-1'
    var x: ?*anyopaque = @as(?*anyopaque, @ptrFromInt(-@as(c_int, 1)));
```

the solution would be to use `-%` wrapping negation for the `-1` I guess.

### PR DESCRIPTION
**Pull request by Rexicon226**
closes #18543

cc @Vexu 

I shed a couple tears writing this, just thinking about why anyone would use negative void pointers. Good news is that my original code that triggered this investigation in the first place compiles and works now!

### CODE REVIEW

**Comment by ehaas** [comment]
The underlying problem will happen with integer variables as well, not just literals. e.g. 
```c
    int x = 0;
    void *p = (void *)x;
```

So we can't just look for a negation operation. I also think reaching into the expression to pull a subexpression out and reuse in a different expression is non-standard; I don't see that being done anywhere else in `translate_c.zig`

Instead I think we need separate cases for signed vs unsigned integers. The status-quo code should be used for unsigned integers (you can use `cIsUnsignedInteger` to check for that). For signed integers (`cIsSignedInteger`) we should as-cast to isize and then bitcast to usize.

**Comment by Rexicon226** [comment]
> The underlying problem will happen with integer variables as well, not just literals. e.g. 
> 
> ```c
> 
>     int x = 0;
> 
>     void *p = (void *)x;
> 
> ```
> 
> 
> 
> So we can't just look for a negation operation. I also think reaching into the expression to pull a subexpression out and reuse in a different expression is non-standard; I don't see that being done anywhere else in `translate_c.zig`
> 
> 
> 
> Instead I think we need separate cases for signed vs unsigned integers. The status-quo code should be used for unsigned integers (you can use `cIsUnsignedInteger` to check for that). For signed integers (`cIsSignedInteger`) we should as-cast to isize and then bitcast to usize.
> 
> 
> 
> 

I agree that my solution is a bit flimsy and doesn't target the core issue and can totally be improved. However I'm a bit confused by what you suggest. The logical issue that I ran into was the inability to look ahead to see the ptrFromInt afaik. Please correct me if I'm wrong. The solution you propose would also require parsing the payload further. What if we just blanket as(usize, bitCast(expr)). This should solve it I think? (not at the computer so i can't test).

**Comment by Rexicon226** [comment]
I did a mix of the both. I think that taking your solution and just blanketing `ptrFromInt` with it is the right way. There are just too many edge cases and what-not to make it specific to signed integers.

**Comment by f-cozzocrea** [comment]
@Rexicon226 It doesn't work to just `@as(usize, expr)` because the compiler will complain if the expression is signed. We need to sign extend signed types, then bitcast to usize. 

If unsigned QualType (using cIsUnsignedInteger):
@as(usize, expr)

If signed QualType (using cIsSignedInteger):
@as(usize, @bitCast(@as(isize, expr)))

**Comment by Rexicon226** [comment]
> @Rexicon226 It doesn't work to only `@as(usize, expr)` because the compiler will complain if the expression is signed. We need to sign extend signed types, then bitcast to usize.
> 
> If unsigned QualType (using cIsUnsignedInteger): `@as(usize, expr)`
> 
> If signed QualType (using cIsSignedInteger): `@as(usize, @bitCast(@as(isize, expr)))`

Yeah, that’s what I did. Sorry, I had a flight to catch, I would have pushed my changes. What I meant was that I don’t see a point in switching on signed and unsigned. Doing this for all cases would be equally effective without the complexity cost of parsing the payload sign.

**Comment by f-cozzocrea** [comment]
Ah okay, I see. I'll take a look later then. Have a good flight. :)

**Comment by Rexicon226** [comment]
This makes all of the cases I can think of work. 
```c
int x = -1;
void *p = (void *)x;
```

```c
void *p = (void *)-1;
```

```
void *p = (void *)(0-1);
```

**Comment by ehaas** [comment]
Does this work if you cast a larger unsigned integer to a pointer? e.g.
```c
void *p = (void *)0UL;
```
or
```c
unsigned long x = 0;
void *p = (void *)x;
```

(On a system where unsigned long is pointer-sized, e.g. linux or macos, not windows)

**Comment by f-cozzocrea** [comment]
@Rexicon226 FYI I have my own PR that I've been working on for my own issue (#18178) that would actually cover this use case as well. I think I can open the PR sometime this week.

**Comment by ehaas** [comment]
That's why you need separate paths for signed vs unsigned. If the source expression is unsigned, the existing code will work unaltered because `@ptrFromInt` will coerce the argument to `usize`. If the source expression is signed, you need to use `@as` to sign-extend it to `isize`, and then you can bitcast it to `usize`.

This is ignoring the case of a larger-than-pointer integer being converted to a pointer. *That* seems like more of an edge case; the behavior is implementation-defined so I would just ignore that case for now.

**Comment by Rexicon226** [comment]
> That's why you need separate paths for signed vs unsigned. If the source expression is unsigned, the existing code will work unaltered because `@ptrFromInt` will coerce the argument to `usize`. If the source expression is signed, you need to use `@as` to sign-extend it to `isize`, and then you can bitcast it to `usize`.
> 
> This is ignoring the case of a larger-than-pointer integer being converted to a pointer. _That_ seems like more of an edge case; the behavior is implementation-defined so I would just ignore that case for now.

Gotcha, gotcha. My hesitation comes from the challenge of correctly parsing the payload type. Maybe you can give some incite on this. Take for example 
```c
void *x = (void *)-1;
```
The `expr` here is `negate(int_literal)`. You would need to open it up. Now take `void( *)(0 - 1)`. Now you have something more complex that you need to coerce. 

There might be an obvious solution that I'm just missing, but actually understanding what the payload signess is seems very difficult.

**Comment by ehaas** [comment]
You don't need to parse anything, `expr` is already the translated expression to be casted. `src_type` is the type of the C expression being cast; `dst_type` is what it is casting to. The code you have already will work, it just needs to be inside a check for signed integers (and keep the existing code for unsigned integers)

**Comment by Rexicon226** [comment]
> You don't need to parse anything, `expr` is already the translated expression to be casted. `src_type` is the type of the C expression being cast; `dst_type` is what it is casting to. The code you have already will work, it just needs to be inside a check for signed integers (and keep the existing code for unsigned integers)

Ohhhhh, I understand now. I completely missed that parameter. Thanks for clarifying. Will push in a second.

**Comment by Rexicon226** [comment]
superseded by #18595

**Pull request closed without merging**
