### PR TITLE
std/crypto: scrypt update

### PR DESCRIPTION
**Pull request by x13a**
update docs
add fast kdf test
fix inconsistent kdf error
refactor

/cc @jedisct1

### CODE REVIEW

**Comment by jedisct1** [comment]
Unfortunately, even with the interactive parameters, that may be a little too much for CI.

**Comment by x13a** [comment]
Test with interactive params is disabled, I a little refactored it. There is a new kdf test with the lowest params possible.

```zig
test "kdf fast" {
    const TestVector = struct {
        password: []const u8,
        salt: []const u8,
        params: Params,
        want: []const u8,
    };
    const test_vectors = [_]TestVector{
        .{
            .password = "p",
            .salt = "s",
            .params = .{ .ln = 1, .r = 1, .p = 1 },
            .want = &([_]u8{
                0x48, 0xb0, 0xd2, 0xa8, 0xa3, 0x27, 0x26, 0x11,
                0x98, 0x4c, 0x50, 0xeb, 0xd6, 0x30, 0xaf, 0x52,
            }),
        },
    };
    inline for (test_vectors) |v| {
        var dk: [v.want.len]u8 = undefined;
        try kdf(std.testing.allocator, &dk, v.password, v.salt, v.params);
        try std.testing.expectEqualSlices(u8, &dk, v.want);
    }
}
```

I think this failure on azure is a bug in CI. Sometimes it is running to long with no reason.

**Comment by x13a** [comment]
@jedisct1 , all tests have passed. What do you think?

**Comment by jedisct1** [comment]
Looking great!

Thanks for documenting the parameters and for the test!

**Pull request merged**
