### PR TITLE
stage2: fn typeinfo params

### PR DESCRIPTION
**Pull request by Vexu**

### CODE REVIEW

**Comment by Vexu** [comment]
> can I ask you to hold off with merging

Will do.

**Comment by kubkon** [comment]
> > can I ask you to hold off with merging
> 
> Will do.

PR merged. Thanks for waiting!

**Comment by marler8997** [comment]
Curious on why the change from `Arg` to `Param`?

**Comment by andrewrk** [comment]
arguments are what you find at callsites; parameters are what you find at function definitions.

**Pull request merged**
