### PR TITLE
float related C ABI fixes

### PR DESCRIPTION
**Pull request by Vexu**
Trying to match what clang outputs while keeping the classification system similar to the documentation is somewhat difficult. I don't know how it'll be with the self-hosted backend but maybe it'd be better to just do our own thing?

### CODE REVIEW

**Comment by star-tek-mb** [comment]
I think C ABI errors still exist. I recompiled my code with new zig, and still getting same issues with ReleaseFast.

**Comment by Vexu** [comment]
What kind of issues?

**Comment by star-tek-mb** [comment]
https://github.com/star-tek-mb/runner-game
branch bug (should be default)
simple code not working with raylib
stack issues maybe.. i don't know

**Comment by Vexu** [comment]
Hmm, works for me on x86_64-linux. Assuming that you're on Windows the only relevant test seems to be `C function modifies by ref param`, I'll try fixing that.

**Comment by star-tek-mb** [comment]
yes. it is on windows

**Pull request merged**
