### PR TITLE
translate-c: deduplicate global declaration

### LINKED ISSUE #15456: translate-c: duplication of struct___va_list_tag definition
### Zig Version

0.11.0-dev.2822+d8bdfd819

### Steps to Reproduce and Observed Behavior

```
$ cat test.h

struct __va_list_tag {
        unsigned int gp_offset;
        unsigned int fp_offset;
        void *overflow_arg_area;
        void *reg_save_area;
};
typedef __builtin_va_list va_list;

$ zig translate-c -lc test.h

...
pub const struct___va_list_tag = extern struct {
    gp_offset: c_uint,
    fp_offset: c_uint,
    overflow_arg_area: ?*anyopaque,
    reg_save_area: ?*anyopaque,
};
pub const struct___va_list_tag = extern struct {
    gp_offset: c_uint,
    fp_offset: c_uint,
    overflow_arg_area: ?*anyopaque,
    reg_save_area: ?*anyopaque,
};
pub const __builtin_va_list = [1]struct___va_list_tag;
pub const va_list = __builtin_va_list;
...

```

Duplication of `struct___va_list_tag` definition.

### Expected Behavior

No duplication of same type.

### PR DESCRIPTION
**Pull request by tw4452852**
Fix #15456

### CODE REVIEW

**Comment by Vexu** [comment]
Could  you add a test case?

**Comment by tw4452852** [comment]
@Vexu Sure. But right now seems we don't have something like `expectNotContains` (only have `expectContains` right now), do you think we should add this one, or do you have any advice on checking duplication?

**Comment by tw4452852** [comment]
After checking, maybe we could put this case into `test_run_translated_c`, what do you think? @Vexu

**Comment by Vexu** [comment]
I forgot that the translate-c tests check for substrings, in that case this isn't important enough to necessitate new tests.

**Pull request merged**
