### PR TITLE
use open syscall when using an absolute path

### PR DESCRIPTION
**Pull request by I-mikan-I**
With these changes, opening files on linux using `openFileAbsolute` will translate to an `open` syscall instead of `openat`.

With how this is implemented, using `openFile` will also translate to open, when the path is absolute.
Since I am not sure if this was undesired or not, I implemented it in this way anyway. 
If only calls to `openFileAbsolute` should use `open`, we can add a new function, although some replication of boilerplate source code would probably be required.

Since this is my first PR, any feedback is very welcome :).

Closes: #10678

### CODE REVIEW

**Comment by I-mikan-I** [comment]
`openFileW` uses [ntdll](https://docs.microsoft.com/en-us/windows/win32/api/winternl/nf-winternl-ntcreatefile) and already sets the root directory attribute to `NULL` when an absolute file is passed: [snippet](https://github.com/ziglang/zig/blob/b90bfc8de673ea0ceb56184476bc29e42afbeaa7/lib/std/os/windows.zig#L91).

`openFileWasi` uses `path_open`, and I don't think there's an `open` equivalent.

**Comment by matu3ba** [comment]
@I-mikan-I Did you check the wasi sources? https://github.com/WebAssembly/WASI/blob/main/phases/snapshot/docs.md
I dont see anything beside `path_open`.

**Comment by ifreund** [comment]
I don't think there's a good reason for this complexity increase, at least not on linux. In the linux kernel implementation `open()` and `open_at(AT_FDCWD)` are 100% identical.
```c
SYSCALL_DEFINE3(open, const char __user *, filename, int, flags, umode_t, mode)
{
	if (force_o_largefile())
		flags |= O_LARGEFILE;

	return do_sys_open(AT_FDCWD, filename, flags, mode);
}

SYSCALL_DEFINE4(openat, int, dfd, const char __user *, filename, int, flags,
		umode_t, mode)
{
	if (force_o_largefile())
		flags |= O_LARGEFILE;

	return do_sys_open(dfd, filename, flags, mode);
}
```

**Comment by I-mikan-I** [comment]
Since I could not reproduce the original issue when trying out a different approach, I will convert this PR to a draft.

I don't believe the issue is caused by using `openat`, and perhaps we need to do some more testing to identify the cause.  
Has anyone else encountered this issue before?

**Comment by Vexu** [comment]
> Since I could not reproduce the original issue when trying out a different approach, I will convert this PR to a draft.
> 
> I don't believe the issue is caused by using `openat`, and perhaps we need to do some more testing to identify the cause. Has anyone else encountered this issue before?

Let's keep the discussion in the relevant issue and leave the pull request queue for changes that are ready to be merged.

**Pull request closed without merging**
