### PR TITLE
Don't use SSE on freestanding

### PR DESCRIPTION
**Pull request by pixelherodev**
A better solution might be to have an option to disable/enable SSE/SIMD within the current scope, but this at least results in functional code.

### CODE REVIEW

**Comment by LemonBoy** [comment]
Ideally `-mllvm -mattr=-sse` should work too.

**Comment by andrewrk** [comment]
I think it's time to prioritize #2883

**Comment by andrewrk** [comment]
@pixelherodev can you do the equivalent changes here? 

These are for flags passed to C:

**Comment by andrewrk** [comment]
done in f2d0d9820d9b20ddc61866d5fe2575cf80f4d9be

**Pull request merged**
