### PR TITLE
langref: Mention that FixedBufferAllocator is a bump allocator

### PR DESCRIPTION
**Pull request by iamkroot**
Some open questions for the maintainers-
- [ ] Should we put a link to some article describing what a Bump allocator is?
- [ ] Not sure if there are other places to mention this. The docstrings on `FixedBufferAllocator` would be an obvious choice, but they are non-existent currently :P I am not sure of the procedure to add these

I will be happy to take suggestions on improving the choice of words here.

### CODE REVIEW

**Comment by jedisct1** [comment]
Indeed, `FixedBufferAllocator` is not a very self-descriptive name.

The best place to document it would be with a comment just [above its definition](https://github.com/ziglang/zig/blob/2fce991d2ab1dfc6d591b560607ef0edecc7db19/lib/std/heap.zig#L365), so that autodoc automatically picks it up.

**Comment by jedisct1** [comment]
It "bump allocator" the proper way to describe a stack based allocator ?

Looks to me that "bump allocator" is just a funny name invented by a Rust crate, not a generic term for it.

**Comment by iamkroot** [comment]
> Looks to me that "bump allocator" is just a funny name invented by a Rust crate, not a generic term for it.

Well, LLVM has had a similarly named class [since 2006](https://github.com/llvm/llvm-project/blob/b9de90377fcf06aff449ba89b7d6aee8f2f68c4a/llvm/include/llvm/Support/Allocator.h#L31) at least :)

**Comment by andrewrk** [comment]
The language reference is not the correct place for this. Instead the standard library type name should be renamed.

**Pull request closed without merging**
