### PR TITLE
crypto/benchmark - replace testing allocator

### PR DESCRIPTION
**Pull request by kassane**
Recently in my latest tests there has been an error with "testing.allocator".

```bash
error: Cannot use testing allocator outside of test block
        @compileError("Cannot use testing allocator outside of test block");
```

cc: @jedisct1

### CODE REVIEW

**Comment by jedisct1** [comment]
Why not use the GPA?

**Comment by kassane** [comment]
> Why not use the GPA?

GPA does not affect performance?

**Review by andrewrk — CHANGES_REQUESTED** [review]
main() sets up an allocator; this one should be used for everything. If you don't want to use the fixed buffer allocator then use the pattern of arena wrapping page:

https://github.com/ziglang/zig/blob/3e2defd36c0bf90a0604a7618f57beaa4077139c/lib/build_runner.zig#L13-L17

**Comment by jedisct1** [comment]
The function benchmarks `scrypt` and `argon2`. Both intentionally require *a lot* of memory. With a fixed buffer, they are likely to immediately return with an error, and I doubt the benchmark result is relevant.

**Comment by kassane** [comment]
> The function benchmarks `scrypt` and `argon2`. Both intentionally require _a lot_ of memory. With a fixed buffer, they are likely to immediately return with an error, and I doubt the benchmark result is relevant.

changed to arena.

**Comment by kassane** [comment]
Found another error when trying to use stage2 during the build.

Returning this error:
```bash
benchmark.zig:186:39: error: cannot load runtime value in comptime block
            try Signature.verifyBatch(batch.len, batch);
```
I tried to make `comptime var batch`, however a runtime problem occurs with `error: weakPublicKey` on stage1.

And returning this error on stage2:
```bash
~/.local/lib/zig/std/crypto/scrypt.zig:465:47: error: cannot load runtime value in comptime block
        const salt = crypt_format.saltFromBin(salt_bin.len, salt_bin);
```

**Comment by jedisct1** [comment]
Looks like a regression. `batch.len` should be (and used to be) known at comptime.

**Comment by ominitay** [comment]
#12240

**Pull request merged**
