### PR TITLE
CI: additionally test x86_64-macos with a debug build of the zig compiler

### PR DESCRIPTION
**Pull request by andrewrk**

### CODE REVIEW

**Comment by andrewrk** [comment]
I'm not sure what is the cause of this:
```
zig: error: overriding '-mmacosx-version-min=11.7' option with '-target x86_64-unknown-macosx11.7.1-unknown' [-Werror,-Woverriding-t-option]
zig: error: overriding '-mmacosx-version-min=11.7' option with '-target x86_64-unknown-macosx11.7.1-unknown' [-Werror,-Woverriding-t-option]
```

**Comment by matu3ba** [comment]
This seems to be a known issue https://forum.dlang.org/thread/qvcap8$8cj$1@digitalmars.com more elaborated here https://gitlab.kitware.com/cmake/cmake/-/issues/20132, but from the issue I dont understand if later cmake versions are still affected or not.

**Comment by andrewrk** [comment]
I think the fix here is for zig to explicitly decide to omit the `-mmacosx-version-min=11.7` flag when it knows it will be passing a `-target` parameter, which will instead encode this version information.

**Comment by kubkon** [comment]
The funny thing is, this doesn't happen for me locally on macOS 13.

**Comment by matu3ba** [comment]
#13795 but with compilation errors fixed. standalone and lib tests looked like they were passing on VM.

**Comment by mikdusan** [comment]
> The funny thing is, this doesn't happen for me locally on macOS 13.

Perhaps the github runner top level env is setting `MACOSX_DEPLOYMENT_TARGET` ? This leads to `-mmacosx-version-min=11.7` being present when building zig on macOS 13 for me:
```sh
MACOSX_DEPLOYMENT_TARGET=11.7 cmake ...
```

**Pull request merged**
