### PR TITLE
Add stage2 AArch64 backend

### PR DESCRIPTION
**Pull request by joachimschmidt557**
The goal of this PR is getting "Hello World" working on the AArch64 (A64) backend for the stage2 zig compiler.

As always, I'll create this as a draft pull request so people can provide incremental feedback.

TODO:

- [x] genSetReg
- [x] genAsm
- [x] genCall
- [x] ret
- [x] genBreakpoint
- [x] Hello World test

### CODE REVIEW

**Comment by andrewrk** [comment]
It's exciting to see this coming together + @kubkon's macho linking code :)

**Comment by kubkon** [comment]
> It's exciting to see this coming together + @kubkon's macho linking code :)

I'll make it even scarier. We're joining forces on this one!

**Comment by kubkon** [comment]
Before we merge this one, we should investigate why the test crashes on aarch64 Linux.

**Comment by kubkon** [comment]
All is green; great work @joachimschmidt557!

**Pull request merged**
