### PR TITLE
zig2: [mingw] allocate enough memory when building zig2

### PR DESCRIPTION
**Pull request by raedrizqie**

### CODE REVIEW

**Comment by andrewrk** [comment]
Thank you

**Comment by raedrizqie** [comment]
```
[18/20] Linking CXX executable zig2.exe
FAILED: zig2.exe 
C:\Windows\system32\cmd.exe /C "cd . && C:\Users\ci\zig+llvm+lld+clang-x86_64-windows-gnu-0.13.0-dev.130+98a30acad\bin\zig.exe c++ -target x86_64-windows-gnu -mcpu=baseline -O3 -DNDEBUG -Wl,--stack,0x10000000 -Wl,--large-address-aware @CMakeFiles\zig2.rsp -o zig2.exe -Wl,--out-implib,libzig2.dll.a -Wl,--major-image-version,0,--minor-image-version,0 && cd ."
```
ah.. zig was used to build zig2..

**Comment by raedrizqie** [comment]
thanks!

**Comment by alexrp** [comment]
@raedrizqie @andrewrk what was this actually fixing? `--maxrss` defaults to the total system memory. We don't pass `--maxrss` explicitly anywhere in the build system, only in the Linux CI scripts. Also `ZIG_BUILD_ARGS` is used when invoking `zig2` to build `zig3`. Fairly confused about this one.

**Comment by raedrizqie** [comment]
@alexrp It was added for building zig without bootstrap for MSYS2 UCRT 32-bit system not long ago. Now, MSYS2 has drop 32-bit UCRT system on their repo, it is safe to revert this commit. Thank you.

**Pull request merged**
